Repository Homebrew/linuxbrew-core, pull requests merged in 2018-12, with the labels that each got.

#10445 Merge 2018-12-01 87c4c4e7f1
  Formula/docfx.rb
  Formula/exploitdb.rb
  Formula/minio.rb
  Formula/percona-server.rb
  Formula/ppsspp.rb
  Formula/rebar3.rb
  Formula/rtags.rb
Labels: merge

#10448 Merge 2018-12-01 a94389162a
  Formula/openssl@1.1.rb
Labels: merge

#10450 Merge 2018-12-01 cabc9f8bdd
  Formula/ghostscript.rb
  Formula/latex2html.rb
  Formula/libspectre.rb
  Formula/octave.rb
  Formula/pqiv.rb
  Formula/ps2eps.rb
Labels: merge

#10454 Merge 2018-12-02 1e09030fe5
  Formula/openblas.rb
  Formula/qalculate-gtk.rb
Labels: merge

#10456 Merge 2018-12-02 9e854aca60
  Formula/curl-openssl.rb
  Formula/php.rb
Labels: merge

#10459 Merge 2018-12-02 ec8d29c092
  Formula/boot-clj.rb
  Formula/cabal-install.rb
  Formula/cpanminus.rb
  Formula/igraph.rb
  Formula/jenkins.rb
  Formula/le.rb
  Formula/openal-soft.rb
  Formula/parallel.rb
  Formula/pipenv.rb
  Formula/prometheus.rb
  Formula/redsocks.rb
  Formula/webpack.rb
Labels: merge

#10468 Merge 2018-12-03 edf393eb25
  Formula/php@7.1.rb
Labels: merge

#10469 Merge 2018-12-03 21b786f7b3
  Formula/php@5.6.rb
  Formula/php@7.0.rb
  Formula/php@7.1.rb
Labels: merge

#10476 Merge 2018-12-03 658be387e2
  Formula/ansible-cmdb.rb
  Formula/easyengine.rb
  Formula/faas-cli.rb
  Formula/nginx.rb
  Formula/node.rb
  Formula/pandoc.rb
  Formula/sourcekitten.rb
  Formula/swift.rb
  Formula/swiftlint.rb
  Formula/vaulted.rb
  Formula/zsh-autosuggestions.rb
Labels: merge

#10376 autoconf & automake: Depend on perl
  Formula/autoconf.rb
Labels: do-not-merge

#10487 Merge 2018-12-03 a3da894460
  Formula/python.rb
  Formula/python@2.rb
Labels: merge

#10501 Merge 2018-12-04 1d4f1d5602
  Formula/python.rb
Labels: merge

#10502 Merge 2018-12-05 5dd5220643
  Formula/amqp-cpp.rb
  Formula/cmake.rb
  Formula/docfx.rb
  Formula/docker-compose-completion.rb
  Formula/docker-compose.rb
  Formula/ethereum.rb
  Formula/frugal.rb
  Formula/golang-migrate.rb
  Formula/hugo.rb
  Formula/libextractor.rb
  Formula/macvim.rb
  Formula/mesa.rb
  Formula/mongodb@3.4.rb
  Formula/mongodb@3.6.rb
  Formula/node-build.rb
  Formula/pulumi.rb
  Formula/rancher-cli.rb
  Formula/rke.rb
  Formula/rom-tools.rb
  Formula/rustup-init.rb
  Formula/sbt@0.13.rb
  Formula/smimesign.rb
  Formula/swiftformat.rb
  Formula/vim.rb
  Formula/xmake.rb
Labels: merge

#10516 Merge 2018-12-05 10a7080610
  Formula/docker-machine-driver-xhyve.rb
  Formula/exploitdb.rb
  Formula/fn.rb
  Formula/helmfile.rb
  Formula/juju.rb
  Formula/mpc.rb
  Formula/pijul.rb
  Formula/vert.x.rb
  Formula/vsts-cli.rb
Labels: merge

#10523 Merge 2018-12-05 681c59ce65
  Formula/chakra.rb
  Formula/couchdb.rb
  Formula/dwdiff.rb
  Formula/freeciv.rb
  Formula/freeling.rb
  Formula/gjs.rb
  Formula/harfbuzz.rb
  Formula/hfstospell.rb
  Formula/icu4c.rb
  Formula/libcdr.rb
  Formula/libfreehand.rb
  Formula/libical.rb
  Formula/liblcf.rb
  Formula/libmspub.rb
  Formula/libphonenumber.rb
  Formula/libpqxx.rb
  Formula/libvisio.rb
  Formula/mimic.rb
  Formula/mpd.rb
  Formula/node.rb
  Formula/node@10.rb
  Formula/node@8.rb
  Formula/openrct2.rb
  Formula/pazpar2.rb
  Formula/php.rb
  Formula/php@5.6.rb
  Formula/php@7.0.rb
  Formula/php@7.1.rb
  Formula/planck.rb
  Formula/postgresql.rb
  Formula/sile.rb
  Formula/tarantool.rb
  Formula/tectonic.rb
  Formula/widelands.rb
  Formula/yaz.rb
  Formula/zebra.rb
  Formula/zorba.rb
Labels: merge

#10538 Merge 2018-12-05 8816a2b200
  Aliases/gradle@5
  Formula/apache-flink.rb
  Formula/bazel.rb
  Formula/binwalk.rb
  Formula/checkstyle.rb
  Formula/ckan.rb
  Formula/easyengine.rb
  Formula/erlang.rb
  Formula/fping.rb
  Formula/git-quick-stats.rb
  Formula/gradle.rb
  Formula/hstr.rb
  Formula/i386-elf-gdb.rb
  Formula/kobalt.rb
  Formula/lean-cli.rb
  Formula/lighttpd.rb
  Formula/mapnik.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/node@10.rb
  Formula/opa.rb
  Formula/pict.rb
  Formula/platformio.rb
  Formula/stockfish.rb
  Formula/up.rb
  Formula/websocat.rb
  Formula/wget.rb
  Formula/xhyve.rb
  formula_renames.json
Labels: merge

#10544 Merge 2018-12-05 80565ea779
  Formula/ansible.rb
  Formula/archey.rb
  Formula/duo_unix.rb
  Formula/lmod.rb
  Formula/minica.rb
  Formula/mmseqs2.rb
  Formula/skaffold.rb
  Formula/snapcraft.rb
Labels: merge

#10545 Merge 2018-12-06 3da44d9fc2
  Formula/aws-sdk-cpp.rb
  Formula/exploitdb.rb
  Formula/fn.rb
  Formula/fonttools.rb
  Formula/goreleaser.rb
  Formula/harfbuzz.rb
  Formula/ipython.rb
  Formula/jenkins-lts.rb
  Formula/librealsense.rb
  Formula/mkl-dnn.rb
  Formula/osm2pgrouting.rb
  Formula/passenger.rb
  Formula/percona-server@5.6.rb
  Formula/pqiv.rb
  Formula/prettier.rb
  Formula/pyenv-ccache.rb
  Formula/pyenv-pip-migrate.rb
  Formula/pyenv-virtualenvwrapper.rb
  Formula/pyenv-which-ext.rb
  Formula/sng.rb
  Formula/swagger-codegen.rb
  Formula/swiftlint.rb
  Formula/thefuck.rb
  Formula/typescript.rb
  Formula/wine.rb
  Formula/wireshark.rb
Labels: merge

#10555 Merge 2018-12-06 f84e3560b5
  Formula/afsctool.rb
  Formula/angular-cli.rb
  Formula/aptly-completion.rb
  Formula/aptly.rb
  Formula/bazel.rb
  Formula/bgpq3.rb
  Formula/c-blosc.rb
  Formula/digdag.rb
  Formula/expat.rb
  Formula/fn.rb
  Formula/ibex.rb
  Formula/ike-scan.rb
  Formula/jshon.rb
  Formula/libplctag.rb
  Formula/libxslt.rb
  Formula/meson-internal.rb
  Formula/node@8.rb
  Formula/nss.rb
  Formula/openapi-generator.rb
  Formula/pygobject3.rb
  Formula/re2.rb
  Formula/ruby.rb
  Formula/sbt.rb
  Formula/sqlcipher.rb
  Formula/swagger-codegen.rb
  Formula/u-boot-tools.rb
  Formula/unicorn.rb
Labels: merge

#10565 Merge 2018-12-06 9e6ba61dd5
  Formula/activemq.rb
  Formula/allure.rb
  Formula/apache-arrow-glib.rb
  Formula/asciidoctor.rb
  Formula/circleci.rb
  Formula/cmark-gfm.rb
  Formula/cmark.rb
  Formula/dbhash.rb
  Formula/dialog.rb
  Formula/exploitdb.rb
  Formula/flume.rb
  Formula/flyway.rb
  Formula/kafka.rb
  Formula/libpqxx.rb
  Formula/lolcat.rb
  Formula/luit.rb
  Formula/maxwell.rb
  Formula/neo4j.rb
  Formula/openimageio.rb
  Formula/paket.rb
  Formula/postgresql.rb
  Formula/quicktype.rb
  Formula/rargs.rb
  Formula/sdl2.rb
  Formula/sqldiff.rb
  Formula/sqlite-analyzer.rb
  Formula/sqlite.rb
  Formula/theharvester.rb
  Formula/wget.rb
  Formula/you-get.rb
  Formula/youtube-dl.rb
Labels: merge

#10583 Merge 2018-12-06 50856e78fc
  Aliases/v8@7.1
  Formula/analog.rb
  Formula/azure-cli.rb
  Formula/binaryen.rb
  Formula/conan.rb
  Formula/django-completion.rb
  Formula/easyengine.rb
  Formula/exploitdb.rb
  Formula/fn.rb
  Formula/fswatch.rb
  Formula/fwup.rb
  Formula/git-lfs.rb
  Formula/grails.rb
  Formula/kubernetes-cli.rb
  Formula/kustomize.rb
  Formula/libgda.rb
  Formula/mercurial.rb
  Formula/percona-server.rb
  Formula/smimesign.rb
  Formula/spotbugs.rb
  Formula/syncthing.rb
  Formula/taskell.rb
  Formula/tomcat-native.rb
  Formula/traefik.rb
  Formula/twoping.rb
  Formula/v8.rb
  Formula/winetricks.rb
Labels: merge

#10601 Merge 2018-12-06 85f274e9e7
  Formula/binaryen.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/ompl.rb
  Formula/sonobuoy.rb
  Formula/tbb.rb
Labels: merge

#10602 Merge 2018-12-07 fe96795085
  Formula/apachetop.rb
  Formula/cargo-completion.rb
  Formula/dita-ot.rb
  Formula/pulumi.rb
  Formula/taskell.rb
Labels: merge

#10605 Merge 2018-12-09 e04b6ba4ae
  Formula/gcc@7.rb
Labels: merge

#10607 Merge 2018-12-09 c28c7d1da9
  Formula/mutt.rb
  Formula/pyenv.rb
  Formula/qt.rb
  Formula/ruby-build.rb
Labels: merge

#10610 Merge 2018-12-09 abb422da5d
  Formula/curl.rb
Labels: merge

#10612 Merge 2018-12-09 5b7ad5c180
  Formula/dbus.rb
  Formula/imagemagick.rb
  Formula/shellcheck.rb
Labels: merge

#10616 Merge 2018-12-09 6c678cf5c0
  Aliases/postgresql@11
  Formula/ansible.rb
  Formula/citus.rb
  Formula/libpqxx.rb
  Formula/nettle.rb
  Formula/pgroonga.rb
  Formula/pgrouting.rb
  Formula/pldebugger.rb
  Formula/postgis.rb
  Formula/postgresql.rb
  Formula/qrupdate.rb
  Formula/temporal_tables.rb
Labels: merge

#10621 Merge 2018-12-09 a5639713fb
  Formula/arcade-learning-environment.rb
  Formula/astrometry-net.rb
  Formula/aubio.rb
  Formula/gnuradio.rb
  Formula/graph-tool.rb
  Formula/numpy.rb
  Formula/nwchem.rb
  Formula/openblas.rb
  Formula/opencv.rb
  Formula/opencv@2.rb
  Formula/scipy.rb
  Formula/urh.rb
Labels: merge

#10627 Merge 2018-12-10 59f6f8ea73
  Formula/pandoc-crossref.rb
Labels: merge

#10629 Merge 2018-12-10 c0a4206361
  Formula/gcc.rb
Labels: merge

#10630 Merge 2018-12-11 dcf043b2c8
  Formula/gcc@6.rb
Labels: merge

#10633 Merge 2018-12-11 20961a94db
  Formula/elasticsearch.rb
  Formula/fx.rb
  Formula/kibana.rb
  Formula/knot-resolver.rb
  Formula/logstash.rb
  Formula/nss.rb
  Formula/stunnel.rb
Labels: merge

#10634 Merge 2018-12-11 b94effb875
  Formula/shibboleth-sp.rb
  Formula/xml-security-c.rb
  Formula/xml-tooling-c.rb
Labels: merge

#10637 Merge 2018-12-11 bcd5ae835b
  Formula/eslint.rb
  Formula/kubernetes-helm.rb
  Formula/osrm-backend.rb
  Formula/pgweb.rb
  Formula/shfmt.rb
  Formula/sqliteodbc.rb
Labels: merge

#10638 Merge 2018-12-11 a16681dd13
  Formula/alure.rb
  Formula/ne.rb
  Formula/orocos-kdl.rb
  Formula/pgtune.rb
  Formula/skktools.rb
  Formula/xmlformat.rb
  Formula/zsync.rb
Labels: merge

#10642 Merge 2018-12-11 16b8dd3d8c
  Formula/diff-pdf.rb
  Formula/doctl.rb
  Formula/pdftoedn.rb
  Formula/pdftoipe.rb
  Formula/poppler.rb
Labels: merge

#10643 Merge 2018-12-12 d6d6b792c7
  Formula/dub.rb
  Formula/erlang@20.rb
  Formula/fn.rb
  Formula/grpc.rb
  Formula/kotlin.rb
  Formula/packer.rb
  Formula/vips.rb
Labels: merge

#10647 Merge 2018-12-13 cbf014d0ac
  Formula/bundletool.rb
  Formula/doctl.rb
  Formula/git-standup.rb
  Formula/git.rb
  Formula/libbladerf.rb
  Formula/libosmium.rb
  Formula/libphonenumber.rb
Labels: merge

#10650 Merge 2018-12-13 8bdd400cde
  Formula/aircrack-ng.rb
  Formula/checkbashisms.rb
  Formula/generate-json-schema.rb
  Formula/jenkins.rb
  Formula/libressl.rb
  Formula/nativefier.rb
  Formula/openssl@1.1.rb
  Formula/pandoc-citeproc.rb
  Formula/postgresql@10.rb
  Formula/wtf.rb
Labels: merge

#10654 Merge 2018-12-13 89bff3c60d
  Formula/healpix.rb
  Formula/imagemagick.rb
  Formula/mycli.rb
  Formula/nghttp2.rb
  Formula/typescript.rb
  Formula/webpack.rb
Labels: merge

#10655 Merge 2018-12-13 f5dbb70077
  Formula/alexjs.rb
  Formula/cockroach.rb
  Formula/fx.rb
  Formula/gitlab-runner.rb
  Formula/nmh.rb
  Formula/node.rb
  tap_migrations.json
Labels: merge

#10656 Merge 2018-12-14 7f26bd6d47
  Formula/erlang.rb
  Formula/exploitdb.rb
  Formula/fn.rb
  Formula/grafana.rb
  Formula/hub.rb
  Formula/oniguruma.rb
Labels: merge

#10657 Merge 2018-12-14 93b3c142fb
  Formula/bitrise.rb
  Formula/blink1.rb
  Formula/certbot.rb
  Formula/cp2k.rb
  Formula/libtins.rb
  Formula/media-info.rb
  Formula/rustup-init.rb
Labels: merge

#10658 Merge 2018-12-14 179b155259
  Formula/ammonite-repl.rb
  Formula/convox.rb
  Formula/dnscontrol.rb
  Formula/docker-machine-nfs.rb
  Formula/elasticsearch@5.6.rb
  Formula/frugal.rb
  Formula/goreman.rb
  Formula/libatomic_ops.rb
  Formula/opa.rb
  Formula/osmium-tool.rb
  Formula/phpmyadmin.rb
  Formula/phpunit.rb
  Formula/plplot.rb
  Formula/qbs.rb
  Formula/skinny.rb
  Formula/ucloud.rb
Labels: merge

#10664 Merge 2018-12-14 7279f0f4e7
  Formula/agda.rb
  Formula/apache-geode.rb
  Formula/bcal.rb
  Formula/chronograf.rb
  Formula/curl.rb
  Formula/docker.rb
  Formula/gupnp-tools.rb
  Formula/helmfile.rb
  Formula/hyperfine.rb
  Formula/influxdb.rb
  Formula/leiningen.rb
  Formula/lxc.rb
  Formula/macvim.rb
  Formula/mesa.rb
  Formula/mosquitto.rb
  Formula/mutt.rb
  Formula/platformio.rb
  Formula/plplot.rb
  Formula/pumba.rb
  Formula/redis.rb
  Formula/source-to-image.rb
  Formula/telegraf.rb
  Formula/topgrade.rb
Labels: merge

#10681 Merge 2018-12-14 8342f31e28
  Formula/ballerina.rb
  Formula/binaryen.rb
  Formula/brew-php-switcher.rb
  Formula/easyengine.rb
  Formula/kapacitor.rb
  Formula/nvm.rb
  Formula/riemann-client.rb
Labels: merge

#10682 Merge 2018-12-15 77b55956a4
  Formula/conan.rb
  Formula/ethereum.rb
  Formula/exploitdb.rb
  Formula/kibana.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/opam.rb
Labels: merge

#10683 Merge 2018-12-15 e2f8e3e74e
  Formula/cmake.rb
  Formula/freetds.rb
  Formula/geos.rb
  Formula/node@10.rb
  Formula/nuxeo.rb
  Formula/qemu.rb
  Formula/swiftformat.rb
  Formula/tinyproxy.rb
  Formula/wtf.rb
Labels: merge

#10684 Merge 2018-12-15 5aa95855c4
  Formula/create-dmg.rb
  Formula/fauna-shell.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/goenv.rb
  Formula/kubernetes-cli.rb
Labels: merge

#10686 Merge 2018-12-15 b3cd6eeb47
  Formula/ansible.rb
  Formula/basex.rb
  Formula/clblast.rb
  Formula/gmsh.rb
  Formula/goreleaser.rb
  Formula/gradle@2.14.rb
  Formula/stellar-core.rb
  Formula/tomee-webprofile.rb
  Formula/xsimd.rb
Labels: merge

#10688 Merge 2018-12-16 94627e0e27
  Formula/amazon-ecs-cli.rb
  Formula/chakra.rb
  Formula/grafana.rb
  Formula/grpc.rb
  Formula/libjwt.rb
  Formula/parallelstl.rb
  Formula/stress-ng.rb
  Formula/weaver.rb
Labels: merge

#10692 Merge 2018-12-16 9edaa5115c
  Formula/angular-cli.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/swiftformat.rb
  Formula/when.rb
Labels: merge

#10695 Merge 2018-12-16 db575c1bdf
  Formula/bigloo.rb
  Formula/flyway.rb
  Formula/git.rb
  Formula/libxmlsec1.rb
  Formula/pngquant.rb
  Formula/tox.rb
Labels: merge

#10697 Merge 2018-12-16 5075bdd22b
  Aliases/solr@7.6
  Formula/binaryen.rb
  Formula/cython.rb
  Formula/fx.rb
  Formula/go@1.10.rb
  Formula/solr.rb
  Formula/wolfssl.rb
Labels: merge

#10698 Merge 2018-12-16 fd1c0ba8f1
  Formula/grpc.rb
  Formula/leiningen.rb
Labels: merge

#10690 grpc: Build a bottle for Linuxbrew
  Formula/grpc.rb
Labels: bottle, test-failure

#10699 Merge 2018-12-16 40c0446e4d
  Formula/gobject-introspection.rb
  Formula/gtk+3.rb
Labels: merge

#10701 Merge 2018-12-17 7de8bd0af7
  Formula/gtkmm3.rb
  Formula/libdazzle.rb
  Formula/openfortivpn.rb
  Formula/traefik.rb
  Formula/vim.rb
  Formula/zola.rb
Labels: merge

#10704 Merge 2018-12-17 a641a163af
  Formula/aws-sdk-cpp.rb
  Formula/binaryen.rb
  Formula/chronograf.rb
  Formula/libedit.rb
  Formula/pulumi.rb
Labels: merge

#10705 Merge 2018-12-17 e3e476db6d
  Formula/angle-grinder.rb
  Formula/bind.rb
  Formula/catimg.rb
  Formula/pixman.rb
  Formula/terraforming.rb
  cmd/brew-postgresql-upgrade-database.rb
Labels: merge

#10706 Merge 2018-12-17 eb30844709
  Formula/curl-openssl.rb
  Formula/exploitdb.rb
  Formula/libpst.rb
  Formula/librsvg.rb
  Formula/libuv.rb
  Formula/octave.rb
  Formula/presto.rb
  Formula/sundials.rb
  Formula/vte3.rb
  Formula/youtube-dl.rb
Labels: merge

#10709 Merge 2018-12-18 48d8b58d97
  Formula/cabextract.rb
  Formula/citus.rb
  Formula/haproxy.rb
  Formula/immortal.rb
  Formula/sundials.rb
Labels: merge

#10710 Merge 2018-12-18 a1dd66ec92
  Formula/circleci.rb
  Formula/git.rb
  Formula/imagemagick.rb
  Formula/interactive-rebase-tool.rb
  Formula/sysbench.rb
  Formula/terraform.rb
Labels: merge

#10714 Merge 2018-12-18 2eb0adf3d1
  Formula/daemontools.rb
  Formula/swiftformat.rb
  Formula/xtensor.rb
Labels: merge

#10715 Merge 2018-12-18 baef94a516
  Formula/click.rb
  Formula/dependency-check.rb
  Formula/mint.rb
  Formula/mruby.rb
  Formula/pdftoedn.rb
  Formula/vert.x.rb
  Formula/zim.rb
Labels: merge

#10716 Merge 2018-12-19 bd87e5ab95
  Formula/gnupg.rb
  Formula/gocryptfs.rb
  Formula/icemon.rb
  Formula/libassuan.rb
  Formula/libgpg-error.rb
  Formula/openmsx.rb
Labels: merge

#10717 Merge 2018-12-19 3259d20004
  Formula/ceres-solver.rb
  Formula/cockroach.rb
  Formula/eigen.rb
  Formula/graph-tool.rb
  Formula/jenkins.rb
  Formula/mkvtoolnix.rb
Labels: merge

#10719 Merge 2018-12-19 90b9037c5a
  Formula/clojure.rb
  Formula/conan.rb
  Formula/fonttools.rb
  Formula/gstreamermm.rb
  Formula/kubeless.rb
  Formula/picard-tools.rb
  Formula/qpid-proton.rb
Labels: merge

#10722 Merge 2018-12-19 a4ff12244b
  Formula/erlang@17.rb
  Formula/erlang@18.rb
  Formula/erlang@19.rb
Labels: merge

#10723 Merge 2018-12-19 04ce80b163
  Formula/gcc@4.9.rb
  Formula/gcc@5.rb
Labels: merge

#10724 Merge 2018-12-19 d0c7f13d40
  Formula/gnupg@1.4.rb
  Formula/gnuplot@4.rb
  Formula/go@1.4.rb
  Formula/hdf5@1.8.rb
  Formula/lua@5.1.rb
Labels: merge

#10725 Merge 2018-12-19 ef35619973
  Formula/mongodb@3.0.rb
  Formula/mongodb@3.2.rb
  Formula/mongodb@3.4.rb
  Formula/mongodb@3.6.rb
  Formula/opencv@2.rb
Labels: merge

#10726 Merge 2018-12-19 5fdac10b56
  Formula/perl@5.18.rb
  Formula/postgresql@10.rb
  Formula/postgresql@9.4.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
  Formula/protobuf@2.5.rb
  Formula/protobuf@2.6.rb
  Formula/protobuf@3.1.rb
  Formula/redis@3.2.rb
  Formula/subversion@1.8.rb
  Formula/thrift@0.9.rb
Labels: merge

#10727 Merge 2018-12-19 6f546acb03
  Formula/audiofile.rb
  Formula/makensis.rb
  Formula/openssl.rb
  Formula/openssl@1.1.rb
  Formula/you-get.rb
Labels: merge

#10738 Merge 2018-12-20 d1edb66535
  Formula/bullet.rb
  Formula/gdb.rb
  Formula/libarchive.rb
  Formula/lighttpd.rb
  Formula/mapserver.rb
  Formula/qemu.rb
  Formula/swiftformat.rb
  Formula/thrift.rb
  Formula/xcodegen.rb
  Formula/znc.rb
Labels: merge

#10744 Merge 2018-12-20 df78b99e32
  Formula/ansifilter.rb
  Formula/highlight.rb
  Formula/libpng.rb
  Formula/mkvtoolnix.rb
  Formula/sbcl.rb
  Formula/scipy.rb
Labels: merge

#10749 Merge 2018-12-20 76a7b8d3ce
  Formula/exploitdb.rb
  Formula/goenv.rb
  Formula/libressl.rb
  Formula/node.rb
  Formula/node@8.rb
  Formula/wp-cli.rb
Labels: merge

#10750 Merge 2018-12-20 a6a6f9c111
  Formula/docfx.rb
  Formula/jsonnet.rb
  Formula/logtalk.rb
  Formula/spotbugs.rb
  Formula/sqlcipher.rb
  Formula/tippecanoe.rb
Labels: merge

#10751 Merge 2018-12-20 ba68405367
  Formula/go-bindata.rb
  Formula/jboss-forge.rb
  Formula/libvmaf.rb
  Formula/node-build.rb
  Formula/rke.rb
Labels: merge

#10752 Merge 2018-12-20 90e6931235
  Formula/caffe.rb
  Formula/ffmbc.rb
  Formula/ffmpeg.rb
  Formula/ffmpeg2theora.rb
  Formula/ffmpeg@2.8.rb
  Formula/ffmpegthumbnailer.rb
  Formula/ffms2.rb
  Formula/gst-plugins-ugly.rb
  Formula/libav.rb
  Formula/opencv.rb
  Formula/qmmp.rb
  Formula/x264.rb
Labels: merge

#10756 Merge 2018-12-21 0a1055eea4
  Formula/annie.rb
  Formula/bison.rb
  Formula/blackbox.rb
  Formula/citus.rb
  Formula/conan.rb
  Formula/docfx.rb
  Formula/embulk.rb
  Formula/exploitdb.rb
  Formula/fluxctl.rb
  Formula/gnu-sed.rb
  Formula/graphite2.rb
  Formula/jsonnet.rb
  Formula/kubernetes-helm.rb
  Formula/libcouchbase.rb
  Formula/mas.rb
  Formula/micronaut.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/nsd.rb
  Formula/paket.rb
  Formula/pdfpc.rb
  Formula/percona-server.rb
  Formula/prometheus.rb
  Formula/skopeo.rb
  Formula/zsh-completions.rb
Labels: merge

#10781 Merge 2018-12-21 8d0d13e425
  Formula/babel.rb
  Formula/dnscontrol.rb
  Formula/figlet.rb
  Formula/gauche.rb
  Formula/gdal.rb
  Formula/harfbuzz.rb
  Formula/jhipster.rb
  Formula/libcerf.rb
Labels: merge

#10785 Merge 2018-12-22 72b5d1a59a
  Formula/gnu-sed.rb
  Formula/grep.rb
  Formula/parallel.rb
  Formula/pass-otp.rb
  Formula/skaffold.rb
  Formula/terragrunt.rb
Labels: merge

#10788 Merge 2018-12-22 9a7a936736
  Formula/osrm-backend.rb
  Formula/pass-otp.rb
  Formula/yle-dl.rb
Labels: merge

#10789 Merge 2018-12-23 4e21ee4c53
  Formula/gnutls.rb
  Formula/wireguard-go.rb
Labels: merge

#10110 Make Emacs depend on libxml2
  Formula/emacs.rb
Labels: in progress

#10795 Merge 2018-12-23 304dfcfcf6
  Formula/handbrake.rb
  Formula/libmicrohttpd.rb
  Formula/libssh.rb
  Formula/netcdf.rb
  Formula/netpbm.rb
Labels: merge

#10798 Merge 2018-12-23 64f688a09e
  Formula/doitlive.rb
  Formula/exploitdb.rb
  Formula/libccd.rb
  Formula/libcec.rb
  Formula/supervisor.rb
  Formula/xtensor.rb
Labels: merge

#10799 Merge 2018-12-23 90afcc3355
  Formula/abcm2ps.rb
  Formula/babl.rb
  Formula/diceware.rb
  Formula/gegl.rb
  Formula/gitbucket.rb
  Formula/kitchen-sync.rb
  Formula/maxwell.rb
Labels: merge

#10805 Merge 2018-12-23 147b22af71
  Formula/ghostscript.rb
  Formula/gst-python.rb
Labels: merge

#10806 Merge 2018-12-24 dc9b790b96
  Formula/bochs.rb
  Formula/docker-machine-driver-xhyve.rb
  Formula/ffmpeg2theora.rb
  Formula/git-secret.rb
  Formula/gitversion.rb
  Formula/gradle-completion.rb
  Formula/gspell.rb
  Formula/gtk+3.rb
  Formula/kubectx.rb
  Formula/kubeless.rb
  Formula/libass.rb
  Formula/libgit2.rb
  Formula/nlopt.rb
  Formula/pyenv-ccache.rb
  Formula/tiger-vnc.rb
  Formula/tmux-xpanes.rb
  Formula/yaz.rb
Labels: merge

#10816 Merge 2018-12-24 ce7b15d914
  Formula/blast.rb
  Formula/groff.rb
  Formula/openvdb.rb
  Formula/pushpin.rb
  Formula/zurl.rb
Labels: merge

#10821 Merge 2018-12-25 29be66b9a9
  Formula/commandbox.rb
  Formula/eslint.rb
  Formula/gammaray.rb
  Formula/gnutls.rb
  Formula/gowsdl.rb
  Formula/hugo.rb
  Formula/libetpan.rb
  Formula/nasm.rb
  Formula/nodenv.rb
  Formula/pilosa.rb
  Formula/schismtracker.rb
  Formula/swiftlint.rb
  Formula/tgui.rb
  Formula/topgrade.rb
  Formula/translate-shell.rb
Labels: merge

#10829 Merge 2018-12-25 7f53372f1c
  Formula/erlang.rb
  Formula/gdcm.rb
  Formula/imlib2.rb
  Formula/leptonica.rb
  Formula/ndenv.rb
  Formula/numpy.rb
  Formula/percona-server-mongodb.rb
Labels: merge

#10830 Merge 2018-12-25 6e02e6f844
  Formula/pyqt.rb
  Formula/rbenv.rb
  Formula/root.rb
  Formula/scipy.rb
Labels: merge

#10831 Merge 2018-12-25 d349ca04b5
  Formula/sip.rb
  Formula/suil.rb
  Formula/tomcat-native.rb
  Formula/vips.rb
  Formula/z3.rb
Labels: merge

#10832 Merge 2018-12-25 320e7264eb
  Formula/erlang.rb
  Formula/gdcm.rb
  Formula/imlib2.rb
  Formula/leptonica.rb
  Formula/numpy.rb
  Formula/percona-server-mongodb.rb
  Formula/pyqt.rb
  Formula/rbenv.rb
  Formula/root.rb
  Formula/scipy.rb
  Formula/sip.rb
  Formula/suil.rb
  Formula/tomcat-native.rb
  Formula/vips.rb
  Formula/z3.rb
Labels: merge

#10845 Merge 2018-12-25 4fe0de3e0e
  Formula/angular-cli.rb
  Formula/firebase-cli.rb
  Formula/hwloc.rb
  Formula/mdcat.rb
  Formula/openldap.rb
  Formula/switch-lan-play.rb
Labels: merge

#10849 Merge 2018-12-25 49c8f123c4
  Formula/dpkg.rb
  Formula/exploitdb.rb
  Formula/gitlab-runner.rb
  Formula/kops.rb
  Formula/rpm.rb
  Formula/rswift.rb
Labels: merge

#10852 Merge 2018-12-25 f87d7d538e
  Formula/arcade-learning-environment.rb
  Formula/buku.rb
  Formula/weechat.rb
Labels: merge

#10854 Merge 2018-12-25 6fc8b655ca
  Formula/llvm.rb
Labels: merge

#10856 Merge 2018-12-26 27b11f4e7c
  Formula/bison.rb
  Formula/easyengine.rb
  Formula/fb-client.rb
  Formula/gtk+3.rb
  Formula/nginx.rb
  Formula/orc-tools.rb
  Formula/ruby-build.rb
  Formula/switch-lan-play.rb
Labels: merge

#10860 Merge 2018-12-27 ad427bf702
  Aliases/ruby@2.6
  Formula/cocoapods.rb
  Formula/haste-client.rb
  Formula/kontena.rb
  Formula/libstfl.rb
  Formula/mikutter.rb
  Formula/ruby.rb
  Formula/travis.rb
  Formula/vim.rb
  Formula/vim@7.4.rb
  Formula/wpscan.rb
Labels: merge

#10875 Merge 2018-12-27 ea82f609ab
  Formula/bitlbee.rb
  Formula/cctools.rb
  Formula/dos2unix.rb
  Formula/elektra.rb
  Formula/exif.rb
  Formula/fastd.rb
  Formula/flann.rb
  Formula/gifsicle.rb
  Formula/glfw.rb
  Formula/gnu-smalltalk.rb
  Formula/gromacs.rb
  Formula/h2o.rb
  Formula/io.rb
  Formula/lesspipe.rb
  Formula/libhttpserver.rb
  Formula/libusb.rb
  Formula/mercury.rb
  Formula/msmtp.rb
  Formula/mtr.rb
  Formula/nagios-plugins.rb
  Formula/net-snmp.rb
  Formula/openal-soft.rb
  Formula/openconnect.rb
  Formula/openldap.rb
  Formula/pure-ftpd.rb
  Formula/vimpager.rb
  Formula/whois.rb
  Formula/winetricks.rb
  Formula/wolfssl.rb
  Formula/wxmaxima.rb
Labels: merge

#10878 Merge 2018-12-27 ac18729d8a
  Formula/ddar.rb
  Formula/doitlive.rb
  Formula/eslint.rb
  Formula/gitlab-gem.rb
  Formula/gopass.rb
  Formula/nasm.rb
  Formula/python.rb
  Formula/sip.rb
  Formula/ucloud.rb
  Formula/wget.rb
  Formula/whois.rb
  Formula/xsimd.rb
Labels: merge

#10889 Merge 2018-12-28 03aac53b3d
  Aliases/subversion@1.11
  Formula/rom-tools.rb
  Formula/subversion.rb
Labels: merge

#10891 Merge 2018-12-28 2f807a96af
  Formula/perl.rb
  Formula/subversion.rb
  Formula/vim.rb
  Formula/vim@7.4.rb
Labels: merge

#10895 Merge 2018-12-28 49a9141d7f
  Formula/languagetool.rb
  Formula/mkvtoolnix.rb
  Formula/ola.rb
  Formula/protobuf@2.6.rb
  Formula/protobuf@3.1.rb
  Formula/python@2.rb
Labels: merge

#10897 Merge 2018-12-28 e0cd954f73
  Formula/autorest.rb
  Formula/elasticsearch.rb
  Formula/git-remote-hg.rb
  Formula/gobject-introspection.rb
  Formula/kibana.rb
  Formula/kibana@5.6.rb
  Formula/logstash.rb
  Formula/mame.rb
  Formula/mas.rb
  Formula/mono.rb
  Formula/nicotine-plus.rb
  Formula/node@6.rb
  Formula/opencv@2.rb
  Formula/protobuf.rb
  Formula/robot-framework.rb
  Formula/salt.rb
  Formula/shellshare.rb
  Formula/statik.rb
  Formula/subversion.rb
  Formula/tbb.rb
  Formula/teleport.rb
  Formula/uhd.rb
  Formula/weboob.rb
Labels: merge

#10905 Merge 2018-12-28 533d40af8c
  Formula/apache-flink.rb
  Formula/doxygen.rb
  Formula/fish.rb
  Formula/hub.rb
  Formula/imagemagick.rb
  Formula/libnice.rb
  Formula/postgresql@10.rb
  Formula/pygitup.rb
  Formula/subversion.rb
Labels: merge

#10914 Merge 2018-12-29 6bc1c295d5
  Formula/binaryen.rb
  Formula/erlang.rb
  Formula/exploitdb.rb
  Formula/fn.rb
  Formula/goreleaser.rb
  Formula/minio.rb
Labels: merge

#10918 Merge 2018-12-30 1a9d0360eb
  Formula/dhall.rb
  Formula/ghr.rb
  Formula/goenv.rb
  Formula/mysql.rb
  Formula/react-native-cli.rb
  Formula/signify-osx.rb
Labels: merge

#10921 Merge 2018-12-30 5311047af8
  Formula/cryptopp.rb
  Formula/fmt.rb
  Formula/mockserver.rb
  Formula/sbt.rb
  Formula/tcpreplay.rb
Labels: merge

#10925 Merge 2018-12-30 9fe967ad7a
  Formula/gzip.rb
  Formula/knot-resolver.rb
Labels: merge

#10926 Merge 2018-12-31 d6a145b0a6
  Formula/checkstyle.rb
  Formula/jmxterm.rb
  Formula/newsboat.rb
  Formula/termtosvg.rb
  Formula/xonsh.rb
Labels: merge
