Repository Homebrew/linuxbrew-core, pull requests merged in 2018-10, with the labels that each got.

#9649 Merge 2018-10-01 a3e89f6b3f
  Formula/apib.rb
  Formula/berkeley-db@4.rb
  Formula/bundletool.rb
  Formula/fizmo.rb
  Formula/fragroute.rb
  Formula/ispc.rb
  Formula/jruby.rb
  Formula/jsvc.rb
  Formula/le.rb
  Formula/mariadb-connector-odbc.rb
  Formula/openttd.rb
  Formula/pcapplusplus.rb
  Formula/pinfo.rb
  Formula/pypy.rb
  Formula/pypy3.rb
  Formula/qt.rb
  Formula/rabbitmq.rb
  Formula/reposurgeon.rb
  Formula/rom-tools.rb
  Formula/sile.rb
  Formula/terragrunt.rb
  Formula/tracebox.rb
  Formula/wine.rb
  Formula/xidel.rb
Labels: merge

#9655 Merge 2018-10-02 dd4918b2a5
  Formula/ammonite-repl.rb
  Formula/faac.rb
  Formula/faad2.rb
  Formula/freeswitch.rb
  Formula/geant4.rb
  Formula/libssh.rb
  Formula/llvm.rb
  Formula/llvm@3.9.rb
  Formula/llvm@4.rb
  Formula/llvm@5.rb
  Formula/llvm@6.rb
  Formula/makensis.rb
  Formula/minuit2.rb
  Formula/node.rb
  Formula/node@6.rb
  Formula/node@8.rb
  Formula/opencv.rb
  Formula/opentracing-cpp.rb
  Formula/pypy.rb
  Formula/pypy3.rb
  Formula/root.rb
  Formula/rust.rb
  Formula/scipy.rb
  Formula/snap7.rb
  Formula/stanford-corenlp.rb
  Formula/swift.rb
  Formula/terragrunt.rb
  Formula/vice.rb
Labels: merge

#9661 Use Homebrew::DEFAULT_PREFIX
  Formula/curl.rb
  Formula/fontconfig.rb
  Formula/gcc.rb
  Formula/llvm@4.rb
  Formula/llvm@5.rb
  Formula/xerces-c.rb
Labels: enhancement

#9660 ruby: Fix uninitialized constant OS::Mac::CLT [Linux]
  Formula/ruby.rb
Labels: bug

#9663 Merge 2018-10-03 7fe2b84ea0
  Formula/cern-ndiff.rb
  Formula/cmocka.rb
  Formula/openapi-generator.rb
  Formula/pegtl.rb
  Formula/unrar.rb
  Formula/wireguard-go.rb
Labels: merge

#9664 Merge 2018-10-03 dea5ae4afc
  Formula/alpine.rb
  Formula/analog.rb
  Formula/carthage.rb
  Formula/cfr-decompiler.rb
  Formula/fcgi.rb
  Formula/golang-migrate.rb
  Formula/hg-fast-export.rb
  Formula/isl.rb
  Formula/kompose.rb
  Formula/liblqr.rb
  Formula/libtar.rb
  Formula/makensis.rb
  Formula/nasm.rb
  Formula/neatvi.rb
  Formula/node-build.rb
  Formula/openal-soft.rb
  Formula/pachi.rb
  Formula/pbc.rb
  Formula/pjproject.rb
  Formula/presto.rb
  Formula/safe-rm.rb
  Formula/ttfautohint.rb
Labels: merge

#9666 Merge 2018-10-03 8e75045fbb
  Formula/cpprestsdk.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/python.rb
  Formula/python@2.rb
  Formula/serverless.rb
Labels: merge

#9669 Merge 2018-10-04 770cbb5a9c
  Formula/aircrack-ng.rb
  Formula/aws-okta.rb
  Formula/fpc.rb
  Formula/freeradius-server.rb
  Formula/git.rb
  Formula/landscaper.rb
  Formula/skafos.rb
  Formula/terragrunt.rb
Labels: merge

#9668 abyss: gcc is a dependency on macOS only
  Formula/abyss.rb
Labels: dependency, enhancement

#9670 Merge 2018-10-04 a2191e57af
  Formula/cityhash.rb
  Formula/commandbox.rb
  Formula/goenv.rb
  Formula/haproxy.rb
  Formula/joplin.rb
  Formula/jruby.rb
  Formula/nginx.rb
  Formula/pg_top.rb
  Formula/pgtune.rb
  Formula/python.rb
  Formula/tcl-tk.rb
  Formula/tcsh.rb
  Formula/tdlib.rb
  Formula/topgrade.rb
  Formula/vim.rb
Labels: merge

#9673 Merge 2018-10-04 e767f31779
  Aliases/qt@5.11
  Formula/at-spi2-atk.rb
  Formula/at-spi2-core.rb
  Formula/automake.rb
  Formula/ccm.rb
  Formula/cgal.rb
  Formula/clisp.rb
  Formula/cryfs.rb
  Formula/gdb.rb
  Formula/gobby.rb
  Formula/gpp.rb
  Formula/libheif.rb
  Formula/mikmod.rb
  Formula/pax-runner.rb
  Formula/qemu.rb
  Formula/rabbitmq.rb
  Formula/sbcl.rb
  Formula/shml.rb
  Formula/sonar-scanner.rb
  Formula/sonarlint.rb
  Formula/sonarqube-lts.rb
  Formula/sonarqube.rb
  Formula/squid.rb
  formula_renames.json
Labels: merge

#9677 Merge 2018-10-04 9a2f4d3e0e
  Formula/abcde.rb
  Formula/caffe.rb
  Formula/ffmbc.rb
  Formula/fontforge.rb
  Formula/icecast.rb
  Formula/kubernetes-service-catalog-client.rb
  Formula/links.rb
  Formula/open-scene-graph.rb
  Formula/poppler.rb
  Formula/qca.rb
  Formula/rakudo-star.rb
  Formula/suricata.rb
Labels: merge

#9686 Merge 2018-10-06 ecbf0f441e
  Formula/bcal.rb
  Formula/dita-ot.rb
  Formula/jetty-runner.rb
  Formula/jetty.rb
  Formula/jhipster.rb
  Formula/numpy.rb
  Formula/opensubdiv.rb
  Formula/skaffold.rb
  Formula/vert.x.rb
Labels: merge

#9687 Merge 2018-10-06 a99800edb2
  Formula/asciinema2gif.rb
  Formula/casperjs.rb
  Formula/swiftgen.rb
  tap_migrations.json
Labels: merge

#9688 Merge 2018-10-06 fe419deb56
  Formula/clamav.rb
  Formula/cmake.rb
  Formula/container-diff.rb
  Formula/dnscrypt-proxy.rb
  Formula/doctl.rb
  Formula/jenkins.rb
  Formula/jfrog-cli-go.rb
  Formula/metabase.rb
Labels: merge

#9691 Merge 2018-10-07 6a3e663628
  Formula/cadaver.rb
  Formula/caf.rb
  Formula/devd.rb
  Formula/icecream.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/ldc.rb
  Formula/libxml++.rb
  Formula/libxml++3.rb
  Formula/par2.rb
  Formula/prometheus.rb
  Formula/rsstail.rb
  Formula/tesseract.rb
  Formula/webtorrent-cli.rb
Labels: merge

#9693 Merge 2018-10-07 edcbe4779d
  Formula/bettercap.rb
  Formula/bitcoin.rb
  Formula/clipper.rb
  Formula/fail2ban.rb
  Formula/geckodriver.rb
  Formula/grakn.rb
  Formula/gst-editing-services.rb
  Formula/gst-libav.rb
  Formula/gst-plugins-bad.rb
  Formula/gst-plugins-base.rb
  Formula/gst-plugins-good.rb
  Formula/gst-plugins-ugly.rb
  Formula/gst-python.rb
  Formula/gst-rtsp-server.rb
  Formula/gst-validate.rb
  Formula/gstreamer.rb
  Formula/krakend.rb
  Formula/mariadb.rb
  Formula/mpv.rb
  Formula/nodebrew.rb
  Formula/phoronix-test-suite.rb
  Formula/puzzles.rb
  Formula/shpotify.rb
  Formula/strongswan.rb
Labels: merge

#9700 Merge 2018-10-07 278b20a6c6
  Formula/apache-geode.rb
  Formula/checkbashisms.rb
  Formula/exercism.rb
  Formula/flatbuffers.rb
  Formula/grc.rb
  Formula/highlight.rb
  Formula/i2p.rb
  Formula/i2pd.rb
  Formula/ipv6calc.rb
  Formula/jhipster.rb
  Formula/libphonenumber.rb
  Formula/makensis.rb
  Formula/mariadb.rb
  Formula/mariadb@10.0.rb
  Formula/mariadb@10.1.rb
  Formula/mariadb@10.2.rb
  Formula/meson.rb
  Formula/orc-tools.rb
  Formula/percona-server@5.6.rb
  Formula/phpunit.rb
  Formula/tcc.rb
  Formula/unrar.rb
  Formula/youtube-dl.rb
  Formula/yubico-piv-tool.rb
Labels: merge

#9710 Merge 2018-10-08 7a227d0ea2
  Formula/app-engine-java.rb
  Formula/ark.rb
  Formula/krakend.rb
  Formula/kubernetes-service-catalog-client.rb
  Formula/libepoxy.rb
  Formula/makensis.rb
  Formula/micronaut.rb
  Formula/mkvtoolnix.rb
  Formula/nomad.rb
  Formula/yamllint.rb
  Formula/ykman.rb
  Formula/yubico-piv-tool.rb
  Formula/zenity.rb
Labels: merge

#9717 Merge 2018-10-09 03db806ae6
  Formula/apache-spark.rb
  Formula/avro-cpp.rb
  Formula/blink1.rb
  Formula/cloc.rb
  Formula/convox.rb
  Formula/elasticsearch.rb
  Formula/elm-format.rb
  Formula/fzf.rb
  Formula/git-annex.rb
  Formula/git.rb
  Formula/hledger.rb
  Formula/hyperfine.rb
  Formula/livestreamer.rb
  Formula/mkdocs.rb
  Formula/mscgen.rb
  Formula/opentracing-cpp.rb
  Formula/pandoc-citeproc.rb
  Formula/rustup-init.rb
  Formula/singular.rb
  Formula/source-highlight.rb
  Formula/texmath.rb
  Formula/wireguard-tools.rb
Labels: merge

#9727 Merge 2018-10-09 537f3703aa
  Formula/aws-elasticbeanstalk.rb
  Formula/fn.rb
  Formula/futhark.rb
  Formula/highlight.rb
  Formula/jbake.rb
  Formula/jhipster.rb
  Formula/libheif.rb
  Formula/libvirt.rb
  Formula/mkdocs.rb
  Formula/php-code-sniffer.rb
  Formula/swiftgen.rb
  Formula/terragrunt.rb
  Formula/x265.rb
  Formula/zstd.rb
Labels: merge

#9739 Merge 2018-10-09 c9967f9634
  Formula/circleci.rb
  Formula/crosstool-ng.rb
  Formula/duc.rb
  Formula/gosu.rb
  Formula/gwenhywfar.rb
  Formula/hayai.rb
  Formula/icu4c.rb
  Formula/jenkins.rb
  Formula/libcerf.rb
  Formula/libpointing.rb
  Formula/libxc.rb
  Formula/maven-shell.rb
  Formula/mupdf-tools.rb
  Formula/mysqltuner.rb
  Formula/nlopt.rb
  Formula/nu.rb
  Formula/pbzip2.rb
  Formula/pelikan.rb
  Formula/picat.rb
  Formula/procmail.rb
  Formula/qca.rb
  Formula/quex.rb
  Formula/rsnapshot.rb
  Formula/salt.rb
  Formula/sbt.rb
  Formula/shntool.rb
  Formula/shorten.rb
  Formula/sqlcipher.rb
  Formula/tcping.rb
  Formula/todo-txt.rb
  Formula/topgrade.rb
  Formula/tta.rb
  Formula/wireguard-tools.rb
  Formula/wskdeploy.rb
  Formula/xcenv.rb
Labels: merge

#9741 Merge 2018-10-09 2b285aa49a
  Formula/alure.rb
  Formula/arangodb.rb
  Formula/atf.rb
  Formula/bonnie++.rb
  Formula/c-blosc.rb
  Formula/conan.rb
  Formula/ekg2.rb
  Formula/git-standup.rb
  Formula/jerm.rb
  Formula/juju.rb
  Formula/librealsense.rb
  Formula/mp3cat.rb
  Formula/mpc.rb
  Formula/muparser.rb
  Formula/mupdf-tools.rb
  Formula/mupdf.rb
  Formula/ne.rb
  Formula/objfw.rb
  Formula/openal-soft.rb
  Formula/pipenv.rb
  Formula/reop.rb
  Formula/rke.rb
  Formula/roswell.rb
  Formula/sbt.rb
  Formula/softhsm.rb
  Formula/teleport.rb
  Formula/terraform-docs.rb
  Formula/tinc.rb
Labels: merge

#9751 Merge 2018-10-10 9f5c2cd842
  Formula/awscli.rb
  Formula/carthage.rb
  Formula/embulk.rb
  Formula/hmmer.rb
  Formula/nexus.rb
  Formula/peg.rb
Labels: merge

#9755 Merge 2018-10-10 875a1f985e
  Formula/autopep8.rb
  Formula/bento4.rb
  Formula/cheat.rb
  Formula/grip.rb
  Formula/hachoir-metadata.rb
  Formula/hugo.rb
  Formula/hyperscan.rb
  Formula/pdf-redact-tools.rb
  Formula/proselint.rb
  Formula/pwntools.rb
  Formula/queequeg.rb
  Formula/remarshal.rb
  Formula/sickbeard.rb
Labels: merge

#9756 Merge 2018-10-11 828c5aac1c
  Formula/chamber.rb
  Formula/cocoapods.rb
  Formula/jsonrpc-glib.rb
  Formula/lxc.rb
  Formula/metaproxy.rb
  Formula/tippecanoe.rb
  Formula/yaz.rb
Labels: merge

#9757 Merge 2018-10-11 8f1cb0f771
  Formula/bitrise.rb
  Formula/brogue.rb
  Formula/cmu-sphinxbase.rb
  Formula/gitg.rb
  Formula/grafana.rb
  Formula/gtkspell3.rb
  Formula/libgit2-glib.rb
  Formula/libsecret.rb
Labels: merge

#9759 Merge 2018-10-11 365600c1bc
  Formula/archivemail.rb
  Formula/jrnl.rb
  Formula/mimms.rb
  Formula/mkdocs.rb
  Formula/nyx.rb
  Formula/shocco.rb
  Formula/sshuttle.rb
  Formula/subliminal.rb
  Formula/termius.rb
  Formula/tnote.rb
  Formula/tvnamer.rb
  Formula/twarc.rb
  Formula/unoconv.rb
Labels: merge

#9766 Merge 2018-10-12 11f74f5096
  Formula/aap.rb
  Formula/afflib.rb
  Formula/boost@1.55.rb
  Formula/chrome-export.rb
  Formula/closure-linter.rb
  Formula/collectd.rb
  Formula/doitlive.rb
  Formula/dxpy.rb
  Formula/enchant.rb
  Formula/gwyddion.rb
  Formula/honcho.rb
  Formula/jenkins-job-builder.rb
  Formula/lcm.rb
  Formula/libbtbb.rb
  Formula/libpeas.rb
  Formula/libproxy.rb
  Formula/libpst.rb
  Formula/libtorrent-rasterbar.rb
  Formula/mat.rb
  Formula/pacparser.rb
  Formula/reclass.rb
  Formula/restview.rb
  Formula/silk.rb
  Formula/unbound.rb
Labels: merge

#9782 Merge 2018-10-13 cfcfb6ecff
  Formula/bind.rb
  Formula/firebase-cli.rb
  Formula/geos.rb
  Formula/hugo.rb
  Formula/jenkins-lts.rb
  Formula/node-build.rb
  Formula/openvdb.rb
  Formula/php.rb
  Formula/php@7.1.rb
  Formula/rswift.rb
  Formula/sslmate.rb
  Formula/swiftformat.rb
Labels: merge

#9788 Merge 2018-10-14 21dccbc07d
  Formula/bubbros.rb
  Formula/crosstool-ng.rb
  Formula/docker-cloud.rb
  Formula/freetds.rb
  Formula/jenkins.rb
  Formula/jfrog-cli-go.rb
  Formula/twine-pypi.rb
  Formula/wakatime-cli.rb
Labels: merge

#9789 Merge 2018-10-14 1412c89a44
  Formula/consul.rb
  Formula/duo_unix.rb
  Formula/erlang@17.rb
  Formula/monero.rb
  Formula/node.rb
  Formula/ocrmypdf.rb
  Formula/skaffold.rb
  Formula/wireshark.rb
Labels: merge

#9794 Merge 2018-10-15 62b906d142
  Formula/ansible-cmdb.rb
  Formula/ansible-lint.rb
  Formula/arcade-learning-environment.rb
  Formula/atdtool.rb
  Formula/azure-cli.rb
  Formula/b2-tools.rb
  Formula/bde.rb
  Formula/credstash.rb
  Formula/dnstwist.rb
  Formula/docker-compose.rb
  Formula/docker-squash.rb
  Formula/docutils.rb
  Formula/euler-py.rb
  Formula/golang-migrate.rb
  Formula/goolabs.rb
  Formula/howdoi.rb
  Formula/httpstat.rb
  Formula/mdv.rb
  Formula/mongo-orchestration.rb
  Formula/nanomsgxx.rb
  Formula/watchman.rb
  Formula/watson.rb
  Formula/ydcv.rb
  Formula/ykman.rb
  Formula/yle-dl.rb
Labels: merge

#9807 Merge 2018-10-15 85bf73b268
  Formula/awslogs.rb
  Formula/blitz.rb
  Formula/blueutil.rb
  Formula/eralchemy.rb
  Formula/eye-d3.rb
  Formula/fobis.rb
  Formula/ford.rb
  Formula/git-plus.rb
  Formula/gitless.rb
  Formula/iproute2mac.rb
  Formula/knot-resolver.rb
  Formula/livestreamer.rb
  Formula/muttils.rb
  Formula/percol.rb
  Formula/pius.rb
  Formula/sceptre.rb
  Formula/stormpath-cli.rb
  Formula/supervisor.rb
  Formula/urweb.rb
Labels: merge

#9815 Merge 2018-10-16 4c5c1fb5bb
  Formula/binwalk.rb
  Formula/cookiecutter.rb
  Formula/cxxtest.rb
  Formula/fbi-servefiles.rb
  Formula/genometools.rb
  Formula/glances.rb
  Formula/googler.rb
  Formula/internetarchive.rb
  Formula/mkvtomp4.rb
  Formula/onepass.rb
  Formula/stormssh.rb
  Formula/streamlink.rb
  Formula/sundials.rb
  Formula/suricata.rb
  Formula/tarsnapper.rb
  Formula/testssl.rb
  Formula/trash-cli.rb
Labels: merge

#9823 Merge 2018-10-17 dbc0f1edbf
  Aliases/ansible@2.7
  Formula/alluxio.rb
  Formula/annie.rb
  Formula/ansible.rb
  Formula/ansible@1.9.rb
  Formula/ansible@2.0.rb
  Formula/asdf.rb
  Formula/chisel.rb
  Formula/convox.rb
  Formula/faas-cli.rb
  Formula/git-review.rb
  Formula/ib.rb
  Formula/ino.rb
  Formula/juju-quickstart.rb
  Formula/legit.rb
  Formula/libtorrent-rasterbar.rb
  Formula/micronaut.rb
  Formula/pipenv.rb
  Formula/planck.rb
  Formula/pony-stable.rb
  Formula/ponyc.rb
  Formula/recon-ng.rb
  Formula/rst-lint.rb
  Formula/rust.rb
  Formula/scour.rb
  Formula/tarantool.rb
Labels: merge

#9845 Merge 2018-10-17 d1b4a80301
  Formula/ansifilter.rb
  Formula/bat.rb
  Formula/bazel.rb
  Formula/crowdin.rb
  Formula/deark.rb
  Formula/epstool.rb
  Formula/fmpp.rb
  Formula/gitlab-runner.rb
  Formula/grafana.rb
  Formula/hcloud.rb
  Formula/hdf5@1.8.rb
  Formula/helmfile.rb
  Formula/help2man.rb
  Formula/heroku.rb
  Formula/highlight.rb
  Formula/imageworsener.rb
  Formula/jflex.rb
  Formula/kops.rb
  Formula/lasso.rb
  Formula/libvirt.rb
  Formula/logentries.rb
  Formula/luvit.rb
  Formula/mysql-utilities.rb
  Formula/pacparser.rb
  Formula/platformio.rb
  Formula/rclone.rb
  Formula/terragrunt.rb
  Formula/zsh.rb
  Formula/zstd.rb
Labels: merge

#9856 Merge 2018-10-17 227835fd37
  Formula/azure-cli.rb
  Formula/beast.rb
  Formula/cppcheck.rb
  Formula/doctl.rb
  Formula/eslint.rb
  Formula/etcd.rb
  Formula/fuseki.rb
  Formula/gpgme.rb
  Formula/jenkins.rb
  Formula/jhipster.rb
  Formula/libssh.rb
  Formula/libuv.rb
  Formula/libvirt.rb
  Formula/magic-wormhole.rb
  Formula/plantuml.rb
  Formula/rancher-cli.rb
  Formula/re2.rb
  Formula/tox.rb
  Formula/typescript.rb
Labels: merge

#9880 Merge 2018-10-20 4e1e1dc649
  Aliases/v8@7.0
  Formula/cython.rb
  Formula/gjstest.rb
  Formula/monetdb.rb
  Formula/quicktype.rb
  Formula/sbt.rb
  Formula/ucloud.rb
  Formula/v8.rb
Labels: merge

#9882 Merge 2018-10-20 d20ea8ad6b
  Formula/ffmpeg.rb
Labels: merge

#9884 Merge 2018-10-20 c83e431260
  Formula/libgit2.rb
  Formula/lsh.rb
  Formula/nesemu2.rb
  Formula/ngspice.rb
  Formula/open-vcdiff.rb
  Formula/opensyobon.rb
  Formula/pulumi.rb
  Formula/sary.rb
Labels: merge

#9885 Merge 2018-10-21 04a6b16d03
  Formula/ack.rb
  Formula/choose.rb
  Formula/codemod.rb
  Formula/global.rb
  Formula/gprof2dot.rb
  Formula/gst-plugins-bad.rb
  Formula/gst-plugins-base.rb
  Formula/gst-plugins-good.rb
  Formula/gst-plugins-ugly.rb
  Formula/yara.rb
Labels: merge

#9886 Merge 2018-10-21 85a95d5034
  Formula/ark.rb
  Formula/basex.rb
  Formula/bind.rb
  Formula/clojure.rb
  Formula/cnats.rb
  Formula/cromwell.rb
  Formula/ffmpeg@2.8.rb
  Formula/fselect.rb
  Formula/git-review.rb
  Formula/graphite2.rb
  Formula/libmxml.rb
  Formula/micronaut.rb
  Formula/minizip.rb
  Formula/monkeysphere.rb
  Formula/n.rb
  Formula/openshift-cli.rb
  Formula/orocos-kdl.rb
  Formula/qt.rb
  Formula/ruby-build.rb
  Formula/ruby.rb
  Formula/ruby@2.3.rb
  Formula/sleuthkit.rb
  Formula/spades.rb
  Formula/tmux.rb
  Formula/vagrant-completion.rb
  Formula/vtk.rb
  Formula/wine.rb
Labels: merge

#9898 Merge 2018-10-21 35f5932a4e
  Formula/autopep8.rb
  Formula/erlang@20.rb
  Formula/exploitdb.rb
  Formula/flake8.rb
  Formula/heroku.rb
  Formula/icdiff.rb
  Formula/mercurial.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/ruby.rb
  Formula/tor.rb
Labels: merge

#9899 Merge 2018-10-21 8825b5e866
  Aliases/redis@5.0
  Formula/closure-compiler.rb
  Formula/dhall-json.rb
  Formula/diffoscope.rb
  Formula/erlang@19.rb
  Formula/ffmpeg@2.8.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/influxdb.rb
  Formula/kubernetes-service-catalog-client.rb
  Formula/libcouchbase.rb
  Formula/libexif.rb
  Formula/libphonenumber.rb
  Formula/libressl.rb
  Formula/memcached.rb
  Formula/mercurial.rb
  Formula/mongo-c-driver.rb
  Formula/mongodb.rb
  Formula/neovim.rb
  Formula/nghttp2.rb
  Formula/opus.rb
  Formula/qmmp.rb
  Formula/redis.rb
  Formula/remarshal.rb
  Formula/restic.rb
  Formula/solr@6.6.rb
  Formula/swift-protobuf.rb
  Formula/telegraf.rb
  Formula/webpack.rb
  Formula/yamllint.rb
Labels: merge

#9900 Merge 2018-10-21 92a7eb9429
  Formula/antlr.rb
  Formula/antlr@2.rb
  Formula/cairo.rb
  Formula/ccache.rb
  Formula/conan.rb
  Formula/datomic.rb
  Formula/dnsmasq.rb
  Formula/duti.rb
  Formula/faas-cli.rb
  Formula/gauge.rb
  Formula/hiredis.rb
  Formula/ldc.rb
  Formula/libjson-rpc-cpp.rb
  Formula/libpq.rb
  Formula/nats-streaming-server.rb
  Formula/nco.rb
  Formula/openssh.rb
  Formula/pandoc-citeproc.rb
  Formula/restic.rb
  Formula/root.rb
  Formula/solr@6.6.rb
  Formula/ssh-copy-id.rb
  Formula/tika.rb
  Formula/unar.rb
  Formula/xctool.rb
Labels: merge

#9935 Merge 2018-10-23 534ed0a6e7
  Formula/ammonite-repl.rb
  Formula/bat.rb
  Formula/git-annex.rb
  Formula/gnome-latex.rb
  Formula/gtksourceview4.rb
  Formula/kommit.rb
  Formula/libcerf.rb
  Formula/pandoc-citeproc.rb
  Formula/phpunit.rb
  Formula/swiftlint.rb
  Formula/tepl.rb
  Formula/terraform.rb
  Formula/tika.rb
  Formula/wireguard-go.rb
  formula_renames.json
Labels: merge

#9941 Merge 2018-10-23 7596f0d474
  Formula/abook.rb
  Formula/ack.rb
  Formula/aspell.rb
  Formula/basex.rb
  Formula/cdrtools.rb
  Formula/cmdshelf.rb
  Formula/cmus.rb
  Formula/cocoapods.rb
  Formula/collada-dom.rb
  Formula/gnutls.rb
  Formula/librsvg.rb
  Formula/php.rb
  Formula/python.rb
  Formula/qt.rb
  Formula/wine.rb
Labels: merge

#9943 Merge 2018-10-23 5279195ccd
  Formula/armadillo.rb
  Formula/caffe.rb
  Formula/dartsim.rb
  Formula/dynare.rb
  Formula/field3d.rb
  Formula/flann.rb
  Formula/gmt.rb
  Formula/gmt@4.rb
  Formula/hdf5.rb
  Formula/kallisto.rb
  Formula/libbi.rb
  Formula/libmatio.rb
  Formula/ncview.rb
  Formula/netcdf.rb
  Formula/octave.rb
  Formula/pcl.rb
  Formula/pdal.rb
  Formula/shogun.rb
  Formula/sratoolkit.rb
  Formula/vtk.rb
Labels: merge

#9957 Merge 2018-10-24 60d5a36df8
  Formula/angband.rb
  Formula/aubio.rb
  Formula/cgit.rb
  Formula/chocolate-doom.rb
  Formula/codemod.rb
  Formula/dbus.rb
  Formula/eg-examples.rb
  Formula/freerdp.rb
  Formula/frugal.rb
  Formula/git-cinnabar.rb
  Formula/git-multipush.rb
  Formula/gnu-smalltalk.rb
  Formula/gnuplot.rb
  Formula/harfbuzz.rb
  Formula/inadyn.rb
  Formula/libvmaf.rb
  Formula/lincity-ng.rb
  Formula/linklint.rb
  Formula/moc.rb
  Formula/moon-buggy.rb
  Formula/nu-smv.rb
  Formula/numpy.rb
  Formula/onetime.rb
  Formula/paperkey.rb
  Formula/premake.rb
  Formula/rdiff-backup.rb
  Formula/readline.rb
  Formula/rswift.rb
  Formula/ruby-build.rb
  Formula/scala.rb
  Formula/scipy.rb
  Formula/smimesign.rb
  Formula/sonobuoy.rb
  Formula/swi-prolog.rb
  Formula/wallpaper.rb
Labels: merge

#9965 Merge 2018-10-24 83202ce4e7
  Formula/apache-arrow-glib.rb
  Formula/apache-arrow.rb
  Formula/gnu-units.rb
  Formula/harfbuzz.rb
  Formula/open-ocd.rb
  Formula/zstd.rb
Labels: merge

#9966 Merge 2018-10-24 3a2c4ba0fa
  Formula/bup.rb
  Formula/cpansearch.rb
  Formula/crf++.rb
  Formula/dante.rb
  Formula/dc3dd.rb
  Formula/gedit.rb
  Formula/headphones.rb
  Formula/innotop.rb
  Formula/iproute2mac.rb
  Formula/libvoikko.rb
  Formula/mps-youtube.rb
  Formula/mytop.rb
  Formula/osc.rb
  Formula/percona-toolkit.rb
  Formula/percona-xtrabackup.rb
  Formula/platypus.rb
  Formula/pxz.rb
  Formula/resin-cli.rb
  Formula/salt.rb
  Formula/simgrid.rb
  Formula/sngrep.rb
  Formula/tomcat.rb
  Formula/tomcat@6.rb
  Formula/tomcat@7.rb
  Formula/tomcat@8.rb
  Formula/topgrade.rb
  Formula/uwsgi.rb
  Formula/varnish.rb
  Formula/watchman.rb
Labels: merge

#9979 Merge 2018-10-24 ce865ab5a4
  Formula/bnd.rb
  Formula/cmake.rb
  Formula/diff-pdf.rb
  Formula/mysql@5.5.rb
  Formula/mysql@5.6.rb
  Formula/numpy.rb
  Formula/pdftoedn.rb
  Formula/pdftoipe.rb
  Formula/poppler.rb
  Formula/pumba.rb
Labels: merge

#9987 Merge 2018-10-25 bdc2de66d9
  Formula/apple-gcc42.rb
  Formula/camlp5.rb
  Formula/coq.rb
  Formula/gcc@4.9.rb
  Formula/gcc@5.rb
  Formula/ld64.rb
  Formula/smlnj.rb
  Formula/valgrind.rb
  Formula/wine.rb
Labels: merge

#9988 Merge 2018-10-25 f8637c6135
  Formula/gcc@4.9.rb
  Formula/gcc@5.rb
  Formula/llvm.rb
  Formula/llvm@3.9.rb
  Formula/llvm@4.rb
  Formula/llvm@5.rb
  Formula/llvm@6.rb
  Formula/radare2.rb
Labels: merge

#9989 Merge 2018-10-25 8583b4a7d4
  Formula/pngpaste.rb
  Formula/smlnj.rb
  Formula/treefrog.rb
  Formula/wine.rb
Labels: merge

#9990 Merge 2018-10-25 bdba8323cc
  Formula/afsctool.rb
  Formula/crf++.rb
  Formula/hbase.rb
  Formula/mapserver.rb
  Formula/mas.rb
  Formula/phpunit.rb
  Formula/prips.rb
  Formula/when.rb
Labels: merge

#9992 Merge 2018-10-25 52b19b42e4
  Formula/azure-cli.rb
  Formula/doxygen.rb
  Formula/file-formula.rb
  Formula/gecode.rb
  Formula/gitlab-runner.rb
  Formula/libmagic.rb
  Formula/noweb.rb
  Formula/payara.rb
  Formula/safe.rb
Labels: merge

#9994 Merge 2018-10-25 b2b8b70ef5
  Aliases/node@11
  Formula/awscli.rb
  Formula/evince.rb
  Formula/hub.rb
  Formula/joplin.rb
  Formula/micronaut.rb
  Formula/node.rb
  Formula/node@10.rb
  Formula/tealdeer.rb
  Formula/terraform.rb
  Formula/tldr.rb
  Formula/vault.rb
Labels: merge

#9996 Merge 2018-10-25 f878db3dad
  Formula/abyss.rb
  Formula/advancecomp.rb
  Formula/angular-cli.rb
  Formula/arangodb.rb
  Formula/ark.rb
  Formula/bluepill.rb
  Formula/duplicity.rb
  Formula/git-review.rb
  Formula/grafana.rb
  Formula/httpd.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jbake.rb
  Formula/librsvg.rb
  Formula/meson.rb
  Formula/minizinc.rb
  Formula/node-build.rb
  Formula/opam.rb
  Formula/pdfpc.rb
  Formula/planck.rb
  Formula/qpdf.rb
  Formula/shellz.rb
  Formula/skafos.rb
  Formula/terraform-docs.rb
  Formula/tippecanoe.rb
  Formula/ucloud.rb
  Formula/um.rb
  Formula/wabt.rb
Labels: merge

#10012 Fix Error: uninitialized constant OS::Mac::CLT [Linux]
  Formula/erlang.rb
  Formula/erlang@18.rb
  Formula/erlang@19.rb
  Formula/gcc@4.9.rb
  Formula/gcc@5.rb
  Formula/gcc@6.rb
  Formula/gcc@7.rb
  Formula/gcc@8.rb
  Formula/llvm.rb
  Formula/llvm@5.rb
  Formula/llvm@6.rb
  Formula/python.rb
  Formula/python@2.rb
  Formula/ruby@2.0.rb
  Formula/ruby@2.3.rb
  Formula/valgrind.rb
Labels: bug

#10015 Merge 2018-10-26 8020dee4f4
  Formula/doitlive.rb
  Formula/feh.rb
  Formula/flyway.rb
  Formula/homebank.rb
  Formula/idris.rb
  Formula/mkvtoolnix.rb
  Formula/nss.rb
  Formula/parallel.rb
  Formula/pgformatter.rb
  Formula/rust.rb
  Formula/xmake.rb
Labels: merge

#10024 Merge 2018-10-27 d9f22504f4
  Formula/ansible.rb
  Formula/aspectj.rb
  Formula/bmake.rb
  Formula/diffoscope.rb
  Formula/flake8.rb
  Formula/futhark.rb
  Formula/gandi.cli.rb
  Formula/json-fortran.rb
  Formula/nnn.rb
  Formula/plantuml.rb
  Formula/tbb.rb
  Formula/z3.rb
Labels: merge

#10037 Merge 2018-10-28 6a0c1acb0e
  Formula/autopep8.rb
  Formula/brotli.rb
  Formula/c-ares.rb
  Formula/elixir.rb
  Formula/mdcat.rb
  Formula/php-cs-fixer.rb
  Formula/webpack.rb
  Formula/zsh-completions.rb
Labels: merge

#10041 Merge 2018-10-29 4ec7e3b19b
  Formula/collectd.rb
  Formula/ejabberd.rb
  Formula/eslint.rb
  Formula/libgcrypt.rb
  Formula/lynis.rb
  Formula/nifi.rb
  Formula/safe.rb
  Formula/skaffold.rb
Labels: merge

#10042 Merge 2018-10-29 3e94ae4217
  Formula/gcc@6.rb
Labels: merge

#10048 Merge 2018-10-30 389ccc48f0
  Formula/crowdin.rb
  Formula/dlib.rb
  Formula/fd.rb
  Formula/gmime.rb
  Formula/jsonnet.rb
  Formula/nsd.rb
  Formula/whois.rb
  Formula/yarn.rb
  Formula/zookeeper.rb
Labels: merge

#10054 Merge 2018-10-31 372fddc2a4
  Formula/advancemame.rb
  Formula/app-engine-java.rb
  Formula/asciidoc.rb
  Formula/beast.rb
  Formula/bzt.rb
  Formula/circleci.rb
  Formula/dosbox-x.rb
  Formula/hugo.rb
  Formula/imageworsener.rb
  Formula/imapfilter.rb
  Formula/ipython.rb
  Formula/kakoune.rb
  Formula/platformio.rb
  Formula/presto.rb
  Formula/pwntools.rb
  Formula/skafos.rb
  Formula/sox.rb
  Formula/tox.rb
  Formula/unbound.rb
  Formula/vim.rb
  Formula/vips.rb
  Formula/wireguard-tools.rb
  Formula/xmrig.rb
  Formula/youtube-dl.rb
Labels: merge

#10067 Merge 2018-10-31 b7bc467b9e
  Formula/binutils.rb
  Formula/pwntools.rb
Labels: merge

#10068 Merge 2018-10-31 26abed6a37
  Formula/ahcpd.rb
  Formula/blahtexml.rb
  Formula/contacts.rb
  Formula/dbacl.rb
  Formula/dependency-check.rb
  Formula/embulk.rb
  Formula/emscripten.rb
  Formula/erlang@18.rb
  Formula/gdbm.rb
  Formula/ghc.rb
  Formula/grepcidr.rb
  Formula/influxdb.rb
  Formula/jenkins.rb
  Formula/packer.rb
  Formula/pulumi.rb
  Formula/ruby@2.4.rb
  Formula/tesseract.rb
  Formula/uriparser.rb
  Formula/vapoursynth.rb
  Formula/wandio.rb
  Formula/yq.rb
  Formula/zanata-client.rb
Labels: merge

#10078 Merge 2018-10-31 114d2384db
  Aliases/bison@3.2
  Formula/bison.rb
  Formula/i386-elf-binutils.rb
  Formula/i386-elf-gcc.rb
  Formula/jsonrpc-glib.rb
  Formula/kotlin.rb
  Formula/kustomize.rb
  Formula/open-mpi.rb
  Formula/pyenv.rb
  Formula/tbb.rb
  Formula/typescript.rb
  Formula/yarn.rb
Labels: merge
