Repository Homebrew/linuxbrew-core, pull requests merged in 2018-09, with the labels that each got.

#9171 Merge 2018-09-01 80860911cd
  Formula/darkice.rb
  Formula/dirt.rb
  Formula/djbdns.rb
  Formula/efl.rb
  Formula/evince.rb
  Formula/goffice.rb
  Formula/gupnp.rb
  Formula/jack.rb
  Formula/knot-resolver.rb
  Formula/libgdata.rb
  Formula/ltc-tools.rb
  Formula/luajit.rb
  Formula/luaradio.rb
  Formula/minetest.rb
  Formula/moc.rb
  Formula/ncmpc.rb
  Formula/neovim.rb
  Formula/ngrep.rb
  Formula/ocrmypdf.rb
  Formula/openblas.rb
  Formula/pyside.rb
  Formula/qjackctl.rb
  Formula/snort.rb
  Formula/solarus.rb
  Formula/sourcekitten.rb
  Formula/vim.rb
  Formula/vim@7.4.rb
  Formula/virtualpg.rb
  Formula/zelda-roth-se.rb
  Formula/zsdx.rb
  Formula/zsxd.rb
Labels: merge

#9176 Merge 2018-09-01 3d27b8c3e1
  Formula/blastem.rb
  Formula/cimg.rb
  Formula/deployer.rb
  Formula/duo_unix.rb
  Formula/flatcc.rb
  Formula/gitup.rb
  Formula/gobuster.rb
  Formula/volatility.rb
  Formula/weboob.rb
Labels: merge

#9182 Merge 2018-09-01 2d92aaa142
  Formula/bloaty.rb
  Formula/cwlogs.rb
  Formula/wsk.rb
Labels: merge

#9185 Merge 2018-09-02 e31fad140a
  Formula/elm-format.rb
  Formula/glib.rb
  Formula/juju.rb
  Formula/libwpd.rb
  Formula/libwpg.rb
  Formula/liquigraph.rb
  Formula/media-info.rb
  Formula/monetdb.rb
  Formula/ooniprobe.rb
  Formula/xonsh.rb
Labels: merge

#9187 Merge 2018-09-02 d7e25c01d2
  Formula/adwaita-icon-theme.rb
  Formula/afsctool.rb
  Formula/allegro.rb
  Formula/amdatu-bootstrap.rb
  Formula/anjuta.rb
  Formula/antlr4-cpp-runtime.rb
  Formula/apache-geode.rb
  Formula/aqbanking.rb
  Formula/bat.rb
  Formula/calabash.rb
  Formula/cataclysm.rb
  Formula/circleci.rb
  Formula/django-completion.rb
  Formula/docker-completion.rb
  Formula/docker-compose.rb
  Formula/docker-squash.rb
  Formula/elm.rb
  Formula/flow.rb
  Formula/fontconfig.rb
  Formula/freetds.rb
  Formula/gitlab-runner.rb
  Formula/gobject-introspection.rb
  Formula/goreleaser.rb
  Formula/gsoap.rb
  Formula/hebcal.rb
  Formula/heroku.rb
  Formula/htmldoc.rb
  Formula/icon.rb
  Formula/jadx.rb
  Formula/knot.rb
  Formula/ldns.rb
  Formula/librtlsdr.rb
  Formula/lolcat.rb
  Formula/mackup.rb
  Formula/mdp.rb
  Formula/mill.rb
  Formula/minimesos.rb
  Formula/monax.rb
  Formula/nspr.rb
  Formula/openrct2.rb
  Formula/picard-tools.rb
  Formula/pumba.rb
  Formula/re2c.rb
  Formula/tokei.rb
  Formula/vagrant-completion.rb
  Formula/vault.rb
  Formula/wine.rb
  Formula/wp-cli-completion.rb
Labels: merge

#9206 Merge 2018-09-03 a4ec34d4f5
  Formula/artifactory.rb
  Formula/atlassian-cli.rb
  Formula/bear.rb
  Formula/buku.rb
  Formula/chakra.rb
  Formula/youtube-dl.rb
Labels: merge

#9207 Merge 2018-09-03 58bca4acd0
  Formula/md5deep.rb
  Formula/wcslib.rb
Labels: merge

#9208 Merge 2018-09-03 e106d15aa0
  Formula/gcc@6.rb
  Formula/gcc@7.rb
Labels: merge

#9211 Merge 2018-09-03 bc34ff05ec
  Formula/anjuta.rb
  Formula/autopep8.rb
  Formula/bcpp.rb
  Formula/capnp.rb
  Formula/faas-cli.rb
  Formula/gist.rb
  Formula/git-archive-all.rb
  Formula/gjs.rb
  Formula/gnome-recipes.rb
  Formula/gucharmap.rb
  Formula/hadolint.rb
  Formula/libharu.rb
  Formula/luit.rb
  Formula/mame.rb
  Formula/maven@3.3.rb
  Formula/md5deep.rb
  Formula/multimarkdown.rb
  Formula/phpunit.rb
  Formula/rbspy.rb
  Formula/rom-tools.rb
  Formula/sqlite-analyzer.rb
  Formula/vala.rb
  Formula/valabind.rb
  Formula/vte3.rb
  Formula/wcslib.rb
  Formula/wsk.rb
Labels: merge

#9096 util-linux: Depends on python on Linux
  Formula/util-linux.rb
Labels: dependency

#9139 texinfo: Fix build error related to perl dependency
  Formula/texinfo.rb
Labels: build-error, dependency

#9220 Merge 2018-09-05 f57861d44f
  Formula/b2sum.rb
  Formula/braid.rb
  Formula/cadubi.rb
  Formula/cucumber-cpp.rb
  Formula/dnsviz.rb
  Formula/evince.rb
  Formula/gitlab-gem.rb
  Formula/haste-client.rb
  Formula/kontena.rb
  Formula/ldid.rb
  Formula/libstfl.rb
  Formula/logstash.rb
  Formula/mdxmini.rb
  Formula/mikutter.rb
  Formula/nsq.rb
  Formula/nxengine.rb
  Formula/osrm-backend.rb
  Formula/pijul.rb
  Formula/pygobject3.rb
  Formula/rclone.rb
  Formula/redpen.rb
  Formula/ruby.rb
  Formula/scw.rb
  Formula/swiftgen.rb
  Formula/terraform_landscape.rb
  Formula/woboq_codebrowser.rb
  Formula/wpscan.rb
Labels: merge

#9224 Merge 2018-09-05 371a5c80b6
  Aliases/rebar@2
  Formula/azure-cli.rb
  Formula/baobab.rb
  Formula/cmdshelf.rb
  Formula/dnstwist.rb
  Formula/dxpy.rb
  Formula/firebase-cli.rb
  Formula/fluent-bit.rb
  Formula/gedit.rb
  Formula/glslviewer.rb
  Formula/grpc.rb
  Formula/irssi.rb
  Formula/jenkins.rb
  Formula/ldid.rb
  Formula/lf.rb
  Formula/libxlsxwriter.rb
  Formula/mesos.rb
  Formula/metashell.rb
  Formula/pdns.rb
  Formula/pdnsrec.rb
  Formula/rebar3.rb
  Formula/skaffold.rb
  Formula/tile38.rb
  Formula/travis.rb
  Formula/uftp.rb
  Formula/wildfly-as.rb
  Formula/wine.rb
  Formula/zabbix.rb
  formula_renames.json
Labels: merge

#9238 Merge 2018-09-05 8aaf91f1e1
  Formula/adwaita-icon-theme.rb
  Formula/annie.rb
  Formula/at-spi2-core.rb
  Formula/badtouch.rb
  Formula/balance.rb
  Formula/convox.rb
  Formula/crystal.rb
  Formula/diff-pdf.rb
  Formula/dosbox.rb
  Formula/evince.rb
  Formula/file-roller.rb
  Formula/flake8.rb
  Formula/freediameter.rb
  Formula/gdrive.rb
  Formula/gearman.rb
  Formula/gitg.rb
  Formula/gmt.rb
  Formula/jbig2dec.rb
  Formula/jhipster.rb
  Formula/kakoune.rb
  Formula/ldc.rb
  Formula/libbi.rb
  Formula/libpsl.rb
  Formula/libsoup.rb
  Formula/llvm@5.rb
  Formula/nco.rb
  Formula/ncview.rb
  Formula/newsboat.rb
  Formula/nghttp2.rb
  Formula/oniguruma.rb
  Formula/pijul.rb
  Formula/pushpin.rb
  Formula/quicktype.rb
  Formula/range-v3.rb
  Formula/ruby@2.3.rb
  Formula/rust.rb
  Formula/sccache.rb
  Formula/ssh-permit-a38.rb
  Formula/tectonic.rb
  Formula/travis.rb
  Formula/unrar.rb
  Formula/unravel.rb
  Formula/wine.rb
  Formula/yelp-tools.rb
Labels: merge

#9254 Merge 2018-09-05 1e49b74a54
  Formula/cgal.rb
  Formula/citus.rb
  Formula/corectl.rb
  Formula/dante.rb
  Formula/dynare.rb
  Formula/euca2ools.rb
  Formula/fb-client.rb
  Formula/gf-complete.rb
  Formula/gmt@4.rb
  Formula/gnome-autoar.rb
  Formula/golang-migrate.rb
  Formula/gupnp-av.rb
  Formula/ios-deploy.rb
  Formula/jerm.rb
  Formula/jump.rb
  Formula/kore.rb
  Formula/libquicktime.rb
  Formula/mercurial.rb
  Formula/noweb.rb
  Formula/nss.rb
  Formula/openrtsp.rb
  Formula/pdftoedn.rb
  Formula/proof-general.rb
  Formula/pytouhou.rb
  Formula/range-v3.rb
  Formula/raylib.rb
  Formula/switchaudio-osx.rb
  Formula/tarsnap-gui.rb
  Formula/unbound.rb
  Formula/zero-install.rb
Labels: merge

#9261 Merge 2018-09-05 af0526bb48
  Aliases/v8@6.9
  Formula/bitwarden-cli.rb
  Formula/bzt.rb
  Formula/nats-streaming-server.rb
  Formula/v8.rb
  Formula/webpack.rb
  Formula/wireguard-tools.rb
  Formula/zsh.rb
Labels: merge

#9262 Merge 2018-09-06 6fa2094d50
  Formula/jsonrpc-glib.rb
  Formula/libdazzle.rb
  Formula/mongodb.rb
  Formula/pagmo.rb
  Formula/template-glib.rb
Labels: merge

#9269 Merge 2018-09-06 ed0ad3a220
  Formula/curl.rb
  Formula/git-ftp.rb
  Formula/shibboleth-sp.rb
  Formula/xml-tooling-c.rb
Labels: merge

#9271 Merge 2018-09-06 cec6e2d704
  Formula/caf.rb
  Formula/gauge.rb
  Formula/mmseqs2.rb
  Formula/php-cs-fixer.rb
  Formula/phpunit.rb
  Formula/topgrade.rb
Labels: merge

#9275 Merge 2018-09-06 93ad2d4665
  Formula/bash-snippets.rb
  Formula/bup.rb
  Formula/dar.rb
  Formula/git.rb
  Formula/groonga.rb
  Formula/libgetdata.rb
  Formula/nut.rb
  Formula/ola.rb
  Formula/opencolorio.rb
  Formula/pike.rb
  Formula/sphinx.rb
  Formula/sqlite.rb
  Formula/weechat.rb
  Formula/x3270.rb
  Formula/xapian.rb
  Formula/xplanet.rb
Labels: merge

#9276 Merge 2018-09-06 d12ed46391
  Formula/glfw.rb
  Formula/mupen64plus.rb
  Formula/postgres-xc.rb
  Formula/redland.rb
  Formula/vrpn.rb
Labels: merge

#9278 Merge 2018-09-06 19d06d96ab
  Formula/apr-util.rb
  Formula/gegl.rb
  Formula/ibex.rb
  Formula/mjpegtools.rb
  Formula/ngircd.rb
  Formula/open-scene-graph.rb
  Formula/shmcat.rb
  Formula/udunits.rb
Labels: merge

#9279 Merge 2018-09-06 735f5f5e3d
  Formula/aubio.rb
  Formula/libquicktime.rb
  Formula/teem.rb
  Formula/uwsgi.rb
Labels: merge

#9280 Merge 2018-09-06 ee48284f2e
  Formula/checkbashisms.rb
  Formula/iso-codes.rb
  Formula/jhipster.rb
  Formula/kakoune.rb
  Formula/libopendkim.rb
  Formula/sphinx-doc.rb
  Formula/swiftformat.rb
  Formula/xplanet.rb
  Formula/yarn.rb
Labels: merge

#9286 Merge 2018-09-06 d990848005
  Formula/agda.rb
  Formula/bitlbee.rb
  Formula/dovecot.rb
  Formula/ghc.rb
  Formula/hydra.rb
  Formula/mcabber.rb
  Formula/nsd.rb
  Formula/parrot.rb
  Formula/percona-server.rb
  Formula/pidgin.rb
  Formula/protobuf.rb
  Formula/pulseaudio.rb
  Formula/yarn.rb
  Formula/zookeeper.rb
Labels: merge

#9287 Merge 2018-09-06 183ab7a507
  Formula/erlang.rb
  Formula/gdal.rb
  Formula/gdk-pixbuf.rb
  Formula/geogram.rb
  Formula/gitg.rb
  Formula/glib-networking.rb
  Formula/glib.rb
  Formula/gsettings-desktop-schemas.rb
  Formula/gtksourceview3.rb
  Formula/gtksourceview@4.rb
  Formula/libucl.rb
  Formula/logtalk.rb
  Formula/meson-internal.rb
  Formula/octave.rb
  Formula/presto.rb
  Formula/prototool.rb
  Formula/tarantool.rb
Labels: merge

#9300 Merge 2018-09-07 c027050ee2
  Formula/kettle.rb
  Formula/libarchive.rb
Labels: merge

#9301 Merge 2018-09-07 155ea89029
  Formula/ccache.rb
  Formula/certbot.rb
  Formula/circleci.rb
  Formula/davmail.rb
  Formula/dhall-json.rb
  Formula/diffoscope.rb
  Formula/metabase.rb
  Formula/node.rb
  Formula/smali.rb
  Formula/trezor-agent.rb
Labels: merge

#9303 Merge 2018-09-07 018a182775
  Formula/bibutils.rb
  Formula/fdk-aac-encoder.rb
  Formula/gitbucket.rb
  Formula/libre.rb
Labels: merge

#9305 Merge 2018-09-07 469e9a657e
  Formula/gdk-pixbuf.rb
  Formula/glib.rb
Labels: merge

#9306 Merge 2018-09-08 6ca78aa85c
  Formula/mongodb@3.2.rb
  Formula/telnet.rb
Labels: merge

#9307 Merge 2018-09-08 469e24813c
  Formula/glide.rb
Labels: merge

#9309 Merge 2018-09-08 5df670e45b
  Formula/emscripten.rb
  Formula/gifski.rb
  Formula/hcloud.rb
Labels: merge

#9310 Merge 2018-09-08 c80e967fad
  Formula/ansible.rb
  Formula/apktool.rb
  Formula/aws-okta.rb
  Formula/awscli.rb
  Formula/cmake.rb
  Formula/fauna-shell.rb
  Formula/gdnsd.rb
  Formula/glide.rb
  Formula/globjects.rb
  Formula/gnu-indent.rb
  Formula/grafana.rb
  Formula/mpage.rb
  Formula/mpd.rb
  Formula/node-build.rb
  Formula/php.rb
  Formula/rclone.rb
  Formula/st.rb
  Formula/swiftformat.rb
  Formula/vault.rb
  Formula/vim.rb
Labels: merge

#9318 Merge 2018-09-08 ce9cf96c2a
  Formula/cloc.rb
  Formula/cmdshelf.rb
  Formula/glm.rb
  Formula/handbrake.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/mps-youtube.rb
  Formula/pdf-redact-tools.rb
  Formula/pdfsandwich.rb
  Formula/phpunit.rb
  Formula/ripgrep.rb
  Formula/skopeo.rb
  Formula/youtube-dl.rb
Labels: merge

#9324 Merge 2018-09-10 1ad2f971a0
  Formula/cquery.rb
  Formula/dcadec.rb
  Formula/docker-ls.rb
  Formula/docker-machine-driver-xhyve.rb
  Formula/dockviz.rb
  Formula/fairymax.rb
  Formula/hubflow.rb
  Formula/kibana@4.4.rb
  Formula/ldid.rb
  Formula/minio-mc.rb
  Formula/moz-git-tools.rb
  Formula/neatvi.rb
  Formula/openshift-cli.rb
  Formula/serialosc.rb
  Formula/source-to-image.rb
  Formula/spaceinvaders-go.rb
  Formula/stellar-core.rb
  Formula/teleconsole.rb
  Formula/torsocks.rb
  Formula/zsh-syntax-highlighting.rb
Labels: merge

#9325 Merge 2018-09-10 0f34fc1217
  Formula/annie.rb
  Formula/ghostscript.rb
  Formula/libspectre.rb
  Formula/pqiv.rb
Labels: merge

#9326 Merge 2018-09-11 baddc3e3cb
  Formula/at-spi2-atk.rb
  Formula/atk.rb
  Formula/eslint.rb
  Formula/mdcat.rb
  Formula/nano.rb
  Formula/terragrunt.rb
  Formula/ucloud.rb
  Formula/youtube-dl.rb
Labels: merge

#9327 Merge 2018-09-11 4d9dcbf849
  Formula/cairo.rb
  Formula/libimobiledevice.rb
  Formula/llvm@3.7.rb
  Formula/xmount.rb
  Formula/zig.rb
  formula_renames.json
Labels: merge

#9329 Merge 2018-09-11 a4c46d0a8b
  Formula/atomicparsley.rb
  Formula/cmake.rb
  Formula/graphite2.rb
  Formula/source-highlight.rb
Labels: merge

#9331 Merge 2018-09-11 1b30a21a5a
  Formula/double-conversion.rb
  Formula/folly.rb
  Formula/fonttools.rb
  Formula/kubernetes-cli.rb
  Formula/media-info.rb
  Formula/msgpack.rb
Labels: merge

#9332 Merge 2018-09-12 0c7d972043
  Formula/apache-drill.rb
  Formula/bwfmetaedit.rb
  Formula/cracklib.rb
  Formula/grunt-cli.rb
  Formula/kustomize.rb
  Formula/libphonenumber.rb
  Formula/lnav.rb
  Formula/logentries.rb
Labels: merge

#9333 Merge 2018-09-12 de7a2acf99
  Formula/geoipupdate.rb
  Formula/git.rb
  Formula/harfbuzz.rb
  Formula/mariadb@10.1.rb
  Formula/tor.rb
  Formula/upx.rb
  Formula/webpack.rb
  Formula/wskdeploy.rb
  Formula/zsh.rb
Labels: merge

#9334 Merge 2018-09-12 cea1258f66
  Formula/activemq.rb
  Formula/chronograf.rb
  Formula/folly.rb
  Formula/gutenberg.rb
  Formula/hlint.rb
  Formula/peru.rb
  Formula/the_platinum_searcher.rb
  Formula/watchexec.rb
  Formula/wireguard-tools.rb
Labels: merge

#9336 Merge 2018-09-12 619852b0e6
  Formula/curl.rb
  Formula/homebank.rb
  Formula/llvm.rb
  Formula/node@8.rb
  Formula/tomcat@6.rb
  Formula/tomcat@7.rb
Labels: merge

#9337 Merge 2018-09-12 34214b7217
  Formula/afflib.rb
  Formula/goreleaser.rb
  Formula/mongodb@3.4.rb
  Formula/pulumi.rb
Labels: merge

#9339 Merge 2018-09-12 25590710e3
  Formula/openssl@1.1.rb
Labels: merge

#9341 Merge 2018-09-12 ac705f81d5
  Formula/folly.rb
  Formula/heroku.rb
  Formula/pybind11.rb
  Formula/snapcraft.rb
  Formula/tippecanoe.rb
  Formula/tox.rb
Labels: merge

#9343 Merge 2018-09-12 969f49df56
  Formula/gcc@4.9.rb
  Formula/gcc@5.rb
Labels: merge

#9344 Merge 2018-09-12 64c2fecb1d
  Formula/caffe.rb
  Formula/gjstest.rb
  Formula/grpc.rb
  Formula/libphonenumber.rb
  Formula/mosh.rb
  Formula/packer.rb
  Formula/protobuf-c.rb
  Formula/protobuf-swift.rb
  Formula/protobuf.rb
  Formula/supersonic.rb
  Formula/zbackup.rb
Labels: merge

#9346 Merge 2018-09-12 cc2306ceea
  Formula/abyss.rb
  Formula/bettercap.rb
  Formula/pcre2.rb
Labels: merge

#9350 Merge 2018-09-12 cbe766be8e
  Formula/acme.rb
  Formula/astyle.rb
  Formula/ctags.rb
  Formula/dasm.rb
  Formula/dosbox.rb
  Formula/fuego.rb
  Formula/fuse-emulator.rb
  Formula/gmtl.rb
  Formula/gpsim.rb
  Formula/irrlicht.rb
  Formula/lasi.rb
  Formula/lcs.rb
  Formula/libspectrum.rb
  Formula/mediatomb.rb
  Formula/netpbm.rb
  Formula/npush.rb
  Formula/pdfsandwich.rb
  Formula/qmmp.rb
  Formula/quex.rb
  Formula/sdcc.rb
  Formula/spim.rb
  Formula/supermodel.rb
  Formula/synfig.rb
  Formula/sz81.rb
  Formula/teem.rb
  Formula/ucon64.rb
  Formula/xu4.rb
  Formula/zboy.rb
Labels: merge

#9351 Merge 2018-09-12 cf8b56ec30
  Formula/iperf.rb
  Formula/pulumi.rb
Labels: merge

#9352 Merge 2018-09-12 9332b2445b
  Formula/asciinema2gif.rb
  Formula/ffmbc.rb
  Formula/fuego.rb
  Formula/lcs.rb
  Formula/lean-cli.rb
  Formula/opencv@2.rb
  Formula/spim.rb
  Formula/webarchiver.rb
  Formula/xu4.rb
Labels: merge

#9354 Merge 2018-09-12 22569c484b
  Formula/fn.rb
  Formula/ocamlbuild.rb
  Formula/shogun.rb
Labels: merge

#9356 Merge 2018-09-12 5d963f682a
  Formula/bitrise.rb
  Formula/git.rb
  Formula/lxc.rb
  Formula/sphinx-doc.rb
  Formula/ttyd.rb
Labels: merge

#9357 Merge 2018-09-13 7997345198
  Formula/bitrise.rb
  Formula/llvm.rb
  Formula/lxc.rb
  Formula/sphinx-doc.rb
Labels: merge

#9366 Merge 2018-09-13 c754aa2ed2
  Formula/audacious.rb
  Formula/dcmtk.rb
  Formula/dtrx.rb
  Formula/freeciv.rb
  Formula/getdns.rb
  Formula/gnupg.rb
  Formula/imlib2.rb
  Formula/minetest.rb
  Formula/open-ocd.rb
  Formula/pqiv.rb
  Formula/qscintilla2.rb
  Formula/sdl_image.rb
  Formula/sdl_sound.rb
  Formula/swftools.rb
  Formula/upscaledb.rb
Labels: merge

#9367 Merge 2018-09-14 051833ca50
  Formula/llvm@5.rb
Labels: merge

#9368 Merge 2018-09-14 53a5615c2d
  Formula/llvm@4.rb
Labels: merge

#9369 Merge 2018-09-14 a834c83672
  Formula/llvm@3.9.rb
Labels: merge

#9370 Merge 2018-09-14 4364c86f90
  Formula/ii.rb
  Formula/root.rb
Labels: merge

#9371 Merge 2018-09-14 05ba2c3ddf
  Formula/audiofile.rb
  Formula/caf.rb
  Formula/freexl.rb
  Formula/ghc@8.2.rb
  Formula/git-credential-manager.rb
  Formula/gnu-smalltalk.rb
  Formula/gnuplot@4.rb
  Formula/google-sparsehash.rb
  Formula/jbigkit.rb
  Formula/libdap.rb
  Formula/libiscsi.rb
  Formula/libuv.rb
  Formula/ninja.rb
  Formula/protobuf@2.5.rb
  Formula/protobuf@2.6.rb
  Formula/protobuf@3.1.rb
Labels: merge

#9373 Merge 2018-09-14 d83284165f
  Formula/git-cola.rb
  Formula/glm.rb
  Formula/httest.rb
  Formula/libzdb.rb
  Formula/nuttcp.rb
  Formula/ocamlsdl.rb
  Formula/pyenv.rb
  Formula/rdup.rb
  Formula/sdl2_image.rb
  Formula/sha2.rb
  Formula/speex.rb
  Formula/stk.rb
  Formula/task.rb
  Formula/timidity.rb
  Formula/trafficserver.rb
  Formula/unicorn.rb
  Formula/wesnoth.rb
  Formula/wslay.rb
  Formula/xalan-c.rb
  Formula/xdelta.rb
  Formula/yaws.rb
  Formula/yosys.rb
  Formula/zyre.rb
Labels: merge

#9374 Merge 2018-09-14 be97c3162f
  Formula/bat.rb
  Formula/erlang.rb
  Formula/git-secret.rb
  Formula/php@7.0.rb
  Formula/php@7.1.rb
  Formula/picat.rb
  Formula/rust.rb
  Formula/stlink.rb
  Formula/swift-protobuf.rb
  Formula/webpack.rb
  Formula/xqilla.rb
Labels: merge

#9381 Merge 2018-09-14 3fd0f5f766
  Formula/brew-gem.rb
  Formula/bullet.rb
  Formula/carla.rb
  Formula/dpkg.rb
  Formula/fabric.rb
  Formula/gcc.rb
  Formula/ghostscript.rb
  Formula/gradle.rb
  Formula/hyperkit.rb
  Formula/john-jumbo.rb
  Formula/john.rb
  Formula/libspectre.rb
  Formula/logstalgia.rb
  Formula/mit-scheme.rb
  Formula/mmark.rb
  Formula/mpich.rb
  Formula/orc-tools.rb
  Formula/passwdqc.rb
  Formula/pgbadger.rb
  Formula/php.rb
  Formula/pqiv.rb
  Formula/selenium-server-standalone.rb
  Formula/wpscan.rb
Labels: merge

#9386 Merge 2018-09-14 34c78578de
  Formula/glm.rb
  Formula/webpack.rb
Labels: merge

#9388 Merge 2018-09-14 d203ae1b8e
  Formula/algol68g.rb
  Formula/asio.rb
  Formula/aubio.rb
  Formula/autopsy.rb
  Formula/bwctl.rb
  Formula/center-im.rb
  Formula/curseofwar.rb
  Formula/dex.rb
  Formula/eralchemy.rb
  Formula/fwknop.rb
  Formula/glulxe.rb
  Formula/homebank.rb
  Formula/httping.rb
  Formula/oysttyer.rb
  Formula/pinfo.rb
  Formula/povray.rb
  Formula/profanity.rb
Labels: merge

#9389 Merge 2018-09-14 78081d754a
  Formula/homebank.rb
  Formula/povray.rb
  Formula/profanity.rb
  Formula/pv.rb
  Formula/r3.rb
  Formula/repl.rb
  Formula/sfml.rb
  Formula/snappystream.rb
  Formula/texapp.rb
  Formula/tpp.rb
  Formula/uhd.rb
  Formula/urweb.rb
Labels: merge

#9393 Merge 2018-09-14 d196e1615d
  Formula/hyperestraier.rb
  Formula/idnits.rb
  Formula/imageworsener.rb
  Formula/imgur-screenshot.rb
  Formula/irods.rb
  Formula/john-jumbo.rb
  Formula/lensfun.rb
  Formula/libagg.rb
  Formula/libcanberra.rb
  Formula/libfishsound.rb
  Formula/libkate.rb
  Formula/libosinfo.rb
  Formula/mdxmini.rb
  Formula/mftrace.rb
  Formula/mydumper.rb
  Formula/oscats.rb
  Formula/sipp.rb
  Formula/tasksh.rb
  Formula/tig.rb
  Formula/wimlib.rb
  Formula/xboard.rb
Labels: merge

#9099 graphite2: Depends on freetype2 when built on Linux
  Formula/graphite2.rb
Labels: build-error, dependency

#9398 Merge 2018-09-15 2547ced8f7
  Formula/apr.rb
  Formula/consul.rb
  Formula/jenkins-lts.rb
  Formula/lz4.rb
  Formula/metabase.rb
  Formula/packer.rb
  Formula/rebar3.rb
  Formula/shellharden.rb
  Formula/vagrant-completion.rb
Labels: merge

#9407 Merge 2018-09-15 92cf5ea716
  Formula/fontforge.rb
  Formula/platypus.rb
  Formula/transmission.rb
  Formula/vfuse.rb
  Formula/wireshark.rb
Labels: merge

#9412 Merge 2018-09-16 cc1df0ccd8
  Formula/eslint.rb
  Formula/node@8.rb
  Formula/php@5.6.rb
  Formula/wine.rb
Labels: merge

#9415 Merge 2018-09-17 2530e06b3f
  Formula/annie.rb
  Formula/bbftp-client.rb
  Formula/codequery.rb
  Formula/dependency-check.rb
  Formula/double-conversion.rb
  Formula/dropbear.rb
  Formula/krakend.rb
  Formula/libmemcached.rb
  Formula/links.rb
  Formula/povray.rb
  Formula/stout.rb
  Formula/zpython.rb
Labels: merge

#9420 Merge 2018-09-17 d9ed4328af
  Formula/cabocha.rb
  Formula/gdk-pixbuf.rb
  Formula/libstfl.rb
  Formula/libtomcrypt.rb
  Formula/little-cms.rb
  Formula/little-cms2.rb
  Formula/luajit.rb
  Formula/mecab-ipadic.rb
  Formula/mecab-jumandic.rb
  Formula/nuxeo.rb
  Formula/ocp.rb
  Formula/openmsx.rb
  Formula/pkgdiff.rb
  Formula/rxvt-unicode.rb
  Formula/telegram-cli.rb
Labels: merge

#9421 Merge 2018-09-17 960f872640
  Formula/dbhash.rb
  Formula/gnu-smalltalk.rb
  Formula/luajit.rb
  Formula/sqldiff.rb
  Formula/sqlite-analyzer.rb
  Formula/sqlite.rb
  Formula/terragrunt.rb
  Formula/vim.rb
Labels: merge

#9425 Merge 2018-09-17 29c4cf3cea
  Formula/python.rb
  Formula/python@2.rb
Labels: merge

#9429 Merge 2018-09-17 0ace799ab3
  Formula/abcde.rb
  Formula/abuse.rb
  Formula/activemq-cpp.rb
  Formula/advancemame.rb
  Formula/adwaita-icon-theme.rb
  Formula/aescrypt-packetizer.rb
  Formula/asciidoc.rb
  Formula/awk.rb
  Formula/influxdb.rb
Labels: merge

#9430 Merge 2018-09-17 2e303aa57c
  Formula/aide.rb
  Formula/aircrack-ng.rb
  Formula/airspy.rb
  Formula/alure.rb
  Formula/anjuta.rb
  Formula/ansible-cmdb.rb
  Formula/ansible@1.9.rb
  Formula/ansible@2.0.rb
  Formula/appscale-tools.rb
  Formula/aqbanking.rb
  Formula/arangodb.rb
  Formula/arp-scan.rb
  Formula/arpack.rb
  Formula/asdf.rb
  Formula/asn1c.rb
  Formula/at-spi2-atk.rb
  Formula/at-spi2-core.rb
  Formula/atari800.rb
  Formula/aubio.rb
  Formula/audacious.rb
  Formula/augeas.rb
  Formula/avfs.rb
  Formula/avian.rb
  Formula/avrdude.rb
  Formula/avro-c.rb
  Formula/avro-cpp.rb
  Formula/aws-apigateway-importer.rb
Labels: merge

#9431 Merge 2018-09-17 eba9dbff63
  Formula/babl.rb
  Formula/bacula-fd.rb
  Formula/baobab.rb
  Formula/baresip.rb
  Formula/bdw-gc.rb
  Formula/bibtex2html.rb
  Formula/biogeme.rb
  Formula/btfs.rb
  Formula/bwm-ng.rb
  Formula/byobu.rb
  Formula/bzr-fastimport.rb
  Formula/c-ares.rb
  Formula/cadaver.rb
  Formula/caffe.rb
  Formula/cairo.rb
  Formula/cairomm.rb
  Formula/cassandra.rb
  Formula/cattle.rb
  Formula/ccache.rb
  Formula/cclive.rb
  Formula/cconv.rb
  Formula/cdrdao.rb
  Formula/cfengine.rb
  Formula/cgal.rb
  Formula/cgrep.rb
Labels: merge

#9432 Merge 2018-09-17 393a704bc5
  Formula/charm-tools.rb
  Formula/charm.rb
  Formula/chinadns-c.rb
  Formula/chocolate-doom.rb
  Formula/choose-gui.rb
  Formula/chruby-fish.rb
  Formula/clamav.rb
  Formula/cless.rb
  Formula/clhep.rb
  Formula/clutter-gst.rb
  Formula/clutter-gtk.rb
  Formula/clutter.rb
  Formula/cmockery2.rb
  Formula/cmu-sphinxbase.rb
  Formula/cmus.rb
  Formula/cnats.rb
  Formula/coccinelle.rb
  Formula/collada-dom.rb
  Formula/collectd.rb
  Formula/colortail.rb
  Formula/conjure-up.rb
  Formula/consul-backinator.rb
Labels: merge

#9433 Merge 2018-09-17 13337d34e0
  Formula/coq.rb
  Formula/corebird.rb
  Formula/corectl.rb
  Formula/coreutils.rb
  Formula/couchdb-lucene.rb
  Formula/couchdb.rb
  Formula/cppcms.rb
  Formula/cpprestsdk.rb
  Formula/cquery.rb
  Formula/credstash.rb
  Formula/cromwell.rb
  Formula/crosstool-ng.rb
  Formula/crush-tools.rb
  Formula/ctl.rb
  Formula/curl.rb
  Formula/curlftpfs.rb
  Formula/cutter.rb
  Formula/dark-mode.rb
  Formula/darkice.rb
  Formula/darkstat.rb
  Formula/dasht.rb
  Formula/dateutils.rb
  Formula/dbus-glib.rb
  Formula/dbxml.rb
  Formula/dcraw.rb
  Formula/ddar.rb
  Formula/deja-gnu.rb
  Formula/dfu-programmer.rb
  Formula/dgen.rb
  Formula/diff-pdf.rb
  Formula/diffoscope.rb
Labels: merge

#9434 Merge 2018-09-17 6afaae2e47
  Formula/djvulibre.rb
  Formula/dlib.rb
  Formula/dlite.rb
  Formula/dnscrypt-wrapper.rb
  Formula/dnsmasq.rb
  Formula/dnstwist.rb
  Formula/docker-cloud.rb
  Formula/docker-compose.rb
  Formula/docker-machine-driver-xhyve.rb
  Formula/docker-machine.rb
  Formula/dosbox-x.rb
  Formula/dosbox.rb
  Formula/dosfstools.rb
  Formula/doxygen.rb
  Formula/dropbear.rb
  Formula/druid.rb
  Formula/dsd.rb
  Formula/dub.rb
  Formula/duck.rb
  Formula/duplicity.rb
  Formula/dvdauthor.rb
  Formula/dynamips.rb
  Formula/easy-tag.rb
  Formula/echoprint-codegen.rb
  Formula/efl.rb
  Formula/einstein.rb
  Formula/ejabberd.rb
  Formula/ekg2.rb
  Formula/elm.rb
  Formula/emacs.rb
  Formula/ems-flasher.rb
  Formula/enchant.rb
  Formula/enigma.rb
  Formula/epeg.rb
  Formula/erlang.rb
  Formula/erlang@17.rb
  Formula/erlang@18.rb
  Formula/erlang@19.rb
  Formula/erlang@20.rb
Labels: merge

#9435 Merge 2018-09-17 79d02e8297
  Formula/evince.rb
  Formula/exif.rb
  Formula/exim.rb
  Formula/expect.rb
  Formula/ext2fuse.rb
  Formula/exult.rb
  Formula/eye-d3.rb
  Formula/ezstream.rb
  Formula/fabric.rb
  Formula/fastd.rb
  Formula/fcgiwrap.rb
  Formula/feh.rb
  Formula/ffmpeg.rb
  Formula/ffmpeg@2.8.rb
  Formula/ffmpegthumbnailer.rb
  Formula/ffms2.rb
  Formula/fftw.rb
  Formula/fibjs.rb
  Formula/file-roller.rb
  Formula/fizmo.rb
  Formula/flac123.rb
  Formula/flactag.rb
  Formula/flashrom.rb
  Formula/flex.rb
  Formula/fltk.rb
  Formula/fluid-synth.rb
  Formula/fmsx.rb
  Formula/folly.rb
  Formula/fontforge.rb
  Formula/fourstore.rb
  Formula/fox.rb
  Formula/freeciv.rb
  Formula/freedink.rb
  Formula/freeglut.rb
  Formula/freerdp.rb
  Formula/freeswitch.rb
  Formula/freetds.rb
  Formula/freetds@0.91.rb
  Formula/frugal.rb
  Formula/fs-uae.rb
  Formula/fstar.rb
  Formula/fstrm.rb
  Formula/ftimes.rb
  Formula/fuse-emulator.rb
Labels: merge

#9436 Merge 2018-09-17 4a725db4c8
  Formula/cabal-install.rb
  Formula/pandoc-citeproc.rb
  Formula/pandoc.rb
Labels: merge

#9444 Merge 2018-09-18 37e3db8be5
  Formula/hackrf.rb
  Formula/hatari.rb
  Formula/haxe.rb
  Formula/hbase.rb
  Formula/henplus.rb
  Formula/herrie.rb
  Formula/hesiod.rb
  Formula/hevea.rb
  Formula/hg-flow.rb
  Formula/hicolor-icon-theme.rb
  Formula/highlighting-kate.rb
  Formula/hive.rb
  Formula/htmlcompressor.rb
  Formula/htmldoc.rb
  Formula/httperf.rb
  Formula/huexpress.rb
  Formula/hydra.rb
  Formula/hyperscan.rb
  Formula/tiger-vnc.rb
Labels: merge

#9445 Merge 2018-09-18 19e088998e
  Formula/g3log.rb
  Formula/gammu.rb
  Formula/ganglia.rb
  Formula/gcc@6.rb
  Formula/gconf.rb
  Formula/gcsfuse.rb
  Formula/gdb.rb
  Formula/gdcm.rb
  Formula/gdk-pixbuf.rb
  Formula/gdl.rb
  Formula/gdmap.rb
  Formula/gearman.rb
  Formula/gedit.rb
  Formula/geeqie.rb
  Formula/gegl.rb
  Formula/geomview.rb
  Formula/get_iplayer.rb
  Formula/gexiv2.rb
  Formula/gforth.rb
  Formula/ghc.rb
  Formula/ghc@8.2.rb
  Formula/ghex.rb
  Formula/ghostscript.rb
  Formula/gitg.rb
  Formula/gitless.rb
  Formula/gjs.rb
  Formula/gjstest.rb
  Formula/gkrellm.rb
  Formula/glade.rb
  Formula/glib-networking.rb
  Formula/glib.rb
Labels: merge

#9446 Merge 2018-09-18 0ee7c1db8b
  Formula/glibmm.rb
  Formula/globjects.rb
  Formula/glyr.rb
  Formula/gmediaserver.rb
  Formula/gnome-autoar.rb
  Formula/gnome-builder.rb
  Formula/gnome-doc-utils.rb
  Formula/gnome-latex.rb
  Formula/gnome-recipes.rb
  Formula/gnome-themes-standard.rb
  Formula/gnu-apl.rb
  Formula/gnu-smalltalk.rb
  Formula/gnu-tar.rb
  Formula/gnumeric.rb
  Formula/gnupg-pkcs11-scd.rb
  Formula/gnuplot.rb
  Formula/gnuplot@4.rb
  Formula/gnuradio.rb
  Formula/gnutls.rb
  Formula/goaccess.rb
  Formula/gobby.rb
  Formula/gobject-introspection.rb
  Formula/gocr.rb
  Formula/gom.rb
  Formula/gosu.rb
  Formula/gource.rb
  Formula/gpac.rb
  Formula/gpgme.rb
  Formula/gprof2dot.rb
  Formula/gpsim.rb
  Formula/grace.rb
  Formula/graphene.rb
  Formula/graphviz.rb
  Formula/grpc.rb
  Formula/grsync.rb
  Formula/gsettings-desktop-schemas.rb
Labels: merge

#9447 Merge 2018-09-18 4e74aa738a
  Formula/gsmartcontrol.rb
  Formula/gssdp.rb
  Formula/gst-editing-services.rb
  Formula/gst-plugins-bad.rb
  Formula/gst-plugins-base.rb
  Formula/gst-plugins-good.rb
  Formula/gst-plugins-ugly.rb
  Formula/gst-python.rb
  Formula/gst-rtsp-server.rb
  Formula/gst-validate.rb
  Formula/gstreamermm.rb
  Formula/gtk+.rb
  Formula/gtk+3.rb
  Formula/gtk-doc.rb
  Formula/gtk-engines.rb
  Formula/gtk-mac-integration.rb
  Formula/gtk-murrine-engine.rb
  Formula/gtk-vnc.rb
  Formula/gtkmm.rb
  Formula/gtkmm3.rb
  Formula/gtksourceview.rb
  Formula/gtksourceview3.rb
  Formula/gtksourceview@4.rb
  Formula/gtksourceviewmm.rb
  Formula/gtksourceviewmm3.rb
  Formula/gtkspell3.rb
  Formula/gtmess.rb
  Formula/gucharmap.rb
  Formula/guile.rb
  Formula/guile@2.0.rb
  Formula/gupnp-av.rb
  Formula/gupnp-tools.rb
  Formula/gupnp.rb
  Formula/gwenhywfar.rb
  Formula/gxml.rb
Labels: merge

#9448 Merge 2018-09-18 8a5f29be25
  Formula/compcert.rb
  Formula/menhir.rb
Labels: merge

#9455 Merge 2018-09-18 ad0ddcf03d
  Formula/apollo.rb
  Formula/crystal.rb
  Formula/ettercap.rb
  Formula/gmic.rb
  Formula/graphicsmagick.rb
  Formula/harfbuzz.rb
  Formula/libgxps.rb
  Formula/libspatialite.rb
  Formula/libspectrum.rb
  Formula/percona-xtrabackup.rb
  Formula/pypy3.rb
Labels: merge

#9456 Merge 2018-09-18 70d37edfc7
  Formula/carla.rb
  Formula/git-lfs.rb
  Formula/pdf-redact-tools.rb
  Formula/pdfsandwich.rb
  Formula/prototool.rb
  Formula/vala.rb
  Formula/youtube-dl.rb
Labels: merge

#9459 Merge 2018-09-18 f3ff0cd822
  Formula/lablgtk.rb
  Formula/lasi.rb
  Formula/lasso.rb
  Formula/lastfmfpclient.rb
  Formula/latex2html.rb
  Formula/lcdproc.rb
  Formula/lcm.rb
  Formula/ld64.rb
  Formula/ldapvi.rb
  Formula/ledit.rb
  Formula/leptonica.rb
  Formula/lesstif.rb
  Formula/lftp.rb
  Formula/lhasa.rb
  Formula/libagar.rb
  Formula/libao.rb
  Formula/libass.rb
  Formula/libbladerf.rb
  Formula/libbpg.rb
  Formula/libcdr.rb
  Formula/libchamplain.rb
  Formula/libconfig.rb
  Formula/libcouchbase.rb
  Formula/libcroco.rb
  Formula/libdap.rb
  Formula/libdc1394.rb
  Formula/libetonyek.rb
  Formula/libewf.rb
  Formula/libfreehand.rb
  Formula/libgaiagraphics.rb
  Formula/lighttpd.rb
  Formula/lincity-ng.rb
  Formula/link-grammar.rb
  Formula/links.rb
  Formula/lldpd.rb
  Formula/lmod.rb
  Formula/lnav.rb
  Formula/logstalgia.rb
  Formula/loudmouth.rb
  Formula/lrdf.rb
  Formula/lsh.rb
  Formula/ltc-tools.rb
  Formula/luabind.rb
Labels: merge

#9460 Merge 2018-09-18 17f49db1d2
  Formula/libgda.rb
  Formula/libgdata.rb
  Formula/libgeotiff.rb
  Formula/libggz.rb
  Formula/libghthash.rb
  Formula/libgit2-glib.rb
  Formula/libgit2.rb
  Formula/libglade.rb
  Formula/libgnomecanvas.rb
  Formula/libgnomecanvasmm.rb
  Formula/libgphoto2.rb
  Formula/libgtop.rb
  Formula/libgweather.rb
  Formula/libgxps.rb
  Formula/libhttpserver.rb
  Formula/libhttpseverywhere.rb
  Formula/libimobiledevice.rb
  Formula/libinfinity.rb
  Formula/libiodbc.rb
  Formula/libjson-rpc-cpp.rb
  Formula/liblas.rb
  Formula/liblastfm.rb
  Formula/liblcf.rb
  Formula/liblunar.rb
  Formula/liblwgeom.rb
  Formula/libmp3splt.rb
  Formula/libmspub.rb
  Formula/libmypaint.rb
  Formula/libnet.rb
  Formula/libnfs.rb
  Formula/libnids.rb
  Formula/libodfgen.rb
  Formula/liboil.rb
  Formula/libopendkim.rb
  Formula/libopkele.rb
  Formula/libosmium.rb
  Formula/libpano.rb
  Formula/libphonenumber.rb
  Formula/libplist.rb
  Formula/libprotoident.rb
  Formula/libproxy.rb
  Formula/libpst.rb
Labels: merge

#9462 Merge 2018-09-18 1383c05987
  Formula/jfrog-cli-go.rb
  Formula/jhipster.rb
  Formula/nagios-plugins.rb
  Formula/nagios.rb
  Formula/nanopb-generator.rb
  Formula/nasm.rb
  Formula/ncdc.rb
  Formula/ncdu.rb
  Formula/ncmpcpp.rb
  Formula/ndpi.rb
  Formula/neko.rb
  Formula/neofetch.rb
  Formula/neovim.rb
  Formula/nesc.rb
  Formula/nestopia-ue.rb
  Formula/netcdf.rb
  Formula/netpbm.rb
  Formula/nghttp2.rb
  Formula/nicotine-plus.rb
  Formula/node-build.rb
Labels: merge

#9465 Merge 2018-09-18 689a3c9bec
  Formula/node.rb
  Formula/node@6.rb
  Formula/node@8.rb
  Formula/nordugrid-arc.rb
  Formula/nsq.rb
  Formula/ntfs-3g.rb
  Formula/ntopng.rb
  Formula/numpy.rb
  Formula/nutcracker.rb
  Formula/nvc.rb
  Formula/nzbget.rb
  Formula/objc-codegenutils.rb
  Formula/onepass.rb
  Formula/onscripter.rb
  Formula/open-babel.rb
  Formula/open-cobol.rb
  Formula/open-mpi.rb
  Formula/openal-soft.rb
  Formula/openclonk.rb
  Formula/opencv.rb
  Formula/openfortivpn.rb
  Formula/openjpeg.rb
  Formula/openldap.rb
  Formula/openrct2.rb
  Formula/opensaml.rb
  Formula/openslide.rb
  Formula/openttd.rb
  Formula/openvpn.rb
  Formula/opus-tools.rb
  Formula/osc.rb
  Formula/osm-gps-map.rb
  Formula/osm2pgsql.rb
  Formula/osmfilter.rb
  Formula/osquery.rb
  Formula/osrm-backend.rb
  Formula/osslsigncode.rb
  Formula/p11-kit.rb
  Formula/pam-u2f.rb
  Formula/pango.rb
  Formula/pangomm.rb
  Formula/paps.rb
  Formula/partio.rb
  Formula/pass.rb
  Formula/passenger.rb
  Formula/passpie.rb
  Formula/patchutils.rb
  Formula/pazpar2.rb
  Formula/pbrt.rb
  Formula/pc6001vx.rb
  Formula/pcb2gcode.rb
  Formula/pce.rb
  Formula/pcre.rb
  Formula/pdf-redact-tools.rb
  Formula/pdf2htmlex.rb
  Formula/pdf2image.rb
  Formula/pdfgrep.rb
  Formula/pdftoedn.rb
  Formula/pdns.rb
  Formula/pdnsrec.rb
Labels: merge

#9466 Merge 2018-09-18 349e5bad84
  Formula/percona-server-mongodb.rb
  Formula/percona-server.rb
  Formula/perkeep.rb
  Formula/pev.rb
  Formula/pgcli.rb
  Formula/pgloader.rb
  Formula/phantomjs.rb
  Formula/php.rb
  Formula/pianobar.rb
  Formula/pianod.rb
  Formula/pillar.rb
  Formula/pinentry.rb
  Formula/pioneer.rb
  Formula/pioneers.rb
  Formula/pktanon.rb
  Formula/pla.rb
  Formula/planck.rb
  Formula/pngpaste.rb
  Formula/poco.rb
  Formula/podofo.rb
  Formula/points2grid.rb
  Formula/ponyc.rb
  Formula/ponysay.rb
  Formula/poppler.rb
  Formula/postgis.rb
  Formula/povray.rb
  Formula/ppsspp.rb
  Formula/predictionio.rb
  Formula/prefixsuffix.rb
  Formula/psqlodbc.rb
  Formula/pstoedit.rb
  Formula/pure-ftpd.rb
  Formula/pushpin.rb
  Formula/putty.rb
  Formula/pwntools.rb
  Formula/pyexiv2.rb
  Formula/pygobject3.rb
  Formula/pygtk.rb
  Formula/pygtkglext.rb
  Formula/pygtksourceview.rb
  Formula/pypy.rb
  Formula/pytouhou.rb
  Formula/qca.rb
  Formula/qcli.rb
  Formula/qdae.rb
  Formula/qemu.rb
  Formula/qjackctl.rb
Labels: merge

#9467 Merge 2018-09-18 31ed413cfd
  Formula/qmmp.rb
  Formula/qt@5.5.rb
  Formula/quantlib.rb
  Formula/quilt.rb
  Formula/r.rb
  Formula/rabbitmq-c.rb
  Formula/radare2.rb
  Formula/rakudo-star.rb
  Formula/rbenv-ctags.rb
  Formula/rdup.rb
  Formula/redex.rb
  Formula/redis-leveldb.rb
  Formula/redshift.rb
  Formula/remctl.rb
  Formula/renameutils.rb
  Formula/rethinkdb.rb
  Formula/riak.rb
  Formula/riemann-client.rb
  Formula/rlwrap.rb
  Formula/rmlint.rb
  Formula/robot-framework.rb
  Formula/rocksdb.rb
  Formula/rofs-filtered.rb
  Formula/rom-tools.rb
  Formula/roswell.rb
  Formula/rp.rb
  Formula/rpm.rb
  Formula/rrdtool.rb
  Formula/ruby-build.rb
  Formula/rust.rb
  Formula/ry.rb
  Formula/s-lang.rb
  Formula/s3fs.rb
  Formula/saldl.rb
  Formula/salt.rb
  Formula/sane-backends.rb
  Formula/scalapack.rb
  Formula/scipy.rb
  Formula/scrollkeeper.rb
  Formula/scrub.rb
  Formula/scrypt.rb
  Formula/sdcc.rb
  Formula/sdcv.rb
  Formula/sdl2_ttf.rb
  Formula/sdl_ttf.rb
  Formula/serialosc.rb
  Formula/sha1dc.rb
Labels: merge

#9469 Merge 2018-09-18 4227e3e5d5
  Formula/sxiv.rb
  Formula/sync_gateway.rb
  Formula/synfig.rb
  Formula/sysbench.rb
  Formula/t1utils.rb
  Formula/tarsnap.rb
  Formula/tbb.rb
  Formula/tcpflow.rb
  Formula/tenyr.rb
  Formula/terminal-notifier.rb
  Formula/terminator.rb
  Formula/termius.rb
  Formula/texmath.rb
  Formula/theora.rb
  Formula/tiff2png.rb
  Formula/tiger-vnc.rb
  Formula/tlsdate.rb
  Formula/tmate.rb
  Formula/tomcat-native.rb
  Formula/tracebox.rb
  Formula/traildb.rb
  Formula/treefrog.rb
  Formula/ttfautohint.rb
  Formula/ttyd.rb
  Formula/ucg.rb
  Formula/ufraw.rb
  Formula/unac.rb
  Formula/unbound.rb
  Formula/unpaper.rb
  Formula/unrtf.rb
  Formula/upscaledb.rb
  Formula/urh.rb
  Formula/uriparser.rb
  Formula/usbmuxd.rb
  Formula/utimer.rb
  Formula/uwsgi.rb
  Formula/v8.rb
  Formula/vala.rb
  Formula/vamp-plugin-sdk.rb
  Formula/vapoursynth.rb
  Formula/varnish.rb
  Formula/varnish@4.rb
  Formula/vcs.rb
  Formula/verilator.rb
  Formula/vgmstream.rb
  Formula/vim.rb
  Formula/vim@7.4.rb
Labels: merge

#9470 Merge 2018-09-18 4de1a06503
  Formula/ettercap.rb
  Formula/graphicsmagick.rb
  Formula/vimpc.rb
  Formula/vis.rb
  Formula/volatility.rb
  Formula/voms.rb
  Formula/vorbis-tools.rb
  Formula/vorbisgain.rb
  Formula/vte.rb
  Formula/vte3.rb
  Formula/waon.rb
  Formula/watchman.rb
  Formula/wavpack.rb
  Formula/webalizer.rb
  Formula/weboob.rb
  Formula/wget.rb
  Formula/whois.rb
  Formula/widelands.rb
  Formula/wine.rb
  Formula/winexe.rb
  Formula/wmctrl.rb
  Formula/writerperfect.rb
  Formula/wslay.rb
  Formula/wv.rb
  Formula/wv2.rb
  Formula/x11vnc.rb
  Formula/xapian.rb
  Formula/xml-security-c.rb
  Formula/xml-tooling-c.rb
  Formula/xmoto.rb
  Formula/xshogi.rb
  Formula/xsw.rb
  Formula/xu4.rb
  Formula/yaz.rb
  Formula/yelp-tools.rb
  Formula/ykclient.rb
  Formula/ykman.rb
  Formula/ykneomgr.rb
  Formula/yle-dl.rb
  Formula/zbackup.rb
  Formula/zbar.rb
  Formula/zebra.rb
  Formula/zenity.rb
  Formula/zero-install.rb
  Formula/zile.rb
  Formula/zim.rb
  Formula/zmap.rb
  Formula/zookeeper.rb
  Formula/zorba.rb
  Formula/zpython.rb
Labels: merge

#9471 Merge 2018-09-18 92238e4425
  Formula/ace.rb
  Formula/asdf.rb
  Formula/aurora-cli.rb
  Formula/babel.rb
  Formula/fn.rb
  Formula/folly.rb
  Formula/hcloud.rb
  Formula/isync.rb
  Formula/json-glib.rb
  Formula/nwchem.rb
  Formula/smimesign.rb
  Formula/subversion.rb
Labels: merge

#9477 Merge 2018-09-18 12192e9c22
  Formula/gst-editing-services.rb
  Formula/gst-libav.rb
  Formula/gst-plugins-bad.rb
  Formula/gst-plugins-base.rb
  Formula/gst-plugins-good.rb
  Formula/gst-plugins-ugly.rb
  Formula/gst-python.rb
  Formula/gst-rtsp-server.rb
  Formula/gst-validate.rb
  Formula/gstreamer.rb
Labels: merge

#9480 Merge 2018-09-18 a180a510ca
  Formula/graphviz.rb
  Formula/libav.rb
  Formula/mpd.rb
  Formula/mysql-cluster.rb
  Formula/subversion.rb
Labels: merge

#9481 Merge 2018-09-18 4bd74e69ba
  Formula/fonttools.rb
  Formula/ranger.rb
  Formula/roswell.rb
  Formula/simutrans.rb
  Formula/skafos.rb
  Formula/svgo.rb
  Formula/webpack.rb
  Formula/wireguard-tools.rb
Labels: merge

#9487 Merge 2018-09-19 aac5f3f0ed
  Formula/harfbuzz.rb
  Formula/libav.rb
  Formula/mysql-cluster.rb
  Formula/subversion.rb
  Formula/subversion@1.8.rb
Labels: merge

#9488 Merge 2018-09-19 ade573f6fa
  Formula/angular-cli.rb
  Formula/erlang@20.rb
  Formula/faas-cli.rb
  Formula/homebank.rb
  Formula/mongodb@3.6.rb
  Formula/pcl.rb
Labels: merge

#9489 Merge 2018-09-19 4f77d466f4
  Formula/ace.rb
  Formula/dbhash.rb
  Formula/helmfile.rb
  Formula/sops.rb
  Formula/sqldiff.rb
  Formula/sqlite-analyzer.rb
  Formula/sqlite.rb
Labels: merge

#9493 Merge 2018-09-19 7c545396bc
  Formula/python.rb
  Formula/python@2.rb
Labels: merge

#9497 Merge 2018-09-19 1afd7d2e50
  Formula/avfs.rb
  Formula/cnats.rb
  Formula/cpmtools.rb
  Formula/gloox.rb
  Formula/lsh.rb
  Formula/makefile2graph.rb
  Formula/monitoring-plugins.rb
  Formula/namazu.rb
  Formula/ncdc.rb
  Formula/ogmtools.rb
  Formula/onioncat.rb
  Formula/pazpar2.rb
  Formula/pound.rb
  Formula/scummvm-tools.rb
  Formula/somagic.rb
  Formula/stone.rb
  Formula/sword.rb
  Formula/twemcache.rb
  Formula/whitedb.rb
  Formula/zebra.rb
  Formula/zorba.rb
Labels: merge

#9486 wxmac: Depends on linuxbrew/xorg/libsm [Linux]
  Formula/wxmac.rb
Labels: bug

#9503 Merge 2018-09-19 c0399af143
  Formula/bullet.rb
  Formula/libgeotiff.rb
  Formula/libphonenumber.rb
  Formula/ntopng.rb
  Formula/proj.rb
  Formula/pulumi.rb
  Formula/root.rb
  Formula/rustup-init.rb
  Formula/skaffold.rb
  Formula/xcodegen.rb
Labels: merge

#9509 Merge 2018-09-20 56c500b569
  Formula/qt.rb
Labels: merge

#9514 Merge 2018-09-21 22d52eff99
  Formula/ark.rb
  Formula/bind.rb
  Formula/convox.rb
  Formula/hapi-fhir-cli.rb
  Formula/nano.rb
  Formula/ntopng.rb
  Formula/prettier.rb
  Formula/vips.rb
Labels: merge

#9516 Merge 2018-09-21 115b8a2b90
  Aliases/elasticsearch@6.4
  Aliases/kibana@6.4
  Formula/aravis.rb
  Formula/bitcoin.rb
  Formula/brotli.rb
  Formula/chapel.rb
  Formula/coffeescript.rb
  Formula/duplicity.rb
  Formula/elasticsearch.rb
  Formula/git-archive-all.rb
  Formula/glances.rb
  Formula/gradle.rb
  Formula/graphviz.rb
  Formula/kibana.rb
  Formula/libmodplug.rb
  Formula/logstash.rb
  Formula/mosquitto.rb
  Formula/nng.rb
  Formula/node.rb
  Formula/oclgrind.rb
  Formula/sfcgal.rb
  Formula/tor.rb
  Formula/woff2.rb
  Formula/wtf.rb
  Formula/xerces-c.rb
  Formula/xsd.rb
  Formula/xtensor.rb
Labels: merge

#9529 Merge 2018-09-21 a32c1f73ba
  Formula/cabocha.rb
  Formula/cattle.rb
  Formula/curaengine.rb
  Formula/dartsim.rb
  Formula/dbxml.rb
  Formula/eventlog.rb
  Formula/exim.rb
  Formula/getdns.rb
  Formula/gptfdisk.rb
  Formula/graph-tool.rb
  Formula/gupnp-tools.rb
  Formula/ical-buddy.rb
  Formula/juise.rb
  Formula/kibana@5.6.rb
  Formula/landscaper.rb
  Formula/liberasurecode.rb
  Formula/libghthash.rb
  Formula/libgtop.rb
  Formula/libodfgen.rb
  Formula/librem.rb
  Formula/llvm@3.9.rb
  Formula/mdbtools.rb
  Formula/mkvalidator.rb
  Formula/monero.rb
Labels: merge

#9536 Merge 2018-09-24 bd29bc2b97
  Formula/cargo-completion.rb
  Formula/cash-cli.rb
  Formula/dub.rb
  Formula/hwloc.rb
  Formula/kumo.rb
  Formula/llvm.rb
  Formula/llvm@6.rb
  Formula/mdds.rb
  Formula/pre-commit.rb
  Formula/spotbugs.rb
  Formula/twarc.rb
Labels: merge

#9543 Merge 2018-09-24 a7bd8d98eb
  Formula/afsctool.rb
  Formula/amqp-cpp.rb
  Formula/apache-arrow.rb
  Formula/arangodb.rb
  Formula/auditbeat.rb
  Formula/avra.rb
  Formula/aws-apigateway-importer.rb
  Formula/blahtexml.rb
  Formula/boost-python3.rb
  Formula/boost@1.60.rb
  Formula/caf.rb
  Formula/cairomm.rb
  Formula/camlp5.rb
  Formula/cataclysm.rb
  Formula/clingo.rb
  Formula/cracklib.rb
  Formula/dbxml.rb
  Formula/dosbox-x.rb
  Formula/dynare.rb
  Formula/ed.rb
  Formula/enigma.rb
  Formula/erlang@17.rb
  Formula/erlang@18.rb
  Formula/erlang@19.rb
Labels: merge

#9544 Merge 2018-09-24 0824ba70ee
  Formula/exim.rb
  Formula/fastbit.rb
  Formula/findutils.rb
  Formula/folly.rb
  Formula/gammaray.rb
  Formula/gcc.rb
  Formula/gcc@4.9.rb
  Formula/gcc@5.rb
  Formula/gcc@6.rb
  Formula/gcc@7.rb
  Formula/gdb.rb
  Formula/geeqie.rb
  Formula/ghostscript.rb
  Formula/gjs.rb
  Formula/glfw.rb
  Formula/gnu-indent.rb
  Formula/gnu-sed.rb
  Formula/gnu-units.rb
  Formula/gnu-which.rb
  Formula/go@1.8.rb
  Formula/gobby.rb
  Formula/graph-tool.rb
  Formula/graphite2.rb
  Formula/groonga.rb
  Formula/hercules.rb
  Formula/hidapi.rb
  Formula/imake.rb
  Formula/inspircd.rb
  Formula/ios-deploy.rb
  Formula/ipmiutil.rb
  Formula/ircd-hybrid.rb
  Formula/john-jumbo.rb
  Formula/jsoncpp.rb
  Formula/jsonnet.rb
  Formula/kafka.rb
  Formula/ld64.rb
  Formula/ldc.rb
  Formula/ledger.rb
  Formula/libcec.rb
  Formula/libgda.rb
  Formula/libvoikko.rb
  Formula/llvm.rb
  Formula/llvm@6.rb
  Formula/mame.rb
  Formula/mapcrafter.rb
  Formula/memcached.rb
  Formula/mesos.rb
  Formula/minisat.rb
  Formula/mongo-cxx-driver.rb
  Formula/mongodb@3.0.rb
  Formula/mono.rb
  Formula/mysql.rb
  Formula/ncmpcpp.rb
  Formula/nordugrid-arc.rb
  Formula/nzbget.rb
  Formula/ocaml.rb
  Formula/opencv.rb
  Formula/openssh.rb
  Formula/openvdb.rb
  Formula/osquery.rb
Labels: merge

#9548 Merge 2018-09-25 313c6b81ce
  Formula/pdftoedn.rb
  Formula/pdnsrec.rb
  Formula/percona-server.rb
  Formula/percona-server@5.6.rb
  Formula/phantomjs.rb
  Formula/php.rb
  Formula/php@5.6.rb
  Formula/php@7.0.rb
  Formula/php@7.1.rb
  Formula/pioneers.rb
  Formula/ponyc.rb
  Formula/proj.rb
  Formula/protobuf-swift.rb
  Formula/protobuf.rb
  Formula/protobuf@2.6.rb
Labels: merge

#9550 Merge 2018-09-25 b75d621331
  Formula/jenkins.rb
  Formula/qemu.rb
  Formula/renameutils.rb
  Formula/rocksdb.rb
  Formula/root.rb
  Formula/shogun.rb
  Formula/slashem.rb
  Formula/solid.rb
  Formula/sphinx.rb
  Formula/subversion.rb
  Formula/subversion@1.8.rb
  Formula/swift.rb
  Formula/synfig.rb
  Formula/tesseract.rb
  Formula/tinyproxy.rb
  Formula/tomcat@7.rb
  Formula/tracebox.rb
  Formula/treefrog.rb
  Formula/ttfautohint.rb
  Formula/unnethack.rb
  Formula/upscaledb.rb
  Formula/vc4asm.rb
  Formula/vim.rb
  Formula/wellington.rb
  Formula/wget.rb
  Formula/wine.rb
  Formula/winexe.rb
  Formula/wireshark.rb
  Formula/xalan-c.rb
  Formula/xmoto.rb
  Formula/xsd.rb
  Formula/xtensor.rb
  Formula/yconalyzer.rb
  Formula/yosys.rb
  Formula/zile.rb
  Formula/zmap.rb
Labels: merge

#9551 Merge 2018-09-25 ee8abf7341
  Formula/erlang@19.rb
  Formula/pandoc-crossref.rb
Labels: merge

#9554 Merge 2018-09-25 b191a89728
  Formula/baresip.rb
  Formula/cattle.rb
  Formula/eventlog.rb
  Formula/libghthash.rb
  Formula/mrboom.rb
  Formula/node@6.rb
  Formula/open-scene-graph.rb
  Formula/pony-stable.rb
  Formula/ponyc.rb
  Formula/portmidi.rb
  Formula/postgres-xc.rb
  Formula/premake.rb
  Formula/reminiscence.rb
  Formula/restund.rb
  Formula/setweblocthumb.rb
  Formula/sratoolkit.rb
  Formula/stubby.rb
  Formula/thors-serializer.rb
  Formula/unison.rb
  Formula/writerperfect.rb
Labels: merge

#9555 Merge 2018-09-25 109d5f10e0
  Formula/arpack.rb
  Formula/elasticsearch@5.6.rb
  Formula/fmsx.rb
  Formula/futhark.rb
  Formula/gawk.rb
  Formula/geckodriver.rb
  Formula/jerasure.rb
  Formula/kibana@5.6.rb
  Formula/libgtop.rb
  Formula/opam.rb
  Formula/paket.rb
  Formula/pincaster.rb
  Formula/ruby@1.8.rb
  Formula/ruby@2.2.rb
  Formula/skafos.rb
  Formula/telnetd.rb
  Formula/tomcat@7.rb
  Formula/tomcat@8.rb
Labels: merge

#9556 Merge 2018-09-25 60a233f583
  Formula/gawk.rb
  Formula/gnu-indent.rb
  Formula/gnu-time.rb
  Formula/gnu-units.rb
  Formula/gnu-which.rb
Labels: merge

#9561 Merge 2018-09-25 d2239bd458
  Formula/azure-cli.rb
  Formula/cargo-completion.rb
  Formula/duck.rb
  Formula/fn.rb
  Formula/grpc.rb
  Formula/libcouchbase.rb
  Formula/libuv.rb
  Formula/megatools.rb
  Formula/pgrouting.rb
  Formula/rust.rb
  Formula/sphinx-doc.rb
  Formula/telegraf.rb
Labels: merge

#9571 Merge 2018-09-26 8b44f8f69c
  Formula/gdb.rb
  Formula/ghostscript.rb
  Formula/tor.rb
Labels: merge

#9575 Merge 2018-09-26 7448f70832
  Formula/aws-shell.rb
  Formula/bat.rb
  Formula/diceware.rb
  Formula/diffoscope.rb
  Formula/help2man.rb
  Formula/httpd.rb
  Formula/kustomize.rb
  Formula/parallel.rb
  Formula/sourcery.rb
Labels: merge

#9577 Merge 2018-09-26 88505eeebc
  Formula/arangodb.rb
  Formula/avfs.rb
  Formula/cairo.rb
  Formula/crowdin.rb
  Formula/dartsim.rb
  Formula/fossil.rb
  Formula/fzy.rb
  Formula/gjs.rb
  Formula/grakn.rb
  Formula/hugo.rb
  Formula/immortal.rb
  Formula/lynis.rb
  Formula/nlopt.rb
  Formula/postgis.rb
  Formula/pyinvoke.rb
  Formula/pyside.rb
  Formula/stunnel.rb
  Formula/vnu.rb
Labels: merge

#9580 Merge 2018-09-26 93faf13b41
  Formula/abcl.rb
  Formula/aqbanking.rb
  Formula/argus-clients.rb
  Formula/bro.rb
  Formula/chocolate-doom.rb
  Formula/fabio.rb
  Formula/fceux.rb
  Formula/feh.rb
  Formula/gammaray.rb
  Formula/gammu.rb
  Formula/gdnsd.rb
  Formula/gjs.rb
  Formula/gprof2dot.rb
  Formula/gtk-mac-integration.rb
  Formula/http_load.rb
  Formula/irssi.rb
  Formula/itpp.rb
  Formula/jigdo.rb
  Formula/knot-resolver.rb
  Formula/kube-ps1.rb
  Formula/lbdb.rb
  Formula/libbluray.rb
  Formula/libdivecomputer.rb
  Formula/libebur128.rb
  Formula/libnids.rb
  Formula/libplist.rb
  Formula/librdkafka.rb
  Formula/libxmlsec1.rb
  Formula/links.rb
  Formula/luaradio.rb
Labels: merge

#9581 Merge 2018-09-26 593c763c5a
  Formula/abcm2ps.rb
  Formula/allegro.rb
  Formula/anjuta.rb
  Formula/aria2.rb
  Formula/arp-scan.rb
  Formula/avrdude.rb
  Formula/avro-c.rb
  Formula/bind.rb
  Formula/bubbros.rb
  Formula/bulk_extractor.rb
  Formula/clamav.rb
  Formula/giflossy.rb
  Formula/gocr.rb
  Formula/gtk-vnc.rb
  Formula/libgsf.rb
  Formula/libucl.rb
  Formula/libuvc.rb
  Formula/libwbxml.rb
  Formula/libzzip.rb
  Formula/makepkg.rb
  Formula/mikutter.rb
  Formula/mkvtomp4.rb
  Formula/newlisp.rb
  Formula/nicotine-plus.rb
  Formula/normalize.rb
  Formula/onscripter.rb
  Formula/openjpeg.rb
  Formula/osm2pgsql.rb
  Formula/paket.rb
  Formula/pianod.rb
  Formula/psqlodbc.rb
  Formula/pwntools.rb
  Formula/pytouhou.rb
  Formula/qcachegrind.rb
  Formula/ry.rb
  Formula/s-lang.rb
  Formula/shairport.rb
  Formula/smpeg.rb
  Formula/spdylay.rb
  Formula/stlink.rb
  Formula/superlu.rb
  Formula/tenyr.rb
  Formula/the_silver_searcher.rb
  Formula/urh.rb
  Formula/vorbis-tools.rb
  Formula/wdiff.rb
  Formula/xmoto.rb
  Formula/yafc.rb
  Formula/ykpers.rb
Labels: merge

#9582 Merge 2018-09-26 bc97105dea
  Formula/abcm2ps.rb
  Formula/allegro.rb
  Formula/anjuta.rb
  Formula/aria2.rb
  Formula/arp-scan.rb
  Formula/avrdude.rb
  Formula/avro-c.rb
  Formula/bind.rb
  Formula/bubbros.rb
  Formula/bulk_extractor.rb
  Formula/clamav.rb
  Formula/giflossy.rb
  Formula/gocr.rb
  Formula/gtk-vnc.rb
  Formula/libgsf.rb
  Formula/libucl.rb
  Formula/libuvc.rb
  Formula/libwbxml.rb
  Formula/libzzip.rb
  Formula/makepkg.rb
  Formula/qcachegrind.rb
  Formula/s-lang.rb
  Formula/shairport.rb
  Formula/smpeg.rb
  Formula/stlink.rb
  Formula/superlu.rb
  Formula/urh.rb
  Formula/vorbis-tools.rb
  Formula/wdiff.rb
Labels: merge

#9595 Merge 2018-09-26 3a49bddd81
  Formula/diff-pdf.rb
  Formula/pdftoedn.rb
  Formula/pdftoipe.rb
  Formula/poppler.rb
Labels: merge

#9607 Merge 2018-09-26 03c0cf6b5b
  Formula/ark.rb
  Formula/clang-format.rb
  Formula/gcc@4.9.rb
  Formula/gcc@5.rb
  Formula/gtk-mac-integration.rb
  Formula/kerl.rb
  Formula/mariadb@10.2.rb
  Formula/nginx.rb
  Formula/prometheus.rb
  Formula/protobuf-swift.rb
  Formula/stellar-core.rb
  Formula/tcpflow.rb
  Formula/weaver.rb
  Formula/xonsh.rb
  Formula/yarn.rb
Labels: merge

#9615 Merge 2018-09-26 a2aa4aecd9
  Formula/chronograf.rb
  Formula/chruby-fish.rb
  Formula/fontforge.rb
  Formula/get_iplayer.rb
  Formula/gnuradio.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/llnode.rb
  Formula/macvim.rb
  Formula/mkvtoolnix.rb
  Formula/mpv.rb
  Formula/neofetch.rb
  Formula/node-build.rb
  Formula/postgis.rb
  Formula/pre-commit.rb
  Formula/pypy.rb
  Formula/ruby-build.rb
  Formula/termius.rb
Labels: merge

#9616 Merge 2018-09-27 ff5429b605
  Formula/cromwell.rb
  Formula/fn.rb
  Formula/glide.rb
  Formula/kubernetes-helm.rb
  Formula/nifi-registry.rb
Labels: merge

#9617 Merge 2018-09-27 a8b53d6a39
  Formula/bdw-gc.rb
  Formula/black.rb
  Formula/folly.rb
  Formula/gitless.rb
  Formula/kotlin.rb
  Formula/languagetool.rb
  Formula/libmodbus.rb
  Formula/mosquitto.rb
  Formula/mujs.rb
  Formula/sops.rb
  Formula/webpack.rb
  Formula/wtf.rb
Labels: merge

#9623 Merge 2018-09-27 eeb085c401
  Formula/gflags.rb
  Formula/glib.rb
  Formula/httperf.rb
  Formula/hyperscan.rb
  Formula/ledger.rb
  Formula/leveldb.rb
  Formula/liblas.rb
  Formula/libmikmod.rb
  Formula/mosh.rb
  Formula/mutt.rb
  Formula/mysql.rb
  Formula/mysql@5.5.rb
  Formula/mysql@5.6.rb
  Formula/mysql@5.7.rb
  Formula/node@6.rb
  Formula/node@8.rb
  Formula/perl.rb
  Formula/pyqt.rb
  Formula/sdl2.rb
  Formula/snort.rb
  Formula/wget.rb
  Formula/znc.rb
Labels: merge

#9624 Merge 2018-09-28 0fcf275fae
  Formula/afuse.rb
  Formula/app-engine-java.rb
  Formula/archivemount.rb
  Formula/bindfs.rb
  Formula/btfs.rb
  Formula/cryfs.rb
  Formula/curlftpfs.rb
  Formula/dislocker.rb
  Formula/djmount.rb
  Formula/encfs.rb
  Formula/ext2fuse.rb
  Formula/ext4fuse.rb
  Formula/fuse-zip.rb
  Formula/ifuse.rb
  Formula/mp3fs.rb
  Formula/ntfs-3g.rb
  Formula/ori.rb
  Formula/rofs-filtered.rb
  Formula/s3-backer.rb
  Formula/s3fs.rb
  Formula/securefs.rb
  Formula/simple-mtpfs.rb
  Formula/squashfuse.rb
  Formula/sshfs.rb
  Formula/terragrunt.rb
  Formula/tup.rb
  Formula/wdfs.rb
  Formula/xmount.rb
Labels: merge

#9626 Merge 2018-09-28 d9f0b79fe5
  Aliases/solr@7.5
  Formula/alexjs.rb
  Formula/bazel.rb
  Formula/faas-cli.rb
  Formula/git-archive-all.rb
  Formula/iamy.rb
  Formula/jmeter.rb
  Formula/kubernetes-service-catalog-client.rb
  Formula/libgda.rb
  Formula/mame.rb
  Formula/nim.rb
  Formula/pass.rb
  Formula/rtags.rb
  Formula/saxon.rb
  Formula/scala.rb
  Formula/skaffold.rb
  Formula/solr.rb
  Formula/typescript.rb
  Formula/wrk.rb
Labels: merge

#9637 Merge 2018-09-28 7f189c5816
  Aliases/ipython@7
  Formula/bower.rb
  Formula/caffe.rb
  Formula/calc.rb
  Formula/calicoctl.rb
  Formula/clamav.rb
  Formula/exiftool.rb
  Formula/gnumeric.rb
  Formula/ipython.rb
  Formula/kubernetes-cli.rb
  Formula/liblas.rb
  Formula/mit-scheme.rb
  Formula/ssldump.rb
  Formula/sysbench.rb
  Formula/vtk.rb
  Formula/zig.rb
Labels: merge

#9642 Merge 2018-09-29 f3d5acb045
  Formula/efl.rb
  Formula/ettercap.rb
  Formula/ledger.rb
  Formula/libopkele.rb
  Formula/pixz.rb
  Formula/pyqt.rb
  Formula/redis@2.8.rb
  Formula/smlnj.rb
  formula_renames.json
Labels: merge

#9645 Merge 2018-09-30 5b43a2eaf0
  Formula/babel.rb
  Formula/eslint.rb
  Formula/grv.rb
  Formula/pulumi.rb
  Formula/quicktype.rb
  Formula/swiftformat.rb
  Formula/swiftgen.rb
Labels: merge

#9648 Merge 2018-09-30 4bf16ba433
  Formula/ansible.rb
  Formula/evince.rb
  Formula/glances.rb
  Formula/mallet.rb
  Formula/pandoc.rb
Labels: merge
