Repository Homebrew/linuxbrew-core, pull requests merged in 2018-08, with the labels that each got.

#8678 Merge 2018-08-01 a3cbd45296
  Formula/arangodb.rb
  Formula/asdf.rb
  Formula/consul.rb
  Formula/docfx.rb
  Formula/firebase-cli.rb
  Formula/fn.rb
  Formula/folly.rb
  Formula/fwup.rb
  Formula/gradio.rb
  Formula/gst-editing-services.rb
  Formula/gupnp.rb
  Formula/haproxy.rb
  Formula/hive.rb
  Formula/nsd.rb
  Formula/pango.rb
  Formula/pazpar2.rb
  Formula/pgpool-ii.rb
  Formula/prettier.rb
  Formula/sbt.rb
  Formula/swiftformat.rb
  Formula/teleport.rb
  Formula/tippecanoe.rb
  Formula/typescript.rb
  Formula/xonsh.rb
Labels: merge

#8691 Merge 2018-08-01 8b3fbf236e
  Formula/abcm2ps.rb
  Formula/azure-cli.rb
  Formula/buildifier.rb
  Formula/ethereum.rb
  Formula/faas-cli.rb
  Formula/fabric.rb
  Formula/freeimage.rb
  Formula/gcc.rb
  Formula/gdb.rb
  Formula/gdbm.rb
  Formula/lsof.rb
  Formula/mill.rb
  Formula/minimal-racket.rb
  Formula/mitmproxy.rb
  Formula/nativefier.rb
  Formula/pegtl.rb
  Formula/pyinvoke.rb
  Formula/re2.rb
  Formula/redex.rb
  Formula/root.rb
  Formula/shellharden.rb
  Formula/sundials.rb
  Formula/sysdig.rb
  Formula/tbox.rb
  Formula/terragrunt.rb
  Formula/wireguard-tools.rb
Labels: merge

#8710 Merge 2018-08-02 a5013437ba
  Formula/qemu.rb
Labels: merge

#8711 Merge 2018-08-02 375047ce19
  Formula/confluent-oss.rb
  Formula/hugo.rb
  Formula/mercurial.rb
  Formula/node.rb
  Formula/openimageio.rb
  Formula/quicktype.rb
  Formula/swiftformat.rb
  Formula/zabbix.rb
Labels: merge

#8712 Merge 2018-08-02 d30f231bf0
  Formula/leiningen.rb
  Formula/zsh-lovers.rb
Labels: merge

#8713 Merge 2018-08-02 bec0145d38
  Formula/angle-grinder.rb
  Formula/angular-cli.rb
  Formula/cryptol.rb
  Formula/faas-cli.rb
  Formula/firebase-cli.rb
  Formula/libpst.rb
  Formula/logtalk.rb
  Formula/mariadb@10.0.rb
  Formula/passenger.rb
Labels: merge

#8714 Merge 2018-08-02 dca9e616ae
  Formula/cassandra.rb
  Formula/harfbuzz.rb
  Formula/pilosa.rb
  Formula/snakemake.rb
  Formula/trafficserver.rb
  Formula/uhd.rb
  Formula/xtensor.rb
  Formula/zebra.rb
Labels: merge

#8721 Merge 2018-08-03 b05fe03369
  Formula/abcde.rb
  Formula/csvprintf.rb
  Formula/django-completion.rb
  Formula/flow.rb
  Formula/git-lfs.rb
  Formula/gtk-vnc.rb
  Formula/imagesnap.rb
  Formula/kotlin.rb
  Formula/node-build.rb
  Formula/presto.rb
  Formula/taskell.rb
Labels: merge

#8726 Merge 2018-08-04 573250f7c2
  Formula/gammaray.rb
  Formula/go-statik.rb
  Formula/grpc.rb
  Formula/hashcat.rb
  Formula/knot-resolver.rb
  Formula/ocrmypdf.rb
  Formula/proselint.rb
  Formula/skaffold.rb
  Formula/teleport.rb
  Formula/vcftools.rb
  Formula/webpack.rb
Labels: merge

#8727 Merge 2018-08-04 704471a8fe
  Formula/cython.rb
  Formula/dartsim.rb
  Formula/dxpy.rb
  Formula/openshift-cli.rb
  Formula/shibboleth-sp.rb
  Formula/taskell.rb
  Formula/wireguard-tools.rb
  Formula/xml-security-c.rb
Labels: merge

#8728 Merge 2018-08-04 2ddc180ae6
  Formula/cargo-completion.rb
  Formula/paket.rb
  Formula/rust.rb
  Formula/tmux-xpanes.rb
Labels: merge

#8731 Merge 2018-08-04 c1e2120401
  Formula/erlang@20.rb
  Formula/gptfdisk.rb
  Formula/libcanberra.rb
  Formula/liquigraph.rb
  Formula/nnn.rb
  Formula/swig.rb
  Formula/yarn.rb
  Formula/youtube-dl.rb
  tap_migrations.json
Labels: merge

#8738 Merge 2018-08-05 65dbae7112
  Formula/mkdocs.rb
  Formula/percona-server-mongodb.rb
  Formula/redis.rb
  Formula/sceptre.rb
  Formula/tox.rb
  Formula/wxmac.rb
Labels: merge

#8740 Merge 2018-08-06 e7099f630e
  Formula/annie.rb
  Formula/go-bindata.rb
  Formula/go-jira.rb
  Formula/maven@3.0.rb
  Formula/maven@3.1.rb
  Formula/maven@3.2.rb
  Formula/msitools.rb
  Formula/pkcs11-helper.rb
  Formula/rabbitmq.rb
  Formula/reattach-to-user-namespace.rb
  Formula/ruby-install.rb
  Formula/swiftformat.rb
  Formula/taskell.rb
Labels: merge

#8756 Merge 2018-08-07 678657865e
  Formula/openapi-generator.rb
  README.md
Labels: merge

#8758 Merge 2018-08-08 b834b490a2
  Formula/composer.rb
  Formula/goenv.rb
  Formula/grakn.rb
  Formula/jhipster.rb
  Formula/jlog.rb
  Formula/kubectx.rb
  Formula/mint.rb
  Formula/pandoc.rb
  Formula/phpunit.rb
  Formula/sbt.rb
  Formula/tarantool.rb
  Formula/vim.rb
Labels: merge

#8766 Merge 2018-08-09 086d2700d2
  Formula/angband.rb
  Formula/duck.rb
  Formula/platformio.rb
  Formula/pre-commit.rb
  Formula/the_silver_searcher.rb
  Formula/tippecanoe.rb
  Formula/twarc.rb
  Formula/yara.rb
Labels: merge

#8773 Merge 2018-08-10 83955f540a
  Formula/annie.rb
  Formula/app-engine-python.rb
  Formula/appscale-tools.rb
  Formula/argyll-cms.rb
  Formula/bash-completion@2.rb
  Formula/cmark-gfm.rb
  Formula/docker-credential-helper.rb
  Formula/eccodes.rb
  Formula/folly.rb
  Formula/fontconfig.rb
  Formula/fwknop.rb
  Formula/gitlab-gem.rb
  Formula/gutenberg.rb
  Formula/hashcat.rb
  Formula/hcloud.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/kubernetes-cli.rb
  Formula/libvirt.rb
  Formula/libwps.rb
  Formula/llvm.rb
  Formula/mingw-w64.rb
  Formula/rakudo-star.rb
  Formula/restic.rb
  Formula/root.rb
Labels: merge

#8785 Merge 2018-08-10 eaf201828d
  Formula/ace.rb
  Formula/advancemame.rb
  Formula/apache-arrow-glib.rb
  Formula/apache-arrow.rb
  Formula/artifactory.rb
  Formula/badtouch.rb
  Formula/binaryen.rb
  Formula/black.rb
  Formula/bowtie2.rb
  Formula/creduce.rb
  Formula/fabric.rb
  Formula/gnupg@1.4.rb
  Formula/gst-plugins-good.rb
  Formula/harfbuzz.rb
  Formula/helmfile.rb
  Formula/infrakit.rb
  Formula/jboss-forge.rb
  Formula/kubernetes-service-catalog-client.rb
  Formula/micronaut.rb
  Formula/safe.rb
  Formula/sfst.rb
  Formula/swiftformat.rb
  Formula/upx.rb
  Formula/weaver.rb
  Formula/yarn-completion.rb
Labels: merge

#8790 Merge 2018-08-10 62b087d495
  Formula/apache-flink.rb
  Formula/convox.rb
  Formula/folly.rb
  Formula/gimme.rb
  Formula/gst-plugins-bad.rb
  Formula/gtk-mac-integration.rb
  Formula/harfbuzz.rb
  Formula/icdiff.rb
  Formula/libgsf.rb
  Formula/lsusb.rb
  Formula/mariadb@10.1.rb
  Formula/mint.rb
  Formula/perl-build.rb
  Formula/presto.rb
  Formula/qemu.rb
  Formula/quicktype.rb
  Formula/s-nail.rb
  Formula/safe.rb
  Formula/sbt.rb
  Formula/scrcpy.rb
  Formula/serverless.rb
  Formula/swift.rb
  Formula/sysdig.rb
  Formula/weechat.rb
  Formula/xsimd.rb
Labels: merge

#8802 Merge 2018-08-11 a7678c47ae
  Formula/armadillo.rb
  Formula/ballerina.rb
  Formula/bzip2.rb
  Formula/cmark-gfm.rb
  Formula/discount.rb
  Formula/druid.rb
  Formula/erlang@20.rb
  Formula/git-extras.rb
  Formula/kontena.rb
  Formula/libpq.rb
  Formula/libpqxx.rb
  Formula/librealsense.rb
  Formula/lynis.rb
  Formula/nnn.rb
  Formula/postgresql.rb
  Formula/postgresql@9.4.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
  Formula/range-v3.rb
  Formula/stone-soup.rb
  Formula/swiftformat.rb
  Formula/wireguard-tools.rb
  Formula/xtensor.rb
Labels: merge

#8814 Merge 2018-08-11 97a95dae8a
  Formula/angular-cli.rb
  Formula/dartsim.rb
  Formula/exploitdb.rb
  Formula/goreleaser.rb
  Formula/grails.rb
  Formula/jfrog-cli-go.rb
  Formula/kubernetes-service-catalog-client.rb
  Formula/libtensorflow.rb
  Formula/mkvtoolnix.rb
  Formula/opencoarrays.rb
  Formula/schismtracker.rb
  Formula/teleport.rb
  Formula/terragrunt.rb
  Formula/tox.rb
  Formula/twoping.rb
  Formula/ubertooth.rb
  Formula/xsane.rb
Labels: merge

#8823 Merge 2018-08-12 7e45a1d56e
  Formula/acpica.rb
  Formula/activemq.rb
  Formula/annie.rb
  Formula/ark.rb
  Formula/closure-compiler.rb
  Formula/erlang.rb
  Formula/exomizer.rb
  Formula/go.rb
  Formula/ocaml.rb
  Formula/sshguard.rb
  Formula/zero-install.rb
Labels: merge

#8831 Merge 2018-08-12 ddb17a02ea
  Formula/b2-tools.rb
  Formula/checkstyle.rb
  Formula/dynare.rb
  Formula/erlang@19.rb
  Formula/fdclone.rb
  Formula/glib-networking.rb
  Formula/memcached.rb
  Formula/nco.rb
  Formula/octave.rb
  Formula/osmium-tool.rb
  Formula/p11-kit.rb
  Formula/translate-shell.rb
  Formula/twoping.rb
  Formula/webdis.rb
Labels: merge

#8842 perl: Call setup_build_environment(self) [Linux]
  Formula/perl.rb
Labels: bug, build-error

#8845 Merge 2018-08-13 abb40bed2e
  Formula/automake.rb
  Formula/bdw-gc.rb
  Formula/byobu.rb
  Formula/bzip2.rb
  Formula/commandbox.rb
  Formula/ddclient.rb
  Formula/di.rb
  Formula/dmd.rb
  Formula/folly.rb
  Formula/fselect.rb
  Formula/gnu-smalltalk.rb
  Formula/hadoop.rb
  Formula/infer.rb
  Formula/mint.rb
  Formula/mkcert.rb
  Formula/mono.rb
  Formula/pcapplusplus.rb
  Formula/plank.rb
  Formula/sqoop.rb
  Formula/tokei.rb
  Formula/tty-solitaire.rb
  Formula/vsts-cli.rb
  Formula/xonsh.rb
Labels: merge

#8860 Remove all uses of OS::NAME
  Formula/android-platform-tools.rb
  Formula/blahtexml.rb
  Formula/caddy.rb
  Formula/chapel.rb
  Formula/chicken.rb
  Formula/devd.rb
  Formula/fibjs.rb
  Formula/go.rb
  Formula/go@1.9.rb
  Formula/openshift-cli.rb
  Formula/packer.rb
  Formula/serf.rb
  Formula/source-to-image.rb
  Formula/terraform.rb
Labels: enhancement

#8863 valgrind: Guard MaximumMacOSRequirement [Linux]
  Formula/valgrind.rb
Labels: enhancement

#8865 Merge 2018-08-14 80c9256239
  Aliases/v8@6.8
  Formula/cockroach.rb
  Formula/dateutils.rb
  Formula/docfx.rb
  Formula/geoipupdate.rb
  Formula/gjstest.rb
  Formula/hadolint.rb
  Formula/hh.rb
  Formula/jenkins.rb
  Formula/jhipster.rb
  Formula/libqalculate.rb
  Formula/lighttpd.rb
  Formula/metabase.rb
  Formula/mongoose.rb
  Formula/nsd.rb
  Formula/pgbouncer.rb
  Formula/rtv.rb
  Formula/sleuthkit.rb
  Formula/sonarqube.rb
  Formula/v8.rb
  Formula/zanata-client.rb
Labels: merge

#8877 Merge 2018-08-15 c3eff47949
  Formula/azure-cli.rb
  Formula/babl.rb
  Formula/beast.rb
  Formula/convox.rb
  Formula/cquery.rb
  Formula/firebase-cli.rb
  Formula/fortio.rb
  Formula/fselect.rb
  Formula/genometools.rb
  Formula/geoipupdate.rb
  Formula/groovy.rb
  Formula/groovysdk.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/influxdb.rb
  Formula/libical.rb
  Formula/libslax.rb
  Formula/linkerd.rb
  Formula/lxc.rb
  Formula/mongoose.rb
  Formula/mysql-cluster.rb
  Formula/mysql-connector-c.rb
  Formula/neo4j.rb
  Formula/node.rb
  Formula/ocrmypdf.rb
  Formula/openssl.rb
  Formula/openssl@1.1.rb
  Formula/protobuf-c.rb
  Formula/suite-sparse.rb
  Formula/wtf.rb
Labels: merge

#8894 Merge 2018-08-16 2136d1e911
  Formula/expat.rb
  Formula/gcc@6.rb
  Formula/git-archive-all.rb
  Formula/git-flow-avh.rb
  Formula/graphite2.rb
  Formula/harfbuzz.rb
  Formula/heroku.rb
  Formula/ios-webkit-debug-proxy.rb
  Formula/libatomic_ops.rb
  Formula/libpcap.rb
  Formula/macvim.rb
  Formula/mariadb@10.2.rb
  Formula/mkdocs.rb
  Formula/mujs.rb
  Formula/openapi-generator.rb
  Formula/prest.rb
  Formula/roswell.rb
  Formula/swift-protobuf.rb
  Formula/sysdig.rb
  Formula/terragrunt.rb
  Formula/thors-serializer.rb
  Formula/you-get.rb
Labels: merge

#8909 Merge 2018-08-16 002112bf96
  Formula/armadillo.rb
  Formula/convox.rb
  Formula/erlang@20.rb
  Formula/firebase-cli.rb
  Formula/fwup.rb
  Formula/gambit.rb
  Formula/gimme.rb
  Formula/go.rb
  Formula/goreleaser.rb
  Formula/hadoop.rb
  Formula/igv.rb
  Formula/jenkins-lts.rb
  Formula/jenkins.rb
  Formula/kafka.rb
  Formula/libomp.rb
  Formula/libslax.rb
  Formula/libswiftnav.rb
  Formula/makedepend.rb
  Formula/mariadb.rb
  Formula/mkl-dnn.rb
  Formula/ntp.rb
  Formula/openssl.rb
  Formula/pc6001vx.rb
  Formula/pkg-config.rb
  Formula/skktools.rb
  Formula/telegraf.rb
  Formula/terraform.rb
  Formula/vegeta.rb
Labels: merge

#8920 Merge 2018-08-16 686caa3e0e
  Formula/ansible-cmdb.rb
  Formula/chakra.rb
  Formula/kops.rb
Labels: merge

#8921 Merge 2018-08-17 1d5b386e96
  Formula/autoconf.rb
  Formula/automake.rb
  Formula/cmake.rb
  Formula/coreutils.rb
  Formula/dep.rb
  Formula/fribidi.rb
  Formula/gdbm.rb
  Formula/gettext.rb
  Formula/git-imerge.rb
  Formula/git.rb
  Formula/glide.rb
  Formula/gmp.rb
  Formula/hub.rb
  Formula/icu4c.rb
  Formula/jansson.rb
  Formula/jemalloc.rb
  Formula/jpeg.rb
  Formula/lame.rb
  Formula/launchdns.rb
  Formula/libffi.rb
  Formula/libgpg-error.rb
  Formula/libidn2.rb
  Formula/libpng.rb
  Formula/libssh2.rb
  Formula/libtasn1.rb
  Formula/libtiff.rb
  Formula/libtool.rb
  Formula/libunistring.rb
  Formula/lzip.rb
  Formula/mas.rb
  Formula/nasm.rb
  Formula/nginx.rb
  Formula/oniguruma.rb
  Formula/pcre.rb
  Formula/readline.rb
  Formula/redis.rb
  Formula/sphinx-doc.rb
  Formula/sqlite.rb
  Formula/texi2html.rb
  Formula/webp.rb
  Formula/xvid.rb
  Formula/xz.rb
Labels: merge

#8924 Merge 2018-08-17 379b9d6ef5
  Formula/adns.rb
  Formula/asciidoc.rb
  Formula/atomicparsley.rb
  Formula/boost.rb
  Formula/docbook.rb
  Formula/doxygen.rb
  Formula/freetype.rb
  Formula/libassuan.rb
  Formula/nettle.rb
  Formula/p11-kit.rb
  Formula/python.rb
  Formula/python@2.rb
  Formula/ragel.rb
  Formula/rust.rb
  Formula/x264.rb
Labels: merge

#8925 Merge 2018-08-17 836f4870e9
  Formula/arangodb.rb
  Formula/composer.rb
  Formula/geoipupdate.rb
  Formula/rancher-cli.rb
  Formula/rsyslog.rb
  Formula/yara.rb
Labels: merge

#8926 Merge 2018-08-17 138f45af65
  Formula/docbook-xsl.rb
  Formula/ffmpeg.rb
  Formula/gd.rb
  Formula/gnutls.rb
  Formula/libevent.rb
  Formula/libgcrypt.rb
  Formula/libksba.rb
  Formula/libusb.rb
  Formula/npth.rb
  Formula/pinentry.rb
  Formula/python.rb
  Formula/python@2.rb
Labels: merge

#8928 Merge 2018-08-18 df96223959
  Formula/cash-cli.rb
  Formula/kustomize.rb
  Formula/lsyncd.rb
  Formula/net-snmp.rb
  Formula/wine.rb
  formula_renames.json
Labels: merge

#8929 Merge 2018-08-18 4e6387ea41
  Formula/amber.rb
  Formula/armadillo.rb
  Formula/bitrise.rb
  Formula/crystal.rb
  Formula/hugo.rb
  Formula/imageoptim-cli.rb
  Formula/libyaml.rb
  Formula/nagios.rb
  Formula/pkcs11-helper.rb
  Formula/pulumi.rb
  Formula/qemu.rb
  Formula/termius.rb
  tap_migrations.json
Labels: merge

#8949 Merge 2018-08-18 f36ed07966
  Formula/python.rb
  Formula/python@2.rb
Labels: merge

#8952 Merge 2018-08-19 aeb9cefe98
  Formula/flow.rb
  Formula/goenv.rb
  Formula/heroku.rb
  Formula/mosquitto.rb
  Formula/wine.rb
Labels: merge

#8953 Merge 2018-08-19 8304fe23df
  Formula/gcc.rb
Labels: merge

#8963 Merge 2018-08-19 47f4f1aeb4
  Formula/bash-completion.rb
  Formula/binutils.rb
  Formula/cairo.rb
  Formula/camlp4.rb
  Formula/cscope.rb
  Formula/dnsmasq.rb
  Formula/docker-machine.rb
  Formula/duck.rb
  Formula/efl.rb
  Formula/emacs.rb
  Formula/fibjs.rb
  Formula/fluent-bit.rb
  Formula/fzf.rb
  Formula/gawk.rb
  Formula/gegl.rb
  Formula/ghostscript.rb
  Formula/git-lfs.rb
  Formula/glibmm.rb
  Formula/go.rb
  Formula/gocryptfs.rb
  Formula/gtk-vnc.rb
  Formula/hicolor-icon-theme.rb
  Formula/leptonica.rb
  Formula/libcroco.rb
  Formula/libev.rb
  Formula/libimobiledevice.rb
  Formula/libphonenumber.rb
  Formula/memcached.rb
  Formula/metis.rb
  Formula/midnight-commander.rb
  Formula/mpd.rb
  Formula/ninja.rb
  Formula/nmap.rb
  Formula/nyancat.rb
  Formula/ocamlbuild.rb
  Formula/openjpeg.rb
  Formula/openvdb.rb
  Formula/osmium-tool.rb
  Formula/parallel.rb
  Formula/percona-server@5.6.rb
  Formula/perltidy.rb
  Formula/plotutils.rb
  Formula/portaudio.rb
  Formula/pstoedit.rb
  Formula/radare2.rb
  Formula/s-lang.rb
  Formula/shared-mime-info.rb
  Formula/suite-sparse.rb
  Formula/swiftlint.rb
  Formula/tig.rb
  Formula/tor.rb
  Formula/unibilium.rb
  Formula/zsh-syntax-highlighting.rb
Labels: merge

#8968 Merge 2018-08-20 56f05a1afc
  Formula/alpine.rb
  Formula/arpoison.rb
  Formula/autoconf-archive.rb
  Formula/bazel.rb
  Formula/bench.rb
  Formula/berkeley-db.rb
  Formula/cgal.rb
  Formula/cloc.rb
  Formula/cowsay.rb
  Formula/cunit.rb
  Formula/epstool.rb
  Formula/ethereum.rb
  Formula/fd.rb
  Formula/fdk-aac-encoder.rb
  Formula/fdk-aac.rb
  Formula/fig2dev.rb
  Formula/fswatch.rb
  Formula/gl2ps.rb
  Formula/glew.rb
  Formula/gpp.rb
  Formula/inetutils.rb
  Formula/iperf3.rb
  Formula/jmeter.rb
  Formula/libgeotiff.rb
  Formula/libgit2.rb
  Formula/librdkafka.rb
  Formula/lrzsz.rb
  Formula/lua@5.1.rb
  Formula/lynx.rb
  Formula/mad.rb
  Formula/make.rb
  Formula/mujs.rb
  Formula/mutt.rb
  Formula/mysql-client.rb
  Formula/mysql-connector-c++.rb
  Formula/mysql-connector-c.rb
  Formula/nano.rb
  Formula/neofetch.rb
  Formula/nghttp2.rb
  Formula/openvpn.rb
  Formula/potrace.rb
  Formula/pwgen.rb
  Formula/qemu.rb
  Formula/qhull.rb
  Formula/qpdf.rb
  Formula/reattach-to-user-namespace.rb
  Formula/rename.rb
  Formula/ripgrep.rb
  Formula/rlwrap.rb
  Formula/screenresolution.rb
  Formula/tesseract.rb
  Formula/texinfo.rb
  Formula/tokyo-cabinet.rb
  Formula/x265.rb
  Formula/zlib.rb
Labels: merge

#8971 Merge 2018-08-20 8429d9e993
  Formula/firebase-cli.rb
  Formula/ntl.rb
  Formula/singular.rb
  Formula/vegeta.rb
Labels: merge

#8976 Revert "glibc: update 2.23_1 bottle for Linuxbrew"
  Formula/glibc.rb
Labels: bug

#8981 Merge 2018-08-21 310736cc7c
  Formula/gnumeric.rb
  Formula/goffice.rb
  Formula/liquidprompt.rb
  Formula/naturaldocs.rb
Labels: merge

#8984 glib-openssl: Fix test for Linux
  Formula/glib-openssl.rb
Labels: test-failure

#8983 mono: Depends on python@2 unzip to build [Linux]
  Formula/mono.rb
Labels: bottle, dependency

#8988 hugo: Merge 2018-08-22 5d19d42b49
  Formula/hugo.rb
Labels: merge

#8996 Merge 2018-08-22 6d47b51bb2
  Formula/corsixth.rb
  Formula/lmod.rb
  Formula/lua.rb
  Formula/lua@5.1.rb
  Formula/luarocks.rb
  Formula/neovim.rb
  Formula/sile.rb
  Formula/vis.rb
Labels: merge

#8997 gmt@4: Merge 2018-08-22 cf7e2b9083
  Formula/gmt@4.rb
Labels: merge

#9000 folly: Merge 2018-08-22 80ae04a872
  Formula/folly.rb
Labels: merge

#9007 qtkeychain: Fix test for Linux
  Formula/qtkeychain.rb
Labels: test-failure

#9016 xqilla: Fix test for Linux
  Formula/xqilla.rb
Labels: test-failure

#9018 ode: Fix test [Linux]
  Formula/ode.rb
Labels: test-failure

#9019 whois: Fix test for Linux
  Formula/whois.rb
Labels: test-failure

#9020 Merge 2018-08-23 eea44928f3
  Formula/cmus.rb
  Formula/console_bridge.rb
  Formula/docker-credential-helper.rb
  Formula/docker-machine-driver-hyperkit.rb
  Formula/espeak.rb
  Formula/hackrf.rb
  Formula/hexgui.rb
  Formula/mailutils.rb
  Formula/mariadb-connector-c.rb
  Formula/mongo-c-driver.rb
  Formula/mongodb@3.0.rb
  Formula/mongoose.rb
  Formula/msmtp.rb
  Formula/mupdf.rb
  Formula/planck.rb
  Formula/pure-ftpd.rb
  Formula/rancher-cli.rb
  Formula/rename.rb
  Formula/superlu.rb
  Formula/swi-prolog.rb
  Formula/util-linux.rb
Labels: merge

#9040 Merge 2018-08-24 e6dfc574b6
  Formula/dxpy.rb
  Formula/mkdocs.rb
  Formula/mlkit.rb
  Formula/osquery.rb
Labels: merge

#9041 open-mpi: Merge 2018-08-24 0618f66ec7
  Formula/open-mpi.rb
Labels: merge

#9044 boost-python: Fix test [Linux]
  Formula/boost-python.rb
Labels: good, test-failure

#9050 git-review: Fix test for Linux
  Formula/git-review.rb
Labels: good, test-failure

#9052 jenkins-job-builder: Fix test for Linux
  Formula/jenkins-job-builder.rb
Labels: good, test-failure

#9054 llvm@4: Fix test for Linux
  Formula/llvm@4.rb
Labels: test-failure

#9055 llvm@5: Fix test for Linux
  Formula/llvm@5.rb
Labels: test-failure

#9065 Merge 2018-08-24 d9bfb163ae
  Formula/kubectx.rb
  Formula/openssh.rb
  Formula/sbcl.rb
  Formula/ssh-copy-id.rb
Labels: merge

#9067 go: Merge 2018-08-25 674513c718
  Aliases/go@1.11
  Formula/go.rb
  Formula/godep.rb
Labels: merge

#9123 libjson-rpc-cpp: add missing dependency [Linux]
  Formula/libjson-rpc-cpp.rb
Labels: dependency

#9125 Merge 2018-08-28 62b9eb5fd1
  Formula/alot.rb
  Formula/armadillo.rb
  Formula/azure-cli.rb
  Formula/blitzwave.rb
  Formula/convox.rb
  Formula/field3d.rb
  Formula/flann.rb
  Formula/gconf.rb
  Formula/gnome-builder.rb
  Formula/gnome-latex.rb
  Formula/gpredict.rb
  Formula/gupnp.rb
  Formula/kallisto.rb
  Formula/kore.rb
  Formula/libchamplain.rb
  Formula/libmatio.rb
  Formula/libofx.rb
  Formula/libsecret.rb
  Formula/libslax.rb
  Formula/lilv.rb
  Formula/lincity-ng.rb
  Formula/livestreamer.rb
  Formula/luit.rb
  Formula/lumo.rb
  Formula/metaproxy.rb
  Formula/minbif.rb
  Formula/neomutt.rb
  Formula/netcdf.rb
  Formula/ola.rb
  Formula/opam.rb
  Formula/poppler.rb
  Formula/tarsnap-gui.rb
  Formula/topgrade.rb
Labels: merge

#9127 sphinx-doc: Merge 2018-08-28 147e7632a2
  Formula/sphinx-doc.rb
Labels: merge

#9128 Merge 2018-08-28 2a6d1cee10
  Aliases/bison@3.1
  Formula/alexjs.rb
  Formula/babel.rb
  Formula/bat.rb
  Formula/bison.rb
  Formula/doctl.rb
  Formula/erlang@20.rb
  Formula/fauna-shell.rb
  Formula/ghostscript.rb
  Formula/haxe.rb
  Formula/influxdb.rb
  Formula/jfrog-cli-go.rb
  Formula/ldc.rb
  Formula/nginx.rb
  Formula/pyside.rb
  Formula/re2c.rb
  Formula/tsung.rb
  Formula/urbit.rb
  Formula/wemux.rb
  Formula/xorriso.rb
Labels: merge

#9140 Merge 2018-08-28 cda3775e98
  Formula/bwfmetaedit.rb
  Formula/p11-kit.rb
Labels: merge

#9141 Merge 2018-08-28 46582c655b
  Formula/helmfile.rb
  Formula/mkvtoolnix.rb
  Formula/smlnj.rb
Labels: merge

#9147 Merge 2018-08-29 6ff8b8e4e1
  Formula/angle-grinder.rb
  Formula/badtouch.rb
  Formula/bat.rb
  Formula/click.rb
  Formula/dssim.rb
  Formula/fd.rb
  Formula/fselect.rb
  Formula/geckodriver.rb
  Formula/genact.rb
  Formula/gifski.rb
  Formula/git-series.rb
  Formula/grafana.rb
  Formula/gutenberg.rb
  Formula/hugo.rb
  Formula/hyperfine.rb
  Formula/just.rb
  Formula/ktmpl.rb
  Formula/libofx.rb
  Formula/loc.rb
  Formula/mdcat.rb
  Formula/miniserve.rb
  Formula/pijul.rb
  Formula/pngquant.rb
  Formula/ripgrep.rb
  Formula/rustup-init.rb
  Formula/sccache.rb
  Formula/shellharden.rb
  Formula/ssh-permit-a38.rb
  Formula/svgcleaner.rb
  Formula/tectonic.rb
  Formula/tokei.rb
  Formula/topgrade.rb
  Formula/watchexec.rb
  Formula/xsv.rb
Labels: merge

#9150 Merge 2018-08-29 0259c66b03
  Formula/cmocka.rb
  Formula/gradle.rb
  Formula/llvm.rb
  Formula/openblas.rb
  Formula/terragrunt.rb
Labels: merge

#9151 Merge 2018-08-29 fbba734507
  Formula/bro.rb
  Formula/check_postgres.rb
  Formula/ephemeralpg.rb
  Formula/exercism.rb
  Formula/gomplate.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/kapacitor.rb
  Formula/libpqxx.rb
  Formula/libzdb.rb
  Formula/mobiledevice.rb
  Formula/postgresql.rb
  Formula/postgresql@9.4.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
  Formula/sbcl.rb
  Formula/sourcery.rb
  Formula/telegraf.rb
  Formula/util-linux.rb
  Formula/vagrant-completion.rb
  Formula/wireshark.rb
Labels: merge

#9161 Merge 2018-08-30 72f81802f4
  Formula/osm2pgrouting.rb
  Formula/osm2pgsql.rb
  Formula/pdal.rb
  Formula/pex.rb
  Formula/pg_top.rb
  Formula/pgpool-ii.rb
  Formula/pgroonga.rb
  Formula/pgrouting.rb
  Formula/pldebugger.rb
Labels: merge

#9164 Merge 2018-08-30 006bed0a40
  Formula/gcore.rb
  Formula/sleepwatcher.rb
Labels: merge

#9165 Merge 2018-08-30 fa2a9aca6e
  Formula/fn.rb
  Formula/gnatsd.rb
  Formula/lftp.rb
  Formula/openapi-generator.rb
  Formula/presto.rb
Labels: merge

#9168 Merge 2018-08-30 41d2625ba4
  Formula/erlang.rb
  Formula/fortio.rb
  Formula/gnupg.rb
  Formula/heroku.rb
  Formula/icecast.rb
  Formula/ipsumdump.rb
  Formula/mapnik.rb
  Formula/pyinvoke.rb
  Formula/typescript.rb
Labels: merge

#9169 isl@0.18: Fix test for Linux
  Formula/isl@0.18.rb
Labels: test-failure
