Repository Homebrew/linuxbrew-core, pull requests merged in 2019-11, with the labels that each got.

#16843 Merge 2019-11-01 8a35e1210b
  Formula/angular-cli.rb
  Formula/ask-cli.rb
  Formula/cimg.rb
  Formula/dnscrypt-proxy.rb
  Formula/hugo.rb
  Formula/jfrog-cli-go.rb
  Formula/minikube.rb
  Formula/openvpn.rb
  Formula/pmd.rb
  Formula/rabbitmq.rb
  Formula/residualvm.rb
  Formula/ruby-build.rb
  Formula/scummvm-tools.rb
  Formula/scummvm.rb
  Formula/serverless.rb
Labels: merge

#16851 Merge 2019-11-01 de439b3529
  Formula/balena-cli.rb
  Formula/ballerina.rb
  Formula/cfssl.rb
  Formula/cmatrix.rb
  Formula/doitlive.rb
  Formula/drafter.rb
  Formula/exploitdb.rb
  Formula/gnunet.rb
  Formula/go.rb
  Formula/go@1.12.rb
  Formula/godep.rb
  Formula/just.rb
  Formula/llvm@7.rb
  Formula/lmod.rb
  Formula/osquery.rb
  Formula/pspg.rb
  Formula/python.rb
  Formula/re2.rb
  Formula/rocksdb.rb
  Formula/shared-mime-info.rb
  Formula/sip.rb
  Formula/vagrant-completion.rb
  Formula/vim@7.4.rb
  Formula/xcodegen.rb
Labels: merge

#16867 Merge 2019-11-01 e96d80c190
  Formula/apache-arrow-glib.rb
  Formula/apache-arrow.rb
  Formula/bro.rb
  Formula/cfn-lint.rb
  Formula/composer.rb
  Formula/goreleaser.rb
  Formula/libcouchbase.rb
  Formula/opencv.rb
  Formula/ponyc.rb
  Formula/terraform.rb
Labels: merge

#16885 Merge 2019-11-02 391a103855
  Formula/appstream-glib.rb
  Formula/borg.rb
  Formula/cmu-pocketsphinx.rb
  Formula/crc32c.rb
  Formula/darksky-weather.rb
  Formula/dbxml.rb
  Formula/djbdns.rb
  Formula/dwm.rb
  Formula/exact-image.rb
  Formula/exploitdb.rb
  Formula/flactag.rb
  Formula/halibut.rb
  Formula/lcdf-typetools.rb
  Formula/lean.rb
  Formula/libdsk.rb
  Formula/liberasurecode.rb
  Formula/libpeas.rb
  Formula/libxspf.rb
  Formula/lmod.rb
  Formula/mupdf-tools.rb
  Formula/mupdf.rb
  Formula/pssh.rb
  Formula/puzzles.rb
  Formula/python-markdown.rb
  Formula/rawgl.rb
  Formula/somagic.rb
  Formula/src.rb
  Formula/tasksh.rb
  Formula/whatmp3.rb
  Formula/xboard.rb
Labels: merge

#16893 Merge 2019-11-02 3251a9c1d5
  Formula/audiofile.rb
  Formula/bup.rb
  Formula/dasm.rb
  Formula/dcal.rb
  Formula/ipbt.rb
  Formula/lemon.rb
  Formula/otf2bdf.rb
  Formula/quex.rb
  Formula/rtptools.rb
  Formula/spigot.rb
Labels: merge

#16903 Merge 2019-11-02 12d70a1c78
  Formula/dvc.rb
  Formula/neomutt.rb
  Formula/psftools.rb
  Formula/ruby-build.rb
Labels: merge

#16907 Merge 2019-11-03 4690c29cf2
  Formula/bat.rb
  Formula/cash-cli.rb
  Formula/comby.rb
  Formula/coq.rb
  Formula/fd.rb
  Formula/frpc.rb
  Formula/frps.rb
  Formula/goofys.rb
  Formula/helmfile.rb
  Formula/hexyl.rb
  Formula/hlint.rb
  Formula/jd.rb
  Formula/jupyterlab.rb
  Formula/libmaxminddb.rb
  Formula/rclone.rb
  Formula/repo.rb
  Formula/ripgrep.rb
  Formula/xsv.rb
  formula_renames.json
Labels: merge

#16925 Merge 2019-11-03 8aaeb2ad0b
  Formula/llvm@6.rb
  Formula/llvm@8.rb
Labels: merge

#16926 Merge 2019-11-03 e583bea9b6
  Formula/aiccu.rb
  Formula/angle-grinder.rb
  Formula/dust.rb
  Formula/fastmod.rb
  Formula/ffsend.rb
  Formula/genact.rb
  Formula/lsd.rb
  Formula/mdbook.rb
  Formula/open-ocd.rb
  Formula/pastel.rb
  Formula/rbspy.rb
  Formula/sccache.rb
  Formula/sd.rb
  Formula/shadowenv.rb
  Formula/shellharden.rb
  Formula/sk.rb
  Formula/sn0int.rb
  Formula/ssh-permit-a38.rb
  Formula/starship.rb
  Formula/tectonic.rb
  Formula/toast.rb
  Formula/tokei.rb
  Formula/topgrade.rb
  Formula/wagyu.rb
  Formula/watchexec.rb
  Formula/websocat.rb
Labels: merge

#16952 Merge 2019-11-03 068d680424
  Formula/boringtun.rb
  Formula/broot.rb
  Formula/cfn-lint.rb
  Formula/click.rb
  Formula/cmdshelf.rb
  Formula/diffr.rb
  Formula/diskus.rb
  Formula/dust.rb
  Formula/folly.rb
  Formula/fwup.rb
  Formula/gifski.rb
  Formula/git-absorb.rb
  Formula/git-delta.rb
  Formula/gleam.rb
  Formula/go-bindata.rb
  Formula/interactive-rebase-tool.rb
  Formula/jabba.rb
  Formula/javacc.rb
  Formula/jrtplib.rb
  Formula/just.rb
  Formula/kanif.rb
  Formula/ktmpl.rb
  Formula/kyoto-tycoon.rb
  Formula/kyua.rb
  Formula/loc.rb
  Formula/mdbook.rb
  Formula/mdcat.rb
  Formula/miniserve.rb
  Formula/mkl-dnn.rb
  Formula/operator-sdk.rb
  Formula/oxipng.rb
  Formula/pacman4console.rb
  Formula/picard-tools.rb
  Formula/prestosql.rb
  Formula/procs.rb
  Formula/quantlib.rb
  Formula/quasi88.rb
  Formula/quilt.rb
  Formula/randomize-lines.rb
  Formula/rargs.rb
  Formula/rdate.rb
  Formula/redstore.rb
  Formula/regldg.rb
  Formula/ripgrep-all.rb
  Formula/rustup-init.rb
  Formula/vit.rb
  Formula/woboq_codebrowser.rb
  Formula/wolfssl.rb
  Formula/yle-dl.rb
  Formula/zmqpp.rb
Labels: merge

#16983 Merge 2019-11-03 e8b1b6387c
  Formula/eg.rb
  Formula/elvish.rb
  Formula/enigma.rb
  Formula/fastd.rb
  Formula/fdclone.rb
  Formula/fs-uae.rb
  Formula/get_iplayer.rb
  Formula/globjects.rb
  Formula/gpredict.rb
  Formula/gupnp.rb
  Formula/i386-elf-grub.rb
  Formula/id3v2.rb
  Formula/itk.rb
  Formula/rdate.rb
  Formula/yq.rb
Labels: merge

#16987 Merge 2019-11-03 e6f138c030b
  Formula/fcgi.rb
  Formula/flake8.rb
  Formula/flyway.rb
  Formula/git-delta.rb
  Formula/gmtl.rb
  Formula/gost.rb
  Formula/gtk-gnutella.rb
  Formula/howard-hinnant-date.rb
  Formula/icon.rb
  Formula/jfrog-cli-go.rb
  Formula/kyma-cli.rb
  Formula/makensis.rb
  Formula/mas.rb
  Formula/mercurial.rb
  Formula/mongroup.rb
  Formula/nvm.rb
Labels: merge

#16994 Merge 2019-11-04 edc8b28b601
  Formula/cmake.rb
  Formula/dcmtk.rb
  Formula/deark.rb
  Formula/gmt.rb
  Formula/harfbuzz.rb
  Formula/hydra.rb
  Formula/idutils.rb
  Formula/jsvc.rb
  Formula/libssh.rb
  Formula/offlineimap.rb
  Formula/php-cs-fixer.rb
  Formula/sourcedocs.rb
  Formula/tile38.rb
  Formula/yafc.rb
Labels: merge

#17004 Merge 2019-11-04 a34d39a63d
  Formula/ack.rb
  Formula/git.rb
  Formula/manticoresearch.rb
  Formula/qt.rb
  Formula/siril.rb
  Formula/ucloud.rb
Labels: merge

#17008 Merge 2019-11-04 1ea069b710
  Formula/conan.rb
  Formula/di.rb
  Formula/django-completion.rb
  Formula/dvc.rb
  Formula/eprover.rb
  Formula/fluid-synth.rb
  Formula/gdcm.rb
  Formula/gmic.rb
  Formula/hypre.rb
  Formula/i2p.rb
  Formula/imapfilter.rb
  Formula/jruby.rb
  Formula/miller.rb
  Formula/mpi4py.rb
  Formula/paket.rb
Labels: merge

#17017 Merge 2019-11-05 281adcca8cf
  Aliases/ansible@2.9
  Formula/adwaita-icon-theme.rb
  Formula/ansible.rb
  Formula/asdf.rb
  Formula/axel.rb
  Formula/clojure.rb
  Formula/fig2dev.rb
  Formula/ghq.rb
  Formula/grafana.rb
  Formula/haproxy.rb
  Formula/haxe.rb
  Formula/hyperscan.rb
  Formula/imageoptim-cli.rb
  Formula/inlets.rb
  Formula/jenkins.rb
  Formula/jmeter.rb
  Formula/libedit.rb
  Formula/libetpan.rb
  Formula/libopenmpt.rb
  Formula/libsass.rb
  Formula/libtiff.rb
  Formula/nodenv.rb
  Formula/nomad.rb
  Formula/packer.rb
  Formula/pyenv.rb
  Formula/s3-backer.rb
  Formula/starship.rb
  Formula/tunnel.rb
  Formula/youtube-dl.rb
Labels: merge

#17036 Merge 2019-11-05 907534264dc
  Formula/cvs.rb
  Formula/zydis.rb
Labels: merge

#17038 Merge 2019-11-05 76220f7bd5c
  Formula/ghc.rb
  Formula/ghq.rb
Labels: merge

#17040 Merge 2019-11-05 b8a1bf8c7bb
  Formula/adios2.rb
  Formula/babel.rb
  Formula/conan.rb
  Formula/contentful-cli.rb
  Formula/dive.rb
  Formula/dvc.rb
  Formula/elixir.rb
  Formula/exploitdb.rb
  Formula/ghq.rb
  Formula/goreleaser.rb
  Formula/kubeseal.rb
  Formula/lazygit.rb
  Formula/logtalk.rb
  Formula/mpv.rb
  Formula/netdata.rb
  Formula/ngt.rb
  Formula/nifi.rb
  Formula/oauth2l.rb
  Formula/paket.rb
  Formula/proteinortho.rb
  Formula/ruby-build.rb
  tap_migrations.json
Labels: merge

#17051 Merge 2019-11-06 44b4df15152
  Aliases/mysql-connector-c++@8.0
  Formula/cheat.rb
  Formula/deno.rb
  Formula/duplicity.rb
  Formula/flow.rb
  Formula/libtommath.rb
  Formula/micronaut.rb
  Formula/mkvtoolnix.rb
  Formula/mpg123.rb
  Formula/mpi4py.rb
  Formula/mysql-connector-c++.rb
  Formula/mysql@5.6.rb
  Formula/ngt.rb
  Formula/nuget.rb
  Formula/openimageio.rb
  Formula/openrct2.rb
  Formula/paket.rb
  Formula/parallel.rb
  Formula/qjackctl.rb
  Formula/rpm.rb
  Formula/s3ql.rb
  Formula/s6.rb
  Formula/snakemake.rb
  Formula/sonobuoy.rb
  Formula/yacas.rb
  formula_renames.json
Labels: merge

#17068 Merge 2019-11-06 2c9111f0b3b
  Formula/black.rb
  Formula/qxmpp.rb
  Formula/teleport.rb
  Formula/terragrunt.rb
  Formula/typescript.rb
Labels: merge

#17076 Merge 2019-11-06 dfbacc955dd
  Formula/calceph.rb
  Formula/conan.rb
  Formula/contentful-cli.rb
  Formula/couchdb.rb
  Formula/curl-openssl.rb
  Formula/curl.rb
  Formula/cython.rb
  Formula/dav1d.rb
  Formula/deployer.rb
  Formula/elixir.rb
  Formula/erlang.rb
  Formula/exploitdb.rb
  Formula/flow.rb
  Formula/fx.rb
  Formula/git-town.rb
  Formula/goreleaser.rb
  Formula/grafana.rb
  Formula/helmfile.rb
  Formula/hub.rb
  Formula/hydra.rb
  Formula/jvgrep.rb
  Formula/kubernetes-helm.rb
  Formula/mariadb.rb
  Formula/mariadb@10.2.rb
  Formula/mysql@5.5.rb
  Formula/mysql@5.6.rb
  Formula/neko.rb
  Formula/nss.rb
  Formula/paket.rb
  Formula/phpunit.rb
  Formula/python-yq.rb
  Formula/qhull.rb
  Formula/rgbds.rb
  Formula/serverless.rb
  Formula/shared-mime-info.rb
  Formula/sispmctl.rb
  Formula/squid.rb
  Formula/vim.rb
  Formula/virgil.rb
  formula_renames.json
Labels: merge

#17016 Run brew as normal user and other Azure changes
  azure-pipelines.yml
Labels: do-not-merge

#17099 Merge 2019-11-07 1b8d40f742
  Formula/aws-sdk-cpp.rb
  Formula/babel.rb
  Formula/calicoctl.rb
  Formula/cargo-completion.rb
  Formula/dvc.rb
  Formula/exploitdb.rb
  Formula/freeswitch.rb
  Formula/gerbv.rb
  Formula/gitmoji.rb
  Formula/gnumeric.rb
  Formula/goffice.rb
  Formula/imagemagick@6.rb
  Formula/ksh.rb
  Formula/libvirt.rb
  Formula/mariadb@10.1.rb
  Formula/mysql-connector-c++@1.1.rb
  Formula/neovim.rb
  Formula/percona-server.rb
  Formula/php-code-sniffer.rb
  Formula/pulumi.rb
  Formula/pyside.rb
  Formula/slowhttptest.rb
  Formula/stress-ng.rb
  Formula/tunnel.rb
  Formula/tweak.rb
  Formula/vapoursynth-imwri.rb
  Formula/vapoursynth-ocr.rb
  Formula/vapoursynth-sub.rb
  Formula/vapoursynth.rb
  Formula/wireguard-go.rb
  Formula/x264.rb
Labels: merge

#17116 Merge 2019-11-08 a25b95559c
  Formula/angular-cli.rb
  Formula/annie.rb
  Formula/apache-geode.rb
  Formula/apache-zeppelin.rb
  Formula/arangodb.rb
  Formula/boot-clj.rb
  Formula/bulk_extractor.rb
  Formula/ceres-solver.rb
  Formula/cheat.rb
  Formula/comby.rb
  Formula/devspace.rb
  Formula/dita-ot.rb
  Formula/dynare.rb
  Formula/exploitdb.rb
  Formula/gitversion.rb
  Formula/glooctl.rb
  Formula/helmfile.rb
  Formula/istioctl.rb
  Formula/jfrog-cli-go.rb
  Formula/kops.rb
  Formula/lerna.rb
  Formula/libssh.rb
  Formula/mysql-client.rb
  Formula/node-build.rb
  Formula/nut.rb
  Formula/octave.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/platformio.rb
  Formula/rust.rb
  Formula/shadowenv.rb
  Formula/skaffold.rb
  Formula/sourcekitten.rb
  Formula/sparse.rb
  Formula/suite-sparse.rb
  Formula/sundials.rb
  Formula/tektoncd-cli.rb
  Formula/topgrade.rb
  Formula/vault.rb
  Formula/velero.rb
Labels: merge

#17143 Merge 2019-11-09 401f540ec2
  Formula/adwaita-icon-theme.rb
  Formula/arangodb.rb
  Formula/consul-template.rb
  Formula/dvc.rb
  Formula/envconsul.rb
  Formula/frugal.rb
  Formula/gdb.rb
  Formula/geoipupdate.rb
  Formula/libcds.rb
  Formula/libkate.rb
  Formula/lmod.rb
  Formula/mariadb.rb
  Formula/mariadb@10.1.rb
  Formula/mariadb@10.2.rb
  Formula/mariadb@10.3.rb
  Formula/mesos.rb
  Formula/now-cli.rb
  Formula/nu.rb
  Formula/octant.rb
  Formula/osquery.rb
  Formula/pdnsrec.rb
  Formula/prettier.rb
  Formula/pspg.rb
  Formula/vulkan-headers.rb
Labels: merge

#17163 Merge 2019-11-10 a5561705c81
  Aliases/subversion@1.13
  Formula/abcm2ps.rb
  Formula/armadillo.rb
  Formula/badtouch.rb
  Formula/broot.rb
  Formula/bundletool.rb
  Formula/byacc.rb
  Formula/dive.rb
  Formula/eye-d3.rb
  Formula/folly.rb
  Formula/fop.rb
  Formula/futhark.rb
  Formula/git-archive-all.rb
  Formula/grpc.rb
  Formula/http-server.rb
  Formula/jo.rb
  Formula/kubectx.rb
  Formula/librealsense.rb
  Formula/pulumi.rb
  Formula/sfst.rb
  Formula/subversion.rb
  Formula/swiftlint.rb
  Formula/tunnel.rb
  Formula/ungit.rb
Labels: merge

#17179 Merge 2019-11-10 a426105d93
  Formula/blast.rb
  Formula/dvc.rb
  Formula/kallisto.rb
  Formula/lazygit.rb
  Formula/lego.rb
  Formula/mkvtoolnix.rb
  Formula/monero.rb
  Formula/onefetch.rb
  Formula/skopeo.rb
  Formula/tunnel.rb
Labels: merge

#17187 Merge 2019-11-11 334577d87b
  Formula/carla.rb
  Formula/convox.rb
  Formula/deployer.rb
  Formula/dnscrypt-proxy.rb
  Formula/erlang.rb
  Formula/fselect.rb
  Formula/gatsby-cli.rb
  Formula/gifski.rb
  Formula/git-cola.rb
  Formula/janet.rb
  Formula/jenkins.rb
  Formula/jhipster.rb
  Formula/libplist.rb
  Formula/pygments.rb
  Formula/pyqt.rb
  Formula/qscintilla2.rb
  Formula/raine.rb
  Formula/root.rb
  Formula/sip.rb
  Formula/terragrunt.rb
  Formula/urh.rb
  Formula/valgrind.rb
  Formula/vice.rb
  Formula/vtk.rb
  Formula/wine.rb
  Formula/wtf.rb
  Formula/wtfutil.rb
Labels: merge

#17205 Merge 2019-11-11 0818aeeee79
  Aliases/usb-multiplex-daemon
  Formula/aws-cdk.rb
  Formula/bibutils.rb
  Formula/caf.rb
  Formula/cfn-lint.rb
  Formula/conan.rb
  Formula/couchdb-lucene.rb
  Formula/dependency-check.rb
  Formula/devspace.rb
  Formula/fselect.rb
  Formula/git-annex.rb
  Formula/h3.rb
  Formula/ideviceinstaller.rb
  Formula/ifuse.rb
  Formula/ios-webkit-debug-proxy.rb
  Formula/jvmtop.rb
  Formula/lazydocker.rb
  Formula/lazygit.rb
  Formula/libheif.rb
  Formula/libimobiledevice.rb
  Formula/libusbmuxd.rb
  Formula/mkcert.rb
  Formula/neomutt.rb
  Formula/paket.rb
  Formula/pyqt.rb
  Formula/rancher-cli.rb
  Formula/ruby-build.rb
  Formula/termshark.rb
  Formula/vala.rb
  formula_renames.json
Labels: merge

#17224 Merge 2019-11-12 934964aff1
  Formula/abcmidi.rb
  Formula/ansifilter.rb
  Formula/aws-cdk.rb
  Formula/aws-google-auth.rb
  Formula/azure-cli.rb
  Formula/bullet.rb
  Formula/dependency-check.rb
  Formula/dvc.rb
  Formula/embulk.rb
  Formula/exploitdb.rb
  Formula/goreleaser.rb
  Formula/haxe.rb
  Formula/hcloud.rb
  Formula/jfrog-cli-go.rb
  Formula/lazygit.rb
  Formula/libusbmuxd.rb
  Formula/mdbook.rb
  Formula/now-cli.rb
  Formula/suil.rb
  Formula/ungit.rb
  Formula/yadm.rb
Labels: merge

#17241 Merge 2019-11-13 b99a095579
  Formula/aws-cdk.rb
  Formula/balena-cli.rb
  Formula/bitrise.rb
  Formula/cf-tool.rb
  Formula/cfssl.rb
  Formula/cheat.rb
  Formula/chromaprint.rb
  Formula/convox.rb
  Formula/exploitdb.rb
  Formula/flow.rb
  Formula/gatsby-cli.rb
  Formula/glooctl.rb
  Formula/goofys.rb
  Formula/highlight.rb
  Formula/jfrog-cli-go.rb
  Formula/just.rb
  Formula/kubernetes-helm.rb
  Formula/libphonenumber.rb
  Formula/mariadb-connector-c.rb
  Formula/mysql.rb
  Formula/netlify-cli.rb
  Formula/ngt.rb
  Formula/ocrmypdf.rb
  Formula/paket.rb
  Formula/scc.rb
  Formula/sord.rb
  Formula/starship.rb
  Formula/stress-ng.rb
  Formula/telegraf.rb
  Formula/tnef.rb
  Formula/tokei.rb
  Formula/tunnel.rb
  Formula/vamp-plugin-sdk.rb
  Formula/vfuse.rb
  Formula/wp-cli.rb
  Formula/xa.rb
Labels: merge

#17268 Merge 2019-11-14 22b840e5b6
  Formula/angular-cli.rb
  Formula/apache-arrow.rb
  Formula/bingrep.rb
  Formula/blast.rb
  Formula/bro.rb
  Formula/buildkit.rb
  Formula/caf.rb
  Formula/exploitdb.rb
  Formula/gdcm.rb
  Formula/imagemagick.rb
  Formula/itk.rb
  Formula/kubernetes-cli.rb
  Formula/lazygit.rb
  Formula/libchaos.rb
  Formula/libxml2.rb
  Formula/mariadb-connector-odbc.rb
  Formula/mariadb.rb
  Formula/mariadb@10.1.rb
  Formula/mariadb@10.2.rb
  Formula/mariadb@10.3.rb
  Formula/pcl.rb
  Formula/pdal.rb
  Formula/pulumi.rb
  Formula/screenfetch.rb
  Formula/sratom.rb
  Formula/terragrunt.rb
  Formula/visp.rb
  Formula/vtk.rb
  Formula/zint.rb
Labels: merge

#17289 Merge 2019-11-15 722a4a2e94d
  Formula/console_bridge.rb
  Formula/consul-template.rb
  Formula/convox.rb
  Formula/docker-completion.rb
  Formula/docker.rb
  Formula/git.rb
  Formula/gmime.rb
  Formula/handbrake.rb
  Formula/helmfile.rb
  Formula/istioctl.rb
  Formula/kubeseal.rb
  Formula/libxslt.rb
  Formula/minica.rb
  Formula/paket.rb
  Formula/pnpm.rb
  Formula/ssh-audit.rb
  Formula/taskell.rb
  Formula/traefik.rb
  Formula/triton.rb
  Formula/virustotal-cli.rb
Labels: merge

#17303 Merge 2019-11-15 01c89ef17a
  Formula/bat.rb
  Formula/fontforge.rb
  Formula/gdal.rb
  Formula/giflib.rb
  Formula/leptonica.rb
  Formula/libming.rb
  Formula/mapserver.rb
  Formula/openimageio.rb
  Formula/pdf2htmlex.rb
  Formula/prestodb.rb
  Formula/prestosql.rb
  Formula/sxiv.rb
  Formula/vips.rb
  Formula/xplanet.rb
Labels: merge

#17319 Merge 2019-11-16 31e5bcfca3
  Formula/aliyun-cli.rb
  Formula/arx-libertatis.rb
  Formula/arx.rb
  Formula/bro.rb
  Formula/catch2.rb
  Formula/exploitdb.rb
  Formula/gatsby-cli.rb
  Formula/geckodriver.rb
  Formula/git-annex.rb
  Formula/ispc.rb
  Formula/paket.rb
  Formula/rnv.rb
  Formula/sonobuoy.rb
  Formula/terrahub.rb
  Formula/tunnel.rb
Labels: merge

#17325 Merge 2019-11-16 0b50e4fdbc
  Aliases/helm@3
  Formula/ampl-mp.rb
  Formula/aws-okta.rb
  Formula/broot.rb
  Formula/caddy.rb
  Formula/cfn-lint.rb
  Formula/chamber.rb
  Formula/freerdp.rb
  Formula/gitleaks.rb
  Formula/gomplate.rb
  Formula/helm.rb
  Formula/helm@2.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/percona-server.rb
  Formula/percona-xtrabackup.rb
  Formula/riak.rb
  Formula/sparkey.rb
  Formula/sphinx.rb
  formula_renames.json
Labels: merge

#17343 Remove formulae removed from homebrew-core
  Formula/apple-gcc42.rb
  Formula/bdsup2sub.rb
  Formula/corebird.rb
  Formula/gdnsd.rb
  Formula/ghc@8.0.rb
  Formula/gmt@4.rb
  Formula/gnome-doc-utils.rb
  Formula/gv.rb
  Formula/hana.rb
  Formula/heroku.rb
  Formula/kdiff3.rb
  Formula/kes.rb
  Formula/kibana@4.4.rb
  Formula/konoha.rb
  Formula/kontena.rb
  Formula/libical-glib.rb
  Formula/liblacewing.rb
  Formula/mongodb.rb
  Formula/mongodb@3.6.rb
  Formula/mysql-cluster.rb
  Formula/percona-server@5.6.rb
  Formula/php@5.6.rb
  Formula/protobuf@3.1.rb
  Formula/skipfish.rb
  Formula/taylor.rb
Labels: needs response

#17345 Merge 2019-11-17 ba4bb6511a
  Aliases/node@13
  Formula/awscli.rb
  Formula/cayley.rb
  Formula/cheat.rb
  Formula/csound.rb
  Formula/dvc.rb
  Formula/ethereum.rb
  Formula/exploitdb.rb
  Formula/fibjs.rb
  Formula/fzf.rb
  Formula/gitfs.rb
  Formula/glooctl.rb
  Formula/goreleaser.rb
  Formula/janet.rb
  Formula/joplin.rb
  Formula/knot-resolver.rb
  Formula/lazydocker.rb
  Formula/libcapn.rb
  Formula/libressl.rb
  Formula/luajit.rb
  Formula/luaradio.rb
  Formula/luvit.rb
  Formula/mercurial.rb
  Formula/minetest.rb
  Formula/n.rb
  Formula/node.rb
  Formula/node@12.rb
  Formula/perl-build.rb
  Formula/snort.rb
  Formula/solarus.rb
  Formula/ssldump.rb
  Formula/syncthing.rb
  Formula/sysdig.rb
  Formula/tflint.rb
  Formula/trader.rb
  Formula/um.rb
  Formula/vault.rb
  Formula/zelda-roth-se.rb
  Formula/zsdx.rb
  Formula/zsxd.rb
Labels: merge

#17376 Merge 2019-11-18 7ea5a17c10
  Formula/clac.rb
  Formula/conjure-up.rb
  Formula/eventql.rb
  Formula/gitleaks.rb
  Formula/goofys.rb
  Formula/helmfile.rb
  Formula/jenkins.rb
  Formula/joplin.rb
  Formula/nghttp2.rb
  Formula/pnpm.rb
  Formula/qemu.rb
  Formula/remind.rb
  Formula/termtosvg.rb
Labels: merge

#17384 Merge 2019-11-18 2d2aa9cf0d
  Aliases/mysql-client@8.0
  Formula/dvc.rb
  Formula/hydra.rb
  Formula/innotop.rb
  Formula/kitchen-sync.rb
  Formula/libzdb.rb
  Formula/mariadb.rb
  Formula/mercurial.rb
  Formula/mydumper.rb
  Formula/mysql++.rb
  Formula/mysql-client.rb
  Formula/mysql-client@5.7.rb
  Formula/mysql-connector-c++.rb
  Formula/mysql-connector-c++@1.1.rb
  Formula/mysql-connector-c.rb
  Formula/mysql.rb
  Formula/mytop.rb
  Formula/neko.rb
  Formula/node_exporter.rb
  Formula/ntopng.rb
  Formula/percona-server.rb
  Formula/percona-toolkit.rb
  Formula/percona-xtrabackup.rb
  Formula/rex.rb
  Formula/shairport-sync.rb
  Formula/sysbench.rb
  Formula/terraform.rb
  Formula/thrift@0.9.rb
  Formula/travis.rb
  Formula/unrar.rb
  formula_renames.json
Labels: merge

#17412 Merge 2019-11-18 6998a8cae0
  Formula/awsume.rb
  Formula/byteman.rb
  Formula/erlang@20.rb
  Formula/fonttools.rb
  Formula/imagemagick.rb
  Formula/luajit.rb
  Formula/manticoresearch.rb
  Formula/newman.rb
  Formula/opa.rb
  Formula/open-zwave.rb
  Formula/qpdf.rb
  Formula/qstat.rb
  Formula/skaffold.rb
  Formula/stellar-core.rb
  Formula/travis.rb
  Formula/vala.rb
  Formula/whois.rb
  formula_renames.json
Labels: merge

#17424 Merge 2019-11-19 64555220bf
  Formula/amazon-ecs-cli.rb
  Formula/aria2.rb
  Formula/docker-compose.rb
  Formula/doctl.rb
  Formula/fabio.rb
  Formula/firebase-cli.rb
  Formula/gatsby-cli.rb
  Formula/git-revise.rb
  Formula/gradle.rb
  Formula/imagemagick@6.rb
  Formula/kind.rb
  Formula/liblouis.rb
  Formula/nats-server.rb
  Formula/prometheus.rb
  Formula/rclone.rb
  Formula/sentencepiece.rb
  Formula/terraform.rb
  Formula/tunnel.rb
  Formula/virtuoso.rb
Labels: merge

#17450 Merge 2019-11-19 0c5930b3e5
  Formula/exploitdb.rb
  Formula/kotlin.rb
  Formula/mysql-client.rb
  Formula/node@12.rb
  Formula/nushell.rb
  Formula/pgloader.rb
  Formula/rpm.rb
  Formula/tile38.rb
  Formula/tmate.rb
  Formula/topgrade.rb
  Formula/tox.rb
  Formula/uncrustify.rb
  Formula/watchexec.rb
Labels: merge

#17458 Merge 2019-11-20 790c14225f
  Formula/ansible.rb
  Formula/aws-cdk.rb
  Formula/aws-sdk-cpp.rb
  Formula/berglas.rb
  Formula/bnd.rb
  Formula/cartridge-cli.rb
  Formula/cfn-lint.rb
  Formula/cfssl.rb
  Formula/cheat.rb
  Formula/conan.rb
  Formula/gitlab-runner.rb
  Formula/glib.rb
  Formula/helmfile.rb
  Formula/lerna.rb
  Formula/lmod.rb
  Formula/monero.rb
  Formula/mpich.rb
  Formula/mysql-client.rb
  Formula/rav1e.rb
  Formula/rclone.rb
  Formula/repo.rb
  Formula/unbound.rb
  Formula/vit.rb
  Formula/vulkan-headers.rb
Labels: merge

#17474 Merge 2019-11-20 03addf34c9
  Formula/ccache.rb
  Formula/cointop.rb
  Formula/convox.rb
  Formula/darksky-weather.rb
  Formula/diamond.rb
  Formula/docker-compose-completion.rb
  Formula/exploitdb.rb
  Formula/folly.rb
  Formula/fwup.rb
  Formula/ghq.rb
  Formula/jhipster.rb
  Formula/kubebuilder.rb
  Formula/librealsense.rb
  Formula/libxlsxwriter.rb
  Formula/mlt.rb
  Formula/picard-tools.rb
  Formula/rclone.rb
  Formula/redis.rb
  Formula/reminiscence.rb
  Formula/scrcpy.rb
  Formula/swagger-codegen.rb
  Formula/swagger-codegen@2.rb
  Formula/telegraf.rb
  Formula/tig.rb
  Formula/zstd.rb
Labels: merge

#17493 Merge 2019-11-21 5c09121491
  Formula/auditbeat.rb
  Formula/aws-cdk.rb
  Formula/breezy.rb
  Formula/clojure.rb
  Formula/convox.rb
  Formula/elasticsearch.rb
  Formula/gatsby-cli.rb
  Formula/goreleaser.rb
  Formula/graph-tool.rb
  Formula/hapi-fhir-cli.rb
  Formula/jenkins-lts.rb
  Formula/kops.rb
  Formula/libharu.rb
  Formula/libimobiledevice.rb
  Formula/librdkafka.rb
  Formula/libusbmuxd.rb
  Formula/mariadb-connector-c.rb
  Formula/mesa.rb
  Formula/mysql.rb
  Formula/numpy.rb
  Formula/paket.rb
  Formula/percona-server.rb
  Formula/pspg.rb
  Formula/pulumi.rb
  Formula/pushpin.rb
  Formula/qt.rb
  Formula/serverless.rb
  Formula/synscan.rb
  Formula/treefrog.rb
  Formula/tunnel.rb
  Formula/valgrind.rb
  Formula/whois.rb
  Formula/wxpython.rb
Labels: merge

#17510 Merge 2019-11-21 fd693ac780
  Aliases/openssl@1.0
  Formula/ansible.rb
  Formula/cheat.rb
  Formula/convox.rb
  Formula/dvc.rb
  Formula/firebase-cli.rb
  Formula/fork-cleaner.rb
  Formula/gedit.rb
  Formula/gitlab-runner.rb
  Formula/just.rb
  Formula/lerna.rb
  Formula/logstash.rb
  Formula/metricbeat.rb
  Formula/mrboom.rb
  Formula/mysql-client.rb
  Formula/zeek.rb
  formula_renames.json
Labels: merge

#17520 Merge 2019-11-21 5d02fe0210
  Formula/cminpack.rb
  Formula/cucumber-cpp.rb
  Formula/git.rb
  Formula/infer.rb
  Formula/libftdi.rb
  Formula/libgraphqlparser.rb
  Formula/moc.rb
  Formula/node@12.rb
  Formula/php.rb
  Formula/procs.rb
  Formula/tiger-vnc.rb
Labels: merge

#17529 Merge 2019-11-21 b4b9c1cd84
  Aliases/openssl
  Formula/ansible-lint.rb
  Formula/erlang.rb
  Formula/exploitdb.rb
  Formula/lazygit.rb
  Formula/paket.rb
  Formula/skafos.rb
  Formula/tepl.rb
  Formula/wxmaxima.rb
  Formula/yaml-cpp.rb
Labels: merge

#17536 Merge 2019-11-22 00b39db1c3
  Formula/cabal-install.rb
  Formula/gimme-aws-creds.rb
  Formula/groonga.rb
  Formula/helmfile.rb
  Formula/libsodium.rb
  Formula/libtasn1.rb
  Formula/now-cli.rb
  Formula/pcre2.rb
  Formula/postgresql@10.rb
  Formula/postgresql@9.4.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
  Formula/protobuf.rb
  Formula/sbcl.rb
  Formula/youtube-dl.rb
Labels: merge

#17551 Merge 2019-11-22 f0e708b9f5
  Aliases/ansible@2.9
  Formula/ace.rb
  Formula/allureofthestars.rb
  Formula/cln.rb
  Formula/dnsviz.rb
  Formula/gcc.rb
  Formula/ipopt.rb
  Formula/jetty.rb
  Formula/ledger.rb
  Formula/mesa.rb
  Formula/osc.rb
  Formula/php@7.2.rb
  Formula/sops.rb
  Formula/tektoncd-cli.rb
  Formula/tomcat.rb
  Formula/uwsgi.rb
  Formula/virgil.rb
  Formula/yarn.rb
  formula_renames.json
Labels: merge

#17575 Merge 2019-11-23 3c4768deeb
  Aliases/postgresql@12
  Formula/cargo-c.rb
  Formula/citus.rb
  Formula/cstore_fdw.rb
  Formula/devdash.rb
  Formula/dxpy.rb
  Formula/eslint.rb
  Formula/fluxctl.rb
  Formula/gwyddion.rb
  Formula/libpq.rb
  Formula/libpqxx.rb
  Formula/monolith.rb
  Formula/passenger.rb
  Formula/pgloader.rb
  Formula/pgroonga.rb
  Formula/pgrouting.rb
  Formula/postgis.rb
  Formula/postgresql.rb
  Formula/postgresql@11.rb
  Formula/restic.rb
  Formula/scipy.rb
  Formula/simple-scan.rb
  Formula/temporal_tables.rb
  Formula/terrahub.rb
  Formula/tomcat@8.rb
  Formula/wal2json.rb
  Formula/wget.rb
Labels: merge

#17593 Merge 2019-11-24 a5ca051acc
  Formula/babel.rb
  Formula/dcos-cli.rb
  Formula/eccodes.rb
  Formula/exploitdb.rb
  Formula/glooctl.rb
  Formula/goreleaser.rb
  Formula/ice.rb
  Formula/juju.rb
  Formula/maxwell.rb
  Formula/navi.rb
  Formula/nsd.rb
  Formula/nss.rb
  Formula/paket.rb
  Formula/pspg.rb
  Formula/salt.rb
  Formula/wal2json.rb
Labels: merge

#17604 Merge 2019-11-24 39ceb165b9
  Formula/awscli.rb
  Formula/cfn-lint.rb
  Formula/evince.rb
  Formula/file-roller.rb
  Formula/gcc@6.rb
  Formula/gcc@8.rb
  Formula/gitleaks.rb
  Formula/haproxy.rb
  Formula/helmfile.rb
  Formula/n.rb
  Formula/phpmyadmin.rb
  Formula/proftpd.rb
  Formula/rav1e.rb
  Formula/sn0int.rb
  Formula/streamlink.rb
  Formula/stunnel.rb
  Formula/yelp-tools.rb
Labels: merge

#17635 Merge 2019-11-24 875716802d
  Formula/ammonite-repl.rb
  Formula/antlr4-cpp-runtime.rb
  Formula/aws-google-auth.rb
  Formula/bit.rb
  Formula/bitcoin.rb
  Formula/gcc@7.rb
  Formula/gjs.rb
  Formula/goreleaser.rb
  Formula/libcroco.rb
  Formula/liblwgeom.rb
  Formula/pandoc-crossref.rb
  Formula/pandoc.rb
  Formula/pgbouncer.rb
  Formula/ruby-build.rb
  Formula/sratoolkit.rb
  Formula/stellar-core.rb
  Formula/swiftformat.rb
  Formula/transmission-cli.rb
  Formula/ttyd.rb
  Formula/v8.rb
  Formula/vte3.rb
Labels: merge

#17646 Merge 2019-11-25 11eacb09d8
  Formula/cheat.rb
  Formula/clamav.rb
  Formula/eslint.rb
  Formula/jenkins.rb
  Formula/jmeter.rb
  Formula/libhttpserver.rb
  Formula/libidn2.rb
  Formula/librsvg.rb
  Formula/node.rb
  Formula/pandoc-citeproc.rb
  Formula/sbt.rb
  Formula/ungit.rb
Labels: merge

#17656 Merge 2019-11-26 5a9850094d
  Formula/bind.rb
  Formula/clojure.rb
  Formula/dafny.rb
  Formula/gjs.rb
  Formula/grafana.rb
  Formula/imlib2.rb
  Formula/mono-libgdiplus.rb
  Formula/orc-tools.rb
  Formula/pachi.rb
  Formula/parallel.rb
  Formula/pdns.rb
  Formula/pgpool-ii.rb
  Formula/pianobar.rb
  Formula/pianod.rb
  Formula/pylint.rb
  Formula/scipy.rb
  Formula/stress-ng.rb
  Formula/swiftformat.rb
  Formula/todoman.rb
  Formula/urh.rb
  Formula/vale.rb
  Formula/vice.rb
  Formula/xapian.rb
  Formula/z3.rb
  cmd/brew-postgresql-upgrade-database.rb
Labels: merge

#17674 Merge 2019-11-26 925999779e
  Aliases/thrift@0.13
  Formula/abcl.rb
  Formula/abcmidi.rb
  Formula/alexjs.rb
  Formula/ansiweather.rb
  Formula/apache-arrow.rb
  Formula/arm-linux-gnueabihf-binutils.rb
  Formula/arp-scan.rb
  Formula/audacious.rb
  Formula/azure-cli.rb
  Formula/babeld.rb
  Formula/binutils.rb
  Formula/fauna-shell.rb
  Formula/freeradius-server.rb
  Formula/fs-uae.rb
  Formula/grakn.rb
  Formula/haproxy.rb
  Formula/hyperfine.rb
  Formula/i386-elf-binutils.rb
  Formula/imapsync.rb
  Formula/imlib2.rb
  Formula/include-what-you-use.rb
  Formula/jailkit.rb
  Formula/kepubify.rb
  Formula/libcoap.rb
  Formula/libgusb.rb
  Formula/onnxruntime.rb
  Formula/osquery.rb
  Formula/postgresql@11.rb
  Formula/pypy.rb
  Formula/pypy3.rb
  Formula/thrift.rb
  Formula/tio.rb
  Formula/urbit.rb
Labels: merge

#17700 Merge 2019-11-26 fe431c8959
  Formula/aws-cdk.rb
  Formula/dnstwist.rb
  Formula/duck.rb
  Formula/dvc.rb
  Formula/ethereum.rb
  Formula/exploitdb.rb
  Formula/gatsby-cli.rb
  Formula/glooctl.rb
  Formula/jfrog-cli-go.rb
  Formula/lazygit.rb
  Formula/libepoxy.rb
  Formula/libphonenumber.rb
  Formula/libtorch.rb
  Formula/libtrace.rb
  Formula/libusbmuxd.rb
  Formula/lilv.rb
  Formula/mame.rb
  Formula/memcached.rb
  Formula/menhir.rb
  Formula/paket.rb
  Formula/php-cs-fixer.rb
  Formula/psqlodbc.rb
  Formula/ssh-audit.rb
  Formula/terrahub.rb
  Formula/wtfutil.rb
Labels: merge

#17713 Merge 2019-11-27 4d33aa5ddb
  Formula/bazel.rb
  Formula/bazelisk.rb
  Formula/cfn-lint.rb
  Formula/exploitdb.rb
  Formula/googler.rb
  Formula/icecream.rb
  Formula/maven.rb
  Formula/nushell.rb
  Formula/pianod.rb
  Formula/pulumi.rb
  Formula/rke.rb
  Formula/samurai.rb
  Formula/smali.rb
  Formula/tmux.rb
  Formula/vim.rb
  Formula/vit.rb
  Formula/vsts-cli.rb
  Formula/wtfutil.rb
Labels: merge

#17724 Merge 2019-11-27 6807fd8cb8
  Formula/ballerina.rb
  Formula/deno.rb
  Formula/futhark.rb
  Formula/git-cola.rb
  Formula/gnupg.rb
  Formula/hugo.rb
  Formula/imagemagick.rb
  Formula/jfrog-cli-go.rb
  Formula/nushell.rb
  Formula/sbcl.rb
  Formula/swiftformat.rb
  Formula/teleport.rb
  Formula/vert.x.rb
  Formula/yadm.rb
Labels: merge

#17734 Merge 2019-11-28 808d309b0b
  Formula/angular-cli.rb
  Formula/blastem.rb
  Formula/broot.rb
  Formula/calceph.rb
  Formula/charm-tools.rb
  Formula/comby.rb
  Formula/consul.rb
  Formula/dnscrypt-proxy.rb
  Formula/elektra.rb
  Formula/exploitdb.rb
  Formula/fauna-shell.rb
  Formula/gource.rb
  Formula/node-build.rb
  Formula/nomad.rb
  Formula/pandoc.rb
  Formula/prestosql.rb
  Formula/rom-tools.rb
  Formula/solr.rb
  Formula/topgrade.rb
  Formula/zrepl.rb
Labels: merge

#17745 Merge 2019-11-28 25678c4046
  Aliases/protobuf@3.11
  Formula/apache-arrow-glib.rb
  Formula/apache-arrow.rb
  Formula/caffe.rb
  Formula/citus.rb
  Formula/frpc.rb
  Formula/frps.rb
  Formula/grafana.rb
  Formula/grpc.rb
  Formula/inlets.rb
  Formula/juju.rb
  Formula/libphonenumber.rb
  Formula/libpulsar.rb
  Formula/libtorch.rb
  Formula/mosh.rb
  Formula/oniguruma.rb
  Formula/openfortivpn.rb
  Formula/protobuf-c.rb
  Formula/protobuf.rb
  Formula/pspg.rb
  Formula/scalapack.rb
  Formula/shogun.rb
  Formula/uncrustify.rb
  Formula/xlearn.rb
  Formula/youtube-dl.rb
  Formula/zabbix.rb
  Formula/zbackup.rb
  Formula/zopfli.rb
Labels: merge

#17760 Merge 2019-11-29 a6e8244aae
  Formula/abyss.rb
  Formula/arangodb.rb
  Formula/cling.rb
  Formula/devspace.rb
  Formula/faas-cli.rb
  Formula/fonttools.rb
  Formula/glslang.rb
  Formula/kubecfg.rb
  Formula/monetdb.rb
  Formula/purescript.rb
  Formula/tile38.rb
  Formula/wireguard-tools.rb
  Formula/yapf.rb
Labels: merge

#17768 Merge 2019-11-30 51af987f52
  Formula/borgmatic.rb
  Formula/drafter.rb
  Formula/exploitdb.rb
  Formula/hugo.rb
  Formula/lightgbm.rb
  Formula/math-comp.rb
  Formula/neomutt.rb
  Formula/tcsh.rb
  Formula/timewarrior.rb
  Formula/wiiuse.rb
  Formula/xlearn.rb
Labels: merge
