Repository Homebrew/linuxbrew-core, pull requests merged in 2019-07, with the labels that each got.

#14041 Merge 2019-07-02 3d1768d3dd
  Formula/advancecomp.rb
  Formula/aws-sdk-cpp.rb
  Formula/bazaar.rb
  Formula/bison.rb
  Formula/ccache.rb
  Formula/chezscheme.rb
  Formula/collectd.rb
  Formula/haskell-stack.rb
  Formula/imagemagick.rb
  Formula/io.rb
  Formula/irssi.rb
  Formula/jack.rb
Labels: merge

#14045 Merge 2019-07-02 653d494c5b
  Formula/beanstalkd.rb
  Formula/catimg.rb
  Formula/collectd.rb
  Formula/cppcheck.rb
  Formula/exploitdb.rb
  Formula/gegl.rb
  Formula/gmic.rb
  Formula/gst-plugins-good.rb
  Formula/libebml.rb
  Formula/libev.rb
  Formula/libfabric.rb
  Formula/libmatroska.rb
  Formula/libopenmpt.rb
  Formula/libshout.rb
  Formula/libsvm.rb
  Formula/lldpd.rb
  Formula/lynis.rb
  Formula/magic-wormhole.rb
  Formula/mame.rb
  Formula/pdns.rb
  Formula/proteinortho.rb
  Formula/sbcl.rb
  Formula/spice-protocol.rb
  Formula/swi-prolog.rb
Labels: merge

#14061 Merge 2019-07-02 63843dddc4
  Formula/ammonite-repl.rb
  Formula/bgpstream.rb
  Formula/cointop.rb
  Formula/ffsend.rb
  Formula/gammu.rb
  Formula/gearsystem.rb
  Formula/helmsman.rb
  Formula/influxdb.rb
  Formula/ios-webkit-debug-proxy.rb
  Formula/jenkins.rb
  Formula/libtrace.rb
  Formula/libzdb.rb
  Formula/mill.rb
  Formula/pmd.rb
  Formula/sqlmap.rb
  Formula/topgrade.rb
  Formula/unzip.rb
  Formula/userspace-rcu.rb
  Formula/uwsgi.rb
  Formula/vulkan-headers.rb
  Formula/wandio.rb
  Formula/webtorrent-cli.rb
  Formula/xonsh.rb
  Formula/zshdb.rb
Labels: merge

#14072 Merge 2019-07-02 5dc80da0c2
  Formula/agda.rb
  Formula/calicoctl.rb
  Formula/cfengine.rb
  Formula/convox.rb
  Formula/doxygen.rb
  Formula/enchant.rb
  Formula/ettercap.rb
  Formula/git-cinnabar.rb
  Formula/glooctl.rb
  Formula/guile.rb
  Formula/imageoptim-cli.rb
  Formula/janet.rb
  Formula/juju.rb
  Formula/libuninameslist.rb
  Formula/lmod.rb
  Formula/nco.rb
  Formula/neovim.rb
  Formula/odpi.rb
  Formula/paket.rb
  Formula/picard-tools.rb
  Formula/re2.rb
  Formula/sceptre.rb
  Formula/shc.rb
  Formula/terragrunt.rb
  Formula/unzip.rb
  Formula/youtube-dl.rb
Labels: merge

#14088 Merge 2019-07-03 2312e6ac04
  Formula/angular-cli.rb
  Formula/argon2.rb
  Formula/bazel.rb
  Formula/blink1.rb
  Formula/collectd.rb
  Formula/devspace.rb
  Formula/dub.rb
  Formula/exploitdb.rb
  Formula/gatsby-cli.rb
  Formula/grpc.rb
  Formula/kubeless.rb
  Formula/libuv.rb
  Formula/mujs.rb
  Formula/neo4j.rb
  Formula/netlify-cli.rb
  Formula/paket.rb
  Formula/protobuf-c.rb
  Formula/skaffold.rb
  Formula/terragrunt.rb
  Formula/tox.rb
  Formula/webpack.rb
  Formula/wireguard-tools.rb
Labels: merge

#14099 Merge 2019-07-04 ecc560823a
  Formula/argon2.rb
  Formula/erlang@21.rb
  Formula/exploitdb.rb
  Formula/frugal.rb
  Formula/i2pd.rb
  Formula/kotlin.rb
  Formula/minio-mc.rb
  Formula/mlkit.rb
  Formula/neovim.rb
  Formula/oxipng.rb
Labels: merge

#14109 Merge 2019-07-05 fccd852192
  Formula/acpica.rb
  Formula/aliyun-cli.rb
  Formula/ask-cli.rb
  Formula/azure-cli.rb
  Formula/bzip2.rb
  Formula/clojure.rb
  Formula/cointop.rb
  Formula/django-completion.rb
  Formula/erlang.rb
  Formula/exploitdb.rb
  Formula/glooctl.rb
  Formula/gmsh.rb
  Formula/grpcurl.rb
  Formula/hadolint.rb
  Formula/kubeprod.rb
  Formula/libgweather.rb
  Formula/opa.rb
  Formula/paket.rb
  Formula/phpunit.rb
  Formula/podofo.rb
  Formula/proguard.rb
  Formula/pushpin.rb
  Formula/sonar-scanner.rb
  Formula/sonarqube.rb
  Formula/terrahub.rb
  Formula/ykpers.rb
  Formula/zurl.rb
Labels: merge

#14112 bzip2: Build a bottle for Linuxbrew
  Formula/bzip2.rb
Labels: bottle

#14133 Merge 2019-07-10 10fc7d6f2d
  Formula/babel.rb
  Formula/cargo-completion.rb
  Formula/contentful-cli.rb
  Formula/convox.rb
  Formula/exploitdb.rb
  Formula/fontconfig.rb
  Formula/freetype.rb
  Formula/gatsby-cli.rb
  Formula/grakn.rb
  Formula/gxml.rb
  Formula/hamlib.rb
  Formula/helmfile.rb
  Formula/jboss-forge.rb
  Formula/libgphoto2.rb
  Formula/libpqxx.rb
  Formula/micronaut.rb
  Formula/php.rb
  Formula/php@7.2.rb
  Formula/postgresql.rb
  Formula/react-native-cli.rb
  Formula/rust.rb
  Formula/stern.rb
  Formula/thors-serializer.rb
  Formula/tokei.rb
  Formula/ucloud.rb
  Formula/vnstat.rb
  Formula/xsimd.rb
Labels: merge

#14134 Merge 2019-07-10 a2acc0cb32
  Formula/aptly.rb
  Formula/arangodb.rb
  Formula/cimg.rb
  Formula/cointop.rb
  Formula/csvq.rb
  Formula/exploitdb.rb
  Formula/gammaray.rb
  Formula/goreleaser.rb
  Formula/gst-plugins-good.rb
  Formula/gtk+3.rb
  Formula/imagemagick@6.rb
  Formula/kustomize.rb
  Formula/libagar.rb
  Formula/libsixel.rb
  Formula/minio.rb
  Formula/openshift-cli.rb
  Formula/pius.rb
  Formula/ponyc.rb
  Formula/qt.rb
  Formula/smlnj.rb
  Formula/termtosvg.rb
  Formula/thors-serializer.rb
  Formula/webtorrent-cli.rb
  Formula/xonsh.rb
  Formula/zeromq.rb
Labels: merge

#14161 Merge 2019-07-11 be4d976798
  Formula/cfn-lint.rb
  Formula/ghr.rb
  Formula/libbi.rb
  Formula/prototool.rb
  Formula/swiftlint.rb
  Formula/vim.rb
Labels: merge

#14160 mongodb@3.6: remove duplicated xcode dependency
  Formula/mongodb@3.6.rb
Labels: build-error

#14164 Merge 2019-07-11 d183fb7f30
  Formula/ask-cli.rb
  Formula/balena-cli.rb
  Formula/binaryen.rb
  Formula/bzt.rb
  Formula/cjdns.rb
  Formula/clhep.rb
  Formula/creduce.rb
  Formula/csound.rb
  Formula/deno.rb
  Formula/diffoscope.rb
  Formula/dmd.rb
  Formula/docker-credential-helper-ecr.rb
  Formula/dpkg.rb
  Formula/exercism.rb
  Formula/faas-cli.rb
  Formula/fasttext.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/goreleaser.rb
  Formula/gxml.rb
  Formula/mesa.rb
  Formula/mill.rb
  Formula/netdata.rb
  Formula/osc.rb
  Formula/pgbouncer.rb
  Formula/rabbitmq.rb
  Formula/typescript.rb
  Formula/ungit.rb
  Formula/vips.rb
  Formula/vulkan-headers.rb
  Formula/webpack.rb
Labels: merge

#14165 Merge 2019-07-11 035418caed
  Formula/atomist-cli.rb
  Formula/conan.rb
  Formula/contentful-cli.rb
  Formula/eccodes.rb
  Formula/exploitdb.rb
  Formula/faudio.rb
  Formula/ffmpeg.rb
  Formula/frugal.rb
  Formula/ginac.rb
  Formula/glib.rb
  Formula/hwloc.rb
  Formula/igv.rb
  Formula/imagemagick.rb
  Formula/jetty.rb
  Formula/jfrog-cli-go.rb
  Formula/jhead.rb
  Formula/languagetool.rb
  Formula/mednafen.rb
  Formula/mesa.rb
  Formula/monit.rb
  Formula/nsd.rb
  Formula/prometheus.rb
  Formula/pyenv.rb
  Formula/r.rb
  Formula/s3ql.rb
  Formula/ship.rb
  Formula/syncthing.rb
  Formula/u-boot-tools.rb
  Formula/ucloud.rb
Labels: merge

#14192 Merge 2019-07-11 8a2c8e365d
  Formula/balena-cli.rb
  Formula/chakra.rb
  Formula/cocoapods.rb
  Formula/glooctl.rb
  Formula/gsoap.rb
  Formula/hub.rb
  Formula/klavaro.rb
  Formula/kore.rb
  Formula/libhdhomerun.rb
  Formula/libraw.rb
  Formula/libvirt.rb
  Formula/log4cplus.rb
  Formula/log4shib.rb
  Formula/logcheck.rb
  Formula/logstash.rb
  Formula/openapi-generator.rb
  Formula/opensaml.rb
  Formula/protoc-gen-go.rb
  Formula/pyside.rb
  Formula/s3-backer.rb
  Formula/shibboleth-sp.rb
  Formula/telegraf.rb
  Formula/xml-tooling-c.rb
Labels: merge

#14206 Merge 2019-07-12 ada355ae6c
  Formula/amazon-ecs-cli.rb
  Formula/apache-flink.rb
  Formula/ask-cli.rb
  Formula/aws-sdk-cpp.rb
  Formula/babel.rb
  Formula/convox.rb
  Formula/digdag.rb
  Formula/erlang.rb
  Formula/exploitdb.rb
  Formula/hcloud.rb
  Formula/janet.rb
  Formula/meson.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/serverless.rb
  Formula/ship.rb
  Formula/tomcat.rb
  Formula/tomcat@8.rb
Labels: merge

#14207 Merge 2019-07-12 70cfae2f21
  Formula/ansible.rb
  Formula/chronograf.rb
  Formula/ckan.rb
  Formula/dnstwist.rb
  Formula/doitlive.rb
  Formula/dosbox.rb
  Formula/fonttools.rb
  Formula/ghostscript.rb
  Formula/glide.rb
  Formula/gradle.rb
  Formula/mono.rb
  Formula/nim.rb
  Formula/node.rb
  Formula/openconnect.rb
  Formula/python.rb
  Formula/sip.rb
  Formula/vim@7.4.rb
Labels: merge

#14229 Merge 2019-07-13 0ebc0466f5
  Formula/angular-cli.rb
  Formula/bazel.rb
  Formula/binaryen.rb
  Formula/cfn-lint.rb
  Formula/citus.rb
  Formula/cxxopts.rb
  Formula/ethereum.rb
  Formula/goreleaser.rb
  Formula/hypre.rb
  Formula/jsoncpp.rb
  Formula/kustomize.rb
  Formula/lgogdownloader.rb
  Formula/libjson-rpc-cpp.rb
  Formula/libsbol.rb
  Formula/linkerd.rb
  Formula/lmod.rb
  Formula/mkl-dnn.rb
  Formula/openrct2.rb
  Formula/prometheus.rb
  Formula/redex.rb
  Formula/sysdig.rb
  Formula/tag.rb
  Formula/webdis.rb
Labels: merge

#14237 Merge 2019-07-13 1f744b70b9
  Formula/amazon-ecs-cli.rb
  Formula/bitrise.rb
  Formula/bro.rb
  Formula/caddy.rb
  Formula/chipmunk.rb
  Formula/dcd.rb
  Formula/dscanner.rb
  Formula/erlang.rb
  Formula/exploitdb.rb
  Formula/firebase-cli.rb
  Formula/gatsby-cli.rb
  Formula/helmfile.rb
  Formula/isync.rb
  Formula/jlog.rb
  Formula/kubernetes-helm.rb
  Formula/libsbol.rb
  Formula/ocrmypdf.rb
  Formula/opam.rb
  Formula/open-zwave.rb
  Formula/phpmd.rb
  Formula/proteinortho.rb
  Formula/swagger-codegen.rb
  Formula/swagger-codegen@2.rb
  Formula/terraform.rb
  Formula/youtube-dl.rb
Labels: merge

#13622 Fix for subversion
  Formula/subversion.rb
Labels: changes requested

#14257 Merge 2019-07-14 2a7c981766
  Formula/botan.rb
  Formula/debianutils.rb
  Formula/dita-ot.rb
  Formula/fs-uae.rb
  Formula/openhmd.rb
Labels: merge

#14259 Merge 2019-07-14 d1085c538c
  Formula/dynamips.rb
  Formula/gatsby-cli.rb
Labels: merge, needs response

#14260 Merge 2019-07-14 41aff003fe
  Formula/atlantis.rb
  Formula/bazel.rb
  Formula/bundletool.rb
  Formula/di.rb
  Formula/doctl.rb
  Formula/erlang@21.rb
  Formula/exploitdb.rb
  Formula/fio.rb
  Formula/golang-migrate.rb
  Formula/helmfile.rb
  Formula/hqx.rb
  Formula/i386-elf-gcc.rb
  Formula/i386-elf-gdb.rb
  Formula/i386-elf-grub.rb
  Formula/kube-aws.rb
  Formula/kustomize.rb
  Formula/landscaper.rb
  Formula/nss.rb
  Formula/operator-sdk.rb
  Formula/ttyd.rb
  Formula/ucloud.rb
  Formula/ungit.rb
  Formula/zabbix.rb
  Formula/znc.rb
Labels: merge

#14271 Merge 2019-07-14 f59c3acedc
  Formula/jsoncpp.rb
  Formula/lgogdownloader.rb
  Formula/libjson-rpc-cpp.rb
  Formula/redex.rb
  Formula/sysdig.rb
Labels: merge

#14272 Merge 2019-07-14 6762773ab0
  Formula/circleci.rb
  Formula/dbus.rb
  Formula/eprover.rb
  Formula/minio-mc.rb
Labels: merge

#14276 Merge 2019-07-14 3dae0782aa
  Formula/ghex.rb
  Formula/kvazaar.rb
  Formula/libtensorflow.rb
  Formula/lxc.rb
  Formula/presto.rb
  Formula/pulumi.rb
  Formula/radare2.rb
  Formula/whalebrew.rb
Labels: merge

#14282 Merge 2019-07-15 1890a4fad8
  Formula/asdf.rb
  Formula/exploitdb.rb
  Formula/frpc.rb
  Formula/fselect.rb
  Formula/gatsby-cli.rb
  Formula/get_iplayer.rb
  Formula/gst-plugins-bad.rb
  Formula/webp.rb
  Formula/yarn.rb
  Formula/yash.rb
  Formula/yaz.rb
Labels: merge

#14283 Merge 2019-07-15 0b7d3f9751
  Formula/mpop.rb
  Formula/msmtp.rb
  Formula/nickle.rb
  Formula/ocrad.rb
  Formula/pdnsrec.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/poco.rb
  Formula/vulkan-headers.rb
  Formula/websocat.rb
Labels: merge

#14284 Merge 2019-07-15 fffa7d66fb
  Formula/frps.rb
  Formula/mkl-dnn.rb
  Formula/proj.rb
  Formula/thors-serializer.rb
  Formula/youtube-dl.rb
Labels: merge

#14285 Merge 2019-07-15 459591b96b
  Formula/bzip2.rb
  Formula/docfx.rb
  Formula/doctl.rb
  Formula/jenkins.rb
  Formula/phpunit.rb
  Formula/squid.rb
  Formula/sshguard.rb
  Formula/stanford-parser.rb
  Formula/suil.rb
  Formula/whalebrew.rb
Labels: merge

#14286 Merge 2019-07-15 8b3ddfedb5
  Formula/armor.rb
  Formula/git-absorb.rb
  Formula/jsdoc3.rb
  Formula/ktlint.rb
  Formula/pioneer.rb
  Formula/prips.rb
  Formula/repo.rb
  Formula/reposurgeon.rb
  Formula/svgo.rb
  Formula/widelands.rb
Labels: merge

#14287 Merge 2019-07-15 2a8b9b60c8
  Formula/atomist-cli.rb
  Formula/dependency-check.rb
  Formula/exa.rb
  Formula/gatsby-cli.rb
  Formula/gitmoji.rb
  Formula/graph-tool.rb
  Formula/platformio.rb
  Formula/thors-serializer.rb
  Formula/xorriso.rb
  Formula/ydcv.rb
Labels: merge

#14313 Merge 2019-07-17 388933b987
  Formula/astrometry-net.rb
  Formula/azure-cli.rb
  Formula/balena-cli.rb
  Formula/cake.rb
  Formula/cfn-lint.rb
  Formula/click.rb
  Formula/cromwell.rb
  Formula/gdal.rb
  Formula/libphonenumber.rb
  Formula/libxmlsec1.rb
  Formula/mdbook.rb
  Formula/nats-server.rb
  Formula/omega.rb
  Formula/rke.rb
  Formula/ship.rb
  Formula/tectonic.rb
  Formula/terrahub.rb
  Formula/tmpreaper.rb
  Formula/urh.rb
  Formula/vala.rb
  Formula/vim.rb
  Formula/watson.rb
  Formula/wcslib.rb
  Formula/wgetpaste.rb
  Formula/xa.rb
Labels: merge

#14314 Merge 2019-07-17 1dab4a6533
  Formula/ask-cli.rb
  Formula/binaryen.rb
  Formula/cfssl.rb
  Formula/cpprestsdk.rb
  Formula/exploitdb.rb
  Formula/fn.rb
  Formula/git-absorb.rb
  Formula/hapi-fhir-cli.rb
  Formula/libvpx.rb
  Formula/liquibase.rb
  Formula/qmmp.rb
  Formula/remarshal.rb
  Formula/rex.rb
  Formula/rpm2cpio.rb
  Formula/rsyslog.rb
  Formula/shogun.rb
  Formula/stella.rb
  Formula/stress-ng.rb
  Formula/stuntman.rb
  Formula/topgrade.rb
  Formula/twine-pypi.rb
  Formula/txr.rb
  Formula/uhd.rb
  Formula/vfuse.rb
  Formula/vmtouch.rb
  Formula/youtube-dl.rb
Labels: merge

#14339 Merge 2019-07-18 2cc8d7d522
  Formula/cmake.rb
  Formula/cockroach.rb
  Formula/contentful-cli.rb
  Formula/cpl.rb
  Formula/deno.rb
  Formula/digdag.rb
  Formula/docker-credential-helper.rb
  Formula/ffmpeg.rb
  Formula/ffmpeg@2.8.rb
  Formula/gdal.rb
  Formula/glooctl.rb
  Formula/haskell-stack.rb
  Formula/hidapi.rb
  Formula/libheif.rb
  Formula/media-info.rb
  Formula/newt.rb
  Formula/pulumi.rb
  Formula/scamper.rb
  Formula/snakemake.rb
  Formula/tflint.rb
  Formula/wireshark.rb
  Formula/x265.rb
Labels: merge

#14352 Merge 2019-07-18 51760a30a9
  Formula/curl-openssl.rb
  Formula/curl.rb
Labels: merge

#14356 Merge 2019-07-19 25337a25a1
  Formula/angular-cli.rb
  Formula/babel.rb
  Formula/cake.rb
  Formula/certbot.rb
  Formula/clojure.rb
  Formula/cmake.rb
  Formula/direvent.rb
  Formula/docker-completion.rb
  Formula/docker.rb
  Formula/exploitdb.rb
  Formula/faas-cli.rb
  Formula/firebase-cli.rb
  Formula/gpgme.rb
  Formula/grails.rb
  Formula/imageoptim-cli.rb
  Formula/jenkins-lts.rb
  Formula/jenkins.rb
  Formula/kustomize.rb
  Formula/luarocks.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/netlify-cli.rb
  Formula/nim.rb
  Formula/pipenv.rb
  Formula/rush.rb
  Formula/vert.x.rb
  Formula/webpack.rb
Labels: merge

#14367 Merge 2019-07-19 d059f0af2c
  Formula/abcm2ps.rb
  Formula/apache-arrow-glib.rb
  Formula/apache-arrow.rb
  Formula/asyncplusplus.rb
  Formula/balena-cli.rb
  Formula/bit.rb
  Formula/esptool.rb
  Formula/glooctl.rb
  Formula/kubernetes-cli.rb
  Formula/libspng.rb
  Formula/libstatgrab.rb
  Formula/libvpx.rb
  Formula/link-grammar.rb
  Formula/metabase.rb
  Formula/monero.rb
  Formula/netlify-cli.rb
  Formula/overmind.rb
  Formula/perltidy.rb
  Formula/pjproject.rb
  Formula/png++.rb
  Formula/quickjs.rb
  Formula/terraform.rb
  Formula/terragrunt.rb
  Formula/v8.rb
Labels: merge

#14368 Merge 2019-07-19 f11d40ac2c
  Formula/balena-cli.rb
  Formula/byacc.rb
  Formula/cpl.rb
  Formula/curl-openssl.rb
  Formula/curl.rb
  Formula/deark.rb
  Formula/doctl.rb
  Formula/dovecot.rb
  Formula/drone-cli.rb
  Formula/ejabberd.rb
  Formula/elixir.rb
  Formula/exploitdb.rb
  Formula/flashrom.rb
  Formula/flawfinder.rb
  Formula/fn.rb
  Formula/fossil.rb
  Formula/freediameter.rb
  Formula/geoserver.rb
  Formula/glances.rb
  Formula/libvncserver.rb
  Formula/lolcat.rb
  Formula/monero.rb
  Formula/presto.rb
  Formula/swift-protobuf.rb
  Formula/uriparser.rb
Labels: merge

#14396 Merge 2019-07-20 e79426a982
  Formula/abcmidi.rb
  Formula/ack.rb
  Formula/ask-cli.rb
  Formula/awscli.rb
  Formula/bacula-fd.rb
  Formula/btfs.rb
  Formula/eiffelstudio.rb
  Formula/glooctl.rb
  Formula/hub.rb
  Formula/icecream.rb
  Formula/kustomize.rb
  Formula/mercurial.rb
  Formula/mesos.rb
  Formula/netlify-cli.rb
  Formula/serverless.rb
  Formula/swiftlint.rb
  Formula/thors-serializer.rb
Labels: merge

#14402 Merge 2019-07-21 189d8af574
  Formula/avfs.rb
  Formula/bundletool.rb
  Formula/ccache.rb
  Formula/ctags.rb
  Formula/diff-pdf.rb
  Formula/epubcheck.rb
  Formula/glooctl.rb
  Formula/lmdb.rb
  Formula/mpg123.rb
  Formula/pazpar2.rb
  Formula/pcsc-lite.rb
  Formula/pdftoipe.rb
  Formula/poppler.rb
  Formula/scdoc.rb
  Formula/serverless.rb
  Formula/sflowtool.rb
  Formula/subnetcalc.rb
  Formula/tomcat-native.rb
  Formula/translate-toolkit.rb
  Formula/vapoursynth-imwri.rb
  Formula/vapoursynth-ocr.rb
  Formula/vapoursynth-sub.rb
  Formula/vapoursynth.rb
  Formula/volatility.rb
  Formula/vttest.rb
  Formula/whois.rb
  Formula/zstd.rb
Labels: merge

#14403 Merge 2019-07-21 28a044e949
  Formula/bazel.rb
  Formula/bazelisk.rb
  Formula/cocoapods.rb
  Formula/contentful-cli.rb
  Formula/convox.rb
  Formula/exiftool.rb
  Formula/exploitdb.rb
  Formula/gatsby-cli.rb
  Formula/gnu-apl.rb
  Formula/mono.rb
  Formula/netlify-cli.rb
  Formula/pinboard-notes-backup.rb
  Formula/platypus.rb
  Formula/pulumi.rb
  Formula/rke.rb
  Formula/sdl2_image.rb
  Formula/sdlpop.rb
  Formula/skaffold.rb
  Formula/tag.rb
  Formula/terraformer.rb
  Formula/tflint.rb
  Formula/triton.rb
  Formula/vegeta.rb
  Formula/xonsh.rb
Labels: merge

#14430 Merge 2019-07-22 f33ff3558b
  Formula/armadillo.rb
  Formula/ats2-postiats.rb
  Formula/bindfs.rb
  Formula/black.rb
  Formula/byobu.rb
  Formula/calcurse.rb
  Formula/diffoscope.rb
  Formula/dnsperf.rb
  Formula/ecasound.rb
  Formula/eslint.rb
  Formula/exploitdb.rb
  Formula/gambit-scheme.rb
  Formula/gatsby-cli.rb
  Formula/ghostscript.rb
  Formula/gspell.rb
  Formula/ipython.rb
  Formula/iso-codes.rb
  Formula/kedge.rb
  Formula/lbzip2.rb
  Formula/lego.rb
  Formula/libggz.rb
  Formula/libguess.rb
  Formula/libpq.rb
  Formula/lysp.rb
  Formula/mesos.rb
  Formula/n.rb
  Formula/ne.rb
  Formula/peg.rb
  Formula/rapidjson.rb
  Formula/s6.rb
  Formula/sgrep.rb
  Formula/verilator.rb
  Formula/wtf.rb
Labels: merge

#14431 Merge 2019-07-22 b8170f065b
  Formula/gibo.rb
  Formula/go@1.11.rb
  Formula/kobalt.rb
  Formula/llvm@7.rb
  Formula/vegeta.rb
Labels: merge

#14432 Merge 2019-07-22 f45e02c3e3
  Formula/aws-google-auth.rb
  Formula/breezy.rb
  Formula/cash-cli.rb
  Formula/dbhash.rb
  Formula/gauche.rb
  Formula/lf.rb
  Formula/lnav.rb
  Formula/macvim.rb
  Formula/mypy.rb
  Formula/neo4j.rb
  Formula/onscripter.rb
  Formula/pari.rb
  Formula/png++.rb
  Formula/pyinstaller.rb
  Formula/quickjs.rb
  Formula/shadowenv.rb
  Formula/sqldiff.rb
  Formula/sqlite-analyzer.rb
  Formula/sqlite.rb
  Formula/vfuse.rb
  Formula/webtorrent-cli.rb
  Formula/wxmac.rb
  Formula/yapf.rb
  Formula/zabbix-cli.rb
Labels: merge

#14455 Merge 2019-07-23 993d29eff2
  Formula/borgmatic.rb
  Formula/cython.rb
  Formula/dependency-check.rb
  Formula/dhall-bash.rb
  Formula/flake8.rb
  Formula/freetds.rb
  Formula/goreleaser.rb
  Formula/internetarchive.rb
  Formula/jenkins.rb
  Formula/legit.rb
  Formula/open-jtalk.rb
  Formula/open-mesh.rb
  Formula/openttd.rb
  Formula/putty.rb
  Formula/python-markdown.rb
  Formula/pyvim.rb
  Formula/robot-framework.rb
  Formula/s3ql.rb
  Formula/scons.rb
  Formula/sourcekitten.rb
  Formula/sphinx-doc.rb
  Formula/tintin.rb
  Formula/todoman.rb
  Formula/tox.rb
  Formula/xapian.rb
Labels: merge

#14469 Merge 2019-07-27 be81522995
  Formula/docker-completion.rb
  Formula/docker.rb
  Formula/doctl.rb
  Formula/ser2net.rb
  Formula/sf-pwgen.rb
  Formula/wireshark.rb
Labels: merge

#14470 Merge 2019-07-27 6b4d507105
  Formula/conan.rb
  Formula/folly.rb
  Formula/git-lfs.rb
  Formula/idris.rb
  Formula/k3d.rb
  Formula/telegraf.rb
  Formula/terragrunt.rb
  Formula/uftp.rb
  Formula/vnstat.rb
Labels: merge

#14479 Merge 2019-07-27 c1dc2cfb09
  Formula/babeld.rb
  Formula/debianutils.rb
  Formula/exploitdb.rb
  Formula/glooctl.rb
  Formula/kubeseal.rb
  Formula/mg.rb
  Formula/ship.rb
  Formula/webpack.rb
Labels: merge

#14482 Merge 2019-07-28 a01ea833b4
  Formula/gcsfuse.rb
  Formula/gitlab-runner.rb
  Formula/haproxy.rb
  Formula/ktlint.rb
  Formula/libqalculate.rb
  Formula/mesa.rb
  Formula/plantuml.rb
  Formula/re-flex.rb
  Formula/remarshal.rb
  Formula/sispmctl.rb
Labels: merge

#14483 Merge 2019-07-28 87d6436bff
  Formula/aws-okta.rb
  Formula/balena-cli.rb
  Formula/cash-cli.rb
  Formula/chamber.rb
  Formula/h3.rb
  Formula/lego.rb
  Formula/mysql++.rb
  Formula/x3270.rb
Labels: merge

#14484 Merge 2019-07-28 c8a8273ef9
  Formula/apache-arrow-glib.rb
  Formula/apache-arrow.rb
  Formula/docker.rb
  Formula/gatsby-cli.rb
  Formula/picard-tools.rb
  Formula/proftpd.rb
  Formula/swaks.rb
  Formula/terragrunt.rb
  Formula/wolfssl.rb
Labels: merge

#14497 Merge 2019-07-28 4d8585fcb7
  Formula/c-blosc.rb
  Formula/dovecot.rb
  Formula/entr.rb
  Formula/gphoto2.rb
  Formula/groonga.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/modules.rb
  Formula/subversion.rb
Labels: merge

#14505 Merge 2019-07-29 b61111e630
  Formula/ethereum.rb
  Formula/exploitdb.rb
  Formula/fuse-emulator.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jinja2-cli.rb
  Formula/libiscsi.rb
  Formula/wtf.rb
Labels: merge

#14506 Merge 2019-07-29 4714c7a722
  Formula/glib.rb
Labels: merge

#14508 Merge 2019-07-29 b54784fbad
  Formula/bit.rb
  Formula/devspace.rb
  Formula/firebase-cli.rb
  Formula/graphicsmagick.rb
  Formula/libcouchbase.rb
  Formula/libmaa.rb
  Formula/libxkbcommon.rb
  Formula/mackup.rb
  Formula/mariadb-connector-c.rb
  Formula/mbedtls.rb
Labels: merge

#14521 Merge 2019-07-30 c91ea7bc80
  Formula/aws-okta.rb
  Formula/duck.rb
  Formula/lean-cli.rb
  Formula/libtrace.rb
  Formula/memcached.rb
  Formula/monkeysphere.rb
  Formula/msitools.rb
  Formula/ncdc.rb
  Formula/omniorb.rb
  Formula/parallel.rb
  Formula/wandio.rb
Labels: merge

#14522 Merge 2019-07-30 bc120fd371
  Aliases/solr@8.2
  Formula/conan.rb
  Formula/fluxctl.rb
  Formula/gatsby-cli.rb
  Formula/gitg.rb
  Formula/hugo.rb
  Formula/libdazzle.rb
  Formula/pdfcrack.rb
  Formula/serverless.rb
  Formula/solr.rb
  Formula/supervisor.rb
  Formula/unrtf.rb
Labels: merge

#14523 Merge 2019-07-30 a08bbcb76a
  Formula/aws-google-auth.rb
  Formula/cfn-lint.rb
  Formula/diamond.rb
  Formula/exploitdb.rb
  Formula/hlint.rb
  Formula/liblcf.rb
  Formula/schismtracker.rb
  Formula/valgrind.rb
  Formula/vitetris.rb
  Formula/wxmaxima.rb
Labels: merge

#14524 Merge 2019-07-30 6f7be63a8a
  Formula/cjson.rb
  Formula/kim-api.rb
  Formula/netdata.rb
  Formula/openkim-models.rb
  Formula/png++.rb
  Formula/pony-stable.rb
  Formula/spin.rb
  Formula/tesseract.rb
  Formula/tfenv.rb
  Formula/x11vnc.rb
Labels: merge

#14542 Merge 2019-07-30 82aa0a1569
  Formula/benthos.rb
  Formula/doctl.rb
  Formula/docutils.rb
  Formula/grpc-swift.rb
  Formula/mysql.rb
  Formula/nginx.rb
  Formula/passenger.rb
  Formula/vault.rb
Labels: merge

#14544 Merge 2019-07-30 e673be09da
  Formula/ansible.rb
  Formula/contacts.rb
  Formula/docker-completion.rb
  Formula/inadyn.rb
  Formula/kubeseal.rb
  Formula/nco.rb
  Formula/ncview.rb
  Formula/skaffold.rb
  Formula/u-boot-tools.rb
  Formula/udunits.rb
Labels: merge

#14545 Merge 2019-07-30 5085c04143
  Formula/aws-sdk-cpp.rb
  Formula/consul.rb
  Formula/docker.rb
  Formula/feh.rb
  Formula/firebase-cli.rb
  Formula/gdcm.rb
  Formula/gkrellm.rb
  Formula/gnunet.rb
  Formula/haproxy.rb
  Formula/netlify-cli.rb
Labels: merge

#14546 Merge 2019-07-30 601ae32c30
  Formula/aliyun-cli.rb
  Formula/basex.rb
  Formula/cmake.rb
  Formula/glooctl.rb
  Formula/gopass.rb
  Formula/kustomize.rb
  Formula/libbluray.rb
  Formula/pspg.rb
  Formula/redo.rb
  Formula/webpack.rb
Labels: merge

#14547 Merge 2019-07-30 efdbd566aa
  Formula/btparse.rb
  Formula/cfr-decompiler.rb
  Formula/desktop-file-utils.rb
  Formula/dnsperf.rb
  Formula/exiftool.rb
  Formula/exploitdb.rb
  Formula/gmsh.rb
  Formula/skinny.rb
  Formula/zboy.rb
Labels: merge

#14548 Merge 2019-07-30 8cecedb163
  Formula/credstash.rb
  Formula/cython.rb
  Formula/exim.rb
  Formula/planck.rb
  Formula/presto.rb
  Formula/silk.rb
  Formula/solarus.rb
  Formula/translate-shell.rb
  Formula/tvnamer.rb
  Formula/yaf.rb
  Formula/youtube-dl.rb
Labels: merge

#14568 Merge 2019-07-31 46d20bdd1a
  Formula/dynare.rb
  Formula/glooctl.rb
  Formula/gsoap.rb
  Formula/i2p.rb
  Formula/libmatio.rb
  Formula/luvit.rb
  Formula/nyx.rb
  Formula/offlineimap.rb
  Formula/vim.rb
  Formula/vips.rb
Labels: merge

#14569 Merge 2019-07-31 648efa90f7
  Formula/babl.rb
  Formula/buildifier.rb
  Formula/caf.rb
  Formula/dialog.rb
  Formula/libosip.rb
  Formula/menhir.rb
  Formula/modules.rb
  Formula/openldap.rb
  Formula/orc.rb
  Formula/zsdx.rb
Labels: merge

#14570 Merge 2019 07 31 f25d66f353
  Formula/checkstyle.rb
  Formula/exploitdb.rb
  Formula/helmfile.rb
  Formula/mockserver.rb
  Formula/ode.rb
  Formula/opa.rb
  Formula/pngquant.rb
  Formula/ponyc.rb
  Formula/wtf.rb
  Formula/zelda-roth-se.rb
  Formula/zsxd.rb
Labels: merge

#14587 Merge 2019-07-31 a2983f41cb
  Formula/gitmoji.rb
  Formula/hugo.rb
  Formula/ipython.rb
  Formula/jfrog-cli-go.rb
  Formula/joplin.rb
  Formula/openimageio.rb
  Formula/pmd.rb
  Formula/quickjs.rb
  Formula/shellcheck.rb
  Formula/teleport.rb
Labels: merge

#14588 Merge 2019-07-31 9e4997cf8d
  Formula/cnats.rb
  Formula/dhall-json.rb
  Formula/dhall.rb
  Formula/gatsby-cli.rb
  Formula/homebank.rb
  Formula/mackup.rb
  Formula/ocrmypdf.rb
  Formula/s-nail.rb
  Formula/wtf.rb
Labels: merge
