Repository Homebrew/linuxbrew-core, pull requests merged in 2019-10, with the labels that each got.

#15855 Merge 2019-10-01 8435565bee
  Formula/contentful-cli.rb
  Formula/groovysdk.rb
  Formula/lcm.rb
  Formula/now-cli.rb
  Formula/ponyc.rb
  Formula/sbcl.rb
  Formula/starship.rb
  Formula/zig.rb
Labels: merge

#15859 Merge 2019-10-01 0844a1e397
  Formula/aircrack-ng.rb
  Formula/cscope.rb
  Formula/emacs.rb
  Formula/epsilon.rb
  Formula/gnupg.rb
  Formula/gnutls.rb
  Formula/libxmlsec1.rb
  Formula/wget.rb
Labels: merge

#15860 Merge 2019-10-01 41d34502f8
  Formula/gcc.rb
Labels: merge

#15861 Merge 2019-10-01 0c92663464
  Formula/ccls.rb
  Formula/go-jira.rb
  Formula/ipopt.rb
  Formula/jmeter.rb
  Formula/krakend.rb
  Formula/lapack.rb
  Formula/links.rb
  Formula/luarocks.rb
  Formula/openblas.rb
  Formula/rabbitmq.rb
  Formula/veclibfort.rb
Labels: merge

#15864 Merge 2019-10-01 59e58de4a0
  Formula/fftw.rb
Labels: merge

#15865 Merge 2019-10-01 f524892ab4
  Formula/arpack.rb
  Formula/ceres-solver.rb
  Formula/cfn-lint.rb
  Formula/cgal.rb
  Formula/coreutils.rb
  Formula/django-completion.rb
  Formula/exploitdb.rb
  Formula/gawk.rb
  Formula/glib-networking.rb
  Formula/gnu-sed.rb
  Formula/gnu-tar.rb
  Formula/gpgme.rb
  Formula/hdf5.rb
  Formula/ipython.rb
  Formula/kubeseal.rb
  Formula/languagetool.rb
  Formula/libass.rb
  Formula/liblo.rb
  Formula/libmicrohttpd.rb
  Formula/libwpd.rb
  Formula/mecab.rb
  Formula/netcdf.rb
  Formula/numpy.rb
  Formula/open-mpi.rb
  Formula/pulumi.rb
  Formula/pumba.rb
  Formula/qrupdate.rb
  Formula/r.rb
  Formula/scipy.rb
  Formula/suite-sparse.rb
  Formula/sundials.rb
  Formula/superlu.rb
Labels: merge

#15873 Merge 2019-10-02 a63834b2dd
  Formula/apache-geode.rb
  Formula/aws-cdk.rb
  Formula/aws-sdk-cpp.rb
  Formula/faas-cli.rb
  Formula/flow.rb
  Formula/glooctl.rb
  Formula/pbrt.rb
  Formula/ruby-build.rb
  Formula/ship.rb
  Formula/sourcekitten.rb
Labels: merge

#15877 Merge 2019-10-02 0a233cd0ef
  Formula/aom.rb
  Formula/devspace.rb
  Formula/erlang.rb
  Formula/expat.rb
  Formula/freexl.rb
  Formula/gdal.rb
  Formula/glooctl.rb
  Formula/imagemagick.rb
  Formula/istioctl.rb
  Formula/libbluray.rb
  Formula/libheif.rb
  Formula/libspatialite.rb
  Formula/rancher-cli.rb
  Formula/ruby.rb
  Formula/teleport.rb
  Formula/terraformer.rb
  Formula/vala.rb
  Formula/x265.rb
Labels: merge

#15890 Merge 2019-10-02 28d93d3439
  Formula/awscli.rb
  Formula/balena-cli.rb
  Formula/bear.rb
  Formula/buildkit.rb
  Formula/convox.rb
  Formula/dafny.rb
  Formula/dos2unix.rb
  Formula/eslint.rb
  Formula/fn.rb
  Formula/folly.rb
  Formula/fribidi.rb
  Formula/gammu.rb
  Formula/icu4c.rb
  Formula/jenkins-lts.rb
  Formula/kubebuilder.rb
  Formula/lxc.rb
  Formula/packer.rb
  Formula/paket.rb
  Formula/pspg.rb
  Formula/quickjs.rb
  Formula/shared-mime-info.rb
  Formula/ship.rb
  Formula/sops.rb
  Formula/sqlmap.rb
  Formula/step.rb
  Formula/tmuxinator-completion.rb
  Formula/tmuxinator.rb
  Formula/xsimd.rb
Labels: merge

#15911 Merge 2019-10-03 1a4022046e
  .github/workflows/generate_formulae.brew.sh_data.yml
  Formula/alp.rb
  Formula/amazon-ecs-cli.rb
  Formula/angle-grinder.rb
  Formula/cnats.rb
  Formula/exploitdb.rb
  Formula/kubeaudit.rb
  Formula/kubernetes-cli.rb
  Formula/libphonenumber.rb
  Formula/lmod.rb
  Formula/minio.rb
  Formula/mysql-connector-c++@1.1.rb
  Formula/newman.rb
  Formula/newsboat.rb
  Formula/nvm.rb
  Formula/serf.rb
  Formula/varnish.rb
Labels: merge

#15922 Merge 2019-10-03 2128564a1f
  Formula/aws-cdk.rb
  Formula/bee.rb
  Formula/bnd.rb
  Formula/cloc.rb
  Formula/conan.rb
  Formula/cromwell.rb
  Formula/embulk.rb
  Formula/ethereum.rb
  Formula/exploitdb.rb
  Formula/fetchmail.rb
  Formula/gnutls.rb
  Formula/jack.rb
  Formula/k3d.rb
  Formula/knock.rb
  Formula/minizip2.rb
  Formula/ne.rb
  Formula/now-cli.rb
  Formula/peg.rb
  Formula/pssh.rb
  Formula/terragrunt.rb
  Formula/wagyu.rb
  Formula/wsk.rb
  Formula/wtf.rb
Labels: merge

#15938 Merge 2019-10-03 53536059ed
  Aliases/protobuf@3.10
  Formula/apache-arrow.rb
  Formula/aws-okta.rb
  Formula/caffe.rb
  Formula/collectd.rb
  Formula/crystal.rb
  Formula/gmime.rb
  Formula/groonga.rb
  Formula/grpc.rb
  Formula/icdiff.rb
  Formula/juju.rb
  Formula/libphonenumber.rb
  Formula/libpulsar.rb
  Formula/mosh.rb
  Formula/php@7.2.rb
  Formula/pnetcdf.rb
  Formula/protobuf-c.rb
  Formula/protobuf.rb
  Formula/shogun.rb
  Formula/zbackup.rb
Labels: merge

#15952 Merge 2019-10-04 88cd312f21
  Formula/angular-cli.rb
  Formula/armadillo.rb
  Formula/b2-tools.rb
  Formula/cgal.rb
  Formula/cmake.rb
  Formula/ffsend.rb
  Formula/fluid-synth.rb
  Formula/go@1.12.rb
  Formula/gspell.rb
  Formula/haproxy.rb
  Formula/iso-codes.rb
  Formula/joplin.rb
  Formula/kcov.rb
  Formula/libcaca.rb
  Formula/libfabric.rb
  Formula/lmod.rb
  Formula/mkl-dnn.rb
  Formula/newsboat.rb
  Formula/parallel.rb
  Formula/phoronix-test-suite.rb
  Formula/picard-tools.rb
  Formula/rke.rb
  Formula/ruby-build.rb
Labels: merge

#15972 Merge 2019-10-05 55a51cde00
  Formula/balena-cli.rb
  Formula/deno.rb
  Formula/diffr.rb
  Formula/exploitdb.rb
  Formula/ffmpeg.rb
  Formula/gleam.rb
  Formula/gnome-latex.rb
  Formula/lightning.rb
  Formula/minizinc.rb
  Formula/nano.rb
  Formula/node.rb
  Formula/opa.rb
  Formula/openapi-generator.rb
  Formula/prometheus.rb
  Formula/roswell.rb
  Formula/rust.rb
  Formula/screen.rb
  Formula/starship.rb
  Formula/vert.x.rb
  Formula/zint.rb
  Formula/znc.rb
Labels: merge

#15987 Merge 2019-10-05 4045c5a859
  Formula/clib.rb
  Formula/fonttools.rb
  Formula/frugal.rb
  Formula/geos.rb
  Formula/pdsh.rb
  Formula/salt.rb
  Formula/skafos.rb
  Formula/terragrunt.rb
  Formula/v8.rb
  Formula/yaml-cpp.rb
Labels: merge

#15996 Merge 2019-10-05 d3ead9e8d0
  Formula/ballerina.rb
  Formula/cfn-lint.rb
  Formula/exploitdb.rb
  Formula/helmfile.rb
  Formula/kerl.rb
  Formula/kyma-cli.rb
  Formula/pgweb.rb
  Formula/phpunit.rb
  Formula/rclone.rb
Labels: merge

#16003 Merge 2019-10-06 a5a6dc12e0
  Formula/amtk.rb
  Formula/anjuta.rb
  Formula/baobab.rb
  Formula/clutter-gtk.rb
  Formula/conjure-up.rb
  Formula/ettercap.rb
  Formula/evince.rb
  Formula/file-roller.rb
  Formula/gdl.rb
  Formula/gedit.rb
  Formula/ghex.rb
  Formula/gitg.rb
  Formula/glade.rb
  Formula/glib-networking.rb
  Formula/glib.rb
  Formula/gnome-builder.rb
  Formula/gnome-latex.rb
  Formula/gnome-recipes.rb
  Formula/gnumeric.rb
  Formula/gobby.rb
  Formula/goffice.rb
  Formula/gsmartcontrol.rb
  Formula/gspell.rb
  Formula/gtk+3.rb
  Formula/gtk-mac-integration.rb
  Formula/gtkmm3.rb
  Formula/gtksourceview3.rb
  Formula/gtksourceview4.rb
  Formula/gtksourceviewmm3.rb
  Formula/gtkspell3.rb
  Formula/gtranslator.rb
  Formula/gupnp-tools.rb
  Formula/homebank.rb
  Formula/klavaro.rb
  Formula/libdazzle.rb
  Formula/libgweather.rb
  Formula/libpeas.rb
  Formula/osm-gps-map.rb
  Formula/prefixsuffix.rb
  Formula/qalculate-gtk.rb
  Formula/simple-scan.rb
  Formula/siril.rb
  Formula/spice-gtk.rb
  Formula/tepl.rb
  Formula/topgrade.rb
  Formula/vte3.rb
Labels: merge

#16015 Merge 2019-10-06 306d7f8d65
  Formula/bit.rb
  Formula/libdazzle.rb
Labels: merge

#16017 Merge 2019-10-06 8bd2725763
  Aliases/numpy@1.17
  Formula/apache-arrow-glib.rb
  Formula/apache-arrow.rb
  Formula/aws-iam-authenticator.rb
  Formula/dhall.rb
  Formula/findutils.rb
  Formula/gdb.rb
  Formula/gnuradio.rb
  Formula/harfbuzz.rb
  Formula/libsoup.rb
  Formula/libvirt.rb
  Formula/makedepend.rb
  Formula/mcrypt.rb
  Formula/neofetch.rb
  Formula/ntfs-3g.rb
  Formula/numpy.rb
  Formula/numpy@1.16.rb
  Formula/ola.rb
  Formula/opencv@2.rb
  Formula/scipy.rb
  Formula/starship.rb
Labels: merge

#16024 Merge 2019-10-06 3030833081
  Formula/autojump.rb
  Formula/axel.rb
  Formula/clang-format.rb
  Formula/direnv.rb
  Formula/elixir.rb
  Formula/flex.rb
  Formula/geckodriver.rb
  Formula/git-crypt.rb
  Formula/grep.rb
  Formula/gst-plugins-good.rb
  Formula/httrack.rb
  Formula/iperf.rb
  Formula/libgee.rb
  Formula/libnfc.rb
  Formula/media-info.rb
  Formula/mosquitto.rb
  Formula/mutt.rb
  Formula/mycli.rb
  Formula/neon.rb
  Formula/open-babel.rb
  Formula/opendetex.rb
  Formula/optipng.rb
  Formula/povray.rb
  Formula/pstree.rb
  Formula/pv.rb
  Formula/recode.rb
  Formula/rpm.rb
  Formula/sfcgal.rb
  Formula/stoken.rb
  Formula/tig.rb
  Formula/tokyo-cabinet.rb
  Formula/unzip.rb
  Formula/vde.rb
  Formula/voro++.rb
  Formula/wtfutil.rb
  Formula/zimg.rb
Labels: merge

#16025 Merge 2019-10-06 76224652ca
  Formula/bazaar.rb
  Formula/bsdmake.rb
  Formula/confuse.rb
  Formula/glm.rb
  Formula/gtksourceview.rb
  Formula/iperf3.rb
  Formula/jack.rb
  Formula/lftp.rb
  Formula/libconfig.rb
  Formula/libdvdcss.rb
  Formula/libdvdread.rb
  Formula/libelf.rb
  Formula/libid3tag.rb
  Formula/libmpdclient.rb
  Formula/libraw.rb
  Formula/lmdb.rb
  Formula/openmotif.rb
  Formula/physfs.rb
  Formula/rapidjson.rb
  Formula/scalapack.rb
  Formula/speexdsp.rb
  Formula/vapoursynth.rb
  Formula/xonsh.rb
Labels: merge

#16030 Merge 2019-10-06 7cfa271299
  Formula/aalib.rb
  Formula/abook.rb
  Formula/aces_container.rb
  Formula/afflib.rb
  Formula/airspy.rb
  Formula/argp-standalone.rb
  Formula/asciidoctor.rb
  Formula/asio.rb
  Formula/boost-python3.rb
  Formula/clingo.rb
  Formula/consul.rb
  Formula/glpk.rb
  Formula/gsasl.rb
  Formula/hidapi.rb
  Formula/libftdi0.rb
  Formula/libgda.rb
  Formula/libsigsegv.rb
  Formula/lolcat.rb
  Formula/minizip.rb
  Formula/mplayer.rb
  Formula/openconnect.rb
  Formula/re2c.rb
  Formula/reattach-to-user-namespace.rb
  Formula/rrdtool.rb
  Formula/serd.rb
Labels: merge

#16031 Merge 2019-10-07 009e8c0a28
  Formula/augeas.rb
  Formula/cppcheck.rb
  Formula/cppunit.rb
  Formula/ctags.rb
  Formula/e2fsprogs.rb
  Formula/epstool.rb
  Formula/fig2dev.rb
  Formula/gifsicle.rb
  Formula/git-extras.rb
  Formula/gl2ps.rb
  Formula/gpp.rb
  Formula/gst-plugins-bad.rb
  Formula/hashcat.rb
  Formula/highlight.rb
  Formula/hydra.rb
  Formula/icoutils.rb
  Formula/imap-uw.rb
  Formula/libnice.rb
  Formula/libscrypt.rb
  Formula/libsmi.rb
  Formula/libuninameslist.rb
  Formula/netcat.rb
  Formula/nim.rb
  Formula/php@7.1.rb
  Formula/pngquant.rb
  Formula/podofo.rb
  Formula/pstoedit.rb
  Formula/pwgen.rb
  Formula/qemu.rb
  Formula/spdylay.rb
  Formula/stern.rb
  Formula/stunnel.rb
  Formula/tldr.rb
  Formula/uchardet.rb
  Formula/webpack.rb
Labels: merge

#16034 Merge 2019-10-07 df6e047fb3
  Formula/aws-elasticbeanstalk.rb
  Formula/bedtools.rb
  Formula/blueutil.rb
  Formula/cmatrix.rb
  Formula/collectd.rb
  Formula/cowsay.rb
  Formula/dfu-programmer.rb
  Formula/dnscrypt-proxy.rb
  Formula/encfs.rb
  Formula/exa.rb
  Formula/fcrackzip.rb
  Formula/fluxctl.rb
  Formula/fortune.rb
  Formula/freeglut.rb
  Formula/getdns.rb
  Formula/golang-migrate.rb
  Formula/goreleaser.rb
  Formula/hping.rb
  Formula/jpegoptim.rb
  Formula/less.rb
  Formula/libftdi.rb
  Formula/libmemcached.rb
  Formula/libosinfo.rb
  Formula/libspiro.rb
  Formula/mailhog.rb
  Formula/mbedtls.rb
  Formula/minicom.rb
  Formula/mint.rb
  Formula/mkdocs.rb
  Formula/mujs.rb
  Formula/net-snmp.rb
  Formula/nkf.rb
  Formula/nushell.rb
  Formula/operator-sdk.rb
  Formula/portmidi.rb
  Formula/privoxy.rb
  Formula/rdesktop.rb
  Formula/re2.rb
  Formula/sleuthkit.rb
  Formula/spice-protocol.rb
  Formula/squashfs.rb
  Formula/stow.rb
  Formula/talloc.rb
  Formula/tcpdump.rb
  Formula/tcptraceroute.rb
  Formula/tinyxml2.rb
  Formula/unar.rb
  Formula/vegeta.rb
  Formula/wdiff.rb
  Formula/yamllint.rb
  Formula/yq.rb
Labels: merge

#16047 Merge 2019-10-07 156ca45c40
  Formula/apache-zeppelin.rb
  Formula/aspcud.rb
  Formula/bdw-gc.rb
  Formula/berkeley-db@4.rb
  Formula/gjs.rb
  Formula/glooctl.rb
  Formula/hbase.rb
  Formula/htslib.rb
  Formula/i2util.rb
  Formula/imlib2.rb
  Formula/libccd.rb
  Formula/libhid.rb
  Formula/libmodplug.rb
  Formula/libotr.rb
  Formula/libre.rb
  Formula/librsync.rb
  Formula/libspectre.rb
  Formula/libupnp.rb
  Formula/libwpg.rb
  Formula/libxml++.rb
  Formula/monero.rb
  Formula/netlify-cli.rb
  Formula/nnn.rb
  Formula/ocaml-findlib.rb
  Formula/phpunit.rb
  Formula/postgis.rb
  Formula/sdl2_mixer.rb
  Formula/sdl_rtf.rb
  Formula/sip.rb
  Formula/termius.rb
  Formula/terraform.rb
  Formula/unbound.rb
  Formula/wireshark.rb
  Formula/wtf.rb
  Formula/xrootd.rb
  Formula/yash.rb
Labels: merge

#16056 aws-google-auth: Fix build for Linuxbrew
  Formula/aws-google-auth.rb
Labels: checksum mismatch, enhancement

#16057 Merge 2019-10-08 a035f9f7cb
  Formula/aria2.rb
  Formula/ask-cli.rb
  Formula/atasm.rb
  Formula/aws-cdk.rb
  Formula/broot.rb
  Formula/cocoapods.rb
  Formula/cromwell.rb
  Formula/deno.rb
  Formula/diff-pdf.rb
  Formula/evince.rb
  Formula/fmt.rb
  Formula/kubeseal.rb
  Formula/lerna.rb
  Formula/librsvg.rb
  Formula/notifiers.rb
  Formula/nss.rb
  Formula/pdftoipe.rb
  Formula/poppler.rb
  Formula/sccache.rb
  Formula/telegraf.rb
  Formula/terragrunt.rb
  Formula/vte3.rb
  Formula/zsh-completions.rb
Labels: merge

#16074 Merge 2019-10-09 3e5ccd3e47
  Formula/bazel.rb
  Formula/docker-completion.rb
  Formula/docker.rb
  Formula/exploitdb.rb
  Formula/firebase-cli.rb
  Formula/gawk.rb
  Formula/grafana.rb
  Formula/lego.rb
  Formula/liblockfile.rb
  Formula/mysql-connector-c.rb
  Formula/mysql@5.6.rb
  Formula/netlify-cli.rb
  Formula/oxipng.rb
  Formula/postgresql@10.rb
  Formula/postgresql@9.6.rb
  Formula/spdlog.rb
  Formula/starship.rb
  Formula/terragrunt.rb
  Formula/thefuck.rb
  Formula/thrift.rb
  Formula/tor.rb
  Formula/yarn.rb
Labels: merge

#16094 Merge 2019-10-10 9e10fcfa2b
  Formula/aws-sdk-cpp.rb
  Formula/balena-cli.rb
  Formula/duo_unix.rb
  Formula/etcd.rb
  Formula/fauna-shell.rb
  Formula/glooctl.rb
  Formula/jrnl.rb
  Formula/lerna.rb
  Formula/librdkafka.rb
  Formula/maxwell.rb
  Formula/metaproxy.rb
  Formula/minio-mc.rb
  Formula/node@8.rb
  Formula/paket.rb
  Formula/pspg.rb
  Formula/pulumi.rb
  Formula/repo.rb
  Formula/tile38.rb
  Formula/typescript.rb
Labels: merge

#16104 Merge 2019-10-10 2da781ffc5
  Formula/armadillo.rb
  Formula/base64.rb
  Formula/bazel.rb
  Formula/coq.rb
  Formula/erlang.rb
  Formula/exploitdb.rb
  Formula/flyway.rb
  Formula/folly.rb
  Formula/ginac.rb
  Formula/gmic.rb
  Formula/gocryptfs.rb
  Formula/imagesnap.rb
  Formula/inlets.rb
  Formula/libpcap.rb
  Formula/libsass.rb
  Formula/math-comp.rb
  Formula/meson.rb
  Formula/newman.rb
  Formula/ola.rb
  Formula/pdfgrep.rb
  Formula/ppsspp.rb
  Formula/procmail.rb
  Formula/screenfetch.rb
  Formula/subnetcalc.rb
  Formula/supersonic.rb
  Formula/terragrunt.rb
  Formula/wavpack.rb
  Formula/zshdb.rb
Labels: merge

#16118 Merge 2019-10-10 0db1fad3f4
  Formula/beanstalkd.rb
  Formula/black.rb
  Formula/brightness.rb
  Formula/davix.rb
  Formula/enca.rb
  Formula/gifski.rb
  Formula/libiodbc.rb
  Formula/librtlsdr.rb
  Formula/root.rb
  Formula/s3fs.rb
  Formula/svgo.rb
Labels: merge

#16122 Merge 2019-10-11 48a3a49c57
  Formula/aws-okta.rb
  Formula/bind.rb
  Formula/clamav.rb
  Formula/ffmpeg.rb
  Formula/ffmpeg@2.8.rb
  Formula/fontforge.rb
  Formula/geos.rb
  Formula/git-flow-avh.rb
  Formula/grip.rb
  Formula/jhipster.rb
  Formula/jsonlint.rb
  Formula/libheif.rb
  Formula/mongoose.rb
  Formula/mysqltuner.rb
  Formula/netdata.rb
  Formula/nu.rb
  Formula/opencolorio.rb
  Formula/opencv.rb
  Formula/pinentry-mac.rb
  Formula/pioneer.rb
  Formula/pngcrush.rb
  Formula/procs.rb
  Formula/pwntools.rb
  Formula/re-flex.rb
  Formula/sbjson.rb
  Formula/scrcpy.rb
  Formula/stgit.rb
  Formula/tcpreplay.rb
  Formula/tiger-vnc.rb
  Formula/weechat.rb
  Formula/wireguard-go.rb
  Formula/wxmaxima.rb
  Formula/x264.rb
  Formula/x265.rb
  Formula/xxhash.rb
Labels: merge

#16136 Merge 2019-10-11 e1c4362eea
  Formula/avrdude.rb
  Formula/binwalk.rb
  Formula/dcraw.rb
  Formula/docker-credential-helper-ecr.rb
  Formula/emscripten.rb
  Formula/fdk-aac.rb
  Formula/gmediaserver.rb
  Formula/gnu-shogi.rb
  Formula/hayai.rb
  Formula/httpflow.rb
  Formula/imagejs.rb
  Formula/keystone.rb
  Formula/ldid.rb
  Formula/libpagemaker.rb
  Formula/libucl.rb
  Formula/libwandevent.rb
  Formula/libyubikey.rb
  Formula/lsd.rb
  Formula/lwtools.rb
  Formula/lzip.rb
  Formula/m2c.rb
  Formula/madplay.rb
  Formula/malbolge.rb
  Formula/minised.rb
  Formula/mit-scheme.rb
  Formula/mp3fs.rb
  Formula/mpage.rb
  Formula/mruby-cli.rb
  Formula/namazu.rb
  Formula/opencv@3.rb
  Formula/openslide.rb
  Formula/ossp-uuid.rb
  Formula/pigz.rb
  Formula/platformio.rb
  Formula/pure-ftpd.rb
  Formula/pybind11.rb
  Formula/rocksdb.rb
  Formula/s3cmd.rb
  Formula/sourcery.rb
  Formula/sphinx.rb
  Formula/tcpflow.rb
  Formula/trash.rb
  Formula/vtclock.rb
  Formula/wbox.rb
  Formula/wumpus.rb
  Formula/wv2.rb
  Formula/xpa.rb
  Formula/yaze-ag.rb
  Formula/yazpp.rb
  Formula/ykpers.rb
  Formula/z80asm.rb
  Formula/z80dasm.rb
  Formula/zdelta.rb
Labels: merge

#16137 Merge 2019-10-11 55654cbbbc
  Formula/admesh.rb
  Formula/align.rb
  Formula/atdtool.rb
  Formula/balance.rb
  Formula/bbcolors.rb
  Formula/bcpp.rb
  Formula/bittwist.rb
  Formula/bsdconv.rb
  Formula/cdargs.rb
  Formula/codec2.rb
  Formula/color-code.rb
  Formula/cppp.rb
  Formula/cubelib.rb
  Formula/dcadec.rb
  Formula/devtodo.rb
  Formula/dlite.rb
  Formula/dwatch.rb
  Formula/dxflib.rb
  Formula/etsh.rb
  Formula/euca2ools.rb
  Formula/fits.rb
  Formula/flint-checker.rb
  Formula/flvmeta.rb
  Formula/g2.rb
  Formula/g3log.rb
  Formula/httpdiff.rb
  Formula/hyperkit.rb
  Formula/iprint.rb
  Formula/irrtoolset.rb
  Formula/ivykis.rb
  Formula/jnethack.rb
  Formula/libowfat.rb
  Formula/libwps.rb
  Formula/mecab-ko.rb
  Formula/mecab-unidic.rb
  Formula/mikmod.rb
  Formula/mlogger.rb
  Formula/ncompress.rb
  Formula/oath-toolkit.rb
  Formula/openjazz.rb
  Formula/openmsx.rb
  Formula/otf2.rb
  Formula/ott.rb
  Formula/rem.rb
  Formula/rex.rb
  Formula/rnv.rb
  Formula/snobol4.rb
  Formula/snow.rb
  Formula/sql-translator.rb
  Formula/switch-lan-play.rb
  Formula/syntaxerl.rb
  Formula/terraform@0.11.rb
  Formula/testdisk.rb
Labels: merge

#16139 Merge 2019-10-11 ad5ecdfbc9
  Formula/abcl.rb
  Formula/alac.rb
  Formula/apache-forrest.rb
  Formula/bsdsfv.rb
  Formula/bsponmpi.rb
  Formula/bwctl.rb
  Formula/cconv.rb
  Formula/diamond.rb
  Formula/eless.rb
  Formula/flatcc.rb
  Formula/gdcm.rb
  Formula/gifski.rb
  Formula/instead.rb
  Formula/libical.rb
  Formula/modgit.rb
  Formula/nomad.rb
  Formula/opencv.rb
  Formula/openimageio.rb
  Formula/pdfcpu.rb
  Formula/pgbadger.rb
  Formula/roll.rb
  Formula/scalaenv.rb
  Formula/soci.rb
  Formula/sparse.rb
  Formula/stdman.rb
  Formula/stone.rb
  Formula/sword.rb
  Formula/wartremover.rb
  Formula/xsd.rb
  Formula/zboy.rb
Labels: merge

#16150 Merge 2019-10-11 e81963f35f
  Formula/alexjs.rb
  Formula/benthos.rb
  Formula/cern-ndiff.rb
  Formula/clang-format.rb
  Formula/duplicity.rb
  Formula/gitlab-gem.rb
  Formula/glib.rb
  Formula/glooctl.rb
  Formula/goreman.rb
  Formula/opentracing-cpp.rb
  Formula/openvdb.rb
  Formula/operator-sdk.rb
  Formula/osmium-tool.rb
  Formula/pagmo.rb
  Formula/pdf2json.rb
  Formula/pgformatter.rb
  Formula/pspg.rb
  Formula/swift-protobuf.rb
  Formula/swiftformat.rb
  Formula/tarsnap-gui.rb
  Formula/tenyr.rb
  Formula/vfuse.rb
  Formula/wp-cli-completion.rb
Labels: merge

#16166 Merge 2019-10-11 261dd96829
  Formula/babel.rb
  Formula/csmith.rb
  Formula/direvent.rb
  Formula/djmount.rb
  Formula/dnscontrol.rb
  Formula/docker-machine-driver-vultr.rb
  Formula/dvorak7min.rb
  Formula/dwarf.rb
  Formula/ffmpegthumbnailer.rb
  Formula/grt.rb
  Formula/helmfile.rb
  Formula/k3d.rb
  Formula/kakasi.rb
  Formula/kstart.rb
  Formula/kytea.rb
  Formula/lcrack.rb
  Formula/lesstif.rb
  Formula/libantlr3c.rb
  Formula/libbind.rb
  Formula/libbinio.rb
  Formula/libchewing.rb
  Formula/libcsv.rb
  Formula/libetpan.rb
  Formula/libgosu.rb
  Formula/libmonome.rb
  Formula/libstatgrab.rb
  Formula/link-grammar.rb
  Formula/lpc21isp.rb
  Formula/mecab-jumandic.rb
  Formula/memcacheq.rb
  Formula/mitie.rb
  Formula/mm-common.rb
  Formula/mpfi.rb
  Formula/naga.rb
  Formula/ncdc.rb
  Formula/pacapt.rb
  Formula/pioneers.rb
  Formula/pound.rb
  Formula/quotatool.rb
  Formula/tmx.rb
  Formula/topgit.rb
  Formula/traildb.rb
  Formula/twoping.rb
  Formula/txr.rb
  Formula/udpxy.rb
  Formula/vip.rb
  Formula/vncsnapshot.rb
  Formula/w-calc.rb
  Formula/webarchiver.rb
  Formula/xtail.rb
Labels: merge

#16182 Merge 2019-10-11 49ec13c732
  Formula/bitchx.rb
  Formula/chrome-cli.rb
  Formula/cliclick.rb
  Formula/cquery.rb
  Formula/datamash.rb
  Formula/doitlive.rb
  Formula/ext2fuse.rb
  Formula/fzy.rb
  Formula/game-music-emu.rb
  Formula/gearman.rb
  Formula/leiningen.rb
  Formula/libbitcoin.rb
  Formula/most.rb
  Formula/mozjpeg.rb
  Formula/mu.rb
  Formula/multimarkdown.rb
  Formula/nethogs.rb
  Formula/pugixml.rb
  Formula/rmlint.rb
  Formula/sl.rb
  Formula/tintin.rb
  Formula/tippecanoe.rb
  Formula/w3m.rb
  Formula/xdotool.rb
Labels: merge

#16183 Merge 2019-10-11 8aa6c87b4b
  Formula/angular-cli.rb
  Formula/cassandra.rb
  Formula/exploitdb.rb
  Formula/gpatch.rb
  Formula/libressl.rb
  Formula/minio.rb
  Formula/postgresql@9.4.rb
  Formula/proxychains-ng.rb
  Formula/ruby-install.rb
  Formula/teleport.rb
  Formula/terraformer.rb
  Formula/webpack.rb
  Formula/wireguard-tools.rb
  Formula/xhyve.rb
Labels: merge

#16184 Merge 2019-10-11 44233a7789
  Formula/cypher-shell.rb
  Formula/jhipster.rb
  Formula/odpi.rb
  Formula/pastel.rb
Labels: merge

#16188 Merge 2019-10-11 e3905928c8
  Formula/cloog.rb
  Formula/gopass.rb
  Formula/mono-libgdiplus.rb
  Formula/octomap.rb
  Formula/openh264.rb
  Formula/potrace.rb
  Formula/strongswan.rb
  Formula/zip.rb
Labels: merge

#16191 Merge 2019-10-12 36c26bb87e
  Formula/antibody.rb
  Formula/appium.rb
  Formula/cockroach.rb
  Formula/io.rb
  Formula/iproute2mac.rb
  Formula/libslax.rb
  Formula/minio.rb
  Formula/openjazz.rb
  Formula/osqp.rb
  Formula/pulumi.rb
  Formula/riemann.rb
  Formula/skaffold.rb
  Formula/terragrunt.rb
  Formula/volatility.rb
  Formula/wtfutil.rb
  Formula/yara.rb
Labels: merge

#16204 Remove remaining CIRCLECI checks for Linuxbrew
  Formula/asio.rb
  Formula/blast.rb
  Formula/boost-mpi.rb
  Formula/clang-format.rb
  Formula/consul.rb
  Formula/corebird.rb
  Formula/dbxml.rb
  Formula/freeswitch.rb
  Formula/gdal.rb
  Formula/ginac.rb
  Formula/gl2ps.rb
  Formula/gnu-tar.rb
  Formula/inspectrum.rb
  Formula/kibana@4.4.rb
  Formula/makefile2graph.rb
  Formula/mednafen.rb
  Formula/mysql@5.7.rb
  Formula/nnn.rb
  Formula/p11-kit.rb
  Formula/ppsspp.rb
  Formula/protobuf@3.1.rb
  Formula/rocksdb.rb
  Formula/rust.rb
  Formula/wabt.rb
Labels: enhancement

#16210 Merge 2019-10-12 8b9fc94181
  Formula/glances.rb
  Formula/operator-sdk.rb
  Formula/shadowsocks-libev.rb
  Formula/tflint.rb
Labels: merge

#16226 Merge 2019-10-13 e058513757
  Formula/aliyun-cli.rb
  Formula/devspace.rb
  Formula/docfx.rb
  Formula/erlang.rb
  Formula/istioctl.rb
  Formula/librsync.rb
  Formula/maxwell.rb
  Formula/tbb.rb
  Formula/terraformer.rb
  Formula/tmate.rb
Labels: merge

#16239 Merge 2019-10-13 5612a02239
  Formula/arduino-cli.rb
  Formula/bitwarden-cli.rb
  Formula/bluepill.rb
  Formula/clutter.rb
  Formula/cogl.rb
  Formula/dnscrypt-proxy.rb
  Formula/fabio.rb
  Formula/fork-cleaner.rb
  Formula/gitup.rb
  Formula/htmlcleaner.rb
  Formula/icemon.rb
  Formula/ipv6calc.rb
  Formula/ircd-hybrid.rb
  Formula/iron-functions.rb
  Formula/known_hosts.rb
  Formula/libosip.rb
  Formula/libpuzzle.rb
  Formula/libresample.rb
  Formula/libspnav.rb
  Formula/libspng.rb
  Formula/libstrophe.rb
  Formula/libtextcat.rb
  Formula/lxsplit.rb
  Formula/mairix.rb
  Formula/mmark.rb
  Formula/prototool.rb
  Formula/robotfindskitten.rb
  Formula/vte3.rb
  Formula/wandio.rb
  Formula/wcslib.rb
  Formula/xml-tooling-c.rb
  Formula/xmltoman.rb
Labels: merge

#16306 Merge 2019-10-13 c0670cea7a
  Formula/ktlint.rb
  Formula/lcdproc.rb
  Formula/lci.rb
  Formula/libbi.rb
  Formula/libcds.rb
  Formula/libcmph.rb
  Formula/libdill.rb
  Formula/libgetdata.rb
  Formula/pipebench.rb
  Formula/pms.rb
  Formula/posh.rb
  Formula/powerman.rb
  Formula/primer3.rb
  Formula/qdbm.rb
  Formula/qprint.rb
  Formula/qtads.rb
  Formula/qxmpp.rb
  Formula/redex.rb
  Formula/reprepro.rb
  Formula/rp.rb
  Formula/scour.rb
  Formula/scrub.rb
  Formula/scummvm-tools.rb
Labels: merge

#16308 Merge 2019-10-13 23784d4bb6
  Formula/bedops.rb
  Formula/berglas.rb
  Formula/blink1.rb
  Formula/dcm2niix.rb
  Formula/elixir.rb
  Formula/gatsby-cli.rb
  Formula/git-revise.rb
  Formula/git-secrets.rb
  Formula/hypre.rb
  Formula/imapfilter.rb
  Formula/inetutils.rb
  Formula/influxdb.rb
  Formula/insect.rb
  Formula/kafkacat.rb
  Formula/libjwt.rb
  Formula/mkvtoolnix.rb
  Formula/needle.rb
  Formula/openssh.rb
  Formula/pass.rb
  Formula/pdal.rb
  Formula/postgresql@9.5.rb
  Formula/quicktype.rb
  Formula/swagger-codegen.rb
  Formula/vips.rb
Labels: merge

#16318 Merge 2019-10-14 24c6ba24ff
  Formula/arp-scan.rb
  Formula/arping.rb
  Formula/ask-cli.rb
  Formula/autossh.rb
  Formula/bcal.rb
  Formula/bcftools.rb
  Formula/bchunk.rb
  Formula/bcrypt.rb
  Formula/bde.rb
  Formula/boost-mpi.rb
  Formula/boost-python.rb
  Formula/boost-python3.rb
  Formula/boost.rb
  Formula/capstone.rb
  Formula/cucumber-cpp.rb
  Formula/diffutils.rb
  Formula/dive.rb
  Formula/docker-machine-driver-hyperkit.rb
  Formula/dpkg.rb
  Formula/grunt-cli.rb
  Formula/gzip.rb
  Formula/hyperfine.rb
  Formula/icarus-verilog.rb
  Formula/iftop.rb
  Formula/jena.rb
  Formula/john-jumbo.rb
  Formula/lazydocker.rb
  Formula/lazygit.rb
  Formula/libvirt-glib.rb
  Formula/m4.rb
  Formula/newt.rb
  Formula/ntl.rb
  Formula/nuget.rb
  Formula/octant.rb
  Formula/opensc.rb
  Formula/osquery.rb
  Formula/parquet-tools.rb
  Formula/passenger.rb
  Formula/percona-toolkit.rb
  Formula/singular.rb
  Formula/starship.rb
  Formula/streamlink.rb
  Formula/tomcat.rb
  Formula/tomcat@8.rb
Labels: merge

#16328 Merge 2019-10-14 82ef5a2b26
  Formula/beecrypt.rb
  Formula/bento4.rb
  Formula/bgpdump.rb
  Formula/bgpq3.rb
  Formula/bibtexconv.rb
  Formula/bibutils.rb
  Formula/binaryen.rb
  Formula/binkd.rb
  Formula/bitwise.rb
  Formula/blahtexml.rb
  Formula/blastem.rb
  Formula/blazeblogger.rb
  Formula/blitz.rb
  Formula/boringtun.rb
  Formula/bowtie2.rb
  Formula/boxes.rb
  Formula/bpm-tools.rb
  Formula/brainfuck.rb
  Formula/breezy.rb
  Formula/brogue.rb
  Formula/bsdiff.rb
  Formula/btfs.rb
  Formula/btparse.rb
  Formula/bwm-ng.rb
  Formula/byacc.rb
  Formula/bzr-fastimport.rb
  Formula/bzt.rb
  Formula/c-blosc.rb
  Formula/catch2.rb
  Formula/cf4ocl.rb
  Formula/cfengine.rb
  Formula/cflow.rb
  Formula/cfv.rb
  Formula/cgdb.rb
  Formula/cgit.rb
  Formula/cglm.rb
  Formula/cgoban.rb
  Formula/cgvg.rb
  Formula/chadwick.rb
  Formula/chafa.rb
  Formula/chaiscript.rb
  Formula/chapel.rb
  Formula/elinks.rb
  Formula/git-delta.rb
  Formula/ice.rb
  Formula/nanopb-generator.rb
  Formula/texinfo.rb
  Formula/zookeeper.rb
Labels: merge

#16334 Merge 2019-10-14 46e720494c
  Formula/afsctool.rb
  Formula/aften.rb
  Formula/afuse.rb
  Formula/agedu.rb
  Formula/aggregate.rb
  Formula/aha.rb
  Formula/ahcpd.rb
  Formula/ahoy.rb
  Formula/aide.rb
  Formula/akamai.rb
  Formula/aldo.rb
  Formula/alpine.rb
  Formula/autopep8.rb
  Formula/cbmbasic.rb
  Formula/cc65.rb
  Formula/ccal.rb
  Formula/ccat.rb
  Formula/ccd2iso.rb
  Formula/cdb.rb
  Formula/cdecl.rb
  Formula/cdk.rb
  Formula/cdlabelgen.rb
  Formula/cdogs-sdl.rb
  Formula/cdparanoia.rb
  Formula/cdpr.rb
  Formula/cdrdao.rb
  Formula/cdrtools.rb
  Formula/center-im.rb
  Formula/cheat.rb
  Formula/check_postgres.rb
  Formula/chezscheme.rb
  Formula/chibi-scheme.rb
  Formula/chicken.rb
  Formula/dylibbundler.rb
  Formula/feh.rb
  Formula/gist.rb
  Formula/igraph.rb
  Formula/knock.rb
  Formula/kube-aws.rb
  Formula/lerna.rb
  Formula/libbs2b.rb
  Formula/libnfs.rb
  Formula/mawk.rb
  Formula/mysql@5.5.rb
  Formula/pcsc-lite.rb
  Formula/pdftk-java.rb
  Formula/qpdf.rb
  Formula/rarian.rb
  Formula/truncate.rb
  Formula/xmlstarlet.rb
  Formula/zopfli.rb
Labels: merge

#16353 Merge 2019-10-14 cdb2152340
  Formula/balena-cli.rb
  Formula/docker-machine-nfs.rb
  Formula/extract_url.rb
  Formula/exult.rb
  Formula/eye-d3.rb
  Formula/ezstream.rb
  Formula/fakeroot.rb
  Formula/fastbit.rb
  Formula/fb-client.rb
  Formula/fceux.rb
  Formula/fcitx-remote-for-osx.rb
  Formula/fcl.rb
  Formula/fdk-aac-encoder.rb
  Formula/fdroidserver.rb
  Formula/ficy.rb
  Formula/field3d.rb
  Formula/fizsh.rb
  Formula/flac123.rb
  Formula/flake8.rb
  Formula/flann.rb
  Formula/flashrom.rb
  Formula/flif.rb
  Formula/flow-tools.rb
  Formula/fmsx.rb
  Formula/fsevent_watch.rb
  Formula/fsevents-tools.rb
  Formula/fsql.rb
  Formula/fstrm.rb
  Formula/ftgl.rb
  Formula/ftjam.rb
  Formula/fuse-zip.rb
  Formula/fuzzy-find.rb
  Formula/fwknop.rb
  Formula/h2.rb
  Formula/libbitcoin-consensus.rb
  Formula/libbitcoin-database.rb
  Formula/libbitcoin-network.rb
  Formula/libbitcoin-protocol.rb
  Formula/qbs.rb
  Formula/wireguard-tools.rb
Labels: merge

#16358 Merge 2019-10-15 c89583a568
  Formula/restic.rb
  Formula/sbt.rb
  Formula/starship.rb
Labels: merge

#16365 Merge 2019-10-15 7d4a89794e
  Formula/bzt.rb
  Formula/duplicity.rb
  Formula/freeipmi.rb
  Formula/freeling.rb
  Formula/freeradius-server.rb
  Formula/libaacs.rb
  Formula/libagg.rb
  Formula/libb2.rb
  Formula/libbdplus.rb
  Formula/libbpg.rb
  Formula/libbtbb.rb
  Formula/libcapn.rb
  Formula/libcuefile.rb
  Formula/libdc1394.rb
  Formula/libdshconfig.rb
  Formula/libdv.rb
  Formula/libdvbpsi.rb
  Formula/libdvdnav.rb
  Formula/librsvg.rb
  Formula/libtins.rb
  Formula/libtrace.rb
  Formula/libtrng.rb
  Formula/mysql.rb
  Formula/mysql@5.6.rb
  Formula/mysql@5.7.rb
  Formula/s6.rb
  Formula/sagittarius-scheme.rb
  Formula/saldl.rb
  Formula/samtools.rb
  Formula/sassc.rb
  Formula/sblim-sfcc.rb
  Formula/sc-im.rb
  Formula/sc68.rb
  Formula/scale2x.rb
  Formula/scamper.rb
  Formula/scc.rb
  Formula/scdoc.rb
  Formula/sceptre.rb
  Formula/scheme48.rb
  Formula/schroedinger.rb
  Formula/scm-manager.rb
  Formula/scmpuff.rb
  Formula/scriptcs.rb
  Formula/scrollkeeper.rb
  Formula/tektoncd-cli.rb
Labels: merge

#16371 Merge 2019-10-15 66db2ec220
  Formula/jenkins.rb
  Formula/linkerd.rb
  Formula/neo4j.rb
  Formula/scc.rb
  Formula/scrypt.rb
  Formula/scs.rb
  Formula/scummvm.rb
  Formula/scw.rb
  Formula/sd.rb
  Formula/sdb.rb
  Formula/sdcv.rb
  Formula/sdhash.rb
  Formula/securefs.rb
  Formula/seqtk.rb
  Formula/ser2net.rb
  Formula/sersniff.rb
  Formula/serve.rb
  Formula/servus.rb
  Formula/sf-pwgen.rb
  Formula/shairport.rb
  Formula/shapelib.rb
  Formula/shc.rb
  Formula/shellharden.rb
  Formula/shellinabox.rb
  Formula/shellz.rb
  Formula/shfmt.rb
  Formula/shivavg.rb
  Formula/shmcat.rb
  Formula/shmux.rb
  Formula/shntool.rb
  Formula/shocco.rb
  Formula/shyaml.rb
  Formula/sic.rb
  Formula/sickle.rb
  Formula/sift.rb
  Formula/signify-osx.rb
  Formula/sile.rb
  Formula/simg2img.rb
  Formula/simh.rb
  Formula/simple-mtpfs.rb
  Formula/simple-tiles.rb
  Formula/since.rb
  Formula/sipcalc.rb
  Formula/sipp.rb
  Formula/sipsak.rb
  Formula/sispmctl.rb
  Formula/ski.rb
  Formula/skktools.rb
  Formula/slashem.rb
  Formula/slowhttptest.rb
Labels: merge

#16374 Merge 2019-10-15 b038c78b26
  Formula/slackcat.rb
  Formula/sleepwatcher.rb
  Formula/sloc.rb
  Formula/slrn.rb
  Formula/slurm.rb
  Formula/smimesign.rb
  Formula/smpeg2.rb
  Formula/sn0int.rb
  Formula/snag.rb
  Formula/snakemake.rb
  Formula/snap-telemetry.rb
  Formula/snap7.rb
  Formula/snappystream.rb
  Formula/snzip.rb
  Formula/sofia-sip.rb
  Formula/softhsm.rb
  Formula/solid.rb
  Formula/somagic-tools.rb
  Formula/spaceinvaders-go.rb
  Formula/spades.rb
  Formula/spandsp.rb
  Formula/sparkey.rb
  Formula/spatialite-gui.rb
  Formula/spawn-fcgi.rb
  Formula/speech-tools.rb
  Formula/spim.rb
  Formula/spin.rb
  Formula/sqldiff.rb
  Formula/sqlite-analyzer.rb
  Formula/sqliteodbc.rb
  Formula/sqlparse.rb
  Formula/squashfuse.rb
  Formula/sshguard.rb
  Formula/sshtrix.rb
  Formula/sslh.rb
  Formula/ssllabs-scan.rb
  Formula/sslmate.rb
  Formula/sslsplit.rb
  Formula/ssss.rb
  Formula/st.rb
  Formula/star.rb
  Formula/startup-notification.rb
  Formula/statik.rb
  Formula/stella.rb
  Formula/stk.rb
  Formula/stlviewer.rb
  Formula/stm32flash.rb
  Formula/stockfish.rb
  Formula/stolon.rb
  Formula/stone-soup.rb
  cmd/brew-aspell-dictionaries.rb
  cmd/brew-postgresql-upgrade-database.rb
Labels: merge

#16379 Merge 2019-10-15 f4715d87c0
  Formula/snapraid.rb
  Formula/spiped.rb
  Formula/spirv-tools.rb
  Formula/splint.rb
  Formula/spoof-mac.rb
  Formula/sproxy.rb
  Formula/stormpath-cli.rb
  Formula/stout.rb
  Formula/streamripper.rb
  Formula/stress.rb
  Formula/svgcleaner.rb
Labels: merge

#16383 Merge 2019-10-15 182bd4215a
  Formula/aespipe.rb
  Formula/azure-cli.rb
  Formula/calicoctl.rb
  Formula/glooctl.rb
  Formula/janet.rb
  Formula/mpd.rb
  Formula/screenfetch.rb
  Formula/ssed.rb
  Formula/svdlibc.rb
  Formula/svg2pdf.rb
  Formula/svg2png.rb
  Formula/svtplay-dl.rb
  Formula/vim.rb
  Formula/yamllint.rb
Labels: merge

#16392 Merge 2019-10-15 c55434745e
  Formula/gauche.rb
  Formula/gaul.rb
  Formula/gbdfed.rb
  Formula/gcal.rb
  Formula/gcore.rb
  Formula/gcovr.rb
  Formula/gcsfuse.rb
  Formula/gdm.rb
  Formula/gdmap.rb
  Formula/geant4.rb
  Formula/gearboy.rb
  Formula/gearsystem.rb
  Formula/gecode.rb
  Formula/geeqie.rb
  Formula/gegl.rb
  Formula/gel.rb
  Formula/genact.rb
  Formula/genders.rb
  Formula/generate-json-schema.rb
  Formula/genext2fs.rb
  Formula/geocode-glib.rb
  Formula/gerbv.rb
  Formula/get-flash-videos.rb
  Formula/getmail.rb
  Formula/getxbook.rb
  Formula/gexiv2.rb
  Formula/giflossy.rb
  Formula/git-absorb.rb
  Formula/git-archive-all.rb
  Formula/git-cal.rb
  Formula/git-cinnabar.rb
  Formula/git-fixup.rb
  Formula/git-hooks.rb
  Formula/git-if.rb
  Formula/git-imerge.rb
  Formula/git-multipush.rb
  Formula/git-now.rb
  Formula/git-number.rb
  Formula/git-octopus.rb
  Formula/git-remote-hg.rb
Labels: merge

#16394 Merge 2019-10-15 2956715f90
  Formula/gforth.rb
  Formula/git-review.rb
  Formula/git-series.rb
  Formula/git-sh.rb
  Formula/git-sizer.rb
  Formula/git-subrepo.rb
  Formula/git-town.rb
  Formula/git-tracker.rb
  Formula/git-url-sub.rb
  Formula/git-vendor.rb
  Formula/gitfs.rb
  Formula/github-markdown-toc.rb
  Formula/github-release.rb
  Formula/gitleaks.rb
  Formula/gitless.rb
  Formula/gitmoji.rb
  Formula/gitslave.rb
  Formula/gkrellm.rb
  Formula/glbinding.rb
  Formula/glkterm.rb
  Formula/global.rb
  Formula/globe.rb
  Formula/globus-toolkit.rb
  Formula/gloox.rb
  Formula/glslang.rb
  Formula/glslviewer.rb
  Formula/glui.rb
  Formula/glulxe.rb
  Formula/glyr.rb
  Formula/gmt.rb
  Formula/gmt@4.rb
  Formula/gnome-autoar.rb
  Formula/gnu-apl.rb
  Formula/gnu-barcode.rb
  Formula/gnu-chess.rb
  Formula/gnu-cobol.rb
  Formula/gnu-go.rb
  Formula/gnu-smalltalk.rb
  Formula/gnu-time.rb
  Formula/gnu-typist.rb
  Formula/gnu-units.rb
  Formula/gnunet.rb
  Formula/gnupg-pkcs11-scd.rb
  Formula/gnupg@1.4.rb
  Formula/gnuplot@4.rb
  Formula/gnuski.rb
  Formula/gnustep-make.rb
  Formula/go-statik.rb
Labels: merge

#16398 Merge 2019-10-15 54ebbf100c
  Formula/yle-dl.rb
  Formula/yosys.rb
  Formula/yubico-piv-tool.rb
  Formula/yydecode.rb
  Formula/zabbix-cli.rb
  Formula/zile.rb
  Formula/zlog.rb
  Formula/zmap.rb
  Formula/znapzend.rb
  Formula/zorba.rb
  Formula/zork.rb
Labels: merge

#16400 Merge 2019-10-16 f89017354e
  Formula/exploitdb.rb
  Formula/x3270.rb
  Formula/xa.rb
  Formula/xalan-c.rb
  Formula/xaric.rb
  Formula/xbee-comm.rb
  Formula/zsync.rb
  Formula/zurl.rb
  Formula/zydis.rb
  Formula/zyre.rb
  Formula/zzuf.rb
Labels: merge

#16401 Merge 2019-10-16 33a15023ba
  Formula/aws-cdk.rb
  Formula/convox.rb
  Formula/dark-mode.rb
  Formula/docker-squash.rb
  Formula/kubecfg.rb
  Formula/mono-libgdiplus.rb
  Formula/starship.rb
  Formula/webpack.rb
Labels: merge

#16402 Merge 2019-10-16 2a83d48980
  Formula/logtalk.rb
  Formula/watch-sim.rb
  Formula/watchexec.rb
  Formula/wdc.rb
  Formula/wdfs.rb
  Formula/web100clt.rb
  Formula/webalizer.rb
  Formula/webdis.rb
  Formula/webfs.rb
  Formula/weboob.rb
  Formula/websocketd.rb
  Formula/xclip.rb
  Formula/xcproj.rb
  Formula/xlispstat.rb
  Formula/xlslib.rb
  Formula/xmake.rb
  Formula/xml-coreutils.rb
  Formula/xml2.rb
  Formula/xmlcatmgr.rb
  Formula/xmlrpc-c.rb
  Formula/xmp.rb
  Formula/xmrig.rb
  Formula/xorriso.rb
  Formula/xplanet.rb
  Formula/xqilla.rb
  Formula/xrick.rb
  Formula/xsane.rb
  Formula/xshogi.rb
  Formula/xspin.rb
  Formula/xsv.rb
  Formula/xtensor.rb
  Formula/xu4.rb
  Formula/zabbix.rb
  Formula/zenity.rb
  Formula/zita-convolver.rb
  Formula/zpaq.rb
  Formula/zpython.rb
  Formula/zrepl.rb
  Formula/zsh-navigation-tools.rb
  Formula/zssh.rb
Labels: merge

#16413 Merge 2019-10-16 cc5c17ac7e
  Formula/cayley.rb
  Formula/ical-buddy.rb
  Formula/kpcli.rb
  Formula/mame.rb
  Formula/mypy.rb
Labels: merge

#16439 Merge 2019-10-17 de4ff05313
  Formula/angle-grinder.rb
  Formula/botan.rb
  Formula/conan.rb
  Formula/kompose.rb
  Formula/libphonenumber.rb
  Formula/memcached.rb
  Formula/perltidy.rb
  Formula/pyenv.rb
  Formula/r3.rb
  Formula/rack.rb
  Formula/radamsa.rb
  Formula/rancher-compose.rb
  Formula/rawtoaces.rb
  Formula/raylib.rb
  Formula/rbspy.rb
  Formula/rc.rb
  Formula/rcs.rb
  Formula/reaver.rb
  Formula/redir.rb
  Formula/tj.rb
  Formula/tmpreaper.rb
  Formula/tmux-mem-cpu-load.rb
  Formula/tnef.rb
  Formula/tre.rb
  Formula/treecc.rb
  Formula/treefrog.rb
  Formula/trezor-agent.rb
  Formula/triangle.rb
  Formula/triton.rb
  Formula/truecrack.rb
  Formula/tsung.rb
  Formula/tta.rb
  Formula/ttf2eot.rb
  Formula/ttfautohint.rb
  Formula/tth.rb
  Formula/tty-clock.rb
  Formula/tty-solitaire.rb
  Formula/ttyd.rb
  Formula/ttygif.rb
  Formula/tundra.rb
  Formula/tunnel.rb
  Formula/tup.rb
  Formula/tvnamer.rb
  Formula/twarc.rb
  Formula/twemcache.rb
  Formula/twine-pypi.rb
  Formula/typespeed.rb
Labels: merge

#16521 Merge 2019-10-18 b9628a2fad
  Formula/llnode.rb
  Formula/lnav.rb
  Formula/mmix.rb
  Formula/mmseqs2.rb
  Formula/mmsrip.rb
  Formula/mmv.rb
  Formula/mp3gain.rb
  Formula/mp3info.rb
  Formula/mp3splt.rb
  Formula/mp3unicode.rb
  Formula/mp3val.rb
  Formula/mp3wrap.rb
  Formula/mpack.rb
  Formula/mpck.rb
  Formula/mpdas.rb
  Formula/mpdviz.rb
  Formula/mpegdemux.rb
  Formula/mpg321.rb
  Formula/mpich.rb
  Formula/mpir.rb
  Formula/mplayershell.rb
  Formula/mps-youtube.rb
  Formula/mpw.rb
  Formula/mrboom.rb
  Formula/mrtg.rb
  Formula/mruby.rb
  Formula/mscgen.rb
  Formula/msdl.rb
  Formula/msgpack-tools.rb
  Formula/msitools.rb
  Formula/mysql-connector-c++.rb
  Formula/mysql-connector-c++@1.1.rb
  Formula/mysql-sandbox.rb
  Formula/mytop.rb
Labels: merge

#16522 Merge 2019-10-18 9967308668
  Formula/mdv.rb
  Formula/mdxmini.rb
  Formula/mecab-ko-dic.rb
  Formula/mecab-unidic-extended.rb
  Formula/mediaconch.rb
  Formula/mfoc.rb
  Formula/mfterm.rb
  Formula/mftrace.rb
  Formula/mg.rb
  Formula/mgba.rb
  Formula/mspdebug.rb
  Formula/mtools.rb
  Formula/multitail.rb
  Formula/muparser.rb
  Formula/mupen64plus.rb
  Formula/mvtools.rb
  Formula/mydumper.rb
  Formula/myman.rb
  Formula/mysql++.rb
Labels: merge

#16523 Merge 2019-10-19 aa43ee0bb3
  Formula/acpica.rb
  Formula/ansible.rb
  Formula/azure-cli.rb
  Formula/batik.rb
  Formula/cfr-decompiler.rb
  Formula/devspace.rb
  Formula/dfix.rb
  Formula/dfmt.rb
  Formula/dmd.rb
  Formula/docker-completion.rb
  Formula/docker.rb
  Formula/doctl.rb
  Formula/duplicity.rb
  Formula/dvdauthor.rb
  Formula/dvdbackup.rb
  Formula/futhark.rb
  Formula/ghostscript.rb
  Formula/git-annex.rb
  Formula/go-statik.rb
  Formula/go.rb
  Formula/go@1.12.rb
  Formula/godep.rb
  Formula/lcdf-typetools.rb
  Formula/libdvdnav.rb
  Formula/libdvdread.rb
  Formula/libopenmpt.rb
  Formula/librsync.rb
  Formula/libspectre.rb
  Formula/lsdvd.rb
  Formula/mill.rb
  Formula/plantuml.rb
  Formula/pulumi.rb
  Formula/sbcl.rb
  Formula/ship.rb
  Formula/source-to-image.rb
  Formula/stunnel.rb
  Formula/terraform.rb
  Formula/ttf2eot.rb
Labels: merge

#16545 Merge 2019-10-19 47d932067f
  Formula/appscale-tools.rb
  Formula/buildapp.rb
  Formula/cafeobj.rb
  Formula/charm-tools.rb
  Formula/devspace.rb
  Formula/exploitdb.rb
  Formula/fabric.rb
  Formula/fd.rb
  Formula/flintrock.rb
  Formula/fstrm.rb
  Formula/gatsby-cli.rb
  Formula/geoipupdate.rb
  Formula/git-quick-stats.rb
  Formula/grails.rb
  Formula/hwloc.rb
  Formula/libbitcoin-blockchain.rb
  Formula/libbitcoin-client.rb
  Formula/libbitcoin-explorer.rb
  Formula/libbitcoin-node.rb
  Formula/libbitcoin-server.rb
  Formula/libgdata.rb
  Formula/libgnomecanvasmm.rb
  Formula/magic-wormhole.rb
  Formula/maxima.rb
  Formula/neatvi.rb
  Formula/nspr.rb
  Formula/octant.rb
  Formula/s3ql.rb
  Formula/swagger-codegen.rb
  Formula/swagger-codegen@2.rb
Labels: merge

#16555 Merge 2019-10-19 cc19cac8a8
  Formula/buku.rb
  Formula/calicoctl.rb
  Formula/certbot.rb
  Formula/chamber.rb
  Formula/go-bindata.rb
  Formula/maxwell.rb
  Formula/mitmproxy.rb
  Formula/ooniprobe.rb
  Formula/stormssh.rb
  Formula/unison.rb
  Formula/ykman.rb
Labels: merge

#16563 Merge 2019-10-19 560afd4e62
  Formula/aggregate.rb
  Formula/fetchmail.rb
  Formula/file-formula.rb
  Formula/folly.rb
  Formula/kubernetes-helm.rb
  Formula/libmagic.rb
  Formula/sile.rb
  Formula/tcsh.rb
Labels: merge

#16565 Merge 2019-10-19 27aa773565
  Formula/carthage.rb
  Formula/clojure.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/proteinortho.rb
  Formula/pygtk.rb
  Formula/reposurgeon.rb
  Formula/saxon.rb
  Formula/sdlpop.rb
  Formula/silk.rb
  Formula/ski.rb
  Formula/smali.rb
  Formula/source-highlight.rb
  Formula/stanford-ner.rb
  Formula/ufraw.rb
Labels: merge

#16570 Merge 2019-10-19 bf0fe3f3a4
  Formula/carthage.rb
  Formula/diffuse.rb
  Formula/gwyddion.rb
  Formula/javacc.rb
  Formula/legit.rb
  Formula/nicotine-plus.rb
  Formula/pygtkglext.rb
  Formula/pygtksourceview.rb
  Formula/vte.rb
Labels: merge

#16572 Merge 2019-10-19 343984278e
  Formula/mpg123.rb
  Formula/terminator.rb
  Formula/zim.rb
Labels: merge

#16574 Merge 2019-10-19 88c5b5c151
  Formula/chibi-scheme.rb
  Formula/file-formula.rb
  Formula/goreleaser.rb
  Formula/libmagic.rb
  Formula/ncview.rb
  Formula/orocos-kdl.rb
  Formula/par.rb
  Formula/tcsh.rb
Labels: merge

#16576 Merge 2019-10-20 b2f67e7426
  Formula/aws-cdk.rb
  Formula/cocoapods.rb
  Formula/deno.rb
  Formula/firebase-cli.rb
  Formula/kyma-cli.rb
  Formula/qt.rb
  Formula/supervisor.rb
Labels: merge

#16580 Merge 2019-10-20 9c32e16d69
  Formula/aspell.rb
  Formula/inspectrum.rb
  Formula/pushpin.rb
  Formula/pygtk.rb
  Formula/pyside.rb
  Formula/qcli.rb
  Formula/qjackctl.rb
  Formula/qjson.rb
  Formula/qsoas.rb
  Formula/tor.rb
  Formula/u-boot-tools.rb
  Formula/verilator.rb
  Formula/whois.rb
Labels: merge

#16588 Merge 2019-10-20 89006dff40
  Formula/autogen.rb
  Formula/bettercap.rb
  Formula/caf.rb
  Formula/dhall.rb
  Formula/gnu-complexity.rb
  Formula/guile.rb
  Formula/libtensorflow@1.rb
  Formula/mdk.rb
  Formula/percona-server.rb
  Formula/pulseaudio.rb
  Formula/pylint.rb
  Formula/starship.rb
  Formula/ttyplot.rb
  Formula/util-linux.rb
  Formula/wal2json.rb
  Formula/xpdf.rb
Labels: merge

#16598 Merge 2019-10-21 e6dec9d9e8
  Formula/catch2.rb
  Formula/faas-cli.rb
  Formula/ipmitool.rb
  Formula/jenkins.rb
  Formula/macvim.rb
  Formula/phpstan.rb
Labels: merge

#16601 Merge 2019-10-22 29c7cfb92c
  Formula/bazel.rb
  Formula/buku.rb
  Formula/carthage.rb
  Formula/ccm.rb
  Formula/contentful-cli.rb
  Formula/convox.rb
  Formula/devspace.rb
  Formula/fabric.rb
  Formula/fdroidserver.rb
  Formula/flintrock.rb
  Formula/flow.rb
  Formula/gitfs.rb
  Formula/gitless.rb
  Formula/goreleaser.rb
  Formula/hugo.rb
  Formula/lerna.rb
  Formula/libxmlsec1.rb
  Formula/mdbook.rb
  Formula/mitmproxy.rb
  Formula/pgcli.rb
  Formula/phpstan.rb
  Formula/pylint.rb
  Formula/restview.rb
  Formula/rtmpdump.rb
  Formula/salt.rb
  Formula/scc.rb
  Formula/snapcraft.rb
  Formula/stormssh.rb
  Formula/telegram-cli.rb
  Formula/terraformer.rb
  Formula/varnish.rb
  Formula/wtf.rb
  Formula/zabbix.rb
Labels: merge

#16621 Merge 2019-10-22 80c190fa2d
  Formula/contentful-cli.rb
  Formula/exploitdb.rb
  Formula/frugal.rb
  Formula/glib.rb
  Formula/golang-migrate.rb
  Formula/goreleaser.rb
  Formula/vulkan-headers.rb
Labels: merge

#16627 Merge 2019-10-22 cbfeb13078
  Formula/aws-cdk.rb
  Formula/balena-cli.rb
  Formula/erlang.rb
  Formula/esptool.rb
  Formula/gatsby-cli.rb
  Formula/i2pd.rb
  Formula/netdata.rb
  Formula/now-cli.rb
  Formula/tintin.rb
  Formula/unoconv.rb
  Formula/unrar.rb
  Formula/urh.rb
  Formula/watson.rb
  Formula/xapian.rb
Labels: merge

#16646 Merge 2019-10-24 fd679805d6
  Formula/apache-flink.rb
  Formula/auditbeat.rb
  Formula/bit.rb
  Formula/convox.rb
  Formula/dcos-cli.rb
  Formula/devspace.rb
  Formula/elasticsearch.rb
  Formula/etcd.rb
  Formula/exploitdb.rb
  Formula/gatsby-cli.rb
  Formula/grpc.rb
  Formula/hwloc.rb
  Formula/k3d.rb
  Formula/kubernetes-helm.rb
  Formula/logstash.rb
  Formula/metricbeat.rb
  Formula/netlify-cli.rb
  Formula/ruby-build.rb
  Formula/tcpdump.rb
  Formula/terrahub.rb
  Formula/vim.rb
  Formula/virgil.rb
  Formula/xonsh.rb
Labels: merge

#16661 azure: switch to homebrew image
  azure-pipelines.yml
Labels: do-not-merge

#16663 Merge 2019-10-24 507b67bec8
  Formula/aamath.rb
  Formula/aiccu.rb
  Formula/aldo.rb
  Formula/aview.rb
  Formula/aws-okta.rb
  Formula/cd-discid.rb
  Formula/cdargs.rb
  Formula/cmockery.rb
  Formula/colordiff.rb
  Formula/colorsvn.rb
  Formula/cpprestsdk.rb
  Formula/ctags.rb
  Formula/dirac.rb
  Formula/dmg2img.rb
  Formula/einstein.rb
  Formula/ekg2.rb
  Formula/exploitdb.rb
  Formula/flow.rb
  Formula/gdmap.rb
  Formula/gmtl.rb
  Formula/gobby.rb
  Formula/gocr.rb
  Formula/gtksourceview.rb
  Formula/helmfile.rb
  Formula/hspell.rb
  Formula/httperf.rb
  Formula/jhead.rb
  Formula/libhid.rb
  Formula/libnids.rb
  Formula/librsvg.rb
  Formula/mkvdts2ac3.rb
  Formula/mpg321.rb
  Formula/ori.rb
  Formula/osquery.rb
  Formula/pygobject.rb
  Formula/pygtk.rb
  Formula/renameutils.rb
  Formula/rpcgen.rb
  Formula/rrdtool.rb
  Formula/rtmpdump.rb
  Formula/rxvt-unicode.rb
  Formula/serverless.rb
  Formula/spatialite-gui.rb
  Formula/srecord.rb
  Formula/subversion@1.8.rb
  Formula/syncthing.rb
  Formula/telegraf.rb
  Formula/teleport.rb
  Formula/terminator.rb
  Formula/tiny-fugue.rb
  Formula/udns.rb
  Formula/upscaledb.rb
  Formula/vavrdiasm.rb
  Formula/vip.rb
  Formula/vsftpd.rb
  Formula/wmctrl.rb
  Formula/wput.rb
  Formula/xsd.rb
  Formula/yconalyzer.rb
Labels: merge

#16669 Merge 2019-10-25 24edb0edb6
  Formula/anime-downloader.rb
  Formula/catch2.rb
  Formula/dvc.rb
  Formula/exercism.rb
  Formula/gleam.rb
  Formula/glooctl.rb
  Formula/gtkmm3.rb
  Formula/jfrog-cli-go.rb
  Formula/netlify-cli.rb
  Formula/notmuch.rb
  Formula/php.rb
  Formula/pulumi.rb
  Formula/theharvester.rb
  Formula/tundra.rb
  Formula/twine-pypi.rb
  Formula/two-lame.rb
Labels: merge

#16679 Merge 2019-10-25 ea623d4914
  Formula/abcmidi.rb
  Formula/ansible@1.9.rb
  Formula/ansible@2.0.rb
  Formula/dvc.rb
  Formula/dxpy.rb
  Formula/python@2.rb
  Formula/swiftlint.rb
Labels: merge

#16686 Merge 2019-10-25 e63f1c706a
  Formula/aws-sdk-cpp.rb
  Formula/jetty.rb
  Formula/neko.rb
  Formula/pango.rb
  Formula/php@7.1.rb
  Formula/php@7.2.rb
  Formula/teleport.rb
Labels: merge

#16692 Merge 2019-10-25 624d331f01
  Formula/arp-scan.rb
  Formula/calcurse.rb
  Formula/ccache.rb
  Formula/certbot.rb
  Formula/check.rb
  Formula/checkbashisms.rb
  Formula/confluent-platform.rb
  Formula/cutter.rb
  Formula/exploitdb.rb
Labels: merge

#16698 Merge 2019-10-26 96bf6a93dd
  Formula/cash-cli.rb
  Formula/dhall-bash.rb
  Formula/dhall-json.rb
  Formula/diffoscope.rb
  Formula/dovecot.rb
  Formula/eye-d3.rb
  Formula/fdk-aac.rb
  Formula/gitmoji.rb
  Formula/helmfile.rb
  Formula/now-cli.rb
  Formula/omega.rb
  Formula/rancid.rb
  Formula/salt.rb
  Formula/stella.rb
  Formula/stress-ng.rb
  Formula/swaks.rb
  Formula/wireshark.rb
Labels: merge

#16710 Merge 2019-10-26 616d008adc
  Formula/eslint.rb
  Formula/git-annex.rb
  Formula/glooctl.rb
  Formula/rancher-cli.rb
  Formula/skaffold.rb
  Formula/terragrunt.rb
Labels: merge

#16716 Merge 2019-10-26 b40815d11d
  Formula/erlang@21.rb
  Formula/exploitdb.rb
  Formula/node-build.rb
  Formula/rclone.rb
Labels: merge

#16720 Merge 2019-10-26 ffbede34d9
  Formula/dcraw.rb
  Formula/nvm.rb
Labels: merge

#16726 Merge 2019-10-27 d0cdb6cea7
  Formula/toast.rb
Labels: merge

#16728 Merge 2019-10-27 29e4cdfdac
  Formula/artifactory.rb
  Formula/awsume.rb
  Formula/govc.rb
  Formula/haxe.rb
  Formula/mdbook.rb
  Formula/minikube.rb
  Formula/navi.rb
  Formula/ngt.rb
  Formula/pnpm.rb
  Formula/pre-commit.rb
  Formula/pygobject3.rb
  Formula/topgrade.rb
Labels: merge

#16739 Merge 2019-10-27 f4c5959b74
  Formula/cheat.rb
Labels: merge

#16741 Merge 2019-10-28 67b9423e72
  Formula/bettercap.rb
  Formula/bit.rb
  Formula/checkstyle.rb
  Formula/dcos-cli.rb
  Formula/hfstospell.rb
  Formula/istioctl.rb
  Formula/kafka.rb
  Formula/libvoikko.rb
  Formula/orc-tools.rb
  Formula/sphinx-doc.rb
  Formula/xcodegen.rb
Labels: merge

#16751 Merge 2019-10-28 649e46d1f3
  Formula/arduino-cli.rb
  Formula/csound.rb
  Formula/open-babel.rb
Labels: merge

#16756 Merge 2019-10-29 287eaef14d
  Formula/ammonite-repl.rb
  Formula/angular-cli.rb
  Formula/atlantis.rb
  Formula/borgmatic.rb
  Formula/dnscrypt-proxy.rb
  Formula/docfx.rb
  Formula/doctl.rb
  Formula/exploitdb.rb
  Formula/fn.rb
  Formula/frugal.rb
  Formula/glooctl.rb
  Formula/jenkins.rb
  Formula/kubeprod.rb
  Formula/macvim.rb
  Formula/mypy.rb
  Formula/nim.rb
  Formula/phpunit.rb
  Formula/quickjs.rb
  Formula/rke.rb
  Formula/swiftformat.rb
  Formula/watchexec.rb
Labels: merge

#16772 Merge 2019-10-29 e7150614f2
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/config.yml
  Formula/aws-cdk.rb
  Formula/conan.rb
  Formula/firebase-cli.rb
  Formula/gatsby-cli.rb
  Formula/git-quick-stats.rb
  Formula/gitlab-runner.rb
  Formula/go.rb
  Formula/helmfile.rb
  Formula/jenkins-lts.rb
  Formula/kubebuilder.rb
  Formula/paket.rb
  Formula/pre-commit.rb
  Formula/skopeo.rb
  Formula/suricata.rb
  Formula/tidyp.rb
  Formula/traefik.rb
  Formula/traefik@1.rb
Labels: merge

#16782 Merge 2019-10-30 fd79755e41
  Formula/libphonenumber.rb
  Formula/mvnvm.rb
  Formula/netlify-cli.rb
  Formula/sfk.rb
  Formula/zrepl.rb
Labels: merge

#16784 Merge 2019-10-30 f8309b877d
  Formula/llvm.rb
Labels: merge

#16786 Merge 2019-10-30 179da25cce
  Formula/ammonite-repl.rb
  Formula/arangodb.rb
  Formula/atlassian-cli.rb
  Formula/bazelisk.rb
  Formula/cli53.rb
  Formula/deno.rb
  Formula/erlang.rb
  Formula/gatsby-cli.rb
  Formula/geckodriver.rb
  Formula/grin-wallet.rb
  Formula/grin.rb
  Formula/helmsman.rb
  Formula/influxdb.rb
  Formula/kubernetes-helm.rb
  Formula/libxml2.rb
  Formula/mdbook.rb
  Formula/minikube.rb
  Formula/mm-common.rb
  Formula/onefetch.rb
  Formula/osquery.rb
  Formula/prestodb.rb
  Formula/prestosql.rb
  Formula/puzzles.rb
  Formula/python-yq.rb
  Formula/redpen.rb
  Formula/rocksdb.rb
  Formula/ruby.rb
  Formula/serd.rb
  Formula/simgrid.rb
  Formula/stubby.rb
  Formula/svgo.rb
  Formula/sysbench.rb
  Formula/tdkjs.rb
  Formula/tfenv.rb
  Formula/urweb.rb
  Formula/xorriso.rb
  Formula/youtube-dl.rb
  Formula/zita-convolver.rb
  formula_renames.json
Labels: merge

#16738 azure: report status back if build failed
  azure-pipelines.yml
Labels: do-not-merge

#16807 Merge 2019-10-31 407e1d02eb
  Formula/angular-cli.rb
  Formula/atlantis.rb
  Formula/blockhash.rb
  Formula/chafa.rb
  Formula/cheat.rb
  Formula/csvq.rb
  Formula/dmtx-utils.rb
  Formula/dnscrypt-proxy.rb
  Formula/exploitdb.rb
  Formula/flow.rb
  Formula/gitlab-runner.rb
  Formula/goreleaser.rb
  Formula/helmfile.rb
  Formula/imagemagick.rb
  Formula/kubeseal.rb
  Formula/kustomize.rb
  Formula/llvm@7.rb
  Formula/macvim.rb
  Formula/mgba.rb
  Formula/mypy.rb
  Formula/nbdime.rb
  Formula/opa.rb
  Formula/pqiv.rb
  Formula/py2cairo.rb
  Formula/py3cairo.rb
  Formula/rom-tools.rb
  Formula/rrdtool.rb
  Formula/ruby-build.rb
  Formula/shairport-sync.rb
  Formula/skopeo.rb
  Formula/slowhttptest.rb
  Formula/spatialindex.rb
  Formula/stgit.rb
  Formula/svgo.rb
  Formula/vapoursynth-imwri.rb
  Formula/vips.rb
  Formula/xtensor.rb
  Formula/zabbix.rb
  Formula/zbar.rb
  Formula/zsh-history-substring-search.rb
Labels: merge

#16838 Merge 2019-10-31 861af33a1a
  Aliases/solr@8.3
  Formula/exploitdb.rb
  Formula/glooctl.rb
  Formula/shadowsocks-libev.rb
  Formula/solr.rb
  Formula/zola.rb
Labels: merge
