Repository Homebrew/linuxbrew-core, pull requests merged in 2019-06, with the labels that each got.

#13422 Merge 2019-06-02 dfe1e847f6
  Formula/bedops.rb
  Formula/charm.rb
  Formula/cppad.rb
  Formula/embree.rb
  Formula/hexyl.rb
  Formula/mgba.rb
  Formula/nave.rb
  Formula/node-build.rb
  Formula/nss.rb
  Formula/pgformatter.rb
  Formula/phoronix-test-suite.rb
  Formula/sync_gateway.rb
  Formula/traefik.rb
  Formula/whirr.rb
  Formula/xmake.rb
Labels: merge

#13423 Merge 2019-06-02 3d4ffdc472
  Aliases/perl@5.30
  Formula/astrometry-net.rb
  Formula/babl.rb
  Formula/cc65.rb
  Formula/ccextractor.rb
  Formula/dcm2niix.rb
  Formula/dscanner.rb
  Formula/erlang@21.rb
  Formula/flow.rb
  Formula/h3.rb
  Formula/ipfs.rb
  Formula/ispc.rb
  Formula/jsonschema2pojo.rb
  Formula/khal.rb
  Formula/mlt.rb
  Formula/mongo-c-driver.rb
  Formula/openvdb.rb
  Formula/perl.rb
  Formula/pgcli.rb
  Formula/rhino.rb
  Formula/sk.rb
  Formula/subversion.rb
  Formula/vim.rb
  Formula/vim@7.4.rb
  Formula/vulkan-headers.rb
  Formula/websocketd.rb
  Formula/weechat.rb
  Formula/wp-cli-completion.rb
Labels: merge

#13424 Merge 2019-06-02 84922fc6c4
  Formula/bear.rb
  Formula/bowtie2.rb
  Formula/ccls.rb
  Formula/cocoapods.rb
  Formula/digdag.rb
  Formula/flintrock.rb
  Formula/freeradius-server.rb
  Formula/ghq.rb
  Formula/git-ftp.rb
  Formula/git-review.rb
  Formula/google-authenticator-libpam.rb
  Formula/hapi-fhir-cli.rb
  Formula/heatshrink.rb
  Formula/lizard.rb
  Formula/makensis.rb
  Formula/mono-libgdiplus.rb
  Formula/mpop.rb
  Formula/pdfpc.rb
  Formula/pgbadger.rb
  Formula/quazip.rb
  Formula/rebar3.rb
  Formula/scalariform.rb
  Formula/testssl.rb
  Formula/triton.rb
  Formula/wxmaxima.rb
Labels: merge

#13425 Merge 2019-06-02 22e19bd04d
  Formula/angular-cli.rb
  Formula/cfn-lint.rb
  Formula/conan.rb
  Formula/doctl.rb
  Formula/exploitdb.rb
  Formula/folly.rb
  Formula/gomplate.rb
  Formula/grpc.rb
  Formula/libagg.rb
  Formula/libcapn.rb
  Formula/libpulsar.rb
  Formula/libsass.rb
  Formula/libsodium.rb
  Formula/lighttpd.rb
  Formula/linkerd.rb
  Formula/micropython.rb
  Formula/nats-streaming-server.rb
  Formula/php.rb
  Formula/php@7.1.rb
  Formula/php@7.2.rb
  Formula/pkg-config.rb
  Formula/raylib.rb
  Formula/webkit2png.rb
  Formula/wxpython.rb
Labels: merge

#13468 gcc: restore `cellar :any`
  Formula/gcc@6.rb
  Formula/gcc@9.rb
Labels: bottle, bug

#13469 Merge 2019-06-03 a8c51eb8dd
  Formula/atomist-cli.rb
  Formula/basex.rb
  Formula/cmake.rb
  Formula/csvq.rb
  Formula/faudio.rb
  Formula/harfbuzz.rb
  Formula/liberasurecode.rb
  Formula/lizard.rb
  Formula/lwtools.rb
  Formula/mafft.rb
  Formula/mailutils.rb
  Formula/minio.rb
  Formula/openapi-generator.rb
  Formula/pgformatter.rb
  Formula/plplot.rb
  Formula/ponyc.rb
  Formula/re2.rb
  Formula/rebar3.rb
  Formula/saxon.rb
  Formula/scalariform.rb
  Formula/sqlcipher.rb
  Formula/sqlmap.rb
  Formula/webdis.rb
  Formula/wireguard-tools.rb
  Formula/xmrig.rb
Labels: merge

#13470 Merge 2019-06-03 3d75dfbd7e
  Formula/bind.rb
  Formula/bit.rb
  Formula/cointop.rb
  Formula/coq.rb
  Formula/fio.rb
  Formula/gcsfuse.rb
  Formula/git-secret.rb
  Formula/groovy.rb
  Formula/groovysdk.rb
  Formula/just.rb
  Formula/kafka.rb
  Formula/math-comp.rb
  Formula/php.rb
  Formula/php@7.1.rb
  Formula/php@7.2.rb
  Formula/polyglot.rb
  Formula/sassc.rb
  Formula/sec.rb
  Formula/swiftlint.rb
  Formula/syncthing.rb
  Formula/vim.rb
Labels: merge

#13490 Merge 2019-06-04 1770ed7ccf
  Formula/ask-cli.rb
  Formula/atlantis.rb
  Formula/autorest.rb
  Formula/awscli.rb
  Formula/cromwell.rb
  Formula/django-completion.rb
  Formula/dnscrypt-proxy.rb
  Formula/erlang.rb
  Formula/firebase-cli.rb
  Formula/folly.rb
  Formula/git-town.rb
  Formula/gmic.rb
  Formula/gnumeric.rb
  Formula/goffice.rb
  Formula/grpc.rb
  Formula/isync.rb
  Formula/joplin.rb
  Formula/jsonnet.rb
  Formula/minio.rb
  Formula/mksh.rb
  Formula/nativefier.rb
  Formula/nim.rb
  Formula/payara.rb
  Formula/plantuml.rb
  Formula/quicktype.rb
  Formula/sbcl.rb
  Formula/teleport.rb
  Formula/yubico-piv-tool.rb
  Formula/z3.rb
Labels: merge

#13491 Merge 2019-06-04 9094019d31
  Formula/cjson.rb
  Formula/convox.rb
  Formula/fontforge.rb
  Formula/jdupes.rb
  Formula/juju.rb
  Formula/kubernetes-service-catalog-client.rb
  Formula/lasi.rb
  Formula/mftrace.rb
  Formula/mk-configure.rb
  Formula/pam-u2f.rb
  Formula/sfcgal.rb
  Formula/solr@7.7.rb
Labels: merge

#13370 swimat: Build a bottle for Linuxbrew
  Formula/swimat.rb
Labels: bottle, good

#13511 Merge 2019-06-05 2d41f167b3
  Formula/conan.rb
  Formula/csound.rb
  Formula/exploitdb.rb
  Formula/gdcm.rb
  Formula/golang-migrate.rb
  Formula/ipopt.rb
  Formula/itk.rb
  Formula/libextractor.rb
  Formula/libtiff.rb
  Formula/libvirt.rb
  Formula/micronaut.rb
  Formula/node.rb
  Formula/node_exporter.rb
  Formula/paket.rb
  Formula/pkcrack.rb
  Formula/pulumi.rb
  Formula/tcsh.rb
  Formula/terraform.rb
  Formula/terragrunt.rb
  Formula/terrahub.rb
  Formula/topgrade.rb
  Formula/u-boot-tools.rb
  Formula/virgil.rb
  Formula/xonsh.rb
Labels: merge

#13523 Merge 2019-06-06 3157dd0ad8
  Aliases/v8@7.5
  Formula/azure-cli.rb
  Formula/duck.rb
  Formula/fselect.rb
  Formula/git-remote-hg.rb
  Formula/grafana.rb
  Formula/helmfile.rb
  Formula/maxima.rb
  Formula/molecule.rb
  Formula/nats-streaming-server.rb
  Formula/proteinortho.rb
  Formula/rke.rb
  Formula/sslsplit.rb
  Formula/tile38.rb
  Formula/v8.rb
  Formula/vala.rb
  Formula/zlog.rb
Labels: merge

#13532 Merge 2019-06-06 7caaf87854
  Formula/curl.rb
Labels: merge

#13535 Merge 2019-06-08 015703c215
  Formula/akamai.rb
  Formula/bazel.rb
  Formula/clojure-lsp.rb
  Formula/crystal.rb
  Formula/erlang@21.rb
  Formula/fn.rb
  Formula/gitleaks.rb
  Formula/glooctl.rb
  Formula/gnunet.rb
  Formula/inlets.rb
  Formula/istioctl.rb
  Formula/joplin.rb
  Formula/jsonnet.rb
  Formula/kubernetes-helm.rb
  Formula/latex2html.rb
  Formula/mesa.rb
  Formula/monetdb.rb
  Formula/nats-streaming-server.rb
  Formula/pre-commit.rb
  Formula/rke.rb
  Formula/topgrade.rb
  Formula/tox.rb
Labels: merge

#13536 Merge 2019-06-08 3f992b24ba
  Formula/angular-cli.rb
  Formula/bit.rb
  Formula/bitwarden-cli.rb
  Formula/certbot.rb
  Formula/clojure.rb
  Formula/curl-openssl.rb
  Formula/cython.rb
  Formula/dhall.rb
  Formula/duo_unix.rb
  Formula/exploitdb.rb
  Formula/gengetopt.rb
  Formula/gnu-units.rb
  Formula/imagemagick.rb
  Formula/kubernetes-cli.rb
  Formula/libical.rb
  Formula/mercurial.rb
  Formula/minio-mc.rb
  Formula/pod2man.rb
  Formula/prettier.rb
  Formula/pulumi.rb
  Formula/sphinx-doc.rb
  Formula/weechat.rb
  Formula/wtf.rb
Labels: merge

#13562 Merge 2019-06-09 4db761d43b
  Formula/ansible.rb
  Formula/docker-machine-driver-vmware.rb
  Formula/dust.rb
  Formula/grpc.rb
  Formula/helmfile.rb
  Formula/hey.rb
  Formula/libosinfo.rb
  Formula/linkerd.rb
  Formula/lmod.rb
  Formula/nats-server.rb
  Formula/newman.rb
  Formula/nim.rb
  Formula/procs.rb
  Formula/pstoedit.rb
  Formula/scdoc.rb
  Formula/skaffold.rb
  Formula/termshark.rb
  Formula/terraformer.rb
  Formula/terrahub.rb
  Formula/thefuck.rb
  Formula/vault.rb
  Formula/yamllint.rb
  Formula/ykman.rb
  formula_renames.json
Labels: merge

#13563 Merge 2019-06-09 7a6f1aaaf0
  Formula/arangodb.rb
  Formula/cryfs.rb
  Formula/fuseki.rb
  Formula/geoipupdate.rb
  Formula/git.rb
  Formula/gitlab-runner.rb
  Formula/gpsbabel.rb
  Formula/hyperfine.rb
  Formula/inlets.rb
  Formula/mariadb-connector-c.rb
  Formula/php-cs-fixer.rb
  Formula/prettier.rb
  Formula/prototool.rb
  Formula/shadowsocks-libev.rb
  Formula/sslsplit.rb
  Formula/tfenv.rb
  Formula/vim.rb
  Formula/wimlib.rb
  Formula/youtube-dl.rb
  Formula/zim.rb
Labels: merge

#13583 Merge 2019-06-10 80745d7975
  Aliases/boost-python@1.70
  Aliases/boost@1.70
  Formula/avro-cpp.rb
  Formula/azure-storage-cpp.rb
  Formula/bitcoin.rb
  Formula/boost-bcp.rb
  Formula/boost-build.rb
  Formula/boost-mpi.rb
  Formula/boost-python.rb
  Formula/boost-python3.rb
  Formula/boost.rb
  Formula/caffe.rb
  Formula/cgal.rb
  Formula/cpprestsdk.rb
  Formula/cucumber-cpp.rb
  Formula/folly.rb
  Formula/gnuradio.rb
  Formula/graph-tool.rb
  Formula/i2pd.rb
  Formula/ledger.rb
  Formula/lgogdownloader.rb
  Formula/libbitcoin-blockchain.rb
  Formula/libbitcoin-client.rb
  Formula/libbitcoin-database.rb
  Formula/libbitcoin-explorer.rb
  Formula/libbitcoin-network.rb
  Formula/libbitcoin-node.rb
  Formula/libbitcoin-protocol.rb
  Formula/libbitcoin-server.rb
  Formula/libbitcoin.rb
  Formula/libpulsar.rb
  Formula/libswiften.rb
  Formula/libtorrent-rasterbar.rb
  Formula/metaproxy.rb
  Formula/mkvtoolnix.rb
  Formula/monero.rb
  Formula/ncmpcpp.rb
  Formula/openimageio.rb
  Formula/osquery.rb
  Formula/osrm-backend.rb
  Formula/pcl.rb
  Formula/pgrouting.rb
  Formula/sfcgal.rb
  Formula/source-highlight.rb
  Formula/uhd.rb
  Formula/upscaledb.rb
  Formula/wesnoth.rb
  Formula/widelands.rb
Labels: merge

#13597 Merge 2019-06-10 b0ff54bed6
  Formula/anyenv.rb
  Formula/aravis.rb
  Formula/buildifier.rb
  Formula/cointop.rb
  Formula/deno.rb
  Formula/dependency-check.rb
  Formula/drone-cli.rb
  Formula/futhark.rb
  Formula/glib-networking.rb
  Formula/goofys.rb
  Formula/goreleaser.rb
  Formula/helmfile.rb
  Formula/hlint.rb
  Formula/icecream.rb
  Formula/jenkins.rb
  Formula/libtorrent-rasterbar.rb
  Formula/mame.rb
  Formula/mpich.rb
  Formula/node-build.rb
  Formula/phpmyadmin.rb
  Formula/sslsplit.rb
  Formula/terraform.rb
  Formula/terragrunt.rb
Labels: merge

#13609 Merge 2019-06-12 a604f09957
  Aliases/scala@2.13
  Formula/armadillo.rb
  Formula/atlantis.rb
  Formula/bitrise.rb
  Formula/cfn-lint.rb
  Formula/citus.rb
  Formula/composer.rb
  Formula/encfs.rb
  Formula/grakn.rb
  Formula/helmfile.rb
  Formula/imagemagick@6.rb
  Formula/jenkins-lts.rb
  Formula/librealsense.rb
  Formula/macvim.rb
  Formula/mesa.rb
  Formula/openssl.rb
  Formula/pandoc.rb
  Formula/scala.rb
  Formula/scala@2.12.rb
  Formula/serverless.rb
  Formula/sphinx-doc.rb
  Formula/terragrunt.rb
  Formula/tokei.rb
  Formula/tomcat.rb
  Formula/you-get.rb
  cmd/brew-postgresql-upgrade-database.rb
Labels: merge

#13623 Merge 2019-06-13 eba05faa4f
  Formula/aws-sdk-cpp.rb
  Formula/calicoctl.rb
  Formula/chakra.rb
  Formula/doctl.rb
  Formula/envconsul.rb
  Formula/glib.rb
  Formula/gmic.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/graph-tool.rb
  Formula/jdupes.rb
  Formula/jhipster.rb
  Formula/libsigc++.rb
  Formula/lmod.rb
  Formula/minio-mc.rb
  Formula/nomad.rb
  Formula/paket.rb
  Formula/phpunit.rb
  Formula/pulumi.rb
  Formula/ship.rb
  Formula/sops.rb
  Formula/telegraf.rb
  Formula/terraform.rb
  Formula/webpack.rb
  Formula/wildfly-as.rb
Labels: merge

#13638 Merge 2019-06-14 ee75d751c8
  Aliases/swig@4
  Formula/braid.rb
  Formula/certbot.rb
  Formula/exiftool.rb
  Formula/folly.rb
  Formula/gibo.rb
  Formula/glooctl.rb
  Formula/gst-plugins-good.rb
  Formula/hlint.rb
  Formula/imagemagick.rb
  Formula/joplin.rb
  Formula/knot.rb
  Formula/minio.rb
  Formula/opa.rb
  Formula/openimageio.rb
  Formula/procs.rb
  Formula/pyenv.rb
  Formula/rbspy.rb
  Formula/scalariform.rb
  Formula/scrcpy.rb
  Formula/subversion.rb
  Formula/swig@3.rb
  Formula/vultr.rb
  Formula/whois.rb
  Formula/yelp-tools.rb
Labels: merge

#13650 Merge 2019-06-15 255b8e25d5
  Formula/ammonite-repl.rb
  Formula/angular-cli.rb
  Formula/circleci.rb
  Formula/cocoapods.rb
  Formula/druid.rb
  Formula/firebase-cli.rb
  Formula/flow.rb
  Formula/fluxctl.rb
  Formula/google-benchmark.rb
  Formula/jfrog-cli-go.rb
  Formula/libev.rb
  Formula/lxc.rb
  Formula/meson.rb
  Formula/mighttpd2.rb
  Formula/opencolorio.rb
  Formula/presto.rb
  Formula/pybind11.rb
  Formula/rakudo-star.rb
  Formula/rbspy.rb
  Formula/scons.rb
  Formula/ship.rb
  Formula/swi-prolog.rb
  Formula/terragrunt.rb
  Formula/topgrade.rb
  Formula/wtf.rb
Labels: merge

#13651 Merge 2019-06-15 f2f82ede91
  Formula/helmfile.rb
  Formula/istioctl.rb
  Formula/node.rb
  Formula/typescript.rb
  Formula/yarn.rb
Labels: merge

#13669 Merge 2019-06-16 74e8d45853
  Formula/python@2.rb
Labels: merge

#13670 Merge 2019-06-16 df2a382bc9
  Formula/conan.rb
  Formula/dep.rb
  Formula/goreleaser.rb
  Formula/hub.rb
  Formula/kakoune.rb
  Formula/openfortivpn.rb
  Formula/ruby-build.rb
  Formula/yle-dl.rb
Labels: merge

#13677 Merge 2019-06-16 74503a3f21
  Formula/braid.rb
  Formula/ghi.rb
  Formula/gitlab-gem.rb
  Formula/haste-client.rb
  Formula/kontena.rb
  Formula/mikutter.rb
  Formula/odt2txt.rb
  Formula/scrcpy.rb
  Formula/terraform_landscape.rb
  Formula/terraforming.rb
  Formula/travis.rb
  Formula/um.rb
  cmd/brew-aspell-dictionaries.rb
Labels: merge, needs response

#13678 Merge 2019-06-16 ebe417a81c
  Formula/artifactory.rb
  Formula/deno.rb
  Formula/gobject-introspection.rb
  Formula/gst-validate.rb
  Formula/libnids.rb
  Formula/mill.rb
  Formula/minio.rb
  Formula/mutt.rb
  Formula/r.rb
  Formula/rclone.rb
  Formula/skopeo.rb
Labels: merge

#12940 crosstool-ng: Build a bottle for Linuxbrew
  Formula/crosstool-ng.rb
Labels: bottle, build-error, dependency

#13829 Merge 2019-06-22 f195d58491
  Formula/app-engine-python.rb
  Formula/awscli.rb
  Formula/catch2.rb
  Formula/chrome-export.rb
  Formula/cockroach.rb
  Formula/commandbox.rb
  Formula/convox.rb
  Formula/doctl.rb
  Formula/erlang.rb
  Formula/exploitdb.rb
  Formula/git-cola.rb
  Formula/helmfile.rb
  Formula/hydra.rb
  Formula/hyperkit.rb
  Formula/i2pd.rb
  Formula/imageoptim-cli.rb
  Formula/jfrog-cli-go.rb
  Formula/libfabric.rb
  Formula/mariadb.rb
  Formula/mysql@5.7.rb
  Formula/pushpin.rb
  Formula/schismtracker.rb
  Formula/sd.rb
  Formula/teleport.rb
  Formula/terragrunt.rb
Labels: merge

#13840 Merge 2019-06-22 44a2116327
  Formula/audacious.rb
  Formula/azure-cli.rb
  Formula/babl.rb
  Formula/cairo.rb
  Formula/erlang.rb
  Formula/gabedit.rb
  Formula/gnunet.rb
  Formula/grafana.rb
  Formula/gst-plugins-good.rb
  Formula/jenkins.rb
  Formula/libgda.rb
  Formula/libhttpseverywhere.rb
  Formula/logtalk.rb
  Formula/mariadb@10.2.rb
  Formula/mikutter.rb
  Formula/monero.rb
  Formula/mosquitto.rb
  Formula/nghttp2.rb
  Formula/phpunit.rb
  Formula/pypy3.rb
  Formula/qemu.rb
  Formula/rpm.rb
  Formula/sonobuoy.rb
  Formula/topgrade.rb
  Formula/unbound.rb
  Formula/vice.rb
  Formula/viewvc.rb
Labels: merge

#13872 Merge 2019-06-23 bc08275181
  Formula/chicken.rb
  Formula/chrome-export.rb
  Formula/docfx.rb
  Formula/erlang@20.rb
  Formula/exploitdb.rb
  Formula/folly.rb
  Formula/fonttools.rb
  Formula/glooctl.rb
  Formula/grakn.rb
  Formula/gst-plugins-good.rb
  Formula/gtk+3.rb
  Formula/harfbuzz.rb
  Formula/helmfile.rb
  Formula/kapacitor.rb
  Formula/maxwell.rb
  Formula/mill.rb
  Formula/nano.rb
  Formula/prototool.rb
  Formula/sd.rb
  Formula/stunnel.rb
  Formula/terraformer.rb
  Formula/topgrade.rb
  Formula/vala.rb
  Formula/vfuse.rb
  Formula/vim.rb
Labels: merge

#13873 Merge 2019-06-23 e03b83695f
  Formula/balena-cli.rb
  Formula/catch2.rb
  Formula/dosbox-x.rb
  Formula/fluid-synth.rb
  Formula/fn.rb
  Formula/fonttools.rb
  Formula/istioctl.rb
  Formula/jnettop.rb
  Formula/kallisto.rb
  Formula/kustomize.rb
  Formula/libphonenumber.rb
  Formula/mdbook.rb
  Formula/newman.rb
  Formula/parallel.rb
  Formula/phpunit.rb
  Formula/procs.rb
  Formula/pwntools.rb
  Formula/python.rb
  Formula/python@2.rb
  Formula/rtags.rb
  Formula/sipp.rb
  Formula/sleepwatcher.rb
  Formula/sphinx-doc.rb
  Formula/task-spooler.rb
  Formula/virgil.rb
  Formula/vulkan-headers.rb
Labels: merge

#13890 Merge 2019-06-25 778a60b852
  .github/issue-close-app.yml
  Formula/cfn-lint.rb
  Formula/clozure-cl.rb
  Formula/ejdb.rb
  Formula/exploitdb.rb
  Formula/ghostscript.rb
  Formula/gmic.rb
  Formula/go.rb
  Formula/go@1.10.rb
  Formula/go@1.11.rb
  Formula/go@1.9.rb
  Formula/gromacs.rb
  Formula/juju.rb
  Formula/kotlin.rb
  Formula/kubernetes-cli.rb
  Formula/libspectre.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/neovim.rb
  Formula/openapi-generator.rb
  Formula/pc6001vx.rb
  Formula/pqiv.rb
  Formula/sn0int.rb
  Formula/sshtrix.rb
  Formula/terrahub.rb
  Formula/xmake.rb
  Formula/xtensor.rb
Labels: merge

#13893 Merge 2019-06-25 7ae18db209
  Aliases/guile@2.2
  Aliases/varnish@6
  Formula/annie.rb
  Formula/ansible.rb
  Formula/antibody.rb
  Formula/bettercap.rb
  Formula/contentful-cli.rb
  Formula/cxxopts.rb
  Formula/glooctl.rb
  Formula/guile@2.0.rb
  Formula/h3.rb
  Formula/hadolint.rb
  Formula/jhipster.rb
  Formula/k3d.rb
  Formula/k6.rb
  Formula/libmpdclient.rb
  Formula/mariadb.rb
  Formula/meson.rb
  Formula/minio.rb
  Formula/mkvtoolnix.rb
  Formula/mps-youtube.rb
  Formula/postgrest.rb
  Formula/terragrunt.rb
  Formula/varnish@4.rb
  Formula/yapf.rb
  Formula/youtube-dl.rb
Labels: merge

#13940 Merge 2019-06-26 f00e29af88
  Formula/asciidoctorj.rb
  Formula/checkstyle.rb
  Formula/devspace.rb
  Formula/dsd.rb
  Formula/eslint.rb
  Formula/exploitdb.rb
  Formula/gobuster.rb
  Formula/helmsman.rb
  Formula/irrlicht.rb
  Formula/irssi.rb
  Formula/kim-api.rb
  Formula/lammps.rb
  Formula/libre.rb
  Formula/librem.rb
  Formula/luarocks.rb
  Formula/openkim-models.rb
  Formula/osquery.rb
  Formula/pinboard-notes-backup.rb
  Formula/rocksdb.rb
  Formula/sk.rb
  Formula/teleconsole.rb
  Formula/tmux-xpanes.rb
  Formula/zola.rb
Labels: merge

#13948 Merge 2019-06-26 65f94bb607
  Formula/dartsim.rb
  Formula/enchant.rb
  Formula/fluid-synth.rb
  Formula/git-flow-avh.rb
  Formula/gitlab-runner.rb
  Formula/iperf3.rb
  Formula/jenkins.rb
  Formula/jhipster.rb
  Formula/libgit2.rb
  Formula/libpqxx.rb
  Formula/librdkafka.rb
  Formula/libsass.rb
  Formula/meson.rb
  Formula/openh264.rb
  Formula/pulumi.rb
  Formula/py2cairo.rb
  Formula/pygobject3.rb
  Formula/rdesktop.rb
  Formula/roswell.rb
  Formula/rtv.rb
  Formula/sassc.rb
  Formula/swiftformat.rb
  Formula/tbb.rb
  Formula/tfenv.rb
  Formula/winetricks.rb
  Formula/zimg.rb
  Formula/zsh-autosuggestions.rb
Labels: merge

#13949 Merge 2019-06-26 7b00b65e4f
  Formula/ack.rb
  Formula/angular-cli.rb
  Formula/autorest.rb
  Formula/aws-sdk-cpp.rb
  Formula/cql.rb
  Formula/dartsim.rb
  Formula/docfx.rb
  Formula/docker-compose-completion.rb
  Formula/docker-compose.rb
  Formula/elixir.rb
  Formula/erlang@21.rb
  Formula/exploitdb.rb
  Formula/faas-cli.rb
  Formula/flow.rb
  Formula/git-fresh.rb
  Formula/go.rb
  Formula/go@1.11.rb
  Formula/gpgme.rb
  Formula/helmfile.rb
  Formula/lazygit.rb
  Formula/mongoose.rb
  Formula/ocaml-num.rb
  Formula/paket.rb
  Formula/sonobuoy.rb
  Formula/verilator.rb
  Formula/vowpal-wabbit.rb
  Formula/webtorrent-cli.rb
  Formula/zsh-autosuggestions.rb
Labels: merge

#13963 Merge 2019-06-29 e00e13fb11
  .github/issue-close-app.yml
  Formula/anime-downloader.rb
  Formula/contentful-cli.rb
  Formula/corectl.rb
  Formula/deno.rb
  Formula/dnstwist.rb
  Formula/duck.rb
  Formula/eslint.rb
  Formula/glooctl.rb
  Formula/helmfile.rb
  Formula/imagemagick.rb
  Formula/kubeprod.rb
  Formula/mighttpd2.rb
  Formula/nginx.rb
  Formula/parallel.rb
  Formula/passenger.rb
  Formula/pdf2htmlex.rb
  Formula/teleport.rb
  Formula/terraform.rb
  Formula/terragrunt.rb
  Formula/util-linux.rb
  Formula/vagrant-completion.rb
  Formula/vamp-plugin-sdk.rb
  Formula/wtf.rb
Labels: merge

#13964 Merge 2019-06-29 f08590d742
  Formula/circleci.rb
  Formula/cointop.rb
  Formula/devspace.rb
  Formula/drone-cli.rb
  Formula/exploitdb.rb
  Formula/faas-cli.rb
  Formula/firebase-cli.rb
  Formula/glooctl.rb
  Formula/gnu-getopt.rb
  Formula/grafana.rb
  Formula/grakn.rb
  Formula/haskell-stack.rb
  Formula/hlint.rb
  Formula/istioctl.rb
  Formula/nave.rb
  Formula/noti.rb
  Formula/pgbadger.rb
  Formula/procs.rb
  Formula/serverless.rb
  Formula/ship.rb
  Formula/telegraf.rb
  Formula/ttyd.rb
  Formula/vim.rb
  Formula/vulkan-headers.rb
Labels: merge

#13965 Merge 2019-06-29 cffa6d1d70
  Formula/aliyun-cli.rb
  Formula/convox.rb
  Formula/cql.rb
  Formula/cromwell.rb
  Formula/datetime-fortran.rb
  Formula/dehydrated.rb
  Formula/dhall-json.rb
  Formula/emscripten.rb
  Formula/exploitdb.rb
  Formula/gitlab-runner.rb
  Formula/helmsman.rb
  Formula/imagemagick@6.rb
  Formula/json-fortran.rb
  Formula/jvgrep.rb
  Formula/libevent.rb
  Formula/pulumi.rb
  Formula/reattach-to-user-namespace.rb
  Formula/riemann.rb
  Formula/sccache.rb
  Formula/ship.rb
  Formula/spirv-cross.rb
  Formula/vfuse.rb
  Formula/wla-dx.rb
  Formula/youtube-dl.rb
Labels: merge

#13966 Merge 2019-06-29 5659fc352d
  Formula/aliyun-cli.rb
  Formula/angular-cli.rb
  Formula/autorest.rb
  Formula/cfn-lint.rb
  Formula/consul.rb
  Formula/docker-completion.rb
  Formula/docker.rb
  Formula/exploitdb.rb
  Formula/faas-cli.rb
  Formula/fluxctl.rb
  Formula/futhark.rb
  Formula/gpac.rb
  Formula/homeassistant-cli.rb
  Formula/istioctl.rb
  Formula/latexml.rb
  Formula/ldc.rb
  Formula/librealsense.rb
  Formula/libuv.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/node.rb
  Formula/orc-tools.rb
  Formula/stellar-core.rb
  Formula/swagger-codegen@2.rb
Labels: merge

#13967 Merge 2019-06-29 342c9a8a48
  Formula/bazel.rb
  Formula/dependency-check.rb
  Formula/gradle.rb
  Formula/harfbuzz.rb
  Formula/hub.rb
  Formula/jadx.rb
  Formula/janet.rb
  Formula/libevhtp.rb
  Formula/minizinc.rb
  Formula/root.rb
  Formula/serverless.rb
  Formula/tile38.rb
  Formula/xcodegen.rb
  Formula/yarn.rb
Labels: merge

#14009 Merge 2019-06-30 bd0e850618
  Formula/awscli.rb
  Formula/clojure.rb
  Formula/cocoapods.rb
  Formula/diff-so-fancy.rb
  Formula/gnuradio.rb
  Formula/goreleaser.rb
  Formula/gr-osmosdr.rb
  Formula/irssi.rb
  Formula/jboss-forge.rb
  Formula/mkl-dnn.rb
  Formula/opensubdiv.rb
  Formula/recon-ng.rb
  Formula/rtags.rb
  Formula/swagger-codegen.rb
  Formula/teleport.rb
  Formula/uhd.rb
Labels: merge

#13466 wxpython: Build a bottle for Linuxbrew
  Formula/wxpython.rb
Labels: bottle
