Repository Homebrew/linuxbrew-core, pull requests merged in 2019-05, with the labels that each got.

#12886 Merge 2019-05-02 65a45a9e61
  Aliases/swig@4.0
  Formula/bluepill.rb
  Formula/ghq.rb
  Formula/pulumi.rb
  Formula/qt.rb
  Formula/sbcl.rb
  Formula/swig.rb
  Formula/tmux.rb
Labels: merge

#12892 Merge 2019-05-03 ce59a1a3a2
  Formula/bettercap.rb
  Formula/bit.rb
  Formula/bzt.rb
  Formula/dovecot.rb
  Formula/faas-cli.rb
  Formula/gssdp.rb
  Formula/gupnp.rb
  Formula/hugo.rb
  Formula/mercurial.rb
  Formula/php.rb
  Formula/php@7.2.rb
  Formula/pumba.rb
  Formula/pushpin.rb
  Formula/translate-shell.rb
Labels: merge

#12903 Merge 2019-05-03 f8538a565e
  Formula/allureofthestars.rb
  Formula/awscli.rb
  Formula/camlp4.rb
  Formula/diff-pdf.rb
  Formula/glib-networking.rb
  Formula/gmic.rb
  Formula/imagemagick@6.rb
  Formula/imapsync.rb
  Formula/mariadb@10.1.rb
  Formula/nexus.rb
  Formula/pdftoipe.rb
  Formula/php@7.1.rb
  Formula/pipx.rb
  Formula/poppler.rb
  Formula/prototool.rb
  Formula/simgrid.rb
  Formula/taskell.rb
  Formula/tor.rb
  Formula/unp64.rb
Labels: merge

#12911 Merge 2019-05-04 16d6d3920a
  Formula/bash.rb
  Formula/cloc.rb
  Formula/cmatrix.rb
  Formula/cxxtest.rb
  Formula/dhcpdump.rb
  Formula/dhcping.rb
  Formula/diffstat.rb
  Formula/dnstracer.rb
  Formula/dvorak7min.rb
  Formula/eccodes.rb
  Formula/etcd.rb
  Formula/fftw.rb
  Formula/libmatroska.rb
  Formula/mkvtoolnix.rb
  Formula/mu.rb
  Formula/netcat6.rb
  Formula/num-utils.rb
  Formula/openssl.rb
  Formula/ophcrack.rb
  Formula/patchutils.rb
  Formula/rdesktop.rb
  Formula/sane-backends.rb
  Formula/stress.rb
  Formula/tesseract.rb
  Formula/toilet.rb
  Formula/velero.rb
  Formula/webalizer.rb
  Formula/yara.rb
  Formula/zola.rb
Labels: merge

#12919 Merge 2019-05-05 9b37cb4053
  Formula/aws-cfn-tools.rb
  Formula/aws-elasticache.rb
  Formula/glib.rb
  Formula/imagemagick.rb
  Formula/interactive-rebase-tool.rb
  Formula/klavaro.rb
  Formula/libnfc.rb
  Formula/mkvtoolnix.rb
  Formula/rds-command-line-tools.rb
  Formula/rustup-init.rb
  Formula/s3-backer.rb
  Formula/torsocks.rb
  Formula/unarj.rb
Labels: merge

#12923 Merge 2019-05-05 bcc377d439
  Formula/gdal.rb
  Formula/glooctl.rb
  Formula/libgaiagraphics.rb
  Formula/libgeotiff.rb
  Formula/liblas.rb
  Formula/librasterlite.rb
  Formula/nodenv.rb
  Formula/pdal.rb
Labels: merge

#12925 Merge 2019-05-06 a5672b074d
  Formula/gmt.rb
  Formula/numpy.rb
  Formula/nwchem.rb
  Formula/openblas.rb
  Formula/opencv.rb
  Formula/opencv@3.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/r.rb
  Formula/scalapack.rb
  Formula/scipy.rb
  Formula/visp.rb
Labels: merge

#12935 Merge 2019-05-07 58cb1e2fd4
  Formula/agda.rb
  Formula/argyll-cms.rb
  Formula/azure-cli.rb
  Formula/bzt.rb
  Formula/cargo-completion.rb
  Formula/ccache.rb
  Formula/crosstool-ng.rb
  Formula/ettercap.rb
  Formula/flow.rb
  Formula/ghq.rb
  Formula/gtksourceview3.rb
  Formula/libgsf.rb
  Formula/logstash.rb
  Formula/simple-scan.rb
Labels: merge

#12944 Merge 2019-05-07 d5a04a186e
  Formula/dirac.rb
  Formula/dvorak7min.rb
  Formula/jenkins.rb
  Formula/minbif.rb
  Formula/mytop.rb
  Formula/ppl.rb
  Formula/schroedinger.rb
  Formula/sdl_sound.rb
  Formula/toilet.rb
  Formula/unp.rb
  Formula/urlview.rb
Labels: merge

#12946 Merge 2019-05-08 6f34b1f9c7
  Formula/apache-spark.rb
  Formula/basex.rb
  Formula/bazel.rb
  Formula/bitcoin.rb
  Formula/docker-completion.rb
  Formula/docker.rb
  Formula/easyengine.rb
  Formula/ghq.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/gomplate.rb
  Formula/gst-validate.rb
  Formula/leveldb.rb
  Formula/libdazzle.rb
  Formula/libomp.rb
  Formula/proteinortho.rb
  Formula/syncthing.rb
  Formula/ucloud.rb
  Formula/vte3.rb
  Formula/yelp-tools.rb
Labels: merge

#12954 Merge 2019-05-08 763ca1f3c6
  Aliases/gcc@9
  Formula/gcc.rb
Labels: merge

#12955 Merge 2019-05-08 06473a6f04
  Formula/abyss.rb
  Formula/arpack.rb
  Formula/binwalk.rb
  Formula/cp2k.rb
  Formula/dungeon.rb
  Formula/dynare.rb
  Formula/eccodes.rb
  Formula/fastme.rb
  Formula/fftw.rb
  Formula/grib-api.rb
  Formula/hdf5.rb
  Formula/hdf5@1.8.rb
  Formula/json-fortran.rb
  Formula/kahip.rb
  Formula/lapack.rb
  Formula/libxc.rb
  Formula/lysp.rb
  Formula/mmseqs2.rb
  Formula/mpich.rb
  Formula/netcdf.rb
  Formula/octave.rb
Labels: merge

#12956 Merge 2019-05-08 addf9e29c9
  Formula/armadillo.rb
  Formula/imake.rb
  Formula/minisat.rb
  Formula/nwchem.rb
  Formula/open-mpi.rb
  Formula/openblas.rb
  Formula/packmol.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/pgplot.rb
  Formula/plplot.rb
  Formula/qrupdate.rb
  Formula/r.rb
  Formula/reprepro.rb
  Formula/root.rb
  Formula/scalapack.rb
  Formula/scipy.rb
  Formula/spades.rb
Labels: merge

#12957 Merge 2019 05 08 eabc89d95b
  Formula/gcc@8.rb
Labels: merge

#12958 Merge 2019-05-08 915a61dee5
  Formula/abyss.rb
  Formula/armadillo.rb
  Formula/arpack.rb
  Formula/binwalk.rb
  Formula/cp2k.rb
  Formula/dungeon.rb
  Formula/dynare.rb
  Formula/eccodes.rb
  Formula/fastme.rb
  Formula/fftw.rb
  Formula/gcc.rb
  Formula/grib-api.rb
  Formula/hdf5.rb
  Formula/hdf5@1.8.rb
  Formula/imake.rb
  Formula/json-fortran.rb
  Formula/kahip.rb
  Formula/lapack.rb
  Formula/libxc.rb
  Formula/lysp.rb
  Formula/mmseqs2.rb
  Formula/mpich.rb
  Formula/netcdf.rb
  Formula/nwchem.rb
  Formula/octave.rb
  Formula/open-mpi.rb
  Formula/openblas.rb
  Formula/packmol.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/pgplot.rb
  Formula/plplot.rb
  Formula/qrupdate.rb
  Formula/r.rb
  Formula/reprepro.rb
  Formula/root.rb
  Formula/scalapack.rb
  Formula/scipy.rb
  Formula/spades.rb
Labels: merge

#12959 Merge 2019-05-08 0f37d04a91
  Formula/gcc@8.rb
Labels: merge

#12988 Merge 2019-05-10 c33ad7f96f
  Formula/allure.rb
  Formula/ant.rb
  Formula/asciidoctor.rb
  Formula/bazel.rb
  Formula/cfn-lint.rb
  Formula/dep.rb
  Formula/eccodes.rb
  Formula/fn.rb
  Formula/geos.rb
  Formula/gjs.rb
  Formula/glooctl.rb
  Formula/jenkins.rb
  Formula/libgda.rb
  Formula/logtalk.rb
  Formula/mvnvm.rb
  Formula/nethack.rb
  Formula/ngspice.rb
  Formula/pulumi.rb
  Formula/qpdf.rb
  Formula/terraforming.rb
  Formula/travis.rb
  Formula/vegeta.rb
  Formula/vim.rb
Labels: merge

#12998 Merge 2019-05-11 0a6eb69ef0
  Formula/armadillo.rb
  Formula/buildkit.rb
  Formula/bwfmetaedit.rb
  Formula/easyengine.rb
  Formula/freetds.rb
  Formula/freetds@0.91.rb
  Formula/libgadu.rb
  Formula/openimageio.rb
  Formula/osmosis.rb
  Formula/percona-xtrabackup.rb
  Formula/phpunit.rb
  Formula/planck.rb
  Formula/roswell.rb
  Formula/sfst.rb
  Formula/unarj.rb
  Formula/velero.rb
Labels: merge

#12999 Merge 2019-05-11 991a579a14
  Formula/aliyun-cli.rb
  Formula/calicoctl.rb
  Formula/doctl.rb
  Formula/glooctl.rb
  Formula/gtk-doc.rb
  Formula/i2pd.rb
  Formula/imapsync.rb
  Formula/istioctl.rb
  Formula/kotlin.rb
  Formula/kubeprod.rb
  Formula/lxc.rb
  Formula/serverless.rb
  Formula/skaffold.rb
  Formula/ttyd.rb
  Formula/ucloud.rb
  Formula/yarn.rb
Labels: merge

#13008 Boost: Fix test for linux
  Formula/boost.rb
Labels: test-failure

#13009 Merge 2019-05-11 1e6fc8013f
  Formula/cfn-lint.rb
  Formula/checkbashisms.rb
  Formula/conan.rb
  Formula/glooctl.rb
  Formula/imagemagick.rb
  Formula/ipmitool.rb
  Formula/istioctl.rb
  Formula/jhipster.rb
  Formula/joplin.rb
  Formula/juju.rb
  Formula/netpbm.rb
  Formula/oniguruma.rb
  Formula/opencoarrays.rb
  Formula/postgresql@9.6.rb
  Formula/pygobject.rb
  Formula/socat.rb
  Formula/utf8proc.rb
  Formula/wtf.rb
  Formula/youtube-dl.rb
Labels: merge

#13024 Merge 2019-05-13 24ed74a050
  Formula/angular-cli.rb
  Formula/app-engine-python.rb
  Formula/asciidoctorj.rb
  Formula/atlassian-cli.rb
  Formula/bazel.rb
  Formula/checkstyle.rb
  Formula/cypher-shell.rb
  Formula/elasticsearch.rb
  Formula/erlang.rb
  Formula/erlang@19.rb
  Formula/eslint.rb
  Formula/exiv2.rb
  Formula/faas-cli.rb
  Formula/frugal.rb
  Formula/geeqie.rb
  Formula/gegl.rb
  Formula/gexiv2.rb
  Formula/groovy.rb
  Formula/gtk-doc.rb
  Formula/jenkins-lts.rb
  Formula/libnice.rb
  Formula/libpq.rb
  Formula/libpqxx.rb
  Formula/micronaut.rb
  Formula/osm2pgrouting.rb
  Formula/postgresql.rb
  Formula/terraforming.rb
Labels: merge

#13038 Merge 2019-05-13 22f2c75ba4
  Formula/fluxctl.rb
  Formula/ghq.rb
  Formula/gnunet.rb
  Formula/groovysdk.rb
  Formula/kube-aws.rb
  Formula/kubernetes-service-catalog-client.rb
  Formula/landscaper.rb
  Formula/lazygit.rb
  Formula/libshout.rb
  Formula/supervisor.rb
  Formula/topgrade.rb
  Formula/typesafe-activator.rb
  Formula/verilator.rb
  Formula/webpack.rb
  Formula/wiremock-standalone.rb
Labels: merge

#13051 Merge 2019-05-13 74fe49da37
  Formula/amazon-ecs-cli.rb
  Formula/babel.rb
  Formula/efl.rb
  Formula/fibjs.rb
  Formula/grakn.rb
  Formula/jenkins.rb
  Formula/kubeless.rb
  Formula/libmtp.rb
  Formula/libmwaw.rb
  Formula/libntlm.rb
  Formula/libodfgen.rb
  Formula/libofx.rb
  Formula/libopenmpt.rb
  Formula/libpsl.rb
  Formula/libwpd.rb
  Formula/libwpg.rb
  Formula/mbedtls.rb
  Formula/mdds.rb
  Formula/mdk.rb
  Formula/mesa.rb
  Formula/prettier.rb
  Formula/sourcekitten.rb
  Formula/terragrunt.rb
Labels: merge

#13061 nlopt: fix test for linux
  Formula/nlopt.rb
Labels: test-failure

#13064 Merge 2019-05-14 e528458185
  Formula/bartycrouch.rb
  Formula/cointop.rb
  Formula/elixir.rb
  Formula/fonttools.rb
  Formula/freetds.rb
  Formula/gdb.rb
  Formula/gibo.rb
  Formula/js-test-driver.rb
  Formula/jsdoc3.rb
  Formula/kibana.rb
  Formula/lzip.rb
  Formula/mackup.rb
  Formula/mimic.rb
  Formula/phpstan.rb
  Formula/prettier.rb
  Formula/protoc-gen-go.rb
  Formula/serve.rb
  Formula/syncthing.rb
  Formula/teleport.rb
  Formula/terrahub.rb
  Formula/tile38.rb
  Formula/topgrade.rb
  Formula/vegeta.rb
Labels: merge

#13062 open-mpi: fix test
  Formula/open-mpi.rb
Labels: test-failure

#13080 Merge 2019-05-14 5061fd0ca1
  Formula/appstream-glib.rb
  Formula/evince.rb
  Formula/openapi-generator.rb
  Formula/terrahub.rb
Labels: merge

#13081 Merge 2019-05-14 cb211b7c25
  Formula/util-linux.rb
Labels: merge

#13083 Merge 2019-05-14 3ec9299df8
  Formula/appstream-glib.rb
  Formula/cromwell.rb
  Formula/evince.rb
  Formula/llvm.rb
Labels: merge

#13085 Merge 2019-05-15 9574c97fea
  Formula/chamber.rb
  Formula/consul.rb
  Formula/dnscrypt-proxy.rb
  Formula/frpc.rb
  Formula/mplayer.rb
  Formula/mupdf.rb
  Formula/ocrmypdf.rb
  Formula/phoronix-test-suite.rb
Labels: merge

#13089 Merge 2019-05-15 e6287d6072
  Formula/patchelf.rb
Labels: merge

#13091 Merge 2019-05-15 4f99ccddcb
  Formula/fn.rb
  Formula/gcsfuse.rb
  Formula/memcached.rb
  Formula/mongoose.rb
  Formula/mruby.rb
  Formula/msmtp.rb
  Formula/ndpi.rb
  Formula/nss.rb
  Formula/ntl.rb
  Formula/pcb.rb
  Formula/pulumi.rb
Labels: merge

#13099 patchelf: Update the bottle sha256 for Linux
  Formula/patchelf.rb
Labels: bottle, bug

#13101 Merge 2019-05-16 79c8c3603c
  Formula/cfr-decompiler.rb
  Formula/convox.rb
  Formula/erlang.rb
  Formula/joplin.rb
  Formula/juju.rb
  Formula/librsvg.rb
  Formula/mailutils.rb
  Formula/mpck.rb
  Formula/mtools.rb
  Formula/mupdf-tools.rb
  Formula/ncdc.rb
  Formula/ompl.rb
  Formula/opencc.rb
  Formula/pari.rb
  Formula/pdal.rb
  Formula/phpunit.rb
  Formula/pypy.rb
  Formula/serverless.rb
  Formula/topgrade.rb
Labels: merge

#13113 Merge 2019-05-16 1b95614c5a
  Formula/rust.rb
Labels: merge

#13115 Merge 2019-05-16 17cf003b16
  Formula/avro-c.rb
  Formula/avro-cpp.rb
  Formula/avro-tools.rb
  Formula/bitrise.rb
  Formula/chakra.rb
  Formula/dmd.rb
  Formula/elasticsearch@5.6.rb
  Formula/frugal.rb
  Formula/gambit-scheme.rb
  Formula/glooctl.rb
  Formula/juju.rb
  Formula/kops.rb
  Formula/kubernetes-service-catalog-client.rb
  Formula/libzt.rb
  Formula/mariadb.rb
  Formula/mariadb@10.2.rb
  Formula/needle.rb
  Formula/nomad.rb
  Formula/telegraf.rb
  Formula/tomcat.rb
  Formula/topgrade.rb
  Formula/wireshark.rb
  Formula/xplanet.rb
Labels: merge

#13116 Merge 2019-05-16 3a1ad03ec0
  Formula/ghr.rb
  Formula/gkrellm.rb
  Formula/lensfun.rb
  Formula/mpdscribble.rb
  Formula/proteinortho.rb
  Formula/ship.rb
  Formula/valabind.rb
Labels: merge

#13117 Merge 2019-05-16 8329ea14b9
  Formula/gtk-engines.rb
  Formula/gtk-murrine-engine.rb
  Formula/rlvm.rb
  Formula/xmoto.rb
Labels: merge

#13118 Merge 2019-05-16 b7d3de1a09
  Formula/calicoctl.rb
  Formula/corsixth.rb
  Formula/cql.rb
  Formula/cracklib.rb
  Formula/kubernetes-helm.rb
  Formula/lilv.rb
  Formula/lv2.rb
  Formula/pinfo.rb
  Formula/serd.rb
  Formula/ship.rb
  Formula/source-to-image.rb
  Formula/sratom.rb
Labels: merge

#13135 Merge 2019-05-17 798a0f6603
  Formula/arpack.rb
  Formula/hypre.rb
Labels: merge

#13136 Merge 2019-05-17 94913e5bdc
  Formula/qrupdate.rb
  Formula/suite-sparse.rb
  Formula/superlu.rb
Labels: merge

#13137 Merge 2019-05-17 857afd10f2
  Formula/dynare.rb
  Formula/octave.rb
  Formula/sundials.rb
Labels: merge

#13138 Merge 2019-05-17 193c6138d5
  Formula/arpack.rb
  Formula/dynare.rb
  Formula/hypre.rb
  Formula/octave.rb
  Formula/qrupdate.rb
  Formula/suite-sparse.rb
  Formula/sundials.rb
  Formula/superlu.rb
Labels: merge

#13145 Merge 2019-05-17 4f140c105c
  Formula/mariadb-connector-c.rb
  Formula/postgresql@9.5.rb
Labels: merge

#13150 Merge 2019-05-17 5654726ef7
  Formula/etl.rb
  Formula/gtk-gnutella.rb
  Formula/pure-ftpd.rb
  Formula/qca.rb
  Formula/qd.rb
  Formula/qwt.rb
  Formula/rancid.rb
  Formula/remind.rb
  Formula/sdl2_ttf.rb
  Formula/smali.rb
  Formula/spin.rb
  Formula/srt.rb
  Formula/sslscan.rb
  Formula/stk.rb
  Formula/stunnel.rb
  Formula/synfig.rb
  Formula/sysbench.rb
  Formula/talloc.rb
  Formula/tass64.rb
  Formula/tbb.rb
  Formula/tcsh.rb
  Formula/tdlib.rb
  Formula/texmath.rb
  Formula/velero.rb
Labels: merge

#13151 Merge 2019-05-17 397b4c982f
  Formula/cmake.rb
  Formula/ghq.rb
  Formula/ospray.rb
  Formula/paperkey.rb
  Formula/physfs.rb
  Formula/pick.rb
  Formula/plzip.rb
  Formula/proguard.rb
  Formula/quantlib.rb
  Formula/quilt.rb
  Formula/rdesktop.rb
  Formula/re2.rb
  Formula/recoverjpeg.rb
  Formula/reposurgeon.rb
  Formula/rt-audio.rb
  Formula/rtmidi.rb
  Formula/sdcc.rb
  Formula/shyaml.rb
  Formula/topgrade.rb
Labels: merge

#13170 Merge 2019-05-17 18c3817332
  Aliases/solr@8.1
  Formula/awscli.rb
  Formula/bind.rb
  Formula/bit.rb
  Formula/buku.rb
  Formula/cfn-lint.rb
  Formula/corsixth.rb
  Formula/docker-machine-driver-xhyve.rb
  Formula/doctl.rb
  Formula/firebase-cli.rb
  Formula/frugal.rb
  Formula/kops.rb
  Formula/kubernetes-cli.rb
  Formula/liquid-dsp.rb
  Formula/llvm.rb
  Formula/proj.rb
  Formula/pulumi.rb
  Formula/redis.rb
  Formula/riemann.rb
  Formula/sile.rb
  Formula/solr.rb
  Formula/terraform.rb
  Formula/terragrunt.rb
  Formula/tippecanoe.rb
  Formula/tkdiff.rb
  Formula/tomcat@6.rb
  Formula/tomcat@7.rb
  Formula/tomcat@8.rb
  Formula/ungit.rb
  Formula/wireguard-go.rb
  formula_renames.json
Labels: merge

#13182 Merge 2019-05-18 eede0ee7f1
  Formula/apache-archiva.rb
  Formula/artifactory.rb
  Formula/aspectj.rb
  Formula/bat.rb
  Formula/byteman.rb
  Formula/gollum.rb
  Formula/ivykis.rb
  Formula/libdc1394.rb
  Formula/libelf.rb
  Formula/libsoup.rb
  Formula/mariadb@10.1.rb
  Formula/mmseqs2.rb
  Formula/operator-sdk.rb
  Formula/postgresql@9.4.rb
  Formula/sparse.rb
  Formula/step.rb
  Formula/visp.rb
  Formula/yq.rb
Labels: merge

#13037 postgresql: remove initdb calls when root
  Formula/postgresql.rb
  Formula/postgresql@10.rb
  Formula/postgresql@9.4.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
Labels: enhancement

#13195 Merge 2019-05-18 cf0ae29976
  Formula/akka.rb
  Formula/auditbeat.rb
  Formula/circleci.rb
  Formula/gandi.cli.rb
  Formula/glooctl.rb
  Formula/gor.rb
  Formula/gx.rb
  Formula/istioctl.rb
  Formula/lf.rb
  Formula/metricbeat.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/mmark.rb
  Formula/node_exporter.rb
  Formula/opa.rb
  Formula/openshift-cli.rb
  Formula/pilosa.rb
  Formula/postgresql@10.rb
  Formula/s-search.rb
  Formula/serf.rb
Labels: merge

#13211 Merge 2019-05-19 2a2fe93a8e
  Formula/ammonite-repl.rb
  Formula/hugo.rb
  Formula/libuv.rb
  Formula/mkvtoolnix.rb
  Formula/operator-sdk.rb
  Formula/skopeo.rb
  Formula/supervisor.rb
  Formula/swi-prolog.rb
  Formula/topgrade.rb
  Formula/wine.rb
  Formula/wiremock-standalone.rb
Labels: merge

#13216 Merge 2019-05-20 e1f113a5e6
  Aliases/bison@3.4
  Formula/binaryen.rb
  Formula/bison.rb
  Formula/cocoapods.rb
  Formula/dep.rb
  Formula/dhall.rb
  Formula/ffsend.rb
  Formula/file-formula.rb
  Formula/genact.rb
  Formula/google-benchmark.rb
  Formula/imagemagick.rb
  Formula/just.rb
  Formula/libmagic.rb
  Formula/mighttpd2.rb
  Formula/planck.rb
  Formula/scipy.rb
  Formula/shogun.rb
  Formula/smimesign.rb
  Formula/sn0int.rb
  Formula/spirv-cross.rb
  Formula/stout.rb
  Formula/wabt.rb
  Formula/websocat.rb
  Formula/wtf.rb
Labels: merge

#13230 Merge 2019-05-20 08ab93a878
  Aliases/ansible@2.8
  Formula/ansible.rb
  Formula/asdf.rb
  Formula/atari800.rb
  Formula/atlantis.rb
  Formula/cfengine.rb
  Formula/conan.rb
  Formula/jenkins.rb
  Formula/pandoc-crossref.rb
  Formula/presto.rb
  Formula/pyside.rb
  Formula/rabbitmq.rb
  Formula/velero.rb
  Formula/vim.rb
  Formula/webpack.rb
Labels: merge

#13241 Merge 2019-05-21 7ce4a83276
  Formula/allure.rb
  Formula/auditbeat.rb
  Formula/cglm.rb
  Formula/cryptol.rb
  Formula/dbmate.rb
  Formula/kitchen-sync.rb
  Formula/kubeprod.rb
  Formula/libphonenumber.rb
  Formula/metricbeat.rb
  Formula/mill.rb
  Formula/mkl-dnn.rb
  Formula/opa.rb
  Formula/parallelstl.rb
  Formula/phpstan.rb
  Formula/qpdf.rb
  Formula/riff.rb
  Formula/roswell.rb
  Formula/serverless.rb
  Formula/shc.rb
  Formula/ship.rb
  Formula/strongswan.rb
  Formula/xsimd.rb
  Formula/yle-dl.rb
  Formula/youtube-dl.rb
Labels: merge

#13255 Merge 2019-05-21 1ad3ec66c9
  Aliases/elasticsearch@6.8
  Aliases/kibana@6.8
  Formula/acpica.rb
  Formula/ant@1.9.rb
  Formula/augeas.rb
  Formula/avra.rb
  Formula/aws-sdk-cpp.rb
  Formula/b2-tools.rb
  Formula/byteman.rb
  Formula/cql.rb
  Formula/dartsim.rb
  Formula/docfx.rb
  Formula/dub.rb
  Formula/elasticsearch.rb
  Formula/gitlab-runner.rb
  Formula/kibana.rb
  Formula/lmod.rb
  Formula/nlopt.rb
  Formula/paket.rb
  Formula/shogun.rb
  Formula/xmrig.rb
Labels: merge

#13268 Merge 2019-05-22 e0426079e9
  Formula/convox.rb
  Formula/dav1d.rb
  Formula/glib.rb
  Formula/nats-streaming-server.rb
  Formula/node.rb
  Formula/php.rb
  Formula/php@7.1.rb
  Formula/php@7.2.rb
Labels: merge

#13278 Merge 2019-05-23 2c0186f74b
  Formula/django-completion.rb
  Formula/exploitdb.rb
  Formula/git-quick-stats.rb
  Formula/glslang.rb
  Formula/grails.rb
  Formula/ibex.rb
  Formula/librealsense.rb
  Formula/micronaut.rb
  Formula/n.rb
  Formula/nginx.rb
  Formula/passenger.rb
  Formula/picard-tools.rb
  Formula/tmuxinator-completion.rb
Labels: merge

#13284 Merge 2019-05-23 e47f3e2682
  Formula/curl-openssl.rb
  Formula/curl.rb
Labels: merge

#13288 Merge 2019-05-23 2efb485138
  Formula/aws-okta.rb
  Formula/babel.rb
  Formula/cockroach.rb
  Formula/cocoapods.rb
  Formula/emscripten.rb
  Formula/epubcheck.rb
  Formula/flow.rb
  Formula/fluxctl.rb
  Formula/fn.rb
  Formula/gmic.rb
  Formula/grpc.rb
  Formula/libressl.rb
  Formula/neo4j.rb
  Formula/php-cs-fixer.rb
  Formula/pre-commit.rb
  Formula/pulumi.rb
  Formula/radare2.rb
  Formula/spirv-tools.rb
  Formula/uncrustify.rb
  Formula/vips.rb
  Formula/webpack.rb
  Formula/you-get.rb
Labels: merge

#13310 Merge 2019-05-24 5bbefd7fee
  .github/lock.yml
  .github/no-response.yml
  .github/stale.yml
  Aliases/iwyu
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Formula/atlantis.rb
  Formula/bazel.rb
  Formula/cargo-completion.rb
  Formula/certbot.rb
  Formula/clzip.rb
  Formula/consul.rb
  Formula/csvq.rb
  Formula/deno.rb
  Formula/exploitdb.rb
  Formula/faudio.rb
  Formula/gitg.rb
  Formula/grafana.rb
  Formula/hlint.rb
  Formula/include-what-you-use.rb
  Formula/libdazzle.rb
  Formula/lsd.rb
  Formula/molten-vk.rb
  Formula/paket.rb
  Formula/parallel.rb
  Formula/parallelstl.rb
  Formula/pngquant.rb
  Formula/sqlmap.rb
  Formula/terrahub.rb
  Formula/tmuxinator-completion.rb
  Formula/vert.x.rb
  Formula/wartremover.rb
Labels: merge

#13318 Merge 2019-05-25 fa2be39ea1
  Formula/aide.rb
  Formula/atlantis.rb
  Formula/aws-sdk-cpp.rb
  Formula/beast.rb
  Formula/clzip.rb
  Formula/conserver.rb
  Formula/dscanner.rb
  Formula/git-cinnabar.rb
  Formula/hana.rb
  Formula/jdnssec-tools.rb
  Formula/jmxterm.rb
  Formula/libagg.rb
  Formula/libimagequant.rb
  Formula/math-comp.rb
  Formula/osc.rb
  Formula/owfs.rb
  Formula/range-v3.rb
  Formula/restview.rb
  Formula/riemann.rb
  Formula/rust.rb
  Formula/sdb.rb
  Formula/skaffold.rb
  Formula/spirv-cross.rb
  Formula/stellar-core.rb
  Formula/treefrog.rb
  Formula/tundra.rb
  Formula/wiredtiger.rb
Labels: merge

#13335 Merge 2019-05-27 35c9587785
  Aliases/terraform@0.12
  Formula/aliyun-cli.rb
  Formula/augustus.rb
  Formula/bind.rb
  Formula/cfn-lint.rb
  Formula/csound.rb
  Formula/harfbuzz.rb
  Formula/highlight.rb
  Formula/libidn2.rb
  Formula/libpsl.rb
  Formula/libuv.rb
  Formula/moarvm.rb
  Formula/neo4j.rb
  Formula/p11-kit.rb
  Formula/packer.rb
  Formula/scmpuff.rb
  Formula/terraform@0.11.rb
  Formula/wget.rb
  Formula/whois.rb
Labels: merge

#13345 Merge 2019-05-28 ef01dcf33e
  Formula/bat.rb
  Formula/bee.rb
  Formula/boost-python3.rb
  Formula/cfn-lint.rb
  Formula/cmark-gfm.rb
  Formula/convox.rb
  Formula/diffoscope.rb
  Formula/dnstwist.rb
  Formula/eye-d3.rb
  Formula/fobis.rb
  Formula/ghq.rb
  Formula/grpc.rb
  Formula/grpcurl.rb
  Formula/ibex.rb
  Formula/kobalt.rb
  Formula/lsd.rb
  Formula/mpop.rb
  Formula/msktutil.rb
  Formula/nco.rb
  Formula/pdns.rb
  Formula/peru.rb
  Formula/picat.rb
  Formula/xctool.rb
Labels: merge

#13359 azure-pipelines: setup bottle upload
  azure-pipelines.yml
Labels: needs response

#13360 Merge 2019-05-28 0c49c0b349
  .github/ISSUE_TEMPLATE/Reproducible-Bug-Report.md
  .github/issue-close-app.yml
  Formula/allure.rb
  Formula/corsixth.rb
  Formula/dcd.rb
  Formula/dhall-json.rb
  Formula/docfx.rb
  Formula/exploitdb.rb
  Formula/faas-cli.rb
  Formula/gecode.rb
  Formula/goreleaser.rb
  Formula/hlint.rb
  Formula/mame.rb
  Formula/mesa.rb
  Formula/mutt.rb
  Formula/opencascade.rb
  Formula/prometheus.rb
  Formula/rom-tools.rb
  Formula/sleuthkit.rb
  Formula/sshtrix.rb
  Formula/sslh.rb
  Formula/supervisor.rb
  Formula/swimat.rb
  Formula/topgrade.rb
  Formula/xmake.rb
Labels: merge

#13376 Merge 2019-05-29 42e3f9f64a
  .github/issue-close-app.yml
  Formula/acpica.rb
  Formula/checkstyle.rb
  Formula/crc32c.rb
  Formula/csvq.rb
  Formula/dbmate.rb
  Formula/djvu2pdf.rb
  Formula/dnscontrol.rb
  Formula/double-conversion.rb
  Formula/git-quick-stats.rb
  Formula/grafana.rb
  Formula/lego.rb
  Formula/libevent.rb
  Formula/minimal-racket.rb
  Formula/msgpack.rb
  Formula/netdata.rb
  Formula/nnn.rb
  Formula/notmuch.rb
  Formula/paket.rb
  Formula/pmd.rb
  Formula/proteinortho.rb
  Formula/swiftformat.rb
  Formula/urdfdom_headers.rb
  Formula/vim.rb
  Formula/volt.rb
  Formula/wtf.rb
Labels: merge

#13377 Merge 2019-05-29 720cbb8f57
  Formula/axel.rb
  Formula/bazel.rb
  Formula/dartsim.rb
  Formula/dita-ot.rb
  Formula/exploitdb.rb
  Formula/fn.rb
  Formula/fonttools.rb
  Formula/gnutls.rb
  Formula/heimdal.rb
  Formula/jena.rb
  Formula/ktlint.rb
  Formula/kubecfg.rb
  Formula/libqalculate.rb
  Formula/logstash.rb
  Formula/maxwell.rb
  Formula/nifi-registry.rb
  Formula/openssl@1.1.rb
  Formula/paket.rb
  Formula/perl.rb
  Formula/picard-tools.rb
  Formula/pulumi.rb
  Formula/qalculate-gtk.rb
  Formula/siril.rb
  Formula/subversion.rb
  Formula/tika.rb
  Formula/vim.rb
  Formula/vim@7.4.rb
  Formula/weechat.rb
Labels: merge

#13378 Merge 2019-05-29 6d8c03a1b5
  Formula/angular-cli.rb
  Formula/apache-drill.rb
  Formula/catch2.rb
  Formula/fq.rb
  Formula/ghq.rb
  Formula/libphonenumber.rb
  Formula/mat2.rb
  Formula/mesos.rb
  Formula/neovim.rb
  Formula/node@10.rb
  Formula/numpy.rb
  Formula/phpunit.rb
  Formula/serverless.rb
  Formula/terrahub.rb
Labels: merge

#13404 Merge 2019-05-29 406649d3d1
  .github/issue-close-app.yml
  Formula/arangodb.rb
  Formula/cgrep.rb
  Formula/flow.rb
  Formula/fuseki.rb
  Formula/gitless.rb
  Formula/hebcal.rb
  Formula/homebank.rb
  Formula/jenkins.rb
  Formula/neovim.rb
  Formula/opencoarrays.rb
  Formula/paket.rb
  Formula/qbs.rb
  Formula/solr.rb
  Formula/swift-protobuf.rb
  Formula/tomee-plus.rb
  Formula/tomee-webprofile.rb
  Formula/trafficserver.rb
  Formula/watchexec.rb
Labels: merge

#13408 Merge 2019-05-31 1c8331487e
  Formula/bzt.rb
  Formula/cython.rb
  Formula/deno.rb
  Formula/exploitdb.rb
  Formula/gitlab-runner.rb
  Formula/gnupg.rb
  Formula/gnuplot.rb
  Formula/googler.rb
  Formula/highlight.rb
  Formula/imagemagick.rb
  Formula/imageoptim-cli.rb
  Formula/inlets.rb
  Formula/jenkins-job-builder.rb
  Formula/libjwt.rb
  Formula/minio-mc.rb
  Formula/nanopb-generator.rb
  Formula/phpstan.rb
  Formula/protoc-gen-go.rb
  Formula/sourcery.rb
  Formula/spice-gtk.rb
  Formula/trezor-agent.rb
  Formula/typescript.rb
  Formula/wtf.rb
  Formula/xpdf.rb
Labels: merge
