Repository Homebrew/linuxbrew-core, pull requests merged in 2020-06, with the labels that each got.

#20459 Merge 2020-06-01 35204b9362
  Formula/artifactory.rb
  Formula/ask-cli.rb
  Formula/babel.rb
  Formula/balena-cli.rb
  Formula/bitwarden-cli.rb
  Formula/broot.rb
  Formula/cartridge-cli.rb
  Formula/cromwell.rb
  Formula/exploitdb.rb
  Formula/fcct.rb
  Formula/firebase-cli.rb
  Formula/fluent-bit.rb
  Formula/gauge.rb
  Formula/git-absorb.rb
  Formula/jenkins-job-builder.rb
  Formula/kyma-cli.rb
  Formula/lazydocker.rb
  Formula/lerna.rb
  Formula/minikube.rb
  Formula/operator-sdk.rb
  Formula/picard-tools.rb
  Formula/polynote.rb
  Formula/prestosql.rb
  Formula/pulumi.rb
  Formula/solr.rb
  Formula/solr@7.7.rb
  Formula/stress-ng.rb
  Formula/terragrunt.rb
  Formula/vte3.rb
Labels: merge

#20460 Merge 2020-06-01 0ecb1e14f2
  Formula/acpica.rb
  Formula/atlantis.rb
  Formula/babel.rb
  Formula/cake.rb
  Formula/circleci.rb
  Formula/dbhash.rb
  Formula/deno.rb
  Formula/diffoscope.rb
  Formula/efl.rb
  Formula/evince.rb
  Formula/gatsby-cli.rb
  Formula/helmfile.rb
  Formula/hlint.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jupyterlab.rb
  Formula/latexdiff.rb
  Formula/librsvg.rb
  Formula/libtrace.rb
  Formula/mavsdk.rb
  Formula/maxwell.rb
  Formula/mu.rb
  Formula/ncdu.rb
  Formula/node-sass.rb
  Formula/nss.rb
  Formula/onnxruntime.rb
  Formula/pandoc-crossref.rb
  Formula/plantuml.rb
  Formula/pnpm.rb
  Formula/protobuf.rb
  Formula/rav1e.rb
  Formula/re-flex.rb
  Formula/redis.rb
  Formula/sqldiff.rb
  Formula/sqlite-analyzer.rb
  Formula/sqlite.rb
  Formula/stellar-core.rb
  Formula/vault.rb
  Formula/vim.rb
  Formula/watson.rb
  Formula/yara.rb
Labels: merge

#20463 Merge 2020-06-01 8bb7a46553
  Formula/activemq.rb
  Formula/ant.rb
  Formula/asyncplusplus.rb
  Formula/autopep8.rb
  Formula/benthos.rb
  Formula/cake.rb
  Formula/cddlib.rb
  Formula/checkstyle.rb
  Formula/cppad.rb
  Formula/docfx.rb
  Formula/easyrpg-player.rb
  Formula/fetchmail.rb
  Formula/fluid-synth.rb
  Formula/fmt.rb
  Formula/gatsby-cli.rb
  Formula/goreleaser.rb
  Formula/graph-tool.rb
  Formula/groonga.rb
  Formula/hlint.rb
  Formula/homeshick.rb
  Formula/hugo.rb
  Formula/hypre.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/ipython.rb
  Formula/jc.rb
  Formula/knot.rb
  Formula/kops.rb
  Formula/kubeseal.rb
  Formula/libgpg-error.rb
  Formula/libgphoto2.rb
  Formula/libgr.rb
  Formula/libhdhomerun.rb
  Formula/libosinfo.rb
  Formula/libxlsxwriter.rb
  Formula/mdcat.rb
  Formula/menhir.rb
  Formula/metabase.rb
  Formula/mkvtoolnix.rb
  Formula/mpg123.rb
  Formula/mu.rb
  Formula/osc.rb
  Formula/sbcl.rb
  Formula/sbt.rb
  Formula/snapraid.rb
  Formula/sniffglue.rb
  Formula/spotify-tui.rb
  Formula/ssh-copy-id.rb
  Formula/swi-prolog.rb
  Formula/swiftformat.rb
  Formula/valgrind.rb
  Formula/vapoursynth.rb
  Formula/volta.rb
  Formula/vpn-slice.rb
  Formula/zabbix.rb
Labels: merge

#20465 Merge 2020-06-01 bffaa7b50d
  Formula/aom.rb
  Formula/caffe.rb
  Formula/cassowary.rb
  Formula/castxml.rb
  Formula/cdogs-sdl.rb
  Formula/chromaprint.rb
  Formula/cloud-nuke.rb
  Formula/dar.rb
  Formula/dosbox-x.rb
  Formula/erlang.rb
  Formula/erlang@22.rb
  Formula/feh.rb
  Formula/ffmpeg.rb
  Formula/ffmpeg2theora.rb
  Formula/ffmpeg@2.8.rb
  Formula/ffmpegthumbnailer.rb
  Formula/ffms2.rb
  Formula/frugal.rb
  Formula/gauge.rb
  Formula/ghz-web.rb
  Formula/gitleaks.rb
  Formula/glooctl.rb
  Formula/gnu-chess.rb
  Formula/gocryptfs.rb
  Formula/gotop.rb
  Formula/imgproxy.rb
  Formula/komposition.rb
  Formula/libheif.rb
  Formula/little-cms2.rb
  Formula/mesa.rb
  Formula/mgba.rb
  Formula/minidlna.rb
  Formula/mpd.rb
  Formula/mpv.rb
  Formula/opencv.rb
  Formula/opencv@2.rb
  Formula/opencv@3.rb
  Formula/openimageio.rb
  Formula/pianobar.rb
  Formula/qcli.rb
  Formula/rakudo.rb
  Formula/scrcpy.rb
  Formula/siril.rb
  Formula/sqlmap.rb
  Formula/stlink.rb
  Formula/tengo.rb
  Formula/unpaper.rb
  Formula/v2ray-plugin.rb
  Formula/vcs.rb
  Formula/vips.rb
  Formula/whistle.rb
  Formula/x265.rb
  Formula/zsh-completions.rb
Labels: merge

#20469 Merge 2020-06-02 fee8ef7999
  Formula/austin.rb
  Formula/bnd.rb
  Formula/commandbox.rb
  Formula/darkice.rb
  Formula/flash.rb
  Formula/folly.rb
  Formula/gauge.rb
  Formula/ghz-web.rb
  Formula/ghz.rb
  Formula/gjs.rb
  Formula/gleam.rb
  Formula/gpp.rb
  Formula/jsoncpp.rb
  Formula/jupyterlab.rb
  Formula/lgogdownloader.rb
  Formula/libjson-rpc-cpp.rb
  Formula/libsbol.rb
  Formula/mosquitto.rb
  Formula/pastel.rb
  Formula/redex.rb
  Formula/sysdig.rb
  Formula/uriparser.rb
  Formula/wartremover.rb
  Formula/webdis.rb
Labels: merge

#20471 Merge 2020-06-02 ddd39cf1b7
  Formula/arangodb.rb
  Formula/azure-cli.rb
  Formula/earthly.rb
  Formula/go@1.13.rb
  Formula/mit-scheme.rb
  Formula/octant.rb
  Formula/rke.rb
  Formula/stella.rb
Labels: merge

#20476 Merge 2020-06-02 3832ecf63b
  Formula/acme.rb
  Formula/benthos.rb
  Formula/bettercap.rb
  Formula/broot.rb
  Formula/calicoctl.rb
  Formula/chronograf.rb
  Formula/coturn.rb
  Formula/ctop.rb
  Formula/docker.rb
  Formula/doctl.rb
  Formula/exploitdb.rb
  Formula/git-gui.rb
  Formula/git.rb
  Formula/haproxy.rb
  Formula/libyaml.rb
  Formula/nghttp2.rb
  Formula/packr.rb
  Formula/ponysay.rb
  Formula/pulumi.rb
Labels: merge

#20477 Merge 2020-06-02 c2e7fa3a02
  Formula/contentful-cli.rb
  Formula/cypher-shell.rb
  Formula/docker-completion.rb
  Formula/doctl.rb
  Formula/exult.rb
  Formula/gjs.rb
  Formula/inxi.rb
  Formula/jfrog-cli.rb
  Formula/kube-aws.rb
  Formula/latex2rtf.rb
  Formula/libvirt.rb
  Formula/man-db.rb
  Formula/nco.rb
  Formula/opa.rb
  Formula/openfortivpn.rb
  Formula/openimageio.rb
  Formula/openttd.rb
  Formula/perl.rb
  Formula/proftpd.rb
  Formula/pueue.rb
  Formula/re2.rb
  Formula/serverless.rb
  Formula/subversion.rb
  Formula/syncthing.rb
  Formula/vim.rb
  Formula/weechat.rb
  formula_renames.json
Labels: merge

#20478 Merge 2020-06-03 b8d5c76d7f
  Formula/buildifier.rb
  Formula/csvq.rb
  Formula/cucumber-ruby.rb
  Formula/deno.rb
  Formula/dnscontrol.rb
  Formula/doctl.rb
  Formula/flow.rb
  Formula/geoserver.rb
  Formula/gosu.rb
  Formula/gradle.rb
  Formula/grin-wallet.rb
  Formula/i2pd.rb
  Formula/librsvg.rb
  Formula/miniserve.rb
  Formula/monolith.rb
  Formula/node@10.rb
  Formula/node@12.rb
  Formula/rbspy.rb
  Formula/semgrep.rb
  Formula/vulkan-headers.rb
  Formula/yash.rb
Labels: merge

#20480 Merge 2020-06-03 a4bdccb657
  Formula/abcmidi.rb
  Formula/aliyun-cli.rb
  Formula/aws-cdk.rb
  Formula/awscli.rb
  Formula/awscli@1.rb
  Formula/elektra.rb
  Formula/eureka.rb
  Formula/imagemagick.rb
  Formula/ktlint.rb
  Formula/liblouis.rb
  Formula/node.rb
Labels: merge

#20482 Merge 2020-06-03 002cbab741
  Formula/ant-contrib.rb
  Formula/argyll-cms.rb
  Formula/avimetaedit.rb
  Formula/bloaty.rb
  Formula/bombadillo.rb
  Formula/closure-stylesheets.rb
  Formula/composer.rb
  Formula/coredns.rb
  Formula/cpputest.rb
  Formula/dbus.rb
  Formula/drake.rb
  Formula/dvanalyzer.rb
  Formula/dylibbundler.rb
  Formula/ghq.rb
  Formula/ivykis.rb
  Formula/mediaconch.rb
  Formula/pipenv.rb
  Formula/ploticus.rb
  Formula/rest-shell.rb
  Formula/rke.rb
  Formula/rogue.rb
  Formula/scalastyle.rb
  Formula/simple-scan.rb
  Formula/sslscan.rb
  Formula/tldr.rb
  Formula/unar.rb
  Formula/zsh-lovers.rb
Labels: merge

#20485 Merge 2020-06-04 0159c45f5c
  Formula/axel.rb
  Formula/dnscrypt-proxy.rb
  Formula/docker-compose-completion.rb
  Formula/elvish.rb
  Formula/fastlane.rb
  Formula/frpc.rb
  Formula/frps.rb
  Formula/github-markdown-toc.rb
  Formula/grafana.rb
  Formula/jenkins.rb
  Formula/kumactl.rb
  Formula/libheif.rb
  Formula/monetdb.rb
  Formula/mypy.rb
  Formula/nexus.rb
  Formula/node-build.rb
  Formula/octant.rb
  Formula/pipenv.rb
Labels: merge

#20489 Merge 2020-06-04 d043c3bc99
  Formula/adios2.rb
  Formula/asciidoc.rb
  Formula/augustus.rb
  Formula/aws-cdk.rb
  Formula/docker-compose.rb
  Formula/faudio.rb
  Formula/gauge.rb
  Formula/gnutls.rb
  Formula/klavaro.rb
  Formula/libwebsockets.rb
  Formula/logstash.rb
  Formula/odin.rb
  Formula/sslyze.rb
  Formula/vlang.rb
Labels: merge

#20492 Merge 2020-06-05 fffe4d81fb
  Formula/bison.rb
  Formula/cogl.rb
  Formula/deno.rb
  Formula/gdcm.rb
  Formula/git-filter-repo.rb
  Formula/hadolint.rb
  Formula/helmsman.rb
  Formula/modules.rb
  Formula/mpop.rb
  Formula/mruby.rb
  Formula/msmtp.rb
  Formula/psqlodbc.rb
  Formula/sourcedocs.rb
  Formula/trailscraper.rb
Labels: merge

#20493 Merge 2020-06-05 467e04e806
  Formula/airshare.rb
  Formula/awscli.rb
  Formula/contentful-cli.rb
  Formula/dita-ot.rb
  Formula/django-completion.rb
  Formula/exploitdb.rb
  Formula/gitleaks.rb
  Formula/gopass.rb
  Formula/jolie.rb
  Formula/libphonenumber.rb
  Formula/lxc.rb
  Formula/netlify-cli.rb
  Formula/php.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
  Formula/phpunit.rb
  Formula/protobuf.rb
  Formula/sqldiff.rb
  Formula/sqlite-analyzer.rb
  Formula/tile38.rb
  Formula/typescript.rb
  Formula/vim.rb
  Formula/wtf.rb
Labels: merge

#20494 Merge 2020-06-05 14bcf06a4c
  Formula/apr.rb
  Formula/davix.rb
  Formula/dhall.rb
  Formula/duck.rb
  Formula/fontconfig.rb
  Formula/freeswitch.rb
  Formula/glib.rb
  Formula/mkvtoolnix.rb
Labels: merge

#20495 Merge 2020-06-05 9b179d6ca7
  Formula/freeswitch.rb
  Formula/hub.rb
  Formula/jack.rb
  Formula/libdap.rb
  Formula/mosquitto.rb
  Formula/openldap.rb
  Formula/postgresql.rb
  Formula/postgresql@10.rb
  Formula/postgresql@11.rb
  Formula/postgresql@9.4.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
  Formula/task.rb
  Formula/translate-shell.rb
  Formula/wget.rb
  Formula/xapian.rb
  Formula/xrootd.rb
Labels: merge

#20496 Merge 2020-06-05 938ceb36b2
  Formula/mdcat.rb
  Formula/molecule.rb
  Formula/mycli.rb
  Formula/mysql@5.7.rb
  Formula/nushell.rb
  Formula/openjdk.rb
  Formula/openjdk@11.rb
  Formula/pcsc-lite.rb
  Formula/progress.rb
  Formula/pwntools.rb
  Formula/salt.rb
  Formula/sdl2.rb
  Formula/skopeo.rb
  Formula/sratoolkit.rb
  Formula/statik.rb
  Formula/stormssh.rb
  Formula/streamlink.rb
  Formula/tcl-tk.rb
  Formula/tealdeer.rb
  Formula/termius.rb
  Formula/vsts-cli.rb
  Formula/wrk.rb
  Formula/wxmac.rb
  Formula/wxpython.rb
  Formula/ykman.rb
  Formula/zssh.rb
Labels: merge

#20502 Merge 2020-06-06 a74ad2f414
  Formula/annie.rb
  Formula/choose-gui.rb
  Formula/contentful-cli.rb
  Formula/dbhash.rb
  Formula/hadolint.rb
  Formula/helm.rb
  Formula/helmfile.rb
  Formula/librsvg.rb
  Formula/mm-common.rb
  Formula/node-sass.rb
  Formula/pipenv.rb
  Formula/youtube-dl.rb
Labels: merge

#20503 Merge 2020-06-07 e45dd6af7c
  Formula/aws-cdk.rb
  Formula/aws-es-proxy.rb
  Formula/balena-cli.rb
  Formula/beanstalkd.rb
  Formula/bitcoin.rb
  Formula/cargo-completion.rb
  Formula/cpr.rb
  Formula/csvq.rb
  Formula/devd.rb
  Formula/dgraph.rb
  Formula/di.rb
  Formula/docker-swarm.rb
  Formula/eslint.rb
  Formula/exploitdb.rb
  Formula/firebase-cli.rb
  Formula/fwup.rb
  Formula/gatsby-cli.rb
  Formula/gobo.rb
  Formula/grakn.rb
  Formula/gravity.rb
  Formula/helmfile.rb
  Formula/jhipster.rb
  Formula/ldid.rb
  Formula/libgosu.rb
  Formula/mailhog.rb
  Formula/mu.rb
  Formula/navi.rb
  Formula/nomad.rb
  Formula/numpy.rb
  Formula/ocrmypdf.rb
  Formula/okteto.rb
  Formula/phpunit.rb
  Formula/picard-tools.rb
  Formula/plantuml.rb
  Formula/pnpm.rb
  Formula/poetry.rb
  Formula/popt.rb
  Formula/protoc-gen-grpc-web.rb
  Formula/pulp.rb
  Formula/rex.rb
  Formula/tflint.rb
  Formula/vale.rb
  Formula/wxmaxima.rb
Labels: merge

#20506 Merge 2020-06-07 3d68b330eb
  Formula/genometools.rb
  Formula/little-cms2.rb
  Formula/mpv.rb
Labels: merge

#20507 Merge 2020-06-08 a2c70cbb7b
  Formula/cairo.rb
  Formula/camlp5.rb
  Formula/contentful-cli.rb
  Formula/gitlab-runner.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/mackup.rb
  Formula/maxima.rb
  Formula/minisign.rb
  Formula/oxipng.rb
  Formula/phpstan.rb
  Formula/phpunit.rb
  Formula/pylint.rb
  Formula/rethinkdb.rb
  Formula/topgrade.rb
  Formula/twoping.rb
  Formula/xgboost.rb
  Formula/xmake.rb
Labels: merge

#20509 Merge 2020-06-09 1cf3f00233
  Formula/airshare.rb
  Formula/cfn-lint.rb
  Formula/eg-examples.rb
  Formula/fcgi.rb
  Formula/folly.rb
  Formula/helm.rb
  Formula/hledger.rb
  Formula/ompl.rb
  Formula/phpstan.rb
  Formula/pyqt.rb
  Formula/seal.rb
  Formula/sip.rb
  Formula/snakemake.rb
  Formula/sshuttle.rb
  Formula/tox.rb
  Formula/twarc.rb
Labels: merge

#20511 Merge 2020-06-09 ffcb19e0b2
  Aliases/libcouchbase@3
  Formula/cgrep.rb
  Formula/dhall-bash.rb
  Formula/dhall-json.rb
  Formula/dhall-lsp-server.rb
  Formula/dhall-yaml.rb
  Formula/flawfinder.rb
  Formula/ivykis.rb
  Formula/jenkins.rb
  Formula/ktlint.rb
  Formula/libcouchbase.rb
  Formula/libcouchbase@2.rb
  Formula/mdds.rb
  Formula/pass.rb
  Formula/tomcat.rb
  Formula/txt2tags.rb
  Formula/wxmac.rb
Labels: merge

#20512 Merge 2020-06-09 da7af2b30b
  Formula/angband.rb
  Formula/awsume.rb
  Formula/bazelisk.rb
  Formula/bmake.rb
  Formula/cargo-c.rb
  Formula/chezmoi.rb
  Formula/circleci.rb
  Formula/conan.rb
  Formula/cpp-gsl.rb
  Formula/dlib.rb
  Formula/ethereum.rb
  Formula/fossil.rb
  Formula/gimme-aws-creds.rb
  Formula/mercurial.rb
  Formula/micronaut.rb
  Formula/notifiers.rb
  Formula/pdftk-java.rb
  Formula/progress.rb
  Formula/rav1e.rb
  Formula/spotbugs.rb
  Formula/statik.rb
  Formula/terragrunt.rb
  Formula/toot.rb
  Formula/unrar.rb
  Formula/verilator.rb
  Formula/vis.rb
  Formula/xmrig.rb
  Formula/znc.rb
Labels: merge

#20516 Merge 2020-06-10 abfb2efb19
  Formula/armadillo.rb
  Formula/aws-google-auth.rb
  Formula/awscurl.rb
  Formula/breezy.rb
  Formula/buku.rb
  Formula/c-blosc.rb
  Formula/cake.rb
  Formula/cargo-c.rb
  Formula/cassandra-cpp-driver.rb
  Formula/certbot.rb
  Formula/clinfo.rb
  Formula/conjure-up.rb
  Formula/credstash.rb
  Formula/emscripten.rb
  Formula/evince.rb
  Formula/fontconfig.rb
  Formula/gdb.rb
  Formula/gimme-aws-creds.rb
  Formula/git-trim.rb
  Formula/gitfs.rb
  Formula/gitless.rb
  Formula/gleam.rb
  Formula/haproxy.rb
  Formula/howard-hinnant-date.rb
  Formula/jlog.rb
  Formula/lanraragi.rb
  Formula/lastpass-cli.rb
  Formula/lerna.rb
  Formula/libopendkim.rb
  Formula/libzip.rb
  Formula/literate-git.rb
  Formula/magic-wormhole.rb
  Formula/poetry.rb
  Formula/redis.rb
  Formula/starship.rb
  Formula/vdirsyncer.rb
  Formula/xrootd.rb
Labels: merge

#20521 Merge 2020-06-10 df89017f1c
  Formula/cgal.rb
  Formula/coinutils.rb
  Formula/dolt.rb
  Formula/git-filter-repo.rb
  Formula/hashlink.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jc.rb
  Formula/khal.rb
  Formula/mdds.rb
  Formula/phpstan.rb
  Formula/urh.rb
Labels: merge

#20525 Merge 2020-06-11 69781173e9
  Formula/angular-cli.rb
  Formula/code-server.rb
  Formula/consul.rb
  Formula/contentful-cli.rb
  Formula/convox.rb
  Formula/flyway.rb
  Formula/fonttools.rb
  Formula/helm@2.rb
  Formula/nushell.rb
  Formula/pulumi.rb
  Formula/rclone.rb
  Formula/sphinx-doc.rb
  Formula/telegraf.rb
  Formula/zeek.rb
Labels: merge

#20526 Merge 2020-06-11 c13ea7ead1
  Formula/angle-grinder.rb
  Formula/ansible-lint.rb
  Formula/aria2.rb
  Formula/asuka.rb
  Formula/aws-elasticbeanstalk.rb
  Formula/aws-okta.rb
  Formula/awslogs.rb
  Formula/azure-cli.rb
  Formula/bic.rb
  Formula/borgmatic.rb
  Formula/cairo.rb
  Formula/cgal.rb
  Formula/charm-tools.rb
  Formula/cimg.rb
  Formula/cmake.rb
  Formula/code-server.rb
  Formula/crystal.rb
  Formula/curl.rb
  Formula/dbus.rb
  Formula/envchain.rb
  Formula/gmic.rb
  Formula/helmfile.rb
  Formula/mesa.rb
  Formula/packer.rb
  Formula/uni.rb
Labels: merge

#20530 Merge 2020-06-11 0f610676c8
  Formula/adplug.rb
  Formula/bgpdump.rb
  Formula/bluepill.rb
  Formula/cacli.rb
  Formula/dhall-bash.rb
  Formula/flake8.rb
  Formula/lazydocker.rb
  Formula/leakcanary-shark.rb
  Formula/mu.rb
  Formula/nave.rb
  Formula/ncdu.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/pnpm.rb
  Formula/polynote.rb
  Formula/prometheus.rb
  Formula/qscintilla2.rb
  Formula/r.rb
  Formula/rst-lint.rb
  Formula/sdb.rb
  Formula/semgrep.rb
  Formula/shadowenv.rb
  Formula/squid.rb
  Formula/stress-ng.rb
  Formula/swig.rb
  Formula/tengo.rb
  Formula/twoping.rb
  Formula/vulkan-headers.rb
  Formula/wpscan.rb
Labels: merge

#20532 Merge 2020-06-11 83be4f9cd6
  Formula/apache-spark.rb
  Formula/apollo-cli.rb
  Formula/audacious.rb
  Formula/balena-cli.rb
  Formula/bee.rb
  Formula/biosig.rb
  Formula/corral.rb
  Formula/dune.rb
  Formula/hexyl.rb
  Formula/hpack.rb
  Formula/igv.rb
  Formula/immudb.rb
  Formula/libcouchbase.rb
  Formula/libhttpserver.rb
  Formula/pwntools.rb
  Formula/tomcat@8.rb
  Formula/vpn-slice.rb
  Formula/wxmaxima.rb
Labels: merge

#20534 Merge 2020-06-11 7ea2bfbb8c
  Formula/assh.rb
  Formula/babl.rb
  Formula/benthos.rb
  Formula/carla.rb
  Formula/ffsend.rb
  Formula/fn.rb
  Formula/foma.rb
  Formula/freeradius-server.rb
  Formula/freeswitch.rb
  Formula/gatsby-cli.rb
  Formula/git.rb
  Formula/gobject-introspection.rb
  Formula/hadolint.rb
  Formula/haxe.rb
  Formula/hub.rb
  Formula/latexml.rb
  Formula/ldc.rb
  Formula/libgit2.rb
  Formula/libpcap.rb
  Formula/libpq.rb
  Formula/pre-commit.rb
Labels: merge

#20535 Merge 2020-06-12 fac7f45fcc
  Formula/adns.rb
  Formula/contentful-cli.rb
  Formula/deark.rb
  Formula/diffoscope.rb
  Formula/libolm.rb
  Formula/librealsense.rb
  Formula/openrtsp.rb
  Formula/pc6001vx.rb
  Formula/php.rb
  Formula/quicktype.rb
  Formula/sonobuoy.rb
  Formula/spirv-tools.rb
  Formula/tasksh.rb
  Formula/tealdeer.rb
  Formula/teleport.rb
  Formula/terragrunt.rb
  Formula/tippecanoe.rb
  Formula/topgrade.rb
  Formula/unpaper.rb
  Formula/vifm.rb
  Formula/vips.rb
  Formula/volatility.rb
  Formula/websocat.rb
  Formula/wildfly-as.rb
  Formula/wrk.rb
  Formula/wxpython.rb
  Formula/x3270.rb
  Formula/xapian.rb
  Formula/xmake.rb
  Formula/xrootd.rb
  Formula/yaegi.rb
  Formula/ykman.rb
  Formula/ykpers.rb
  Formula/yq.rb
  Formula/zola.rb
  Formula/zssh.rb
Labels: merge

#20536 Merge 2020-06-12 7973adf99e
  Formula/astrometry-net.rb
  Formula/blogc.rb
  Formula/cpl.rb
  Formula/dmagnetic.rb
  Formula/fblog.rb
  Formula/jlog.rb
  Formula/mask.rb
  Formula/maxwell.rb
  Formula/natalie.rb
  Formula/ocrmypdf.rb
  Formula/php@7.3.rb
  Formula/qt.rb
  Formula/qwtpolar.rb
  Formula/skaffold.rb
  Formula/stella.rb
  Formula/ultralist.rb
  Formula/wcslib.rb
  Formula/weaver.rb
  Formula/xsimd.rb
Labels: merge

#20541 Merge 2020-06-13 966ee397d09
  Formula/cassowary.rb
  Formula/chakra.rb
  Formula/devdash.rb
  Formula/dnscrypt-proxy.rb
  Formula/duckdb.rb
  Formula/evince.rb
  Formula/findomain.rb
  Formula/flow.rb
  Formula/helib.rb
  Formula/htmldoc.rb
  Formula/jc.rb
  Formula/liblqr.rb
  Formula/liquibase.rb
  Formula/menhir.rb
  Formula/mmctl.rb
  Formula/nodeenv.rb
  Formula/ocrmypdf.rb
  Formula/pgbouncer.rb
  Formula/pnpm.rb
  Formula/tty-solitaire.rb
  Formula/tup.rb
  Formula/whistle.rb
  Formula/yaz.rb
Labels: merge

#20542 Merge 2020-06-13 ff4e539c85e
  Formula/apollo-cli.rb
  Formula/ask-cli.rb
  Formula/balena-cli.rb
  Formula/click.rb
  Formula/diesel.rb
  Formula/docfx.rb
  Formula/glooctl.rb
  Formula/govc.rb
  Formula/libwebsockets.rb
  Formula/msgpack.rb
  Formula/newman.rb
  Formula/now-cli.rb
  Formula/terragrunt.rb
Labels: merge

#20543 xmake: fix test for Linuxbrew
  Formula/xmake.rb
Labels: test failure

#20544 adns: Fix build for Linuxbrew
  Formula/adns.rb
Labels: dependency

#20546 Merge 2020-06-13 b4e9e0642f8
  Formula/patchelf.rb
Labels: merge

#20547 Merge 2020-06-13 8137afb9170
  Formula/dmd.rb
  Formula/emscripten.rb
  Formula/google-benchmark.rb
  Formula/goreleaser.rb
  Formula/mpd.rb
  Formula/operator-sdk.rb
  Formula/rust-analyzer.rb
Labels: merge

#20549 google-benchmark: Fix test for Linuxbrew
  Formula/google-benchmark.rb
Labels: test failure

#20551 Merge 2020-06-14 7a86fed0b60
  Formula/bacula-fd.rb
  Formula/cppcheck.rb
  Formula/gitmoji.rb
  Formula/handbrake.rb
  Formula/idris2.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jrnl.rb
  Formula/kde-extra-cmake-modules.rb
  Formula/kde-threadweaver.rb
  Formula/liboqs.rb
  Formula/libzip.rb
  Formula/makepkg.rb
  Formula/nativefier.rb
  Formula/plantuml.rb
  Formula/qca.rb
  Formula/stgit.rb
  Formula/vcpkg.rb
  Formula/weighttp.rb
Labels: merge

#20553 Merge 2020-06-15 7a12c4e47ad
  Formula/benthos.rb
  Formula/binaryen.rb
  Formula/broot.rb
  Formula/calicoctl.rb
  Formula/clojure.rb
  Formula/exploitdb.rb
  Formula/freetds.rb
  Formula/git-filter-repo.rb
  Formula/inxi.rb
  Formula/jc.rb
  Formula/libgnt.rb
  Formula/mutt.rb
  Formula/phpstan.rb
  Formula/sphinx-doc.rb
  Formula/terragrunt.rb
  Formula/todoman.rb
  Formula/wtf.rb
  Formula/yq.rb
Labels: merge

#20554 Merge 2020-06-15 5b1fa959f9c
  Formula/aws-es-proxy.rb
  Formula/cglm.rb
  Formula/deno.rb
  Formula/eureka.rb
  Formula/fetchmail.rb
  Formula/file-formula.rb
  Formula/flarectl.rb
  Formula/flint.rb
  Formula/g3log.rb
  Formula/gleam.rb
  Formula/gotop.rb
  Formula/i386-elf-gdb.rb
  Formula/janet.rb
  Formula/jvgrep.rb
  Formula/katago.rb
  Formula/libplctag.rb
  Formula/math-comp.rb
  Formula/mdcat.rb
  Formula/mypy.rb
  Formula/paket.rb
  Formula/pc6001vx.rb
  Formula/pueue.rb
  Formula/sqliteodbc.rb
  Formula/swift-sh.rb
  Formula/tcpreplay.rb
  Formula/topgrade.rb
  Formula/xclogparser.rb
Labels: merge

#20555 gotop: fix test for Linuxbrew
  Formula/gotop.rb
Labels: test failure

#20558 Merge 2020-06-15 9761b23c1dc
  Formula/aws-google-auth.rb
  Formula/bcoin.rb
  Formula/c14-cli.rb
  Formula/cppman.rb
  Formula/folly.rb
  Formula/gitmoji.rb
  Formula/itk.rb
  Formula/knot-resolver.rb
  Formula/libvncserver.rb
  Formula/ott.rb
  Formula/paket.rb
  Formula/pcsc-lite.rb
  Formula/phpunit.rb
  Formula/picard-tools.rb
Labels: merge

#20559 Merge 2020-06-16 57bb8886529
  Formula/binwalk.rb
  Formula/buildifier.rb
  Formula/cdk8s.rb
  Formula/confluent-platform.rb
  Formula/contentful-cli.rb
  Formula/hcxtools.rb
  Formula/jfrog-cli.rb
  Formula/meson.rb
  Formula/netlify-cli.rb
  Formula/proteinortho.rb
  Formula/scdoc.rb
  Formula/v8.rb
  Formula/youtube-dl.rb
Labels: merge

#20560 Merge 2020-06-16 68980d5a770
  Formula/bison.rb
  Formula/buku.rb
  Formula/ed.rb
  Formula/helm.rb
  Formula/helmfile.rb
  Formula/ilmbase.rb
  Formula/istioctl.rb
  Formula/jetty-runner.rb
  Formula/jetty.rb
  Formula/latexdiff.rb
  Formula/openexr.rb
  Formula/rust-analyzer.rb
  Formula/vulkan-headers.rb
Labels: merge

#20562 Merge 2020-06-16 d89ca2b921f
  Aliases/ki18n
  Formula/ansiweather.rb
  Formula/asimov.rb
  Formula/chromaprint.rb
  Formula/dropbear.rb
  Formula/fava.rb
  Formula/ffmpeg.rb
  Formula/fpdns.rb
  Formula/git-interactive-rebase-tool.rb
  Formula/gitui.rb
  Formula/helmsman.rb
  Formula/inko.rb
  Formula/jabba.rb
  Formula/kde-ki18n.rb
  Formula/ktlint.rb
  Formula/libressl.rb
  Formula/ocrmypdf.rb
  Formula/opencv.rb
  Formula/opencv@2.rb
  Formula/opencv@3.rb
  Formula/percona-xtrabackup.rb
  Formula/redo.rb
  Formula/skopeo.rb
  Formula/sslyze.rb
  Formula/stone-soup.rb
  Formula/tmx.rb
  formula_renames.json
Labels: merge

#20571 Merge 2020-06-17 ba9f5242ddb
  Formula/asimov.rb
  Formula/balena-cli.rb
  Formula/black.rb
  Formula/boost-build.rb
  Formula/cfengine.rb
  Formula/closure-compiler.rb
  Formula/fava.rb
  Formula/fonttools.rb
  Formula/gegl.rb
  Formula/gupnp.rb
  Formula/helm@2.rb
  Formula/ideviceinstaller.rb
  Formula/ifuse.rb
  Formula/igv.rb
  Formula/ios-webkit-debug-proxy.rb
  Formula/ldid.rb
  Formula/libimobiledevice.rb
  Formula/libplist.rb
  Formula/libusbmuxd.rb
  Formula/little-cms2.rb
  Formula/neo4j.rb
  Formula/newrelic-cli.rb
  Formula/node_exporter.rb
  Formula/opa.rb
  Formula/pnpm.rb
  Formula/prestosql.rb
  Formula/robot-framework.rb
  Formula/s6.rb
  Formula/semgrep.rb
  Formula/snakemake.rb
Labels: merge

#20573 Merge 2020-06-17 d55a2f5a3be
  Aliases/karchive
  Formula/allureofthestars.rb
  Formula/awscli.rb
  Formula/bc.rb
  Formula/biosig.rb
  Formula/cocoapods.rb
  Formula/emacs.rb
  Formula/exa.rb
  Formula/freetds.rb
  Formula/git-cola.rb
  Formula/guile.rb
  Formula/haskell-stack.rb
  Formula/istioctl.rb
  Formula/jrnl.rb
  Formula/kde-karchive.rb
  Formula/kubernetes-cli.rb
  Formula/link-grammar.rb
  Formula/logtalk.rb
  Formula/lv.rb
  Formula/mpv.rb
  Formula/now-cli.rb
  Formula/ntfs-3g.rb
  Formula/pyenv.rb
  Formula/ruby.rb
  Formula/sdl2_ttf.rb
  Formula/swift-format.rb
  Formula/taskell.rb
  Formula/tre-command.rb
  Formula/xcodegen.rb
Labels: merge

#20574 Merge 2020-06-18 e65dabac769
  Formula/angular-cli.rb
  Formula/apache-spark.rb
  Formula/asciidoctorj.rb
  Formula/bazel.rb
  Formula/bind.rb
  Formula/circleci.rb
  Formula/citus.rb
  Formula/cloud-nuke.rb
  Formula/contentful-cli.rb
  Formula/convox.rb
  Formula/dependency-check.rb
  Formula/efl.rb
  Formula/ffmpeg.rb
  Formula/firebase-cli.rb
  Formula/fx.rb
  Formula/gatsby-cli.rb
  Formula/kubernetes-cli.rb
  Formula/nim.rb
  Formula/node@12.rb
  Formula/nss.rb
  Formula/onnxruntime.rb
  Formula/pnpm.rb
  Formula/puzzles.rb
  Formula/rethinkdb.rb
  Formula/salt.rb
  Formula/scummvm.rb
  Formula/seal.rb
  Formula/serverless.rb
  Formula/sshuttle.rb
  Formula/stress-ng.rb
  Formula/twoping.rb
  Formula/vcpkg.rb
  Formula/volta.rb
  Formula/xclogparser.rb
  Formula/zlog.rb
Labels: merge

#20576 Merge 2020-06-18 811984539e9
  Formula/sync_gateway.rb
Labels: merge

#20577 Merge 2020-06-19 14beeb3b2ed
  Formula/bnd.rb
  Formula/gdal.rb
  Formula/gmt.rb
  Formula/gmt@5.rb
  Formula/jenkins-lts.rb
  Formula/jenkins.rb
  Formula/liblas.rb
  Formula/mapnik.rb
  Formula/mapserver.rb
  Formula/pdal.rb
  Formula/points2grid.rb
  Formula/postgis.rb
  Formula/simple-tiles.rb
  Formula/vim.rb
  Formula/yaegi.rb
Labels: merge

#20578 Merge 2020-06-20 ccf78cdf324
  Formula/agedu.rb
  Formula/auditbeat.rb
  Formula/carthage.rb
  Formula/dbhash.rb
  Formula/desktop-file-utils.rb
  Formula/evince.rb
  Formula/exploitdb.rb
  Formula/gluon.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/grakn.rb
  Formula/helm.rb
  Formula/istioctl.rb
  Formula/just.rb
  Formula/micro.rb
  Formula/mutt.rb
  Formula/octave.rb
  Formula/pcl.rb
  Formula/pnpm.rb
  Formula/premake.rb
  Formula/qhull.rb
  Formula/sn0int.rb
  Formula/sqldiff.rb
  Formula/sqlite-analyzer.rb
  Formula/unar.rb
  Formula/visp.rb
  Formula/vlang.rb
  Formula/weaver.rb
Labels: merge

#20579 Merge 2020-06-20 be6a6e4adf8
  Formula/allure.rb
  Formula/ansible.rb
  Formula/awscli.rb
  Formula/cfn-lint.rb
  Formula/devspace.rb
  Formula/eslint.rb
  Formula/exploitdb.rb
  Formula/filebeat.rb
  Formula/heartbeat.rb
  Formula/httpie.rb
  Formula/janet.rb
  Formula/libphonenumber.rb
  Formula/libtorch.rb
  Formula/mockolo.rb
  Formula/packetbeat.rb
  Formula/skopeo.rb
  Formula/toot.rb
Labels: merge

#20580 Merge 2020-06-20 bc88931c115
  Formula/alpine.rb
  Formula/berglas.rb
  Formula/calicoctl.rb
  Formula/chapel.rb
  Formula/crystal.rb
  Formula/deno.rb
  Formula/fdroidserver.rb
  Formula/gatsby-cli.rb
  Formula/git-annex.rb
  Formula/gor.rb
  Formula/libgweather.rb
  Formula/mdcat.rb
  Formula/neomutt.rb
  Formula/openstackclient.rb
  Formula/perltidy.rb
  Formula/robotfindskitten.rb
  Formula/ship.rb
  Formula/swiftgen.rb
Labels: merge

#20581 Merge 2020-06-20 e337444f113
  .github/workflows/scheduled.yml
  Formula/babel.rb
  Formula/dhall.rb
  Formula/diffoscope.rb
  Formula/dvc.rb
  Formula/gitlab-runner.rb
  Formula/haxe.rb
  Formula/hlint.rb
  Formula/ipfs.rb
  Formula/juju.rb
  Formula/rancher-cli.rb
  Formula/rke.rb
Labels: merge

#20592 Merge 2020-06-21 9097beb3f26
  Formula/aliyun-cli.rb
  Formula/aws-cdk.rb
  Formula/awscli@1.rb
  Formula/bde.rb
  Formula/broot.rb
  Formula/cbmc.rb
  Formula/clojure-lsp.rb
  Formula/desktop-file-utils.rb
  Formula/doctest.rb
  Formula/gatsby-cli.rb
  Formula/genometools.rb
  Formula/harfbuzz.rb
  Formula/hasura-cli.rb
  Formula/libwebsockets.rb
  Formula/mavsdk.rb
  Formula/menhir.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/plantuml.rb
  Formula/pnpm.rb
  Formula/prometheus.rb
  Formula/sentencepiece.rb
  Formula/spotbugs.rb
  Formula/switch-lan-play.rb
  Formula/topgrade.rb
  Formula/watchexec.rb
  Formula/wslay.rb
  Formula/yle-dl.rb
Labels: merge

#20594 Merge 2020-06-21 c01f85884ad
  Formula/amp.rb
  Formula/consul.rb
  Formula/ghq.rb
  Formula/idris2.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/nest.rb
  Formula/ntfs-3g.rb
  Formula/phpstan.rb
  Formula/phpunit.rb
  Formula/sentencepiece.rb
Labels: merge

#20595 Merge 2020-06-21 b9632323074
  Formula/abcm2ps.rb
  Formula/balena-cli.rb
  Formula/fuse-zip.rb
  Formula/gpac.rb
  Formula/lynis.rb
  Formula/open-image-denoise.rb
  Formula/openblas.rb
  Formula/opendetex.rb
  Formula/percona-xtrabackup.rb
  Formula/proteinortho.rb
  Formula/sparse.rb
  Formula/tcping.rb
Labels: merge

#20600 Merge 2020-06-21 424b71c2301
  Formula/a2ps.rb
  Formula/algol68g.rb
  Formula/awscli.rb
  Formula/check.rb
  Formula/faiss.rb
  Formula/gdk-pixbuf.rb
  Formula/gegl.rb
  Formula/gitui.rb
  Formula/gl2ps.rb
  Formula/glib-networking.rb
  Formula/global.rb
  Formula/gnutls.rb
  Formula/igraph.rb
  Formula/ispell.rb
  Formula/kettle.rb
  Formula/libass.rb
  Formula/libsoup.rb
  Formula/mariadb-connector-c.rb
  Formula/pwncat.rb
Labels: merge

#20604 Merge 2020-06-22 9b4f1a71431
  Formula/aardvark_shell_utils.rb
  Formula/alot.rb
  Formula/cgns.rb
  Formula/check.rb
  Formula/contentful-cli.rb
  Formula/coreutils.rb
  Formula/corsixth.rb
  Formula/dav1d.rb
  Formula/diamond.rb
  Formula/dvc.rb
  Formula/git-extras.rb
  Formula/hledger.rb
  Formula/javacc.rb
  Formula/katago.rb
  Formula/keystone.rb
  Formula/libpulsar.rb
  Formula/librdkafka.rb
  Formula/logstash.rb
  Formula/mesa.rb
  Formula/perkeep.rb
  Formula/plank.rb
  Formula/rsync.rb
  Formula/scipy.rb
  Formula/tnftp.rb
  Formula/truncate.rb
  Formula/wabt.rb
  Formula/whistle.rb
Labels: merge

#20605 tnftp: Fix build for Linuxbrew
  Formula/tnftp.rb
Labels: dependency

#20606 check: Fix build for Linuxbrew
  Formula/check.rb
Labels: dependency

#20607 Merge 2020-06-22 7c8471f9ed0
  Formula/balena-cli.rb
  Formula/diamond.rb
  Formula/duckdb.rb
  Formula/gatsby-cli.rb
  Formula/glassfish.rb
  Formula/graphene.rb
  Formula/gst-plugins-bad.rb
  Formula/guile.rb
  Formula/harfbuzz.rb
  Formula/haskell-stack.rb
  Formula/hcloud.rb
  Formula/libtcod.rb
  Formula/macos-trash.rb
  Formula/nest.rb
  Formula/onednn.rb
  Formula/phpunit.rb
  Formula/pnpm.rb
  Formula/tnftp.rb
  Formula/trash-cli.rb
  Formula/trash.rb
  Formula/wallpaper.rb
  formula_renames.json
Labels: merge

#20612 Merge 2020-06-23 42d8f03d7e8
  Aliases/kdoctools
  Formula/acmetool.rb
  Formula/apr-util.rb
  Formula/asciidoc.rb
  Formula/bnfc.rb
  Formula/consul.rb
  Formula/coq.rb
  Formula/crosstool-ng.rb
  Formula/davix.rb
  Formula/go.rb
  Formula/go@1.10.rb
  Formula/go@1.11.rb
  Formula/go@1.12.rb
  Formula/go@1.13.rb
  Formula/go@1.9.rb
  Formula/kde-kdoctools.rb
Labels: merge

#20614 Merge 2020-06-23 977d6327963
  Aliases/numpy@1.19
  Formula/citus.rb
  Formula/cpr.rb
  Formula/epubcheck.rb
  Formula/erlang@22.rb
  Formula/fpc.rb
  Formula/freerdp.rb
  Formula/jc.rb
  Formula/neon.rb
  Formula/numpy.rb
  Formula/ode.rb
  Formula/okteto.rb
  Formula/open-tyrian.rb
  Formula/pdftk-java.rb
  Formula/pnpm.rb
  Formula/rubberband.rb
  Formula/swiftformat.rb
  Formula/switch-lan-play.rb
  Formula/tgui.rb
  Formula/tnftpd.rb
  Formula/tokei.rb
Labels: merge

#20616 Merge 2020-06-23 fc2e6f01027
  Formula/abcmidi.rb
  Formula/azure-cli.rb
  Formula/ccache.rb
  Formula/contentful-cli.rb
  Formula/dvc.rb
  Formula/dvm.rb
  Formula/eslint.rb
  Formula/grpc.rb
  Formula/json-fortran.rb
  Formula/jupyterlab.rb
  Formula/libtorrent-rasterbar.rb
  Formula/mlton.rb
  Formula/moarvm.rb
  Formula/node-sass.rb
  Formula/nqp.rb
  Formula/paket.rb
  Formula/questdb.rb
  Formula/r.rb
  Formula/rakudo.rb
  Formula/rsync.rb
  Formula/sync_gateway.rb
  Formula/talisman.rb
  Formula/tomee-plume.rb
  Formula/tomee-plus.rb
  Formula/tomee-webprofile.rb
  Formula/translate-toolkit.rb
  Formula/vulkan-headers.rb
  Formula/webdis.rb
Labels: merge

#20618 PATCHELF_RB env for test-bot
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/tests.yml
Labels: do not merge

#20619 Merge 2020-06-24 e4c3d88869a
  Aliases/perl@5.32
  Formula/direnv.rb
  Formula/git-extras.rb
  Formula/gssdp.rb
  Formula/gupnp.rb
  Formula/lanraragi.rb
  Formula/perl.rb
  Formula/subversion.rb
  Formula/terraform.rb
  Formula/vim.rb
  Formula/weechat.rb
Labels: merge

#20620 Merge 2020-06-24 864ffd01ef6
  Formula/aliyun-cli.rb
  Formula/apache-archiva.rb
  Formula/atlantis.rb
  Formula/balena-cli.rb
  Formula/bundletool.rb
  Formula/carton.rb
  Formula/conan.rb
  Formula/coredns.rb
  Formula/cucumber-ruby.rb
  Formula/epubcheck.rb
  Formula/exploitdb.rb
  Formula/fortio.rb
  Formula/gatsby-cli.rb
  Formula/gluon.rb
  Formula/heksa.rb
  Formula/hugo.rb
  Formula/igv.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/linkerd.rb
  Formula/lmod.rb
  Formula/mafft.rb
  Formula/man-db.rb
  Formula/mp3fs.rb
  Formula/ngircd.rb
  Formula/ocrmypdf.rb
  Formula/parallel.rb
  Formula/pdf2json.rb
  Formula/picard-tools.rb
  Formula/popt.rb
  Formula/pwntools.rb
  Formula/spotbugs.rb
  Formula/terragrunt.rb
  Formula/zurl.rb
Labels: merge

#20622 Merge 2020-06-24 71c0eb5b2ae
  Formula/awscli.rb
  Formula/broot.rb
  Formula/buildifier.rb
  Formula/cfengine.rb
  Formula/consul.rb
  Formula/dafny.rb
  Formula/dolt.rb
  Formula/flank.rb
  Formula/freetype.rb
  Formula/glooctl.rb
  Formula/jenkins.rb
  Formula/jpeg-turbo.rb
  Formula/lesstif.rb
  Formula/mdbook.rb
  Formula/nanopb-generator.rb
  Formula/popt.rb
  Formula/sn0int.rb
  Formula/superlu.rb
  Formula/terraformer.rb
Labels: merge

#20624 Merge 2020-06-25 7ed3272db33
  Formula/balena-cli.rb
  Formula/curl-openssl.rb
  Formula/curl.rb
  Formula/doitlive.rb
  Formula/gatsby-cli.rb
  Formula/gh.rb
  Formula/gmsh.rb
  Formula/helm.rb
  Formula/helm@2.rb
  Formula/libtool.rb
  Formula/root.rb
  Formula/semgrep.rb
  Formula/tcptrace.rb
  Formula/tektoncd-cli.rb
  Formula/twine-pypi.rb
Labels: merge

#20626 Merge 2020-06-25 dba60822e34
  Formula/abcl.rb
  Formula/angular-cli.rb
  Formula/composer.rb
  Formula/cpm.rb
  Formula/dvc.rb
  Formula/exploitdb.rb
  Formula/hlint.rb
  Formula/internetarchive.rb
  Formula/ipython.rb
  Formula/lean-cli.rb
  Formula/libpqxx.rb
  Formula/libpqxx@6.rb
  Formula/micro.rb
  Formula/mutt.rb
  Formula/nats-streaming-server.rb
  Formula/ngircd.rb
  Formula/nspr.rb
  Formula/phpstan.rb
  Formula/rclone.rb
  Formula/source-to-image.rb
  Formula/terraform.rb
  Formula/terrahub.rb
  Formula/vim.rb
Labels: merge

#20628 Merge 2020-06-25 64d0b4f8aaf
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  Formula/acmetool.rb
  Formula/annie.rb
  Formula/anycable-go.rb
  Formula/apr.rb
  Formula/ask-cli.rb
  Formula/aws-cdk.rb
  Formula/balena-cli.rb
  Formula/cfn-lint.rb
  Formula/cjdns.rb
  Formula/clojure-lsp.rb
  Formula/convox.rb
  Formula/csound.rb
  Formula/exempi.rb
  Formula/fdroidserver.rb
  Formula/git-hooks.rb
  Formula/gpx.rb
  Formula/grafana.rb
  Formula/hbase.rb
  Formula/instalooter.rb
  Formula/jdupes.rb
  Formula/jobber.rb
  Formula/libav.rb
  Formula/libnice.rb
  Formula/libvpx.rb
  Formula/meilisearch.rb
  Formula/mesa.rb
  Formula/micronaut.rb
  Formula/movgrab.rb
  Formula/msgpack.rb
  Formula/osqp.rb
  Formula/profanity.rb
  Formula/pulumi.rb
  Formula/rgbds.rb
  Formula/term.rb
  Formula/terraform.rb
  Formula/topgrade.rb
  Formula/twtxt.rb
  Formula/ucl.rb
  Formula/xxhash.rb
Labels: merge

#20629 Merge 2020-06-26 d8af23e0bc4
  Formula/arduino-cli.rb
  Formula/ask-cli.rb
  Formula/chezmoi.rb
  Formula/chocolate-doom.rb
  Formula/docker-completion.rb
  Formula/docker.rb
  Formula/ejdb.rb
  Formula/elasticsearch@2.4.rb
  Formula/elasticsearch@5.6.rb
  Formula/embree.rb
  Formula/exploitdb.rb
  Formula/go@1.10.rb
  Formula/go@1.11.rb
  Formula/go@1.12.rb
  Formula/go@1.9.rb
  Formula/gradio.rb
  Formula/guile.rb
  Formula/jc.rb
  Formula/kibana@5.6.rb
  Formula/menhir.rb
  Formula/mypy.rb
  Formula/ntp.rb
  Formula/operator-sdk.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
  Formula/postgresql@9.4.rb
  Formula/skaffold.rb
  Formula/terragrunt.rb
  Formula/tokei.rb
  Formula/unyaffs.rb
  Formula/zoxide.rb
Labels: merge

#20630 Merge 2020-06-26 c8f467f73a9
  Formula/awscli.rb
  Formula/balena-cli.rb
  Formula/bench.rb
  Formula/cheat.rb
  Formula/choose-gui.rb
  Formula/choose-rust.rb
  Formula/choose.rb
  Formula/code-server.rb
  Formula/contentful-cli.rb
  Formula/dbmate.rb
  Formula/diesel.rb
  Formula/ghq.rb
  Formula/highlighting-kate.rb
  Formula/libcouchbase@2.rb
  Formula/libqalculate.rb
  Formula/mariadb-connector-c.rb
  Formula/mighttpd2.rb
  Formula/networkit.rb
  Formula/node_exporter.rb
  Formula/oq.rb
  Formula/pngquant.rb
  Formula/qalculate-gtk.rb
  Formula/s2n.rb
  Formula/scala.rb
  Formula/sonic.rb
  Formula/yara.rb
Labels: merge

#20632 Merge 2020-06-27 c7104ffa808
  Formula/abcmidi.rb
  Formula/asciidoc.rb
  Formula/biosig.rb
  Formula/broot.rb
  Formula/caddy.rb
  Formula/cake.rb
  Formula/charm-tools.rb
  Formula/deno.rb
  Formula/diffoscope.rb
  Formula/eccodes.rb
  Formula/giter8.rb
  Formula/graph-tool.rb
  Formula/gtksourceview4.rb
  Formula/jobber.rb
  Formula/monero.rb
  Formula/neomutt.rb
  Formula/nss.rb
  Formula/okteto.rb
  Formula/openrtsp.rb
  Formula/prometheus.rb
  Formula/python@3.8.rb
  Formula/serverless.rb
  Formula/starship.rb
  Formula/vcs.rb
Labels: merge

#20634 Merge 2020-06-27 d8a396173e6
  Formula/b2sum.rb
  Formula/balena-cli.rb
  Formula/choose-rust.rb
  Formula/confuse.rb
  Formula/detekt.rb
  Formula/doctest.rb
  Formula/dropbear.rb
  Formula/flow.rb
  Formula/helmfile.rb
  Formula/imagemagick@6.rb
  Formula/javacc.rb
  Formula/kubernetes-cli.rb
  Formula/lizard-analyzer.rb
  Formula/mame.rb
  Formula/minio-mc.rb
  Formula/pmd.rb
  Formula/pwntools.rb
  Formula/sqliteodbc.rb
  Formula/tflint.rb
  Formula/tox.rb
Labels: merge

#20635 confuse: fix bottling for Linuxbrew
  Formula/confuse.rb
Labels: cellar failure

#20637 Merge 2020-06-28 71eff3ad6c0
  Formula/algernon.rb
  Formula/b2-tools.rb
  Formula/confluent-platform.rb
  Formula/dlib.rb
  Formula/duck.rb
  Formula/dvc.rb
  Formula/exim.rb
  Formula/flyway.rb
  Formula/git-revise.rb
  Formula/imagemagick.rb
  Formula/languagetool.rb
  Formula/libdrawtext.rb
  Formula/libebml.rb
  Formula/liblwgeom.rb
  Formula/libmagic.rb
  Formula/libmatroska.rb
  Formula/lmod.rb
  Formula/mkvtoolnix.rb
  Formula/neo4j.rb
  Formula/nuget.rb
  Formula/php-cs-fixer.rb
  Formula/pwntools.rb
  Formula/questdb.rb
  Formula/shfmt.rb
  Formula/sk.rb
  Formula/sonar-scanner.rb
  Formula/sonic.rb
  Formula/stella.rb
  Formula/storm.rb
  Formula/trafficserver.rb
  Formula/ttyd.rb
  Formula/xmake.rb
Labels: merge

#20640 Merge 2020-06-29 bd96b4d69f4
  Formula/alluxio.rb
  Formula/amp.rb
  Formula/angle-grinder.rb
  Formula/asuka.rb
  Formula/badtouch.rb
  Formula/bandwhich.rb
  Formula/bat.rb
  Formula/bingrep.rb
  Formula/boringtun.rb
  Formula/broot.rb
  Formula/cargo-c.rb
  Formula/cargo-instruments.rb
  Formula/click.rb
  Formula/cmdshelf.rb
  Formula/cobalt.rb
  Formula/diffr.rb
  Formula/diskus.rb
  Formula/dust.rb
  Formula/eureka.rb
  Formula/eva.rb
  Formula/fastmod.rb
  Formula/fblog.rb
  Formula/fd.rb
  Formula/ffsend.rb
  Formula/findomain.rb
  Formula/fselect.rb
  Formula/geckodriver.rb
  Formula/genact.rb
  Formula/gifski.rb
  Formula/git-absorb.rb
  Formula/git-delta.rb
  Formula/git-interactive-rebase-tool.rb
  Formula/git-trim.rb
  Formula/netdata.rb
  Formula/rustup-init.rb
  Formula/sccache.rb
  Formula/spotifyd.rb
  Formula/tokei.rb
Labels: merge

#20642 Merge 2020-06-29 a6e84844b38
  Formula/baobab.rb
  Formula/benthos.rb
  Formula/blast.rb
  Formula/breezy.rb
  Formula/broot.rb
  Formula/checkstyle.rb
  Formula/git-quick-stats.rb
  Formula/igv.rb
  Formula/javacc.rb
  Formula/jhipster.rb
  Formula/l-smash.rb
  Formula/libfreefare.rb
  Formula/libnfc.rb
  Formula/libosmium.rb
  Formula/libserdes.rb
  Formula/mfcuk.rb
  Formula/mfoc.rb
  Formula/mfterm.rb
  Formula/minizip2.rb
  Formula/mkvtoolnix.rb
  Formula/muparser.rb
  Formula/netpbm.rb
  Formula/nfcutils.rb
  Formula/nim.rb
  Formula/nlohmann-json.rb
  Formula/oauth2_proxy.rb
  Formula/paket.rb
  Formula/pcb2gcode.rb
  Formula/plantuml.rb
  Formula/po4a.rb
  Formula/ppsspp.rb
  Formula/putty.rb
  Formula/rgf.rb
  Formula/sjk.rb
  Formula/tvnamer.rb
  Formula/vlang.rb
  Formula/yle-dl.rb
  Formula/zim.rb
Labels: merge

#20644 Merge 2020-06-30 6b743558b81
  Formula/bagit.rb
  Formula/borgmatic.rb
  Formula/contentful-cli.rb
  Formula/crowdin.rb
  Formula/dpkg.rb
  Formula/just.rb
  Formula/nasm.rb
  Formula/needle.rb
  Formula/osmium-tool.rb
  Formula/pandoc-citeproc.rb
  Formula/pdfcpu.rb
  Formula/protoc-gen-grpc-web.rb
  Formula/rsyslog.rb
  Formula/sslyze.rb
  Formula/twarc.rb
  Formula/uptoc.rb
  Formula/vsearch.rb
Labels: merge

#20646 Merge 2020-06-30 4501ee0d440
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20647 Merge 2020-06-30 37fd6371d9e
  Formula/bit.rb
  Formula/broot.rb
  Formula/cdk8s.rb
  Formula/checkbashisms.rb
  Formula/cypher-shell.rb
  Formula/dcos-cli.rb
  Formula/folly.rb
  Formula/get_iplayer.rb
  Formula/groonga.rb
  Formula/grpcui.rb
  Formula/kitchen-sync.rb
  Formula/monit.rb
  Formula/terragrunt.rb
  Formula/yaegi.rb
Labels: merge

#20649 Merge 2020-06-30 102f98b0cd7
  .github/workflows/tests.yml
Labels: merge

#20650 Merge 2020-06-30 e94f8632d17
  Formula/bitwarden-cli.rb
  Formula/catch2.rb
  Formula/circleci.rb
  Formula/clojure-lsp.rb
  Formula/cubelib.rb
  Formula/dolt.rb
  Formula/dpkg.rb
  Formula/duktape.rb
  Formula/faas-cli.rb
  Formula/fplll.rb
  Formula/gatsby-cli.rb
  Formula/gdal.rb
  Formula/h3.rb
  Formula/jam.rb
  Formula/lablgtk.rb
  Formula/liblzf.rb
  Formula/metaproxy.rb
  Formula/sbcl.rb
  Formula/serverless.rb
  Formula/sfcgal.rb
  Formula/skylighting.rb
  Formula/unrar.rb
  Formula/vapor.rb
  Formula/volta.rb
  Formula/wren.rb
Labels: merge

#20651 Merge 2020-06-30 94f4467b333
  Formula/abcmidi.rb
  Formula/avro-c.rb
  Formula/avro-cpp.rb
  Formula/avro-tools.rb
  Formula/berglas.rb
  Formula/ghq.rb
  Formula/spirv-cross.rb
  Formula/tox.rb
Labels: merge

#20652 Merge 2020-06-30 1a6e990611b
  Formula/awsume.rb
  Formula/bench.rb
  Formula/jerryscript.rb
  Formula/latexindent.rb
  Formula/roswell.rb
  Formula/statik.rb
Labels: merge
