Repository Homebrew/linuxbrew-core, pull requests merged in 2020-02, with the labels that each got.

#19407 Merge 2020-02-01 2562e3c605
  Formula/clp.rb
  Formula/coffeescript.rb
  Formula/cppman.rb
  Formula/libraqm.rb
  Formula/octant.rb
  Formula/osquery.rb
  Formula/rocksdb.rb
  Formula/roswell.rb
  Formula/rsyslog.rb
  Formula/sentencepiece.rb
  Formula/skaffold.rb
  Formula/urdfdom.rb
  Formula/wiremock-standalone.rb
  Formula/zabbix.rb
Labels: merge

#19416 Merge 2020-02-01 e240db108d
  Formula/cheat.rb
  Formula/cmt.rb
  Formula/diffstat.rb
  Formula/digdag.rb
  Formula/dnscrypt-proxy.rb
  Formula/exploitdb.rb
  Formula/gifski.rb
  Formula/gitmoji.rb
  Formula/glfw.rb
  Formula/hadolint.rb
  Formula/helib.rb
  Formula/k3d.rb
  Formula/keydb.rb
  Formula/lablgtk.rb
  Formula/libheif.rb
  Formula/mkl-dnn.rb
  Formula/mockserver.rb
  Formula/p11-kit.rb
  Formula/par.rb
  Formula/poetry.rb
  Formula/rclone.rb
  Formula/snapcraft.rb
  Formula/sqlmap.rb
  Formula/tika.rb
  Formula/vagrant-completion.rb
  Formula/xcodegen.rb
Labels: merge

#19428 Merge 2020-02-02 dd8ed3def4
  Formula/binutils.rb
  Formula/psc-package.rb
Labels: merge

#19430 Merge 2020-02-02 6c5dce50a3
  Formula/b3sum.rb
  Formula/cake.rb
  Formula/csound.rb
  Formula/get_iplayer.rb
  Formula/gitleaks.rb
  Formula/insect.rb
  Formula/libtensorflow@1.rb
  Formula/lighttpd.rb
Labels: merge

#19438 Merge 2020-02-02 ac55cfcabc
  Formula/anime-downloader.rb
  Formula/euler-py.rb
  Formula/gatsby-cli.rb
  Formula/git-plus.rb
  Formula/gnutls.rb
  Formula/joplin.rb
  Formula/lazydocker.rb
  Formula/libtasn1.rb
  Formula/nspr.rb
  Formula/pdftk-java.rb
  Formula/rust.rb
  Formula/xcodegen.rb
Labels: merge

#19447 Merge 2020-02-03 31b1f059e7
  Formula/argyll-cms.rb
  Formula/bit.rb
  Formula/cassandra.rb
  Formula/cheat.rb
  Formula/dvc.rb
  Formula/ffuf.rb
  Formula/janet.rb
  Formula/libomp.rb
  Formula/libvirt.rb
  Formula/mame.rb
  Formula/netlify-cli.rb
  Formula/rawtoaces.rb
Labels: merge

#19151 znc: fix znc-buildmod
  Formula/znc.rb
Labels: bottle, do not merge

#19461 Merge 2020-02-03 9e66b9e8d4
  Formula/alot.rb
  Formula/diamond.rb
  Formula/hlint.rb
  Formula/swiftformat.rb
Labels: merge

#19465 Merge 2020-02-04 00970d05a7
  Formula/dbhash.rb
  Formula/sqldiff.rb
  Formula/sqlite-analyzer.rb
  Formula/sqlite.rb
Labels: merge

#19468 Merge 2020-02-04 f2ccfde294
  Formula/dbhash.rb
  Formula/gitless.rb
  Formula/memcached.rb
  Formula/ponyc.rb
  Formula/sqldiff.rb
Labels: merge

#19472 Merge 2020-02-04 0a39741425
  Formula/ocrmypdf.rb
  Formula/remind.rb
  Formula/s-nail.rb
Labels: merge

#19474 Merge 2020-02-04 ef5fc2402c
  Formula/annie.rb
  Formula/azure-cli.rb
  Formula/deno.rb
  Formula/django-completion.rb
  Formula/docker-compose-completion.rb
  Formula/docker-compose.rb
  Formula/fonttools.rb
  Formula/fstar.rb
  Formula/helmfile.rb
  Formula/helmsman.rb
  Formula/lazygit.rb
  Formula/libzip.rb
  Formula/molten-vk.rb
  Formula/mongo-c-driver.rb
  Formula/nng.rb
  Formula/ocaml.rb
  Formula/radare2.rb
  Formula/rom-tools.rb
  Formula/sbt.rb
  Formula/taskell.rb
  Formula/termshark.rb
  Formula/terraform-docs.rb
  Formula/tintin.rb
  Formula/vim.rb
  cmd/aspell-dictionaries.rb
  cmd/brew-aspell-dictionaries.rb
  cmd/brew-postgresql-upgrade-database.rb
  cmd/postgresql-upgrade-database.rb
Labels: merge

#18710 pstoedit: Build a bottle for Linux
  Formula/pstoedit.rb
Labels: bottle, build failure

#19476 libzip: fix build for Linuxbrew
  Formula/libzip.rb
Labels: bottle, dependency

#19480 Merge 2020-02-05 006ff7f2a2
  Formula/cfn-lint.rb
  Formula/clp.rb
  Formula/gitmoji.rb
  Formula/paket.rb
  Formula/ungit.rb
Labels: merge

#19481 Merge 2020-02-05 357d0a7a50
  Formula/coinutils.rb
  Formula/composer.rb
  Formula/erlang.rb
  Formula/erlang@21.rb
  Formula/hugo.rb
  Formula/protobuf.rb
  Formula/rubyfmt.rb
  Formula/starship.rb
  Formula/syncthing.rb
Labels: merge

#19485 Merge 2020-02-05 467bd69a9b
  Formula/mercurial.rb
  Formula/profanity.rb
  Formula/util-linux.rb
  Formula/whistle.rb
Labels: merge

#19487 Merge 2020-02-05 1f3628b8fe
  Formula/xmrig.rb
Labels: merge

#19488 Merge 2020-02-05 4b884b7277
  Formula/doctl.rb
Labels: merge

#19489 Merge 2020-02-05 0539a0154a
  Formula/movgrab.rb
  Formula/wxmaxima.rb
  Formula/zint.rb
Labels: merge

#19490 Merge 2020-02-05 9606393825
  Formula/exploitdb.rb
  Formula/geoserver.rb
  Formula/git-annex.rb
  Formula/grex.rb
  Formula/micronaut.rb
  Formula/nifi.rb
  Formula/tektoncd-cli.rb
Labels: merge

#19491 Merge 2020-02-05 3ad507a58e
  Formula/frps.rb
Labels: merge

#19492 Merge 2020-02-05 6009f8ccab
  Formula/frpc.rb
Labels: merge

#19493 Merge 2020-02-05 970e00172e
  Formula/inlets.rb
Labels: merge

#19494 Merge 2020-02-05 66a7e8c668
  Formula/moarvm.rb
  Formula/nqp.rb
  Formula/rakudo.rb
Labels: merge

#19495 Merge 2020-02-05 445e92a03d
  Formula/mmctl.rb
  Formula/poco.rb
Labels: merge

#19496 Merge 2020-02-05 233bf7a953
  Formula/csvq.rb
  Formula/mono.rb
Labels: merge

#19497 Merge 2020-02-05 7696aa9b93
  Formula/varnish.rb
Labels: merge

#19499 Merge 2020-02-05 10f18a6bcb
  Formula/openjdk.rb
  Formula/openjdk@11.rb
  Formula/openjdk@12.rb
Labels: merge

#19500 Merge 2020-02-05 73cdcbb21d
  Formula/borgmatic.rb
Labels: merge

#19501 Merge 2020-02-05 efda583d0e
  Formula/krew.rb
Labels: merge

#19502 Merge 2020-02-05 a2d256d68d
  Formula/awscli.rb
  Formula/git-annex-remote-rclone.rb
  Formula/luaradio.rb
  Formula/phpstan.rb
  Formula/tdlib.rb
Labels: merge

#19507 Merge 2020-02-06 159656c422
  Aliases/v8@8.0
  Formula/activemq.rb
  Formula/allure.rb
  Formula/ammonite-repl.rb
  Formula/ant.rb
  Formula/antlr.rb
  Formula/antlr@2.rb
  Formula/apache-archiva.rb
  Formula/artifactory.rb
  Formula/kcptun.rb
  Formula/node-build.rb
  Formula/pioneer.rb
  Formula/v8.rb
Labels: merge

#19509 Merge 2020-02-06 f104d39ef9
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
Labels: merge

#19510 Merge 2020-02-06 33438e62f4
  Formula/findomain.rb
  Formula/yarn.rb
Labels: merge

#19511 Merge 2020-02-06 e202f57f79
  Formula/legit.rb
  Formula/pdfcpu.rb
Labels: merge

#19512 Merge 2020-02-06 82d0cc212e
  Formula/exploitdb.rb
  Formula/ngt.rb
  Formula/openjdk.rb
  Formula/openjdk@11.rb
  Formula/openjdk@12.rb
  Formula/pulumi.rb
  Formula/serverless.rb
Labels: merge

#19515 Merge 2020-02-06 62a7a1799d
  Formula/angular-cli.rb
  Formula/cctz.rb
  Formula/conan.rb
  Formula/embree.rb
  Formula/flow.rb
  Formula/helmfile.rb
  Formula/kcptun.rb
  Formula/minikube.rb
  Formula/node.rb
  Formula/node@10.rb
  Formula/node@12.rb
  Formula/procs.rb
  Formula/screen.rb
  Formula/telegraf.rb
  Formula/wtfutil.rb
Labels: merge

#19519 libetonyek: Fix build for Linux
  Formula/libetonyek.rb
Labels: almost there, cellar failure

#19524 Merge 2020-02-07 a7922929d6
  Formula/apache-forrest.rb
  Formula/apollo.rb
  Formula/bit.rb
  Formula/broot.rb
  Formula/cimg.rb
  Formula/contentful-cli.rb
  Formula/dvc.rb
  Formula/exploitdb.rb
  Formula/flasm.rb
  Formula/fluxctl.rb
  Formula/fuseki.rb
  Formula/grafana.rb
  Formula/libphonenumber.rb
  Formula/libstrophe.rb
  Formula/now-cli.rb
  Formula/par.rb
  Formula/yadm.rb
Labels: merge

#19525 Merge 2020-02-07 f624f65c45
  Formula/apache-spark.rb
  Formula/buildifier.rb
  Formula/clamav.rb
  Formula/dynare.rb
  Formula/gdal.rb
  Formula/gsasl.rb
  Formula/jhipster.rb
  Formula/linkerd.rb
  Formula/octave.rb
  Formula/pulumi.rb
  Formula/source-to-image.rb
  Formula/tippecanoe.rb
  Formula/traefik.rb
  Formula/wireguard-tools.rb
  Formula/xcodegen.rb
  Formula/yq.rb
Labels: merge

#19528 Merge 2020-02-07 fbd8e1bdab
  Formula/angular-cli.rb
  Formula/ballerina.rb
  Formula/bazel.rb
  Formula/bazelisk.rb
  Formula/exploitdb.rb
  Formula/faiss.rb
  Formula/glslviewer.rb
  Formula/golo.rb
  Formula/just.rb
  Formula/manticoresearch.rb
  Formula/minio.rb
  Formula/phpunit.rb
  Formula/pipx.rb
  Formula/rav1e.rb
  Formula/spotbugs.rb
  Formula/ssh-vault.rb
  Formula/subversion.rb
  Formula/wasm3.rb
Labels: merge

#19522 openjdk@11: fix
  Formula/openjdk@11.rb
Labels: build failure, help wanted

#19529 subversion: fix dependencies
  Formula/subversion.rb
Labels: dependency

#19065 libsigc++: Build a bottle for Linux
  Formula/libsigc++.rb
Labels: bottle, test failure

#19534 Merge 2020-02-08 1252f760fe
  Formula/activemq.rb
  Formula/akka.rb
  Formula/allure.rb
  Formula/ammonite-repl.rb
  Formula/ant.rb
  Formula/antlr.rb
  Formula/antlr@2.rb
  Formula/apache-archiva.rb
  Formula/apache-ctakes.rb
  Formula/artifactory.rb
  Formula/aws-sdk-cpp.rb
  Formula/beast.rb
  Formula/gh.rb
  Formula/gimme-aws-creds.rb
  Formula/git-delta.rb
  Formula/gradle.rb
  Formula/hapi-fhir-cli.rb
  Formula/maven.rb
  Formula/maven@3.2.rb
  Formula/maven@3.3.rb
  Formula/maven@3.5.rb
  Formula/netlify-cli.rb
  Formula/opa.rb
  Formula/ptex.rb
  Formula/pueue.rb
  Formula/starship.rb
  Formula/terraformer.rb
Labels: merge

#19549 Merge 2020-02-09 e6c5f7c9e2
  Formula/flow-tools.rb
  Formula/ford.rb
Labels: merge

#19545 gobby: Fix build for Linux
  Formula/gobby.rb
Labels: build failure, dependency

#19557 Merge 2020-02-10 d608e4a3dd
  Formula/broot.rb
  Formula/caf.rb
  Formula/exploitdb.rb
  Formula/hugo.rb
  Formula/libgpg-error.rb
  Formula/movgrab.rb
  Formula/now-cli.rb
  Formula/nss.rb
  Formula/opa.rb
  Formula/profanity.rb
  Formula/pueue.rb
  Formula/pumba.rb
  Formula/pyinvoke.rb
  Formula/rex.rb
  Formula/sfk.rb
  Formula/sphinx-doc.rb
  Formula/wtf.rb
  Formula/zeek.rb
Labels: merge

#19564 Merge 2020-02-10 028f11f9e4
  Aliases/python2
  Formula/ansible.rb
  Formula/apache-arrow-glib.rb
  Formula/apache-arrow.rb
  Formula/broot.rb
  Formula/checkbashisms.rb
  Formula/flyway.rb
  Formula/kops.rb
  Formula/lazygit.rb
  Formula/minikube.rb
  Formula/minio.rb
  Formula/navi.rb
  Formula/vala.rb
Labels: merge

#19571 Merge 2020-02-10 1911cda6d4
  Formula/ace.rb
  Formula/dive.rb
  Formula/hlint.rb
  Formula/jenkins.rb
  Formula/jsonnet.rb
  Formula/pympress.rb
Labels: merge

#19576 Merge 2020-02-10 f8547f7a32
  Formula/abcmidi.rb
  Formula/armadillo.rb
  Formula/asymptote.rb
  Formula/closure-compiler.rb
  Formula/elixir.rb
  Formula/libgee.rb
  Formula/python-markdown.rb
  Formula/qxmpp.rb
  Formula/simgrid.rb
  Formula/skopeo.rb
  Formula/snakemake.rb
Labels: merge

#19582 Merge 2020-02-10 730dd7e79f
  Formula/zdelta.rb
Labels: merge

#19577 git-archive-all: use python@3.8
  Formula/git-archive-all.rb
Labels: python

#19579 htop: remove python@2 dependency
  Formula/htop.rb
Labels: python

#19581 ninja: use python@3.8
  Formula/ninja.rb
Labels: python

#19580 neovim: remove python@2 dependency
  Formula/neovim.rb
Labels: python

#19590 llvm: Depend on Python@3.8
  Formula/llvm.rb
Labels: python

#19594 Merge 2020-02-11 6f8a17891e
  Formula/assimp.rb
  Formula/bash.rb
  Formula/cmake.rb
  Formula/cobalt.rb
  Formula/dateutils.rb
  Formula/dvc.rb
  Formula/erlang.rb
  Formula/findomain.rb
  Formula/fio.rb
  Formula/fits.rb
  Formula/folly.rb
  Formula/gdb.rb
  Formula/http-parser.rb
  Formula/i386-elf-gdb.rb
  Formula/ioping.rb
  Formula/libcdr.rb
  Formula/libmtp.rb
  Formula/lldpd.rb
  Formula/nng.rb
  Formula/python.rb
Labels: merge

#19573 scons: use python 3
  Formula/scons.rb
Labels: python

#19592 llvm@7: Depend on Python@3.8
  Formula/llvm@7.rb
Labels: python

#19574 rust: comment about Python 3 support
  Formula/rust.rb
Labels: python

#19591 llvm@6: Depend on Python@3.8
  Formula/llvm@6.rb
Labels: python

#19537 hadolint: Fix build for Linuxbrew
  Formula/hadolint.rb
Labels: bottle, dependency

#19596 gsettings-desktop-schemas: depend on Python 3
  Formula/gsettings-desktop-schemas.rb
Labels: python

#19600 Merge 2020-02-12 3672f28052
  Formula/cacli.rb
  Formula/citus.rb
  Formula/eye-d3.rb
  Formula/glooctl.rb
  Formula/kubecfg.rb
  Formula/liquibase.rb
  Formula/mk-configure.rb
  Formula/nano.rb
  Formula/ncdu.rb
  Formula/paket.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/picard-tools.rb
  Formula/pumba.rb
  Formula/terragrunt.rb
  Formula/tile38.rb
Labels: merge

#19601 Merge 2020-02-12 68bb18ac69
  Formula/allure.rb
  Formula/aws-cdk.rb
  Formula/benthos.rb
  Formula/dartsim.rb
  Formula/fcl.rb
  Formula/gdb.rb
  Formula/homebank.rb
  Formula/httpry.rb
  Formula/i386-elf-gdb.rb
  Formula/libdeflate.rb
  Formula/nesc.rb
  Formula/ocp.rb
  Formula/repo.rb
  Formula/run.rb
  Formula/sile.rb
  Formula/swiftlint.rb
  Formula/ttyd.rb
Labels: merge

#19604 Merge 2020-02-12 52ab521e80
  Formula/cfn-lint.rb
  Formula/conan.rb
  Formula/exploitdb.rb
  Formula/goffice.rb
  Formula/micro.rb
  Formula/nats-streaming-server.rb
  Formula/nesc.rb
  Formula/nnn.rb
  Formula/proteinortho.rb
  Formula/riff.rb
  Formula/stress-ng.rb
  Formula/subnetcalc.rb
  Formula/swiftlint.rb
  Formula/sysdig.rb
  Formula/texlab.rb
  Formula/verilator.rb
  Formula/xtensor.rb
  Formula/yetris.rb
  Formula/yq.rb
  Formula/zeek.rb
  Formula/zorba.rb
Labels: merge

#19607 Merge 2020-02-12 95854c9ae9
  Formula/libpsl.rb
  Formula/scons.rb
Labels: merge

#19617 Merge 2020-02-13 e9746a2d19
  Formula/abcmidi.rb
  Formula/agedu.rb
  Formula/allegro.rb
  Formula/apache-flink.rb
  Formula/appstream-glib.rb
  Formula/arcade-learning-environment.rb
  Formula/avro-cpp.rb
  Formula/awscli.rb
  Formula/corral.rb
  Formula/cython.rb
  Formula/dmd.rb
  Formula/exploitdb.rb
  Formula/fauna-shell.rb
  Formula/fish.rb
  Formula/fx.rb
  Formula/gauge.rb
  Formula/gh.rb
  Formula/gist.rb
  Formula/glooctl.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/i2p.rb
  Formula/katago.rb
  Formula/micro.rb
  Formula/mysql.rb
  Formula/node@10.rb
  Formula/openttd.rb
  Formula/platformio.rb
  Formula/predictionio.rb
  Formula/sphinx-doc.rb
  Formula/starship.rb
  Formula/tile38.rb
  Formula/tomcat.rb
  Formula/tomcat@8.rb
Labels: merge

#19620 libprelude: modernize
  Formula/libprelude.rb
Labels: python

#19624 Merge 2020-02-13 34f4321527
  Formula/angular-cli.rb
  Formula/avro-c.rb
  Formula/avro-tools.rb
  Formula/byobu.rb
  Formula/chakra.rb
  Formula/docker-completion.rb
  Formula/exploitdb.rb
  Formula/go@1.12.rb
  Formula/gosu.rb
  Formula/jhipster.rb
  Formula/libphonenumber.rb
  Formula/node-build.rb
  Formula/node@12.rb
  Formula/packer.rb
  Formula/phpunit.rb
  Formula/procs.rb
  Formula/terragrunt.rb
Labels: merge

#19616 ledger: use Python@3.8
  Formula/ledger.rb
Labels: python

#19619 rust: use python@3.8
  Formula/rust.rb
Labels: python

#19625 Merge 2020-02-13 a381fd1cc9
  Formula/ledger.rb
Labels: merge

#19626 libssh: no need to depend on python
  Formula/libssh.rb
Labels: python

#19627 Merge 2020-02-14 d1a201211b
  Formula/atlassian-cli.rb
  Formula/ats2-postiats.rb
  Formula/awscli@1.rb
  Formula/bitrise.rb
  Formula/bmake.rb
  Formula/check_postgres.rb
  Formula/cimg.rb
  Formula/ckan.rb
  Formula/clojurescript.rb
  Formula/conan.rb
  Formula/emscripten.rb
  Formula/helm.rb
  Formula/helmfile.rb
  Formula/icecream.rb
  Formula/imgproxy.rb
  Formula/istioctl.rb
  Formula/jboss-forge.rb
  Formula/kubernetes-cli.rb
  Formula/lazygit.rb
  Formula/lxc.rb
  Formula/mint.rb
  Formula/pcre.rb
  Formula/postgresql.rb
  Formula/salt.rb
Labels: merge

#19630 Merge 2020-02-14 4b82bfc315
  Formula/byacc.rb
  Formula/cdogs-sdl.rb
  Formula/cppad.rb
  Formula/dar.rb
  Formula/dovecot.rb
  Formula/fail2ban.rb
  Formula/fantom.rb
  Formula/fdclone.rb
  Formula/feh.rb
  Formula/gmic.rb
  Formula/groovy.rb
  Formula/gsoap.rb
  Formula/hevea.rb
  Formula/jsonschema2pojo.rb
  Formula/metabase.rb
  Formula/mgba.rb
Labels: merge

#19631 Merge 2020-02-14 1a2461c5cf
  Formula/freeswitch.rb
  Formula/ldns.rb
  Formula/lftp.rb
  Formula/libfixbuf.rb
  Formula/libtrace.rb
  Formula/openssh.rb
  Formula/par2.rb
  Formula/pod2man.rb
  Formula/postgresql@9.5.rb
  Formula/psqlodbc.rb
  Formula/rust.rb
  Formula/sip.rb
  Formula/stress-ng.rb
  Formula/v8.rb
Labels: merge

#19634 Merge 2020-02-15 facefb6838
  Formula/clojure.rb
  Formula/emscripten.rb
  Formula/fluent-bit.rb
  Formula/flyway.rb
  Formula/gh.rb
  Formula/groovysdk.rb
  Formula/haproxy.rb
  Formula/helm@2.rb
  Formula/jena.rb
  Formula/libarchive.rb
  Formula/libdap.rb
  Formula/libpqxx.rb
  Formula/mesa.rb
  Formula/modules.rb
  Formula/operator-sdk.rb
  Formula/ott.rb
  Formula/postgresql@10.rb
  Formula/postgresql@11.rb
  Formula/postgresql@9.4.rb
  Formula/postgresql@9.6.rb
  Formula/proj.rb
  Formula/python-markdown.rb
  Formula/ruby-build.rb
  Formula/simple-scan.rb
  Formula/txr.rb
Labels: merge

#19635 libpqxx: Depend on python@3.8
  Formula/libpqxx.rb
Labels: python

#19636 Merge 2020-02-15 d6ab414ff2
  Formula/acpica.rb
  Formula/antibody.rb
  Formula/apache-flink.rb
  Formula/apollo-cli.rb
  Formula/arduino-cli.rb
  Formula/ask-cli.rb
  Formula/citus.rb
  Formula/crystal.rb
  Formula/cypher-shell.rb
  Formula/deno.rb
  Formula/devspace.rb
  Formula/dnscontrol.rb
  Formula/kube-aws.rb
  Formula/kyma-cli.rb
  Formula/micronaut.rb
  Formula/minio-mc.rb
  Formula/packer.rb
  Formula/prometheus.rb
  Formula/terraform_landscape.rb
  Formula/tokei.rb
  Formula/yaegi.rb
Labels: merge

#19637 Merge 2020-02-15 80174e1f71
  Formula/exploitdb.rb
  Formula/hg-fast-export.rb
  Formula/lcov.rb
  Formula/libpqxx.rb
  Formula/mariadb.rb
  Formula/octant.rb
Labels: merge

#19639 linux-pam: Bump revision for libprelude
  Formula/linux-pam.rb
Labels: python

#19640 Merge 2020-02-15 5b26bfd522
  Formula/octant.rb
Labels: merge

#19642 Merge 2020-02-16 948e4d1d17
  Formula/antibody.rb
  Formula/atari800.rb
  Formula/exploitdb.rb
  Formula/ginac.rb
  Formula/giter8.rb
  Formula/gmime.rb
  Formula/mdcat.rb
  Formula/mikutter.rb
  Formula/openssh.rb
  Formula/pandoc.rb
  Formula/scdoc.rb
  Formula/storm.rb
  Formula/suricata.rb
  Formula/ucloud.rb
Labels: merge

#19645 Merge 2020-02-17 8a947170e0
  Formula/angle-grinder.rb
  Formula/awscli@1.rb
  Formula/balena-cli.rb
  Formula/bison.rb
  Formula/broot.rb
  Formula/certbot.rb
  Formula/cheat.rb
  Formula/docker.rb
  Formula/fetch-crl.rb
  Formula/file-roller.rb
  Formula/iam-policy-json-to-terraform.rb
  Formula/imagemagick.rb
  Formula/mutt.rb
  Formula/pacapt.rb
  Formula/percona-toolkit.rb
  Formula/phpstan.rb
  Formula/procs.rb
  Formula/protobuf.rb
  Formula/quicktype.rb
  Formula/raxml-ng.rb
  Formula/vim.rb
  Formula/youtube-dl.rb
  Formula/zsh.rb
Labels: merge

#19651 Merge 2020-02-17 d62c109abd
  Aliases/gradle@6
  Formula/cheat.rb
  Formula/frotz.rb
  Formula/gradle.rb
  Formula/groovy.rb
  Formula/gsettings-desktop-schemas.rb
  Formula/helmfile.rb
  Formula/ldc.rb
  Formula/libcbor.rb
  Formula/manticoresearch.rb
  Formula/mit-scheme.rb
  Formula/pandoc.rb
  Formula/taskell.rb
  Formula/visp.rb
  Formula/xmake.rb
Labels: merge

#19653 Merge 2020-02-17 838f84f7e4
  Aliases/ruby@2.7
  Formula/libstfl.rb
  Formula/macvim.rb
  Formula/mikutter.rb
  Formula/ruby.rb
  Formula/vim.rb
  Formula/weechat.rb
  Formula/wpscan.rb
Labels: merge

#19650 gpgme: depend on python 3 only
  Formula/gpgme.rb
Labels: python

#19655 wpscan: cleanup dependencies
  Formula/wpscan.rb
Labels: dependency

#19656 Merge 2020-02-18 21ab44ad05
  Formula/balena-cli.rb
  Formula/cassandra.rb
  Formula/cfn-lint.rb
  Formula/dialog.rb
  Formula/freeciv.rb
  Formula/git-gui.rb
  Formula/golang-migrate.rb
  Formula/groovysdk.rb
  Formula/gsoap.rb
  Formula/mgba.rb
  Formula/mmctl.rb
  Formula/paket.rb
  Formula/pandoc-citeproc.rb
  Formula/plantuml.rb
  Formula/zola.rb
Labels: merge

#19657 Merge 2020-02-18 93ac3eae76
  Formula/antlr@2.rb
  Formula/bitlbee.rb
  Formula/clhep.rb
  Formula/gnu-getopt.rb
  Formula/grpc.rb
  Formula/gtk+3.rb
  Formula/ipython.rb
  Formula/netpbm.rb
  Formula/platformio.rb
  Formula/pyenv-virtualenv.rb
  Formula/root.rb
  Formula/subversion.rb
  Formula/tcl-tk.rb
Labels: merge

#19608 subversion: depend on python@3.8
  Formula/subversion.rb
Labels: python

#19660 bedtools: Fix the build from source [Linux]
  Formula/bedtools.rb
Labels: python

#19593 llvm@8: Depend on Python@3.8
  Formula/llvm@8.rb
Labels: python

#19663 Merge 2020-02-19 31009f98a4
  Formula/augeas.rb
  Formula/aws-elasticbeanstalk.rb
  Formula/ejabberd.rb
  Formula/ffmpeg.rb
  Formula/ffmpeg@2.8.rb
  Formula/gjs.rb
  Formula/glib.rb
  Formula/gmp.rb
  Formula/jupyterlab.rb
  Formula/libheif.rb
  Formula/libpq.rb
  Formula/mftrace.rb
  Formula/nrpe.rb
  Formula/nushell.rb
  Formula/octomap.rb
  Formula/openimageio.rb
  Formula/poco.rb
  Formula/raylib.rb
  Formula/ruby-build.rb
  Formula/scheme48.rb
  Formula/sphinx-doc.rb
  Formula/ssh-copy-id.rb
  Formula/subversion.rb
  Formula/whois.rb
  Formula/x265.rb
Labels: merge

#19669 Merge 2020-02-19 2a0649e715
  Formula/activemq-cpp.rb
  Formula/activemq.rb
  Formula/ant.rb
  Formula/ant@1.9.rb
  Formula/apache-archiva.rb
  Formula/apache-arrow-glib.rb
  Formula/apache-arrow.rb
  Formula/apache-forrest.rb
  Formula/apache-opennlp.rb
  Formula/apache-spark.rb
  Formula/apache-zeppelin.rb
  Formula/apr-util.rb
  Formula/apr.rb
  Formula/aurora-cli.rb
  Formula/avro-c.rb
  Formula/avro-cpp.rb
  Formula/avro-tools.rb
  Formula/cassandra@2.2.rb
  Formula/cointop.rb
  Formula/couchdb.rb
  Formula/derby.rb
  Formula/fop.rb
  Formula/hadoop.rb
  Formula/hbase.rb
  Formula/hive.rb
  Formula/httpd.rb
  Formula/ivy.rb
  Formula/jmeter.rb
  Formula/jsvc.rb
  Formula/juju.rb
  Formula/kafka.rb
  Formula/libpulsar.rb
  Formula/log4cxx.rb
  Formula/mahout.rb
  Formula/nifi-registry.rb
  Formula/qpid-proton.rb
  Formula/solr.rb
  Formula/solr@7.7.rb
  Formula/storm.rb
  Formula/thrift.rb
  Formula/tika.rb
  Formula/tomcat.rb
  Formula/tomcat@8.rb
  Formula/xalan-c.rb
  Formula/xerces-c.rb
Labels: merge

#19672 Merge 2020-02-20 6f349ccd2a
  Formula/aliyun-cli.rb
  Formula/cfn-lint.rb
  Formula/chronograf.rb
  Formula/devspace.rb
  Formula/dwarfutils.rb
  Formula/erlang.rb
  Formula/ethereum.rb
  Formula/exploitdb.rb
  Formula/firebase-cli.rb
  Formula/fonttools.rb
  Formula/git-annex.rb
  Formula/glooctl.rb
  Formula/gom.rb
  Formula/istioctl.rb
  Formula/kube-aws.rb
  Formula/netlify-cli.rb
  Formula/node@12.rb
  Formula/serverless.rb
  Formula/starship.rb
  Formula/swiftformat.rb
  Formula/terragrunt.rb
  Formula/topgrade.rb
  Formula/wtf.rb
Labels: merge

#19673 dwarfutils: Fix linkage for Linuxbrew
  Formula/dwarfutils.rb
Labels: dependency

#19677 Merge 2020-02-21 7de1633bab
  Formula/mandoc.rb
Labels: merge

#19678 Merge 2020-02-21 fb61f5d98d
  Formula/anycable-go.rb
  Formula/aurora-cli.rb
  Formula/bedtools.rb
  Formula/dnsmasq.rb
  Formula/hugo.rb
  Formula/srtp.rb
Labels: merge

#19681 Merge 2020-02-21 d8d7cb29ac
  Formula/ant.rb
  Formula/apache-flink.rb
  Formula/apollo.rb
  Formula/cassandra.rb
  Formula/cassandra@2.1.rb
  Formula/flow.rb
  Formula/fuseki.rb
  Formula/glooctl.rb
  Formula/jena.rb
  Formula/mahout.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/notmuch.rb
  Formula/sqoop.rb
  Formula/tomee-jax-rs.rb
  Formula/tomee-plume.rb
  Formula/tomee-plus.rb
  Formula/tomee-webprofile.rb
  Formula/trafficserver.rb
  Formula/zookeeper.rb
Labels: merge

#19682 Merge 2020-02-21 8068c4d8fc
  Formula/gh.rb
Labels: merge

#19615 arangodb: fix
  Formula/arangodb.rb
Labels: checksum mismatch, upstream issue

#19654 libstfl: Depend on python@3.8
  Formula/libstfl.rb
Labels: python

#19683 Merge 2020-02-22 b4b0fd1646
  Formula/activemq-cpp.rb
  Formula/activemq.rb
  Formula/ant@1.9.rb
  Formula/apache-archiva.rb
  Formula/apache-arrow-glib.rb
  Formula/apache-arrow.rb
  Formula/apache-drill.rb
  Formula/apache-forrest.rb
  Formula/apache-geode.rb
  Formula/apache-opennlp.rb
  Formula/apr-util.rb
  Formula/apr.rb
  Formula/aurora-cli.rb
  Formula/avro-c.rb
  Formula/avro-cpp.rb
  Formula/avro-tools.rb
  Formula/cassandra@2.2.rb
  Formula/couchdb.rb
  Formula/derby.rb
  Formula/exploitdb.rb
  Formula/flume.rb
  Formula/fop.rb
  Formula/hadoop.rb
  Formula/hbase.rb
  Formula/hive.rb
  Formula/httpd.rb
  Formula/ivy.rb
  Formula/jmeter.rb
  Formula/jsvc.rb
  Formula/kafka.rb
  Formula/libfido2.rb
  Formula/liblzf.rb
  Formula/libpulsar.rb
  Formula/log4cxx.rb
  Formula/mahout.rb
  Formula/maven.rb
  Formula/maven@3.2.rb
  Formula/maven@3.3.rb
  Formula/maven@3.5.rb
  Formula/mesos.rb
  Formula/nifi-registry.rb
  Formula/nifi.rb
  Formula/pig.rb
  Formula/solr.rb
  Formula/solr@7.7.rb
  Formula/storm.rb
  Formula/subversion.rb
  Formula/subversion@1.8.rb
  Formula/thrift.rb
  Formula/tika.rb
  Formula/tomcat-native.rb
  Formula/tomcat.rb
  Formula/tomcat@7.rb
  Formula/tomcat@8.rb
  Formula/xalan-c.rb
  Formula/xerces-c.rb
  Formula/xml-security-c.rb
Labels: merge

#19685 Merge 2020-02-22 e9d131eec9
  Aliases/java
  Aliases/java11
  Formula/balena-cli.rb
  Formula/bazel.rb
  Formula/byobu.rb
  Formula/cargo-instruments.rb
  Formula/detekt.rb
  Formula/ed.rb
  Formula/ensmallen.rb
  Formula/fetchmail.rb
  Formula/ffuf.rb
  Formula/micronaut.rb
  Formula/ncurses.rb
  Formula/ode.rb
  Formula/php.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
Labels: merge

#19687 Merge 2020-02-22 3d89f488c0
  Formula/aws-sdk-cpp.rb
  Formula/cfn-lint.rb
  Formula/chisel.rb
  Formula/cobalt.rb
  Formula/findomain.rb
  Formula/flashrom.rb
  Formula/flawfinder.rb
  Formula/git-archive-all.rb
  Formula/iblinter.rb
  Formula/libpulsar.rb
  Formula/mmseqs2.rb
  Formula/now-cli.rb
  Formula/openssh.rb
  Formula/protoc-gen-grpc-web.rb
  Formula/terraform-provider-libvirt.rb
  Formula/terragrunt.rb
Labels: merge

#19690 Merge 2020-02-23 2327a1caa7
  Formula/bazel.rb
  Formula/cstore_fdw.rb
  Formula/faas-cli.rb
  Formula/hugo.rb
  Formula/shfmt.rb
  Formula/sn0int.rb
  Formula/snapcraft.rb
  Formula/sshrc.rb
  Formula/ucon64.rb
  Formula/yle-dl.rb
Labels: merge

#19693 Merge 2020-02-23 0f95ca35a6a
  Formula/py3cairo.rb
  Formula/wtfutil.rb
Labels: merge

#19696 Merge 2020-02-23 b724587399a
  Formula/biosig.rb
  Formula/cassandra-cpp-driver.rb
  Formula/gdcm.rb
  Formula/golo.rb
  Formula/spotbugs.rb
  Formula/wapm.rb
Labels: merge

#19698 Merge 2020-02-23 02a2136053
  Formula/bit.rb
  Formula/clojure-lsp.rb
  Formula/dfix.rb
  Formula/git-fixup.rb
  Formula/krb5.rb
  Formula/sk.rb
  Formula/uhd.rb
  Formula/vault.rb
Labels: merge

#19700 Merge 2020-02-24 1ca9851f29
  Formula/gcc.rb
  Formula/gconf.rb
  Formula/gdb.rb
  Formula/get_iplayer.rb
  Formula/gimme-aws-creds.rb
  Formula/git-absorb.rb
  Formula/git-cinnabar.rb
  Formula/git-ftp.rb
  Formula/git-remote-hg.rb
  Formula/gitfs.rb
  Formula/gitless.rb
  Formula/global.rb
  Formula/graphicsmagick.rb
  Formula/graphviz.rb
  Formula/gtk+3.rb
  Formula/h2o.rb
  Formula/hdf5.rb
  Formula/hledger.rb
  Formula/hlint.rb
  Formula/howdoi.rb
  Formula/httpd.rb
  Formula/hwloc.rb
  Formula/ibex.rb
  Formula/icarus-verilog.rb
  Formula/icecast.rb
  Formula/imagemagick.rb
  Formula/include-what-you-use.rb
  Formula/infer.rb
  Formula/interactive-rebase-tool.rb
  Formula/io.rb
  Formula/irssi.rb
  Formula/isync.rb
  Formula/jose.rb
  Formula/jrnl.rb
  Formula/kakoune.rb
  Formula/komposition.rb
  Formula/literate-git.rb
  Formula/mgba.rb
  Formula/vale.rb
  Formula/vegeta.rb
  Formula/x264.rb
Labels: merge

#19702 Merge 2020-02-24 b34221e461
  Formula/ballerina.rb
  Formula/contentful-cli.rb
  Formula/gitlab-runner.rb
  Formula/hmmer.rb
  Formula/jbake.rb
  Formula/jenkins.rb
  Formula/jpcsp.rb
  Formula/molecule.rb
  Formula/monetdb.rb
  Formula/shellharden.rb
Labels: merge

#19704 Merge 2020-02-24 91c772afe0
  Formula/apache-forrest.rb
  Formula/apollo.rb
  Formula/berglas.rb
  Formula/crc.rb
  Formula/devdash.rb
  Formula/go-bindata.rb
  Formula/mk-configure.rb
  Formula/nfdump.rb
  Formula/okteto.rb
  Formula/parallel.rb
  Formula/postgis.rb
  Formula/shairport-sync.rb
  Formula/wasmer.rb
Labels: merge

#19708 Merge 2020-02-25 c46de3ae83
  Formula/ballerina.rb
Labels: merge

#19652 ldc: Build a bottle for Linuxbrew
  Formula/ldc.rb
Labels: dependency

#19710 Merge 2020-02-25 cfdaee93868
  Formula/libstfl.rb
  Formula/ruby-build.rb
Labels: merge

#19712 Merge 2020-02-25 2177ac70e0
  Formula/etcd.rb
  Formula/fluid-synth.rb
  Formula/gatsby-cli.rb
  Formula/glooctl.rb
  Formula/gradle.rb
  Formula/helmfile.rb
  Formula/ipfs.rb
  Formula/kubespy.rb
  Formula/lazygit.rb
  Formula/n.rb
  Formula/netdata.rb
  Formula/newman.rb
  Formula/ngt.rb
  Formula/okteto.rb
  Formula/procs.rb
  Formula/proftpd.rb
  Formula/protobuf-c.rb
  Formula/repo.rb
  Formula/sccache.rb
  Formula/sphinx-doc.rb
  Formula/unbound.rb
  Formula/urh.rb
  Formula/weaver.rb
Labels: merge

#19717 Merge 2020-02-26 af7b27c200
  Aliases/go@1.14
  Formula/anttweakbar.rb
  Formula/aws-cdk.rb
  Formula/binaryen.rb
  Formula/consul.rb
  Formula/flow.rb
  Formula/ghc.rb
  Formula/ghc@8.6.rb
  Formula/git-fixup.rb
  Formula/glade.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/k6.rb
  Formula/less.rb
  Formula/lftp.rb
  Formula/libbi.rb
  Formula/libbluray.rb
  Formula/libcroco.rb
  Formula/libcue.rb
  Formula/libdap.rb
  Formula/libgcrypt.rb
  Formula/libgetdata.rb
  Formula/libgsf.rb
  Formula/libical.rb
  Formula/libjson-rpc-cpp.rb
  Formula/libmetalink.rb
  Formula/libosmium.rb
  Formula/libproxy.rb
  Formula/libquvi.rb
  Formula/libre.rb
  Formula/libserdes.rb
  Formula/libsoup.rb
  Formula/libssh2.rb
  Formula/libstrophe.rb
  Formula/libsvg.rb
  Formula/libtermkey.rb
  Formula/libtiff.rb
  Formula/libtool.rb
  Formula/libwebsockets.rb
  Formula/libxml++.rb
  Formula/libxml2.rb
  Formula/libzip.rb
  Formula/lrzip.rb
  Formula/lynx.rb
  Formula/micro.rb
  Formula/polynote.rb
  Formula/sk.rb
  Formula/stlink.rb
  Formula/vaulted.rb
Labels: merge

#19718 Merge 2020-02-26 ac6d144527
  Formula/go@1.13.rb
Labels: merge

#19720 Merge 2020-02-26 8fb7f7b7f2a
  Formula/aws-cdk.rb
  Formula/cgal.rb
  Formula/circleci.rb
  Formula/ejabberd.rb
  Formula/elixir.rb
  Formula/exploitdb.rb
  Formula/i2pd.rb
  Formula/kubeseal.rb
  Formula/meson.rb
  Formula/minio-mc.rb
  Formula/pandoc-crossref.rb
  Formula/pwntools.rb
  Formula/serverless.rb
  Formula/telegraf.rb
  Formula/xapian.rb
  Formula/xmake.rb
  Formula/zabbix.rb
Labels: merge

#19723 Merge 2020-02-27 a8b172dac1
  Formula/aliyun-cli.rb
  Formula/apollo-cli.rb
  Formula/autorest.rb
  Formula/exploitdb.rb
  Formula/ghq.rb
  Formula/go-jira.rb
  Formula/grpc.rb
  Formula/hcloud.rb
  Formula/helmfile.rb
  Formula/kcptun.rb
  Formula/kompose.rb
  Formula/lego.rb
  Formula/mongo-c-driver.rb
  Formula/netlify-cli.rb
  Formula/protoc-gen-go.rb
  Formula/pulumi.rb
  Formula/pumba.rb
  Formula/terragrunt.rb
  Formula/tflint.rb
  Formula/wireshark.rb
Labels: merge

#19724 Merge 2020-02-27 a513067019
  Formula/arduino-cli.rb
Labels: merge

#19648 fetch-crl: Fix build for Linuxbrew
  Formula/fetch-crl.rb
Labels: dependency

#19647 balena-cli: Build a bottle for Linuxbrew
  Formula/balena-cli.rb
Labels: bottle

#19731 Merge 2020-02-28 88f52e3921
  Formula/cpprestsdk.rb
  Formula/cromwell.rb
  Formula/ctemplate.rb
  Formula/cuba.rb
  Formula/juju.rb
  Formula/latex2html.rb
  Formula/msgpuck.rb
  Formula/needle.rb
  Formula/openjdk.rb
  Formula/osquery.rb
  Formula/sleuthkit.rb
Labels: merge

#19732 Merge 2020-02-28 4ffec25f55
  Formula/aws-google-auth.rb
  Formula/azure-storage-cpp.rb
  Formula/cobalt.rb
  Formula/dust.rb
  Formula/dvc.rb
  Formula/firebase-cli.rb
  Formula/lapack.rb
  Formula/less.rb
  Formula/lesspipe.rb
  Formula/numpy@1.16.rb
  Formula/pastel.rb
  Formula/serverless.rb
  Formula/shadowenv.rb
  Formula/solr.rb
  Formula/solr@7.7.rb
  Formula/tealdeer.rb
  Formula/tmux.rb
  Formula/topgrade.rb
  Formula/wasmer.rb
  Formula/webpack.rb
  Formula/xmake.rb
  Formula/yq.rb
Labels: merge

#19734 Merge 2020-02-28 2517c6edb8
  Formula/agda.rb
  Formula/angle-grinder.rb
  Formula/bench.rb
  Formula/cryptol.rb
  Formula/darcs.rb
  Formula/lft.rb
  Formula/libfido2.rb
  Formula/man-db.rb
  Formula/ne.rb
Labels: merge

#19738 Merge 2020-02-29 ed0f05d625
  Formula/abcm2ps.rb
  Formula/allure.rb
  Formula/appstream-glib.rb
  Formula/b3sum.rb
  Formula/byteman.rb
  Formula/camlp5.rb
  Formula/clblast.rb
  Formula/consul.rb
  Formula/dhall-bash.rb
  Formula/dhall-json.rb
  Formula/dhall-lsp-server.rb
  Formula/dhall.rb
  Formula/elm-format.rb
  Formula/erlang.rb
  Formula/flyway.rb
  Formula/geoipupdate.rb
  Formula/grails.rb
  Formula/hopenpgp-tools.rb
  Formula/i2p.rb
  Formula/idris.rb
  Formula/jruby.rb
  Formula/libgr.rb
  Formula/mill.rb
  Formula/nwchem.rb
  Formula/pinboard-notes-backup.rb
  Formula/postgrest.rb
  Formula/qca.rb
  Formula/shellcheck.rb
  Formula/xmake.rb
  Formula/zydis.rb
Labels: merge

#19739 Merge 2020-02-29 34f1507775
  Formula/cargo-instruments.rb
  Formula/cfengine.rb
  Formula/dps8m.rb
  Formula/folly.rb
  Formula/fonttools.rb
  Formula/gmsh.rb
  Formula/gptfdisk.rb
  Formula/graphicsmagick.rb
  Formula/libgphoto2.rb
  Formula/libjwt.rb
  Formula/mongoose.rb
  Formula/nethack.rb
  Formula/pjproject.rb
  Formula/rancid.rb
  Formula/ratfor.rb
  Formula/stress-ng.rb
Labels: merge

#19742 Merge 2020-02-29 699ef52b5b
  Formula/nethack.rb
Labels: merge

#19575 pyenv: depend on python@3.8
  Formula/pyenv.rb
Labels: python
