Repository Homebrew/linuxbrew-core, pull requests merged in 2020-03, with the labels that each got.

#19746 Merge 2020-03-01 5c961940b1
  Formula/docker-slim.rb
  Formula/jetty.rb
  Formula/magic-wormhole.rb
  Formula/mapserver.rb
  Formula/mariadb-connector-c.rb
  Formula/mariadb.rb
  Formula/mediaconch.rb
  Formula/megatools.rb
  Formula/mesos.rb
  Formula/metricbeat.rb
  Formula/mighttpd2.rb
  Formula/mikutter.rb
  Formula/minizip.rb
  Formula/moreutils.rb
  Formula/mosh.rb
  Formula/mruby.rb
  Formula/mutt.rb
  Formula/myman.rb
  Formula/mysql-client.rb
  Formula/mysql.rb
  Formula/mysql@5.7.rb
  Formula/newsboat.rb
  Formula/nghttp2.rb
  Formula/nload.rb
  Formula/nmap.rb
  Formula/nnn.rb
  Formula/nvi.rb
  Formula/php.rb
  Formula/vim.rb
  Formula/xcodegen.rb
  Formula/zsh-syntax-highlighting.rb
Labels: merge

#19733 balena-cli: remove --unsafe-perm
  Formula/balena-cli.rb
Labels: blocked

#19595 qt: depend on Python 3
  Formula/qt.rb
Labels: do not merge, python

#19747 Merge 2020-03-02 ec732fdb1a
  Formula/octave.rb
  Formula/offlineimap.rb
  Formula/onefetch.rb
  Formula/opam.rb
  Formula/openexr.rb
  Formula/osc.rb
  Formula/osmium-tool.rb
  Formula/pacvim.rb
  Formula/pandoc.rb
  Formula/pdf-redact-tools.rb
  Formula/perl-build.rb
  Formula/perl.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
  Formula/pianobar.rb
  Formula/poppler.rb
  Formula/postgresql@10.rb
  Formula/postgresql@11.rb
  Formula/postgresql@9.4.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
  Formula/profanity.rb
  Formula/progress.rb
  Formula/pulseaudio.rb
  Formula/pwntools.rb
  Formula/pyenv.rb
  Formula/qpdf.rb
Labels: merge

#19748 Merge 2020-03-02 009cb701ba
  Formula/readline.rb
  Formula/reminiscence.rb
  Formula/rethinkdb.rb
  Formula/roswell.rb
  Formula/rsyslog.rb
  Formula/rtmpdump.rb
  Formula/screen.rb
  Formula/seqtk.rb
  Formula/shadowsocks-libev.rb
  Formula/shared-mime-info.rb
  Formula/silk.rb
  Formula/sniffglue.rb
  Formula/spades.rb
  Formula/sphinx.rb
  Formula/sqldiff.rb
  Formula/sqlite.rb
  Formula/sqliteodbc.rb
  Formula/squashfs.rb
  Formula/sratoolkit.rb
  Formula/ssh-permit-a38.rb
  Formula/statik.rb
  Formula/stella.rb
  Formula/stellar-core.rb
  Formula/stoken.rb
  Formula/stormssh.rb
  Formula/streamlink.rb
  Formula/stress-ng.rb
  Formula/suite-sparse.rb
  Formula/sundials.rb
  Formula/swift.rb
  Formula/taskell.rb
  Formula/telegram-cli.rb
  Formula/texinfo.rb
  Formula/tinc.rb
  Formula/tldr.rb
  Formula/tmate.rb
  Formula/tor.rb
  Formula/travis.rb
Labels: merge

#19749 Merge 2020-03-02 3ba0438784
  .github/workflows/tests.yml
  Formula/apache-spark.rb
  Formula/dbhash.rb
  Formula/mongrel2.rb
  Formula/nss.rb
  Formula/proj.rb
  Formula/sn0int.rb
  Formula/swift-sh.rb
  Formula/udunits.rb
  Formula/unpaper.rb
  Formula/unzip.rb
  Formula/uwsgi.rb
  Formula/valabind.rb
  Formula/vifm.rb
  Formula/vim.rb
  Formula/vips.rb
  Formula/virtuoso.rb
  Formula/vorbis-tools.rb
  Formula/vsts-cli.rb
  Formula/w3m.rb
  Formula/wdiff.rb
  Formula/wimlib.rb
  Formula/wiredtiger.rb
  Formula/wordgrinder.rb
  Formula/xerces-c.rb
  Formula/xml2.rb
  Formula/xrootd.rb
  Formula/yaz.rb
  Formula/yle-dl.rb
  Formula/zile.rb
  Formula/zurl.rb
Labels: merge

#19757 Merge 2020-03-04 8d84264068
  Formula/abyss.rb
  Formula/arx-libertatis.rb
  Formula/arx.rb
  Formula/awsume.rb
  Formula/babl.rb
  Formula/bluepill.rb
  Formula/cartridge-cli.rb
  Formula/cless.rb
  Formula/convox.rb
  Formula/deno.rb
  Formula/gegl.rb
  Formula/git-filter-repo.rb
  Formula/git-remote-gcrypt.rb
  Formula/git-review.rb
  Formula/gitleaks.rb
  Formula/glib.rb
  Formula/grpc-swift.rb
  Formula/hugo.rb
  Formula/itk.rb
  Formula/jenkins-lts.rb
  Formula/kerl.rb
  Formula/liblo.rb
  Formula/libvmaf.rb
  Formula/logtalk.rb
  Formula/macvim.rb
  Formula/rnv.rb
  Formula/sbcl.rb
  Formula/scons.rb
  Formula/smali.rb
  Formula/syck.rb
  Formula/velero.rb
  Formula/wtf.rb
  Formula/youtube-dl.rb
Labels: merge

#19758 Merge 2020-03-04 832d7a3182
  Formula/abseil.rb
  Formula/astrometry-net.rb
  Formula/bandwhich.rb
  Formula/bazel.rb
  Formula/cfn-lint.rb
  Formula/cfssl.rb
  Formula/deark.rb
  Formula/diff-pdf.rb
  Formula/gatsby-cli.rb
  Formula/gh.rb
  Formula/gleam.rb
  Formula/jrnl.rb
  Formula/killswitch.rb
  Formula/lazygit.rb
  Formula/netcdf.rb
  Formula/opa.rb
  Formula/openfortivpn.rb
  Formula/openlibm.rb
  Formula/pdftoipe.rb
  Formula/poetry.rb
  Formula/poppler.rb
  Formula/root.rb
  Formula/rsyslog.rb
  Formula/seal.rb
  Formula/stgit.rb
  Formula/terragrunt.rb
  Formula/xrootd.rb
  Formula/zim.rb
  Formula/zsh-completions.rb
Labels: merge

#19761 Merge 2020-03-04 076d47dd7d
  Formula/bareos-client.rb
  Formula/bowtie2.rb
  Formula/ccm.rb
  Formula/cglm.rb
  Formula/comby.rb
  Formula/docker-completion.rb
  Formula/fdupes.rb
  Formula/fn.rb
  Formula/fobis.rb
  Formula/gcovr.rb
  Formula/getdns.rb
  Formula/gibo.rb
  Formula/git-delta.rb
  Formula/gitlab-gem.rb
  Formula/gradle.rb
  Formula/h264bitstream.rb
  Formula/jvgrep.rb
  Formula/keydb.rb
  Formula/kotlin.rb
  Formula/lazygit.rb
  Formula/nginx.rb
  Formula/passenger.rb
  Formula/phoronix-test-suite.rb
  Formula/plantuml.rb
  Formula/r.rb
Labels: merge

#19764 Merge 2020-03-04 c735ec189b
  Formula/asymptote.rb
  Formula/cedille.rb
  Formula/curl-openssl.rb
  Formula/curl.rb
  Formula/docker.rb
  Formula/draco.rb
  Formula/ghc.rb
  Formula/repo.rb
  Formula/topgrade.rb
Labels: merge

#19765 Merge 2020-03-04 697e201355
  Formula/biosig.rb
  Formula/gh.rb
  Formula/graphviz.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/leiningen.rb
  Formula/libmpdclient.rb
  Formula/libmypaint.rb
  Formula/logrotate.rb
  Formula/omega.rb
  Formula/pari.rb
  Formula/psftools.rb
  Formula/vala.rb
  Formula/valabind.rb
Labels: merge

#19743 cppcheck: depend on Python 3.8 for test
  Formula/cppcheck.rb
Labels: python

#19769 Merge 2020-03-05 f6bef2925e
  Formula/anycable-go.rb
  Formula/auditbeat.rb
  Formula/aurora-cli.rb
  Formula/babel.rb
  Formula/circleci.rb
  Formula/cmake.rb
  Formula/cppcheck.rb
  Formula/ddrescue.rb
  Formula/django-completion.rb
  Formula/erlang@20.rb
  Formula/exploitdb.rb
  Formula/goreleaser.rb
  Formula/libnotify.rb
  Formula/libxkbcommon.rb
  Formula/metricbeat.rb
  Formula/minio.rb
  Formula/mmctl.rb
  Formula/molecule.rb
  Formula/netlify-cli.rb
  Formula/node.rb
  Formula/poetry.rb
  Formula/pulumi.rb
  Formula/rethinkdb.rb
  Formula/sqlmap.rb
  Formula/vim.rb
  Formula/yazpp.rb
Labels: merge

#19772 Merge 2020-03-05 897c53114c
  Formula/angular-cli.rb
  Formula/asdf.rb
  Formula/dxpy.rb
  Formula/git-ftp.rb
  Formula/gx.rb
  Formula/idnits.rb
  Formula/imapfilter.rb
  Formula/jfrog-cli-go.rb
  Formula/libquantum.rb
  Formula/libtorrent-rasterbar.rb
  Formula/libvirt.rb
  Formula/libxo.rb
  Formula/logstash.rb
  Formula/procs.rb
  Formula/re2.rb
  Formula/tepl.rb
Labels: merge

#19774 libquantum: fix test for Linuxbrew
  Formula/libquantum.rb
Labels: bottle, test failure

#19776 Merge 2020-03-06 c277e2c6ab
  Formula/arpack.rb
  Formula/ceres-solver.rb
  Formula/clp.rb
  Formula/coinutils.rb
  Formula/cpptest.rb
  Formula/dynare.rb
  Formula/flow.rb
  Formula/gmt.rb
  Formula/gmt@5.rb
  Formula/hub.rb
  Formula/ios-webkit-debug-proxy.rb
  Formula/ipopt.rb
  Formula/istioctl.rb
  Formula/ltl2ba.rb
  Formula/mame.rb
  Formula/mkvtoolnix.rb
  Formula/numpy.rb
  Formula/numpy@1.16.rb
  Formula/nwchem.rb
  Formula/octave.rb
  Formula/openblas.rb
  Formula/opencv.rb
  Formula/opencv@3.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/proteinortho.rb
  Formula/qrupdate.rb
  Formula/r.rb
  Formula/root.rb
  Formula/rsyslog.rb
  Formula/scalapack.rb
  Formula/scipy.rb
  Formula/shogun.rb
  Formula/stgit.rb
  Formula/suite-sparse.rb
  Formula/sundials.rb
  Formula/tokei.rb
  Formula/visp.rb
  Formula/youtube-dl.rb
Labels: merge

#19778 Merge 2020-03-06 0e40e1dd71
  Formula/arpack.rb
  Formula/ceres-solver.rb
  Formula/citus.rb
  Formula/clp.rb
  Formula/coinutils.rb
  Formula/coreutils.rb
  Formula/dynare.rb
  Formula/exploitdb.rb
  Formula/eye-d3.rb
  Formula/forcecli.rb
  Formula/gmt.rb
  Formula/gmt@5.rb
  Formula/ipopt.rb
  Formula/numpy.rb
  Formula/numpy@1.16.rb
  Formula/nwchem.rb
  Formula/octave.rb
  Formula/openblas.rb
  Formula/opencv.rb
  Formula/opencv@3.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/proteinortho.rb
  Formula/qrupdate.rb
  Formula/r.rb
  Formula/root.rb
  Formula/rust.rb
  Formula/scalapack.rb
  Formula/scipy.rb
  Formula/shogun.rb
  Formula/suite-sparse.rb
  Formula/sundials.rb
  Formula/visp.rb
Labels: merge

#19779 Merge 2020-03-06 3aa8012626
  Formula/apollo-cli.rb
  Formula/aws-sdk-cpp.rb
  Formula/calicoctl.rb
  Formula/cocoapods.rb
  Formula/conan.rb
  Formula/contentful-cli.rb
  Formula/dav1d.rb
  Formula/devspace.rb
  Formula/emscripten.rb
  Formula/erlang@21.rb
  Formula/freeglut.rb
  Formula/fribidi.rb
  Formula/katago.rb
  Formula/lcov.rb
  Formula/lxc.rb
  Formula/ntp.rb
  Formula/opencv.rb
  Formula/percona-toolkit.rb
  Formula/procs.rb
  Formula/teleport.rb
  Formula/wasmer.rb
Labels: merge

#19781 Merge 2020-03-06 9269198fc8
  Formula/ansible.rb
  Formula/exploitdb.rb
  Formula/gdal.rb
  Formula/gedit.rb
  Formula/libgaiagraphics.rb
  Formula/libgeotiff.rb
  Formula/liblwgeom.rb
  Formula/librasterlite.rb
  Formula/libspatialite.rb
  Formula/mapserver.rb
  Formula/nvm.rb
  Formula/osm2pgsql.rb
  Formula/postgis.rb
  Formula/proj.rb
  Formula/simple-scan.rb
  Formula/spatialite-gui.rb
  Formula/spatialite-tools.rb
  Formula/vte3.rb
  Formula/wiremock-standalone.rb
Labels: merge

#19784 Merge 2020-03-06 257bb3e8cb
  Formula/chamber.rb
  Formula/commandbox.rb
  Formula/emscripten.rb
  Formula/gatsby-cli.rb
  Formula/glib-networking.rb
  Formula/okteto.rb
  Formula/root.rb
  Formula/terraform.rb
  Formula/yarn.rb
Labels: merge

#19783 liblwgeom: fix test for Linuxbrew
  Formula/liblwgeom.rb
Labels: test failure

#19786 Merge 2020-03-07 18e7d57279
  Aliases/ck
  Formula/biosig.rb
  Formula/bonnie++.rb
  Formula/ceres-solver.rb
  Formula/certbot.rb
  Formula/codec2.rb
  Formula/concurrencykit.rb
  Formula/dialog.rb
  Formula/diffoscope.rb
  Formula/dynare.rb
  Formula/easyrpg-player.rb
  Formula/ecasound.rb
  Formula/gatsby-cli.rb
  Formula/geeqie.rb
  Formula/ilmbase.rb
  Formula/ipython.rb
  Formula/isl.rb
  Formula/jbig2dec.rb
  Formula/jupyterlab.rb
  Formula/libewf.rb
  Formula/libsvm.rb
  Formula/mdds.rb
  Formula/mercurial.rb
  Formula/mesa.rb
  Formula/minikube.rb
  Formula/minio.rb
  Formula/nudoku.rb
  Formula/octave.rb
  Formula/open-mpi.rb
  Formula/openexr.rb
  Formula/sdcc.rb
  Formula/sphinx-doc.rb
  Formula/spirv-tools.rb
  Formula/suite-sparse.rb
  Formula/sundials.rb
  Formula/tfenv.rb
  Formula/tin.rb
  Formula/zimg.rb
Labels: merge

#19788 Merge 2020-03-07 c1ca9b5cfd
  CONTRIBUTING.md
  Formula/awscurl.rb
  Formula/credstash.rb
  Formula/fastlane.rb
  Formula/netcdf.rb
  Formula/qt.rb
  Formula/ttyd.rb
  Formula/v8.rb
  Formula/xmlto.rb
Labels: merge

#19789 Merge 2020-03-07 27e4308cba
  Formula/evince.rb
  Formula/gtksourceview4.rb
  Formula/libdazzle.rb
  Formula/libpeas.rb
  Formula/libsoup.rb
  Formula/pypy.rb
  Formula/pypy3.rb
Labels: merge

#19790 Merge 2020-03-08 e27c8db8c4
  Formula/abseil.rb
  Formula/apibuilder-cli.rb
  Formula/archiver.rb
  Formula/artifactory.rb
  Formula/aws-cdk.rb
  Formula/awsume.rb
  Formula/blazegraph.rb
  Formula/buildifier.rb
  Formula/cfn-lint.rb
  Formula/djmount.rb
  Formula/entr.rb
  Formula/ephemeralpg.rb
  Formula/exploitdb.rb
  Formula/file-roller.rb
  Formula/git-trim.rb
  Formula/gmediaserver.rb
  Formula/gobject-introspection.rb
  Formula/hostess.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jenkins-lts.rb
  Formula/libupnp.rb
  Formula/libwebsockets.rb
  Formula/luaradio.rb
  Formula/moarvm.rb
  Formula/monero.rb
  Formula/mosquitto.rb
  Formula/mpd.rb
  Formula/nqp.rb
  Formula/qp.rb
  Formula/rakudo-star.rb
  Formula/rakudo.rb
  Formula/sn0int.rb
  Formula/stress-ng.rb
  Formula/ttyd.rb
  Formula/vault.rb
Labels: merge

#19798 Merge 2020-03-08 9d888ebfb9
  Formula/adwaita-icon-theme.rb
  Formula/cfr-decompiler.rb
  Formula/cgrep.rb
  Formula/git.rb
  Formula/jhipster.rb
  Formula/joplin.rb
  Formula/ldc.rb
  Formula/libcerf.rb
  Formula/neofetch.rb
  Formula/pipx.rb
  Formula/procs.rb
  Formula/pygobject3.rb
  Formula/youtube-dl.rb
Labels: merge

#19804 rust: test
  Formula/dust.rb
  Formula/rust.rb
Labels: do not merge

#19807 Merge 2020-03-10 38465894bb
  Formula/clutter.rb
  Formula/cogl.rb
  Formula/confluent-platform.rb
  Formula/elasticsearch.rb
  Formula/fselect.rb
  Formula/gatsby-cli.rb
  Formula/gcc@8.rb
  Formula/geocode-glib.rb
  Formula/grin-wallet.rb
  Formula/grin.rb
  Formula/gsettings-desktop-schemas.rb
  Formula/gti.rb
  Formula/hexyl.rb
  Formula/hugo.rb
  Formula/hyperkit.rb
  Formula/ktoblzcheck.rb
  Formula/libgweather.rb
  Formula/libical.rb
  Formula/memcached.rb
  Formula/mercury.rb
  Formula/minio.rb
  Formula/nethack.rb
  Formula/newrelic-cli.rb
  Formula/rabbitmq.rb
  Formula/terragrunt.rb
  Formula/yarn.rb
Labels: merge

#19808 ktoblzcheck: Depend on Python@3.8
  Formula/ktoblzcheck.rb
Labels: python

#19810 Merge 2020-03-10 89b5967da6
  Formula/arping.rb
  Formula/bison.rb
  Formula/bitcoin.rb
  Formula/cargo-completion.rb
  Formula/cartridge-cli.rb
  Formula/cgns.rb
  Formula/cocoapods.rb
  Formula/csvkit.rb
  Formula/dbus.rb
  Formula/diff-pdf.rb
  Formula/dosbox-x.rb
  Formula/dovecot.rb
  Formula/dtc.rb
  Formula/groovy.rb
  Formula/groovysdk.rb
  Formula/jruby.rb
  Formula/nng.rb
  Formula/pastel.rb
  Formula/s6.rb
  Formula/spice-protocol.rb
  Formula/vttest.rb
Labels: merge

#19811 Merge 2020-03-10 d8af7ebca2
  Formula/davmail.rb
  Formula/db-vcs.rb
  Formula/derby.rb
  Formula/detekt.rb
  Formula/dmd.rb
  Formula/docfx.rb
  Formula/docker-slim.rb
  Formula/dune.rb
  Formula/ejdb.rb
  Formula/emscripten.rb
  Formula/fairymax.rb
  Formula/fantom.rb
  Formula/findomain.rb
  Formula/fluent-bit.rb
  Formula/flyway.rb
  Formula/gambit.rb
  Formula/grin-wallet.rb
  Formula/libfabric.rb
  Formula/libgosu.rb
  Formula/libserdes.rb
  Formula/luarocks.rb
  Formula/newrelic-cli.rb
  Formula/quex.rb
  Formula/unicorn.rb
Labels: merge

#19812 Merge 2020-03-10 8bde6d9beb
  Formula/azure-cli.rb
  Formula/azure-storage-cpp.rb
  Formula/benthos.rb
  Formula/folly.rb
  Formula/frugal.rb
  Formula/gammaray.rb
  Formula/git-annex.rb
  Formula/git-standup.rb
  Formula/gromacs.rb
  Formula/ios-sim.rb
  Formula/jenkins.rb
  Formula/juise.rb
  Formula/krew.rb
  Formula/kumo.rb
  Formula/libqalculate.rb
  Formula/librealsense.rb
  Formula/liquibase.rb
  Formula/lolcat.rb
  Formula/mbedtls.rb
  Formula/metabase.rb
  Formula/minizinc.rb
  Formula/minizip2.rb
  Formula/mkl-dnn.rb
  Formula/qalculate-gtk.rb
Labels: merge

#19813 Merge 2020-03-10 7e3229311f
  .github/workflows/tests.yml
  Formula/composer.rb
  Formula/kallisto.rb
  Formula/mongo-cxx-driver.rb
  Formula/mysql-connector-c++.rb
  Formula/python@3.8.rb
  Formula/xmrig.rb
  Formula/you-get.rb
Labels: merge

#19814 Merge 2020-03-10 e03a7e2017
  Formula/buildifier.rb
  Formula/conan.rb
  Formula/dependency-check.rb
  Formula/exploitdb.rb
  Formula/faiss.rb
  Formula/hostess.rb
  Formula/inlets.rb
  Formula/ktoblzcheck.rb
  Formula/n.rb
  Formula/newrelic-cli.rb
  Formula/pushpin.rb
  Formula/terragrunt.rb
Labels: merge

#19817 Merge 2020-03-11 6cd70d625e
  Formula/balena-cli.rb
  Formula/chakra.rb
  Formula/curl.rb
  Formula/dub.rb
  Formula/e2fsprogs.rb
  Formula/editorconfig.rb
  Formula/ext2fuse.rb
  Formula/freeglut.rb
  Formula/geos.rb
  Formula/haxe.rb
  Formula/jenkins-job-builder.rb
  Formula/ledger.rb
  Formula/leela-zero.rb
  Formula/libtorrent-rasterbar.rb
  Formula/lolcode.rb
  Formula/mavsdk.rb
  Formula/micronaut.rb
  Formula/multimarkdown.rb
  Formula/mypy.rb
  Formula/node-sass.rb
  Formula/nodeenv.rb
  Formula/oauth2l.rb
  Formula/ode.rb
  Formula/odpi.rb
  Formula/open-image-denoise.rb
  Formula/pnpm.rb
  Formula/protobuf@3.6.rb
  Formula/python.rb
  Formula/re-flex.rb
  Formula/rp.rb
  Formula/tbb.rb
  Formula/toilet.rb
  Formula/urh.rb
  Formula/velero.rb
  Formula/wpscan.rb
  Formula/wxmaxima.rb
  Formula/zeek.rb
Labels: merge

#19827 Merge 2020-03-12 0b13d2e4a1
  Formula/ansible-lint.rb
  Formula/awscli.rb
  Formula/awslogs.rb
  Formula/awsume.rb
  Formula/conan.rb
  Formula/csvkit.rb
  Formula/flintrock.rb
  Formula/fonttools.rb
  Formula/git-review.rb
  Formula/juju-wait.rb
  Formula/legit.rb
  Formula/pwntools.rb
  Formula/pyvim.rb
  Formula/sceptre.rb
  Formula/sqlparse.rb
  Formula/supervisor.rb
  Formula/translate-toolkit.rb
  Formula/trash-cli.rb
  Formula/twine-pypi.rb
  Formula/ykman.rb
Labels: merge

#19828 Merge 2020-03-12 5677551992
  Formula/aws-shell.rb
  Formula/awscli@1.rb
  Formula/awscurl.rb
  Formula/azure-cli.rb
  Formula/bandcamp-dl.rb
  Formula/cfn-lint.rb
  Formula/cppman.rb
  Formula/diceware.rb
  Formula/docker-squash.rb
  Formula/duplicity.rb
  Formula/dxpy.rb
  Formula/fdroidserver.rb
  Formula/gandi.cli.rb
  Formula/git-revise.rb
  Formula/jrnl.rb
  Formula/keepkey-agent.rb
  Formula/mackup.rb
  Formula/mdv.rb
  Formula/molecule.rb
  Formula/nbdime.rb
  Formula/pgcli.rb
  Formula/pssh.rb
  Formula/pygitup.rb
  Formula/pygments.rb
  Formula/sshuttle.rb
  Formula/svtplay-dl.rb
  Formula/watson.rb
  Formula/yamllint.rb
  Formula/you-get.rb
  Formula/zabbix-cli.rb
Labels: merge

#19829 Merge 2020-03-12 fd7578b01f
  Formula/ansible.rb
  Formula/asciinema.rb
  Formula/atdtool.rb
  Formula/aws-elasticbeanstalk.rb
  Formula/black.rb
  Formula/codemod.rb
  Formula/codespell.rb
  Formula/conjure-up.rb
  Formula/cookiecutter.rb
  Formula/csvtomd.rb
  Formula/docker-compose.rb
  Formula/eg-examples.rb
  Formula/esptool.rb
  Formula/gimme-aws-creds.rb
  Formula/git-plus.rb
  Formula/gitup.rb
  Formula/homeassistant-cli.rb
  Formula/howdoi.rb
  Formula/httpie.rb
  Formula/instalooter.rb
  Formula/internetarchive.rb
  Formula/jinja2-cli.rb
  Formula/khard.rb
  Formula/literate-git.rb
  Formula/magic-wormhole.rb
  Formula/mitmproxy.rb
  Formula/mkdocs.rb
  Formula/mongo-orchestration.rb
  Formula/mycli.rb
  Formula/pipenv.rb
  Formula/platformio.rb
  Formula/proselint.rb
  Formula/pyinvoke.rb
  Formula/pylint.rb
  Formula/python@3.8.rb
  Formula/remarshal.rb
  Formula/rst-lint.rb
  Formula/rtv.rb
  Formula/s3cmd.rb
  Formula/scour.rb
  Formula/streamlink.rb
  Formula/thefuck.rb
  Formula/todoman.rb
  Formula/tox.rb
  Formula/vsts-cli.rb
  Formula/xonsh.rb
  Formula/yapf.rb
  Formula/ydcv.rb
Labels: merge

#19838 Merge 2020-03-12 acc0c5467f
  Formula/astrometry-net.rb
  Formula/bzt.rb
  Formula/cpl.rb
  Formula/sbjson.rb
  Formula/serf.rb
  Formula/sfk.rb
  Formula/simg2img.rb
  Formula/spigot.rb
  Formula/spirv-cross.rb
  Formula/ssdb.rb
  Formula/statik.rb
  Formula/stellar-core.rb
  Formula/stgit.rb
  Formula/stolon.rb
  Formula/swagger-codegen.rb
  Formula/swift-protobuf.rb
  Formula/swift-sh.rb
  Formula/swiftformat.rb
  Formula/switch-lan-play.rb
  Formula/talisman.rb
  Formula/tektoncd-cli.rb
  Formula/terrahelp.rb
  Formula/terrahub.rb
  Formula/wcslib.rb
Labels: merge

#19839 Merge 2020-03-12 44f7876eef
  Formula/dartsim.rb
  Formula/git-trim.rb
  Formula/lgogdownloader.rb
  Formula/libsecret.rb
  Formula/oclgrind.rb
  Formula/sdedit.rb
  Formula/sjk.rb
  Formula/skinny.rb
  Formula/sonar-scanner.rb
  Formula/sonarqube.rb
  Formula/sqlparse.rb
  Formula/ssh-audit.rb
  Formula/texmath.rb
  Formula/tgui.rb
  Formula/tinyxml2.rb
  Formula/trafficserver.rb
  Formula/twarc.rb
  Formula/txr.rb
  Formula/v2ray-plugin.rb
  Formula/vala.rb
  Formula/vowpal-wabbit.rb
  Formula/vulkan-headers.rb
  Formula/wal2json.rb
  Formula/wartremover.rb
  Formula/webdis.rb
  Formula/webtorrent-cli.rb
  Formula/wp-cli-completion.rb
  Formula/x3270.rb
  Formula/xtensor.rb
  Formula/z.rb
Labels: merge

#19840 Merge 2020-03-12 a07fc4262e
  Aliases/awscli@2
  Formula/aliyun-cli.rb
  Formula/arangodb.rb
  Formula/aws-es-proxy.rb
  Formula/bundletool.rb
  Formula/cheat.rb
  Formula/exploitdb.rb
  Formula/frpc.rb
  Formula/frps.rb
  Formula/gatsby-cli.rb
  Formula/gitmoji.rb
  Formula/glances.rb
  Formula/glib.rb
  Formula/hdt.rb
  Formula/ibex.rb
  Formula/kubeprod.rb
  Formula/kubeseal.rb
  Formula/libtcod.rb
  Formula/llvm.rb
  Formula/molten-vk.rb
  Formula/nagios-plugins.rb
  Formula/radare2.rb
  Formula/rex.rb
  Formula/sceptre.rb
  Formula/tlx.rb
  Formula/txt2tags.rb
  Formula/vale.rb
  Formula/webalizer.rb
  Formula/wildfly-as.rb
  Formula/x86_64-elf-binutils.rb
  Formula/x86_64-elf-gcc.rb
  Formula/xclogparser.rb
  Formula/xplanet.rb
  Formula/yafc.rb
  Formula/yarn.rb
  Formula/zim.rb
  Formula/zsh-history-substring-search.rb
Labels: merge

#19841 Merge 2020-03-12 81e8e84b9f
  Formula/allureofthestars.rb
  Formula/apache-brooklyn-cli.rb
  Formula/apache-spark.rb
  Formula/app-engine-java.rb
  Formula/aws-google-auth.rb
  Formula/awscurl.rb
  Formula/balena-cli.rb
  Formula/biosig.rb
  Formula/bitchx.rb
  Formula/blastem.rb
  Formula/calicoctl.rb
  Formula/camlp5.rb
  Formula/carrot2.rb
  Formula/cassandra.rb
  Formula/cassandra@2.1.rb
  Formula/cassandra@2.2.rb
  Formula/castxml.rb
  Formula/ccache.rb
  Formula/ceylon.rb
  Formula/circleci.rb
  Formula/corsixth.rb
  Formula/couchdb.rb
  Formula/crc32c.rb
  Formula/create-dmg.rb
  Formula/csound.rb
  Formula/cvs.rb
  Formula/daemonize.rb
  Formula/dc3dd.rb
  Formula/deno.rb
  Formula/exploitdb.rb
  Formula/kibana.rb
  Formula/netdata.rb
Labels: merge

#19842 Merge 2020-03-12 d43a771dc8
  Formula/bind.rb
  Formula/bitcoin.rb
  Formula/boost-mpi.rb
  Formula/boost-python.rb
  Formula/boost-python3.rb
  Formula/boost.rb
  Formula/cmocka.rb
  Formula/crosstool-ng.rb
  Formula/crystal.rb
  Formula/dlib.rb
  Formula/doxymacs.rb
  Formula/fdroidserver.rb
  Formula/ffmpeg@2.8.rb
  Formula/fontconfig.rb
  Formula/freeling.rb
  Formula/freerdp.rb
  Formula/git.rb
  Formula/gnu-smalltalk.rb
  Formula/grc.rb
  Formula/helm.rb
  Formula/helm@2.rb
  Formula/homeshick.rb
  Formula/libcapn.rb
  Formula/libcddb.rb
  Formula/liblouis.rb
  Formula/libslax.rb
  Formula/mesos.rb
  Formula/mgba.rb
  Formula/mmseqs2.rb
  Formula/mongo-c-driver.rb
  Formula/mutt.rb
  Formula/netpbm.rb
Labels: merge

#19844 Merge 2020-03-13 f62624705a
  Formula/dependency-check.rb
  Formula/docker-machine-driver-xhyve.rb
  Formula/docker-slim.rb
  Formula/drone-cli.rb
  Formula/elasticsearch.rb
  Formula/emojify.rb
  Formula/etcd.rb
  Formula/evince.rb
  Formula/expect.rb
  Formula/ext2fuse.rb
  Formula/fantom.rb
  Formula/nginx.rb
  Formula/ooniprobe.rb
  Formula/open-scene-graph.rb
  Formula/opencv.rb
  Formula/opencv@2.rb
  Formula/opencv@3.rb
  Formula/openssl@1.1.rb
  Formula/pcb2gcode.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
  Formula/portmidi.rb
  Formula/postgresql@10.rb
  Formula/postgresql@9.4.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
  Formula/purescript.rb
  Formula/rabbitmq.rb
  Formula/rbenv.rb
  Formula/shibboleth-sp.rb
  Formula/snownews.rb
  Formula/spdylay.rb
  Formula/weboob.rb
  Formula/xdotool.rb
  Formula/yydecode.rb
  Formula/zero-install.rb
  Formula/zorba.rb
Labels: merge

#19845 Merge 2020-03-13 aefd4418bf
  Formula/advancemenu.rb
  Formula/apache-drill.rb
  Formula/awscli@1.rb
  Formula/bacula-fd.rb
  Formula/buildifier.rb
  Formula/cobalt.rb
  Formula/comby.rb
  Formula/docker-completion.rb
  Formula/docker-slim.rb
  Formula/docker.rb
  Formula/eccodes.rb
  Formula/ensmallen.rb
  Formula/etsh.rb
  Formula/flatbuffers.rb
  Formula/flintrock.rb
  Formula/fn.rb
  Formula/fonttools.rb
  Formula/fq.rb
  Formula/fzf.rb
  Formula/gambit-scheme.rb
  Formula/gdb.rb
  Formula/gerbil-scheme.rb
  Formula/gmsh.rb
  Formula/helm.rb
  Formula/imgproxy.rb
  Formula/instalooter.rb
  Formula/juju.rb
  Formula/kubeprod.rb
  Formula/kubernetes-cli.rb
  Formula/lammps.rb
  Formula/libcouchbase.rb
  Formula/libzdb.rb
  Formula/luit.rb
  Formula/menhir.rb
  Formula/mockolo.rb
  Formula/newrelic-cli.rb
  Formula/nushell.rb
  Formula/ocrmypdf.rb
  Formula/onnxruntime.rb
  Formula/pmd.rb
  Formula/pre-commit.rb
  Formula/protoc-gen-go.rb
  Formula/psc-package.rb
  Formula/pulumi.rb
  Formula/stubby.rb
  Formula/tbox.rb
  Formula/terrahub.rb
  Formula/u-boot-tools.rb
  Formula/zola.rb
Labels: merge

#19848 Merge 2020-03-13 32207943df
  Formula/abduco.rb
  Formula/angular-cli.rb
  Formula/assimp.rb
  Formula/cgoban.rb
  Formula/dmalloc.rb
  Formula/dnsrend.rb
  Formula/f3.rb
  Formula/flac.rb
  Formula/flake8.rb
  Formula/fluxctl.rb
  Formula/fn.rb
  Formula/gambit-scheme.rb
  Formula/gatsby-cli.rb
  Formula/gdcm.rb
  Formula/get_iplayer.rb
  Formula/gimme-aws-creds.rb
  Formula/git-annex-remote-rclone.rb
  Formula/gmt.rb
  Formula/gmt@5.rb
  Formula/grace.rb
  Formula/ibex.rb
  Formula/ncftp.rb
  Formula/ncview.rb
  Formula/pgtune.rb
  Formula/purescript.rb
  Formula/redir.rb
  Formula/sendemail.rb
  Formula/talisman.rb
  Formula/wapm.rb
  Formula/wasmer.rb
Labels: merge

#19849 Merge 2020-03-13 f7a1a17d4a
  Formula/gitleaks.rb
  Formula/gl2ps.rb
  Formula/glade.rb
  Formula/gnome-latex.rb
  Formula/gradle.rb
  Formula/gsar.rb
  Formula/gspell.rb
  Formula/highlighting-kate.rb
  Formula/i2p.rb
  Formula/i2pd.rb
  Formula/i386-elf-grub.rb
  Formula/imgproxy.rb
  Formula/inlets.rb
  Formula/interactive-rebase-tool.rb
  Formula/ipv6calc.rb
  Formula/jnethack.rb
  Formula/k3d.rb
  Formula/kafka.rb
  Formula/katago.rb
  Formula/kibana@5.6.rb
  Formula/krakend.rb
  Formula/kyma-cli.rb
  Formula/latex2rtf.rb
Labels: merge

#19850 Merge 2020-03-13 03fbf2d30d
  Formula/exploitdb.rb
  Formula/gdb.rb
  Formula/killswitch.rb
  Formula/launch_socket_server.rb
  Formula/leela-zero.rb
  Formula/liberasurecode.rb
  Formula/libfido2.rb
  Formula/libntlm.rb
  Formula/libreadline-java.rb
  Formula/libspng.rb
  Formula/libtensorflow.rb
  Formula/libtensorflow@1.rb
  Formula/libwebsockets.rb
  Formula/mallet.rb
  Formula/mesa.rb
  Formula/minizip2.rb
  Formula/miruo.rb
  Formula/mono.rb
  Formula/mpw.rb
  Formula/mu.rb
  Formula/mupen64plus.rb
  Formula/nailgun.rb
  Formula/nbimg.rb
  Formula/nethack.rb
  Formula/nethacked.rb
  Formula/nuvie.rb
  Formula/objc-codegenutils.rb
Labels: merge

#19851 Merge 2020-03-13 20180850f9
  Formula/libgraphqlparser.rb
  Formula/ocaml-findlib.rb
  Formula/ocrmypdf.rb
  Formula/ode.rb
  Formula/openimageio.rb
  Formula/openjdk@11.rb
  Formula/opentracing-cpp.rb
  Formula/opentsdb.rb
  Formula/pass.rb
  Formula/pgrouting.rb
  Formula/phpmd.rb
  Formula/phpstan.rb
  Formula/phpunit.rb
  Formula/pipx.rb
  Formula/pmdmini.rb
  Formula/pyinstaller.rb
  Formula/python.rb
  Formula/python@3.8.rb
  Formula/remarshal.rb
  Formula/remind.rb
  Formula/rex.rb
  Formula/root.rb
  Formula/runcocoa.rb
  Formula/sbuild.rb
  Formula/selenium-server-standalone.rb
  Formula/shadowenv.rb
  Formula/shfmt.rb
  Formula/sile.rb
  Formula/skopeo.rb
  Formula/smimesign.rb
  Formula/sonarqube-lts.rb
  Formula/sonarqube.rb
  Formula/sonobuoy.rb
  Formula/sops.rb
  Formula/sourcery.rb
  Formula/speech-tools.rb
  Formula/spirv-tools.rb
  Formula/sqlcipher.rb
Labels: merge

#19852 Merge 2020-03-13 fd22985e33
  Formula/caf.rb
  Formula/ensmallen.rb
  Formula/ffmpeg@2.8.rb
  Formula/gcsfuse.rb
  Formula/idris.rb
  Formula/mlpack.rb
  Formula/mysql.rb
  Formula/mysql@5.7.rb
  Formula/nethack.rb
  Formula/ospray.rb
  Formula/pcl.rb
  Formula/percona-server.rb
  Formula/php.rb
  Formula/python.rb
  Formula/python@3.8.rb
  Formula/squashfs.rb
  Formula/ssh-permit-a38.rb
  Formula/stellar-core.rb
  Formula/step.rb
  Formula/stolon.rb
  Formula/subversion.rb
  Formula/swiftgen.rb
  Formula/swiftlint.rb
  Formula/sxiv.rb
  Formula/syntaxerl.rb
  Formula/terraformer.rb
  Formula/tesseract.rb
  Formula/tomcat-native.rb
  Formula/v2ray-plugin.rb
  Formula/vapoursynth.rb
  Formula/vert.x.rb
  Formula/vice.rb
  Formula/vowpal-wabbit.rb
  Formula/wandio.rb
  Formula/wasmer.rb
  Formula/weboob.rb
  Formula/zsh.rb
  cmd/postgresql-upgrade-database.rb
Labels: merge

#19854 Merge 2020-03-13 dae4929eb8
  Formula/broot.rb
  Formula/cataclysm.rb
  Formula/cdogs-sdl.rb
  Formula/composer.rb
  Formula/deno.rb
  Formula/dita-ot.rb
  Formula/ghostscript.rb
  Formula/hostess.rb
  Formula/libspectre.rb
  Formula/libtommath.rb
  Formula/libwebsockets.rb
  Formula/liquigraph.rb
  Formula/moarvm.rb
  Formula/nqp.rb
  Formula/okteto.rb
  Formula/procs.rb
  Formula/pyenv.rb
  Formula/rakudo.rb
  Formula/redis.rb
  Formula/sdl2.rb
  Formula/wakatime-cli.rb
  Formula/zabbix-cli.rb
Labels: merge

#19855 Merge 2020-03-14 590483ec21
  Formula/bitwarden-cli.rb
  Formula/firebase-cli.rb
  Formula/fonttools.rb
  Formula/gatsby-cli.rb
  Formula/jam.rb
  Formula/kafka.rb
  Formula/libgr.rb
  Formula/libuv.rb
  Formula/minikube.rb
  Formula/netlify-cli.rb
  Formula/node.rb
Labels: merge

#19856 Merge 2020-03-14 9e36e86ea5
  Formula/cargo-completion.rb
  Formula/gcc.rb
  Formula/ipopt.rb
  Formula/mingw-w64.rb
  Formula/x86_64-elf-gcc.rb
Labels: merge

#19857 Merge 2020-03-14 ace9b61d8b
  Formula/aliyun-cli.rb
  Formula/asdf.rb
  Formula/awsume.rb
  Formula/blink1.rb
  Formula/bnfc.rb
  Formula/c-ares.rb
  Formula/cargo-c.rb
  Formula/cartridge-cli.rb
  Formula/cheat.rb
  Formula/devspace.rb
  Formula/exploitdb.rb
  Formula/get_iplayer.rb
  Formula/gtranslator.rb
  Formula/hapi-fhir-cli.rb
  Formula/neomutt.rb
  Formula/pdnsrec.rb
  Formula/plenv.rb
  Formula/spades.rb
  Formula/virgil.rb
  Formula/wasmer.rb
Labels: merge

#19859 Merge 2020-03-15 56d51cf531
  Formula/azcopy.rb
  Formula/balena-cli.rb
  Formula/bash-completion@2.rb
  Formula/container-structure-test.rb
  Formula/docbook.rb
  Formula/miniserve.rb
  Formula/poppler.rb
  Formula/publish.rb
  Formula/swift-format.rb
  Formula/tomee-plume.rb
  Formula/tomee-plus.rb
  Formula/tomee-webprofile.rb
Labels: merge

#19860 Merge 2020-03-15 d0980a0dcb Merge Homebrew/homebrew-core into Homebrew/linuxbrew-core
  Formula/arp-sk.rb
  Formula/arping.rb
  Formula/arpoison.rb
  Formula/asciidoctor.rb
  Formula/calicoctl.rb
  Formula/dvc.rb
  Formula/ettercap.rb
  Formula/exploitdb.rb
  Formula/fop.rb
  Formula/legit.rb
  Formula/libnet.rb
  Formula/libnids.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/mtoc.rb
  Formula/oclgrind.rb
  Formula/pijul.rb
  Formula/skaffold.rb
  Formula/spades.rb
  Formula/sslsplit.rb
  Formula/suricata.rb
  Formula/tcptraceroute.rb
  Formula/tflint.rb
  Formula/tiny-fugue.rb
  Formula/vice.rb
Labels: merge

#19861 tiny-fugue: depend on ncurses
  Formula/tiny-fugue.rb
Labels: dependency

#19863 Merge 2020-03-16 689c8b39b8
  Formula/appium.rb
  Formula/asciidoctor.rb
  Formula/asciidoctorj.rb
  Formula/dhall-yaml.rb
  Formula/gitlab-gem.rb
  Formula/glooctl.rb
  Formula/golang-migrate.rb
  Formula/gsoap.rb
  Formula/hugo.rb
  Formula/inspircd.rb
  Formula/libarchive.rb
  Formula/nanopb-generator.rb
  Formula/root.rb
  Formula/travis.rb
  Formula/wpscan.rb
  Formula/wtfutil.rb
  Formula/zeek.rb
Labels: merge

#19866 Merge 2020-03-16 bd343981c4
  Formula/dpkg.rb
  Formula/frege.rb
  Formula/httping.rb
  Formula/icarus-verilog.rb
  Formula/libcbor.rb
  Formula/libfido2.rb
  Formula/libvirt.rb
  Formula/ripgrep.rb
  Formula/run.rb
  Formula/selenium-server-standalone.rb
Labels: merge

#19815 pushpin: use Python 3.8
  Formula/pushpin.rb
Labels: python

#19870 Merge 2020-03-16 a07060c7d7
  Formula/gitversion.rb
  Formula/minimal-racket.rb
  Formula/nativefier.rb
  Formula/pushpin.rb
Labels: merge

#19874 Merge 2020-03-17 8106c34699
  Formula/aws-cdk.rb
  Formula/commandbox.rb
  Formula/erlang.rb
  Formula/ethereum.rb
  Formula/futhark.rb
  Formula/kubecfg.rb
  Formula/lego.rb
  Formula/libhdhomerun.rb
  Formula/libuninameslist.rb
  Formula/nift.rb
  Formula/node-build.rb
  Formula/packetq.rb
  Formula/pagmo.rb
  Formula/powerman.rb
  Formula/rancid.rb
  Formula/saxon.rb
  Formula/scala@2.12.rb
Labels: merge

#19875 packetq: fix build for Linux
  Formula/packetq.rb
Labels: dependency

#19880 Merge 2020-03-18 cb54d0e7ee
  Formula/agda.rb
  Formula/buildkit.rb
  Formula/ghostscript.rb
  Formula/glooctl.rb
  Formula/jenkins.rb
  Formula/knot-resolver.rb
  Formula/pgroonga.rb
  Formula/shadowsocks-libev.rb
Labels: merge

#19876 nift: Fix linkage for Linuxbrew
  Formula/nift.rb
Labels: dependency

#19881 Merge 2020-03-17 1d973a5a37
  Formula/bitrise.rb
  Formula/consul.rb
  Formula/dvc.rb
  Formula/exploitdb.rb
  Formula/gatsby-cli.rb
  Formula/goreleaser.rb
  Formula/helm.rb
  Formula/netlify-cli.rb
  Formula/opa.rb
  Formula/ship.rb
Labels: merge

#19882 Merge 2020-03-17 b04f1e2f20
  Formula/cargo-c.rb
  Formula/firebase-cli.rb
  Formula/ghostscript.rb
  Formula/knot-resolver.rb
  Formula/knot.rb
  Formula/kubecfg.rb
  Formula/mailutils.rb
  Formula/mariadb-connector-odbc.rb
  Formula/phpstan.rb
  Formula/teleport.rb
  Formula/tomcat.rb
Labels: merge

#19883 mariadb-connector-odbc: fix bottling for Linux
  Formula/mariadb-connector-odbc.rb
Labels: cellar failure

#19884 Merge 2020-03-18 d7e7114767
  Formula/glibmm.rb
  Formula/guile.rb
  Formula/jbig2dec.rb
  Formula/navi.rb
  Formula/osc.rb
  Formula/plantuml.rb
  Formula/recon-ng.rb
  Formula/syncthing.rb
  Formula/tomcat@8.rb
  Formula/yaegi.rb
Labels: merge

#19888 Merge 2020-03-18 c57ea5af0b
  Formula/exploitdb.rb
  Formula/genometools.rb
  Formula/git-gui.rb
  Formula/git.rb
  Formula/grpcurl.rb
  Formula/tika.rb
  Formula/vpn-slice.rb
  Formula/wildfly-as.rb
  Formula/xz.rb
Labels: merge

#19891 Merge 2020-03-18 f596c1c977
  Formula/doctl.rb
  Formula/gh.rb
  Formula/lazygit.rb
  Formula/leiningen.rb
  Formula/memcached.rb
  Formula/pgbadger.rb
Labels: merge

#19892 Merge 2020-03-19 9584a933d7
  Formula/aws-cdk.rb
  Formula/awscli.rb
  Formula/ccache.rb
  Formula/cfn-lint.rb
  Formula/crc.rb
  Formula/devspace.rb
  Formula/dvc.rb
  Formula/flyway.rb
  Formula/fork-cleaner.rb
  Formula/jfrog-cli-go.rb
  Formula/k6.rb
  Formula/libphonenumber.rb
  Formula/mosquitto.rb
  Formula/netpbm.rb
  Formula/operator-sdk.rb
  Formula/snapcraft.rb
  Formula/teleport.rb
  Formula/v8.rb
  Formula/vim.rb
Labels: merge

#19894 Merge 2020-03-19 722e64cf6a
  Formula/aws-cdk.rb
  Formula/docbook-xsl.rb
  Formula/docker-slim.rb
  Formula/flow.rb
  Formula/gatsby-cli.rb
  Formula/igraph.rb
  Formula/just.rb
  Formula/lazygit.rb
  Formula/mesa.rb
  Formula/miller.rb
  Formula/mmctl.rb
  Formula/pulumi.rb
  Formula/topgrade.rb
  Formula/tor.rb
  Formula/vegeta.rb
Labels: merge

#19902 Merge 2020-03-20 45c0003ff4
  .github/workflows/publish-commit-bottles.yml
  Formula/angular-cli.rb
  Formula/apache-zeppelin.rb
  Formula/ballerina.rb
  Formula/bind.rb
  Formula/catch2.rb
  Formula/ccheck.rb
  Formula/docfx.rb
  Formula/exploitdb.rb
  Formula/gauge.rb
  Formula/glibmm.rb
  Formula/go@1.13.rb
  Formula/grafana.rb
  Formula/helmfile.rb
  Formula/help2man.rb
  Formula/k3d.rb
  Formula/libev.rb
  Formula/libmwaw.rb
  Formula/liquibase.rb
  Formula/mdbook.rb
  Formula/meilisearch.rb
  Formula/minio.rb
  Formula/monero.rb
  Formula/mpw.rb
  Formula/nef.rb
  Formula/nsd.rb
  Formula/overmind.rb
  Formula/php.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
  Formula/plantuml.rb
  Formula/platformio.rb
  Formula/serverless.rb
  Formula/starship.rb
  Formula/terraform.rb
  Formula/tomcat@7.rb
  Formula/whistle.rb
  Formula/wireguard-tools.rb
Labels: merge

#19907 Merge 2020-03-21 93ccdb0feee
  Formula/ballerina.rb
  Formula/diffr.rb
  Formula/gatsby-cli.rb
  Formula/helmfile.rb
  Formula/osquery.rb
  Formula/rocksdb.rb
  Formula/skaffold.rb
  Formula/terraformer.rb
  Formula/thefuck.rb
Labels: merge

#19908 Merge 2020-03-21 48dec09c4b
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#19909 Merge 2020-03-21 724fabcaafa
  .github/workflows/publish-commit-bottles.yml
  Formula/lgogdownloader.rb
  Formula/mpd.rb
Labels: merge

#19910 Merge 2020-03-21 7ae32dc9c1a
  Formula/anime-downloader.rb
  Formula/aws-okta.rb
  Formula/babel.rb
  Formula/cargo-c.rb
  Formula/cassandra-cpp-driver.rb
  Formula/cassandra@2.2.rb
  Formula/cdk8s.rb
  Formula/dnscrypt-proxy.rb
  Formula/dvc.rb
  Formula/emscripten.rb
  Formula/exploitdb.rb
  Formula/fio.rb
  Formula/fluent-bit.rb
  Formula/folly.rb
  Formula/fonttools.rb
  Formula/gedit.rb
  Formula/gitversion.rb
  Formula/hugo.rb
  Formula/katago.rb
  Formula/lxc.rb
  Formula/pangomm.rb
  Formula/phpmyadmin.rb
  Formula/swiftformat.rb
Labels: merge

#19911 Merge 2020-03-22 d69912d55f9
  Formula/collectd.rb
  Formula/comby.rb
  Formula/futhark.rb
  Formula/ghostscript.rb
  Formula/gmime.rb
  Formula/kcptun.rb
  Formula/libspectre.rb
  Formula/tflint.rb
  Formula/tokei.rb
Labels: merge

#19912 Merge 2020-03-22 d5917cf421d
  .github/workflows/publish-commit-bottles.yml
  .github/workflows/tests.yml
  Formula/activemq.rb
  Formula/container-structure-test.rb
  Formula/mednafen.rb
  Formula/prettier.rb
  Formula/tbb.rb
  Formula/tflint.rb
  Formula/varnish.rb
  Formula/vault-cli.rb
Labels: merge

#19913 Merge 2020-03-22 f555326e40e
  Formula/elvish.rb
  Formula/eye-d3.rb
  Formula/ghostscript.rb
  Formula/hugo.rb
Labels: merge

#19914 Merge 2020-03-23 5fb7efa38b
  Formula/antibody.rb
  Formula/automake.rb
  Formula/bat.rb
  Formula/cargo-c.rb
  Formula/cdk8s.rb
  Formula/detekt.rb
  Formula/dnscontrol.rb
  Formula/git-gui.rb
  Formula/git.rb
  Formula/glibmm.rb
  Formula/immortal.rb
  Formula/mmark.rb
  Formula/octant.rb
  Formula/phpstan.rb
  Formula/planck.rb
  Formula/pygments.rb
  Formula/starship.rb
  Formula/travis.rb
  Formula/viewvc.rb
Labels: merge

#19918 Merge 2020-03-24 b9f498cd231
  Formula/assh.rb
  Formula/cargo-c.rb
  Formula/citus.rb
  Formula/cstore_fdw.rb
  Formula/dashing.rb
  Formula/duplicity.rb
  Formula/ephemeralpg.rb
  Formula/fd.rb
  Formula/gnupg.rb
  Formula/pgloader.rb
  Formula/pgroonga.rb
  Formula/pgrouting.rb
  Formula/postgresql.rb
  Formula/postgresql@10.rb
  Formula/postgresql@11.rb
  Formula/postgresql@9.4.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
  Formula/postgrest.rb
  Formula/temporal_tables.rb
  Formula/wal2json.rb
Labels: merge

#19923 Merge 2020-03-24 77d6963bd2f
  Formula/amqp-cpp.rb
  Formula/antibody.rb
  Formula/audacious.rb
  Formula/bazel.rb
  Formula/circleci.rb
  Formula/cmake.rb
  Formula/devspace.rb
  Formula/fastlane.rb
  Formula/firebase-cli.rb
  Formula/gatsby-cli.rb
  Formula/gitlab-runner.rb
  Formula/glooctl.rb
  Formula/helm@2.rb
  Formula/lazygit.rb
  Formula/mimic.rb
  Formula/oil.rb
  Formula/openfortivpn.rb
  Formula/sn0int.rb
  Formula/viewvc.rb
  Formula/xonsh.rb
  Formula/youtube-dl.rb
Labels: merge

#19924 Merge 2020-03-24 949f5c32ffb
  Formula/hiredis.rb
  Formula/jenkins.rb
  Formula/now-cli.rb
  Formula/rke.rb
  Formula/travis.rb
  Formula/vulkan-headers.rb
Labels: merge

#19925 Merge 2020-03-25 373b0ee3b43
  Formula/algernon.rb
  Formula/bnd.rb
  Formula/cfn-lint.rb
  Formula/exploitdb.rb
  Formula/hugo.rb
  Formula/monit.rb
  Formula/pandoc.rb
  Formula/prettier.rb
  Formula/sql-translator.rb
  Formula/vala.rb
  Formula/webpack.rb
Labels: merge

#19927 pandoc: Fix bottling for Linuxbrew
  Formula/pandoc.rb
Labels: cellar failure

#19928 Merge 2020-03-25 9308b614f28
  Aliases/solr@8.5
  Formula/algernon.rb
  Formula/awscli.rb
  Formula/cython.rb
  Formula/dnscrypt-proxy.rb
  Formula/docbook-xsl.rb
  Formula/exploitdb.rb
  Formula/firebase-cli.rb
  Formula/memcached.rb
  Formula/nano.rb
  Formula/nrpe.rb
  Formula/openfortivpn.rb
  Formula/parallel.rb
  Formula/solr.rb
Labels: merge

#19931 Merge 2020-03-25 a7539739bed
  Formula/dvc.rb
  Formula/fonttools.rb
  Formula/rust.rb
  Formula/stella.rb
  Formula/stress-ng.rb
  Formula/xrootd.rb
Labels: merge

#19935 Merge 2020-03-26 b6b8b1c8d94
  Formula/asdf.rb
  Formula/pdftk-java.rb
  Formula/pytouhou.rb
  Formula/traefik.rb
  Formula/traefik@1.rb
Labels: merge

#19939 Merge 2020-03-26 f3a8769e6ae
  Formula/apache-brooklyn-cli.rb
  Formula/aws-cdk.rb
  Formula/cheat.rb
  Formula/etcd.rb
  Formula/hsd.rb
  Formula/minio.rb
  Formula/mmseqs2.rb
  Formula/neomutt.rb
  Formula/prest.rb
  Formula/vegeta.rb
  Formula/whistle.rb
Labels: merge

#19942 Merge 2020-03-26 a0ba32da750
  Formula/docbook.rb
Labels: merge

#19943 Merge 2020-03-26 2107df8d757
  .github/workflows/tests.yml
  Formula/cmake.rb
  Formula/gtk-doc.rb
  Formula/prest.rb
  Formula/stout.rb
  Formula/volt.rb
Labels: merge

#19944 Merge 2020-03-26 26e125fc092
  Formula/angular-cli.rb
  Formula/antibody.rb
  Formula/buildkit.rb
  Formula/citus.rb
  Formula/click.rb
  Formula/dvc.rb
  Formula/gatsby-cli.rb
  Formula/jenkins-lts.rb
  Formula/jenkins.rb
  Formula/kubernetes-cli.rb
  Formula/oauth2_proxy.rb
  Formula/openh264.rb
  Formula/packer.rb
  Formula/percona-toolkit.rb
  Formula/spdylay.rb
  Formula/uftp.rb
  Formula/vowpal-wabbit.rb
Labels: merge

#19947 Merge 2020-03-27 4c716c6fd6d
  Formula/caf.rb
  Formula/cfn-lint.rb
  Formula/click.rb
  Formula/exploitdb.rb
  Formula/gimme-aws-creds.rb
  Formula/glances.rb
  Formula/http-parser.rb
  Formula/libsigc++@2.rb
  Formula/navi.rb
  Formula/pulledpork.rb
  Formula/terraform@0.11.rb
  Formula/uwsgi.rb
Labels: merge

#19948 Merge 2020-03-27 6694aa4040f
  Formula/anycable-go.rb
  Formula/diesel.rb
  Formula/fish.rb
  Formula/gleam.rb
  Formula/gradle.rb
  Formula/graph-tool.rb
  Formula/jemalloc.rb
  Formula/lazygit.rb
  Formula/newsboat.rb
  Formula/r.rb
  Formula/tunnel.rb
Labels: merge

#19950 Merge 2020-03-27 807e9e17e48
  Formula/assh.rb
  Formula/azure-storage-cpp.rb
  Formula/boost.rb
  Formula/closure-compiler.rb
  Formula/dnscrypt-proxy.rb
  Formula/dvc.rb
  Formula/innoextract.rb
  Formula/keydb.rb
  Formula/libtecla.rb
  Formula/mdbook.rb
  Formula/minikube.rb
  Formula/openapi-generator.rb
  Formula/p0f.rb
  Formula/pgplot.rb
  Formula/pueue.rb
  Formula/qmmp.rb
  Formula/rtptools.rb
  Formula/traefik.rb
  Formula/traefik@1.rb
  Formula/vault.rb
  Formula/yaegi.rb
  Formula/yamllint.rb
Labels: merge

#19951 Merge 2020-03-27 8008e210254
  Formula/boost-bcp.rb
  Formula/boost-mpi.rb
  Formula/boost-python.rb
  Formula/boost-python3.rb
  Formula/boost.rb
  Formula/cfn-lint.rb
  Formula/dar.rb
  Formula/dependency-check.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/helm@2.rb
  Formula/joplin.rb
Labels: merge

#19869 joplin: remove Python 2 dependency
  Formula/joplin.rb
Labels: python

#19952 Merge 2020-03-28 4cbcad3549
  Formula/bitrise.rb
  Formula/istioctl.rb
  Formula/simple-scan.rb
  Formula/swift-format.rb
  Formula/vim.rb
Labels: merge

#19953 Merge 2020-03-28 1930cd2cbf
  Formula/asymptote.rb
  Formula/azcopy.rb
  Formula/basex.rb
  Formula/bindfs.rb
  Formula/cmake.rb
  Formula/fish.rb
  Formula/gobo.rb
  Formula/newrelic-cli.rb
  Formula/qmmp.rb
  Formula/tox.rb
Labels: merge

#19954 Merge 2020-03-28 ba7f7dd6d0d
  Formula/flyway.rb
  Formula/freeradius-server.rb
  Formula/gmsh.rb
  Formula/ipmiutil.rb
  Formula/jruby.rb
  Formula/mapserver.rb
  Formula/nativefier.rb
Labels: merge

#19955 Merge 2020-03-29 86181070e3f
  Formula/apibuilder-cli.rb
  Formula/artifactory.rb
  Formula/balena-cli.rb
  Formula/bluepill.rb
  Formula/blueutil.rb
  Formula/bmake.rb
  Formula/cartridge-cli.rb
  Formula/cdk.rb
  Formula/cgns.rb
  Formula/clojure-lsp.rb
  Formula/detekt.rb
  Formula/devspace.rb
  Formula/findomain.rb
  Formula/gsoap.rb
  Formula/hopenpgp-tools.rb
  Formula/jenkins-lts.rb
  Formula/jfrog-cli-go.rb
  Formula/libgsf.rb
  Formula/libsigc++.rb
  Formula/llnode.rb
  Formula/node.rb
  Formula/paket.rb
  Formula/sdl2.rb
  Formula/viewvc.rb
  Formula/wtf.rb
  Formula/znapzend.rb
Labels: merge

#19959 Merge 2020-03-29 1f72fa2b5cb
  Formula/cvs.rb
  Formula/detekt.rb
  Formula/dialog.rb
  Formula/dxpy.rb
  Formula/file-roller.rb
  Formula/folly.rb
  Formula/gatsby-cli.rb
  Formula/git-filter-repo.rb
  Formula/gjs.rb
  Formula/gmic.rb
  Formula/go-bindata.rb
  Formula/hevea.rb
  Formula/ice.rb
  Formula/kotlin.rb
  Formula/mutt.rb
  Formula/nift.rb
  Formula/terragrunt.rb
  Formula/ungit.rb
  Formula/vte3.rb
  Formula/weechat.rb
Labels: merge

#19962 Merge 2020-03-30 fd3c66a099
  Formula/bibutils.rb
  Formula/bundletool.rb
  Formula/calcurse.rb
  Formula/checkstyle.rb
  Formula/comby.rb
  Formula/euler-py.rb
  Formula/exploitdb.rb
  Formula/git-trim.rb
  Formula/glib-networking.rb
  Formula/gtk+3.rb
  Formula/ircd-hybrid.rb
  Formula/jboss-forge.rb
  Formula/jython.rb
  Formula/kpcli.rb
  Formula/kubeseal.rb
  Formula/languagetool.rb
  Formula/meson.rb
  Formula/monero.rb
  Formula/mtools.rb
  Formula/nifi.rb
  Formula/pulumi.rb
  Formula/securefs.rb
  Formula/ungit.rb
  Formula/xmake.rb
Labels: merge

#19964 Merge 2020-03-31 bba318e2b57
  Formula/gitfs.rb
  Formula/gitg.rb
  Formula/gitless.rb
  Formula/gnome-builder.rb
  Formula/libgit2-glib.rb
  Formula/libgit2.rb
  Formula/literate-git.rb
  Formula/lsyncd.rb
  Formula/salt.rb
Labels: merge

#19965 salt: fix build for Linuxbrew
  Formula/salt.rb
Labels: dependency

#19966 Merge 2020-03-31 fc7ac4a5636
  Aliases/llvm@10
  Formula/llvm.rb
  Formula/llvm@9.rb
  Formula/oclgrind.rb
Labels: merge

#19969 Merge 2020-03-31 b3dac032b8e
  Formula/anycable-go.rb
  Formula/dhall-json.rb
  Formula/dhall-lsp-server.rb
  Formula/dhall-yaml.rb
  Formula/dhall.rb
  Formula/eye-d3.rb
  Formula/fluent-bit.rb
  Formula/goreleaser.rb
  Formula/graph-tool.rb
  Formula/helmfile.rb
  Formula/janet.rb
  Formula/jfrog-cli-go.rb
  Formula/lazygit.rb
  Formula/octant.rb
  Formula/pgformatter.rb
  Formula/samurai.rb
  Formula/xcodegen.rb
  Formula/zabbix.rb
  Formula/zero-install.rb
Labels: merge

#19971 Merge 2020-03-31 c0fbbf4a826
  Formula/etcd.rb
  Formula/firebase-cli.rb
  Formula/helmfile.rb
  Formula/jenkins.rb
  Formula/manticoresearch.rb
  Formula/ripgrep.rb
  Formula/tcl-tk.rb
  Formula/vapoursynth-imwri.rb
  Formula/vapoursynth-ocr.rb
  Formula/vapoursynth-sub.rb
  Formula/vapoursynth.rb
  Formula/wireguard-go.rb
Labels: merge

#19973 Merge 2020-03-31 16722fb6599
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#19974 Merge 2020-03-31 457c003d627
  Formula/apache-geode.rb
  Formula/awscli.rb
  Formula/bee.rb
  Formula/glib.rb
  Formula/imapsync.rb
  Formula/jfrog-cli-go.rb
  Formula/kyma-cli.rb
  Formula/libphonenumber.rb
  Formula/monero.rb
  Formula/phpunit.rb
  Formula/rancher-cli.rb
  Formula/rke.rb
  Formula/unrar.rb
  Formula/vert.x.rb
  Formula/vroom.rb
Labels: merge
