Repository Homebrew/linuxbrew-core, pull requests merged in 2020-05, with the labels that each got.

#20266 Merge 2020-05-01 4a7efa7145
  Formula/azure-cli.rb
  Formula/babel.rb
  Formula/ballerina.rb
  Formula/claws-mail.rb
  Formula/ctemplate.rb
  Formula/efl.rb
  Formula/ejabberd.rb
  Formula/exploitdb.rb
  Formula/fargatecli.rb
  Formula/glslang.rb
  Formula/gsettings-desktop-schemas.rb
  Formula/libgr.rb
  Formula/libmypaint.rb
  Formula/monero.rb
  Formula/nift.rb
  Formula/node.rb
  Formula/openconnect.rb
  Formula/quickjs.rb
  Formula/rebar3.rb
  Formula/scrcpy.rb
  Formula/softhsm.rb
  Formula/tmux.rb
  Formula/tmuxinator-completion.rb
  Formula/tmuxinator.rb
  Formula/wtf.rb
  Formula/wxmac.rb
  Formula/zabbix.rb
Labels: merge

#20268 Merge 2020-05-01 118be02bad
  Aliases/redis@6.0
  Formula/ahoy.rb
  Formula/audacious.rb
  Formula/clipsafe.rb
  Formula/colorsvn.rb
  Formula/delta.rb
  Formula/dnstwist.rb
  Formula/elasticsearch.rb
  Formula/gf-complete.rb
  Formula/gotop.rb
  Formula/grsync.rb
  Formula/jerasure.rb
  Formula/kibana.rb
  Formula/kumactl.rb
  Formula/libcroco.rb
  Formula/nef.rb
  Formula/redis.rb
  Formula/sonarqube-lts.rb
  Formula/sonarqube.rb
  Formula/tenyr.rb
Labels: merge

#20270 Merge 2020-05-01 30a58909a1
  Formula/angular-cli.rb
  Formula/balena-cli.rb
  Formula/bazaar.rb
  Formula/earthly.rb
  Formula/flyway.rb
  Formula/graphviz.rb
  Formula/scamper.rb
  Formula/step.rb
  Formula/vault.rb
  Formula/z.rb
Labels: merge

#20274 Merge 2020-05-01 a81e0b1386
  Formula/ace.rb
Labels: merge

#20275 Merge 2020-05-01 433cedc2bd
  .github/workflows/tests.yml
Labels: merge

#20276 Merge 2020-05-01 dc1144c154
  Formula/acpica.rb
  Formula/azcopy.rb
  Formula/chronograf.rb
  Formula/googler.rb
  Formula/gromacs.rb
  Formula/liquigraph.rb
  Formula/mednafen.rb
  Formula/mkvtoolnix.rb
  Formula/mlpack.rb
  Formula/ncmpc.rb
  Formula/swiftformat.rb
Labels: merge

#20277 Merge 2020-05-01 b303dbfdf9
  Formula/gtk+3.rb
Labels: merge

#20278 Merge 2020-05-01 6f0b61d669
  Formula/filebeat.rb
  Formula/pyinstaller.rb
  Formula/redex.rb
  Formula/shyaml.rb
  Formula/snakemake.rb
  Formula/snapcraft.rb
  Formula/tvnamer.rb
  Formula/unoconv.rb
  Formula/yle-dl.rb
  Formula/yosys.rb
Labels: merge

#20282 Merge 2020-05-02 757043b288
  Formula/bison.rb
  Formula/blackbox.rb
  Formula/bluepill.rb
  Formula/exploitdb.rb
  Formula/faas-cli.rb
  Formula/fibjs.rb
  Formula/kind.rb
  Formula/ocrmypdf.rb
  Formula/packer.rb
  Formula/procs.rb
  Formula/questdb.rb
  Formula/re2.rb
  Formula/redis.rb
  Formula/stellar-core.rb
  Formula/supervisor.rb
  Formula/swagger-codegen@2.rb
  Formula/terragrunt.rb
  Formula/tomcat-native.rb
  Formula/wpscan.rb
Labels: merge

#20288 Merge 2020-05-03 da9d15bfa7
  Formula/ansible@2.8.rb
  Formula/charm-tools.rb
  Formula/fb-client.rb
  Formula/liquidctl.rb
  Formula/mps-youtube.rb
  Formula/osc.rb
  Formula/passpie.rb
  Formula/peru.rb
  Formula/pius.rb
  Formula/recon-ng.rb
  Formula/s3ql.rb
  Formula/sslyze.rb
  Formula/tarsnapper.rb
  Formula/termius.rb
  Formula/termtosvg.rb
  Formula/theharvester.rb
  Formula/trezor-agent.rb
Labels: merge

#20292 Merge 2020-05-03 0b738b77a5
  Formula/abcmidi.rb
  Formula/ask-cli.rb
  Formula/cattle.rb
  Formula/cglm.rb
  Formula/dosbox-x.rb
  Formula/ejdb.rb
  Formula/gimme.rb
  Formula/hlint.rb
  Formula/ircd-hybrid.rb
  Formula/ispc.rb
  Formula/libgusb.rb
  Formula/mesa.rb
  Formula/meson-internal.rb
  Formula/molecule.rb
  Formula/mutt.rb
  Formula/oha.rb
  Formula/open-babel.rb
  Formula/osquery.rb
  Formula/pdftk-java.rb
  Formula/phpstan.rb
  Formula/pre-commit.rb
  Formula/simple-scan.rb
  Formula/swift.rb
  Formula/uhd.rb
  Formula/verilator.rb
Labels: merge

#20294 Merge 2020-05-04 46b41b2737
  Formula/cfengine.rb
  Formula/cmark-gfm.rb
  Formula/cmark.rb
  Formula/dhall-bash.rb
  Formula/futhark.rb
  Formula/glslang.rb
  Formula/goreleaser.rb
  Formula/iso-codes.rb
  Formula/livestreamer.rb
  Formula/nicovideo-dl.rb
  Formula/nyx.rb
  Formula/python-markdown.rb
  Formula/spoof-mac.rb
  Formula/ssh-audit.rb
  Formula/yaegi.rb
Labels: merge

#20297 Merge 2020-05-05 bba6ca740d
  Formula/bandwhich.rb
  Formula/django-completion.rb
  Formula/elasticsearch@2.4.rb
  Formula/elasticsearch@5.6.rb
  Formula/exploitdb.rb
  Formula/go@1.10.rb
  Formula/go@1.11.rb
  Formula/go@1.12.rb
  Formula/go@1.9.rb
  Formula/golang-migrate.rb
  Formula/hlint.rb
  Formula/kibana@5.6.rb
  Formula/kops.rb
  Formula/mercurial.rb
  Formula/mkvtomp4.rb
  Formula/mu.rb
  Formula/node-build.rb
  Formula/node_exporter.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
  Formula/phpstan.rb
  Formula/ponysay.rb
  Formula/postgresql@9.4.rb
  Formula/prometheus.rb
  Formula/restview.rb
  Formula/simgrid.rb
  Formula/tmux.rb
Labels: merge

#20298 Merge 2020-05-05 5555006007
  Formula/astrometry-net.rb
  Formula/bison.rb
  Formula/caddy.rb
  Formula/coturn.rb
  Formula/glib-openssl.rb
  Formula/kerl.rb
  Formula/numpy.rb
  Formula/osc.rb
  Formula/pastebinit.rb
  Formula/pyside.rb
  Formula/wallpaper.rb
Labels: merge

#20303 Merge 2020-05-06 5f4608ddaa
  Formula/apache-arrow.rb
  Formula/bison.rb
  Formula/cargo-c.rb
  Formula/clamav.rb
  Formula/exploitdb.rb
  Formula/flow.rb
  Formula/fn.rb
  Formula/folly.rb
  Formula/gradle.rb
  Formula/helm@2.rb
  Formula/libav.rb
  Formula/mupdf.rb
  Formula/paket.rb
  Formula/phpstan.rb
  Formula/prestosql.rb
  Formula/prometheus.rb
  Formula/rancher-cli.rb
  Formula/rke.rb
  Formula/swiftformat.rb
  Formula/tox.rb
  Formula/xonsh.rb
Labels: merge

#20304 Merge 2020-05-06 f1017807b9
  Formula/lv.rb
Labels: merge

#20305 Merge 2020-05-06 cb163da7f4
  Formula/certbot.rb
  Formula/composer.rb
  Formula/contentful-cli.rb
  Formula/duck.rb
  Formula/freetds.rb
  Formula/hugo.rb
  Formula/kops.rb
  Formula/libvirt.rb
  Formula/lmdb.rb
  Formula/mupdf-tools.rb
  Formula/neko.rb
  Formula/nift.rb
  Formula/openapi-generator.rb
  Formula/rargs.rb
  Formula/simple-scan.rb
  Formula/streamripper.rb
  Formula/syncthing.rb
  Formula/terragrunt.rb
  Formula/vim.rb
  Formula/wabt.rb
  Formula/webarchiver.rb
Labels: merge

#20306 certbot: Fix bottling for Linuxbrew
  Formula/certbot.rb
Labels: cellar failure

#20307 Merge 2020-05-07 50345f7e93
  Formula/aws-cdk.rb
  Formula/classads.rb
  Formula/dolt.rb
  Formula/glade.rb
  Formula/gsoap.rb
  Formula/httpflow.rb
  Formula/ipinfo.rb
  Formula/libpqxx.rb
  Formula/libtensorflow.rb
  Formula/mednafen.rb
  Formula/node.rb
  Formula/osmosis.rb
  Formula/paket.rb
  Formula/pygobject3.rb
  Formula/redpen.rb
  Formula/skaffold.rb
  Formula/uutils-coreutils.rb
Labels: merge

#20313 Merge 2020-05-08 628ebe2b5e
  Formula/arangodb.rb
  Formula/chezmoi.rb
  Formula/code-server.rb
  Formula/console_bridge.rb
  Formula/dartsim.rb
  Formula/dvc.rb
  Formula/grc.rb
  Formula/helm.rb
  Formula/jrnl.rb
  Formula/librdkafka.rb
  Formula/libspectre.rb
  Formula/libwebsockets.rb
  Formula/lmod.rb
  Formula/prometheus.rb
  Formula/pylint.rb
  Formula/rex.rb
  Formula/screen.rb
  Formula/tanka.rb
  Formula/teleport.rb
  Formula/tokei.rb
  Formula/urdfdom.rb
  Formula/whistle.rb
  Formula/xa.rb
  Formula/youtube-dl.rb
  Formula/zeek.rb
Labels: merge

#20310 bench: fix bottling for linuxbrew
  Formula/bench.rb
Labels: cellar failure

#20315 Merge 2020-05-09 85a93517ff
  Formula/abook.rb
  Formula/aws-cdk.rb
  Formula/capstone.rb
  Formula/cargo-completion.rb
  Formula/dhall-yaml.rb
  Formula/direnv.rb
  Formula/emscripten.rb
  Formula/exploitdb.rb
  Formula/flarectl.rb
  Formula/gitlab-runner.rb
  Formula/gleam.rb
  Formula/hdf5-mpi.rb
  Formula/jc.rb
  Formula/lc0.rb
  Formula/openstackclient.rb
  Formula/orc-tools.rb
  Formula/oxipng.rb
  Formula/prometheus.rb
  Formula/sd.rb
  Formula/serverless.rb
  Formula/skaffold.rb
  Formula/sysdig.rb
  Formula/topgrade.rb
  Formula/yaegi.rb
Labels: merge

#20316 Merge 2020-05-09 f88de7bda85
  Formula/balena-cli.rb
  Formula/bluetoothconnector.rb
  Formula/cartridge-cli.rb
  Formula/circleci.rb
  Formula/dhall-json.rb
  Formula/dhall-lsp-server.rb
  Formula/dhall.rb
  Formula/earthly.rb
  Formula/eslint.rb
  Formula/exploitdb.rb
  Formula/forcecli.rb
  Formula/fplll.rb
  Formula/gatsby-cli.rb
  Formula/git-lfs.rb
  Formula/knot.rb
  Formula/kyma-cli.rb
  Formula/leakcanary-shark.rb
  Formula/lxc.rb
  Formula/micronaut.rb
  Formula/netlify-cli.rb
  Formula/terragrunt.rb
Labels: merge

#20314 jrnl: fix dependencies for Linuxbrew
  Formula/jrnl.rb
Labels: dependency

#20317 gleam: add missing dependency for Linuxbrew
  Formula/gleam.rb
Labels: dependency

#20319 Merge 2020-05-10 8417673871
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20320 Merge 2020-05-10 0662d7917c
  Formula/angular-cli.rb
  Formula/apollo-cli.rb
  Formula/aurora-cli.rb
  Formula/babl.rb
  Formula/baobab.rb
  Formula/bde.rb
  Formula/bento4.rb
  Formula/clojurescript.rb
  Formula/conan.rb
  Formula/consul.rb
  Formula/erlang.rb
  Formula/exploitdb.rb
  Formula/helmfile.rb
  Formula/hlint.rb
  Formula/ipfs.rb
  Formula/kubeseal.rb
  Formula/leakcanary-shark.rb
  Formula/libphonenumber.rb
  Formula/maxwell.rb
  Formula/mm-common.rb
  Formula/molten-vk.rb
  Formula/nanopb-generator.rb
  Formula/poetry.rb
  Formula/protobuf.rb
  Formula/salt.rb
  Formula/sollya.rb
  Formula/stone-soup.rb
  Formula/tundra.rb
  Formula/uwsgi.rb
  Formula/xxh.rb
Labels: merge

#20322 Merge 2020-05-10 f74123298d
  Formula/abcmidi.rb
  Formula/aliyun-cli.rb
  Formula/ammonite-repl.rb
  Formula/appium.rb
  Formula/bmake.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/libfabric.rb
  Formula/libressl.rb
  Formula/movgrab.rb
  Formula/ngt.rb
  Formula/now-cli.rb
  Formula/oha.rb
  Formula/okteto.rb
  Formula/pngpaste.rb
  Formula/protoc-gen-go.rb
  Formula/ripgrep.rb
  Formula/serf.rb
  Formula/testssl.rb
  Formula/tmux-xpanes.rb
  Formula/whistle.rb
  Formula/wildfly-as.rb
  Formula/zero-install.rb
Labels: merge

#20324 Merge 2020-05-10 ddb25c9201
  Aliases/bison@3.6
  Formula/amqp-cpp.rb
  Formula/ask-cli.rb
  Formula/aws-sdk-cpp.rb
  Formula/awscli@1.rb
  Formula/bison.rb
  Formula/citus.rb
  Formula/clojure-lsp.rb
  Formula/closure-compiler.rb
  Formula/clp.rb
  Formula/couchdb.rb
  Formula/dmagnetic.rb
  Formula/duplicity.rb
  Formula/e2fsprogs.rb
  Formula/ext2fuse.rb
  Formula/frugal.rb
  Formula/gitleaks.rb
  Formula/gopass.rb
  Formula/libplctag.rb
  Formula/mg.rb
  Formula/picat.rb
  Formula/semgrep.rb
  Formula/tealdeer.rb
  Formula/wtfutil.rb
Labels: merge

#20325 appium: fix test for Linux
  Formula/appium.rb
Labels: test failure

#20326 Merge 2020-05-11 acff19b4fa
  Formula/bison.rb
  Formula/gnumeric.rb
  Formula/goffice.rb
  Formula/jupyterlab.rb
  Formula/katago.rb
  Formula/moarvm.rb
  Formula/mu.rb
  Formula/mvtools.rb
  Formula/nqp.rb
  Formula/oauth2_proxy.rb
  Formula/open-babel.rb
  Formula/opencc.rb
  Formula/pcre2.rb
  Formula/plantuml.rb
  Formula/r.rb
  Formula/rakudo.rb
  Formula/rust.rb
  Formula/terragrunt.rb
  Formula/vagrant-completion.rb
  Formula/vapoursynth-imwri.rb
  Formula/vapoursynth-ocr.rb
  Formula/vapoursynth-sub.rb
  Formula/vapoursynth.rb
  Formula/volta.rb
  Formula/webtorrent-cli.rb
  Formula/z3.rb
Labels: merge

#20328 Merge 2020-05-11 0157496f039
  Formula/arangodb.rb
  Formula/contentful-cli.rb
  Formula/crystal.rb
  Formula/curl-openssl.rb
  Formula/doxygen.rb
  Formula/git-quick-stats.rb
  Formula/glib-openssl.rb
  Formula/glooctl.rb
  Formula/jansson.rb
  Formula/katago.rb
  Formula/minimal-racket.rb
  Formula/netpbm.rb
  Formula/openssl@1.1.rb
  Formula/osc.rb
  Formula/php.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
  Formula/phpstan.rb
  Formula/proteinortho.rb
  Formula/proxytunnel.rb
  Formula/pwntools.rb
  Formula/python-markdown.rb
  Formula/ripgrep.rb
  Formula/sleuthkit.rb
  Formula/snownews.rb
  Formula/sonarqube.rb
  Formula/tengo.rb
  Formula/texlab.rb
  Formula/tmuxinator-completion.rb
  Formula/treefrog.rb
  Formula/ungit.rb
  Formula/urdfdom_headers.rb
  Formula/v8.rb
  Formula/vale.rb
  Formula/vfuse.rb
  Formula/vpn-slice.rb
  Formula/wartremover.rb
Labels: merge

#20329 Merge 2020-05-11 cb11462997
  Formula/benthos.rb
  Formula/concurrencykit.rb
  Formula/gexiv2.rb
  Formula/gnutls.rb
  Formula/gom.rb
  Formula/jansson.rb
  Formula/lc0.rb
  Formula/mavsdk.rb
  Formula/mill.rb
  Formula/mvnvm.rb
  Formula/semgrep.rb
  Formula/weechat.rb
  Formula/xrootd.rb
Labels: merge

#20333 Merge 2020-05-11 c75780ec82
  Formula/babl.rb
  Formula/baobab.rb
  Formula/file-roller.rb
  Formula/gcab.rb
  Formula/gdk-pixbuf.rb
  Formula/ghex.rb
  Formula/glib-networking.rb
  Formula/gnome-recipes.rb
  Formula/graphene.rb
  Formula/gsettings-desktop-schemas.rb
  Formula/gtranslator.rb
  Formula/jenkins.rb
  Formula/jsonrpc-glib.rb
  Formula/libdazzle.rb
  Formula/libepoxy.rb
  Formula/libgweather.rb
  Formula/simple-scan.rb
  Formula/sourcedocs.rb
  Formula/template-glib.rb
Labels: merge

#20336 Merge 2020-05-12 d9fdc94240f
  Formula/balena-cli.rb
  Formula/bat.rb
  Formula/bindfs.rb
  Formula/c-ares.rb
  Formula/cassandra-cpp-driver.rb
  Formula/cheat.rb
  Formula/circleci.rb
  Formula/clojure-lsp.rb
  Formula/cppcheck.rb
  Formula/embree.rb
  Formula/fauna-shell.rb
  Formula/fetchmail.rb
  Formula/fmt.rb
  Formula/gh.rb
  Formula/gnu-chess.rb
  Formula/goreleaser.rb
  Formula/hpack.rb
  Formula/inlets.rb
  Formula/janet.rb
  Formula/kumo.rb
  Formula/kustomize.rb
  Formula/minikube.rb
  Formula/now-cli.rb
  Formula/procs.rb
  Formula/pulumi.rb
  Formula/redpen.rb
  Formula/serverless.rb
  Formula/sickle.rb
  Formula/translate-shell.rb
  Formula/travis.rb
  Formula/weaver.rb
  Formula/wireguard-tools.rb
Labels: merge

#20339 Merge 2020-05-13 bfa681db81
  Formula/chezmoi.rb
  Formula/clamav.rb
  Formula/code-server.rb
  Formula/dolt.rb
  Formula/exploitdb.rb
  Formula/fastlane.rb
  Formula/harfbuzz.rb
  Formula/libfido2.rb
  Formula/libqalculate.rb
  Formula/minikube.rb
  Formula/netdata.rb
  Formula/netlify-cli.rb
  Formula/openimageio.rb
  Formula/pre-commit.rb
  Formula/qalculate-gtk.rb
  Formula/quill.rb
  Formula/reorder-python-imports.rb
  Formula/terragrunt.rb
  Formula/tomcat.rb
  Formula/tomcat@8.rb
  Formula/zabbix.rb
Labels: merge

#20340 Merge 2020-05-13 a59d5e0dd9
  Formula/claws-mail.rb
  Formula/epic5.rb
  Formula/ffsend.rb
  Formula/gnutls.rb
  Formula/gst-plugins-bad.rb
  Formula/hopenpgp-tools.rb
  Formula/istioctl.rb
  Formula/kumactl.rb
  Formula/kyma-cli.rb
  Formula/lazygit.rb
  Formula/mas.rb
  Formula/memcached.rb
  Formula/netdata.rb
  Formula/nettle.rb
  Formula/pike.rb
  Formula/qemu.rb
  Formula/rdesktop.rb
  Formula/rdfind.rb
  Formula/rdup.rb
  Formula/s3fs.rb
  Formula/sslyze.rb
  Formula/stoken.rb
  Formula/typescript.rb
  Formula/uncrustify.rb
  Formula/vim.rb
Labels: merge

#20341 Merge 2020-05-13 5326934c838
  Formula/caf.rb
  Formula/exploitdb.rb
  Formula/frotz.rb
  Formula/monolith.rb
  Formula/rbspy.rb
  Formula/shared-mime-info.rb
  Formula/terraform.rb
  Formula/zeek.rb
Labels: merge

#20342 Merge 2020-05-14 62891a0f49
  Formula/cdk8s.rb
  Formula/clingo.rb
  Formula/deno.rb
  Formula/flake8.rb
  Formula/gopass.rb
  Formula/katago.rb
  Formula/mapserver.rb
  Formula/php.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
  Formula/pidgin.rb
  Formula/protobuf-swift.rb
  Formula/protobuf@3.7.rb
  Formula/pulumi.rb
  Formula/pycodestyle.rb
  Formula/qemu.rb
  Formula/repo.rb
  Formula/snakemake.rb
  Formula/stress-ng.rb
  Formula/swiftformat.rb
  Formula/tccutil.rb
  Formula/topgrade.rb
Labels: merge

#20346 Merge 2020-05-15 defc021c41
  Formula/ammonite-repl.rb
  Formula/angular-cli.rb
  Formula/ask-cli.rb
  Formula/bazel.rb
  Formula/borgmatic.rb
  Formula/conan.rb
  Formula/contentful-cli.rb
  Formula/detekt.rb
  Formula/ethereum.rb
  Formula/exploitdb.rb
  Formula/fastlane.rb
  Formula/gatsby-cli.rb
  Formula/ghz.rb
  Formula/gwt.rb
  Formula/homeassistant-cli.rb
  Formula/lerna.rb
  Formula/libdeflate.rb
  Formula/libmypaint.rb
  Formula/libwebsockets.rb
  Formula/salt.rb
Labels: merge

#20343 update sha256 for gzipped patchelf.
  Formula/patchelf.rb
Labels: do not merge, gsoc-outreachy

#20347 Merge 2020-05-15 53fc2c72df
  Formula/caffe.rb
  Formula/ctl.rb
  Formula/dmd.rb
  Formula/easy-tag.rb
  Formula/embree.rb
  Formula/flow.rb
  Formula/ghz.rb
  Formula/grpcurl.rb
  Formula/gucharmap.rb
  Formula/highlight.rb
  Formula/ilmbase.rb
  Formula/lizard-analyzer.rb
  Formula/mesa.rb
  Formula/nift.rb
  Formula/openexr.rb
  Formula/rbtools.rb
  Formula/singular.rb
  Formula/tor.rb
Labels: merge

#20349 Merge 2020-05-15 fbb93aa632
  Formula/caffe.rb
  Formula/ctl.rb
  Formula/folly.rb
  Formula/ilmbase.rb
  Formula/imagemagick.rb
  Formula/imgproxy.rb
  Formula/lcm.rb
  Formula/mono.rb
  Formula/nats-server.rb
  Formula/opencv.rb
  Formula/opencv@2.rb
  Formula/opencv@3.rb
  Formula/openexr.rb
  Formula/openimageio.rb
  Formula/openvdb.rb
  Formula/postgresql.rb
  Formula/rawtoaces.rb
  Formula/spirv-tools.rb
  Formula/starship.rb
  Formula/synfig.rb
  Formula/vips.rb
Labels: merge

#20352 Merge 2020-05-16 176a3ed49b
  Formula/fmt.rb
  Formula/libproxy.rb
  Formula/libtcod.rb
  Formula/llnode.rb
  Formula/macvim.rb
  Formula/pyside.rb
Labels: merge

#20354 Merge 2020-05-16 2688e195ecb
  Formula/anime-downloader.rb
  Formula/ant.rb
  Formula/diffoscope.rb
  Formula/efl.rb
  Formula/fdroidserver.rb
  Formula/flow.rb
  Formula/futhark.rb
  Formula/git-plus.rb
  Formula/homebank.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jc.rb
  Formula/jrnl.rb
  Formula/lmod.rb
  Formula/mkdocs.rb
  Formula/nomad.rb
  Formula/openfortivpn.rb
  Formula/python-yq.rb
  Formula/spdlog.rb
  Formula/tflint.rb
Labels: merge

#20360 Merge 2020-05-17 f3135f849d
  Formula/anime-downloader.rb
  Formula/basex.rb
  Formula/bison.rb
  Formula/exploitdb.rb
  Formula/findent.rb
  Formula/fluent-bit.rb
  Formula/flyway.rb
  Formula/glooctl.rb
  Formula/hebcal.rb
  Formula/hpack.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jhipster.rb
  Formula/libhttpserver.rb
  Formula/liquibase.rb
  Formula/plantuml.rb
  Formula/redis.rb
  Formula/sonobuoy.rb
  Formula/sqlcipher.rb
  Formula/tth.rb
  Formula/urh.rb
Labels: merge

#20361 Merge 2020-05-18 a9b829fa23
  Formula/haskell-stack.rb
Labels: merge

#20363 Merge 2020-05-18 a47b3f69ac9
  Formula/adplug.rb
  Formula/augustus.rb
  Formula/ballerina.rb
  Formula/benthos.rb
  Formula/cgns.rb
  Formula/code-server.rb
  Formula/contentful-cli.rb
  Formula/deno.rb
  Formula/dungeon.rb
  Formula/ffsend.rb
  Formula/glances.rb
  Formula/janet.rb
  Formula/libmemcached.rb
  Formula/libpq.rb
  Formula/libwebsockets.rb
  Formula/mariadb.rb
  Formula/mdv.rb
  Formula/mercury.rb
  Formula/mockolo.rb
  Formula/monolith.rb
  Formula/mu.rb
  Formula/netdata.rb
  Formula/pari.rb
  Formula/pipx.rb
  Formula/rdiff-backup.rb
  Formula/rtorrent.rb
  Formula/whistle.rb
  Formula/xgboost.rb
Labels: merge

#20375 Merge 2020-05-19 e39bef2a12f
  Formula/batik.rb
  Formula/clip.rb
  Formula/devspace.rb
  Formula/duo_unix.rb
  Formula/evince.rb
  Formula/field3d.rb
  Formula/gnome-builder.rb
  Formula/goreleaser.rb
  Formula/ngt.rb
  Formula/nushell.rb
  Formula/pfetch.rb
  Formula/rom-tools.rb
  Formula/sane-backends.rb
  Formula/skopeo.rb
  Formula/vulkan-headers.rb
Labels: merge

#20377 Merge 2020-05-20 10ef853b4e
  Formula/ansible.rb
  Formula/bind.rb
  Formula/calicoctl.rb
  Formula/closure-compiler.rb
  Formula/cosi.rb
  Formula/daq.rb
  Formula/dasm.rb
  Formula/docfx.rb
  Formula/etcd.rb
  Formula/exploitdb.rb
  Formula/freetds.rb
  Formula/goose.rb
  Formula/imgproxy.rb
  Formula/lazygit.rb
  Formula/librsync.rb
  Formula/libtorch.rb
  Formula/maxwell.rb
  Formula/mmctl.rb
  Formula/pnpm.rb
  Formula/postgresql.rb
  Formula/ruby-build.rb
  Formula/sentencepiece.rb
  Formula/singular.rb
Labels: merge

#20380 Merge 2020-05-20 34c2c0f674
  Formula/circleci.rb
  Formula/ffmpeg.rb
  Formula/git.rb
  Formula/gleam.rb
  Formula/goaccess.rb
  Formula/postgresql@10.rb
  Formula/postgresql@11.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
  Formula/ripgrep-all.rb
Labels: merge

#20388 Merge 2020-05-20 a51dbf82440
  Formula/apache-arrow-glib.rb
  Formula/apache-arrow.rb
  Formula/fontforge.rb
  Formula/libspiro.rb
  Formula/node.rb
  Formula/posh.rb
  Formula/ruby-build.rb
  Formula/swagger-codegen.rb
  Formula/swift-protobuf.rb
  Formula/tox.rb
  Formula/typescript.rb
  Formula/vapoursynth.rb
  Formula/vert.x.rb
  Formula/wtf.rb
Labels: merge

#20390 Merge 2020-05-21 57a75a24f25
  Aliases/protobuf@3.12
  Formula/apache-arrow.rb
  Formula/aws-cdk.rb
  Formula/caffe.rb
  Formula/contentful-cli.rb
  Formula/cqlkit.rb
  Formula/csvq.rb
  Formula/cython.rb
  Formula/datetime-fortran.rb
  Formula/deno.rb
  Formula/emscripten.rb
  Formula/exploitdb.rb
  Formula/fonttools.rb
  Formula/fop.rb
  Formula/gitlab-runner.rb
  Formula/glib.rb
  Formula/go-jsonnet.rb
  Formula/grpc.rb
  Formula/libksba.rb
  Formula/libphonenumber.rb
  Formula/libpulsar.rb
  Formula/libtorch.rb
  Formula/monero.rb
  Formula/mosh.rb
  Formula/mysql.rb
  Formula/opencv.rb
  Formula/protobuf-c.rb
  Formula/protobuf.rb
  Formula/protoc-gen-grpc-web.rb
  Formula/serverless.rb
  Formula/shogun.rb
  Formula/timidity.rb
  Formula/ucloud.rb
  Formula/yaegi.rb
  Formula/zbackup.rb
Labels: merge

#20391 Merge 2020-05-21 3c746241a0
  Formula/apollo-cli.rb
  Formula/ask-cli.rb
  Formula/asuka.rb
  Formula/awscli.rb
  Formula/cloc.rb
  Formula/cqlkit.rb
  Formula/dav1d.rb
  Formula/dovecot.rb
  Formula/erlang@21.rb
  Formula/exploitdb.rb
  Formula/freerdp.rb
  Formula/gatsby-cli.rb
  Formula/grpc.rb
  Formula/kubernetes-service-catalog-client.rb
  Formula/libarchive.rb
  Formula/lmod.rb
  Formula/mdcat.rb
  Formula/mill.rb
  Formula/okteto.rb
  Formula/openfortivpn.rb
  Formula/serverless.rb
  Formula/skaffold.rb
  Formula/tile38.rb
Labels: merge

#20394 Merge 2020-05-22 f9461a29f7
  Formula/postgresql.rb
  Formula/postgresql@10.rb
  Formula/postgresql@11.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
Labels: merge

#20396 libexif: fix bottling for Linuxbrew
  Formula/libexif.rb
Labels: cellar failure

#20399 Merge 2020-05-22 fbba5c5681
  Formula/awscli.rb
  Formula/chamber.rb
  Formula/codespell.rb
  Formula/csvq.rb
  Formula/dnstwist.rb
  Formula/ffmpeg.rb
  Formula/firebase-cli.rb
  Formula/gcviewer.rb
  Formula/groovy.rb
  Formula/groovysdk.rb
  Formula/htmlcleaner.rb
  Formula/jena.rb
  Formula/kitchen-sync.rb
  Formula/mikutter.rb
  Formula/opa.rb
  Formula/pachi.rb
  Formula/pgrouting.rb
  Formula/snakemake.rb
  Formula/tengo.rb
  Formula/wireshark.rb
Labels: merge

#20389 .github: Use image homebrew/ubuntu16.04:master
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/request-bottle-after-merge.yml
  .github/workflows/tests.yml
  .github/workflows/upload-bottles.yml
Labels: do not merge, enhancement

#20401 crystal: build
  Formula/crystal.rb
  Formula/llvm.rb
Labels: do not merge

#20404 Merge 2020-05-23 77babe22b6
  .github/workflows/publish-commit-bottles.yml
  .github/workflows/scheduled.yml
Labels: merge

#20409 Merge 2020-05-23 8395d17ac95
  Formula/contentful-cli.rb
  Formula/corral.rb
  Formula/deno.rb
  Formula/eslint.rb
  Formula/etcd.rb
  Formula/eva.rb
  Formula/exploitdb.rb
  Formula/freeipmi.rb
  Formula/gatsby-cli.rb
  Formula/gau.rb
  Formula/git-annex.rb
  Formula/gitlab-gem.rb
  Formula/go-jsonnet.rb
  Formula/gocloc.rb
  Formula/gomplate.rb
  Formula/gr-osmosdr.rb
  Formula/kde-extra-cmake-modules.rb
  Formula/netpbm.rb
  Formula/opa.rb
  Formula/ponyc.rb
  Formula/protobuf.rb
  Formula/sundials.rb
  Formula/swiftformat.rb
  Formula/transmission-cli.rb
  Formula/unbound.rb
  Formula/vault.rb
Labels: merge

#20406 shared-mime-info: build for Linux
  Formula/shared-mime-info.rb
Labels: cellar failure

#20423 exif: rebuild with right glibc version
  Formula/exif.rb
  Formula/libexif.rb
Labels: do not merge

#20402 osmfilter: adding zlib-dependency (again)
  Formula/osmfilter.rb
Labels: do not merge

#20429 Merge 2020-05-24 8d94a700b70
  Formula/aliyun-cli.rb
  Formula/ansible@2.8.rb
  Formula/ant@1.9.rb
  Formula/asciinema.rb
  Formula/aws-sdk-cpp.rb
  Formula/b3sum.rb
  Formula/bandwhich.rb
  Formula/cdk8s.rb
  Formula/cointop.rb
  Formula/confluent-platform.rb
  Formula/console_bridge.rb
  Formula/dasht.rb
  Formula/debianutils.rb
  Formula/diffoscope.rb
  Formula/dnscontrol.rb
  Formula/fastd.rb
  Formula/freetds.rb
  Formula/gexiv2.rb
  Formula/git-cola.rb
  Formula/goreleaser.rb
  Formula/grpc-swift.rb
  Formula/haxe.rb
  Formula/iam-policy-json-to-terraform.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jc.rb
  Formula/jetty-runner.rb
  Formula/jetty.rb
  Formula/jsonnet.rb
  Formula/krb5.rb
  Formula/libfreenect.rb
  Formula/libngspice.rb
  Formula/libnice.rb
  Formula/libressl.rb
  Formula/micro.rb
  Formula/nano.rb
  Formula/nift.rb
  Formula/pgpool-ii.rb
  Formula/platformio.rb
  Formula/pnpm.rb
  Formula/postgrest.rb
  Formula/purescript.rb
  Formula/signal-cli.rb
  Formula/sngrep.rb
  Formula/spirv-cross.rb
  Formula/swift.rb
  Formula/tengo.rb
  Formula/terragrunt.rb
Labels: merge

#20432 Merge 2020-05-25 c919ad5d08
  Formula/cdo.rb
  Formula/go-bindata.rb
  Formula/gsoap.rb
  Formula/helmfile.rb
  Formula/libpulsar.rb
  Formula/mariadb@10.1.rb
  Formula/mariadb@10.2.rb
  Formula/mariadb@10.3.rb
  Formula/ngspice.rb
  Formula/repo.rb
  Formula/snapraid.rb
  Formula/spice-protocol.rb
  Formula/spim.rb
  Formula/terraformer.rb
  Formula/wandio.rb
  Formula/xxh.rb
Labels: merge

#20433 Merge 2020-05-25 faaf9a73382
  Formula/balena-cli.rb
  Formula/benthos.rb
  Formula/btfs.rb
  Formula/contentful-cli.rb
  Formula/debianutils.rb
  Formula/dgraph.rb
  Formula/flake8.rb
  Formula/gdb.rb
  Formula/hugo.rb
  Formula/idris.rb
  Formula/jc.rb
  Formula/lanraragi.rb
  Formula/mariadb-connector-c.rb
  Formula/mas.rb
  Formula/monero.rb
  Formula/parallel.rb
  Formula/pmd.rb
  Formula/qrcp.rb
  Formula/roswell.rb
  Formula/subnetcalc.rb
  Formula/xmrig.rb
Labels: merge

#20434 Merge 2020-05-26 708868e9ce
  Formula/curaengine.rb
  Formula/duckdb.rb
  Formula/flamegraph.rb
  Formula/game-music-emu.rb
  Formula/i2pd.rb
  Formula/node-build.rb
  Formula/opencc.rb
  Formula/quazip.rb
  Formula/sfk.rb
  Formula/sundials.rb
  Formula/zola.rb
Labels: merge

#20435 sundials: fix test for Linuxbrew
  Formula/sundials.rb
Labels: test failure

#20436 Merge 2020-05-26 898ef32d44
  Formula/bmake.rb
  Formula/freeswitch.rb
  Formula/just.rb
  Formula/mill.rb
  Formula/paket.rb
  Formula/pdnsrec.rb
  Formula/phoronix-test-suite.rb
  Formula/pspg.rb
Labels: merge

#20438 Merge 2020-05-26 cc21f19622
  Formula/bat.rb
  Formula/catch2.rb
  Formula/folly.rb
  Formula/git-absorb.rb
  Formula/h2o.rb
  Formula/hyperfine.rb
  Formula/hyperscan.rb
  Formula/jenv.rb
  Formula/kakoune.rb
  Formula/mdcat.rb
  Formula/nanomsg.rb
  Formula/ngt.rb
  Formula/nng.rb
  Formula/openvdb.rb
  Formula/percona-server.rb
  Formula/singular.rb
  Formula/stubby.rb
  Formula/ucloud.rb
Labels: merge

#20439 Merge 2020-05-27 902c3f8939
  Formula/bat.rb
  Formula/botan.rb
  Formula/cassandra-reaper.rb
  Formula/detekt.rb
  Formula/gh.rb
  Formula/grafana.rb
  Formula/graphql-cli.rb
  Formula/helmsman.rb
  Formula/i2p.rb
  Formula/jenkins.rb
  Formula/macvim.rb
  Formula/minizip2.rb
  Formula/mutt.rb
  Formula/nauty.rb
  Formula/pcl.rb
  Formula/rbtools.rb
  Formula/twarc.rb
  Formula/two-lame.rb
  Formula/ungit.rb
  Formula/velero.rb
  Formula/zookeeper.rb
Labels: merge

#20440 Merge 2020-05-27 ac288c1eed5
  Formula/aws-cdk.rb
  Formula/awscli.rb
  Formula/bat.rb
  Formula/coq.rb
  Formula/exploitdb.rb
  Formula/fades.rb
  Formula/fd.rb
  Formula/flac.rb
  Formula/fossil.rb
  Formula/futhark.rb
  Formula/gh.rb
  Formula/gst-validate.rb
  Formula/libao.rb
  Formula/libogg.rb
  Formula/libopusenc.rb
  Formula/libvorbis.rb
  Formula/libxspf.rb
  Formula/math-comp.rb
  Formula/nginx.rb
  Formula/node@12.rb
  Formula/opus-tools.rb
  Formula/opus.rb
  Formula/opusfile.rb
  Formula/passenger.rb
  Formula/pipx.rb
  Formula/reminiscence.rb
  Formula/sourcedocs.rb
  Formula/sphinx-doc.rb
  Formula/texlab.rb
  Formula/tfenv.rb
  Formula/theora.rb
  Formula/wimlib.rb
Labels: merge

#20443 libepoxy: fix bottling for Linuxbrew
  Formula/libepoxy.rb
Labels: cellar failure

#20444 Merge 2020-05-28 7bc1a9c574
  Formula/bazel.rb
  Formula/cdk8s.rb
  Formula/exploitdb.rb
  Formula/netlify-cli.rb
  Formula/nnn.rb
  Formula/nvc.rb
  Formula/pulumi.rb
  Formula/rclone.rb
  Formula/semgrep.rb
  Formula/terraform.rb
Labels: merge

#20445 Merge 2020-05-28 9ecf6990a8
  Formula/hiredis.rb
  Formula/jsvc.rb
  Formula/pdf2htmlex.rb
  Formula/redis.rb
  Formula/redis@3.2.rb
  Formula/redis@4.0.rb
  Formula/snap7.rb
Labels: merge

#20446 Merge 2020-05-29 3884f14082
  Formula/kustomize.rb
  Formula/newrelic-cli.rb
  Formula/openssh.rb
  Formula/rrdtool.rb
  Formula/stone-soup.rb
  Formula/subversion.rb
  Formula/uwsgi.rb
Labels: merge

#20448 Merge 2020-05-29 fa1d1d56db
  Formula/plenv.rb
  Formula/postgresql.rb
  Formula/postgresql@10.rb
  Formula/postgresql@11.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
  Formula/swiftformat.rb
Labels: merge

#20449 Merge 2020-05-29 36d966c9de
  Formula/code-server.rb
  Formula/flyway.rb
  Formula/gatsby-cli.rb
  Formula/gobject-introspection.rb
  Formula/libbladerf.rb
  Formula/mesa.rb
  Formula/node_exporter.rb
  Formula/pdfcpu.rb
  Formula/pipenv.rb
  Formula/pnpm.rb
  Formula/redis.rb
  Formula/teleport.rb
  Formula/tokei.rb
  Formula/tomee-plume.rb
  Formula/tomee-plus.rb
  Formula/tomee-webprofile.rb
  Formula/wasm-pack.rb
  Formula/zenith.rb
Labels: merge

#20454 Merge 2020-05-30 051c129736
  Formula/amazon-ecs-cli.rb
  Formula/bwfmetaedit.rb
  Formula/cddlib.rb
  Formula/cmake.rb
  Formula/contentful-cli.rb
  Formula/cpputest.rb
  Formula/dnsdist.rb
  Formula/exploitdb.rb
  Formula/ghz-web.rb
  Formula/gnu-getopt.rb
  Formula/google-authenticator-libpam.rb
  Formula/guile.rb
  Formula/helmfile.rb
  Formula/kubeaudit.rb
  Formula/kubernetes-service-catalog-client.rb
  Formula/libcpuid.rb
  Formula/libwebsockets.rb
  Formula/protobuf.rb
  Formula/protobuf@3.6.rb
  Formula/protobuf@3.7.rb
  Formula/pspg.rb
  Formula/r.rb
  Formula/spdlog.rb
  Formula/spotifyd.rb
  Formula/stubby.rb
  Formula/terragrunt.rb
  Formula/unum.rb
  Formula/vamp-plugin-sdk.rb
  Formula/when.rb
Labels: merge

#20455 Merge 2020-05-30 1935bc45ce
  Aliases/subversion@1.14
  Formula/console_bridge.rb
  Formula/contentful-cli.rb
  Formula/create-dmg.rb
  Formula/dartsim.rb
  Formula/docker-completion.rb
  Formula/docker.rb
  Formula/glib-networking.rb
  Formula/ice.rb
  Formula/immudb.rb
  Formula/python@3.8.rb
  Formula/ripgrep.rb
  Formula/scrcpy.rb
  Formula/subversion.rb
  Formula/urdfdom.rb
  Formula/youtube-dl.rb
  Formula/zenith.rb
Labels: merge

#20456 Merge 2020-05-30 d7a0bc6615
  Formula/annie.rb
  Formula/borgmatic.rb
  Formula/bup.rb
  Formula/debianutils.rb
  Formula/fonttools.rb
  Formula/libopenmpt.rb
  Formula/liquigraph.rb
  Formula/ocrmypdf.rb
  Formula/ospray.rb
  Formula/puzzles.rb
  Formula/twarc.rb
Labels: merge

#20457 Merge 2020-05-30 d41d921e31
  Formula/diff-pdf.rb
  Formula/dromeaudio.rb
  Formula/gdal.rb
  Formula/jenkins-lts.rb
  Formula/passenger.rb
  Formula/pdfpc.rb
  Formula/pdftoipe.rb
  Formula/poppler.rb
  Formula/vips.rb
Labels: merge

#20458 Merge 2020-05-30 04c1a6d73e
  Formula/boost.rb
  Formula/chakra.rb
  Formula/couchdb.rb
  Formula/dwdiff.rb
  Formula/freeling.rb
  Formula/gjs.rb
  Formula/harfbuzz.rb
  Formula/hfstospell.rb
  Formula/icu4c.rb
  Formula/libcdr.rb
  Formula/libfreehand.rb
  Formula/libical.rb
  Formula/liblcf.rb
  Formula/libmspub.rb
  Formula/libphonenumber.rb
  Formula/libvisio.rb
  Formula/mapnik.rb
  Formula/monero.rb
  Formula/mpd.rb
  Formula/ncmpcpp.rb
  Formula/node.rb
  Formula/node@10.rb
  Formula/node@12.rb
  Formula/openrct2.rb
  Formula/pazpar2.rb
  Formula/php.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
  Formula/planck.rb
  Formula/postgresql.rb
  Formula/postgresql@10.rb
  Formula/postgresql@11.rb
  Formula/sile.rb
  Formula/tarantool.rb
  Formula/tectonic.rb
  Formula/urweb.rb
  Formula/vte3.rb
  Formula/widelands.rb
  Formula/yaz.rb
  Formula/zebra.rb
  Formula/znc.rb
  Formula/zorba.rb
Labels: merge
