Repository Homebrew/linuxbrew-core, pull requests merged in 2020-04, with the labels that each got.

#19976 Merge 2020-04-01 89d93309ba2
  Formula/citus.rb
  Formula/convox.rb
  Formula/exploitdb.rb
  Formula/gnome-latex.rb
  Formula/helmsman.rb
  Formula/janet.rb
  Formula/notmuch.rb
Labels: merge

#19977 Merge 2020-04-01 9e63a3ff81
  Formula/bitrise.rb
  Formula/dvc.rb
  Formula/gh.rb
  Formula/git-annex.rb
  Formula/glooctl.rb
  Formula/libpq.rb
  Formula/lxc.rb
  Formula/nats-server.rb
  Formula/neon.rb
  Formula/nodenv.rb
  Formula/openssl@1.1.rb
  Formula/prestosql.rb
  Formula/ruby-build.rb
  Formula/terraform-docs.rb
Labels: merge

#19981 Merge 2020-04-02 c6d29e75512
  Formula/ansible@2.8.rb
  Formula/armadillo.rb
  Formula/azure-cli.rb
  Formula/confd.rb
  Formula/contentful-cli.rb
  Formula/crc.rb
  Formula/duplicity.rb
  Formula/gh.rb
  Formula/innoextract.rb
  Formula/katago.rb
  Formula/kepubify.rb
  Formula/kubeseal.rb
  Formula/mitmproxy.rb
  Formula/monit.rb
  Formula/nushell.rb
  Formula/pulumi.rb
  Formula/ruby.rb
  Formula/ruby@2.4.rb
  Formula/ruby@2.5.rb
  Formula/ruby@2.6.rb
  Formula/sd.rb
Labels: merge

#19984 Merge 2020-04-02 1fb53e11ebf
  Formula/ansible.rb
  Formula/ansible@2.8.rb
  Formula/aom.rb
  Formula/azure-cli.rb
  Formula/bat.rb
  Formula/erlang.rb
  Formula/erlang@20.rb
  Formula/erlang@21.rb
  Formula/ffmpeg.rb
  Formula/ffmpeg@2.8.rb
  Formula/ghc.rb
  Formula/git-delta.rb
  Formula/gmp.rb
  Formula/guile.rb
  Formula/libbluray.rb
  Formula/libtommath.rb
  Formula/luajit.rb
  Formula/mpfr.rb
  Formula/mpg123.rb
  Formula/mupdf-tools.rb
  Formula/mupdf.rb
  Formula/pachi.rb
  Formula/ufraw.rb
  Formula/x264.rb
  Formula/x265.rb
Labels: merge

#19985 Merge 2020-04-02 ba2548dbc79
  Formula/apollo-cli.rb
  Formula/boost-build.rb
  Formula/diff-pdf.rb
  Formula/django-completion.rb
  Formula/dvc.rb
  Formula/exploitdb.rb
  Formula/firebase-cli.rb
  Formula/futhark.rb
  Formula/glooctl.rb
  Formula/juju.rb
  Formula/kepubify.rb
  Formula/libomp.rb
  Formula/libzt.rb
  Formula/netpbm.rb
  Formula/openttd.rb
  Formula/pachi.rb
  Formula/pdfpc.rb
  Formula/pdftoipe.rb
  Formula/poppler.rb
  Formula/semtag.rb
  Formula/suite-sparse.rb
  Formula/sysdig.rb
  Formula/ufraw.rb
Labels: merge

#19987 Merge 2020-04-02 e0eeb2af5b7
  Formula/batik.rb
  Formula/bee.rb
  Formula/contentful-cli.rb
  Formula/gatsby-cli.rb
  Formula/minipro.rb
  Formula/re2.rb
  Formula/telegraf.rb
  Formula/teleport.rb
Labels: merge

#19989 Merge 2020-04-03 c974d3d6af4
  .github/workflows/tests.yml
Labels: merge

#19990 Merge 2020-04-03 e7f9346064d
  Formula/atk.rb
  Formula/bmake.rb
  Formula/ccache.rb
  Formula/cfn-lint.rb
  Formula/conan.rb
  Formula/contentful-cli.rb
  Formula/detekt.rb
  Formula/devspace.rb
  Formula/diffoscope.rb
  Formula/etcd.rb
  Formula/ffsend.rb
  Formula/flow.rb
  Formula/fluent-bit.rb
  Formula/folly.rb
  Formula/gobo.rb
  Formula/grpc.rb
  Formula/inxi.rb
  Formula/sbt.rb
  Formula/sk.rb
  Formula/sonobuoy.rb
Labels: merge

#19992 Merge 2020-04-03 b43be46d46c
  Formula/llvm.rb
Labels: merge

#19997 Merge 2020-04-04 bd40745ecb
  Formula/abcmidi.rb
  Formula/boost-mpi.rb
  Formula/boost-python.rb
  Formula/boost-python3.rb
  Formula/boost.rb
  Formula/boost@1.55.rb
  Formula/boost@1.57.rb
  Formula/boost@1.59.rb
  Formula/boost@1.60.rb
  Formula/cataclysm.rb
  Formula/contentful-cli.rb
  Formula/iftop.rb
  Formula/logtalk.rb
  Formula/mingw-w64.rb
  Formula/ntfs-3g.rb
  Formula/numpy.rb
  Formula/pyenv.rb
  Formula/terraform-docs.rb
  Formula/you-get.rb
Labels: merge

#19998 Merge 2020-04-04 26f20caec7
  .github/workflows/tests.yml
Labels: merge

#19999 Merge 2020-04-04 4775ccbf5d
  Formula/acpica.rb
  Formula/contentful-cli.rb
  Formula/fzf.rb
  Formula/hledger.rb
  Formula/httpd.rb
  Formula/le.rb
  Formula/minikube.rb
  Formula/phpunit.rb
  Formula/rdiff-backup.rb
  Formula/skaffold.rb
  Formula/whistle.rb
Labels: merge

#20000 Merge 2020-04-04 8c671866ff
  Formula/bmake.rb
  Formula/cimg.rb
  Formula/exploitdb.rb
  Formula/gmsh.rb
  Formula/haproxy.rb
  Formula/hsd.rb
  Formula/hwloc.rb
  Formula/imagemagick.rb
  Formula/libvirt.rb
  Formula/libzdb.rb
  Formula/memcached.rb
  Formula/mercurial.rb
  Formula/mpd.rb
  Formula/nethogs.rb
  Formula/nfdump.rb
  Formula/nim.rb
  Formula/nomad.rb
  Formula/okteto.rb
  Formula/onscripter.rb
  Formula/openimageio.rb
  Formula/pagmo.rb
  Formula/phpmd.rb
  Formula/pspg.rb
  Formula/shunit2.rb
  Formula/sqlmap.rb
  Formula/ucg.rb
Labels: merge

#20003 Merge 2020-04-05 63da548ca3
  Formula/aws-sdk-cpp.rb
  Formula/cfn-lint.rb
  Formula/cjson.rb
  Formula/deno.rb
  Formula/elm-format.rb
  Formula/exploitdb.rb
  Formula/fonttools.rb
  Formula/goreleaser.rb
  Formula/grpc.rb
  Formula/hpack.rb
  Formula/komposition.rb
  Formula/mdbook.rb
  Formula/media-info.rb
  Formula/mesa.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/monolith.rb
  Formula/openrct2.rb
  Formula/pueue.rb
  Formula/purescript.rb
  Formula/quantlib.rb
  Formula/shellcheck.rb
  Formula/spim.rb
  Formula/strongswan.rb
  Formula/swiftlint.rb
  Formula/tbb.rb
  Formula/terragrunt.rb
  Formula/tflint.rb
  Formula/urweb.rb
  Formula/vim.rb
  Formula/vulkan-headers.rb
  Formula/wxmaxima.rb
  Formula/xcodegen.rb
  Formula/xmrig.rb
  Formula/yaz.rb
Labels: merge

#20017 Merge 2020-04-05 87bb8e888c
  Formula/astrometry-net.rb
  Formula/dyld-headers.rb
  Formula/freetds.rb
  Formula/idnits.rb
  Formula/inadyn.rb
  Formula/libwps.rb
  Formula/lsyncd.rb
  Formula/minikube.rb
  Formula/mkvtoolnix.rb
  Formula/ndpi.rb
  Formula/pass-git-helper.rb
  Formula/pkg-config.rb
  Formula/shellcheck.rb
  Formula/singular.rb
  Formula/swiftformat.rb
Labels: merge

#20021 Merge 2020-04-06 558a44898c
  Formula/beancount.rb
  Formula/bison.rb
  Formula/c-blosc.rb
  Formula/cabal-install.rb
  Formula/coq.rb
  Formula/fastlane.rb
  Formula/flake8.rb
  Formula/gobject-introspection.rb
  Formula/graphite2.rb
  Formula/istioctl.rb
  Formula/libgsm.rb
  Formula/logstash.rb
  Formula/math-comp.rb
  Formula/nano.rb
  Formula/nift.rb
  Formula/openssh.rb
  Formula/qjackctl.rb
Labels: merge

#20009 cassandra: fix dependencies
  Formula/cassandra.rb
Labels: test failure

#20023 Merge 2020-04-06 985bced3fd
  Formula/bandwhich.rb
  Formula/csound.rb
  Formula/gtk+3.rb
  Formula/librsvg.rb
  Formula/libsignal-protocol-c.rb
  Formula/mk-configure.rb
  Formula/netdata.rb
  Formula/openfortivpn.rb
  Formula/pegtl.rb
  Formula/utf8proc.rb
Labels: merge

#20027 Merge 2020-04-07 aee220a935
  Formula/mpv.rb
  Formula/pkg-config.rb
Labels: merge

#20029 Merge 2020-04-07 af5847075a
  Formula/eccodes.rb
  Formula/gdal.rb
  Formula/gdcm.rb
  Formula/gmt.rb
  Formula/gmt@5.rb
  Formula/nco.rb
  Formula/ncview.rb
  Formula/netcdf.rb
  Formula/pcl.rb
  Formula/visp.rb
  Formula/vtk.rb
Labels: merge

#20030 Merge 2020-04-07 b05f17c674
  Formula/baidupcs-go.rb
  Formula/bazel.rb
  Formula/contentful-cli.rb
  Formula/crystal.rb
  Formula/dvc.rb
  Formula/ejabberd.rb
  Formula/libaacs.rb
  Formula/libbdplus.rb
  Formula/libdvdcss.rb
  Formula/libdvdnav.rb
  Formula/mapnik.rb
  Formula/monolith.rb
  Formula/newman.rb
  Formula/oauth2_proxy.rb
  Formula/prettier.rb
  Formula/starship.rb
  Formula/terragrunt.rb
Labels: merge

#20031 Merge 2020-04-08 634d117b28
  Formula/apr-util.rb
  Formula/apr.rb
  Formula/binutils.rb
  Formula/bison.rb
  Formula/flex.rb
  Formula/gettext.rb
  Formula/heimdal.rb
  Formula/lapack.rb
  Formula/libffi.rb
  Formula/libressl.rb
  Formula/libunwind-headers.rb
  Formula/openal-soft.rb
  Formula/openblas.rb
  Formula/openssl@1.1.rb
  Formula/pcsc-lite.rb
  Formula/readline.rb
  Formula/sqlite.rb
  Formula/swift.rb
  Formula/tcl-tk.rb
  Formula/texinfo.rb
  Formula/unifdef.rb
Labels: merge

#20032 Merge 2020-04-08 9907874017
  Formula/aamath.rb
  Formula/appscale-tools.rb
  Formula/audacious.rb
  Formula/auditbeat.rb
  Formula/autojump.rb
  Formula/awscli.rb
  Formula/bazaar.rb
  Formula/bic.rb
  Formula/blastem.rb
  Formula/blockhash.rb
  Formula/bnfc.rb
  Formula/boost-python.rb
Labels: merge

#20033 Merge 2020-04-08 7bd76f6581
  Formula/botan.rb
  Formula/bup.rb
  Formula/cassandra@2.1.rb
  Formula/cassandra@2.2.rb
  Formula/check.rb
  Formula/csound.rb
  Formula/deno.rb
  Formula/expat.rb
  Formula/freeradius-server.rb
  Formula/freetds.rb
  Formula/git-remote-hg.rb
  Formula/glib.rb
  Formula/gnuradio.rb
  Formula/hg-fast-export.rb
  Formula/infer.rb
  Formula/jack.rb
  Formula/libming.rb
Labels: merge

#20034 Merge 2020-04-08 155f05ed72
  Formula/appscale-tools.rb
  Formula/groonga.rb
  Formula/mesos.rb
  Formula/metricbeat.rb
  Formula/mmseqs2.rb
  Formula/node@10.rb
  Formula/numpy@1.16.rb
  Formula/offlineimap.rb
  Formula/ooniprobe.rb
  Formula/opencv@2.rb
  Formula/pdf-redact-tools.rb
  Formula/py2cairo.rb
  Formula/quex.rb
  Formula/rethinkdb.rb
  Formula/rust.rb
  Formula/shadowsocks-libev.rb
  Formula/spades.rb
  Formula/ssh-copy-id.rb
  Formula/subliminal.rb
  Formula/subversion.rb
  Formula/unicorn.rb
  Formula/viewvc.rb
  Formula/volatility.rb
  Formula/zeek.rb
Labels: merge

#20035 Merge 2020-04-08 f995e9f52d
  Formula/autopep8.rb
  Formula/aws-cdk.rb
  Formula/awscli.rb
  Formula/botan.rb
  Formula/exploitdb.rb
  Formula/frugal.rb
  Formula/minetest.rb
  Formula/nano.rb
  Formula/omniorb.rb
  Formula/openimageio.rb
  Formula/par.rb
  Formula/vala.rb
Labels: merge

#20037 Merge 2020-04-08 8b2ff39f04
  Aliases/v8@8.1
  Formula/contentful-cli.rb
  Formula/dhall.rb
  Formula/doctl.rb
  Formula/emacs-dracula.rb
  Formula/erlang.rb
  Formula/fetchmail.rb
  Formula/fluid-synth.rb
  Formula/fluxctl.rb
  Formula/fwup.rb
  Formula/gitleaks.rb
  Formula/imgproxy.rb
  Formula/libbluray.rb
  Formula/libpst.rb
  Formula/librdkafka.rb
  Formula/mat2.rb
  Formula/micronaut.rb
  Formula/mksh.rb
  Formula/newrelic-cli.rb
  Formula/plantuml.rb
  Formula/qcli.rb
  Formula/scummvm.rb
  Formula/serverless.rb
  Formula/v8.rb
  Formula/verilator.rb
  Formula/xonsh.rb
Labels: merge

#20042 Merge 2020-04-09 456ff1e849
  Formula/bcoin.rb
  Formula/calceph.rb
  Formula/cheat.rb
  Formula/contentful-cli.rb
  Formula/detekt.rb
  Formula/devspace.rb
  Formula/exploitdb.rb
  Formula/fastmod.rb
  Formula/firebase-cli.rb
  Formula/fn.rb
  Formula/frugal.rb
  Formula/gatsby-cli.rb
  Formula/helmfile.rb
  Formula/jenkins.rb
  Formula/netlify-cli.rb
  Formula/serverless.rb
  Formula/shfmt.rb
  Formula/terragrunt.rb
  Formula/toast.rb
  Formula/travis.rb
Labels: merge

#20045 Merge 2020-04-09 f9927e568d
  Formula/broot.rb
  Formula/grails.rb
  Formula/healpix.rb
  Formula/newman.rb
  Formula/opencv@3.rb
  Formula/serverless.rb
  Formula/syncthing.rb
Labels: merge

#20048 Merge 2020-04-09 f34ce2de48
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20049 Merge 2020-04-09 47de1bc37d
  Formula/afflib.rb
  Formula/b2-tools.rb
  Formula/bettercap.rb
  Formula/dvdauthor.rb
  Formula/dvdbackup.rb
  Formula/git-remote-codecommit.rb
  Formula/libdvdnav.rb
  Formula/libdvdread.rb
  Formula/libfreenect.rb
  Formula/librsync.rb
  Formula/lsdvd.rb
  Formula/mpv.rb
  Formula/ortp.rb
  Formula/pianobar.rb
Labels: merge

#20051 Merge 2020-04-10 bbd457a944
  .github/workflows/tests.yml
Labels: merge

#20052 Merge 2020-04-10 10bac8ea98
  Formula/bear.rb
  Formula/caffe.rb
  Formula/contentful-cli.rb
  Formula/credstash.rb
  Formula/ddgr.rb
  Formula/deno.rb
  Formula/diffoscope.rb
  Formula/gearboy.rb
  Formula/go@1.13.rb
  Formula/killswitch.rb
  Formula/libdca.rb
  Formula/mame.rb
  Formula/newrelic-cli.rb
  Formula/opencv.rb
  Formula/prometheus.rb
  Formula/ripgrep-all.rb
  Formula/siril.rb
  Formula/velero.rb
  Formula/visp.rb
  Formula/xonsh.rb
  tap_migrations.json
Labels: merge

#20039 libbluray: try to rebuild for Linuxbrew
  Formula/libbluray.rb
Labels: build failure

#20053 mpd: Fix bottling for Linuxbrew
  Formula/mpd.rb
Labels: cellar failure

#20054 pianobar: Fix test for Linuxbrew
  Formula/pianobar.rb
Labels: test failure

#20055 Merge 2020-04-10 2ec04388fe
  Formula/bat.rb
  Formula/bumpversion.rb
  Formula/lsd.rb
  Formula/mockolo.rb
  Formula/ocrmypdf.rb
Labels: merge

#20056 Merge 2020-04-10 bd746975e4
  Formula/borgmatic.rb
  Formula/cryptominisat.rb
  Formula/cxxtest.rb
  Formula/dnstwist.rb
  Formula/dnsviz.rb
  Formula/doitlive.rb
  Formula/eralchemy.rb
  Formula/fabric.rb
  Formula/gprof2dot.rb
Labels: merge

#20059 Merge 2020-04-10 5997349381
  Formula/eye-d3.rb
  Formula/fbi-servefiles.rb
  Formula/fobis.rb
  Formula/ford.rb
  Formula/gitfs.rb
  Formula/gitless.rb
  Formula/googler.rb
  Formula/goolabs.rb
  Formula/grip.rb
Labels: merge

#20058 gprof2dot: fix build for Linuxbrew
  Formula/gprof2dot.rb
Labels: dependency/x11

#20060 Merge 2020-04-10 72ece2f1ab
  Formula/aws-es-proxy.rb
  Formula/faas-cli.rb
  Formula/perl.rb
  Formula/subversion.rb
  Formula/vim.rb
  Formula/weechat.rb
Labels: merge

#20061 Merge 2020-04-10 2a7103f512
  Formula/appscale-tools.rb
  Formula/asciidoc.rb
  Formula/audacious.rb
  Formula/blastem.rb
  Formula/blockhash.rb
  Formula/boost-python.rb
  Formula/botan.rb
  Formula/bup.rb
  Formula/cassandra@2.2.rb
  Formula/csound.rb
  Formula/czmq.rb
  Formula/deno.rb
  Formula/git-remote-hg.rb
Labels: merge

#20062 Merge 2020-04-10 ca9b2fae2d
  Formula/gnuradio.rb
  Formula/hg-fast-export.rb
  Formula/ibex.rb
  Formula/infer.rb
  Formula/kcov.rb
  Formula/kibana.rb
  Formula/libgraphqlparser.rb
  Formula/libming.rb
  Formula/libsoup.rb
  Formula/libtcod.rb
  Formula/lv2.rb
  Formula/mesos.rb
  Formula/metricbeat.rb
  Formula/mono.rb
  Formula/nanomsgxx.rb
  Formula/node@10.rb
  Formula/numpy@1.16.rb
  Formula/offlineimap.rb
  Formula/ooniprobe.rb
  Formula/opencv@2.rb
  Formula/pdf-redact-tools.rb
  Formula/py2cairo.rb
  Formula/quex.rb
  Formula/rethinkdb.rb
  Formula/shadowsocks-libev.rb
  Formula/subliminal.rb
  Formula/sync_gateway.rb
  Formula/unicorn.rb
  Formula/viewvc.rb
  Formula/volatility.rb
  Formula/zeek.rb
Labels: merge

#20063 Merge 2020-04-10 84f5670ad9
  Formula/angular-cli.rb
  Formula/antibody.rb
  Formula/balena-cli.rb
  Formula/cassandra@2.2.rb
  Formula/composer.rb
  Formula/contentful-cli.rb
  Formula/deno.rb
  Formula/doctl.rb
  Formula/erlang.rb
  Formula/exploitdb.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/helmfile.rb
  Formula/homebank.rb
  Formula/liquibase.rb
  Formula/moco.rb
  Formula/monolith.rb
  Formula/netlify-cli.rb
  Formula/node@10.rb
  Formula/node@12.rb
  Formula/puzzles.rb
  Formula/pybind11.rb
  Formula/terragrunt.rb
  Formula/tig.rb
  Formula/tomcat.rb
  Formula/viewvc.rb
Labels: merge

#20065 Merge 2020-04-11 d4eb6e646c
  Formula/binwalk.rb
  Formula/compcert.rb
  Formula/docker-compose-completion.rb
  Formula/docker-compose.rb
  Formula/hugo.rb
  Formula/librsvg.rb
  Formula/simh.rb
Labels: merge

#20066 Merge 2020-04-11 e8a66a6659
  Formula/pkg-config.rb
Labels: merge

#20067 Merge 2020-04-11 8780491594
  .github/workflows/tests.yml
  Formula/aws-cdk.rb
  Formula/cartridge-cli.rb
  Formula/go.rb
  Formula/go@1.13.rb
  Formula/kubernetes-cli.rb
  Formula/pushpin.rb
  Formula/spiped.rb
  Formula/step.rb
Labels: merge

#20068 Merge 2020-04-11 16ef381731
  Formula/apollo-cli.rb
  Formula/awsume.rb
  Formula/bartycrouch.rb
  Formula/buku.rb
  Formula/cfn-lint.rb
  Formula/csvq.rb
  Formula/ddgr.rb
  Formula/fdroidserver.rb
  Formula/jetty.rb
  Formula/meilisearch.rb
  Formula/micro.rb
  Formula/minio.rb
  Formula/n.rb
  Formula/ocrmypdf.rb
  Formula/pgcli.rb
  Formula/php-cs-fixer.rb
  Formula/pueue.rb
  Formula/rex.rb
  Formula/s3cmd.rb
  Formula/stella.rb
  Formula/stress-ng.rb
  Formula/weboob.rb
  Formula/wolfmqtt.rb
Labels: merge

#20070 Merge 2020-04-11 e1bf3b3a5a
  Formula/highlight.rb
  Formula/kubebuilder.rb
  Formula/libssh.rb
  Formula/libupnp.rb
  Formula/magic-wormhole.rb
  Formula/mpd.rb
  Formula/nomad.rb
  Formula/remind.rb
  Formula/skopeo.rb
  Formula/sslyze.rb
  Formula/tomcat@8.rb
  Formula/uni.rb
  Formula/wireshark.rb
Labels: merge

#20069 fdroidserver: fix condition
  Formula/fdroidserver.rb
Labels: build failure

#20074 Merge 2020-04-11 8eddec63cc
  Formula/bedops.rb
  Formula/blis.rb
  Formula/cdk8s.rb
  Formula/convox.rb
  Formula/devspace.rb
  Formula/docfx.rb
  Formula/doctl.rb
  Formula/exploitdb.rb
  Formula/findomain.rb
  Formula/glib.rb
  Formula/linkerd.rb
  Formula/n.rb
  Formula/nss.rb
  Formula/pympress.rb
  Formula/root.rb
  Formula/starship.rb
Labels: merge

#20011 ocrmypdf: remove dependency, use depends_on
  Formula/ocrmypdf.rb
Labels: build failure

#20075 Merge 2020-04-12 8ee7b8e5cc
  Formula/awsume.rb
  Formula/faudio.rb
  Formula/flyway.rb
  Formula/fmt.rb
  Formula/folly.rb
  Formula/frpc.rb
  Formula/frps.rb
  Formula/fruit.rb
  Formula/gatsby-cli.rb
  Formula/git-plus.rb
  Formula/glooctl.rb
  Formula/goofys.rb
  Formula/mdcat.rb
  Formula/starship.rb
  Formula/tunnel.rb
Labels: merge

#20076 Merge 2020-04-12 38795af117
  Formula/compcert.rb
  Formula/composer.rb
  Formula/dxpy.rb
  Formula/ensmallen.rb
  Formula/grafana.rb
  Formula/grin.rb
  Formula/groovy.rb
  Formula/groovysdk.rb
  Formula/joplin.rb
  Formula/jp2a.rb
  Formula/jsdoc3.rb
  Formula/json-fortran.rb
  Formula/kcptun.rb
  Formula/kitchen-sync.rb
  Formula/krakend.rb
  Formula/libcbor.rb
  Formula/libfido2.rb
  Formula/mkdocs.rb
  Formula/mkl-dnn.rb
  Formula/mockolo.rb
  Formula/modules.rb
  Formula/mysql-search-replace.rb
  Formula/root.rb
  Formula/sd.rb
Labels: merge

#20081 Merge 2020-04-12 b3572a65aa
  Formula/molecule.rb
  Formula/multimarkdown.rb
  Formula/nebula.rb
  Formula/nifi-registry.rb
  Formula/node-sass.rb
  Formula/now-cli.rb
  Formula/octomap.rb
  Formula/offlineimap.rb
  Formula/okteto.rb
  Formula/opensubdiv.rb
  Formula/pachi.rb
  Formula/pc6001vx.rb
  Formula/pdns.rb
  Formula/phplint.rb
  Formula/picard-tools.rb
  Formula/pnpm.rb
  Formula/pulp.rb
  Formula/raylib.rb
  Formula/re-flex.rb
  Formula/regina-rexx.rb
  Formula/schema-evolution-manager.rb
  Formula/signal-cli.rb
  Formula/spirv-cross.rb
  Formula/sundials.rb
  Formula/swagger-codegen.rb
  Formula/swift-sh.rb
Labels: merge

#20082 Merge 2020-04-12 4da51bd904
  Formula/bzt.rb
  Formula/credstash.rb
  Formula/diffoscope.rb
  Formula/dnsmasq.rb
  Formula/gsoap.rb
  Formula/i2pd.rb
  Formula/internetarchive.rb
  Formula/khard.rb
  Formula/mongo-cxx-driver.rb
  Formula/pdal.rb
  Formula/q.rb
  Formula/rgbds.rb
  Formula/rom-tools.rb
  Formula/sip.rb
  Formula/ttygif.rb
  Formula/twarc.rb
  Formula/txr.rb
  Formula/uftp.rb
  Formula/whistle.rb
  Formula/xpa.rb
  Formula/xsimd.rb
  Formula/zero-install.rb
  Formula/zint.rb
Labels: merge

#20084 Merge 2020-04-12 ed33a189e1
  Formula/ask-cli.rb
  Formula/cdk8s.rb
  Formula/cmake.rb
  Formula/gl2ps.rb
  Formula/octave.rb
  Formula/remarshal.rb
  Formula/root.rb
Labels: merge

#20085 Merge 2020-04-12 c1c9fe85bc
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20087 Merge 2020-04-13 e9b0faf510
  Formula/asdf.rb
  Formula/asio.rb
  Formula/atlassian-cli.rb
  Formula/axel.rb
  Formula/azcopy.rb
  Formula/b3sum.rb
  Formula/byacc.rb
  Formula/codequery.rb
  Formula/dcm2niix.rb
  Formula/dict.rb
  Formula/embree.rb
  Formula/faiss.rb
  Formula/feh.rb
  Formula/freetds.rb
  Formula/fs-uae.rb
  Formula/gd.rb
  Formula/git-subrepo.rb
  Formula/libjson-rpc-cpp.rb
  Formula/libmaa.rb
  Formula/link-grammar.rb
  Formula/maxwell.rb
  Formula/metabase.rb
  Formula/node-build.rb
  Formula/node@10.rb
  Formula/softhsm.rb
  Formula/spirv-tools.rb
Labels: merge

#20090 Merge 2020-04-13 8cdee7e758
  Aliases/freetype2
  Formula/chafa.rb
  Formula/epstool.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jupyterlab.rb
  Formula/libflowmanager.rb
  Formula/libprotoident.rb
  Formula/libtrace.rb
  Formula/macvim.rb
  Formula/manticoresearch.rb
  Formula/nave.rb
  Formula/navi.rb
  Formula/nbdime.rb
  Formula/olsrd.rb
  Formula/opencc.rb
  Formula/ospray.rb
  Formula/parallelstl.rb
  Formula/pypy.rb
  Formula/pypy3.rb
  Formula/pyqt.rb
  Formula/pyvim.rb
  Formula/rgxg.rb
  Formula/vulkan-headers.rb
  Formula/wpscan.rb
Labels: merge

#20086 lv: Fix build for Linuxbrew
  Formula/lv.rb
Labels: dependency

#20092 Merge 2020-04-13 118c223c1b
  Formula/hcloud.rb
  Formula/jflex.rb
  Formula/librealsense.rb
  Formula/luvit.rb
  Formula/mariadb-connector-odbc.rb
  Formula/netlify-cli.rb
  Formula/pspg.rb
  Formula/twarc.rb
  Formula/txr.rb
  Formula/userspace-rcu.rb
  Formula/whistle.rb
Labels: merge

#20093 userspace-rcu: fix test for Linuxbrew
  Formula/userspace-rcu.rb
Labels: test failure

#20097 Merge 2020-04-13 84ceeba094
  Formula/biosig.rb
  Formula/ceres-solver.rb
  Formula/ephemeralpg.rb
  Formula/libplctag.rb
  Formula/molten-vk.rb
  Formula/ocrmypdf.rb
  Formula/octave.rb
  Formula/polynote.rb
  Formula/qpdf.rb
  Formula/stellar-core.rb
  Formula/suite-sparse.rb
  Formula/sundials.rb
  Formula/thors-serializer.rb
  Formula/vim.rb
Labels: merge

#20100 Merge 2020-04-13 06a8b116f1
  .github/workflows/tests.yml
Labels: merge

#20101 Merge 2020-04-13 ae3bda39b9
  Formula/bash-preexec.rb
  Formula/bluepill.rb
  Formula/chapel.rb
  Formula/crc32c.rb
  Formula/flint-checker.rb
  Formula/geant4.rb
  Formula/git-octopus.rb
  Formula/gollum.rb
  Formula/gpsd.rb
  Formula/jemalloc.rb
  Formula/liboauth.rb
  Formula/libopennet.rb
  Formula/memcached.rb
  Formula/mint.rb
  Formula/msmtp.rb
  Formula/neatvi.rb
  Formula/nnn.rb
  Formula/platformio.rb
  Formula/proctools.rb
  Formula/qemu.rb
  Formula/readline.rb
  Formula/shunit2.rb
  Formula/swfmill.rb
  Formula/texinfo.rb
  Formula/tinyxml.rb
  Formula/unar.rb
  Formula/xerces-c.rb
Labels: merge

#20102 Merge 2020-04-14 f356449256a
  .github/workflows/publish-commit-bottles.yml
  Formula/boringtun.rb
  Formula/carla.rb
  Formula/castxml.rb
  Formula/chamber.rb
  Formula/ddclient.rb
  Formula/emscripten.rb
  Formula/firebase-cli.rb
  Formula/gifski.rb
  Formula/ginac.rb
  Formula/gtk+3.rb
  Formula/homeassistant-cli.rb
  Formula/lf.rb
  Formula/lft.rb
  Formula/libqalculate.rb
  Formula/mitmproxy.rb
  Formula/navi.rb
  Formula/netlify-cli.rb
  Formula/now-cli.rb
  Formula/ntopng.rb
  Formula/opa.rb
  Formula/openttd.rb
  Formula/osmosis.rb
  Formula/otf2.rb
  Formula/percona-server.rb
  Formula/pulumi.rb
  Formula/qalculate-gtk.rb
  Formula/terraform-provider-libvirt.rb
  Formula/tintin.rb
  Formula/yamllint.rb
Labels: merge

#20104 Merge 2020-04-14 7c0e823b76
  Formula/armadillo.rb
  Formula/artifactory.rb
  Formula/b3sum.rb
  Formula/bento4.rb
  Formula/bettercap.rb
  Formula/bib-tool.rb
  Formula/dolt.rb
  Formula/exploitdb.rb
  Formula/gitversion.rb
  Formula/glib-networking.rb
  Formula/grpcurl.rb
  Formula/k3d.rb
  Formula/lf.rb
  Formula/miniserve.rb
  Formula/netdata.rb
  Formula/tokei.rb
  Formula/xmrig.rb
Labels: merge

#20105 Merge 2020-04-15 0a493a96f7
  Formula/bibclean.rb
  Formula/cjdns.rb
  Formula/git-gui.rb
  Formula/git.rb
  Formula/go-jsonnet.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/libsecret.rb
  Formula/zig.rb
Labels: merge

#20106 bibclean: fix bottling for Linuxbrew
  Formula/bibclean.rb
Labels: cellar failure

#20110 Merge 2020-04-15 cd73c30a26
  Formula/ballerina.rb
  Formula/cacli.rb
  Formula/gawk.rb
  Formula/geph2.rb
  Formula/gnustep-make.rb
  Formula/helm@2.rb
  Formula/igv.rb
  Formula/irrtoolset.rb
  Formula/krb5.rb
  Formula/libopenmpt.rb
  Formula/memcached.rb
  Formula/mpop.rb
  Formula/nginx.rb
  Formula/passenger.rb
  Formula/radare2.rb
  Formula/sbt.rb
  Formula/yamllint.rb
  Formula/zsh-completions.rb
Labels: merge

#20115 Merge 2020-04-16 3a6cd5e6e9
  Formula/bartycrouch.rb
  Formula/chronograf.rb
  Formula/dolt.rb
  Formula/flash.rb
  Formula/gettext.rb
  Formula/gnutls.rb
  Formula/node.rb
  Formula/profanity.rb
  Formula/tengo.rb
Labels: merge

#20116 Merge 2020-04-16 abc627c9df
  Formula/armor.rb
  Formula/bind.rb
  Formula/codequery.rb
  Formula/contentful-cli.rb
  Formula/dvc.rb
  Formula/php-cs-fixer.rb
  Formula/php.rb
  Formula/php@7.3.rb
Labels: merge

#20117 Merge 2020-04-16 d874b06712
  Formula/fd.rb
Labels: merge

#20118 Merge 2020-04-16 c87055190a
  Formula/binaryen.rb
  Formula/emscripten.rb
  Formula/futhark.rb
  Formula/ipython.rb
  Formula/jupyterlab.rb
  Formula/kotlin.rb
  Formula/mksh.rb
  Formula/node.rb
  Formula/snort.rb
  Formula/vault.rb
  Formula/winetricks.rb
Labels: merge

#20120 Merge 2020-04-17 a024db3cba
  Formula/ansible.rb
  Formula/exodriver.rb
  Formula/ilmbase.rb
  Formula/libyaml.rb
Labels: merge

#20121 Merge 2020-04-17 721b39d5ee
  Formula/ruby.rb
  Formula/ruby@2.6.rb
Labels: merge

#20122 Merge 2020-04-17 8ff2935985
  Formula/perl.rb
  Formula/perl@5.18.rb
Labels: merge

#20124 Merge 2020-04-17 9db71ecefad
  Formula/apib.rb
  Formula/arduino-cli.rb
  Formula/awscli.rb
  Formula/bindfs.rb
  Formula/cassandra.rb
  Formula/chamber.rb
  Formula/chapel.rb
  Formula/contentful-cli.rb
  Formula/deno.rb
  Formula/dune.rb
  Formula/efl.rb
  Formula/flow.rb
  Formula/gcc.rb
  Formula/gcc@4.9.rb
  Formula/gcc@5.rb
  Formula/gcc@6.rb
  Formula/gcc@7.rb
  Formula/gcc@8.rb
  Formula/gearsystem.rb
  Formula/genders.rb
  Formula/git-revise.rb
  Formula/influxdb.rb
  Formula/ipopt.rb
  Formula/jenkins.rb
  Formula/kafka.rb
  Formula/kubernetes-cli.rb
  Formula/lgogdownloader.rb
  Formula/libuninameslist.rb
  Formula/libusb.rb
  Formula/libuv.rb
  Formula/libzzip.rb
  Formula/mbedtls.rb
  Formula/nsd.rb
  Formula/ocrmypdf.rb
  Formula/okteto.rb
  Formula/openconnect.rb
  Formula/openjdk@11.rb
  Formula/operator-sdk.rb
  Formula/pipenv.rb
  Formula/proteinortho.rb
  Formula/telegraf.rb
  tap_migrations.json
Labels: merge

#20133 Merge 2020-04-17 e10a9492669
  Formula/adwaita-icon-theme.rb
  Formula/ballerina.rb
  Formula/bitrise.rb
  Formula/boot-clj.rb
  Formula/calceph.rb
  Formula/contentful-cli.rb
  Formula/devspace.rb
  Formula/folly.rb
  Formula/geph2.rb
  Formula/git.rb
  Formula/grex.rb
  Formula/libgraphqlparser.rb
  Formula/neomutt.rb
  Formula/nift.rb
  Formula/openvpn.rb
  Formula/osmfilter.rb
  Formula/redis.rb
  Formula/rpm.rb
  Formula/wavpack.rb
  Formula/yamllint.rb
Labels: merge

#20135 Merge 2020-04-17 0c3d786402
  Formula/closure-compiler.rb
  Formula/subversion.rb
Labels: merge

#20136 Merge 2020-04-18 8b156ecc734
  Formula/asciidoctor.rb
  Formula/devspace.rb
  Formula/eigen.rb
  Formula/freeciv.rb
  Formula/git-annex.rb
  Formula/hsd.rb
  Formula/kyma-cli.rb
  Formula/neomutt.rb
  Formula/openrct2.rb
  Formula/proj.rb
  Formula/pympress.rb
  Formula/sbcl.rb
  Formula/yq.rb
  Formula/zurl.rb
Labels: merge

#20138 Merge 2020-04-18 57516a41b0
  Formula/conan.rb
  Formula/duplicity.rb
  Formula/ecl.rb
  Formula/freeciv.rb
  Formula/gforth.rb
  Formula/gjs.rb
  Formula/glib.rb
  Formula/gnu-smalltalk.rb
  Formula/gobject-introspection.rb
  Formula/guile.rb
  Formula/libffi.rb
  Formula/llvm.rb
  Formula/llvm@6.rb
  Formula/llvm@7.rb
  Formula/llvm@8.rb
  Formula/llvm@9.rb
  Formula/micropython.rb
  Formula/moarvm.rb
  Formula/oclgrind.rb
  Formula/ocrmypdf.rb
  Formula/p11-kit.rb
  Formula/php.rb
  Formula/pygobject3.rb
  Formula/pypy.rb
  Formula/pypy3.rb
  Formula/rakudo-star.rb
  Formula/rakudo.rb
  Formula/sagittarius-scheme.rb
  Formula/sslyze.rb
  Formula/yosys.rb
Labels: merge

#20142 Merge 2020-04-18 e3f1256d4f
  Formula/ask-cli.rb
  Formula/couchdb-lucene.rb
  Formula/couchdb.rb
  Formula/ethereum.rb
  Formula/feedgnuplot.rb
  Formula/fonttools.rb
  Formula/freetds.rb
  Formula/geoipupdate.rb
  Formula/glooctl.rb
  Formula/guile.rb
  Formula/helmfile.rb
  Formula/helmsman.rb
  Formula/kubecfg.rb
  Formula/mariadb.rb
  Formula/mariadb@10.2.rb
  Formula/pdftk-java.rb
  Formula/php@7.2.rb
  Formula/puzzles.rb
  Formula/repo.rb
  Formula/ruby.rb
  Formula/silk.rb
  Formula/skaffold.rb
  Formula/tass64.rb
  Formula/terragrunt.rb
Labels: merge

#20144 Merge 2020-04-19 87caa9e8f6
  Formula/aws-cdk.rb
  Formula/balena-cli.rb
  Formula/bareos-client.rb
  Formula/bazelisk.rb
  Formula/buildkit.rb
  Formula/cargo-completion.rb
  Formula/chakra.rb
  Formula/chromaprint.rb
  Formula/clojure-lsp.rb
  Formula/davmail.rb
  Formula/dfmt.rb
  Formula/dmd.rb
  Formula/dscanner.rb
  Formula/dub.rb
  Formula/dune.rb
  Formula/exploitdb.rb
  Formula/firebase-cli.rb
  Formula/gatsby-cli.rb
  Formula/git-delta.rb
  Formula/gmailctl.rb
  Formula/grakn.rb
  Formula/httpie.rb
  Formula/kapacitor.rb
  Formula/mariadb@10.3.rb
  Formula/vnu.rb
Labels: merge

#20145 Merge 2020-04-19 3a17fa23ce
  Formula/chuck.rb
  Formula/dafny.rb
  Formula/diffoscope.rb
  Formula/doxygen.rb
  Formula/git-plus.rb
  Formula/harfbuzz.rb
  Formula/mono-libgdiplus.rb
  Formula/mujs.rb
  Formula/mycli.rb
  Formula/mysql-search-replace.rb
  Formula/netlify-cli.rb
  Formula/nickle.rb
  Formula/nlopt.rb
  Formula/php-code-sniffer.rb
  Formula/pnpm.rb
  Formula/solr.rb
  Formula/triangle.rb
  Formula/trimage.rb
  Formula/triton.rb
  Formula/urh.rb
  Formula/vale.rb
  Formula/wartremover.rb
  Formula/z3.rb
  Formula/znc.rb
Labels: merge

#20146 Merge 2020-04-19 fa7cc18398
  Formula/aliyun-cli.rb
  Formula/aws-elasticbeanstalk.rb
  Formula/embulk.rb
  Formula/emscripten.rb
  Formula/libwbxml.rb
  Formula/llvm.rb
  Formula/open-completion.rb
  Formula/trezor-agent.rb
  Formula/txr.rb
  Formula/wxmaxima.rb
  Formula/xclogparser.rb
  Formula/xgboost.rb
  Formula/xtensor.rb
  Formula/yaegi.rb
  Formula/yaz.rb
  Formula/zeek.rb
  Formula/zig.rb
Labels: merge

#20147 Merge 2020-04-19 474c67ebc0
  Formula/iam-policy-json-to-terraform.rb
Labels: merge

#20148 Merge 2020-04-19 5d35fe1f38
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20149 Merge 2020-04-19 9a78c56d5d
  Formula/aws-cdk.rb
  Formula/cypher-shell.rb
  Formula/davmail.rb
  Formula/jetty-runner.rb
  Formula/libvirt.rb
  Formula/mu.rb
  Formula/neon.rb
  Formula/plantuml.rb
  Formula/protoc-gen-go.rb
  Formula/questdb.rb
  Formula/yaws.rb
Labels: merge

#20151 Merge 2020-04-20 0a27529d1d
  Formula/instead.rb
  Formula/jetty-runner.rb
  Formula/opensaml.rb
  Formula/shibboleth-sp.rb
  Formula/singular.rb
  Formula/skopeo.rb
  Formula/snakemake.rb
  Formula/sslyze.rb
  Formula/termrec.rb
  Formula/testssl.rb
  Formula/texmath.rb
  Formula/vim.rb
  Formula/xml-tooling-c.rb
  Formula/yle-dl.rb
Labels: merge

#20173 Merge 2020-04-20 93f6f161455
  Formula/benthos.rb
  Formula/bootloadhid.rb
  Formula/curl-openssl.rb
  Formula/erlang@21.rb
  Formula/file-roller.rb
  Formula/gcore.rb
  Formula/heimdal.rb
  Formula/lazygit.rb
  Formula/libuv.rb
  Formula/libvirt.rb
  Formula/mlpack.rb
  Formula/mu.rb
  Formula/nift.rb
  Formula/phpunit.rb
  Formula/rcm.rb
  Formula/robotfindskitten.rb
  Formula/s-nail.rb
  Formula/sispmctl.rb
  Formula/src.rb
  Formula/sslmate.rb
  Formula/tanka.rb
  Formula/thors-serializer.rb
Labels: merge

#20178 Merge 2020-04-21 edb0831a59
  Formula/folly.rb
  Formula/llvm@9.rb
  Formula/mycli.rb
  Formula/oclgrind.rb
  Formula/oniguruma.rb
Labels: merge

#20179 Merge 2020-04-21 9ca5cfbcd9
  Formula/ansible.rb
  Formula/colordiff.rb
  Formula/freediameter.rb
  Formula/funcoeszz.rb
  Formula/libfido2.rb
  Formula/libntlm.rb
  Formula/libtorrent-rasterbar.rb
  Formula/libyaml.rb
  Formula/lmod.rb
  Formula/megatools.rb
  Formula/neomutt.rb
  Formula/numpy.rb
  Formula/open-zwave.rb
  Formula/postgrest.rb
  Formula/procs.rb
  Formula/pulumi.rb
  Formula/qcachegrind.rb
  Formula/squid.rb
  Formula/volta.rb
  Formula/write-good.rb
  Formula/wumpus.rb
Labels: merge

#20140 sagittarius-scheme: depend on zlib for Linuxbrew
  Formula/sagittarius-scheme.rb
Labels: bug, dependency

#20161 certbot: revision bump for libffi
  Formula/certbot.rb
Labels: build failure

#20182 python@3.8: fix python3-config --ldflags
  Formula/python@3.8.rb
Labels: python

#20184 pylint: revision bump for Python 3
  Formula/pylint.rb
Labels: python

#20185 tox: revision bump for Python 3
  Formula/tox.rb
Labels: python

#20186 awscli@1: revision bump for Python 3
  Formula/awscli@1.rb
Labels: python

#20187 awscli: revision bump for Python 3
  Formula/awscli.rb
Labels: python

#20189 anime-downloader: revision bump for Python 3
  Formula/anime-downloader.rb
Labels: python

#20194 Merge 2020-04-21 2fe1503805
  Formula/binaryen.rb
  Formula/git-gui.rb
  Formula/git.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/nuget.rb
  Formula/phpstan.rb
  Formula/pixman.rb
Labels: merge

#20195 Merge 2020-04-22 64b782f2cd
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20196 Merge 2020-04-22 e803140d36
  Formula/aws-google-auth.rb
  Formula/azure-cli.rb
  Formula/contentful-cli.rb
  Formula/llvm@8.rb
  Formula/openssl@1.1.rb
  Formula/quill.rb
  Formula/timewarrior.rb
  Formula/trafficserver.rb
  Formula/wrangler.rb
Labels: merge

#20200 Merge 2020-04-22 c34aaff9e4
  Formula/allure.rb
  Formula/conan.rb
  Formula/contentful-cli.rb
  Formula/davix.rb
  Formula/dolt.rb
  Formula/drafter.rb
  Formula/fastlane.rb
  Formula/gettext.rb
  Formula/gitlab-runner.rb
  Formula/goreleaser.rb
  Formula/jenkins.rb
  Formula/juju.rb
  Formula/lazygit.rb
  Formula/lft.rb
  Formula/libosmium.rb
  Formula/libxmlsec1.rb
  Formula/lxc.rb
  Formula/phoronix-test-suite.rb
  Formula/prometheus.rb
  Formula/sile.rb
  Formula/texlab.rb
  Formula/vala.rb
  Formula/vttest.rb
Labels: merge

#20201 Merge 2020-04-22 62994f9a5d
  Formula/aws-cdk.rb
  Formula/freeling.rb
  Formula/gdbgui.rb
  Formula/gitfs.rb
  Formula/gitg.rb
  Formula/gitless.rb
  Formula/gnome-builder.rb
  Formula/hugo.rb
  Formula/jc.rb
  Formula/libgit2-glib.rb
  Formula/libgit2.rb
  Formula/libpulsar.rb
  Formula/literate-git.rb
  Formula/salt.rb
Labels: merge

#20202 Merge 2020-04-22 17db3c9522
  .github/workflows/tests.yml
Labels: merge

#20203 Merge 2020-04-22 aa7b3bf765
  Formula/entr.rb
  Formula/flyway.rb
  Formula/ratfor.rb
Labels: merge

#20204 Merge 2020-04-23 23ff5a1873
  Formula/cpp-gsl.rb
  Formula/gh.rb
  Formula/jolie.rb
  Formula/libtorch.rb
  Formula/libvirt.rb
  Formula/salt.rb
  Formula/vips.rb
Labels: merge

#20205 Merge 2020-04-23 5859f7903a7
  Aliases/vimcat
  Formula/apache-arrow-glib.rb
  Formula/apache-arrow.rb
  Formula/archivemount.rb
  Formula/boost.rb
  Formula/chakra.rb
  Formula/clozure-cl.rb
  Formula/cookiecutter.rb
  Formula/couchdb.rb
  Formula/cromwell.rb
  Formula/dwdiff.rb
  Formula/freeling.rb
  Formula/geogram.rb
  Formula/git-bug.rb
  Formula/gjs.rb
  Formula/harfbuzz.rb
  Formula/hfstospell.rb
  Formula/icu4c.rb
  Formula/jlog.rb
  Formula/libcdr.rb
  Formula/libfreehand.rb
  Formula/libical.rb
  Formula/liblcf.rb
  Formula/libmspub.rb
  Formula/libphonenumber.rb
  Formula/libtorch.rb
  Formula/libvisio.rb
  Formula/mapnik.rb
  Formula/monero.rb
  Formula/mpd.rb
  Formula/ncmpcpp.rb
  Formula/node.rb
  Formula/node@10.rb
  Formula/node@12.rb
  Formula/opam.rb
  Formula/openrct2.rb
  Formula/osmium-tool.rb
  Formula/pazpar2.rb
  Formula/php.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
  Formula/picat.rb
  Formula/planck.rb
  Formula/postgresql.rb
  Formula/postgresql@10.rb
  Formula/postgresql@11.rb
  Formula/prettier.rb
  Formula/sile.rb
  Formula/tarantool.rb
  Formula/tectonic.rb
  Formula/urweb.rb
  Formula/vte3.rb
  Formula/webpack.rb
  Formula/widelands.rb
  Formula/yaz.rb
  Formula/zebra.rb
  Formula/znc.rb
  Formula/zorba.rb
Labels: merge

#20210 Merge 2020-04-23 288720efe4
  Formula/arangodb.rb
  Formula/awscli.rb
  Formula/babeld.rb
  Formula/bat.rb
  Formula/bazel.rb
  Formula/chezmoi.rb
  Formula/detekt.rb
  Formula/diffoscope.rb
  Formula/enet.rb
  Formula/ensmallen.rb
  Formula/futhark.rb
  Formula/geoserver.rb
  Formula/git-cinnabar.rb
  Formula/grafana.rb
  Formula/helm.rb
  Formula/jbake.rb
  Formula/kvazaar.rb
  Formula/needle.rb
  Formula/nut.rb
  Formula/phpunit.rb
  Formula/scala.rb
  Formula/streamlink.rb
  Formula/tarantool.rb
  Formula/vala.rb
Labels: merge

#20211 Merge 2020-04-24 1eeb3cf253
  Aliases/node@14
  Formula/angular-cli.rb
  Formula/apollo-cli.rb
  Formula/bcoin.rb
  Formula/cargo-completion.rb
  Formula/catch2.rb
  Formula/contentful-cli.rb
  Formula/exploitdb.rb
  Formula/gitlab-runner.rb
  Formula/joplin.rb
  Formula/metabase.rb
  Formula/mill.rb
  Formula/nativefier.rb
  Formula/node.rb
  Formula/nomad.rb
  Formula/parallel.rb
  Formula/pspg.rb
  Formula/sd.rb
  Formula/serverless.rb
  Formula/shadowenv.rb
  Formula/userspace-rcu.rb
  Formula/xmrig.rb
Labels: merge

#20212 Merge 2020-04-24 ca6e877f19
  Formula/autopep8.rb
  Formula/contentful-cli.rb
  Formula/doctl.rb
  Formula/goreleaser.rb
  Formula/inxi.rb
  Formula/istioctl.rb
  Formula/jrtplib.rb
  Formula/libdap.rb
  Formula/mesa.rb
  Formula/msmtp.rb
  Formula/powerline-go.rb
  Formula/wolfssl.rb
Labels: merge

#20214 Merge 2020-04-24 399c06f773
  Formula/aws-cdk.rb
  Formula/capnp.rb
  Formula/cattle.rb
  Formula/ccls.rb
  Formula/chezmoi.rb
  Formula/cpp-gsl.rb
  Formula/datamash.rb
  Formula/exploitdb.rb
  Formula/fs-uae.rb
  Formula/glooctl.rb
  Formula/homebank.rb
  Formula/hugo.rb
  Formula/ispc.rb
  Formula/kops.rb
  Formula/librsvg.rb
  Formula/mpd.rb
  Formula/mpop.rb
  Formula/r.rb
  Formula/rswift.rb
  Formula/solarus.rb
Labels: merge

#20215 Merge 2020-04-25 3d6cd635fc
  Formula/abseil.rb
  Formula/armadillo.rb
  Formula/bartycrouch.rb
  Formula/bash.rb
  Formula/chordii.rb
  Formula/circleci.rb
  Formula/jupyterlab.rb
  Formula/libgeotiff.rb
  Formula/newrelic-cli.rb
  Formula/nift.rb
  Formula/octant.rb
  Formula/pegtl.rb
  Formula/percona-toolkit.rb
  Formula/pspg.rb
  Formula/stress-ng.rb
  Formula/tika.rb
  Formula/tmux.rb
  Formula/uchardet.rb
  Formula/ultralist.rb
  Formula/yapf.rb
Labels: merge

#20217 Merge 2020-04-25 a0e6ed090c
  Formula/asymptote.rb
  Formula/dnstwist.rb
  Formula/glm.rb
  Formula/help2man.rb
  Formula/libetonyek.rb
  Formula/lightgbm.rb
  Formula/ngt.rb
  Formula/r.rb
  Formula/swift.rb
  Formula/xgboost.rb
Labels: merge

#20222 Merge 2020-04-25 f888779204
  .github/workflows/scheduled.yml
Labels: merge

#20223 Merge 2020-04-25 041f7c7802
  Formula/aws-sdk-cpp.rb
  Formula/balena-cli.rb
  Formula/bat.rb
  Formula/bibtexconv.rb
  Formula/borgmatic.rb
  Formula/cbmc.rb
  Formula/cfn-lint.rb
  Formula/ckan.rb
  Formula/devspace.rb
  Formula/e2tools.rb
  Formula/ecl.rb
  Formula/elixir.rb
  Formula/exploitdb.rb
  Formula/geph2.rb
  Formula/grakn.rb
  Formula/iblinter.rb
  Formula/inspircd.rb
  Formula/libphonenumber.rb
  Formula/neomutt.rb
  Formula/odin.rb
  Formula/pdfcrack.rb
  Formula/pmd.rb
  Formula/streamlink.rb
  Formula/sysbench.rb
  Formula/tflint.rb
Labels: merge

#20230 Merge 2020-04-26 7a712a3917
  Formula/nift.rb
  Formula/s-nail.rb
Labels: merge

#20232 Merge 2020-04-26 45076510b3
  .github/workflows/tests.yml
Labels: merge

#20233 Merge 2020-04-26 e8a7d0b9df
  Formula/azcopy.rb
  Formula/balena-cli.rb
  Formula/bats-core.rb
  Formula/cargo-c.rb
  Formula/checkbashisms.rb
  Formula/checkstyle.rb
  Formula/clojurescript.rb
  Formula/diesel.rb
  Formula/diff-so-fancy.rb
  Formula/fastlane.rb
  Formula/fetchmail.rb
  Formula/gitmoji.rb
  Formula/grin-wallet.rb
  Formula/helmfile.rb
  Formula/kpcli.rb
  Formula/librsvg.rb
  Formula/meson.rb
  Formula/mkl-dnn.rb
  Formula/monolith.rb
  Formula/paket.rb
  Formula/parallelstl.rb
  Formula/pcb2gcode.rb
  Formula/vips.rb
  Formula/watchexec.rb
Labels: merge

#20234 Merge 2020-04-27 c9416edaef
  Formula/cargo-c.rb
  Formula/efl.rb
  Formula/git-series.rb
  Formula/grin.rb
  Formula/libcpuid.rb
  Formula/mysql-client.rb
  Formula/mysql-client@5.7.rb
  Formula/xmake.rb
Labels: merge

#20235 Merge 2020-04-27 7dcd5e2be6
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20237 Merge 2020-04-27 48798a1014
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20238 Merge 2020-04-27 3f5ed4e39d
  Formula/autodiff.rb
  Formula/bullet.rb
  Formula/contentful-cli.rb
  Formula/dartsim.rb
  Formula/duplicity.rb
  Formula/efl.rb
  Formula/hadolint.rb
  Formula/hcxtools.rb
  Formula/nushell.rb
  Formula/onscripter.rb
  Formula/pdftk-java.rb
  Formula/plantuml.rb
  Formula/topgrade.rb
Labels: merge

#20239 Merge 2020-04-27 dc8c20150a
  .github/workflows/publish-commit-bottles.yml
  .github/workflows/tests.yml
  Formula/autopep8.rb
  Formula/cython.rb
  Formula/git-delta.rb
  Formula/graphene.rb
  Formula/hashpump.rb
  Formula/heartbeat.rb
  Formula/helmfile.rb
  Formula/honcho.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jenkins-job-builder.rb
  Formula/keepassc.rb
  Formula/khal.rb
  Formula/mitie.rb
  Formula/notifiers.rb
  Formula/wtfutil.rb
Labels: merge

#20242 Merge 2020-04-27 fffcca9775
  Formula/cartridge-cli.rb
  Formula/cdk8s.rb
  Formula/darcs.rb
  Formula/deno.rb
  Formula/diffoscope.rb
  Formula/dnsdist.rb
  Formula/fish.rb
  Formula/help2man.rb
  Formula/jenkins.rb
  Formula/lasso.rb
  Formula/libcec.rb
  Formula/lilv.rb
  Formula/lv2.rb
  Formula/mysql-connector-c++.rb
  Formula/serd.rb
  Formula/sslyze.rb
Labels: merge

#20245 Merge 2020-04-28 60c83db7b5
  Formula/ammonite-repl.rb
  Formula/awscli@1.rb
  Formula/bgpdump.rb
  Formula/cglm.rb
  Formula/cups.rb
  Formula/cypher-shell.rb
  Formula/dita-ot.rb
  Formula/dnstwist.rb
  Formula/frpc.rb
  Formula/frps.rb
  Formula/git-trim.rb
  Formula/opa.rb
  Formula/paket.rb
  Formula/sbcl.rb
  Formula/terragrunt.rb
  Formula/wasm3.rb
  Formula/wtf.rb
Labels: merge

#20246 Merge 2020-04-28 70953a3d0e
  .github/workflows/scheduled.yml
  .github/workflows/tests.yml
  Formula/awscli.rb
  Formula/bitrise.rb
  Formula/bochs.rb
  Formula/diff-pdf.rb
  Formula/erlang@21.rb
  Formula/exploitdb.rb
  Formula/firebase-cli.rb
  Formula/gatsby-cli.rb
  Formula/gjs.rb
  Formula/http-server.rb
  Formula/logtalk.rb
  Formula/pdfpc.rb
  Formula/pdftoipe.rb
  Formula/platformio.rb
  Formula/poppler.rb
  Formula/rust.rb
  Formula/vgmstream.rb
Labels: merge

#20247 Merge 2020-04-28 6d7146213b
  Formula/fselect.rb
  Formula/languagetool.rb
  Formula/pylint.rb
  Formula/qbs.rb
Labels: merge

#20248 Merge 2020-04-28 89dbd4ebff
  Formula/abcl.rb
  Formula/ansible.rb
  Formula/artifactory.rb
  Formula/aws-cdk.rb
  Formula/azure-cli.rb
  Formula/buildifier.rb
  Formula/consul-template.rb
  Formula/gsettings-desktop-schemas.rb
  Formula/platformio.rb
  Formula/robot-framework.rb
  Formula/sourcery.rb
  Formula/starship.rb
Labels: merge

#20243 openssl_test: add missing test dependency
  Formula/openssl@1.1.rb
Labels: dependency

#20249 Merge 2020-04-29 d7e317137a
  Formula/atlantis.rb
  Formula/azure-storage-cpp.rb
  Formula/b3sum.rb
  Formula/diamond.rb
  Formula/doctl.rb
  Formula/erlang.rb
  Formula/openldap.rb
  Formula/pgbouncer.rb
  Formula/spotbugs.rb
Labels: merge

#20251 Merge 2020-04-29 c6fe159082
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20252 Merge 2020-04-29 da7bf37e20
  Formula/astrometry-net.rb
  Formula/calabash.rb
  Formula/cmake.rb
  Formula/datetime-fortran.rb
  Formula/detox.rb
  Formula/dolt.rb
  Formula/envconsul.rb
  Formula/fasttext.rb
  Formula/ffmpeg@2.8.rb
  Formula/folly.rb
  Formula/gatsby-cli.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/inform6.rb
  Formula/ipfs.rb
  Formula/meilisearch.rb
  Formula/nestopia-ue.rb
  Formula/node@12.rb
  Formula/picard-tools.rb
  Formula/pinboard-notes-backup.rb
  Formula/qemu.rb
  Formula/sonobuoy.rb
  Formula/spades.rb
  Formula/treefrog.rb
Labels: merge

#20255 Merge 2020-04-29 bba41429db
  Formula/binaryen.rb
  Formula/blitz.rb
  Formula/cayley.rb
  Formula/cgoban.rb
  Formula/contentful-cli.rb
  Formula/curl-openssl.rb
  Formula/curl.rb
  Formula/dbmate.rb
  Formula/detach.rb
  Formula/dolt.rb
  Formula/exploitdb.rb
  Formula/fcct.rb
  Formula/ffmpeg.rb
  Formula/fish.rb
  Formula/gnu-cobol.rb
  Formula/igraph.rb
  Formula/luaradio.rb
  Formula/makeself.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/oha.rb
  Formula/open-cobol.rb
  Formula/open-image-denoise.rb
  Formula/paket.rb
  Formula/qmmp.rb
  Formula/rsyslog.rb
  Formula/simple-scan.rb
  Formula/sql-translator.rb
  Formula/suricata.rb
  Formula/telegraf.rb
  Formula/triton.rb
  Formula/uftp.rb
  Formula/urh.rb
  Formula/vim.rb
  Formula/vulkan-headers.rb
  Formula/whistle.rb
  Formula/wolfmqtt.rb
  formula_renames.json
Labels: merge

#20258 Merge 2020-04-29 4dc5d27355
  Formula/darcs.rb
  Formula/fonttools.rb
  Formula/minio.rb
  Formula/mu.rb
  Formula/okteto.rb
  Formula/serverless.rb
Labels: merge

#20259 Merge 2020-04-29 12d7c0db82
  Formula/alot.rb
  Formula/docutils.rb
  Formula/ghc.rb
  Formula/ghc@8.6.rb
  Formula/gpgme.rb
  Formula/mypy.rb
  Formula/notmuch.rb
  Formula/otf2.rb
  Formula/salt.rb
  Formula/sphinx-doc.rb
  Formula/varnish.rb
  Formula/xapian.rb
Labels: merge

#20262 Merge 2020-04-30 4159df3e17
  Formula/algol68g.rb
  Formula/ansible@2.8.rb
  Formula/asio.rb
  Formula/bde.rb
  Formula/davix.rb
  Formula/easyrpg-player.rb
  Formula/kubectx.rb
  Formula/liblcf.rb
  Formula/nagios.rb
  Formula/nrpe.rb
  Formula/oha.rb
  Formula/quazip.rb
  Formula/tektoncd-cli.rb
  Formula/traefik.rb
Labels: merge

#20260 systemd: rewrite python shebangs
  Formula/systemd.rb
Labels: python

#20265 Merge 2020-04-30 c582a6d648
  Formula/aws-cdk.rb
  Formula/deno.rb
  Formula/github-release.rb
  Formula/gotop.rb
  Formula/groonga.rb
  Formula/mesa.rb
  Formula/meson.rb
  Formula/phpunit.rb
  Formula/pulumi.rb
  Formula/salt.rb
Labels: merge

#20253 datetime-fortran: fix test for Linuxbrew
  Formula/datetime-fortran.rb
Labels: test failure
