Repository Homebrew/linuxbrew-core, pull requests merged in 2020-08, with the labels that each got.

#20861 Merge 2020-08-01 9b289d27e94
  Formula/alure.rb
  Formula/b3sum.rb
  Formula/carrot2.rb
  Formula/dgraph.rb
  Formula/dps8m.rb
  Formula/exploitdb.rb
  Formula/flawfinder.rb
  Formula/fmt.rb
  Formula/futhark.rb
  Formula/glib.rb
  Formula/hyperfine.rb
  Formula/istioctl.rb
  Formula/jetty-runner.rb
  Formula/jetty.rb
  Formula/k6.rb
  Formula/kumactl.rb
  Formula/manticoresearch.rb
  Formula/node.rb
  Formula/operator-sdk.rb
  Formula/pg_top.rb
  Formula/skopeo.rb
  Formula/solidity.rb
  Formula/swiftformat.rb
  Formula/up.rb
  Formula/v8.rb
  Formula/webpack.rb
  Formula/yafc.rb
Labels: merge

#20863 Merge 2020-08-01 291ffb05cb3
  Formula/packetbeat.rb
Labels: merge

#20864 Merge 2020-08-01 628c7db9fe1
  Formula/aliyun-cli.rb
  Formula/anime-downloader.rb
  Formula/auditbeat.rb
  Formula/babel.rb
  Formula/balena-cli.rb
  Formula/basex.rb
  Formula/cmake.rb
  Formula/consul.rb
  Formula/convox.rb
  Formula/ejabberd.rb
  Formula/emscripten.rb
  Formula/filebeat.rb
  Formula/geckodriver.rb
  Formula/heartbeat.rb
  Formula/jc.rb
  Formula/jupyterlab.rb
  Formula/khal.rb
  Formula/litecli.rb
  Formula/lxc.rb
  Formula/metabase.rb
  Formula/ocrmypdf.rb
  Formula/ode.rb
  Formula/packer.rb
  Formula/php.rb
  Formula/phpstan.rb
  Formula/semgrep.rb
  Formula/spotbugs.rb
  Formula/tox.rb
Labels: merge

#20865 Merge 2020-08-02 aa1b1d38b4
  Formula/postgresql.rb
  Formula/postgresql@10.rb
  Formula/postgresql@11.rb
  Formula/postgresql@9.4.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
Labels: merge

#20867 Merge 2020-08-02 8832e026d2
  Formula/aspectj.rb
  Formula/awscli.rb
  Formula/bond.rb
  Formula/dxpy.rb
  Formula/grpcurl.rb
  Formula/micronaut.rb
  Formula/x264.rb
Labels: merge

#20869 Merge 2020-08-02 7141f37f3a
  .github/workflows/autolabel.yml
  Formula/apidoc.rb
  Formula/bazelisk.rb
  Formula/chibi-scheme.rb
  Formula/circleci.rb
  Formula/cnats.rb
  Formula/conan.rb
  Formula/exploitdb.rb
  Formula/fastlane.rb
  Formula/folderify.rb
  Formula/haproxy.rb
  Formula/libcouchbase.rb
  Formula/libvpx.rb
  Formula/liquidctl.rb
  Formula/minio.rb
  Formula/modules.rb
  Formula/pipgrip.rb
  Formula/ruby-build.rb
  Formula/rust-analyzer.rb
  Formula/terragrunt.rb
  Formula/vault.rb
Labels: merge

#20870 Merge 2020-08-02 431ae12299
  .github/workflows/tests.yml
  Formula/broot.rb
  Formula/diffoscope.rb
  Formula/duckscript.rb
  Formula/flow.rb
  Formula/freerdp.rb
  Formula/iproute2mac.rb
  Formula/nim.rb
  Formula/pnpm.rb
  Formula/qjackctl.rb
  Formula/reorder-python-imports.rb
  Formula/skylighting.rb
  Formula/strongswan.rb
  Formula/xmrig.rb
  Formula/zint.rb
Labels: merge

#20871 Merge 2020-08-02 445aaebf89
  Formula/elasticsearch.rb
  Formula/eslint.rb
  Formula/flarectl.rb
  Formula/glib.rb
  Formula/groonga.rb
  Formula/kibana.rb
  Formula/libde265.rb
  Formula/libgr.rb
  Formula/libmpdclient.rb
  Formula/pango.rb
  Formula/re2c.rb
  Formula/sbcl.rb
Labels: merge

#20872 Merge 2020-08-02 a7e668093c
  Formula/angular-cli.rb
  Formula/archey.rb
  Formula/argocd.rb
  Formula/aws-cdk.rb
  Formula/awscli@1.rb
  Formula/cglm.rb
  Formula/clojure.rb
  Formula/deno.rb
  Formula/eksctl.rb
  Formula/flint.rb
  Formula/fmt.rb
  Formula/geant4.rb
  Formula/glooctl.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/inspircd.rb
  Formula/istioctl.rb
  Formula/mapserver.rb
  Formula/metabase.rb
  Formula/mlt.rb
  Formula/mosh.rb
  Formula/onednn.rb
  Formula/openrtsp.rb
  Formula/ponyc.rb
  Formula/quill.rb
  Formula/rust-analyzer.rb
  Formula/sd.rb
  Formula/sourcedocs.rb
  Formula/telegraf.rb
  Formula/tfenv.rb
  Formula/wla-dx.rb
Labels: merge

#20873 Merge 2020-08-02 86d810bf15
  Formula/gcc.rb
  Formula/ipopt.rb
Labels: merge

#20874 Merge 2020-08-02 b84d8a9ad6
  Formula/gcc.rb
  Formula/gettext.rb
  Formula/ipopt.rb
Labels: merge

#20875 Merge 2020-08-02 a69fef23cc
  Formula/anime-downloader.rb
  Formula/bitcoin.rb
  Formula/caddy.rb
  Formula/cryptol.rb
  Formula/emscripten.rb
  Formula/faudio.rb
  Formula/freeling.rb
  Formula/fzf.rb
  Formula/git-quick-stats.rb
  Formula/git-review.rb
  Formula/gitfs.rb
  Formula/gnuradio.rb
  Formula/gr-osmosdr.rb
  Formula/igv.rb
  Formula/k9s.rb
  Formula/minio-mc.rb
  Formula/openimageio.rb
  Formula/pnpm.rb
  Formula/rust.rb
  Formula/simple-amqp-client.rb
  Formula/skaffold.rb
  Formula/sshguard.rb
  Formula/swiftformat.rb
  Formula/vapoursynth.rb
  Formula/vim.rb
Labels: merge

#20881 Merge 2020-08-02 1257015df3
  Formula/acmetool.rb
  Formula/clamav.rb
  Formula/liblinear.rb
  Formula/mpd.rb
  Formula/nanorc.rb
  Formula/txr.rb
Labels: merge

#20887 Merge 2020-08-03 cef7c62b8d9
  Formula/angle-grinder.rb
  Formula/apollo-cli.rb
  Formula/augustus.rb
  Formula/babl.rb
  Formula/benthos.rb
  Formula/bison.rb
  Formula/cgal.rb
  Formula/cobalt.rb
  Formula/cointop.rb
  Formula/composer.rb
  Formula/django-completion.rb
  Formula/dvc.rb
  Formula/erlang@22.rb
  Formula/gegl.rb
  Formula/gitui.rb
  Formula/golangci-lint.rb
  Formula/harfbuzz.rb
  Formula/howdoi.rb
  Formula/jc.rb
  Formula/kops.rb
  Formula/libmatroska.rb
  Formula/libvirt.rb
  Formula/meilisearch.rb
  Formula/mlt.rb
  Formula/netlify-cli.rb
  Formula/node-build.rb
  Formula/onefetch.rb
  Formula/oxipng.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/pioneers.rb
  Formula/q.rb
  Formula/qalculate-gtk.rb
  Formula/sdns.rb
  Formula/serverless.rb
  Formula/sonar-completion.rb
  Formula/terragrunt.rb
  Formula/tvnamer.rb
  Formula/ultralist.rb
Labels: merge

#20889 Merge 2020-08-04 d41ff9c0893
  Formula/anime-downloader.rb
  Formula/ats2-postiats.rb
  Formula/cobalt.rb
  Formula/duti.rb
  Formula/findent.rb
  Formula/fmdiff.rb
  Formula/folly.rb
  Formula/gatsby-cli.rb
  Formula/git-delta.rb
  Formula/glooctl.rb
  Formula/golang-migrate.rb
  Formula/hebcal.rb
  Formula/helmfile.rb
  Formula/hexgui.rb
  Formula/igv.rb
  Formula/ispc.rb
  Formula/jruby.rb
  Formula/miller.rb
  Formula/minimal-racket.rb
  Formula/mongo-c-driver.rb
  Formula/mycli.rb
  Formula/nfdump.rb
  Formula/pandoc-citeproc.rb
  Formula/rbenv-gemset.rb
  Formula/re-flex.rb
  Formula/re2c.rb
  Formula/rust-analyzer.rb
  Formula/sqlmap.rb
  Formula/swiftformat.rb
  Formula/vulkan-headers.rb
  Formula/xclogparser.rb
Labels: merge

#20901 Merge 2020-08-04 1eaaa27ddf4
  .github/workflows/autolabel.yml
  Formula/apollo.rb
  Formula/athenacli.rb
  Formula/aws-sdk-cpp.rb
  Formula/azure-cli.rb
  Formula/bond.rb
  Formula/c7n.rb
  Formula/cask.rb
  Formula/cfn-lint.rb
  Formula/cloudformation-cli.rb
  Formula/dhall-bash.rb
  Formula/dhall-json.rb
  Formula/dhall-lsp-server.rb
  Formula/dhall-yaml.rb
  Formula/dhall.rb
  Formula/django-completion.rb
  Formula/dosbox-x.rb
  Formula/duti.rb
  Formula/fades.rb
  Formula/fmdiff.rb
  Formula/freexl.rb
  Formula/ginac.rb
  Formula/janet.rb
  Formula/kakoune.rb
  Formula/osm2pgsql.rb
  Formula/phpstan.rb
  Formula/pipgrip.rb
  Formula/rbenv-gemset.rb
  Formula/re2c.rb
  Formula/s2geometry.rb
  Formula/silicon.rb
  Formula/subliminal.rb
  Formula/tox.rb
  Formula/uwsgi.rb
  Formula/xbee-comm.rb
  Formula/xcodegen.rb
Labels: merge

#20902 Merge 2020-08-05 eb1e6951c1
  Formula/ask-cli.rb
  Formula/babel.rb
  Formula/fortio.rb
  Formula/heksa.rb
  Formula/jenkins.rb
  Formula/libgusb.rb
  Formula/metabase.rb
  Formula/minikube.rb
  Formula/pnpm.rb
  Formula/pulumi.rb
  Formula/ringojs.rb
  Formula/rocksdb.rb
  Formula/rust.rb
  Formula/serverless.rb
  Formula/shallow-backup.rb
  Formula/skaffold.rb
  Formula/swiftgen.rb
  Formula/vsts-cli.rb
Labels: merge

#20903 Merge 2020-08-06 ddb476f9f6
  Formula/aliyun-cli.rb
  Formula/anime-downloader.rb
  Formula/awscli.rb
  Formula/balena-cli.rb
  Formula/c7n.rb
  Formula/certbot.rb
  Formula/circleci.rb
  Formula/clojure-lsp.rb
  Formula/dolt.rb
  Formula/exploitdb.rb
  Formula/fetch.rb
  Formula/git-archive-all.rb
  Formula/html-xml-utils.rb
  Formula/inko.rb
  Formula/isync.rb
  Formula/jasper.rb
  Formula/jc.rb
  Formula/man-db.rb
  Formula/mgba.rb
  Formula/minio.rb
  Formula/oci-cli.rb
  Formula/pgrouting.rb
  Formula/phpstan.rb
  Formula/prest.rb
  Formula/proteinortho.rb
  Formula/s-lang.rb
  Formula/serf.rb
  Formula/solidity.rb
  Formula/spades.rb
  Formula/spigot.rb
  Formula/sql-translator.rb
  Formula/sratoolkit.rb
  Formula/starship.rb
  Formula/stdman.rb
  Formula/subversion.rb
  Formula/vault-cli.rb
  Formula/volta.rb
  Formula/yuicompressor.rb
Labels: merge

#20907 Merge 2020-08-06 85250e72099
  Formula/civl.rb
  Formula/cointop.rb
  Formula/fits.rb
  Formula/ghc.rb
  Formula/ghc@8.6.rb
  Formula/ghc@8.8.rb
  Formula/giter8.rb
  Formula/gnuradio.rb
  Formula/grafana.rb
  Formula/libtorrent-rasterbar.rb
  Formula/libxlsxwriter.rb
  Formula/mercurial.rb
  Formula/rust.rb
  Formula/spades.rb
  Formula/zbar.rb
Labels: merge

#20911 Merge 2020-08-08 2e8996f703f
  .github/workflows/tests.yml
Labels: merge

#20912 Merge 2020-08-08 5818ceac132
  .github/workflows/autopublish.yml
  .github/workflows/publish-commit-bottles.yml
  .github/workflows/tests.yml
  Formula/azure-cli.rb
  Formula/caf.rb
  Formula/mesa.rb
  Formula/mlton.rb
  Formula/snapcraft.rb
  Formula/torchvision.rb
  Formula/zeek.rb
Labels: merge

#20913 Merge 2020-08-08 8a92b019f50
  Formula/aha.rb
  Formula/cbmc.rb
  Formula/conan.rb
  Formula/convox.rb
  Formula/fastlane.rb
  Formula/fblog.rb
  Formula/firebase-cli.rb
  Formula/go@1.13.rb
  Formula/grafana.rb
  Formula/jc.rb
  Formula/libmaxminddb.rb
  Formula/openrtsp.rb
  Formula/perl.rb
  Formula/po4a.rb
Labels: merge

#20915 Merge 2020-08-09 bc1cb9713b8
  .github/workflows/autopublish.yml
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20916 Merge 2020-08-09 47e30f00c0e
  Formula/apache-opennlp.rb
  Formula/bazelisk.rb
  Formula/clib.rb
  Formula/fastlane.rb
  Formula/flank.rb
  Formula/fluxctl.rb
  Formula/gitlab-runner.rb
  Formula/hcxtools.rb
  Formula/httpd.rb
  Formula/imlib2.rb
  Formula/libomp.rb
  Formula/mesa.rb
  Formula/nfpm.rb
  Formula/ocrmypdf.rb
  Formula/php.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
  Formula/phpunit.rb
  Formula/pipgrip.rb
  Formula/prometheus.rb
  Formula/pulumi.rb
  Formula/rabbitmq.rb
  Formula/reposurgeon.rb
  Formula/rust-analyzer.rb
  Formula/sagittarius-scheme.rb
  Formula/semgrep.rb
  Formula/sheldon.rb
  Formula/tektoncd-cli.rb
  Formula/tox.rb
  Formula/virgil.rb
  Formula/xcenv.rb
Labels: merge

#20917 Merge 2020-08-09 7fe5f6b22e8
  Formula/argo.rb
  Formula/aws-cdk.rb
  Formula/awscli.rb
  Formula/balena-cli.rb
  Formula/clojure.rb
  Formula/diffoscope.rb
  Formula/drone-cli.rb
  Formula/exploitdb.rb
  Formula/fastlane.rb
  Formula/fmt.rb
  Formula/genact.rb
  Formula/helmfile.rb
  Formula/hey.rb
  Formula/kyma-cli.rb
  Formula/libqalculate.rb
  Formula/libtrace.rb
  Formula/liquidctl.rb
  Formula/makensis.rb
  Formula/paket.rb
  Formula/pulumi.rb
  Formula/rsync.rb
  Formula/sagittarius-scheme.rb
  Formula/salt.rb
  Formula/ship.rb
  Formula/swift-protobuf.rb
  Formula/swift.rb
  Formula/vlang.rb
Labels: merge

#20920 Merge 2020-08-09 50be1b48552
  Formula/clojure-lsp.rb
  Formula/consul.rb
  Formula/devspace.rb
  Formula/goreleaser.rb
  Formula/jfrog-cli.rb
  Formula/lame.rb
  Formula/mruby.rb
  Formula/nlohmann-json.rb
  Formula/phpunit.rb
  Formula/range-v3.rb
  Formula/scrcpy.rb
  Formula/swiftformat.rb
Labels: merge

#20923 Merge 2020-08-09 7224d7371f8
  .github/workflows/tests.yml
Labels: merge

#20924 Merge 2020-08-09 22a08272036
  Formula/dvc.rb
  Formula/haskell-stack.rb
  Formula/helmfile.rb
  Formula/ios-webkit-debug-proxy.rb
  Formula/lean-cli.rb
  Formula/rclone.rb
  Formula/re2c.rb
Labels: merge

#20925 Merge 2020-08-09 f4de94de671
  .github/workflows/tests.yml
Labels: merge

#20575 glibc: update requirements
  Formula/glibc.rb
Labels: bug, in progress

#20926 Merge 2020-08-09 6782796918d
  Formula/berglas.rb
  Formula/cryptol.rb
  Formula/darcs.rb
  Formula/flow.rb
  Formula/git-annex.rb
  Formula/helmfile.rb
  Formula/lmod.rb
  Formula/mame.rb
  Formula/maxwell.rb
  Formula/neovim.rb
  Formula/osm.rb
  Formula/rom-tools.rb
  Formula/simple-amqp-client.rb
Labels: merge

#20927 Merge 2020-08-09 c156e5277a7
  .github/workflows/tests.yml
Labels: merge

#20929 Merge 2020-08-09 a48f18bee6c
  Formula/cheat.rb
  Formula/doxygen.rb
  Formula/file-roller.rb
  Formula/gatsby-cli.rb
  Formula/git-delta.rb
  Formula/imagemagick@6.rb
  Formula/kde-extra-cmake-modules.rb
  Formula/kde-karchive.rb
  Formula/kde-kdoctools.rb
  Formula/kde-ki18n.rb
  Formula/kde-threadweaver.rb
  Formula/lbzip2.rb
  Formula/pandoc-crossref.rb
  Formula/psc-package.rb
  Formula/shelltestrunner.rb
  Formula/swiftformat.rb
  Formula/tre-command.rb
  Formula/vim.rb
Labels: merge

#20932 Merge 2020-08-10 17b60031791
  Formula/abcmidi.rb
  Formula/acpica.rb
  Formula/check.rb
  Formula/clojure-lsp.rb
  Formula/clojure.rb
  Formula/deno.rb
  Formula/devspace.rb
  Formula/dlib.rb
  Formula/exploitdb.rb
  Formula/fennel.rb
  Formula/ghc.rb
  Formula/hcloud.rb
  Formula/imagemagick.rb
  Formula/oci-cli.rb
  Formula/phpstan.rb
  Formula/phpunit.rb
  Formula/pnpm.rb
  Formula/pyinstaller.rb
  Formula/rake-completion.rb
  Formula/swift.rb
  Formula/virgil.rb
  Formula/whistle.rb
  Formula/wtf.rb
  Formula/x3270.rb
  Formula/yadm.rb
  Formula/ydiff.rb
Labels: merge

#20934 Merge 2020-08-10 b64fab07cf4
  .github/workflows/autolabel.yml
  Formula/dashing.rb
  Formula/folly.rb
  Formula/node.rb
  Formula/openrtsp.rb
Labels: merge

#20936 Merge 2020-08-10 d9ae068c3f4
  Formula/genact.rb
  Formula/gupnp.rb
  Formula/jfrog-cli.rb
  Formula/jupyterlab.rb
  Formula/php-code-sniffer.rb
  Formula/pnpm.rb
  Formula/procs.rb
  Formula/swiftlint.rb
  Formula/talisman.rb
  Formula/taskell.rb
  Formula/tomee-plume.rb
  Formula/tomee-plus.rb
  Formula/vala.rb
  Formula/vips.rb
Labels: merge

#20937 Merge 2020-08-11 3a70e321c3f
  .github/workflows/autolabel.yml
  Aliases/terraform@0.13
  Formula/devspace.rb
  Formula/gitmoji.rb
  Formula/gradle.rb
  Formula/kubeaudit.rb
  Formula/mariadb.rb
  Formula/sphinx-doc.rb
  Formula/terraform.rb
  Formula/ugrep.rb
Labels: merge

#20939 Merge 2020-08-11 b4287a4179f
  Formula/acl2.rb
  Formula/anime-downloader.rb
  Formula/cgl.rb
  Formula/charge.rb
  Formula/clp.rb
  Formula/eleventy.rb
  Formula/gostatic.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/kondo.rb
  Formula/nativefier.rb
  Formula/pandocomatic.rb
  Formula/scrcpy.rb
  Formula/supervisor.rb
  Formula/ugrep.rb
  Formula/vale.rb
Labels: merge

#20548 patchelf 0.11
  Formula/patchelf.rb
Labels: in progress

#20942 Merge 2020-08-12 49ee78d845f
  Formula/athenacli.rb
  Formula/bwfmetaedit.rb
  Formula/cbmc.rb
  Formula/clojure.rb
  Formula/empty.rb
  Formula/ethereum.rb
  Formula/exploitdb.rb
  Formula/fastlane.rb
  Formula/flank.rb
  Formula/git-annex.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/helm.rb
  Formula/k3d.rb
  Formula/media-info.rb
  Formula/microplane.rb
  Formula/mosquitto.rb
  Formula/netdata.rb
  Formula/node.rb
  Formula/phpunit.rb
  Formula/rust-analyzer.rb
  Formula/s3fs.rb
  Formula/snakemake.rb
  Formula/swift-sh.rb
  Formula/swiftformat.rb
  Formula/syncthing.rb
  Formula/terraform-ls.rb
  Formula/terraform@0.12.rb
Labels: merge

#20943 Merge 2020-08-12 e73b97e318a
  Formula/artifactory.rb
  Formula/asymptote.rb
  Formula/awscli.rb
  Formula/awsweeper.rb
  Formula/cbc.rb
  Formula/chakra.rb
  Formula/chezmoi.rb
  Formula/datasette.rb
  Formula/easyengine.rb
  Formula/exploitdb.rb
  Formula/geph2.rb
  Formula/gtk+3.rb
  Formula/gxml.rb
  Formula/istioctl.rb
  Formula/kyma-cli.rb
  Formula/mdbook.rb
  Formula/mu.rb
  Formula/pango.rb
  Formula/semgrep.rb
  Formula/talisman.rb
  Formula/triton.rb
  Formula/vips.rb
  Formula/write-good.rb
Labels: merge

#20945 Merge 2020-08-12 a645bdd42e8
  Formula/fluent-bit.rb
  Formula/jenkins.rb
  Formula/kumactl.rb
  Formula/lcov.rb
  Formula/mdcat.rb
  Formula/nushell.rb
  Formula/smimesign.rb
  Formula/sysdig.rb
Labels: merge

#20950 binutils: Add cellar :any
  Formula/binutils.rb
Labels: bug

#20951 Merge 2020-08-13 f1b4c56655a
  Aliases/mariadb@10.5
  Formula/avfs.rb
  Formula/aws-cdk.rb
  Formula/bettercap.rb
  Formula/cartridge-cli.rb
  Formula/consul.rb
  Formula/contentful-cli.rb
  Formula/datasette.rb
  Formula/gpsd.rb
  Formula/helm@2.rb
  Formula/ilmbase.rb
  Formula/links.rb
  Formula/lmdb.rb
  Formula/mariadb.rb
  Formula/minikube.rb
  Formula/nginx.rb
  Formula/ocrmypdf.rb
  Formula/octant.rb
  Formula/openldap.rb
  Formula/openttd.rb
  Formula/passenger.rb
  Formula/podiff.rb
  Formula/snort.rb
  Formula/sqlite-utils.rb
  Formula/stress-ng.rb
  Formula/teleport.rb
  Formula/v8.rb
  Formula/whistle.rb
Labels: merge

#20952 Merge 2020-08-14 53f1bf78c83
  Formula/aalib.rb
  Formula/aften.rb
  Formula/apng2gif.rb
  Formula/aview.rb
  Formula/base91.rb
  Formula/bluepill.rb
  Formula/bvi.rb
  Formula/clojure-lsp.rb
  Formula/ctags.rb
  Formula/docbook2x.rb
  Formula/docx2txt.rb
  Formula/doublecpp.rb
  Formula/dvdbackup.rb
  Formula/exploitdb.rb
  Formula/gauche.rb
  Formula/gitleaks.rb
  Formula/gptsync.rb
  Formula/harbour.rb
  Formula/libcddb.rb
  Formula/libdv.rb
  Formula/libmodplug.rb
  Formula/libpng.rb
  Formula/lxsplit.rb
  Formula/mergelog.rb
  Formula/mp3val.rb
  Formula/msdl.rb
  Formula/netlify-cli.rb
  Formula/oauth2l.rb
  Formula/opencore-amr.rb
  Formula/podofo.rb
  Formula/qjackctl.rb
  Formula/qrupdate.rb
  Formula/tile38.rb
  Formula/ttf2pt1.rb
  Formula/two-lame.rb
  Formula/ucon64.rb
  Formula/udis86.rb
  Formula/w-calc.rb
Labels: merge

#20953 Merge 2020-08-14 a9c13a37e6d
  .github/workflows/autopublish.yml
  Formula/btfs.rb
  Formula/ccache.rb
  Formula/cglm.rb
  Formula/clojurescript.rb
  Formula/closure-compiler.rb
  Formula/crowdin.rb
  Formula/deheader.rb
  Formula/detekt.rb
  Formula/fdupes.rb
  Formula/flank.rb
  Formula/flint.rb
  Formula/flyway.rb
  Formula/fmpp.rb
  Formula/frege.rb
  Formula/gcviewer.rb
  Formula/git-credential-manager.rb
  Formula/helmfile.rb
  Formula/hopenpgp-tools.rb
  Formula/jasmin.rb
  Formula/jetty-runner.rb
  Formula/jflex.rb
  Formula/jsonschema2pojo.rb
  Formula/kafka.rb
  Formula/kumo.rb
  Formula/libxlsxwriter.rb
  Formula/mariadb@10.1.rb
  Formula/metabase.rb
  Formula/nano.rb
  Formula/openexr.rb
  Formula/openrtsp.rb
  Formula/pipenv.rb
  Formula/prestodb.rb
  Formula/prestosql.rb
  Formula/sdedit.rb
  Formula/selenium-server-standalone.rb
  Formula/sjk.rb
  Formula/smali.rb
  Formula/swagger2markup-cli.rb
  Formula/tika.rb
  Formula/vnu.rb
Labels: merge

#20955 Merge 2020-08-14 7b4524a329b
  Formula/angular-cli.rb
  Formula/ballerina.rb
  Formula/bde.rb
  Formula/chibi-scheme.rb
  Formula/dbmate.rb
  Formula/deno.rb
  Formula/dolt.rb
  Formula/ensmallen.rb
  Formula/fastlane.rb
  Formula/gifski.rb
  Formula/google-sparsehash.rb
  Formula/mariadb@10.3.rb
  Formula/nomad.rb
  Formula/onioncat.rb
  Formula/postgresql.rb
  Formula/postgresql@10.rb
  Formula/postgresql@11.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
  Formula/qemu.rb
  Formula/s3ql.rb
  Formula/semgrep.rb
  Formula/subfinder.rb
  Formula/taskell.rb
  Formula/vulkan-headers.rb
  Formula/wal2json.rb
Labels: merge

#20958 Merge 2020-08-14 bbea9bfcf72
  Formula/awscli.rb
  Formula/cdk8s.rb
  Formula/cloudformation-cli.rb
  Formula/dcd.rb
  Formula/detekt.rb
  Formula/docker-slim.rb
  Formula/dvc.rb
  Formula/flint.rb
  Formula/frugal.rb
  Formula/jenkins-lts.rb
  Formula/libphonenumber.rb
  Formula/llvm.rb
  Formula/mask.rb
  Formula/minio.rb
  Formula/nomad.rb
  Formula/snakemake.rb
  Formula/sourcery.rb
  Formula/txr.rb
  Formula/wxpython.rb
  Formula/yaegi.rb
  Formula/zookeeper.rb
Labels: merge

#20963 Merge 2020-08-14 6a77320bbe5
  Formula/circleci.rb
  Formula/exploitdb.rb
  Formula/harfbuzz.rb
  Formula/helmfile.rb
  Formula/k3d.rb
  Formula/kubernetes-cli.rb
  Formula/staticcheck.rb
  Formula/teleport.rb
Labels: merge

#20965 Merge 2020-08-15 ce5e5881278
  Formula/cointop.rb
  Formula/deheader.rb
  Formula/gnumeric.rb
  Formula/goffice.rb
  Formula/mariadb@10.2.rb
  Formula/operator-sdk.rb
  Formula/ugrep.rb
Labels: merge

#20966 Merge 2020-08-15 2ec67251d4d
  .github/workflows/autocancel.yml
  .github/workflows/autopublish.yml
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20967 Merge 2020-08-15 a46928c4f79
  Formula/acpica.rb
  Formula/apidoc.rb
  Formula/bundletool.rb
  Formula/choose-rust.rb
  Formula/contentful-cli.rb
  Formula/dbhash.rb
  Formula/envconsul.rb
  Formula/gitmoji.rb
  Formula/graphviz.rb
  Formula/lean.rb
  Formula/mmctl.rb
  Formula/sile.rb
  Formula/sqldiff.rb
  Formula/sqlite-analyzer.rb
  Formula/vim.rb
Labels: merge

#20971 Merge 2020-08-16 115465b8ada
  Formula/algernon.rb
  Formula/awscli@1.rb
  Formula/caddy.rb
  Formula/cfn-lint.rb
  Formula/clojure-lsp.rb
  Formula/comby.rb
  Formula/csound.rb
  Formula/datasette.rb
  Formula/diffoscope.rb
  Formula/go.rb
  Formula/go@1.13.rb
  Formula/go@1.14.rb
  Formula/godep.rb
  Formula/ipfs.rb
  Formula/kotlin.rb
  Formula/kyma-cli.rb
  Formula/lftp.rb
  Formula/logcli.rb
  Formula/mailutils.rb
  Formula/patchelf.rb
  Formula/prest.rb
  Formula/quill.rb
  Formula/snakemake.rb
  Formula/sqlite.rb
  Formula/syncthing.rb
  Formula/wireshark.rb
Labels: merge

#20906 gcc: Depends on glibc if the host glibc is too old
  Formula/gcc.rb
Labels: bug

#20977 Merge 2020-08-18 5f9cffaf24a
  Formula/go.rb
  Formula/go@1.10.rb
  Formula/go@1.11.rb
  Formula/go@1.12.rb
  Formula/go@1.13.rb
  Formula/go@1.14.rb
  Formula/go@1.9.rb
  Formula/prest.rb
  Formula/vale.rb
  Formula/virgil.rb
Labels: merge

#21017 Merge 2020-08-24 1153440ac9
  .github/workflows/autopublish.yml
  .github/workflows/publish-commit-bottles.yml
  Formula/agda.rb
  Formula/alexjs.rb
  Formula/angle-grinder.rb
  Formula/bash-preexec.rb
  Formula/broot.rb
  Formula/cheat.rb
  Formula/contentful-cli.rb
  Formula/docker-slim.rb
  Formula/ettercap.rb
  Formula/gdbgui.rb
  Formula/gopass.rb
  Formula/gostatic.rb
  Formula/gsoap.rb
  Formula/hbase.rb
  Formula/just.rb
  Formula/libtorrent-rasterbar.rb
  Formula/parallel.rb
  Formula/perl-build.rb
  Formula/perltidy.rb
  Formula/pipx.rb
  Formula/plantuml.rb
  Formula/pre-commit.rb
  Formula/pylint.rb
  Formula/subfinder.rb
  Formula/tflint.rb
  Formula/topgrade.rb
  Formula/vale.rb
  Formula/zimg.rb
Labels: merge

#21024 Merge 2020-08-28 b222ddbb9c
  Formula/angular-cli.rb
  Formula/arduino-cli.rb
  Formula/argocd.rb
  Formula/ask-cli.rb
  Formula/brotli.rb
  Formula/calicoctl.rb
  Formula/cargo-c.rb
  Formula/chronograf.rb
  Formula/clojure-lsp.rb
  Formula/comby.rb
  Formula/contentful-cli.rb
  Formula/cubejs-cli.rb
  Formula/fantom.rb
  Formula/firebase-cli.rb
  Formula/gateway-go.rb
  Formula/gor.rb
  Formula/hcloud.rb
  Formula/helmfile.rb
  Formula/i2pd.rb
  Formula/iperf3.rb
  Formula/kubernetes-cli.rb
  Formula/libcouchbase.rb
  Formula/libexosip.rb
  Formula/libheif.rb
  Formula/logcli.rb
  Formula/nano.rb
  Formula/navi.rb
  Formula/open-mpi.rb
  Formula/openrtsp.rb
  Formula/phpstan.rb
  Formula/phpunit.rb
  Formula/prettier.rb
  Formula/promtail.rb
  Formula/rancher-cli.rb
  Formula/re-flex.rb
  Formula/rke.rb
  Formula/rust-analyzer.rb
  Formula/rust.rb
  Formula/serverless.rb
  Formula/shellshare.rb
  Formula/slowhttptest.rb
  Formula/sonobuoy.rb
  Formula/sshuttle.rb
  Formula/stellar-core.rb
  Formula/talisman.rb
  Formula/terraform.rb
  Formula/terragrunt.rb
  Formula/tippecanoe.rb
  Formula/wgcf.rb
  Formula/xapian.rb
  Formula/xgboost.rb
  Formula/xonsh.rb
  Formula/zabbix.rb
Labels: merge

#21028 Merge 2020-08-29 420d54b447
  Formula/a52dec.rb
  Formula/abook.rb
  Formula/augustus.rb
  Formula/basex.rb
  Formula/bbftp-client.rb
  Formula/bcrypt.rb
  Formula/bsdiff.rb
  Formula/circleci.rb
  Formula/concurrencykit.rb
  Formula/dialog.rb
  Formula/fortune.rb
  Formula/freetds.rb
  Formula/gl2ps.rb
  Formula/i2util.rb
  Formula/jruby.rb
  Formula/libspatialite.rb
  Formula/lxc.rb
  Formula/mhonarc.rb
  Formula/minizip.rb
  Formula/ntp.rb
  Formula/owamp.rb
  Formula/parallel.rb
  Formula/ragel.rb
  Formula/ren.rb
  Formula/sipcalc.rb
  Formula/smpeg.rb
  Formula/smpeg2.rb
  Formula/spades.rb
  Formula/swaks.rb
  Formula/ungit.rb
Labels: merge

#21030 Merge 2020-08-29 90fbed54b7f
  Formula/act.rb
  Formula/ballerina.rb
  Formula/bundletool.rb
  Formula/deno.rb
  Formula/diffoscope.rb
  Formula/dxpy.rb
  Formula/exploitdb.rb
  Formula/feh.rb
  Formula/gatsby-cli.rb
  Formula/harfbuzz.rb
  Formula/helmfile.rb
  Formula/ispc.rb
  Formula/kustomize.rb
  Formula/nuget.rb
  Formula/ponyc.rb
  Formula/qrencode.rb
Labels: merge

#21031 Merge 2020-08-29 56f1b977cea
  Formula/patchelf.rb
Labels: merge

#21034 Merge 2020-08-30 56e3eb5031
  Aliases/v8@8.5
  Formula/act.rb
  Formula/cadence.rb
  Formula/checkstyle.rb
  Formula/emscripten.rb
  Formula/ghz-web.rb
  Formula/ghz.rb
  Formula/graphite2.rb
  Formula/graphviz.rb
  Formula/hexedit.rb
  Formula/ipython.rb
  Formula/jfrog-cli.rb
  Formula/librealsense.rb
  Formula/lmod.rb
  Formula/lsd.rb
  Formula/mongo-c-driver.rb
  Formula/mono.rb
  Formula/mosh.rb
  Formula/nasm.rb
  Formula/nativefier.rb
  Formula/packer.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
  Formula/physfs.rb
  Formula/sqlite-utils.rb
  Formula/taskell.rb
  Formula/v8.rb
  Formula/yasm.rb
  Formula/zbar.rb
Labels: merge

#21039 Merge 2020-08-31 32624e05ed9
  .github/workflows/tests.yml
Labels: merge

#21040 Merge 2020-08-31 1f581a16f16
  .github/ISSUE_TEMPLATE/bug.md
  Aliases/brz
  Formula/anime-downloader.rb
  Formula/atf.rb
  Formula/aws-apigateway-importer.rb
  Formula/cbmc.rb
  Formula/chezscheme.rb
  Formula/dartsim.rb
  Formula/drone-cli.rb
  Formula/duckdb.rb
  Formula/dvc.rb
  Formula/editorconfig.rb
  Formula/genometools.rb
  Formula/gleam.rb
  Formula/gnu-chess.rb
  Formula/gnu-go.rb
  Formula/joe.rb
  Formula/makeself.rb
  Formula/maxwell.rb
  Formula/morse.rb
  Formula/mutt.rb
  Formula/navi.rb
  Formula/netlify-cli.rb
  Formula/nwchem.rb
  Formula/openstackclient.rb
  Formula/progress.rb
  Formula/scrypt.rb
  Formula/seal.rb
  Formula/swiftformat.rb
  Formula/vim.rb
  Formula/xmrig.rb
  Formula/xxh.rb
Labels: merge
