Repository Homebrew/linuxbrew-core, pull requests merged in 2020-12, with the labels that each got.

#21685 Merge 2020-12-01 aec951f038
  Formula/chart-testing.rb
  Formula/ckan.rb
  Formula/feh.rb
  Formula/freeciv.rb
  Formula/github-markdown-toc.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/kubie.rb
  Formula/phive.rb
  Formula/plantuml.rb
  Formula/silicon.rb
  Formula/structurizr-cli.rb
  Formula/syncthing.rb
  Formula/t-rec.rb
  Formula/termius.rb
  Formula/valabind.rb
  Formula/youtube-dlc.rb
Labels: merge

#21684 hello: update 2.10 bottle for Linux
  Formula/hello.rb
Labels: bottle

#21686 Merge 2020-12-01 ede053fa72
  .github/workflows/stale.yml
Labels: merge

#21687 Merge 2020-12-01 97b9f109be
  Formula/cargo-c.rb
  Formula/cargo-edit.rb
  Formula/contentful-cli.rb
  Formula/dynare.rb
  Formula/envconsul.rb
  Formula/exa.rb
  Formula/exploitdb.rb
  Formula/git-series.rb
  Formula/gitfs.rb
  Formula/gitg.rb
  Formula/gitless.rb
  Formula/gopls.rb
  Formula/goreleaser.rb
  Formula/kotlin.rb
  Formula/libgit2-glib.rb
  Formula/libgit2.rb
  Formula/liblouis.rb
  Formula/literate-git.rb
  Formula/octave.rb
  Formula/openssl@1.1.rb
  Formula/phpunit.rb
  Formula/pyside.rb
  Formula/qt.rb
  Formula/salt.rb
  Formula/vgmstream.rb
Labels: merge

#21688 Merge 2020-12-01 1550673eb6
  Formula/astrometry-net.rb
  Formula/django-completion.rb
  Formula/glab.rb
  Formula/glibmm.rb
  Formula/i2pd.rb
  Formula/libcaca.rb
  Formula/libslax.rb
  Formula/libxi.rb
  Formula/mplayer.rb
  Formula/node-build.rb
  Formula/omega.rb
  Formula/percona-server.rb
  Formula/percona-xtrabackup.rb
  Formula/protobuf.rb
  Formula/python@3.9.rb
Labels: merge

#21690 Merge 2020-12-01 c78526ca98
  Formula/jenkins.rb
Labels: merge

#21691 Merge 2020-12-01 4dec8d8b38
  .github/support.yml
  .github/workflows/scheduled-triage.yml
Labels: merge

#21692 Merge 2020-12-01 921f180f60
  Formula/aliyun-cli.rb
  Formula/awscli.rb
  Formula/dosbox-x.rb
  Formula/flux.rb
  Formula/gnuplot.rb
  Formula/hwloc.rb
  Formula/ioctl.rb
  Formula/libpulsar.rb
  Formula/menhir.rb
  Formula/microplane.rb
  Formula/nim.rb
Labels: merge

#21693 Merge 2020-12-02 0adda83c4f
  Formula/aws-cdk.rb
  Formula/broot.rb
  Formula/code-server.rb
  Formula/contentful-cli.rb
  Formula/cubejs-cli.rb
  Formula/dbhash.rb
  Formula/docker-completion.rb
  Formula/docker.rb
  Formula/earthly.rb
  Formula/fabio.rb
  Formula/fastlane.rb
  Formula/faudio.rb
  Formula/flank.rb
  Formula/fortio.rb
  Formula/libvirt.rb
  Formula/mongo-c-driver.rb
  Formula/nco.rb
  Formula/okteto.rb
  Formula/podman.rb
  Formula/skaffold.rb
  Formula/sqldiff.rb
  Formula/sqlite-analyzer.rb
  Formula/sqlmap.rb
  Formula/topgrade.rb
  Formula/twarc.rb
  Formula/whistle.rb
  Formula/xmrig.rb
  Formula/youtube-dl.rb
Labels: merge

#21694 Merge 2020-12-02 6d7fd44bb5
  .github/workflows/scheduled-triage.yml
Labels: merge

#21695 Merge 2020-12-02 743e404a62
  Formula/dwarfutils.rb
  Formula/exploitdb.rb
  Formula/minisign.rb
  Formula/semgrep.rb
  Formula/zabbix.rb
Labels: merge

#21698 Merge 2020-12-03 88132eb4a1
  Aliases/terraform@0.14
  Formula/apollo-cli.rb
  Formula/bitwarden-cli.rb
  Formula/buildkit.rb
  Formula/contentful-cli.rb
  Formula/diamond.rb
  Formula/dolt.rb
  Formula/draco.rb
  Formula/duck.rb
  Formula/firebase-cli.rb
  Formula/flank.rb
  Formula/gatsby-cli.rb
  Formula/glab.rb
  Formula/gping.rb
  Formula/groonga.rb
  Formula/hcxtools.rb
  Formula/infer.rb
  Formula/infracost.rb
  Formula/jenkins-lts.rb
  Formula/json5.rb
  Formula/kubecm.rb
  Formula/liblouis.rb
  Formula/libphonenumber.rb
  Formula/libtirpc.rb
  Formula/nano.rb
  Formula/netlify-cli.rb
  Formula/pulumi.rb
  Formula/rustup-init.rb
  Formula/telegraf.rb
  Formula/terraform.rb
  Formula/terraformer.rb
  Formula/whistle.rb
  Formula/yeti.rb
  audit_exceptions/throttled_formulae.json
Labels: merge

#21709 Merge 2020-12-05 cc60bcab602
  Formula/cdogs-sdl.rb
  Formula/cfn-format.rb
  Formula/chronograf.rb
  Formula/cmake.rb
  Formula/commitizen.rb
  Formula/docker-ls.rb
  Formula/dosbox-staging.rb
  Formula/druid.rb
  Formula/exploitdb.rb
  Formula/fontforge.rb
  Formula/gauge.rb
  Formula/gnirehtet.rb
  Formula/k3d.rb
  Formula/kubecm.rb
  Formula/lua@5.3.rb
  Formula/metabase.rb
  Formula/minimal-racket.rb
  Formula/mps-youtube.rb
  Formula/pari.rb
  Formula/pcre2.rb
  Formula/platypus.rb
  Formula/postgresql@10.rb
  Formula/postgresql@11.rb
  Formula/postgresql@12.rb
  Formula/postgresql@9.4.rb
  Formula/postgresql@9.5.rb
  Formula/postgresql@9.6.rb
  Formula/proteinortho.rb
  Formula/python@3.9.rb
  Formula/questdb.rb
  Formula/rain.rb
  Formula/rclone.rb
  Formula/scrcpy.rb
  Formula/tfsec.rb
  Formula/transmission-cli.rb
  Formula/wireshark.rb
Labels: merge

#21711 Merge 2020-12-06 50b4bd65764
  .github/workflows/tests.yml
  style_exceptions/non_keg_only_provided_by_macos_formulae.json
  style_exceptions/provided_by_macos_formulae.json
Labels: merge

#21712 Merge 2020-12-06 9b78f78d5fe
  Formula/ballerina.rb
  Formula/datasette.rb
  Formula/eslint.rb
  Formula/expect.rb
  Formula/gdbm.rb
  Formula/gettext.rb
  Formula/gmp.rb
  Formula/icu4c.rb
  Formula/jpeg.rb
  Formula/krb5.rb
  Formula/libtiff.rb
  Formula/libtool.rb
  Formula/node-sass.rb
  Formula/ocrmypdf.rb
  Formula/openssl@1.1.rb
  Formula/pcre.rb
  Formula/pcre2.rb
  Formula/pkg-config.rb
  Formula/readline.rb
  Formula/rustup-init.rb
  Formula/sqlite.rb
  Formula/todoman.rb
  Formula/ungit.rb
  Formula/webpack.rb
  Formula/xz.rb
  Formula/youtube-dl.rb
Labels: merge

#21714 Merge 2020-12-06 e75ec6c4f9a
  Formula/certbot.rb
  Formula/exploitdb.rb
  Formula/fcct.rb
  Formula/flyway.rb
  Formula/fzf.rb
  Formula/gitleaks.rb
  Formula/imapfilter.rb
  Formula/infracost.rb
  Formula/ktlint.rb
  Formula/liquibase.rb
  Formula/minio.rb
  Formula/mutt.rb
  Formula/opa.rb
  Formula/simdjson.rb
Labels: merge

#21716 Merge 2020-12-06 c8853947591
  Formula/abcm2ps.rb
  Formula/autoconf.rb
  Formula/autodiff.rb
  Formula/bacula-fd.rb
  Formula/emscripten.rb
  Formula/freetype.rb
  Formula/gnu-getopt.rb
  Formula/gopls.rb
  Formula/micronaut.rb
  Formula/oci-cli.rb
  Formula/sha2.rb
  Formula/suricata.rb
  Formula/ugrep.rb
Labels: merge

#21717 Merge 2020-12-06 5a6803c2f46
  Formula/gptfdisk.rb
  Formula/hledger.rb
  Formula/jack.rb
  Formula/ncompress.rb
  Formula/udptunnel.rb
Labels: merge

#21719 Merge 2020-12-06 70cc8e80471
  Formula/awscli.rb
  Formula/cdktf.rb
  Formula/cfn-lint.rb
  Formula/clojure-lsp.rb
  Formula/cppcheck.rb
  Formula/doctl.rb
  Formula/docui.rb
  Formula/fastlane.rb
  Formula/fplll.rb
  Formula/gping.rb
  Formula/hledger.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/inspectrum.rb
  Formula/k9s.rb
  Formula/netlify-cli.rb
  Formula/nexus.rb
  Formula/nvi.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/plantuml.rb
  Formula/pugixml.rb
  Formula/pulumi.rb
  Formula/pumba.rb
  Formula/pygments.rb
  Formula/regipy.rb
  Formula/sollya.rb
  Formula/topgrade.rb
  Formula/vim.rb
Labels: merge

#21721 Merge 2020-12-07 21307bf9078
  Formula/advancemame.rb
  Formula/apcupsd.rb
  Formula/apng2gif.rb
  Formula/arb.rb
  Formula/bbftp-client.rb
  Formula/cask.rb
  Formula/fd.rb
  Formula/fonttools.rb
  Formula/git.rb
  Formula/libcddb.rb
  Formula/liblcf.rb
  Formula/libproxy.rb
  Formula/luarocks.rb
  Formula/macos-trash.rb
  Formula/nghttp2.rb
  Formula/opencv.rb
  Formula/pdnsrec.rb
  Formula/serverless.rb
  Formula/slrn.rb
  Formula/vorbis-tools.rb
  Formula/xterm.rb
Labels: merge

#21723 Merge 2020-12-07 2f5bc28d418
  Formula/diff-pdf.rb
  Formula/gdal.rb
  Formula/geos.rb
  Formula/gnuradio.rb
  Formula/gr-osmosdr.rb
  Formula/gtk+3.rb
  Formula/ircd-hybrid.rb
  Formula/libslirp.rb
  Formula/mapnik.rb
  Formula/pdftoipe.rb
  Formula/poppler.rb
  Formula/sdhash.rb
  Formula/sqlite.rb
  Formula/uhd.rb
Labels: merge

#21724 Merge 2020-12-07 fc1ff9d6b06
  Formula/bind.rb
  Formula/povray.rb
  Formula/termius.rb
Labels: merge

#21725 Merge 2020-12-07 5c78f28fa6d
  Formula/a2ps.rb
  Formula/awscli@1.rb
  Formula/brogue.rb
  Formula/cdparanoia.rb
  Formula/clojure-lsp.rb
  Formula/earthly.rb
  Formula/hfsutils.rb
  Formula/httptunnel.rb
  Formula/jpeginfo.rb
  Formula/lha.rb
  Formula/md.rb
  Formula/mercurial.rb
  Formula/protobuf.rb
  Formula/radare2.rb
  Formula/w3m.rb
  Formula/youtube-dl.rb
Labels: merge

#21729 Merge 2020-12-07 3e46a50a039
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/tests.yml
Labels: merge

#21730 Merge 2020-12-07 ea941f76197
  Formula/hspell.rb
  Formula/nativefier.rb
  Formula/php-cs-fixer.rb
  Formula/uftp.rb
  Formula/write-good.rb
Labels: merge

#21731 Merge 2020-12-07 237f3350934
  Formula/autoconf.rb
  Formula/freetype.rb
  Formula/gdbm.rb
  Formula/gettext.rb
  Formula/gmp.rb
  Formula/gnu-getopt.rb
  Formula/icu4c.rb
  Formula/jpeg.rb
  Formula/krb5.rb
  Formula/libtiff.rb
  Formula/libtool.rb
  Formula/openssl@1.1.rb
  Formula/pcre.rb
  Formula/pcre2.rb
  Formula/pkg-config.rb
  Formula/readline.rb
  Formula/ugrep.rb
  Formula/xz.rb
Labels: merge

#21732 Merge 2020-12-07 b6e1a6c75c2
  .github/workflows/tests.yml
Labels: merge

#21733 Merge 2020-12-07 113b606956b
  Formula/freetype.rb
  Formula/gdbm.rb
  Formula/gettext.rb
  Formula/gmp.rb
  Formula/gnu-getopt.rb
  Formula/icu4c.rb
  Formula/jpeg.rb
  Formula/krb5.rb
  Formula/libffi.rb
  Formula/libtiff.rb
  Formula/libtool.rb
  Formula/little-cms.rb
  Formula/little-cms2.rb
  Formula/openssl@1.1.rb
  Formula/pcre.rb
  Formula/pcre2.rb
  Formula/pkg-config.rb
  Formula/readline.rb
  Formula/ugrep.rb
  Formula/vale.rb
  Formula/xz.rb
Labels: merge

#21736 Merge 2020-12-08 09deedb1ebc
  Formula/benthos.rb
  Formula/dhall-lsp-server.rb
  Formula/dhall-yaml.rb
  Formula/dhall.rb
  Formula/erlang.rb
  Formula/mlt.rb
  Formula/scdoc.rb
  Formula/t-rec.rb
  Formula/whatmask.rb
  Formula/zstd.rb
Labels: merge

#21737 Merge 2020-12-08 6ae37e2a444
  .github/workflows/tests.yml
Labels: merge

#21738 Merge 2020-12-08 6bc076d1125
  Formula/apache-flink.rb
  Formula/aws-cdk.rb
  Formula/clojure.rb
  Formula/cubejs-cli.rb
  Formula/dhall-json.rb
  Formula/fd.rb
  Formula/firebase-cli.rb
  Formula/gitmoji.rb
  Formula/gst-devtools.rb
  Formula/gst-editing-services.rb
  Formula/gst-libav.rb
  Formula/gst-plugins-bad.rb
  Formula/gst-plugins-base.rb
  Formula/gst-plugins-good.rb
  Formula/gst-plugins-ugly.rb
  Formula/gst-python.rb
  Formula/gst-rtsp-server.rb
  Formula/gstreamer.rb
  Formula/hpack.rb
  Formula/htop.rb
  Formula/instead.rb
  Formula/kubevela.rb
  Formula/meilisearch.rb
  Formula/monero.rb
  Formula/netlify-cli.rb
  Formula/osrm-backend.rb
  Formula/pulumi.rb
  Formula/python@3.9.rb
  Formula/ugrep.rb
Labels: merge

#21740 Merge 2020-12-08 4a9ce07e721
  Formula/azure-cli.rb
  Formula/clojure-lsp.rb
  Formula/dnscontrol.rb
  Formula/duf.rb
  Formula/envoy.rb
  Formula/exploitdb.rb
  Formula/flarectl.rb
  Formula/flux.rb
  Formula/gping.rb
  Formula/igraph.rb
  Formula/imagemagick.rb
  Formula/kubecm.rb
  Formula/lmod.rb
  Formula/nativefier.rb
  Formula/oil.rb
  Formula/pdm.rb
  Formula/php-cs-fixer.rb
  Formula/phpstan.rb
  Formula/pre-commit.rb
  Formula/python@3.9.rb
  Formula/rocksdb.rb
  Formula/rust-analyzer.rb
  Formula/termius.rb
  Formula/thanos.rb
  Formula/vtk.rb
Labels: merge

#21746 Merge 2020-12-09 3c6f01fa2db
  Formula/avro-c.rb
  Formula/avro-cpp.rb
  Formula/avro-tools.rb
  Formula/cargo-instruments.rb
  Formula/cpmtools.rb
  Formula/cpr.rb
  Formula/devspace.rb
  Formula/dupseek.rb
  Formula/istioctl.rb
  Formula/jasper.rb
  Formula/jruby.rb
  Formula/lightgbm.rb
  Formula/molecule.rb
  Formula/netpbm.rb
  Formula/nomad.rb
  Formula/oil.rb
  Formula/simple-scan.rb
  Formula/swiftformat.rb
  Formula/terraform.rb
  Formula/tmpwatch.rb
Labels: merge

#21747 Merge 2020-12-09 4188ece5fd7
  Formula/activemq.rb
  Formula/ask-cli.rb
  Formula/awscli.rb
  Formula/consul-backinator.rb
  Formula/cubejs-cli.rb
  Formula/docker-ls.rb
  Formula/feh.rb
  Formula/fn.rb
  Formula/gitleaks.rb
  Formula/kotlin.rb
  Formula/kubevela.rb
  Formula/leiningen.rb
  Formula/mysql@5.6.rb
  Formula/mysql@5.7.rb
  Formula/newrelic-cli.rb
  Formula/oci-cli.rb
  Formula/odpi.rb
  Formula/osm2pgsql.rb
  Formula/pegtl.rb
  Formula/perltidy.rb
  Formula/picard-tools.rb
  Formula/seal.rb
  Formula/sipsak.rb
  Formula/ssldump.rb
  Formula/tomcat.rb
  Formula/tomcat@8.rb
  Formula/vis.rb
  Formula/xgboost.rb
  Formula/youtube-dl.rb
  Formula/zlib.rb
Labels: merge

#21750 Merge 2020-12-09 ea55204f71b
  Formula/autoconf.rb
  Formula/automake.rb
  Formula/freetds.rb
  Formula/freetype.rb
  Formula/gdbm.rb
  Formula/gettext.rb
  Formula/git.rb
  Formula/gmp.rb
  Formula/gping.rb
  Formula/icu4c.rb
  Formula/isl.rb
  Formula/jpeg.rb
  Formula/krb5.rb
  Formula/libevent.rb
  Formula/libffi.rb
  Formula/libpng.rb
  Formula/libtiff.rb
  Formula/libtool.rb
  Formula/meson.rb
  Formula/mpfr.rb
  Formula/ninja.rb
  Formula/openssl@1.1.rb
  Formula/p11-kit.rb
  Formula/pcre.rb
  Formula/pcre2.rb
  Formula/pkg-config.rb
  Formula/python@3.9.rb
  Formula/readline.rb
  Formula/s3ql.rb
  Formula/sdl.rb
  Formula/sphinx-doc.rb
  Formula/sqlite.rb
  Formula/xz.rb
Labels: merge

#21751 Merge 2020-12-09 d9b2a746c7d
  Formula/bash.rb
  Formula/bison.rb
  Formula/boost.rb
  Formula/c-ares.rb
  Formula/cairo.rb
  Formula/cmake.rb
  Formula/cscope.rb
  Formula/fontconfig.rb
  Formula/glib.rb
  Formula/jsonlint.rb
  Formula/libomp.rb
  Formula/libsodium.rb
  Formula/libyaml.rb
  Formula/little-cms2.rb
  Formula/lua.rb
  Formula/lzo.rb
  Formula/mysql.rb
  Formula/ncurses.rb
  Formula/node.rb
  Formula/perl.rb
  Formula/pixman.rb
  Formula/protobuf.rb
  Formula/ruby.rb
  Formula/tcl-tk.rb
  Formula/vim.rb
  Formula/zsh.rb
Labels: merge

#21752 Merge 2020-12-09 4f5a1e9aa59
  Formula/ruby.rb
  Formula/ruby@2.4.rb
  Formula/ruby@2.5.rb
  Formula/ruby@2.6.rb
Labels: merge

#21758 Merge 2020-12-10 cde328090d6
  Formula/angular-cli.rb
  Formula/argocd.rb
  Formula/babel.rb
  Formula/bind.rb
  Formula/clib.rb
  Formula/closure-compiler.rb
  Formula/datasette.rb
  Formula/devil.rb
  Formula/firebase-cli.rb
  Formula/fonttools.rb
  Formula/gitleaks.rb
  Formula/gitmoji.rb
  Formula/helib.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/liquibase.rb
  Formula/metricbeat.rb
  Formula/minizip2.rb
  Formula/netlify-cli.rb
  Formula/newrelic-cli.rb
  Formula/nicotine-plus.rb
  Formula/ruby-build.rb
  Formula/swiftformat.rb
  Formula/terraform-ls.rb
  Formula/tfsec.rb
  Formula/winetricks.rb
Labels: merge

#21760 Merge 2020-12-10 7bca8d802b2
  Formula/argocd.rb
  Formula/awscli.rb
  Formula/cddlib.rb
  Formula/draco.rb
  Formula/fn.rb
  Formula/gau.rb
  Formula/libressl.rb
  Formula/minizinc.rb
  Formula/ocp.rb
  Formula/octant.rb
  Formula/openssl@1.1.rb
  Formula/or-tools.rb
  Formula/readline.rb
  Formula/root.rb
  Formula/tflint.rb
  Formula/zpaq.rb
Labels: merge

#21762 Merge 2020-12-10 661095d3010
  Formula/ceres-solver.rb
  Formula/dopewars.rb
  Formula/eigen.rb
  Formula/functionalplus.rb
  Formula/grafana.rb
  Formula/graph-tool.rb
  Formula/hdf5.rb
  Formula/itk.rb
  Formula/lua@5.3.rb
  Formula/mapserver.rb
  Formula/ncftp.rb
  Formula/node-build.rb
  Formula/puzzles.rb
  Formula/ucl.rb
  Formula/vulkan-headers.rb
  Formula/wireshark.rb
Labels: merge

#21765 Merge 2020-12-10 2a87e8ff599
  Formula/arduino-cli.rb
  Formula/cbmc.rb
  Formula/commitizen.rb
  Formula/inframap.rb
  Formula/packetbeat.rb
  Formula/portmidi.rb
  Formula/psftools.rb
  Formula/rsyslog.rb
  Formula/terracognita.rb
Labels: merge

#21766 Merge 2020-12-10 5dd513ac239
  .github/workflows/tests-linux.yml
Labels: merge

#21768 Merge 2020-12-11 f68fe96c6d5
  Formula/bash.rb
  Formula/kustomize.rb
  Formula/luarocks.rb
  Formula/netlify-cli.rb
  Formula/puzzles.rb
  Formula/readline.rb
  Formula/traefik.rb
  Formula/vc.rb
Labels: merge

#21771 Merge 2020-12-11 2a3d13b2cf8
  .github/workflows/tests-linux.yml
  Formula/attr.rb
Labels: merge

#21772 Merge 2020-12-11 baf6aab591e
  Formula/exploitdb.rb
  Formula/kustomize.rb
  Formula/libusb.rb
  Formula/linkerd.rb
  Formula/pike.rb
  Formula/vale.rb
Labels: merge

#21774 Merge 2020-12-11 023f6a12e1a
  Formula/gettext.rb
Labels: merge

#21775 Merge 2020-12-11 cec734cf29f
  Formula/abcmidi.rb
  Formula/arpack.rb
  Formula/awscli.rb
  Formula/calicoctl.rb
  Formula/cdrtools.rb
  Formula/chakra.rb
  Formula/chronograf.rb
  Formula/cminpack.rb
  Formula/consul.rb
  Formula/contentful-cli.rb
  Formula/datasette.rb
  Formula/dehydrated.rb
  Formula/direnv.rb
  Formula/docfx.rb
  Formula/ejdb.rb
  Formula/hardlink.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/lighttpd.rb
  Formula/lxc.rb
  Formula/marked.rb
  Formula/mg.rb
  Formula/mosquitto.rb
  Formula/orc-tools.rb
  Formula/root.rb
  Formula/semtag.rb
  Formula/swiftformat.rb
  Formula/teleport.rb
  Formula/vgrep.rb
  Formula/xrootd.rb
  Formula/zile.rb
Labels: merge

#21776 Merge 2020-12-11 e8ce5afc9e7
  Formula/armadillo.rb
  Formula/couchdb-lucene.rb
  Formula/dtrx.rb
  Formula/ensmallen.rb
  Formula/ethereum.rb
  Formula/exploitdb.rb
  Formula/fwup.rb
  Formula/gcore.rb
  Formula/gdal.rb
  Formula/getmail.rb
  Formula/kubecm.rb
  Formula/libgcrypt.rb
  Formula/libhttpserver.rb
  Formula/mame.rb
  Formula/mlpack.rb
  Formula/okteto.rb
  Formula/poppler.rb
  Formula/superlu.rb
  Formula/winetricks.rb
Labels: merge

#21778 Merge 2020-12-11 64d9ef29600
  Formula/python@3.9.rb
Labels: merge

#21781 Merge 2020-12-12 d0ff6289191
  Formula/abcde.rb
  Formula/azcopy.rb
  Formula/coq.rb
  Formula/dnsperf.rb
  Formula/libtorch.rb
  Formula/math-comp.rb
  Formula/monitoring-plugins.rb
  Formula/pike.rb
  Formula/pulumi.rb
  Formula/recode.rb
  Formula/rgbds.rb
  Formula/semgrep.rb
  Formula/sourcekitten.rb
  Formula/talisman.rb
  Formula/torchvision.rb
Labels: merge

#21782 Merge 2020-12-12 2222829b840
  .github/workflows/triage-issues.yml
Labels: merge

#21784 Merge 2020-12-12 520ebf41632
  Formula/bareos-client.rb
  Formula/dopewars.rb
  Formula/exploitdb.rb
  Formula/gauche.rb
  Formula/imlib2.rb
  Formula/lanraragi.rb
  Formula/m4.rb
  Formula/manticoresearch.rb
  Formula/naabu.rb
  Formula/onednn.rb
  Formula/ruby-install.rb
  Formula/spdlog.rb
Labels: merge

#21793 Merge 2020-12-12 dfc96f43ad6
  Formula/astyle.rb
  Formula/cups.rb
  Formula/dhall-bash.rb
  Formula/glade.rb
  Formula/gtksourceview4.rb
  Formula/innotop.rb
  Formula/nfpm.rb
  Formula/ocrmypdf.rb
  Formula/pipgrip.rb
  Formula/ucon64.rb
  Formula/wren.rb
  Formula/xplanet.rb
Labels: merge

#21796 Merge 2020-12-13 b16073c7639
  Formula/docker-slim.rb
  Formula/librdkafka.rb
  Formula/pulumi.rb
  Formula/v8.rb
  Formula/yash.rb
Labels: merge

#21797 Merge 2020-12-13 2699484345f
  Formula/ansible.rb
  Formula/cig.rb
  Formula/enchant.rb
  Formula/gnu-cobol.rb
  Formula/godep.rb
  Formula/gosu.rb
  Formula/lc0.rb
  Formula/libid3tag.rb
  Formula/monero.rb
  Formula/phpstan.rb
  Formula/the_platinum_searcher.rb
  Formula/theharvester.rb
  Formula/vitetris.rb
Labels: merge

#21802 Merge 2020-12-13 bb86a112c53
  Formula/abseil.rb
  Formula/bmon.rb
  Formula/collectd.rb
  Formula/conan.rb
  Formula/kde-extra-cmake-modules.rb
  Formula/kde-karchive.rb
  Formula/kde-kdoctools.rb
  Formula/kde-ki18n.rb
  Formula/kde-threadweaver.rb
  Formula/net-snmp.rb
  Formula/pangomm.rb
  Formula/phpstan.rb
  Formula/sane-backends.rb
Labels: merge

#21803 Merge 2020-12-13 58e1ebfade2
  Formula/atkmm.rb
  Formula/dvc.rb
  Formula/gtkmm.rb
  Formula/gtkmm3.rb
  Formula/gtksourceviewmm.rb
  Formula/gtksourceviewmm3.rb
  Formula/libglademm.rb
  Formula/libgnomecanvasmm.rb
  Formula/lsd.rb
  Formula/ocaml-num.rb
Labels: merge

#21814 Merge 2020-12-14 81704768574
  Formula/apache-drill.rb
  Formula/aws-console.rb
  Formula/cargo-instruments.rb
  Formula/cubejs-cli.rb
  Formula/gtkmm3.rb
  Formula/icon.rb
  Formula/include-what-you-use.rb
  Formula/kibana.rb
  Formula/libwebsockets.rb
  Formula/lmod.rb
  Formula/logstash.rb
  Formula/man-db.rb
  Formula/mmctl.rb
  Formula/mosquitto.rb
  Formula/netlify-cli.rb
  Formula/oakc.rb
  Formula/ortp.rb
  Formula/phoronix-test-suite.rb
  Formula/pnpm.rb
  Formula/sqlite-utils.rb
  Formula/ttyd.rb
  Formula/vcprompt.rb
  Formula/vips.rb
  Formula/youtube-dl.rb
  style_exceptions/not_a_binary_url_prefix_allowlist.json
Labels: merge

#21822 Merge 2020-12-14 85771bcb196
  Formula/berkeley-db@4.rb
  Formula/mariadb.rb
  Formula/mariadb@10.1.rb
  Formula/mariadb@10.2.rb
  Formula/mariadb@10.3.rb
  Formula/mariadb@10.4.rb
  Formula/mysql.rb
  Formula/mysql@5.6.rb
  Formula/mysql@5.7.rb
  Formula/percona-server.rb
Labels: merge

#21824 Merge 2020-12-14 2b067a107a5
  Formula/cling.rb
  Formula/cryptominisat.rb
  Formula/dwdiff.rb
  Formula/fftw.rb
  Formula/gnu-prolog.rb
  Formula/howdoi.rb
  Formula/inja.rb
  Formula/inxi.rb
  Formula/janet.rb
  Formula/jd.rb
  Formula/juju.rb
  Formula/libphonenumber.rb
  Formula/minizip2.rb
  Formula/mitmproxy.rb
  Formula/mongoose.rb
  Formula/ncspot.rb
  Formula/nzbget.rb
  Formula/onnxruntime.rb
  Formula/ospray.rb
  Formula/pgcli.rb
  Formula/plantuml.rb
  Formula/s2geometry.rb
  Formula/uwsgi.rb
  Formula/vgmstream.rb
  Formula/zig.rb
Labels: merge

#21827 Merge 2020-12-14 e422a6f3682
  Formula/arangodb.rb
  Formula/avra.rb
  Formula/cdrtools.rb
  Formula/cf.rb
  Formula/chakra.rb
  Formula/delta.rb
  Formula/dps8m.rb
  Formula/erlang.rb
  Formula/erlang@20.rb
  Formula/erlang@21.rb
  Formula/erlang@22.rb
  Formula/fobis.rb
  Formula/fs-uae.rb
  Formula/go-jsonnet.rb
  Formula/hyperspec.rb
  Formula/libpqxx.rb
  Formula/libpqxx@6.rb
  Formula/lua.rb
  Formula/lua@5.3.rb
  Formula/luajit.rb
  Formula/mecab-ko.rb
  Formula/mlton.rb
  Formula/mpgtx.rb
  Formula/nagios.rb
  Formula/nest.rb
  Formula/npush.rb
  Formula/openal-soft.rb
  Formula/php.rb
  Formula/php@7.2.rb
  Formula/php@7.3.rb
  Formula/php@7.4.rb
  Formula/rsync.rb
  Formula/squashfuse.rb
  Formula/sshfs.rb
  Formula/tass64.rb
  Formula/thefuck.rb
  Formula/topgrade.rb
  Formula/tree-sitter.rb
  Formula/uggconv.rb
  Formula/zorba.rb
Labels: merge

#21828 Merge 2020-12-14 d6d5823b4c1
  Formula/deno.rb
  Formula/kim-api.rb
  Formula/localstack.rb
  Formula/luajit.rb
  Formula/pdm.rb
  Formula/tree-sitter.rb
Labels: merge

#21829 Merge 2020-12-14 db437260e2b
  Formula/python@3.9.rb
Labels: merge

#21837 at-spi2-core: fix bottling for linux
  Formula/at-spi2-core.rb
Labels: cellar failure

#21840 Merge 2020-12-15 cb8bb9842cd
  Formula/gnuplot.rb
  Formula/sbt.rb
  Formula/twarc.rb
Labels: merge

#21841 Merge 2020-12-15 dc0df95771d
  Formula/aften.rb
  Formula/ampl-mp.rb
  Formula/boost-build.rb
  Formula/fizz.rb
  Formula/folly.rb
  Formula/googletest.rb
  Formula/httpd.rb
  Formula/ktmpl.rb
  Formula/kubernetes-cli.rb
  Formula/mapnik.rb
  Formula/odin.rb
  Formula/s-nail.rb
  Formula/wangle.rb
Labels: merge

#21842 Merge 2020-12-15 f8f64c29e06
  Formula/arangodb.rb
  Formula/knot-resolver.rb
  Formula/libgr.rb
  Formula/minizinc.rb
Labels: merge

#21843 Merge 2020-12-15 feb52fabc2e
  .github/workflows/tests-linux.yml
Labels: merge

#21844 Merge 2020-12-15 f72376bc043
  Formula/carton.rb
  Formula/cpm.rb
  Formula/dbdeployer.rb
  Formula/duckscript.rb
  Formula/heppdt2.rb
  Formula/pdnsrec.rb
  Formula/rancher-cli.rb
  Formula/redsocks.rb
  Formula/silicon.rb
  Formula/simdjson.rb
  Formula/vale.rb
  Formula/vulkan-headers.rb
  Formula/xcinfo.rb
Labels: merge

#21846 Merge 2020-12-15 4fa512e6131
  Formula/latexindent.rb
  Formula/nicotine-plus.rb
  Formula/vips.rb
Labels: merge

#21847 Merge 2020-12-15 0aae21fd18f
  .github/workflows/tests-linux.yml
Labels: merge

#21851 Merge 2020-12-16 d0002786c6c
  .github/workflows/tests-linux.yml
  Formula/wayland.rb
Labels: merge

#21856 Merge 2020-12-17 0ba00196b8b
  Formula/awscli.rb
  Formula/bfg.rb
  Formula/conan.rb
  Formula/csound.rb
  Formula/dislocker.rb
  Formula/dmalloc.rb
  Formula/dvc.rb
  Formula/faas-cli.rb
  Formula/fizz.rb
  Formula/folly.rb
  Formula/gauche.rb
  Formula/geoipupdate.rb
  Formula/gh.rb
  Formula/hashlink.rb
  Formula/haxe.rb
  Formula/infracost.rb
  Formula/jenkins.rb
  Formula/jetty-runner.rb
  Formula/jetty.rb
  Formula/mbedtls.rb
  Formula/mysql.rb
  Formula/mysql@5.6.rb
  Formula/mysql@5.7.rb
  Formula/neko.rb
  Formula/oci-cli.rb
  Formula/ortp.rb
  Formula/phpstan.rb
  Formula/plplot.rb
  Formula/remctl.rb
  Formula/scummvm.rb
  Formula/shadowsocks-libev.rb
  Formula/vcprompt.rb
  Formula/wangle.rb
  Formula/webpack.rb
Labels: merge

#21858 Merge 2020-12-17 1e3ad2498b8
  Formula/a52dec.rb
  Formula/alsa-lib.rb
  Formula/bind.rb
  Formula/commitizen.rb
  Formula/firebase-cli.rb
  Formula/fonttools.rb
  Formula/glib.rb
  Formula/infracost.rb
  Formula/jfrog-cli.rb
  Formula/knot-resolver.rb
  Formula/libaio.rb
  Formula/libcouchbase.rb
  Formula/libvnc.rb
  Formula/libxml++.rb
  Formula/netlify-cli.rb
  Formula/nomad.rb
  Formula/ompl.rb
  Formula/open-sp.rb
  Formula/openblas.rb
  Formula/openfst.rb
  Formula/pdm.rb
  Formula/semgrep.rb
  Formula/snakemake.rb
  Formula/solidity.rb
  Formula/teleport.rb
  Formula/xcbeautify.rb
Labels: merge

#21861 Merge 2020-12-17 72f2ab4cf6a
  Formula/cloog.rb
  Formula/dafny.rb
  Formula/dhall.rb
  Formula/discount.rb
  Formula/erlang.rb
  Formula/logstash.rb
  Formula/octave.rb
  Formula/osm.rb
  Formula/packer.rb
  Formula/rocksdb.rb
  Formula/staticcheck.rb
  Formula/sundials.rb
  Formula/tektoncd-cli.rb
  Formula/topgrade.rb
  Formula/utf8proc.rb
  Formula/zeromq.rb
  style_exceptions/not_a_binary_url_prefix_allowlist.json
Labels: merge

#21863 Merge 2020-12-18 702b00164b2
  Formula/agda.rb
  Formula/aws-cdk.rb
  Formula/bazel.rb
  Formula/carton.rb
  Formula/clojure.rb
  Formula/deno.rb
  Formula/ejdb.rb
  Formula/libheif.rb
  Formula/minikube.rb
  Formula/peru.rb
  Formula/php-cs-fixer.rb
  Formula/util-linux.rb
  Formula/webpack.rb
  Formula/xcinfo.rb
  Formula/zstd.rb
Labels: merge

#21864 Merge 2020-12-18 dd510eef3f5
  .github/workflows/tests-linux.yml
  Formula/wayland-protocols.rb
Labels: merge

#21865 Merge 2020-12-18 feaf8fbc9de
  Formula/acpica.rb
  Formula/angular-cli.rb
  Formula/autorest.rb
  Formula/aws-okta.rb
  Formula/awscli.rb
  Formula/c7n.rb
  Formula/cadence.rb
  Formula/cfn-lint.rb
  Formula/circleci.rb
  Formula/cjdns.rb
  Formula/dbdeployer.rb
  Formula/devspace.rb
  Formula/dlite.rb
  Formula/docker-machine-driver-xhyve.rb
  Formula/doctest.rb
  Formula/exploitdb.rb
  Formula/fluent-bit.rb
  Formula/flux.rb
  Formula/flyway.rb
  Formula/fork-cleaner.rb
  Formula/gatsby-cli.rb
  Formula/gopls.rb
  Formula/grafana.rb
  Formula/hasura-cli.rb
  Formula/imagemagick@6.rb
  Formula/imgur-screenshot.rb
  Formula/knot.rb
  Formula/libphonenumber.rb
  Formula/maxwell.rb
  Formula/netdata.rb
  Formula/pumba.rb
Labels: merge

#21866 Merge 2020-12-18 047d91d1ee1
  Formula/allure.rb
  Formula/g3log.rb
  Formula/glib.rb
  Formula/imagemagick.rb
  Formula/jfrog-cli.rb
  Formula/kyma-cli.rb
  Formula/libpqxx.rb
  Formula/mitmproxy.rb
  Formula/mosquitto.rb
  Formula/newrelic-cli.rb
  Formula/node@14.rb
  Formula/nss.rb
  Formula/nushell.rb
  Formula/onefetch.rb
  Formula/pachi.rb
  Formula/pegtl.rb
  Formula/prestodb.rb
  Formula/qmmp.rb
  Formula/qtkeychain.rb
  Formula/rust-analyzer.rb
  Formula/samurai.rb
  Formula/sbt.rb
  Formula/sdns.rb
  Formula/signal-cli.rb
  Formula/taskwarrior-tui.rb
  Formula/teleport.rb
  Formula/theharvester.rb
  Formula/tm.rb
  Formula/vim.rb
Labels: merge

#21867 Merge 2020-12-18 f333112f40f
  Formula/cmake.rb
  Formula/diamond.rb
  Formula/futhark.rb
  Formula/github-markdown-toc.rb
  Formula/gtk+4.rb
  Formula/infracost.rb
  Formula/menhir.rb
  Formula/mesa.rb
  Formula/pandoc.rb
  Formula/pueue.rb
  Formula/qjackctl.rb
  Formula/shibboleth-sp.rb
  Formula/skylighting.rb
  Formula/t-rec.rb
  Formula/vault.rb
  Formula/volk.rb
  Formula/zeek.rb
Labels: merge

#21868 Merge 2020-12-18 e9ac387c3c0
  Formula/pandoc.rb
  Formula/python@3.9.rb
Labels: merge

#21869 Merge 2020-12-18 81da364a6f5
  Formula/ccache.rb
  Formula/diff-pdf.rb
  Formula/ejabberd.rb
  Formula/khiva.rb
  Formula/kube-linter.rb
  Formula/muffet.rb
  Formula/node-build.rb
  Formula/pike.rb
  Formula/poppler.rb
Labels: merge

#21876 Merge 2020-12-19 f089a94551a
  Formula/convox.rb
  Formula/cython.rb
  Formula/exploitdb.rb
  Formula/freetds.rb
  Formula/frugal.rb
  Formula/git-quick-stats.rb
  Formula/glpk.rb
  Formula/libvnc.rb
  Formula/metabase.rb
  Formula/ncspot.rb
  Formula/pugixml.rb
  Formula/rtags.rb
  Formula/serverless.rb
  Formula/terraform.rb
  Formula/texmath.rb
  Formula/traefik.rb
  Formula/webdis.rb
  Formula/wildfly-as.rb
Labels: merge

#21878 Merge 2020-12-19 f443e68e2eb
  Aliases/boost-python@1.72
  Aliases/boost@1.75
  Formula/apollo-cli.rb
  Formula/avro-cpp.rb
  Formula/aws-sdk-cpp.rb
  Formula/awscli@1.rb
  Formula/boost-python.rb
  Formula/boost-python3.rb
  Formula/boost.rb
  Formula/cfn-lint.rb
  Formula/code-server.rb
  Formula/cubejs-cli.rb
  Formula/cucumber-cpp.rb
  Formula/detekt.rb
  Formula/docbook.rb
  Formula/earthly.rb
  Formula/freeling.rb
  Formula/geos.rb
  Formula/gr-osmosdr.rb
  Formula/imagemagick.rb
  Formula/kubernetes-cli.rb
  Formula/ledger.rb
  Formula/lgogdownloader.rb
  Formula/libbitcoin-client.rb
  Formula/libbitcoin-explorer.rb
  Formula/libbitcoin-protocol.rb
  Formula/libbitcoin-server.rb
  Formula/libbitcoin.rb
  Formula/libpulsar.rb
  Formula/libxslt.rb
  Formula/lighttpd.rb
  Formula/mat2.rb
  Formula/monero.rb
  Formula/mysql-client@5.7.rb
  Formula/ncmpcpp.rb
  Formula/opensaml.rb
  Formula/operator-sdk.rb
  Formula/pcl.rb
  Formula/pdns.rb
  Formula/qcli.rb
  Formula/shibboleth-sp.rb
  Formula/simgrid.rb
  Formula/source-highlight.rb
  Formula/ugrep.rb
  Formula/vips.rb
  Formula/widelands.rb
  Formula/wownero.rb
  Formula/xml-tooling-c.rb
Labels: merge

#21879 Merge 2020-12-19 9c1c6644c83
  Formula/dita-ot.rb
  Formula/emscripten.rb
  Formula/eslint.rb
  Formula/exploitdb.rb
  Formula/gitmoji.rb
  Formula/go.rb
  Formula/grails.rb
  Formula/heimdal.rb
  Formula/imagemagick@6.rb
  Formula/iozone.rb
  Formula/ispc.rb
  Formula/newrelic-cli.rb
  Formula/pandoc.rb
  Formula/postgis.rb
  Formula/python@3.9.rb
  Formula/rswift.rb
  Formula/sratoolkit.rb
  Formula/zsh-async.rb
Labels: merge

#21885 Merge 2020-12-20 056c7e0ded8
  Formula/allureofthestars.rb
  Formula/bash.rb
  Formula/boost-bcp.rb
  Formula/broot.rb
  Formula/connect.rb
  Formula/crf++.rb
  Formula/flash.rb
  Formula/foremost.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jrnl.rb
  Formula/keychain.rb
  Formula/libilbc.rb
  Formula/libjson-rpc-cpp.rb
  Formula/libmaa.rb
  Formula/testdisk.rb
  Formula/xcbeautify.rb
  Formula/xdotool.rb
  Formula/zstd.rb
Labels: merge

#21886 Merge 2020-12-20 e9f1f0fc758
  Formula/xcb-util-keysyms.rb
Labels: merge

#21888 Merge 2020-12-20 d39fba7becb
  Formula/argo.rb
  Formula/boost-mpi.rb
  Formula/czmq.rb
  Formula/flow-cli.rb
  Formula/glibmm@2.64.rb
  Formula/gtkmm4.rb
  Formula/ike-scan.rb
  Formula/inxi.rb
  Formula/mpack.rb
  Formula/testdisk.rb
  Formula/wireshark.rb
  Formula/yq.rb
Labels: merge

#21889 Merge 2020-12-20 61ea587ca41
  .github/workflows/tests-linux.yml
  Formula/libcap-ng.rb
Labels: merge

#21890 Merge 2020-12-20 7dd9ccdfb6f
  Formula/chezmoi.rb
  Formula/devspace.rb
  Formula/lf.rb
  Formula/muffet.rb
  Formula/netdata.rb
Labels: merge

#21891 Merge 2020-12-20 2bed8fbe9ae
  .github/workflows/tests-linux.yml
  Formula/libnsl.rb
Labels: merge

#21893 Merge 2020-12-21 90773dc0bca
  Formula/babl.rb
  Formula/cedille.rb
  Formula/commandbox.rb
  Formula/gitversion.rb
  Formula/hwloc.rb
  Formula/kafka.rb
  Formula/libtiff.rb
  Formula/n.rb
  Formula/netlify-cli.rb
  Formula/nickle.rb
  Formula/orc-tools.rb
  Formula/pandoc-crossref.rb
  Formula/pnpm.rb
  Formula/spack.rb
  Formula/sphinx-doc.rb
  Formula/telegraf.rb
  Formula/volta.rb
  Formula/wownero.rb
  Formula/youtube-dlc.rb
  Formula/zsh-completions.rb
Labels: merge

#21894 Merge 2020-12-21 bd5f9f61c46
  Formula/attr.rb
  Formula/cairo.rb
  Formula/ruby-build.rb
  Formula/xcb-util-image.rb
  Formula/xcb-util-keysyms.rb
  Formula/xcb-util-renderutil.rb
  Formula/xcb-util-wm.rb
Labels: merge

#21896 Merge 2020-12-21 56e809e3cb5
  Formula/gdbgui.rb
  Formula/gegl.rb
  Formula/hardlink-osx.rb
  Formula/idris.rb
  Formula/nginx.rb
  Formula/passenger.rb
  Formula/tundra.rb
Labels: merge

#21900 Merge 2020-12-22 ce17c4f3e54
  Formula/xcb-util-cursor.rb
Labels: merge

#21903 Merge 2020-12-22 2fbd8766de2
  Aliases/gfortran
  Formula/ask-cli.rb
  Formula/bpytop.rb
  Formula/cubejs-cli.rb
  Formula/dolt.rb
  Formula/firebase-cli.rb
  Formula/ghz.rb
  Formula/iam-policy-json-to-terraform.rb
  Formula/logtalk.rb
  Formula/ncmpcpp.rb
  Formula/snakemake.rb
  Formula/unibilium.rb
  Formula/youtube-dl.rb
  Formula/zile.rb
Labels: merge

#21904 Merge 2020-12-22 2fba5bd1f4e
  Formula/ncmpcpp.rb
  Formula/pugixml.rb
  Formula/sccache.rb
Labels: merge

#21905 Merge 2020-12-22 4b9a701bbb4
  Formula/jnettop.rb
  Formula/keepassc.rb
  Formula/mariadb-connector-odbc.rb
  Formula/mogenerator.rb
  Formula/pdm.rb
  Formula/whistle.rb
  audit_exceptions/github_prerelease_allowlist.json
  audit_exceptions/gitlab_prerelease_allowlist.json
Labels: merge

#21909 Merge 2020-12-22 92f5e828d7e
  Formula/libffi.rb
  Formula/nghttp2.rb
Labels: merge

#21910 Merge 2020-12-22 74f4ad5605a
  .github/workflows/tests-linux.yml
  Formula/valgrind.rb
Labels: merge

#21914 Merge 2020-12-23 f0f8f32d719
  Formula/autossh.rb
  Formula/awscli@1.rb
  Formula/hunspell.rb
  Formula/iftop.rb
  Formula/libstfl.rb
  Formula/libxkbcommon.rb
  Formula/mesa.rb
  Formula/mupdf-tools.rb
  Formula/openfortivpn.rb
  Formula/shadowsocks-libev.rb
  Formula/wdiff.rb
  Formula/xmlstarlet.rb
Labels: merge

#21915 Merge 2020-12-23 772a955f508
  Formula/gnu-units.rb
  Formula/gnu-which.rb
  Formula/rustup-init.rb
Labels: merge

#21916 Merge 2020-12-23 aad0088138f
  Formula/amazon-ecs-cli.rb
  Formula/cargo-c.rb
  Formula/ccls.rb
  Formula/cgal.rb
  Formula/checkov.rb
  Formula/ejdb.rb
  Formula/htop.rb
Labels: merge

#21917 Merge 2020-12-23 a44c1aaf29d
  Formula/devspace.rb
  Formula/gnu-indent.rb
  Formula/gnu-sed.rb
  Formula/gnu-time.rb
  Formula/ideviceinstaller.rb
  Formula/libcaca.rb
  Formula/libserdes.rb
  Formula/libusrsctp.rb
  Formula/lmdb.rb
  Formula/mhash.rb
  Formula/streamlink.rb
  Formula/testdisk.rb
  Formula/tldr.rb
  Formula/typescript.rb
  Formula/ykpers.rb
Labels: merge

#21920 Merge 2020-12-23 e9f6874ce33
  Formula/curl.rb
Labels: merge

#21921 Merge 2020-12-23 ce858e66b1f
  Formula/atlantis.rb
  Formula/awscli.rb
  Formula/bdw-gc.rb
  Formula/docbook-xsl.rb
  Formula/earthly.rb
  Formula/enchant.rb
  Formula/flow-cli.rb
  Formula/ghz-web.rb
  Formula/govc.rb
  Formula/gperftools.rb
  Formula/grails.rb
  Formula/highlight.rb
  Formula/kumactl.rb
  Formula/libfido2.rb
  Formula/liblwgeom.rb
  Formula/node.rb
  Formula/ocrmypdf.rb
  Formula/pdftk-java.rb
  Formula/plantuml.rb
  Formula/pugixml.rb
  Formula/pulumi.rb
  Formula/rust-analyzer.rb
  Formula/serverless.rb
  Formula/singular.rb
  Formula/sng.rb
  Formula/tasksh.rb
  Formula/terracognita.rb
  Formula/tomcat-native.rb
  Formula/topgrade.rb
  Formula/tty-share.rb
  Formula/ugrep.rb
  Formula/vale.rb
  Formula/vlang.rb
  Formula/xgboost.rb
  Formula/xmrig.rb
  Formula/yq.rb
  Formula/zabbix.rb
Labels: merge

#21923 Merge 2020-12-23 599086d8b7a
  .github/workflows/tests-linux.yml
  Formula/libva.rb
Labels: merge

#21927 Merge 2020-12-23 3ba58b64bb6
  Formula/asio.rb
  Formula/atk.rb
  Formula/audiofile.rb
  Formula/bdw-gc.rb
  Formula/c-blosc.rb
  Formula/cdb.rb
  Formula/curl.rb
  Formula/davix.rb
  Formula/duktape.rb
  Formula/emacs.rb
  Formula/fcgi.rb
  Formula/font-util.rb
  Formula/gecode.rb
  Formula/geographiclib.rb
  Formula/git-delta.rb
  Formula/glibmm.rb
  Formula/glktermw.rb
  Formula/gnupg.rb
  Formula/gnutls.rb
  Formula/gobject-introspection.rb
  Formula/guile.rb
  Formula/guile@2.rb
  Formula/hiredis.rb
  Formula/htmlcxx.rb
  Formula/i2util.rb
  Formula/jlog.rb
  Formula/libbinio.rb
  Formula/libdiscid.rb
  Formula/libdv.rb
  Formula/libgnt.rb
  Formula/libltc.rb
  Formula/libmaa.rb
  Formula/libmicrohttpd.rb
  Formula/libnxml.rb
  Formula/libre.rb
  Formula/librtlsdr.rb
  Formula/libxaw.rb
  Formula/mariadb-connector-c.rb
  Formula/mesa-glu.rb
  Formula/moarvm.rb
  Formula/mp4v2.rb
  Formula/nmh.rb
  Formula/openmotif.rb
  Formula/osx-cpu-temp.rb
  Formula/p0f.rb
  Formula/pugixml.rb
  Formula/ragel.rb
  Formula/rasqal.rb
  Formula/smake.rb
  Formula/tarsnap.rb
  Formula/tlx.rb
  Formula/tor.rb
  Formula/two-lame.rb
  Formula/udunits.rb
  Formula/vsftpd.rb
  Formula/w3m.rb
  Formula/xmlrpc-c.rb
  Formula/xorgrgb.rb
Labels: merge

#21932 Merge 2020-12-23 b6562f13f2e
  Formula/atkmm.rb
  Formula/bbftp-client.rb
  Formula/bitcoin.rb
  Formula/cabocha.rb
  Formula/cairomm.rb
  Formula/dpkg.rb
  Formula/gdk-pixbuf.rb
  Formula/graphene.rb
  Formula/gsettings-desktop-schemas.rb
  Formula/gtk+.rb
  Formula/gtk+3.rb
  Formula/gtk+4.rb
  Formula/harfbuzz.rb
  Formula/libass.rb
  Formula/pango.rb
  Formula/pcre++.rb
  Formula/pygobject3.rb
  Formula/sassc.rb
Labels: merge

#21933 Merge 2020-12-23 4c0f45bd918
  Formula/gcc.rb
Labels: merge

#21934 Merge 2020-12-23 d42f06a4519
  Formula/arpack.rb
  Formula/cmake.rb
  Formula/counterfeiter.rb
  Formula/crystal-icr.rb
  Formula/cvs-fast-export.rb
  Formula/daemontools.rb
  Formula/dict.rb
  Formula/discount.rb
  Formula/gcc.rb
  Formula/hdf5.rb
  Formula/lapack.rb
  Formula/libepoxy.rb
  Formula/libgpg-error.rb
  Formula/libofx.rb
  Formula/makensis.rb
  Formula/molecule.rb
  Formula/netcdf.rb
  Formula/numpy.rb
  Formula/open-mpi.rb
  Formula/openblas.rb
  Formula/r.rb
  Formula/reprepro.rb
  Formula/scalapack.rb
  Formula/sparse.rb
  Formula/suite-sparse.rb
  Formula/tasksh.rb
  Formula/veclibfort.rb
  Formula/zpaq.rb
  Formula/zyre.rb
Labels: merge

#21935 Merge 2020-12-23 4e799308d7f
  Formula/fftw.rb
Labels: merge

#21936 Merge 2020-12-23 bdd7b9fbe38
  Formula/subversion.rb
Labels: merge

#21937 Merge 2020-12-23 d51c7cfbc59
  Formula/aterm.rb
  Formula/atkmm@2.28.rb
  Formula/awk.rb
  Formula/coinutils.rb
  Formula/czmq.rb
  Formula/easy-tag.rb
  Formula/faust.rb
  Formula/fftw.rb
  Formula/flann.rb
  Formula/gerbv.rb
  Formula/getdns.rb
  Formula/glbinding.rb
  Formula/glib-networking.rb
  Formula/gnome-common.rb
  Formula/gnu-shogi.rb
  Formula/googletest.rb
  Formula/gpgme.rb
  Formula/gstreamer.rb
  Formula/gtkglext.rb
  Formula/gtkmm3.rb
  Formula/gts.rb
  Formula/icecream.rb
  Formula/innoextract.rb
  Formula/jp2a.rb
  Formula/json-glib.rb
  Formula/libbtbb.rb
  Formula/libestr.rb
  Formula/libfontenc.rb
  Formula/libglade.rb
  Formula/libgxps.rb
  Formula/libnetworkit.rb
  Formula/libnfs.rb
  Formula/librem.rb
  Formula/libtorrent-rakshasa.rb
  Formula/libupnp.rb
  Formula/libwmf.rb
  Formula/libxtst.rb
  Formula/lldpd.rb
  Formula/nanomsg.rb
  Formula/netpbm.rb
  Formula/openldap.rb
  Formula/pangomm@2.42.rb
  Formula/pbc.rb
  Formula/qdbm.rb
  Formula/quickjs.rb
  Formula/recode.rb
  Formula/scipy.rb
  Formula/subversion.rb
  Formula/superlu.rb
  Formula/x265.rb
  Formula/xa.rb
  Formula/xcb-util-image.rb
  Formula/xmltoman.rb
  Formula/yaml-cpp.rb
  Formula/zile.rb
Labels: merge

#21940 Merge 2020-12-24 3b89cff8620
  Formula/gnu-tar.rb
  Formula/libva.rb
  Formula/sqlc.rb
Labels: merge

#21941 Merge 2020-12-24 2482b823cd4
  .github/workflows/remove-disabled-formulae.yml
Labels: merge

#21942 Merge 2020-12-24 25d2f457910
  Formula/appledoc.rb
  Formula/ballerina.rb
  Formula/bison@2.7.rb
  Formula/botan.rb
  Formula/chruby.rb
  Formula/contentful-cli.rb
  Formula/dcm2niix.rb
  Formula/dfu-programmer.rb
  Formula/freerdp.rb
  Formula/ghostscript.rb
  Formula/gpac.rb
  Formula/gst-plugins-ugly.rb
  Formula/homebank.rb
  Formula/icarus-verilog.rb
  Formula/immudb.rb
  Formula/john.rb
  Formula/jrnl.rb
  Formula/lcov.rb
  Formula/ledger.rb
  Formula/lightgbm.rb
  Formula/mariadb-connector-c.rb
  Formula/mariadb.rb
  Formula/mariadb@10.1.rb
  Formula/mariadb@10.2.rb
  Formula/mariadb@10.3.rb
  Formula/mariadb@10.4.rb
  Formula/mosquitto.rb
  Formula/msmtp.rb
  Formula/mutt.rb
  Formula/mysql-client@5.7.rb
  Formula/mysql.rb
  Formula/mysql@5.6.rb
  Formula/mysql@5.7.rb
  Formula/neko.rb
  Formula/nlopt.rb
  Formula/notmuch.rb
  Formula/oath-toolkit.rb
  Formula/ompl.rb
  Formula/open-mpi.rb
  Formula/openal-soft.rb
  Formula/openconnect.rb
  Formula/openslide.rb
  Formula/optipng.rb
  Formula/pass.rb
  Formula/percona-server.rb
  Formula/pnpm.rb
  Formula/postgresql@9.5.rb
  Formula/qbs.rb
  Formula/radare2.rb
  Formula/root.rb
  Formula/sdl2.rb
  Formula/spatialindex.rb
  Formula/streamlink.rb
  Formula/vapor.rb
  Formula/vitetris.rb
  Formula/weechat.rb
  Formula/wolfssl.rb
  Formula/xcproj.rb
  Formula/z.lua.rb
Labels: merge

#21953 Merge 2020-12-25 75b0050083c
  Formula/cbc.rb
  Formula/erlang@20.rb
  Formula/erlang@21.rb
  Formula/erlang@22.rb
  Formula/gcc@6.rb
  Formula/gcc@7.rb
  Formula/gcc@8.rb
  Formula/gcc@9.rb
  Formula/ghc@8.6.rb
  Formula/ghc@8.8.rb
  Formula/go@1.10.rb
  Formula/go@1.11.rb
  Formula/go@1.12.rb
  Formula/go@1.13.rb
  Formula/go@1.14.rb
  Formula/go@1.9.rb
  Formula/libgnomecanvas.rb
  Formula/lilv.rb
  Formula/llvm@7.rb
  Formula/llvm@8.rb
  Formula/llvm@9.rb
  Formula/minipro.rb
Labels: merge

#21965 Merge 2020-12-27 539de35586a
  .github/workflows/tests.yml
  Formula/abseil.rb
  Formula/asio.rb
  Formula/grpc.rb
  Formula/hqx.rb
  Formula/imagejs.rb
  Formula/jerasure.rb
  Formula/libcddb.rb
  Formula/liberasurecode.rb
  Formula/nfpm.rb
  Formula/pg_top.rb
  Formula/pyinvoke.rb
  Formula/restview.rb
  Formula/rinetd.rb
  Formula/robot-framework.rb
  Formula/rst-lint.rb
  Formula/scour.rb
  Formula/shallow-backup.rb
  Formula/spidermonkey.rb
  Formula/sshuttle.rb
  Formula/supervisor.rb
  Formula/trailscraper.rb
  Formula/trash-cli.rb
  Formula/ucl.rb
  Formula/ydcv.rb
  Formula/you-get.rb
  Formula/youtube-dlc.rb
Labels: merge

#21967 Merge 2020-12-27 e89c6dc7fdc
  .github/workflows/tests.yml
  Formula/a2ps.rb
  Formula/babl.rb
  Formula/baobab.rb
  Formula/dnscontrol.rb
  Formula/elixir.rb
  Formula/erlang.rb
  Formula/gcab.rb
  Formula/gtksourceview3.rb
  Formula/gtksourceview4.rb
  Formula/gtkspell3.rb
  Formula/jql.rb
  Formula/jsonrpc-glib.rb
  Formula/lfe.rb
  Formula/libarchive.rb
  Formula/libdazzle.rb
  Formula/libgee.rb
  Formula/libgusb.rb
  Formula/libhandy.rb
  Formula/libpeas.rb
  Formula/librttopo.rb
  Formula/libsecret.rb
  Formula/libsoup.rb
  Formula/ngs.rb
  Formula/proper.rb
  Formula/rebar.rb
  Formula/rebar3.rb
  Formula/sdb.rb
  Formula/syntaxerl.rb
  Formula/vala.rb
  Formula/valabind.rb
  Formula/yaws.rb
Labels: merge

#21971 Merge 2020-12-28 ab76bbeb0fb
  Aliases/ruby@3.0
  Formula/cocoapods.rb
  Formula/cucumber-ruby.rb
  Formula/fastlane.rb
  Formula/gxml.rb
  Formula/libhttpseverywhere.rb
  Formula/libstfl.rb
  Formula/macosvpn.rb
  Formula/macvim.rb
  Formula/mikutter.rb
  Formula/msitools.rb
  Formula/nfpm.rb
  Formula/passenger.rb
  Formula/ruby.rb
  Formula/tepl.rb
  Formula/terraform_landscape.rb
  Formula/travis.rb
  Formula/vim.rb
  Formula/vitetris.rb
  Formula/vte3.rb
  Formula/weechat.rb
Labels: merge

#21972 Merge 2020-12-28 8e1b9d7564a
  Formula/cgal.rb
  Formula/codequery.rb
  Formula/color-code.rb
  Formula/dspdfviewer.rb
  Formula/fig2dev.rb
  Formula/git-cola.rb
  Formula/gnuplot.rb
  Formula/hatari.rb
  Formula/iam-policy-json-to-terraform.rb
  Formula/icemon.rb
  Formula/imagemagick.rb
  Formula/inspectrum.rb
  Formula/ircd-hybrid.rb
  Formula/kde-extra-cmake-modules.rb
  Formula/libgr.rb
  Formula/libheif.rb
  Formula/libxslt.rb
  Formula/localstack.rb
  Formula/opencsg.rb
  Formula/pangomm@2.42.rb
  Formula/pgroonga.rb
  Formula/poppler.rb
  Formula/poster.rb
  Formula/pyqt.rb
  Formula/qbs.rb
  Formula/qjson.rb
  Formula/qt.rb
  Formula/qtads.rb
  Formula/qtkeychain.rb
  Formula/stress-ng.rb
  Formula/terraform_landscape.rb
  Formula/trash-cli.rb
  Formula/trimage.rb
  Formula/urh.rb
  Formula/vtk.rb
  Formula/vtk@8.2.rb
  Formula/x265.rb
  Formula/xpdf.rb
  Formula/xterm.rb
  Formula/you-get.rb
  Formula/youtube-dl.rb
  Formula/zurl.rb
Labels: merge

#21974 Merge 2020-12-28 05d9a5fbc44
  Formula/braid.rb
  Formula/cargo-audit.rb
  Formula/cargo-watch.rb
  Formula/graphicsmagick.rb
  Formula/lasi.rb
  Formula/monolith.rb
  Formula/rubberband.rb
  Formula/vcpkg.rb
Labels: merge

#21976 Merge 2020-12-28 f0cd0c7533b
  Formula/agda.rb
  Formula/allureofthestars.rb
  Formula/bond.rb
  Formula/direnv.rb
  Formula/dnsprobe.rb
  Formula/futhark.rb
  Formula/ghc.rb
  Formula/git-annex.rb
  Formula/glab.rb
  Formula/harfbuzz.rb
  Formula/haskell-stack.rb
  Formula/hatari.rb
  Formula/imagejs.rb
  Formula/jpeg-turbo.rb
  Formula/liboil.rb
  Formula/libvnc.rb
  Formula/libvncserver.rb
  Formula/mapcrafter.rb
  Formula/mozjpeg.rb
  Formula/mpg123.rb
  Formula/msgpuck.rb
  Formula/ocp.rb
  Formula/ocrmypdf.rb
  Formula/open-scene-graph.rb
  Formula/pdfgrep.rb
  Formula/podman.rb
  Formula/regldg.rb
  Formula/rgf.rb
  Formula/scummvm.rb
  Formula/t-rec.rb
  Formula/tiger-vnc.rb
  Formula/vecx.rb
  Formula/vice.rb
  Formula/vips.rb
  Formula/wimlib.rb
  Formula/wwwoffle.rb
Labels: merge

#21978 Merge 2020-12-29 7bf13820da1
  Formula/cocoapods.rb
  Formula/cubejs-cli.rb
  Formula/exult.rb
  Formula/gcc.rb
  Formula/git-cal.rb
  Formula/lighttpd.rb
  Formula/macvim.rb
  Formula/nco.rb
  Formula/repo.rb
  Formula/ruby.rb
  Formula/sdb.rb
  Formula/serialosc.rb
  Formula/snappystream.rb
  Formula/task-spooler.rb
  Formula/tectonic.rb
  Formula/texmath.rb
  Formula/tmpreaper.rb
  Formula/topgrade.rb
  Formula/vim.rb
  Formula/whohas.rb
  Formula/ykneomgr.rb
  Formula/yq.rb
Labels: merge

#21979 Merge 2020-12-29 4d3cb563f04
  .github/workflows/dispatch-rebottle.yml
Labels: merge

#21980 Merge 2020-12-29 59761d265a3
  Formula/abseil.rb
  Formula/b43-fwcutter.rb
  Formula/broot.rb
  Formula/bullet.rb
  Formula/dpkg.rb
  Formula/eksctl.rb
  Formula/freerdp.rb
  Formula/ghostscript.rb
  Formula/git-delta.rb
  Formula/glow.rb
  Formula/grpc.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jupyterlab.rb
  Formula/lazygit.rb
  Formula/libarchive.rb
  Formula/libepoxy.rb
  Formula/libxslt.rb
  Formula/massdns.rb
  Formula/mosquitto.rb
  Formula/notmuch.rb
  Formula/pugixml.rb
  Formula/pulumi.rb
  Formula/rttr.rb
  Formula/sdl2.rb
  Formula/sfst.rb
  Formula/sshuttle.rb
  Formula/supervisor.rb
  Formula/swiftformat.rb
  Formula/tmpreaper.rb
  Formula/travis.rb
  Formula/weechat.rb
Labels: merge

#21984 Merge 2020-12-29 619d7365104
  Formula/camlp5.rb
  Formula/croc.rb
  Formula/curl.rb
  Formula/diff-pdf.rb
  Formula/dmalloc.rb
  Formula/dnstwist.rb
  Formula/earthly.rb
  Formula/fex.rb
  Formula/git-gui.rb
  Formula/git.rb
  Formula/gitmoji.rb
  Formula/glab.rb
  Formula/golangci-lint.rb
  Formula/hledger.rb
  Formula/ired.rb
  Formula/lci.rb
  Formula/lean-cli.rb
  Formula/mmctl.rb
  Formula/mockery.rb
  Formula/petsc.rb
  Formula/pidgin.rb
  Formula/poetry.rb
  Formula/rust-analyzer.rb
  Formula/sn0int.rb
  Formula/sshuttle.rb
  Formula/swiftformat.rb
  Formula/uggconv.rb
  Formula/wasm3.rb
  Formula/youtube-dl.rb
Labels: merge

#21985 Merge 2020-12-29 471132123dc
  Formula/cmockery.rb
  Formula/cmuclmtk.rb
  Formula/doublecpp.rb
  Formula/fetch-crl.rb
  Formula/gconf.rb
  Formula/gistit.rb
  Formula/gromacs.rb
  Formula/heatshrink.rb
  Formula/httptunnel.rb
  Formula/iprint.rb
  Formula/jerasure.rb
  Formula/kytea.rb
  Formula/libopendkim.rb
  Formula/luabind.rb
  Formula/m2c.rb
  Formula/makepp.rb
  Formula/marst.rb
  Formula/mboxgrep.rb
  Formula/mlkit.rb
  Formula/mmsrip.rb
  Formula/nylon.rb
  Formula/pit.rb
  Formula/qdae.rb
  Formula/ratfor.rb
  Formula/shivavg.rb
  Formula/supermodel.rb
  Formula/torrentcheck.rb
Labels: merge

#21987 Merge 2020-12-29 e1b43eb23c8
  Formula/ansible.rb
  Formula/azure-cli.rb
  Formula/cubelib.rb
  Formula/dashing.rb
  Formula/g2.rb
  Formula/gdcm.rb
  Formula/gitbucket.rb
  Formula/goreleaser.rb
  Formula/hoedown.rb
  Formula/infracost.rb
  Formula/jenkins.rb
  Formula/kcov.rb
  Formula/libgcrypt.rb
  Formula/libhandy.rb
  Formula/mdbtools.rb
  Formula/mecab-unidic-extended.rb
  Formula/mpdas.rb
  Formula/nfpm.rb
  Formula/oq.rb
  Formula/pbc-sig.rb
  Formula/pdf2svg.rb
  Formula/pkger.rb
  Formula/pod2man.rb
  Formula/qca.rb
  Formula/s2n.rb
  Formula/scs.rb
  Formula/style-check.rb
  Formula/wait_on.rb
  Formula/wangle.rb
  Formula/wolfssl.rb
  Formula/wxmaxima.rb
Labels: merge

#21989 Merge 2020-12-30 52a8d4b04e7
  Formula/blahtexml.rb
  Formula/cartridge-cli.rb
  Formula/catch2.rb
  Formula/cmockery2.rb
  Formula/cortex.rb
  Formula/dashing.rb
  Formula/ekhtml.rb
  Formula/flickcurl.rb
  Formula/gdal.rb
  Formula/git-if.rb
  Formula/groonga.rb
  Formula/juise.rb
  Formula/kpcli.rb
  Formula/kustomize.rb
  Formula/languagetool.rb
  Formula/libdap.rb
  Formula/libproxy.rb
  Formula/libshout.rb
  Formula/mask.rb
  Formula/minio-mc.rb
  Formula/minizip2.rb
  Formula/notmuch-mutt.rb
  Formula/ogmtools.rb
  Formula/pandoc.rb
  Formula/pktanon.rb
  Formula/pueue.rb
  Formula/sqlite-utils.rb
  Formula/sqtop.rb
  Formula/swagger-codegen.rb
  Formula/swagger-codegen@2.rb
  Formula/tokei.rb
  Formula/treecc.rb
  Formula/wireguard-tools.rb
  Formula/xerces-c.rb
  Formula/xml-security-c.rb
  Formula/xqilla.rb
  Formula/xsd.rb
Labels: merge

#21990 Merge 2020-12-30 996fadaab2a
  Formula/apachetop.rb
  Formula/awscli.rb
  Formula/buku.rb
  Formula/castget.rb
  Formula/commitizen.rb
  Formula/fragroute.rb
  Formula/git-annex.rb
  Formula/idris2.rb
  Formula/libgosu.rb
  Formula/minio.rb
  Formula/mps-youtube.rb
  Formula/newrelic-cli.rb
  Formula/nicotine-plus.rb
  Formula/node-sass.rb
  Formula/tcc.rb
  Formula/unac.rb
  Formula/x3270.rb
  Formula/xclogparser.rb
Labels: merge

#21991 Merge 2020-12-30 3f18b0de7c3
  Formula/azure-cli.rb
  Formula/blogc.rb
  Formula/chafa.rb
  Formula/dcled.rb
  Formula/gcc.rb
  Formula/iam-policy-json-to-terraform.rb
  Formula/libchaos.rb
  Formula/logcli.rb
  Formula/mdv.rb
  Formula/mypy.rb
  Formula/numpy.rb
  Formula/passpie.rb
  Formula/pdf-redact-tools.rb
  Formula/pqiv.rb
  Formula/python@3.8.rb
  Formula/qalculate-gtk.rb
  Formula/s3cmd.rb
  Formula/sceptre.rb
  Formula/twtxt.rb
  Formula/vcdimager.rb
  Formula/watch-sim.rb
  Formula/wy60.rb
  Formula/xsw.rb
Labels: merge

#21992 Merge 2020-12-30 dd0275f6774
  Formula/anime-downloader.rb
  Formula/attr.rb
  Formula/binkd.rb
  Formula/bpytop.rb
  Formula/cucumber-cpp.rb
  Formula/cvs-fast-export.rb
  Formula/fsw.rb
  Formula/gnumeric.rb
  Formula/goreleaser.rb
  Formula/hdt.rb
  Formula/jinx.rb
  Formula/kcov.rb
  Formula/libevhtp.rb
  Formula/neofetch.rb
  Formula/platformio.rb
  Formula/postgresql@11.rb
  Formula/r.rb
  Formula/rpg.rb
  Formula/snappystream.rb
  Formula/ucommon.rb
  Formula/vlang.rb
  Formula/xml-tooling-c.rb
  Formula/xmlsectool.rb
  Formula/z.lua.rb
Labels: merge

#21995 Merge 2020-12-31 46de6592e74
  Formula/cfn-lint.rb
  Formula/commitizen.rb
  Formula/cubejs-cli.rb
  Formula/gwyddion.rb
  Formula/jfrog-cli.rb
  Formula/keptn.rb
  Formula/md4c.rb
  Formula/mermaid-cli.rb
  Formula/monero.rb
  Formula/pygitup.rb
  Formula/rpm.rb
  Formula/serverless.rb
  Formula/vim.rb
  Formula/wxmaxima.rb
  Formula/xmlsectool.rb
Labels: merge

#21996 Merge 2020-12-31 09cf49c01b2
  Formula/pypy.rb
  Formula/pypy3.rb
Labels: merge

#21998 Merge 2020-12-31 e1a9ed27915
  Formula/aws-cdk.rb
  Formula/blahtexml.rb
  Formula/eye-d3.rb
  Formula/gmailctl.rb
  Formula/helib.rb
  Formula/hlint.rb
  Formula/ocrmypdf.rb
  Formula/vlang.rb
  Formula/yadm.rb
  Formula/youtube-dl.rb
Labels: merge

#21999 Merge 2020-12-31 82886386cd1
  Formula/ack.rb
  Formula/cloc.rb
  Formula/creduce.rb
  Formula/ddclient.rb
  Formula/extract_url.rb
  Formula/get-flash-videos.rb
  Formula/heimdal.rb
  Formula/innotop.rb
  Formula/monkeysphere.rb
  Formula/moreutils.rb
  Formula/mytop.rb
  Formula/percona-xtrabackup.rb
  Formula/perltidy.rb
  Formula/resty.rb
  Formula/winexe.rb
Labels: merge

#22001 Merge 2020-12-31 79f360462ac
  Formula/cubejs-cli.rb
  Formula/duplicity.rb
  Formula/git-delta.rb
  Formula/kyma-cli.rb
  Formula/libbluray.rb
  Formula/libgcrypt.rb
  Formula/mesa.rb
  Formula/oath-toolkit.rb
  Formula/vim.rb
Labels: merge
