Repository Homebrew/linuxbrew-core, pull requests merged in 2020-07, with the labels that each got.

#20655 Merge 2020-07-01 b37dd495936
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20656 Merge 2020-07-01 d12d39745cd
  CONTRIBUTING.md
  Formula/abcmidi.rb
  Formula/arduino-cli.rb
  Formula/atlassian-cli.rb
  Formula/awscli@1.rb
  Formula/balena-cli.rb
  Formula/bazel.rb
  Formula/broot.rb
  Formula/bwctl.rb
  Formula/caddy.rb
  Formula/ccal.rb
  Formula/ccze.rb
  Formula/cdargs.rb
  Formula/cheat.rb
  Formula/chibi-scheme.rb
  Formula/cpio.rb
  Formula/cvsps.rb
  Formula/diamond.rb
  Formula/docfx.rb
  Formula/docker-compose.rb
  Formula/dvc.rb
  Formula/exploitdb.rb
  Formula/git.rb
  Formula/gradle.rb
  Formula/guile.rb
  Formula/kamel.rb
  Formula/kubectx.rb
  Formula/kubeless.rb
  Formula/kumactl.rb
  Formula/libraqm.rb
  Formula/libunistring.rb
  Formula/liquidprompt.rb
  Formula/meilisearch.rb
  Formula/mit-scheme.rb
  Formula/mmark.rb
  Formula/nauty.rb
  Formula/netlify-cli.rb
  Formula/node@12.rb
  Formula/osmosis.rb
  Formula/swi-prolog.rb
  Formula/topgrade.rb
  Formula/vala.rb
  Formula/wren-cli.rb
Labels: merge

#20658 Merge 2020-07-01 f3258ddad8e
  .github/workflows/publish-commit-bottles.yml
  Formula/ack.rb
  Formula/aws-cdk.rb
  Formula/awscli.rb
  Formula/babel.rb
  Formula/bit.rb
  Formula/cargo-c.rb
  Formula/cartridge-cli.rb
  Formula/curl-openssl.rb
  Formula/curl.rb
  Formula/docker-compose-completion.rb
  Formula/ginac.rb
  Formula/gitlab-runner.rb
  Formula/inxi.rb
  Formula/jenkins.rb
  Formula/maxwell.rb
  Formula/mlpack.rb
  Formula/semgrep.rb
  Formula/teleport.rb
  Formula/vim.rb
Labels: merge

#20662 Merge 2020-07-02 c5c33927924
  Formula/ace.rb
  Formula/afl-fuzz.rb
  Formula/aliyun-cli.rb
  Formula/aws-cdk.rb
  Formula/bmake.rb
  Formula/borgmatic.rb
  Formula/devspace.rb
  Formula/digdag.rb
  Formula/django-completion.rb
  Formula/exploitdb.rb
  Formula/fdupes.rb
  Formula/gdcm.rb
  Formula/grafana.rb
  Formula/kcptun.rb
  Formula/netdata.rb
  Formula/ngt.rb
  Formula/node.rb
  Formula/nushell.rb
  Formula/phpstan.rb
  Formula/re2.rb
  Formula/sqlmap.rb
  Formula/telegraf.rb
  Formula/terragrunt.rb
Labels: merge

#20663 Merge 2020-07-02 5c6dd490292
  Aliases/openjdk@14
  Formula/dynare.rb
  Formula/gitbucket.rb
  Formula/grails.rb
  Formula/hbase.rb
  Formula/i2p.rb
  Formula/lcm.rb
  Formula/lumo.rb
  Formula/micronaut.rb
  Formula/nailgun.rb
  Formula/openjdk.rb
  Formula/opentsdb.rb
  Formula/pdftk-java.rb
  Formula/selenium-server-standalone.rb
  Formula/unravel.rb
Labels: merge

#20664 Merge 2020-07-02 76e0e788242
  Formula/angular-cli.rb
  Formula/aws-iam-authenticator.rb
  Formula/aws-sdk-cpp.rb
  Formula/cbmc.rb
  Formula/conan.rb
  Formula/exiv2.rb
  Formula/faudio.rb
  Formula/gatsby-cli.rb
  Formula/git-delta.rb
  Formula/gleam.rb
  Formula/jenkins-lts.rb
  Formula/jenkins.rb
  Formula/kustomize.rb
  Formula/lxc.rb
  Formula/mandown.rb
  Formula/mdbook.rb
  Formula/nasm.rb
  Formula/netlify-cli.rb
  Formula/okteto.rb
  Formula/orientdb.rb
  Formula/pandoc-include-code.rb
  Formula/pre-commit.rb
  Formula/predictionio.rb
  Formula/proj.rb
  Formula/pwntools.rb
  Formula/re-flex.rb
  Formula/saltwater.rb
  Formula/step.rb
  Formula/swiftformat.rb
  Formula/yaegi.rb
Labels: merge

#20666 Merge 2020-07-03 dd536fe88a3
  Formula/activemq.rb
  Formula/buildozer.rb
  Formula/convox.rb
  Formula/cucumber-ruby.rb
  Formula/docker-compose-completion.rb
  Formula/docker-compose.rb
  Formula/dvc.rb
  Formula/entr.rb
  Formula/exploitdb.rb
  Formula/fastlane.rb
  Formula/gimme-aws-creds.rb
  Formula/google-java-format.rb
  Formula/grin-wallet.rb
  Formula/gsoap.rb
  Formula/gwyddion.rb
  Formula/jruby.rb
  Formula/knot-resolver.rb
  Formula/latex2html.rb
  Formula/libphonenumber.rb
  Formula/libplctag.rb
  Formula/libvmaf.rb
  Formula/minio.rb
  Formula/nasm.rb
  Formula/openssl@1.1.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/questdb.rb
  Formula/rom-tools.rb
  Formula/swiftformat.rb
  Formula/typescript.rb
Labels: merge

#20667 Merge 2020-07-03 8d703e6d960
  Formula/aws-cdk.rb
  Formula/awscli.rb
  Formula/bit.rb
  Formula/broot.rb
  Formula/cartridge-cli.rb
  Formula/crystal.rb
  Formula/dita-ot.rb
  Formula/docker-compose-completion.rb
  Formula/docker-compose.rb
  Formula/gatsby-cli.rb
  Formula/gofish.rb
  Formula/graphql-cli.rb
  Formula/grin.rb
  Formula/istioctl.rb
  Formula/john.rb
  Formula/lego.rb
  Formula/mercurial.rb
  Formula/nebula.rb
  Formula/pandoc-crossref.rb
  Formula/r.rb
  Formula/rust.rb
  Formula/step.rb
  Formula/telnet.rb
  Formula/telnetd.rb
  Formula/terraform-ls.rb
  Formula/tmux.rb
  Formula/ungit.rb
  Formula/wiremock-standalone.rb
Labels: merge

#20670 Merge 2020-07-04 6a06d11a68a
  Aliases/gcc@10
  Formula/abyss.rb
  Formula/adios2.rb
  Formula/armadillo.rb
  Formula/arpack.rb
  Formula/augustus.rb
  Formula/cgns.rb
  Formula/cp2k.rb
  Formula/dungeon.rb
  Formula/dynare.rb
  Formula/eccodes.rb
  Formula/ensmallen.rb
  Formula/fastme.rb
  Formula/fftw.rb
  Formula/gcc.rb
  Formula/gcc@9.rb
  Formula/glew.rb
  Formula/gromacs.rb
  Formula/hdf5-mpi.rb
  Formula/hdf5.rb
  Formula/hdf5@1.10.rb
  Formula/hdf5@1.8.rb
  Formula/imake.rb
  Formula/ipopt.rb
  Formula/json-fortran.rb
  Formula/kahip.rb
  Formula/kim-api.rb
  Formula/lapack.rb
  Formula/libfabric.rb
  Formula/libxc.rb
  Formula/mlpack.rb
  Formula/mpich.rb
  Formula/netcdf.rb
  Formula/nwchem.rb
  Formula/octave.rb
  Formula/open-mpi.rb
  Formula/openblas.rb
  Formula/openfast.rb
  Formula/openkim-models.rb
  Formula/packmol.rb
  Formula/petsc-complex.rb
  Formula/petsc.rb
  Formula/pgplot.rb
  Formula/plplot.rb
  Formula/pnetcdf.rb
  Formula/qrupdate.rb
  Formula/r.rb
  Formula/reprepro.rb
  Formula/root.rb
  Formula/scalapack.rb
  Formula/scipy.rb
  Formula/sparse.rb
  Formula/veclibfort.rb
Labels: merge

#20672 Merge 2020-07-05 dfe07405f42
  Formula/aws-cdk.rb
  Formula/balena-cli.rb
  Formula/coturn.rb
  Formula/cqlkit.rb
  Formula/dbus.rb
  Formula/ddgr.rb
  Formula/dune.rb
  Formula/dvc.rb
  Formula/faas-cli.rb
  Formula/fastlane.rb
  Formula/gatsby-cli.rb
  Formula/govc.rb
  Formula/help2man.rb
  Formula/jdupes.rb
  Formula/libvirt.rb
  Formula/metricbeat.rb
  Formula/mlpack.rb
  Formula/mtoc.rb
  Formula/muparser.rb
  Formula/onscripter.rb
  Formula/openimageio.rb
  Formula/opusfile.rb
  Formula/pdnsrec.rb
  Formula/pnpm.rb
  Formula/profanity.rb
  Formula/sqlite.rb
  Formula/stellar-core.rb
  Formula/swift-protobuf.rb
  Formula/valgrind.rb
  Formula/vault.rb
  Formula/watchexec.rb
  Formula/wireshark.rb
  Formula/x264.rb
  Formula/yaegi.rb
Labels: merge

#20675 Merge 2020-07-05 dd160c3c8eb
  Formula/cloudformation-cli.rb
  Formula/diff-pdf.rb
  Formula/exploitdb.rb
  Formula/ffmpeg.rb
  Formula/ffmpeg@2.8.rb
  Formula/gdal.rb
  Formula/gmt.rb
  Formula/gmt@5.rb
  Formula/gnunet.rb
  Formula/gst-plugins-ugly.rb
  Formula/howdoi.rb
  Formula/i686-elf-gcc.rb
  Formula/jdupes.rb
  Formula/libav.rb
  Formula/libextractor.rb
  Formula/mapserver.rb
  Formula/meson.rb
  Formula/mockserver.rb
  Formula/pdal.rb
  Formula/pdftoipe.rb
  Formula/pgroonga.rb
  Formula/points2grid.rb
  Formula/poppler.rb
  Formula/sile.rb
  Formula/simple-tiles.rb
  Formula/sonarqube.rb
  Formula/terraform-ls.rb
  Formula/watson.rb
  Formula/x264.rb
  Formula/x86_64-elf-gcc.rb
Labels: merge

#20677 Merge 2020-07-05 84578dd13ce
  Formula/aliyun-cli.rb
  Formula/arduino-cli.rb
  Formula/balena-cli.rb
  Formula/deno.rb
  Formula/diffoscope.rb
  Formula/fastlane.rb
  Formula/freetds.rb
  Formula/gowsdl.rb
  Formula/libmpdclient.rb
  Formula/librsvg.rb
  Formula/liquibase.rb
  Formula/mafft.rb
  Formula/mdbook.rb
  Formula/mmctl.rb
  Formula/odpi.rb
  Formula/opencoarrays.rb
  Formula/osm2pgsql.rb
  Formula/ott.rb
  Formula/xclogparser.rb
Labels: merge

#20678 Merge 2020-07-05 aadf808bc28
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20679 Merge 2020-07-05 e9700c948cc
  Formula/atomicparsley.rb
  Formula/bettercap.rb
  Formula/cdargs.rb
  Formula/dxpy.rb
  Formula/eslint.rb
  Formula/evince.rb
  Formula/falcon.rb
  Formula/html2text.rb
  Formula/kitchen-sync.rb
  Formula/libgusb.rb
  Formula/libuv.rb
  Formula/pc6001vx.rb
  Formula/python@3.8.rb
  Formula/simple-scan.rb
  Formula/ungit.rb
  Formula/virustotal-cli.rb
Labels: merge

#20680 Merge 2020-07-06 3f222b4d6b4
  Formula/include-what-you-use.rb
  Formula/ios-webkit-debug-proxy.rb
  Formula/pcre2.rb
  Formula/pnpm.rb
  Formula/python.rb
  Formula/scons.rb
Labels: merge

#20681 Merge 2020-07-06 b231fccb47e
  Formula/awk.rb
  Formula/bacula-fd.rb
  Formula/bareos-client.rb
  Formula/bash-completion.rb
  Formula/bash-completion@2.rb
  Formula/bash-snippets.rb
  Formula/cheat.rb
  Formula/fastbit.rb
  Formula/ffind.rb
  Formula/fluent-bit.rb
  Formula/gawk.rb
  Formula/git-flow-avh.rb
  Formula/git-flow.rb
  Formula/iniparser.rb
  Formula/lesstif.rb
  Formula/libiodbc.rb
  Formula/manticoresearch.rb
  Formula/mariadb-connector-c.rb
  Formula/mariadb.rb
  Formula/midnight-commander.rb
  Formula/minio-mc.rb
  Formula/monitoring-plugins.rb
  Formula/montage.rb
  Formula/moreutils.rb
  Formula/mupdf-tools.rb
  Formula/mupdf.rb
  Formula/mysql.rb
  Formula/nagios-plugins.rb
  Formula/openmotif.rb
  Formula/parallel.rb
  Formula/percona-server.rb
  Formula/pwntools.rb
  Formula/rarian.rb
  Formula/scrollkeeper.rb
  Formula/sleuthkit.rb
  Formula/task-spooler.rb
  Formula/unixodbc.rb
  Formula/virtuoso.rb
  Formula/wdiff.rb
  Formula/xqilla.rb
  Formula/zorba.rb
Labels: merge

#20682 Merge 2020-07-06 e02e6f41333
  Formula/circleci.rb
  Formula/dvc.rb
  Formula/fastlane.rb
  Formula/fdupes.rb
  Formula/gor.rb
  Formula/mill.rb
  Formula/mksh.rb
  Formula/n.rb
  Formula/neatvi.rb
  Formula/node-build.rb
  Formula/pcre.rb
  Formula/publish.rb
  Formula/pwntools.rb
  Formula/remake.rb
  Formula/suite-sparse.rb
  Formula/zoxide.rb
Labels: merge

#20683 Merge 2020-07-06 146159ba435
  Formula/aws-iam-authenticator.rb
  Formula/buildkit.rb
  Formula/cassowary.rb
  Formula/cayley.rb
  Formula/certigo.rb
  Formula/circleci.rb
  Formula/clojure.rb
  Formula/consul-template.rb
  Formula/crystal.rb
  Formula/deno.rb
  Formula/docker.rb
  Formula/flashrom.rb
  Formula/gauge.rb
  Formula/gdcm.rb
  Formula/goofys.rb
  Formula/gopass.rb
  Formula/hcloud.rb
  Formula/kamel.rb
  Formula/kapacitor.rb
  Formula/kind.rb
  Formula/kompose.rb
  Formula/kops.rb
  Formula/kubecfg.rb
  Formula/kubernetes-cli.rb
  Formula/linkerd.rb
  Formula/minikube.rb
  Formula/mmctl.rb
  Formula/monetdb.rb
  Formula/nagios.rb
  Formula/newrelic-cli.rb
  Formula/noweb.rb
  Formula/octant.rb
  Formula/operator-sdk.rb
  Formula/php.rb
  Formula/php@7.3.rb
  Formula/pjproject.rb
  Formula/polipo.rb
  Formula/pulp.rb
  Formula/rack.rb
  Formula/serverless.rb
  Formula/skaffold.rb
  Formula/skopeo.rb
  Formula/ssdb.rb
  Formula/subversion.rb
  Formula/tile38.rb
  Formula/velero.rb
  Formula/virustotal-cli.rb
Labels: merge

#20686 Merge 2020-07-06 75210ba57e4
  Formula/agedu.rb
  Formula/ammonite-repl.rb
  Formula/artifactory.rb
  Formula/benthos.rb
  Formula/bit.rb
  Formula/boost-python.rb
  Formula/broot.rb
  Formula/cartridge-cli.rb
  Formula/catch2.rb
  Formula/elixir.rb
  Formula/erlang.rb
  Formula/flowgrind.rb
  Formula/fluent-bit.rb
  Formula/git-town.rb
  Formula/glooctl.rb
  Formula/gmt.rb
  Formula/grap.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/ipython.rb
  Formula/jhipster.rb
  Formula/juju.rb
  Formula/k9s.rb
  Formula/kustomize.rb
  Formula/lc0.rb
  Formula/libswiften.rb
  Formula/libvorbis.rb
  Formula/mdcat.rb
  Formula/mikutter.rb
  Formula/mpg123.rb
  Formula/pgrouting.rb
  Formula/php@7.2.rb
  Formula/pnpm.rb
  Formula/quickjs.rb
  Formula/rabbitmq.rb
  Formula/rsync.rb
  Formula/rtorrent.rb
  Formula/ruby.rb
  Formula/scipy.rb
  Formula/sdl_mixer.rb
  Formula/serve.rb
  Formula/snapcraft.rb
  Formula/spdylay.rb
  Formula/sphinx-doc.rb
  Formula/sratoolkit.rb
  Formula/swiftgen.rb
  Formula/tarantool.rb
  Formula/tnftp.rb
  Formula/tnftpd.rb
  Formula/unnethack.rb
  Formula/vulkan-headers.rb
  Formula/xmlrpc-c.rb
Labels: merge

#20687 Merge 2020-07-06 d577b06b347
  Formula/aqbanking.rb
  Formula/arabica.rb
  Formula/befunge93.rb
  Formula/circleci.rb
  Formula/docfx.rb
  Formula/duplicity.rb
  Formula/dwarfutils.rb
  Formula/elvish.rb
  Formula/erlang@21.rb
  Formula/erlang@22.rb
  Formula/exploitdb.rb
  Formula/gwenhywfar.rb
  Formula/heimdal.rb
  Formula/helmfile.rb
  Formula/kops.rb
  Formula/libmicrohttpd.rb
  Formula/ltl2ba.rb
  Formula/pick.rb
  Formula/qwt.rb
  Formula/tomcat.rb
  Formula/tomcat@8.rb
  Formula/vttest.rb
Labels: merge

#20689 Merge 2020-07-06 af4d3907b94
  .github/workflows/tests.yml
Labels: merge

#20690 Merge 2020-07-07 42405b31501
  .github/workflows/tests.yml
  Formula/awscli.rb
  Formula/awsweeper.rb
  Formula/cmt.rb
  Formula/easyengine.rb
  Formula/erlang.rb
  Formula/gcsfuse.rb
  Formula/gmp.rb
  Formula/gobby.rb
  Formula/helib.rb
  Formula/libinfinity.rb
  Formula/rust.rb
  Formula/smlpkg.rb
  Formula/spades.rb
  Formula/standardese.rb
  Formula/topgrade.rb
  Formula/ultralist.rb
Labels: merge

#20700 Merge 2020-07-07 3d0445ea4d2
  Formula/bats-core.rb
  Formula/calceph.rb
  Formula/clojure-lsp.rb
  Formula/cmake.rb
  Formula/freeling.rb
  Formula/kube-aws.rb
  Formula/libimobiledevice.rb
  Formula/mercury.rb
  Formula/qca.rb
  Formula/rustup-init.rb
  Formula/starship.rb
Labels: merge

#20701 Merge 2020-07-07 79d74f87682
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20702 Merge 2020-07-07 fe2dccb199f
  Formula/bind.rb
  Formula/carthage.rb
  Formula/clamav.rb
  Formula/colfer.rb
  Formula/cpio.rb
  Formula/dnsperf.rb
  Formula/fastd.rb
  Formula/folly.rb
  Formula/gdal.rb
  Formula/git-plus.rb
  Formula/gitui.rb
  Formula/gjs.rb
  Formula/goreleaser.rb
  Formula/json-c.rb
  Formula/liblwgeom.rb
  Formula/libmypaint.rb
  Formula/libu2f-host.rb
  Formula/libu2f-server.rb
  Formula/mpw.rb
  Formula/ndpi.rb
  Formula/netdata.rb
  Formula/netlify-cli.rb
  Formula/newsboat.rb
  Formula/ntopng.rb
  Formula/pam-u2f.rb
  Formula/pam_yubico.rb
  Formula/pianobar.rb
  Formula/pianod.rb
  Formula/postgis.rb
  Formula/pulseaudio.rb
  Formula/riemann-client.rb
  Formula/seexpr.rb
  Formula/ser2net.rb
  Formula/shogun.rb
  Formula/sloccount.rb
  Formula/tracebox.rb
  Formula/ttyd.rb
  Formula/twarc.rb
  Formula/vgrep.rb
  Formula/ykpers.rb
  Formula/zboy.rb
  Formula/zmap.rb
Labels: merge

#20703 cpio: fix bottling for Linuxbrew
  Formula/cpio.rb
Labels: cellar failure

#20706 Merge 2020-07-08 9206ae4b845
  Formula/aacgain.rb
  Formula/abcmidi.rb
  Formula/afflib.rb
  Formula/allure.rb
  Formula/ask-cli.rb
  Formula/asymptote.rb
  Formula/botan.rb
  Formula/cargo-completion.rb
  Formula/cartridge-cli.rb
  Formula/closure-compiler.rb
  Formula/cpio.rb
  Formula/evince.rb
  Formula/exploitdb.rb
  Formula/freetds.rb
  Formula/futhark.rb
  Formula/gitlab-gem.rb
  Formula/gitui.rb
  Formula/gperftools.rb
  Formula/haproxy.rb
  Formula/lc0.rb
  Formula/libcmph.rb
  Formula/node-build.rb
  Formula/pnpm.rb
  Formula/qca.rb
  Formula/seal.rb
  Formula/sile.rb
  Formula/streamlink.rb
  Formula/u-boot-tools.rb
  Formula/zenith.rb
Labels: merge

#20707 Merge 2020-07-08 be1ba3b4ba9
  Formula/amazon-ecs-cli.rb
  Formula/atlantis.rb
  Formula/aws-cdk.rb
  Formula/awscli.rb
  Formula/botan.rb
  Formula/certbot.rb
  Formula/convox.rb
  Formula/dpkg.rb
  Formula/fastlane.rb
  Formula/ffmpeg@2.8.rb
  Formula/gdal.rb
  Formula/jenkins.rb
  Formula/mftrace.rb
  Formula/mockserver.rb
  Formula/nginx.rb
  Formula/node-sass.rb
  Formula/passenger.rb
  Formula/ppsspp.rb
  Formula/prestosql.rb
  Formula/tanka.rb
  Formula/vim.rb
Labels: merge

#20676 libextractor: Fix build for Linuxbrew
  Formula/libextractor.rb
Labels: dependency

#20714 Merge 2020-07-10 5e548918f27
  Formula/akka.rb
  Formula/angular-cli.rb
  Formula/aws-cdk.rb
  Formula/balena-cli.rb
  Formula/cbmc.rb
  Formula/dmd.rb
  Formula/dub.rb
  Formula/ffsend.rb
  Formula/glooctl.rb
  Formula/gmt.rb
  Formula/gromacs.rb
  Formula/influxdb.rb
  Formula/istioctl.rb
  Formula/liblzf.rb
  Formula/librealsense.rb
  Formula/minetest.rb
  Formula/molecule.rb
  Formula/nomad.rb
  Formula/openstackclient.rb
  Formula/osc.rb
  Formula/phoronix-test-suite.rb
  Formula/php@7.2.rb
  Formula/picard-tools.rb
  Formula/snakemake.rb
  Formula/so.rb
  Formula/spdlog.rb
  Formula/traefik.rb
  Formula/yaegi.rb
Labels: merge

#20715 Merge 2020-07-10 86a9f100c01
  Formula/aliyun-cli.rb
  Formula/awscli.rb
  Formula/awslogs.rb
  Formula/ballerina.rb
  Formula/bareos-client.rb
  Formula/diffoscope.rb
  Formula/erlang@22.rb
  Formula/ethereum.rb
  Formula/exploitdb.rb
  Formula/fonttools.rb
  Formula/gulp-cli.rb
  Formula/juju.rb
  Formula/lazygit.rb
  Formula/litecli.rb
  Formula/minikube.rb
  Formula/muparser.rb
  Formula/openrtsp.rb
  Formula/php.rb
  Formula/php@7.3.rb
  Formula/prometheus.rb
  Formula/simple-scan.rb
  Formula/swift-protobuf.rb
  Formula/vgmstream.rb
Labels: merge

#20723 Merge 2020-07-12 ce89a42ade
  Formula/broot.rb
  Formula/conan.rb
  Formula/dnstwist.rb
  Formula/ultralist.rb
Labels: merge

#20726 Merge 2020-07-12 3b1b34153e
  Formula/apollo-cli.rb
  Formula/bluepill.rb
  Formula/citus.rb
  Formula/console_bridge.rb
  Formula/dvc.rb
  Formula/libcec.rb
  Formula/logrotate.rb
  Formula/micronaut.rb
  Formula/newrelic-cli.rb
  Formula/tbb.rb
  Formula/terraform-ls.rb
  Formula/traefik.rb
  Formula/vroom.rb
Labels: merge

#20727 Merge 2020-07-12 58901749f9
  Formula/jc.rb
  Formula/leiningen.rb
  Formula/re-flex.rb
  Formula/so.rb
  Formula/xmrig.rb
Labels: merge

#20728 Merge 2020-07-12 105b253314
  Formula/audacious.rb
  Formula/cheat.rb
  Formula/dosbox-x.rb
  Formula/fping.rb
  Formula/gau.rb
  Formula/git-delta.rb
  Formula/git-hooks-go.rb
  Formula/glslviewer.rb
  Formula/graphviz.rb
  Formula/kde-extra-cmake-modules.rb
  Formula/kde-karchive.rb
  Formula/kde-kdoctools.rb
  Formula/kde-ki18n.rb
  Formula/kde-threadweaver.rb
  Formula/libsndfile.rb
  Formula/notmuch.rb
  Formula/osi.rb
  Formula/pueue.rb
  Formula/pwntools.rb
  Formula/redis.rb
  Formula/sbt.rb
  Formula/siege.rb
  Formula/tbb.rb
  Formula/verilator.rb
Labels: merge

#20729 Merge 2020-07-12 f424a48d97
  Formula/bash.rb
  Formula/bloaty.rb
  Formula/bmake.rb
  Formula/dnsdist.rb
  Formula/exploitdb.rb
  Formula/ffmpeg.rb
  Formula/fribidi.rb
  Formula/glib.rb
  Formula/gtk-gnutella.rb
  Formula/gwenhywfar.rb
  Formula/jc.rb
  Formula/kettle.rb
  Formula/libevent.rb
  Formula/libzip.rb
  Formula/minio-mc.rb
  Formula/minio.rb
  Formula/mutt.rb
  Formula/operator-sdk.rb
  Formula/pandoc-citeproc.rb
  Formula/pandoc-crossref.rb
  Formula/pandoc-include-code.rb
  Formula/pandoc.rb
  Formula/pnpm.rb
  Formula/poppler.rb
  Formula/ppl.rb
  Formula/re2.rb
  Formula/ser2net.rb
Labels: merge

#20733 Merge 2020-07-12 c75af86de4
  Formula/trailscraper.rb
Labels: merge

#20735 Merge 2020-07-13 1212dab64e
  Aliases/elasticsearch@7.8
  Aliases/kibana@7.8
  Formula/antibody.rb
  Formula/arrayfire.rb
  Formula/benthos.rb
  Formula/catch2.rb
  Formula/cubejs-cli.rb
  Formula/dhall-bash.rb
  Formula/dhall-json.rb
  Formula/dhall-lsp-server.rb
  Formula/dhall-yaml.rb
  Formula/dhall.rb
  Formula/dialog.rb
  Formula/dmagnetic.rb
  Formula/dvc.rb
  Formula/elasticsearch.rb
  Formula/fruit.rb
  Formula/gnunet.rb
  Formula/keydb.rb
  Formula/kibana.rb
  Formula/lazygit.rb
  Formula/meson.rb
  Formula/ppsspp.rb
  Formula/sshuttle.rb
  Formula/swiftformat.rb
  Formula/wtfutil.rb
Labels: merge

#20737 Merge 2020-07-13 e0150beaa3
  Formula/bit.rb
  Formula/cargo-c.rb
  Formula/dislocker.rb
  Formula/folly.rb
  Formula/gitlab-gem.rb
  Formula/hashlink.rb
  Formula/haxe.rb
  Formula/kubeless.rb
  Formula/libcec.rb
  Formula/luabind.rb
  Formula/mbedtls.rb
  Formula/mingw-w64.rb
  Formula/neko.rb
  Formula/ortp.rb
  Formula/rust-analyzer.rb
  Formula/shadowsocks-libev.rb
  Formula/sile.rb
  Formula/subversion@1.8.rb
  Formula/tomee-jax-rs.rb
  Formula/vulkan-headers.rb
  Formula/wartremover.rb
  Formula/zabbix.rb
  formula_renames.json
Labels: merge

#20739 Merge 2020-07-14 d3c0ef3679
  Formula/ascii.rb
  Formula/deheader.rb
  Formula/greed.rb
  Formula/opusfile.rb
  Formula/ski.rb
  Formula/src.rb
  Formula/topgrade.rb
Labels: merge

#20740 Merge 2020-07-14 f399467a032
  Formula/apollo-cli.rb
  Formula/autocode.rb
  Formula/bit.rb
  Formula/fauna-shell.rb
  Formula/glib.rb
  Formula/grpcurl.rb
  Formula/grunt-cli.rb
  Formula/iozone.rb
  Formula/joplin.rb
  Formula/libspng.rb
  Formula/now-cli.rb
  Formula/nsd.rb
  Formula/passenger.rb
  Formula/pgrouting.rb
  Formula/react-native-cli.rb
  Formula/triton.rb
  Formula/ultralist.rb
  Formula/velero.rb
Labels: merge

#20743 Merge 2020-07-15 598f682f284
  Aliases/v8@8.4
  Formula/annie.rb
  Formula/aom.rb
  Formula/aqbanking.rb
  Formula/babel.rb
  Formula/basex.rb
  Formula/bazel.rb
  Formula/curaengine.rb
  Formula/exploitdb.rb
  Formula/fortio.rb
  Formula/futhark.rb
  Formula/gdbgui.rb
  Formula/iblinter.rb
  Formula/jupyterlab.rb
  Formula/kepubify.rb
  Formula/kubeaudit.rb
  Formula/lazygit.rb
  Formula/libtomcrypt.rb
  Formula/minidlna.rb
  Formula/molecule.rb
  Formula/monolith.rb
  Formula/neo4j.rb
  Formula/openstackclient.rb
  Formula/osmosis.rb
  Formula/proguard.rb
  Formula/proteinortho.rb
  Formula/skaffold.rb
  Formula/sonarqube.rb
  Formula/suite-sparse.rb
  Formula/tox.rb
  Formula/v8.rb
  Formula/vapor.rb
  Formula/whistle.rb
Labels: merge

#20747 Merge 2020-07-16 421160c2c1
  Formula/abcmidi.rb
  Formula/angular-cli.rb
  Formula/balena-cli.rb
  Formula/bind.rb
  Formula/ckan.rb
  Formula/cromwell.rb
  Formula/exploitdb.rb
  Formula/flank.rb
  Formula/fontconfig.rb
  Formula/fwup.rb
  Formula/gleam.rb
  Formula/glooctl.rb
  Formula/go.rb
  Formula/godep.rb
  Formula/grails.rb
  Formula/jenkins-lts.rb
  Formula/jenkins.rb
  Formula/jenv.rb
  Formula/kona.rb
  Formula/kubernetes-cli.rb
  Formula/lc0.rb
  Formula/libgr.rb
  Formula/libzip.rb
  Formula/pushpin.rb
  Formula/python@3.8.rb
  Formula/qd.rb
  Formula/serverless.rb
  Formula/siege.rb
  Formula/syncthing.rb
  Formula/traefik@1.rb
  Formula/yaegi.rb
  Formula/yamllint.rb
Labels: merge

#20750 Merge 2020-07-16 cb4aae6cfd
  Formula/aliyun-cli.rb
  Formula/ask-cli.rb
  Formula/astrometry-net.rb
  Formula/awscli.rb
  Formula/azure-cli.rb
  Formula/b2-tools.rb
  Formula/cfn-lint.rb
  Formula/clojure.rb
  Formula/cobalt.rb
  Formula/convox.rb
  Formula/dolt.rb
  Formula/firebase-cli.rb
  Formula/fluxctl.rb
  Formula/glslviewer.rb
  Formula/go@1.13.rb
  Formula/hadoop.rb
  Formula/helmfile.rb
  Formula/ios-sim.rb
  Formula/jansson.rb
  Formula/k6.rb
  Formula/kustomize.rb
  Formula/marked.rb
  Formula/mu.rb
  Formula/ncmpcpp.rb
  Formula/po4a.rb
  Formula/profanity.rb
  Formula/radare2.rb
  Formula/recoverjpeg.rb
  Formula/rhash.rb
  Formula/seal.rb
  Formula/sops.rb
  Formula/sslh.rb
  Formula/tbox.rb
  Formula/termius.rb
  Formula/tflint.rb
  Formula/tox.rb
  Formula/util-linux.rb
Labels: merge

#20752 Merge 2020-07-16 1c6836c0d8
  Formula/cadence.rb
  Formula/croaring.rb
  Formula/howdoi.rb
  Formula/juju.rb
  Formula/libfabric.rb
  Formula/libsndfile.rb
  Formula/naabu.rb
  Formula/ncview.rb
  Formula/opentsdb.rb
  Formula/overmind.rb
  Formula/pandoc.rb
  Formula/python@3.8.rb
  Formula/serverless.rb
  Formula/subfinder.rb
  Formula/vcpkg.rb
Labels: merge

#20753 Merge 2020-07-17 67dd6997f5
  Formula/apollo-cli.rb
  Formula/circleci.rb
  Formula/composer.rb
  Formula/devspace.rb
  Formula/exploitdb.rb
  Formula/gnuplot.rb
  Formula/ideviceinstaller.rb
  Formula/kubie.rb
  Formula/lynx.rb
  Formula/opa.rb
  Formula/terraform-ls.rb
  Formula/typescript.rb
  Formula/wabt.rb
  Formula/yamllint.rb
Labels: merge

#20754 Merge 2020-07-17 85bf81a9a2
  Formula/astrometry-net.rb
  Formula/awscli.rb
  Formula/broot.rb
  Formula/charm-tools.rb
  Formula/cloudformation-cli.rb
  Formula/conjure-up.rb
  Formula/curseofwar.rb
  Formula/dvc.rb
  Formula/etcd.rb
  Formula/fluent-bit.rb
  Formula/glslviewer.rb
  Formula/gpgme.rb
  Formula/grafana.rb
  Formula/helmfile.rb
  Formula/lunchy-go.rb
  Formula/lunchy.rb
  Formula/mpg123.rb
  Formula/rke.rb
  Formula/scamper.rb
  Formula/sile.rb
  Formula/whistle.rb
  Formula/xmrig.rb
Labels: merge

#20755 Merge 2020-07-18 4752b021a5
  Formula/apache-flink.rb
  Formula/cartridge-cli.rb
  Formula/cubejs-cli.rb
  Formula/dnsprobe.rb
  Formula/exploitdb.rb
  Formula/flyway.rb
  Formula/fswatch.rb
  Formula/gdbgui.rb
  Formula/geph2.rb
  Formula/hugo.rb
  Formula/ideviceinstaller.rb
  Formula/jenkins-job-builder.rb
  Formula/just.rb
  Formula/liquidprompt.rb
  Formula/minikube.rb
  Formula/mysql-client.rb
  Formula/mysql.rb
  Formula/mysql@5.7.rb
  Formula/octant.rb
  Formula/traefik.rb
  Formula/wpscan.rb
Labels: merge

#20757 fswatch: Fix bottling for Linuxbrew
  Formula/fswatch.rb
Labels: cellar failure

#20758 Merge 2020-07-18 5647ed415f
  Formula/armadillo.rb
  Formula/aws-cdk.rb
  Formula/broot.rb
  Formula/bzt.rb
  Formula/carton.rb
  Formula/cassandra@2.1.rb
  Formula/cloudformation-cli.rb
  Formula/diffoscope.rb
  Formula/dwdiff.rb
  Formula/ensmallen.rb
  Formula/euler-py.rb
  Formula/exploitdb.rb
  Formula/fluent-bit.rb
  Formula/fortio.rb
  Formula/glslviewer.rb
  Formula/gr-osmosdr.rb
  Formula/grpc.rb
  Formula/imgproxy.rb
  Formula/inetutils.rb
  Formula/libffi.rb
  Formula/liquidctl.rb
  Formula/mlt.rb
  Formula/mmctl.rb
  Formula/nasm.rb
  Formula/nativefier.rb
  Formula/notmuch-mutt.rb
  Formula/pdnsrec.rb
  Formula/peco.rb
  Formula/qmmp.rb
  Formula/scons.rb
  Formula/spoof-mac.rb
  Formula/stone-soup.rb
  Formula/stormssh.rb
  Formula/tth.rb
  Formula/weechat.rb
  Formula/wla-dx.rb
  Formula/z.lua.rb
Labels: merge

#20759 Merge 2020-07-19 89aec1920a
  Formula/abcl.rb
  Formula/arangodb.rb
  Formula/clojure.rb
  Formula/duti.rb
  Formula/eslint.rb
  Formula/go@1.13.rb
  Formula/healpix.rb
  Formula/helmfile.rb
  Formula/imagemagick.rb
  Formula/imagemagick@6.rb
  Formula/jo.rb
  Formula/k3d.rb
  Formula/midnight-commander.rb
  Formula/radare2.rb
  Formula/simdjson.rb
  Formula/subfinder.rb
  Formula/tanka.rb
Labels: merge

#20760 Merge 2020-07-19 83d911bff6
  Formula/abyss.rb
  Formula/ack.rb
  Formula/adios2.rb
  Formula/adr-tools.rb
  Formula/afsctool.rb
  Formula/agda.rb
  Formula/aha.rb
  Formula/akka.rb
  Formula/allegro.rb
  Formula/amazon-ecs-cli.rb
  Formula/ammonite-repl.rb
  Formula/ampl-mp.rb
  Formula/angband.rb
  Formula/ansible@2.8.rb
  Formula/apngasm.rb
  Formula/apollo.rb
  Formula/appledoc.rb
  Formula/appscale-tools.rb
  Formula/arabica.rb
  Formula/arduino-cli.rb
  Formula/argon2.rb
  Formula/aria2.rb
  Formula/arpack.rb
  Formula/arx-libertatis.rb
  Formula/asciidoc.rb
  Formula/asciidoctor.rb
  Formula/asciiquarium.rb
  Formula/asio.rb
  Formula/asn1c.rb
  Formula/assimp.rb
  Formula/atf.rb
  Formula/atlantis.rb
  Formula/audacious.rb
  Formula/audiofile.rb
  Formula/auditbeat.rb
  Formula/augustus.rb
  Formula/aurora-cli.rb
  Formula/austin.rb
  Formula/autojump.rb
  Formula/avian.rb
  Formula/awk.rb
  Formula/aws-keychain.rb
  Formula/awscli.rb
  Formula/awscli@1.rb
  Formula/awslogs.rb
Labels: merge

#20761 Merge 2020-07-19 b513b0c6e9
  Formula/b2-tools.rb
  Formula/b2sum.rb
  Formula/b3sum.rb
  Formula/bagit.rb
  Formula/bam.rb
  Formula/bareos-client.rb
  Formula/bat.rb
  Formula/bats-core.rb
  Formula/bcftools.rb
  Formula/bcoin.rb
  Formula/bdw-gc.rb
  Formula/beagle.rb
  Formula/beansdb.rb
  Formula/beanstalkd.rb
  Formula/bee.rb
  Formula/befunge93.rb
  Formula/betty.rb
  Formula/bgpdump.rb
  Formula/bgpq3.rb
  Formula/bgrep.rb
  Formula/blast.rb
  Formula/blink1.rb
  Formula/blis.rb
  Formula/blitz.rb
  Formula/blueutil.rb
  Formula/bmon.rb
  Formula/bnfc.rb
  Formula/boost@1.55.rb
  Formula/boost@1.57.rb
  Formula/boost@1.59.rb
  Formula/boost@1.60.rb
  Formula/bork.rb
  Formula/brew-cask-completion.rb
  Formula/bsdconv.rb
  Formula/btpd.rb
  Formula/buildapp.rb
  Formula/buildifier.rb
  Formula/buildozer.rb
  Formula/bulk_extractor.rb
  Formula/bullet.rb
  Formula/bup.rb
  Formula/burp.rb
Labels: merge

#20772 Merge 2020-07-22 03be17df05
  Aliases/solr@8.6
  Formula/act.rb
  Formula/aliyun-cli.rb
  Formula/apache-flink.rb
  Formula/ask-cli.rb
  Formula/awscli.rb
  Formula/binaryen.rb
  Formula/closure-compiler.rb
  Formula/cortex.rb
  Formula/fennel.rb
  Formula/file-formula.rb
  Formula/helmfile.rb
  Formula/hy.rb
  Formula/jasper.rb
  Formula/kubeaudit.rb
  Formula/librdkafka.rb
  Formula/loki.rb
  Formula/minio.rb
  Formula/moarvm.rb
  Formula/nqp.rb
  Formula/nushell.rb
  Formula/ospray.rb
  Formula/pnpm.rb
  Formula/promtail.rb
  Formula/quantlib.rb
  Formula/qxmpp.rb
  Formula/rakudo.rb
  Formula/redis.rb
  Formula/rgbds.rb
  Formula/ship.rb
  Formula/solr.rb
  Formula/stress-ng.rb
  Formula/volta.rb
  Formula/wpscan.rb
Labels: merge

#20773 Merge 2020-07-22 7309ae3024
  Aliases/file
  Formula/argocd.rb
  Formula/charm-tools.rb
  Formula/easyengine.rb
  Formula/eksctl.rb
  Formula/emscripten.rb
  Formula/gettext.rb
  Formula/gnutls.rb
  Formula/harfbuzz.rb
  Formula/hashcat.rb
  Formula/jfrog-cli.rb
  Formula/libde265.rb
  Formula/libevent.rb
  Formula/libffi.rb
  Formula/libheif.rb
  Formula/libidn2.rb
  Formula/libksba.rb
  Formula/libomp.rb
  Formula/libosinfo.rb
  Formula/libsodium.rb
  Formula/libtasn1.rb
  Formula/libtool.rb
  Formula/lz4.rb
  Formula/maxima.rb
  Formula/mpw.rb
  Formula/ncurses.rb
  Formula/nettle.rb
  Formula/npth.rb
  Formula/openjpeg.rb
  Formula/p11-kit.rb
  Formula/pango.rb
  Formula/pass.rb
  Formula/pdftoipe.rb
  Formula/pinentry.rb
  Formula/poetry.rb
  Formula/pwgen.rb
  Formula/python@3.8.rb
  Formula/rsync.rb
  Formula/thanos.rb
  Formula/topgrade.rb
  Formula/unar.rb
  Formula/vulkan-headers.rb
  Formula/whistle.rb
  Formula/wxmac.rb
  Formula/wxmaxima.rb
  Formula/x265.rb
  Formula/xxhash.rb
  Formula/xz.rb
  Formula/zstd.rb
Labels: merge

#20774 Merge 2020-07-22 e8804de478
  Formula/aws-cdk.rb
  Formula/ccache.rb
  Formula/citus.rb
  Formula/convox.rb
  Formula/copilot.rb
  Formula/filebeat.rb
  Formula/findomain.rb
  Formula/flow.rb
  Formula/fork-cleaner.rb
  Formula/ghostscript.rb
  Formula/goad.rb
  Formula/grafana.rb
  Formula/groovy.rb
  Formula/groovysdk.rb
  Formula/jenkins.rb
  Formula/kafkacat.rb
  Formula/metabase.rb
  Formula/mill.rb
  Formula/mitmproxy.rb
  Formula/nifi-registry.rb
  Formula/rsnapshot.rb
  Formula/ruby-build.rb
  Formula/wabt.rb
Labels: merge

#20775 Merge 2020-07-23 acbc441d6a
  Formula/angular-cli.rb
  Formula/aspectj.rb
  Formula/aws-okta.rb
  Formula/buildifier.rb
  Formula/buildozer.rb
  Formula/check.rb
  Formula/clib.rb
  Formula/cmake.rb
  Formula/doctl.rb
  Formula/earthly.rb
  Formula/elasticsearch@6.rb
  Formula/ethereum.rb
  Formula/feedgnuplot.rb
  Formula/fortio.rb
  Formula/freerdp.rb
  Formula/frugal.rb
  Formula/gitlab-runner.rb
  Formula/goreleaser.rb
  Formula/grin.rb
  Formula/hasura-cli.rb
  Formula/haxe.rb
  Formula/igv.rb
  Formula/imgproxy.rb
  Formula/jsdoc3.rb
  Formula/kibana@6.rb
  Formula/libfabric.rb
  Formula/libupnp.rb
  Formula/mpd.rb
  Formula/nettle.rb
  Formula/node@10.rb
  Formula/numpy.rb
  Formula/oha.rb
  Formula/onscripter.rb
  Formula/openjdk@11.rb
  Formula/pipgrip.rb
  Formula/pueue.rb
  Formula/pulumi.rb
  Formula/pumba.rb
  Formula/pyenv.rb
  Formula/reorder-python-imports.rb
  Formula/ruby-install.rb
  Formula/semtag.rb
  Formula/sflowtool.rb
  Formula/slacknimate.rb
  Formula/terraform.rb
Labels: merge

#20776 Merge 2020-07-23 0c93a11e24
  Formula/dscanner.rb
Labels: merge

#20780 glibc: Fix: cannot open locale definition file `C'
  Formula/glibc.rb
Labels: bug

#20782 Merge 2020-07-24 848c904f28
  Formula/argo.rb
  Formula/aws-sdk-cpp.rb
  Formula/awscli@1.rb
  Formula/dav1d.rb
  Formula/erlang@21.rb
  Formula/flyway.rb
  Formula/janet.rb
  Formula/lc0.rb
  Formula/libvmaf.rb
  Formula/patchutils.rb
  Formula/pnpm.rb
  Formula/prometheus.rb
  Formula/re2c.rb
  Formula/scrcpy.rb
  Formula/vcpkg.rb
Labels: merge

#20783 Merge 2020-07-24 1bede6d4f6
  Formula/borgmatic.rb
Labels: merge

#20786 Merge 2020-07-25 ef1b9bc5c9
  Formula/clamav.rb
  Formula/dfmt.rb
  Formula/duckdb.rb
  Formula/findomain.rb
  Formula/hugo.rb
  Formula/k9s.rb
  Formula/picard-tools.rb
  Formula/tox.rb
  Formula/yubico-piv-tool.rb
Labels: merge

#20787 Merge 2020-07-25 9900f97af6
  Formula/cassandra-cpp-driver.rb
  Formula/dcd.rb
  Formula/exploitdb.rb
  Formula/flint.rb
  Formula/flow.rb
  Formula/fortio.rb
  Formula/gradle.rb
  Formula/helmfile.rb
  Formula/ldpl.rb
  Formula/mesa.rb
  Formula/ocrmypdf.rb
  Formula/ory-hydra.rb
  Formula/scs.rb
  Formula/semgrep.rb
  Formula/terraform-ls.rb
Labels: merge

#20790 Merge 2020-07-25 b5a65a4b3ce
  Aliases/bison@3.7
  Formula/apibuilder-cli.rb
  Formula/bison.rb
  Formula/comby.rb
  Formula/dgraph.rb
  Formula/geoserver.rb
  Formula/libaacs.rb
  Formula/nomad.rb
  Formula/nspr.rb
  Formula/serverless.rb
Labels: merge

#20791 Merge 2020-07-25 67f66e3aac
  Formula/configen.rb
  Formula/earthly.rb
  Formula/ffuf.rb
  Formula/glooctl.rb
  Formula/k9s.rb
  Formula/mockserver.rb
  Formula/pandoc.rb
  Formula/parallel.rb
  Formula/rust-analyzer.rb
  Formula/scipy.rb
Labels: merge

#20794 Merge 2020-07-25 71ca93ea1d
  Formula/awscli.rb
  Formula/byteman.rb
  Formula/clang-format.rb
  Formula/clojure.rb
  Formula/erlang@22.rb
  Formula/gateway-go.rb
  Formula/ghq.rb
  Formula/git-annex.rb
  Formula/gnu-getopt.rb
  Formula/hadolint.rb
  Formula/haproxy.rb
  Formula/jdupes.rb
  Formula/libidn.rb
  Formula/llvm.rb
  Formula/node.rb
  Formula/proftpd.rb
  Formula/subfinder.rb
  Formula/util-linux.rb
Labels: merge

#20800 Merge 2020-07-26 7244ef5325
  Formula/chalk-cli.rb
  Formula/duckscript.rb
  Formula/exploitdb.rb
  Formula/flarectl.rb
  Formula/functionalplus.rb
  Formula/futhark.rb
  Formula/hlint.rb
  Formula/logcli.rb
  Formula/node@12.rb
  Formula/pandoc.rb
  Formula/sile.rb
  Formula/telegraf.rb
  Formula/widelands.rb
Labels: merge

#20796 libidn: fix bottling for Linuxbrew
  Formula/libidn.rb
Labels: cellar failure

#20805 Merge 2020-07-27 e8c1e6b959d
  Formula/arm-linux-gnueabihf-binutils.rb
  Formula/caf.rb
  Formula/fastlane.rb
  Formula/serf.rb
  Formula/x86_64-elf-binutils.rb
Labels: merge

#20806 Merge 2020-07-27 b34bf8854b3
  Formula/binutils.rb
Labels: merge

#20807 Merge 2020-07-27 4cf51f46b6b
  Formula/aws-okta.rb
  Formula/convox.rb
  Formula/crowdin.rb
  Formula/deno.rb
  Formula/diffoscope.rb
  Formula/duckscript.rb
  Formula/fastlane.rb
  Formula/golangci-lint.rb
  Formula/gradle-profiler.rb
  Formula/grafana.rb
  Formula/h3.rb
  Formula/healpix.rb
  Formula/htslib.rb
  Formula/jenkins.rb
  Formula/kamel.rb
  Formula/kubeprod.rb
  Formula/libgr.rb
  Formula/nef.rb
  Formula/newrelic-cli.rb
  Formula/nss.rb
  Formula/openrtsp.rb
  Formula/paket.rb
  Formula/sonobuoy.rb
  Formula/spotify-tui.rb
  Formula/tektoncd-cli.rb
  Formula/webpack.rb
  Formula/wgcf.rb
  Formula/zim.rb
Labels: merge

#20808 Merge 2020-07-27 f33f8ccb5a7
  Formula/adios2.rb
  Formula/appstream-glib.rb
  Formula/argo.rb
  Formula/caffe.rb
  Formula/cbmc.rb
  Formula/citus.rb
  Formula/clib.rb
  Formula/conjure-up.rb
  Formula/etcd.rb
  Formula/fluent-bit.rb
  Formula/geocode-glib.rb
  Formula/gitg.rb
  Formula/gitleaks.rb
  Formula/gitless.rb
  Formula/gnome-recipes.rb
  Formula/gofish.rb
  Formula/gsoap.rb
  Formula/gssdp.rb
  Formula/gtranslator.rb
  Formula/gupnp-tools.rb
  Formula/gupnp.rb
  Formula/hashpump.rb
  Formula/homebank.rb
  Formula/i686-elf-binutils.rb
  Formula/include-what-you-use.rb
  Formula/ios-deploy.rb
  Formula/john-jumbo.rb
  Formula/komposition.rb
  Formula/libchamplain.rb
  Formula/libgdata.rb
  Formula/libgweather.rb
  Formula/libhttpseverywhere.rb
  Formula/libosinfo.rb
  Formula/libpsl.rb
  Formula/librest.rb
  Formula/libsoup.rb
  Formula/minio.rb
  Formula/mtr.rb
  Formula/nyancat.rb
  Formula/ooniprobe.rb
  Formula/osm-gps-map.rb
  Formula/paket.rb
  Formula/pinentry-mac.rb
  Formula/pueue.rb
  Formula/scalapack.rb
  Formula/telegram-cli.rb
  Formula/terraformer.rb
Labels: merge

#20809 Merge 2020-07-27 178ebf1afc6
  Formula/alexjs.rb
  Formula/ansible.rb
  Formula/assimp.rb
  Formula/bde.rb
  Formula/c-blosc.rb
  Formula/cassandra.rb
  Formula/cassandra@2.2.rb
  Formula/coq.rb
  Formula/ctl.rb
  Formula/dark-mode.rb
  Formula/ddgr.rb
  Formula/erlang.rb
  Formula/fping.rb
  Formula/gitbucket.rb
  Formula/gitleaks.rb
  Formula/hmmer.rb
  Formula/janet.rb
  Formula/jfrog-cli.rb
  Formula/lanraragi.rb
  Formula/lf.rb
  Formula/libcapn.rb
  Formula/libosinfo.rb
  Formula/math-comp.rb
  Formula/mu.rb
  Formula/mycli.rb
  Formula/n.rb
  Formula/nvc.rb
  Formula/opencv@2.rb
  Formula/pgbadger.rb
  Formula/pipgrip.rb
  Formula/pmd.rb
  Formula/pnpm.rb
  Formula/rdiff-backup.rb
  Formula/saltwater.rb
  Formula/snapcraft.rb
  Formula/telegraf.rb
  Formula/yj.rb
Labels: merge

#20813 Merge 2020-07-28 670cc03a2d7
  Formula/beast.rb
  Formula/choose-gui.rb
Labels: merge

#20814 Merge 2020-07-28 07ac6989dda
  Formula/folly.rb
  Formula/ios-deploy.rb
Labels: merge

#20815 Merge 2020-07-28 bce24ff945d
  Formula/launch.rb
  Formula/mogenerator.rb
  Formula/mono.rb
  Formula/mpv.rb
Labels: merge

#20816 Merge 2020-07-28 462fe34d307
  Formula/percona-toolkit.rb
  Formula/rubberband.rb
  Formula/scrollkeeper.rb
  Formula/spaceinvaders-go.rb
  Formula/squashfs.rb
  Formula/stress-ng.rb
  Formula/tasksh.rb
  Formula/termius.rb
Labels: merge

#20817 Merge 2020-07-28 d679ed56f8b
  Formula/fontforge.rb
  Formula/gitg.rb
  Formula/jsoncpp.rb
  Formula/kafkacat.rb
  Formula/kapacitor.rb
  Formula/katago.rb
  Formula/kcov.rb
  Formula/keepassc.rb
  Formula/kerl.rb
  Formula/keystone.rb
  Formula/kibana@6.rb
  Formula/kitchen-completion.rb
  Formula/kotlin.rb
  Formula/kqwait.rb
  Formula/kvazaar.rb
  Formula/kytea.rb
  Formula/monetdb.rb
  Formula/ngs.rb
Labels: merge

#20818 Merge 2020-07-28 43d95f9846b
  .github/workflows/scheduled.yml
Labels: merge

#20820 Merge 2020-07-28 d2a8542b16d
  Formula/aws-google-auth.rb
  Formula/reg.rb
Labels: merge

#20821 Merge 2020-07-28 05b733aea2c
  .github/workflows/autocancel.yml
  .github/workflows/autolabel.yml
  .github/workflows/autopublish.yml
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20823 Merge 2020-07-28 e826a84a475
  Formula/chart-testing.rb
  Formula/serverless.rb
Labels: merge

#20837 Merge 2020-07-28 d36f75979dd
  .github/workflows/autolabel.yml
Labels: merge

#20838 Merge 2020-07-28 0688c059588
  Formula/doxygen.rb
  Formula/jsonnet-bundler.rb
Labels: merge

#20839 Merge 2020-07-28 8f0331d2b9e
  .github/workflows/publish-commit-bottles.yml
Labels: merge

#20840 Merge 2020-07-28 8a79e1bf57a
  Formula/azcopy.rb
  Formula/broot.rb
  Formula/buildkit.rb
  Formula/cargo-c.rb
  Formula/citus.rb
  Formula/ethereum.rb
  Formula/exploitdb.rb
  Formula/fcitx-remote-for-osx.rb
  Formula/gpsbabel.rb
  Formula/hbase.rb
  Formula/homesick-completion.rb
  Formula/jenkins.rb
  Formula/nanomsg.rb
  Formula/narwhal.rb
  Formula/nasm.rb
  Formula/nco.rb
  Formula/ncompress.rb
  Formula/ncrack.rb
  Formula/ndenv.rb
  Formula/nef.rb
  Formula/neko.rb
  Formula/neo4j.rb
  Formula/neovim.rb
  Formula/nesc.rb
  Formula/nethacked.rb
  Formula/netperf.rb
  Formula/newt.rb
  Formula/nfdump.rb
  Formula/nghttp2.rb
  Formula/nim.rb
  Formula/nlopt.rb
  Formula/nmap.rb
  Formula/node.rb
  Formula/nodeenv.rb
  Formula/norm.rb
  Formula/nq.rb
  Formula/nqp.rb
  Formula/nut.rb
  Formula/nwchem.rb
  Formula/nyancat.rb
  Formula/nylon.rb
  Formula/serverless.rb
  Formula/shml.rb
  Formula/singular.rb
  Formula/teleport.rb
  Formula/wagyu.rb
  Formula/xtensor.rb
Labels: merge

#20845 Merge 2020-07-29 553f751f5dd
  Formula/alure.rb
  Formula/appscale-tools.rb
  Formula/audiofile.rb
  Formula/bento4.rb
  Formula/blast.rb
  Formula/certbot.rb
  Formula/cloc.rb
  Formula/creduce.rb
  Formula/deheader.rb
  Formula/fontconfig.rb
  Formula/freerdp.rb
  Formula/gdal.rb
  Formula/objc-codegenutils.rb
  Formula/ocaml-num.rb
  Formula/ocaml.rb
  Formula/ocamlbuild.rb
  Formula/oclgrind.rb
  Formula/ocproxy.rb
  Formula/octave.rb
  Formula/octomap.rb
  Formula/odpi.rb
  Formula/odt2txt.rb
  Formula/offlineimap.rb
  Formula/oil.rb
  Formula/ola.rb
  Formula/olsrd.rb
  Formula/ompl.rb
  Formula/one-ml.rb
  Formula/onetime.rb
  Formula/oniguruma.rb
  Formula/ooniprobe.rb
  Formula/opam.rb
  Formula/open-mpi.rb
  Formula/openal-soft.rb
  Formula/openclonk.rb
  Formula/opencv.rb
  Formula/opencv@2.rb
  Formula/opencv@3.rb
  Formula/opendetex.rb
  Formula/openfortivpn.rb
  Formula/openimageio.rb
  Formula/openmsx.rb
  Formula/openslide.rb
  Formula/orocos-kdl.rb
  Formula/osm2pgrouting.rb
  Formula/osmium-tool.rb
  Formula/osmosis.rb
  Formula/osquery.rb
  Formula/osslsigncode.rb
  Formula/ott.rb
  Formula/owfs.rb
Labels: merge

#20846 Merge 2020-07-29 c12850fa2b1
  .github/workflows/autolabel.yml
  Formula/libtensorflow.rb
  Formula/metricbeat.rb
  Formula/sdns.rb
  Formula/traefik.rb
  Formula/traefik@1.rb
  Formula/vsts-cli.rb
Labels: merge

#20847 Merge 2020-07-29 703d088aa48
  .github/workflows/publish-commit-bottles.yml
  Formula/checkstyle.rb
  Formula/docfx.rb
  Formula/kubeseal.rb
  Formula/logstash.rb
Labels: merge

#20848 Merge 2020-07-29 34f30ced0b1
  Aliases/boost@1.73
  Formula/adios2.rb
  Formula/avro-cpp.rb
  Formula/bitcoin.rb
  Formula/boost-bcp.rb
  Formula/boost-mpi.rb
  Formula/boost-python.rb
  Formula/boost-python3.rb
  Formula/boost.rb
  Formula/cucumber-cpp.rb
  Formula/freeling.rb
  Formula/gnuradio.rb
  Formula/jenkins-lts.rb
  Formula/ledger.rb
  Formula/lgogdownloader.rb
  Formula/libbitcoin-client.rb
  Formula/libbitcoin-explorer.rb
  Formula/libbitcoin-protocol.rb
  Formula/libbitcoin-server.rb
  Formula/libbitcoin.rb
  Formula/libpulsar.rb
  Formula/monero.rb
  Formula/ncmpcpp.rb
  Formula/openimageio.rb
  Formula/source-highlight.rb
  Formula/widelands.rb
Labels: merge

#20857 Merge 2020-07-31 516fdfa3cf7
  Formula/awscli.rb
  Formula/folly.rb
  Formula/git-plus.rb
  Formula/gpp.rb
Labels: merge

#20858 Merge 2020-07-31 42bafef0f5
  .github/workflows/autopublish.yml
  .github/workflows/publish-commit-bottles.yml
  Formula/atool.rb
  Formula/aws-cdk.rb
  Formula/gdbm.rb
  Formula/gnuradio.rb
  Formula/gopass.rb
  Formula/jsonnet-bundler.rb
  Formula/mlpack.rb
  Formula/oci-cli.rb
  Formula/oha.rb
  Formula/pre-commit.rb
Labels: merge

#20859 Merge 2020-07-31 d5a95bc30b2
  Aliases/brz.rb
  Formula/abcmidi.rb
  Formula/aws-cdk.rb
  Formula/cobalt.rb
  Formula/consul-template.rb
  Formula/dmagnetic.rb
  Formula/docker-slim.rb
  Formula/dune.rb
  Formula/elasticsearch@6.rb
  Formula/eprover.rb
  Formula/flyway.rb
  Formula/fortio.rb
  Formula/glib.rb
  Formula/gpsbabel.rb
  Formula/hashcat.rb
  Formula/hcxtools.rb
  Formula/hydra.rb
  Formula/inxi.rb
  Formula/kapacitor.rb
  Formula/kibana@6.rb
  Formula/kubeprod.rb
  Formula/leptonica.rb
  Formula/libqalculate.rb
  Formula/libtorch.rb
  Formula/logtalk.rb
  Formula/mavsdk.rb
  Formula/nlohmann-json.rb
  Formula/operator-sdk.rb
  Formula/pnpm.rb
  Formula/prest.rb
  Formula/qalculate-gtk.rb
  Formula/sonarqube-lts.rb
  Formula/spdlog.rb
  Formula/stress-ng.rb
  Formula/swagger-codegen@2.rb
  Formula/volta.rb
  Formula/wtf.rb
  Formula/zeek.rb
Labels: merge
